window.GUESS_WHAT_CARDS = [
  { id: "sky", level: "basic", topic: "In the sky", words: ["clouds", "birds", "the sun", "the moon", "airplanes", "rainbow"] },
  { id: "zoo-basic", level: "basic", topic: "At the zoo", words: ["lions", "elephants", "monkeys", "zebras", "cages", "bears"] },
  { id: "classroom", level: "basic", topic: "In the classroom", words: ["teacher", "students", "chairs", "books", "chalkboard", "desks"] },
  { id: "sea-basic", level: "basic", topic: "In the sea", words: ["water", "salt", "fish", "boats", "islands", "sharks"] },
  { id: "beach", level: "basic", topic: "At the beach", words: ["sand", "seashells", "umbrellas", "towels", "bathing suits", "waves"] },
  { id: "movie-theater", level: "basic", topic: "At the movie theater", words: ["tickets", "seats", "screens", "popcorn", "lobby", "projectors"] },
  { id: "city", level: "basic", topic: "In a city", words: ["buildings", "shops", "people", "streets", "traffic", "cars"] },
  { id: "kitchen", level: "basic", topic: "In the kitchen", words: ["refrigerator", "plates", "stove", "food", "table", "sink"] },
  { id: "grocery-store", level: "basic", topic: "In a grocery store", words: ["fruit", "meat", "milk", "vegetables", "aisles", "cashiers"] },
  { id: "department-store", level: "basic", topic: "In a department store", words: ["clothing", "electronics", "shoes", "toys", "furniture", "tools"] },
  { id: "house", level: "basic", topic: "In a house", words: ["doors", "kitchen", "bedrooms", "floors", "bathrooms", "walls"] },
  { id: "desert", level: "basic", topic: "In the desert", words: ["camels", "cactus", "sand", "snakes", "oasis", "pyramids"] },
  { id: "yellow", level: "basic", topic: "Things that are yellow", words: ["the sun", "banana", "lemon", "corn", "egg yolk", "butter"] },
  { id: "hotel", level: "basic", topic: "In a hotel", words: ["front desk", "beds", "elevator", "lobby", "restaurant", "housekeeping"] },
  { id: "red", level: "basic", topic: "Things that are red", words: ["apples", "tomatoes", "stop sign", "roses", "blood", "strawberries"] },
  { id: "cold", level: "basic", topic: "Things that are cold", words: ["ice cube", "snow", "ice cream", "winter", "Antarctica", "refrigerator"] },
  { id: "bookstore", level: "basic", topic: "At the bookstore", words: ["books", "CDs", "magazines", "cashier", "shelves", "newspapers"] },
  { id: "big", level: "basic", topic: "Things that are big", words: ["elephants", "whales", "skyscrapers", "airplanes", "the world", "oceans"] },
  { id: "pet-store", level: "basic", topic: "In a pet store", words: ["puppies", "kittens", "fish", "cages", "birds", "pet food"] },
  { id: "restaurant", level: "basic", topic: "At a restaurant", words: ["servers", "menus", "tables", "food", "plates", "chefs"] },
  { id: "breakfast", level: "basic", topic: "At breakfast", words: ["juice", "cereal", "milk", "eggs", "toast", "coffee"] },
  { id: "wear", level: "basic", topic: "Things that you wear", words: ["shirts", "jeans", "coats", "glasses", "shoes", "hats"] },
  { id: "jobs", level: "basic", topic: "Jobs", words: ["teacher", "doctor", "dentist", "police officer", "firefighter", "mechanic"] },
  { id: "round", level: "basic", topic: "Things that are round", words: ["the moon", "clocks", "the Earth", "oranges", "balls", "heads"] },

  { id: "zoo-challenge", level: "challenge", topic: "At the zoo", words: ["kangaroos", "hyenas", "lizards", "eagles", "polar bears", "orangutans"] },
  { id: "sea-challenge", level: "challenge", topic: "In the sea", words: ["dolphins", "submarines", "scuba divers", "coral", "seaweed (kelp)", "octopuses"] },
  { id: "night", level: "challenge", topic: "At night", words: ["sleep", "stars", "the moon", "crickets", "dreams", "darkness"] },
  { id: "save", level: "challenge", topic: "Things you save", words: ["letters", "money", "pictures", "time", "energy", "souvenirs"] },
  { id: "city-street", level: "challenge", topic: "Along a city street", words: ["sidewalks", "signs", "street lights", "trees", "parking spaces", "trash cans"] },
  { id: "space", level: "challenge", topic: "In space", words: ["stars", "planets", "the moon", "the sun", "satellites", "meteors"] },
  { id: "television", level: "challenge", topic: "On TV", words: ["sports", "movies", "shows", "news", "commercials", "cartoons"] },
  { id: "wall", level: "challenge", topic: "On the wall", words: ["calendars", "maps", "photographs", "light switches", "clocks", "mirrors"] },
  { id: "america", level: "challenge", topic: "In America", words: ["baseball", "the White House", "the Grand Canyon", "Thanksgiving", "New York City", "states"] },
  { id: "break", level: "challenge", topic: "Things that break", words: ["glasses", "hearts", "records", "plates", "bones", "promises"] },
  { id: "airport", level: "challenge", topic: "At the airport", words: ["airplanes", "tickets", "customs", "security", "baggage claim", "passport"] },
  { id: "wood", level: "challenge", topic: "Things made of wood", words: ["pencils", "tables", "houses", "guitars", "fences", "canoes"] },
  { id: "gym", level: "challenge", topic: "At the gym", words: ["yoga", "locker room", "treadmill", "swimming pool", "weight room", "sauna"] },
  { id: "book", level: "challenge", topic: "Things in a book", words: ["chapters", "table of contents", "paragraphs", "pages", "pictures", "words"] },
  { id: "doctor", level: "challenge", topic: "At the doctor", words: ["waiting room", "nurses", "patients", "thermometers", "medicine", "vaccinations"] },
  { id: "outdoor", level: "challenge", topic: "Outdoor activities", words: ["running", "gardening", "biking", "skiing", "fishing", "sailing"] },
  { id: "instruments", level: "challenge", topic: "Musical instruments", words: ["guitars", "pianos", "drums", "violins", "trumpets", "saxophones"] },
  { id: "climb", level: "challenge", topic: "Things that you climb", words: ["ladders", "mountains", "trees", "stairs", "ropes", "rock walls"] },
  { id: "pairs", level: "challenge", topic: "Things that come in pairs", words: ["eyes", "shoes", "twins", "earrings", "glasses", "scissors"] },
  { id: "subjects", level: "challenge", topic: "Subjects you study", words: ["math", "biology", "English", "history", "geography", "economics"] },
  { id: "make", level: "challenge", topic: "Things you can make", words: ["plans", "decisions", "phone calls", "money", "beds", "mistakes"] },
  { id: "play", level: "challenge", topic: "Things that you play", words: ["musical instruments", "sports", "video games", "board games", "card games", "songs"] },
  { id: "grow", level: "challenge", topic: "Things that grow", words: ["children", "flowers", "economies", "populations", "hair", "vegetables"] },
  { id: "car", level: "challenge", topic: "Parts of a car", words: ["steering wheel", "brakes", "trunk", "engine", "windshield", "tires"] }
];
