const HINGSHA_STORY = {
  id: "hingsha",
  title: "Hingsha",
  titleBn: "হিংসা",
  kicker: "A Bengali Muslim folk tale",
  sourceNote: "A contextual retelling of ATU 1331",
  contentNote: "This folktale includes non-graphic blindness.",
  audio: "audio/hingsha-story.mp3",
  tts: {
    model: "Gemini 3.8 Flash TTS",
    voice: "Gacrux",
    direction: "An older Bangladeshi Muslim male storyteller speaking clear natural English with a light Bengali accent. Warm oral-folktale rhythm, calm and intimate. Give Jalal a tense, increasingly bitter tone and Pir Sahib a gentle, grave tone, while remaining one narrator. Pronounce Jalal as ja-LAAL, Hamid as HAA-mid with a soft h, and Pir Sahib as peer SHA-heb."
  },
  frames: [
    { src: "assets/frames/01.webp", alt: "Jalal and Hamid walk through their riverside village while Jalal watches Hamid closely." },
    { src: "assets/frames/02.webp", alt: "Jalal watches Hamid hold a bag of money as an elderly Sufi pir arrives in the village." },
    { src: "assets/frames/03.webp", alt: "Pir Sahib shows that one gift for Jalal will mean two gifts for Hamid." },
    { src: "assets/frames/04.webp", alt: "Jalal, Pir Sahib, and Hamid sit together as Jalal makes his first wish." },
    { src: "assets/frames/05.webp", alt: "One fish and one sack of rice appear for Jalal, while Hamid receives two of each." },
    { src: "assets/frames/06.webp", alt: "Jalal receives one chicken while Hamid receives two and his yard fills with food." },
    { src: "assets/frames/07.webp", alt: "Villagers watch as Jalal receives one goat and Hamid receives two." },
    { src: "assets/frames/08.webp", alt: "Jalal receives one chest and one jar while Hamid receives twice the treasure." },
    { src: "assets/frames/09.webp", alt: "At night Jalal lies awake, thinking angrily about Hamid's greater wealth." },
    { src: "assets/frames/10.webp", alt: "The next morning Jalal returns to Pir Sahib while Hamid sits among the gifts." },
    { src: "assets/frames/11.webp", alt: "Jalal points to his eye and asks for a dark final wish as Pir Sahib warns him." },
    { src: "assets/frames/12.webp", alt: "Jalal loses sight in one eye and Hamid loses sight in both as the village reacts in shock." },
    { src: "assets/frames/13.webp", alt: "Later, blind Hamid begs beside the village road while Jalal stands apart, still bitter and unhappy." }
  ],
  portraitPages: [
    { src: "assets/mobile/01.webp", alt: "The opening comic page: Jalal watches Hamid, meets Pir Sahib, and learns that Hamid will receive twice every wish." },
    { src: "assets/mobile/02.webp", alt: "The second comic page: Jalal wishes for food and animals while Hamid receives two of everything." },
    { src: "assets/mobile/03.webp", alt: "The third comic page: Hamid receives greater wealth and Jalal lies awake consumed by envy." },
    { src: "assets/mobile/04.webp", alt: "The fourth comic page: Jalal returns to Pir Sahib, asks to lose one eye, and Hamid loses sight in both." },
    { src: "assets/mobile/05.webp", alt: "The epilogue: blind Hamid begs beside the village road while one-eyed Jalal stands apart without peace." }
  ],
  camera: [
    { p: 1, py: .13, pz: 1.62, lx: .50, ly: .48, lz: 1.03 },
    { p: 1, py: .36, pz: 1.68, lx: .50, ly: .50, lz: 1.06 },
    { p: 1, py: .64, pz: 1.66, lx: .50, ly: .50, lz: 1.04 },
    { p: 1, py: .86, pz: 1.68, lx: .50, ly: .50, lz: 1.05 },
    { p: 2, py: .25, pz: 1.62, lx: .50, ly: .50, lz: 1.04 },
    { p: 2, py: .70, pz: 1.62, lx: .50, ly: .50, lz: 1.05 },
    { p: 3, py: .13, pz: 1.64, lx: .50, ly: .50, lz: 1.05 },
    { p: 3, py: .43, pz: 1.62, lx: .50, ly: .50, lz: 1.04 },
    { p: 3, py: .79, pz: 1.68, lx: .50, ly: .50, lz: 1.06 },
    { p: 4, py: .13, pz: 1.65, lx: .50, ly: .50, lz: 1.04 },
    { p: 4, py: .34, pz: 1.74, lx: .22, ly: .43, lz: 1.25 },
    { p: 4, py: .51, pz: 1.72, lx: .55, ly: .42, lz: 1.25 },
    { p: 4, py: .65, pz: 1.74, lx: .70, ly: .62, lz: 1.25 },
    { p: 4, py: .82, pz: 1.64, lx: .50, ly: .55, lz: 1.04 },
    { p: 5, py: .65, pz: 1.10, lx: .50, ly: .54, lz: 1.02 },
    { p: 5, py: .38, pz: 1.05, lx: .50, ly: .48, lz: 1.04 }
  ],
  lines: [
    { frame: 1, text: "In a riverside village in Bengal, Jalal and Hamid lived side by side. Hamid was prosperous, and Jalal couldn't bear to see it." },
    { frame: 2, text: "One morning, Jalal watched Hamid carry home another heavy bag. Then a wandering Pir Sahib came down the village path." },
    { frame: 3, text: "“Ask me for anything you wish,” the pir said. “But remember: whatever you receive, your neighbor will receive twice as much.”" },
    { frame: 4, text: "“Then give me one fish,” Jalal said." },
    { frame: 5, text: "A fish appeared before Jalal. Two appeared before Hamid. Jalal asked for one sack of rice, and Hamid received two." },
    { frame: 6, text: "Jalal asked for one chicken. Hamid got two. Soon Hamid's yard was overflowing, but Jalal's heart only grew tighter." },
    { frame: 7, text: "“Give me one goat,” Jalal demanded." },
    { frame: 8, text: "Hamid received two. Jalal asked for coins and grain, but every gift made his neighbor twice as rich." },
    { frame: 9, text: "That night Jalal lay awake. He had more than before, yet he could think only of what Hamid had." },
    { frame: 10, text: "By morning, envy had given him a terrible idea. He went back to Pir Sahib." },
    { frame: 11, text: "“Take the sight from one of my eyes,” Jalal said." },
    { frame: 11, text: "“Think carefully,” the pir warned. “Your neighbor will receive twice what you ask.”" },
    { frame: 11, text: "“I know,” Jalal replied. “Do it.”" },
    { frame: 12, text: "The wish was granted. Jalal lost the sight in one eye, and Hamid lost the sight in both." },
    { frame: 13, text: "Without his sight, Hamid couldn't protect his wealth or work as before. In time it was gone, and he had to beg beside the road." },
    { frame: 13, text: "Jalal had finally brought his neighbor lower than himself, but he still found no peace. Envy had taken more than it had given." }
  ],
  glossary: [
    { line: 0, phrase: "riverside village", kind: "phrase", meaning: "a village beside a river", bn: "নদীর ধারের গ্রাম" },
    { line: 0, phrase: "prosperous", kind: "word", meaning: "successful and having enough money or goods", bn: "সমৃদ্ধ; সচ্ছল" },
    { line: 0, phrase: "couldn't bear to see it", kind: "idiom", meaning: "found it too painful or upsetting to accept", bn: "দেখে সহ্য করতে পারত না" },
    { line: 1, phrase: "wandering", kind: "word", meaning: "travelling from place to place", bn: "ঘুরে বেড়ানো" },
    { line: 1, phrase: "Pir Sahib", kind: "culture", meaning: "a respectful Bengali Muslim title for a Sufi spiritual guide or saint", bn: "সম্মানিত সুফি পীর বা আধ্যাত্মিক গুরু" },
    { line: 2, phrase: "whatever you receive", kind: "grammar", meaning: "anything that is given to you; whatever means it doesn't matter which thing", bn: "তুমি যা-ই পাও না কেন" },
    { line: 2, phrase: "twice as much", kind: "grammar", meaning: "two times the amount", bn: "দ্বিগুণ পরিমাণ" },
    { line: 4, phrase: "appeared", kind: "word", meaning: "came into sight suddenly", bn: "হঠাৎ দেখা দিল" },
    { line: 4, phrase: "sack of rice", kind: "phrase", meaning: "a large cloth bag filled with rice", bn: "এক বস্তা চাল" },
    { line: 5, phrase: "overflowing", kind: "word", meaning: "so full that there is almost no space left", bn: "উপচে পড়া" },
    { line: 5, phrase: "heart only grew tighter", kind: "idiom", meaning: "he became more bitter and unhappy instead of grateful", bn: "তার মন আরও সংকীর্ণ ও তিক্ত হয়ে উঠল" },
    { line: 6, phrase: "demanded", kind: "word", meaning: "asked forcefully, as if expecting obedience", bn: "জোর দিয়ে দাবি করল" },
    { line: 7, phrase: "twice as rich", kind: "grammar", meaning: "having two times as much wealth", bn: "দ্বিগুণ ধনী" },
    { line: 8, phrase: "lay awake", kind: "phrase", meaning: "remained in bed without being able to sleep", bn: "ঘুমাতে না পেরে জেগে শুয়ে রইল" },
    { line: 8, phrase: "yet", kind: "grammar", meaning: "but even so; introduces a surprising contrast", bn: "তবুও" },
    { line: 9, phrase: "a terrible idea", kind: "phrase", meaning: "a harmful and frightening plan", bn: "একটি ভয়ংকর চিন্তা" },
    { line: 10, phrase: "Take the sight from", kind: "phrase", meaning: "cause someone to lose the ability to see", bn: "দৃষ্টিশক্তি কেড়ে নেওয়া" },
    { line: 11, phrase: "Think carefully", kind: "phrase", meaning: "consider the consequences before deciding", bn: "ভালো করে ভেবে দেখো" },
    { line: 13, phrase: "was granted", kind: "grammar", meaning: "was given or made real", bn: "মঞ্জুর করা হলো; পূর্ণ হলো" },
    { line: 13, phrase: "lost the sight", kind: "phrase", meaning: "became unable to see", bn: "দৃষ্টিশক্তি হারাল" },
    { line: 14, phrase: "as before", kind: "phrase", meaning: "in the same way he had done earlier", bn: "আগের মতো" },
    { line: 14, phrase: "In time", kind: "phrase", meaning: "after some time had passed", bn: "সময়ের সঙ্গে; কিছুদিন পরে" },
    { line: 14, phrase: "had to beg", kind: "grammar", meaning: "was forced by circumstances to ask other people for money or food", bn: "ভিক্ষা করতে বাধ্য হলো" },
    { line: 15, phrase: "brought his neighbor lower than himself", kind: "idiom", meaning: "deliberately made his neighbor's situation worse than his own", bn: "নিজের চেয়েও প্রতিবেশীর অবস্থা খারাপ করে দিল" },
    { line: 15, phrase: "found no peace", kind: "idiom", meaning: "still couldn't feel calm or satisfied", bn: "মনে শান্তি পেল না" },
    { line: 15, phrase: "taken more than it had given", kind: "idiom", meaning: "caused greater harm than benefit", bn: "যা দিয়েছিল তার চেয়ে বেশি কেড়ে নিয়েছিল" }
  ]
};

if (typeof module !== "undefined") module.exports = { HINGSHA_STORY };
