const HINGSHA_STORY = {
  id: "hingsha",
  title: "Hingsha",
  titleBn: "হিংসা",
  kicker: "A Bengali folk tale",
  sourceNote: "A contextual retelling of ATU 1331",
  audio: "audio/hingsha-story.mp3",
  tts: {
    model: "Gemini 3.8 Flash TTS",
    voice: "Gacrux",
    direction: "An older Bangladeshi Muslim male storyteller speaking clear natural English with a light Bengali accent. Warm oral-folktale rhythm, calm and intimate. Give Jalal a tense, increasingly bitter tone and Pir Sahib a gentle, grave tone, while remaining one narrator. Pronounce Jalal as ja-LAAL, Hamid as HAA-mid with a soft h, and Pir Sahib as peer SHA-heb."
  },
  frames: [
    { src: "assets/frames/01.webp", alt: "Jalal and Hamid walk through their riverside village while Jalal watches Hamid closely." },
    { src: "assets/frames/02.webp", alt: "Jalal watches Hamid hold a bag of money as an elderly Sufi pir arrives in the village." },
    { src: "assets/frames/03.webp", alt: "Pir Sahib shows that one gift for Jalal will mean two gifts for Hamid." },
    { src: "assets/frames/04.webp", alt: "Jalal, Pir Sahib, and Hamid sit together as Jalal makes his first wish." },
    { src: "assets/frames/05.webp", alt: "One fish and one sack of rice appear for Jalal, while Hamid receives two of each." },
    { src: "assets/frames/06.webp", alt: "Jalal receives one chicken while Hamid receives two and his yard fills with food." },
    { src: "assets/frames/07.webp", alt: "Villagers watch as Jalal receives one goat and Hamid receives two." },
    { src: "assets/frames/08.webp", alt: "Jalal receives one chest and one jar while Hamid receives twice the treasure." },
    { src: "assets/frames/09.webp", alt: "At night Jalal lies awake, thinking angrily about Hamid's greater wealth." },
    { src: "assets/frames/10.webp", alt: "The next morning Jalal returns to Pir Sahib while Hamid sits among the gifts." },
    { src: "assets/frames/11.webp", alt: "Jalal points to his eye and asks for a dark final wish as Pir Sahib warns him." },
    { src: "assets/frames/12.webp", alt: "Jalal loses sight in one eye and Hamid loses sight in both as the village reacts in shock." },
    { src: "assets/frames/13.webp", alt: "Later, blind Hamid begs beside the village road while Jalal stands apart, still bitter and unhappy." }
  ],
  portraitPages: [
    { src: "assets/mobile/01.webp", alt: "The opening comic page: Jalal watches Hamid, meets Pir Sahib, and learns that Hamid will receive twice every wish." },
    { src: "assets/mobile/02.webp", alt: "The second comic page: Jalal wishes for food and animals while Hamid receives two of everything." },
    { src: "assets/mobile/03.webp", alt: "The third comic page: Hamid receives greater wealth and Jalal lies awake consumed by envy." },
    { src: "assets/mobile/04.webp", alt: "The fourth comic page: Jalal returns to Pir Sahib, asks to lose one eye, and Hamid loses sight in both." },
    { src: "assets/mobile/05.webp", alt: "The epilogue: blind Hamid begs beside the village road while one-eyed Jalal stands apart without peace." }
  ],
  camera: [
    { p: 1, py: .13, pz: 1.62, lx: .50, ly: .48, lz: 1.03 },
    { p: 1, py: .36, pz: 1.68, lx: .50, ly: .50, lz: 1.06 },
    { p: 1, py: .64, pz: 1.66, lx: .50, ly: .50, lz: 1.04 },
    { p: 1, py: .86, pz: 1.68, lx: .50, ly: .50, lz: 1.05 },
    { p: 2, py: .25, pz: 1.62, lx: .50, ly: .50, lz: 1.04 },
    { p: 2, py: .70, pz: 1.62, lx: .50, ly: .50, lz: 1.05 },
    { p: 3, py: .13, pz: 1.64, lx: .50, ly: .50, lz: 1.05 },
    { p: 3, py: .43, pz: 1.62, lx: .50, ly: .50, lz: 1.04 },
    { p: 3, py: .79, pz: 1.68, lx: .50, ly: .50, lz: 1.06 },
    { p: 4, py: .13, pz: 1.65, lx: .50, ly: .50, lz: 1.04 },
    { p: 4, py: .34, pz: 1.74, lx: .22, ly: .43, lz: 1.25 },
    { p: 4, py: .51, pz: 1.72, lx: .55, ly: .42, lz: 1.25 },
    { p: 4, py: .65, pz: 1.74, lx: .70, ly: .62, lz: 1.25 },
    { p: 4, py: .82, pz: 1.64, lx: .50, ly: .55, lz: 1.04 },
    { p: 5, py: .65, pz: 1.10, lx: .50, ly: .54, lz: 1.02 },
    { p: 5, py: .38, pz: 1.05, lx: .50, ly: .48, lz: 1.04 }
  ],
  lines: [
    { frame: 1, text: "In a riverside village in Bengal, Jalal and Hamid lived side by side. Hamid was prosperous, and Jalal couldn't bear to see it." },
    { frame: 2, text: "One morning, Jalal watched Hamid carry home another heavy bag. Then a wandering Pir Sahib came down the village path." },
    { frame: 3, text: "“Ask me for anything you wish,” the pir said. “But remember: whatever you receive, your neighbor will receive twice as much.”" },
    { frame: 4, text: "“Then give me one fish,” Jalal said." },
    { frame: 5, text: "A fish appeared before Jalal. Two appeared before Hamid. Jalal asked for one sack of rice, and Hamid received two." },
    { frame: 6, text: "Jalal asked for one chicken. Hamid got two. Soon Hamid's yard was overflowing, but Jalal's heart only grew tighter." },
    { frame: 7, text: "“Give me one goat,” Jalal demanded." },
    { frame: 8, text: "Hamid received two. Jalal asked for coins and grain, but every gift made his neighbor twice as rich." },
    { frame: 9, text: "That night Jalal lay awake. He had more than before, yet he could think only of what Hamid had." },
    { frame: 10, text: "By morning, envy had given him a terrible idea. He went back to Pir Sahib." },
    { frame: 11, text: "“Take the sight from one of my eyes,” Jalal said." },
    { frame: 11, text: "“Think carefully,” the pir warned. “Your neighbor will receive twice what you ask.”" },
    { frame: 11, text: "“I know,” Jalal replied. “Do it.”" },
    { frame: 12, text: "The wish was granted. Jalal lost the sight in one eye, and Hamid lost the sight in both." },
    { frame: 13, text: "Without his sight, Hamid couldn't protect his wealth or work as before. In time it was gone, and he had to beg beside the road." },
    { frame: 13, text: "Jalal had finally brought his neighbor lower than himself, but he still found no peace. Envy had taken more than it had given." }
  ],
  // Word offsets refer to the exact transcript, so cues follow the delivered audio.
  // Rectangles are [left, top, width, height] within the intact comic image.
  cameraBeats: [
    { line: 0, word: 0, label: "The riverside village", portrait: [.007,.005,.986,.259], landscape: [.02,.18,.96,.62] },
    { line: 0, word: 6, label: "Jalal and Hamid side by side", portrait: [.40,.035,.34,.229], landscape: [.44,.21,.32,.57] },
    { line: 0, word: 13, frame: 2, label: "Hamid's prosperity", portrait: [.468,.269,.525,.203], landscape: [.48,.045,.49,.485] },
    { line: 0, word: 17, frame: 2, label: "Jalal's jealousy", portrait: [.007,.269,.455,.203], landscape: [.035,.045,.44,.485] },
    { line: 1, word: 0, label: "Jalal watches his neighbor", portrait: [.007,.269,.455,.203], landscape: [.035,.045,.44,.485] },
    { line: 1, word: 4, label: "Hamid's heavy bag", portrait: [.468,.269,.525,.203], landscape: [.48,.045,.49,.485] },
    { line: 1, word: 10, label: "The wandering pir arrives", portrait: [.35,.477,.30,.160], landscape: [.035,.54,.94,.40] },
    { line: 2, word: 0, label: "The pir offers a wish", portrait: [.007,.641,.478,.165], landscape: [.025,.045,.465,.40] },
    { line: 2, word: 9, label: "The condition of the wish", portrait: [.492,.641,.501,.165], landscape: [.495,.045,.48,.40] },
    { line: 2, word: 11, label: "One gift for Jalal", portrait: [.495,.645,.22,.157], landscape: [.495,.045,.235,.40] },
    { line: 2, word: 14, label: "Double for Hamid", portrait: [.715,.645,.278,.157], landscape: [.735,.045,.24,.40] },
    { line: 3, word: 0, label: "Jalal makes his first wish", portrait: [.007,.005,.35,.194], landscape: [.03,.26,.38,.48], page: 2 },
    { line: 4, word: 0, label: "One fish", portrait: [.006,.203,.35,.168], landscape: [.022,.09,.34,.409] },
    { line: 4, word: 5, label: "Two fish", portrait: [.36,.203,.33,.168], landscape: [.369,.09,.318,.409] },
    { line: 4, word: 9, label: "One sack of rice", portrait: [.006,.377,.35,.162], landscape: [.022,.508,.34,.403] },
    { line: 4, word: 17, label: "Two sacks of rice", portrait: [.36,.377,.33,.162], landscape: [.372,.508,.315,.403] },
    { line: 5, word: 0, label: "One chicken", portrait: [.006,.544,.35,.168], landscape: [.094,.029,.294,.348] },
    { line: 5, word: 5, label: "Two chickens", portrait: [.36,.544,.33,.168], landscape: [.392,.029,.282,.348] },
    { line: 5, word: 8, label: "Hamid's overflowing yard", portrait: [.39,.717,.60,.28], landscape: [.39,.385,.515,.581] },
    { line: 5, word: 14, label: "Jalal's bitter heart", portrait: [.006,.717,.39,.28], landscape: [.094,.385,.297,.581] },
    { line: 6, word: 0, label: "Jalal demands a goat", portrait: [.007,.005,.225,.20], landscape: [.025,.265,.23,.47] },
    { line: 7, word: 0, frame: 7, label: "Hamid receives two goats", portrait: [.435,.005,.40,.20], landscape: [.45,.265,.41,.47] },
    { line: 7, word: 3, label: "The wish for coins", portrait: [.34,.209,.43,.173], landscape: [.025,.09,.95,.405] },
    { line: 7, word: 8, label: "Grain and provisions", portrait: [.34,.386,.43,.163], landscape: [.025,.515,.95,.385] },
    { line: 7, word: 9, label: "Hamid's double wealth", portrait: [.35,.21,.43,.339], landscape: [.34,.09,.45,.81] },
    { line: 8, word: 0, label: "Night falls on Jalal", portrait: [.007,.554,.472,.185], landscape: [.085,.07,.388,.371] },
    { line: 8, word: 2, label: "Jalal cannot sleep", portrait: [.486,.554,.507,.185], landscape: [.485,.07,.43,.371] },
    { line: 8, word: 10, label: "Thinking of Hamid's wealth", portrait: [.007,.744,.496,.252], landscape: [.085,.45,.403,.477] },
    { line: 9, word: 0, page: 3, frame: 9, label: "A terrible idea forms", portrait: [.735,.744,.258,.252], landscape: [.715,.45,.20,.477] },
    { line: 9, word: 9, label: "Jalal returns to Pir Sahib", portrait: [.007,.005,.555,.227], landscape: [.025,.26,.53,.535] },
    { line: 10, word: 0, label: "Jalal asks to lose one eye", portrait: [.007,.236,.24,.144], landscape: [.025,.08,.24,.365] },
    { line: 11, word: 0, label: "The pir warns Jalal", portrait: [.253,.236,.253,.144], landscape: [.27,.08,.253,.365] },
    { line: 11, word: 5, label: "The warning about double", portrait: [.512,.236,.481,.144], landscape: [.53,.08,.445,.365] },
    { line: 12, word: 0, label: "Jalal insists", portrait: [.007,.236,.24,.144], landscape: [.025,.08,.24,.365] },
    { line: 13, word: 0, frame: 11, label: "The wish takes effect", portrait: [.007,.385,.597,.155], landscape: [.025,.46,.95,.365] },
    { line: 13, word: 4, frame: 11, label: "Jalal loses one eye", portrait: [.007,.385,.272,.155], landscape: [.025,.46,.278,.365] },
    { line: 13, word: 12, frame: 11, label: "Hamid loses both eyes", portrait: [.284,.385,.32,.155], landscape: [.31,.46,.30,.365] },
    { line: 14, word: 0, page: 4, frame: 12, label: "Hamid among his remaining wealth", portrait: [.40,.543,.593,.188], landscape: [.42,.025,.48,.40] },
    { line: 14, word: 12, label: "Hamid's wealth is gone", portrait: [.23,.47,.76,.45], landscape: [.28,.32,.68,.66] },
    { line: 14, word: 18, label: "Hamid begs beside the road", portrait: [.40,.53,.593,.40], landscape: [.57,.38,.41,.60] },
    { line: 15, word: 0, label: "Jalal watches Hamid", portrait: [.007,.17,.986,.70], landscape: [.025,.035,.95,.91] },
    { line: 15, word: 9, label: "Jalal still finds no peace", portrait: [.007,.20,.25,.53], landscape: [.025,.035,.26,.89] },
    { line: 15, word: 15, label: "The cost of envy", portrait: [.007,.17,.986,.70], landscape: [.025,.035,.95,.91] }
  ],
  glossary: [
    { line: 0, phrase: "riverside village", kind: "phrase", meaning: "a village beside a river", bn: "নদীর ধারের গ্রাম" },
    { line: 0, phrase: "prosperous", kind: "word", meaning: "successful and having enough money or goods", bn: "সমৃদ্ধ; সচ্ছল" },
    { line: 0, phrase: "couldn't bear to see it", kind: "idiom", meaning: "found it too painful or upsetting to accept", bn: "দেখে সহ্য করতে পারত না" },
    { line: 1, phrase: "wandering", kind: "word", meaning: "travelling from place to place", bn: "ঘুরে বেড়ানো" },
    { line: 1, phrase: "Pir Sahib", kind: "culture", meaning: "a respectful Bengali Muslim title for a Sufi spiritual guide or saint", bn: "সম্মানিত সুফি পীর বা আধ্যাত্মিক গুরু" },
    { line: 2, phrase: "whatever you receive", kind: "grammar", meaning: "anything that is given to you; whatever means it doesn't matter which thing", bn: "তুমি যা-ই পাও না কেন" },
    { line: 2, phrase: "twice as much", kind: "grammar", meaning: "two times the amount", bn: "দ্বিগুণ পরিমাণ" },
    { line: 4, phrase: "appeared", kind: "word", meaning: "came into sight suddenly", bn: "হঠাৎ দেখা দিল" },
    { line: 4, phrase: "sack of rice", kind: "phrase", meaning: "a large cloth bag filled with rice", bn: "এক বস্তা চাল" },
    { line: 5, phrase: "overflowing", kind: "word", meaning: "so full that there is almost no space left", bn: "উপচে পড়া" },
    { line: 5, phrase: "heart only grew tighter", kind: "idiom", meaning: "he became more bitter and unhappy instead of grateful", bn: "তার মন আরও সংকীর্ণ ও তিক্ত হয়ে উঠল" },
    { line: 6, phrase: "demanded", kind: "word", meaning: "asked forcefully, as if expecting obedience", bn: "জোর দিয়ে দাবি করল" },
    { line: 7, phrase: "twice as rich", kind: "grammar", meaning: "having two times as much wealth", bn: "দ্বিগুণ ধনী" },
    { line: 8, phrase: "lay awake", kind: "phrase", meaning: "remained in bed without being able to sleep", bn: "ঘুমাতে না পেরে জেগে শুয়ে রইল" },
    { line: 8, phrase: "yet", kind: "grammar", meaning: "but even so; introduces a surprising contrast", bn: "তবুও" },
    { line: 9, phrase: "a terrible idea", kind: "phrase", meaning: "a harmful and frightening plan", bn: "একটি ভয়ংকর চিন্তা" },
    { line: 10, phrase: "Take the sight from", kind: "phrase", meaning: "cause someone to lose the ability to see", bn: "দৃষ্টিশক্তি কেড়ে নেওয়া" },
    { line: 11, phrase: "Think carefully", kind: "phrase", meaning: "consider the consequences before deciding", bn: "ভালো করে ভেবে দেখো" },
    { line: 13, phrase: "was granted", kind: "grammar", meaning: "was given or made real", bn: "মঞ্জুর করা হলো; পূর্ণ হলো" },
    { line: 13, phrase: "lost the sight", kind: "phrase", meaning: "became unable to see", bn: "দৃষ্টিশক্তি হারাল" },
    { line: 14, phrase: "as before", kind: "phrase", meaning: "in the same way he had done earlier", bn: "আগের মতো" },
    { line: 14, phrase: "In time", kind: "phrase", meaning: "after some time had passed", bn: "সময়ের সঙ্গে; কিছুদিন পরে" },
    { line: 14, phrase: "had to beg", kind: "grammar", meaning: "was forced by circumstances to ask other people for money or food", bn: "ভিক্ষা করতে বাধ্য হলো" },
    { line: 15, phrase: "brought his neighbor lower than himself", kind: "idiom", meaning: "deliberately made his neighbor's situation worse than his own", bn: "নিজের চেয়েও প্রতিবেশীর অবস্থা খারাপ করে দিল" },
    { line: 15, phrase: "found no peace", kind: "idiom", meaning: "still couldn't feel calm or satisfied", bn: "মনে শান্তি পেল না" },
    { line: 15, phrase: "taken more than it had given", kind: "idiom", meaning: "caused greater harm than benefit", bn: "যা দিয়েছিল তার চেয়ে বেশি কেড়ে নিয়েছিল" }
  ]
};

if (typeof module !== "undefined") module.exports = { HINGSHA_STORY };
