/* Deterministic phone simulator. Navigation and authored branches, no live services. */
(() => {
 const $=s=>document.querySelector(s), E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let store;try{store=JSON.parse(localStorage.getItem('dialogue-phone-lab-v1'))||{}}catch{store={}}
 let journey, state, view='Home', drawer=false, bn=false, animation, resetScroll=true;
 const save=()=>{try{localStorage.setItem('dialogue-phone-lab-v1',JSON.stringify(store))}catch{}};
 const on=(id,fn)=>{const el=document.getElementById(id);if(el)el.onclick=fn};
 const current=()=>journey.steps[state.step];
 const stopAnimation=()=>{clearTimeout(animation);animation=undefined};
 const icons={Home:'●',Messages:'▣',Browser:'◉',Notes:'▤',Files:'▱',Gallery:'▧',Gemini:'✦',ChatGPT:'◎',Claude:'✳'};
 const persistRender=()=>{save();render()};
 function open(app){stopAnimation();resetScroll=true;state.previous=view;view=app;drawer=false;render()}
 function home(){stopAnimation();journey=null;view='Home';PhoneLab.active=false;
 $('#app').innerHTML=`<section class="pl-welcome"><small>AI Fluency Lab · three guided phone workflows</small><h1>Someone needs your help.<br>You have their phone.</h1><p>Help a student complete a real-world task with AI. Open their messages, check the information, steer the AI and decide what is ready to use.</p><div class="pl-how"><span>① Meet the student</span><span>② Use their phone</span><span>③ Check what you made</span></div><div class="sessions">${PHONE_JOURNEYS.map((j,i)=>`<article class="session"><small>Session ${i+1} · ${j.app} · 45 minutes</small><h2>${j.title}</h2><p>${j.task}</p><p class="muted">Result: ${j.artifact}</p><button class="primary" data-journey="${j.id}">Meet ${j.person} →</button></article>`).join('')}</div><p class="muted">One phone per pair, or project for the class. All people, opportunities and outputs are fictional. The apps are simplified, authored simulations; no account or real upload is needed.</p></section>`;
 document.querySelectorAll('[data-journey]').forEach(b=>b.onclick=()=>location.hash='phone/'+b.dataset.journey);
 $('#teacher').innerHTML='<h3>Three complete workflows</h3><p>Use 3 minutes to establish the character, goal and controls. The eight decisions take 42 minutes including discussion (4, 5, 7, 6, 5, 6, 5, 4). Partner A operates, B asks for evidence; swap after each decision. At the final task, both decide independently before comparing.</p>';
 }
 function route(id){stopAnimation();journey=PHONE_JOURNEYS.find(j=>j.id===id);if(!journey)return home();PhoneLab.active=true;state=store[id]||(store[id]={started:false,step:0,answers:{},receipts:[],visited:[],played:{}});view=state.started?(state.complete?'Notes':'Home'):'Welcome';drawer=false;render()}
 function welcome(){return `<div class="pl-intro"><span class="pl-avatar">${journey.person[0]}</span><h2>This is ${journey.person}’s phone.</h2><p>${journey.university}</p>${bn?'<p class="bn" lang="bn">এই শিক্ষার্থীর ফোন ব্যবহার করে কাজটি শেষ করুন। আগে বার্তা ও তথ্য পড়ুন। তারপর AI-কে নির্দেশ দিন এবং ফলাফল যাচাই করুন।</p>':''}<div class="pl-card"><b>The situation</b><p>${journey.task}</p></div><div class="pl-card"><b>Your job</b><p>Make decisions for ${journey.person}. You will leave with: <strong>${journey.artifact.toLowerCase()}</strong>.</p></div><p>Tap the notification to begin. Use <b>● Home</b> to change apps. <b>◀ Back</b> returns to the previous screen.</p><p>One partner taps; the other checks the evidence. Swap after each decision.</p><button id="pl-unlock" class="primary">Unlock ${journey.person}’s phone →</button></div>`}
 function launcher(){return `<div class="pl-launch"><div class="pl-clock">09:41</div><p>${journey.person}’s practice phone</p><button class="pl-notification" id="pl-notification"><small>Messages · ${journey.id==='opportunity'?'Careers group':journey.id==='learning'?'Class group':'Speaking club'}</small><b>${journey.notification}</b><span>Tap to open →</span></button><div class="pl-appgrid">${['Messages',journey.app,'Browser','Notes','Files',...(journey.id==='poster'?['Gallery']:[])].map(a=>`<button data-open="${a}"><i>${icons[a]}</i><span>${a}</span></button>`).join('')}</div>${state.started?`<button id="pl-resume" class="primary">${state.complete?'Open your result':'Continue the task →'}</button>`:''}</div>`}
 function messages(){return `<div class="pl-message"><small>Classmate · 09:40</small><p>${journey.notification}</p></div><div class="pl-message mine"><small>${journey.person}</small><p>${journey.task}</p></div><div class="pl-card"><b>Help ${journey.person}</b><p>Open the brief first. Then work through the task in ${journey.app}.</p><button id="pl-brief" class="primary">Open the brief in Browser →</button></div>`}
 function source(app){const text=journey.sources[app]||journey.sources.Notes;return `<div class="pl-document"><small>${app==='Browser'?'practice.local / source · fictional':'Saved on this practice phone'}</small>${journey.id==='learning'&&app==='Browser'?'<div class="pl-study-bars"><div><b>Chose the app</b><span style="width:100%">+10 points</span></div><div><b>No app</b><span style="width:40%">+3</span></div><small>20 students in each group · they chose their group</small></div>':''}<h2>${app==='Browser'?'The brief':app==='Files'?'Available files':'Your notes'}</h2><p class="pl-pre">${E(text)}</p>${state.receipts.length?`<details><summary>Your checked decisions (${state.receipts.filter(Boolean).length})</summary>${state.receipts.filter(Boolean).map(r=>`<p>✓ ${E(r)}</p>`).join('')}</details>`:''}<button id="pl-return" class="primary">${state.step===0?'Open '+journey.app+' →':'Return to the task →'}</button></div>`}
 function final(){return `<div class="pl-document">${journey.id==='poster'?poster()+'<div class="pl-card"><b>Announcement · checked version</b><p>Join Speaking Circle on Friday 16 October at 4 pm in Room 205. Free peer speaking practice for up to 30 students. No certificates.</p></div>':''}<small>Saved result · ${journey.person}</small><h2>${journey.artifact}</h2>${state.receipts.filter(Boolean).map(r=>`<div class="pl-record">✓ ${E(r)}</div>`).join('')}<div class="pl-card"><b>Now explain it yourself</b><p>What did you keep for the human? What did you ask AI to do? What did you check? What are you responsible for next?</p></div><button id="pl-download">Save learning record</button><button id="pl-all">Choose another workflow →</button><p class="muted">A completed simulation records practice, not proof of mastery. Explain the result without rereading the feedback.</p></div>`}
 function poster(){const corrected=state.step>3||state.answers[3]?.done;const confirmed=state.complete;return `<div class="pl-poster"><small>Speaking club · draft</small><h2>Speaking<br>Circle</h2><svg viewBox="0 0 260 140" role="img" aria-label="Illustration of two students practising conversation"><rect x="15" y="5" width="230" height="130" rx="25" fill="#e0e7d4"/><circle cx="73" cy="53" r="20" fill="#b28464"/><circle cx="185" cy="53" r="20" fill="#be9775"/><path d="M40 130v-30q33-35 66 0v30M151 130v-30q33-35 66 0v30" fill="#244f43"/><rect x="95" y="12" width="60" height="28" rx="12" fill="#fffefa"/><text x="125" y="32" text-anchor="middle" fill="#244f43">Hi!</text></svg><b>Friday 16 October</b><p>${corrected?'4 pm · Room '+(confirmed?'205':'204'):'5 pm · Room 240'}</p><strong>${corrected?'Peer practice · no certificates':'Official IELTS certificates!'}</strong><p>Free entry · 30 places</p><span>${confirmed?'Room confirmed · check all copies':'Draft · confirm room before sharing'}</span></div>`}
 function gallery(){return `${poster()}<button id="pl-return" class="primary">Return to the decision →</button>`}
 function task(){const step=current();const a=state.answers[state.step]||(state.answers[state.step]={});const ready=state.played[state.step];return `<div class="pl-tasklabel"><small>${step.d} · decision ${state.step+1}/8</small><b>${step.title}</b>${bn?'<span class="bn" lang="bn">আগে তথ্য দেখুন। তারপর সিদ্ধান্ত নিন।</span>':''}</div>${journey.id==='poster'&&(state.step===3||step.app==='Gallery')?poster():''}<div class="pl-chatlog" aria-live="polite"><div class="pl-message mine"><small>${journey.person}</small><p>${state.step===0?journey.task:state.receipts.at(-1)||'Help me with the next step.'}</p></div><div class="pl-message ai"><small>${step.app==='Notes'?'Independent task':journey.app}</small><p id="pl-output">${ready?E(step.text):'<span class="pl-typing">● ● ●</span>'}</p></div></div>${!ready?'<button id="pl-skip">Show the whole message</button>':interaction(step,a)}${a.feedback?`<div class="pl-feedback ${a.done?'good':'retry'}" role="status"><b>${a.done?'✓ Checked':'Look at what happens'}</b><p>${E(a.feedback)}</p></div>`:''}${a.done?`<button id="pl-next" class="primary">${state.step===7?'Save the result →':'Continue the workflow →'}</button>`:''}`}
 function interaction(step,a){const chosen=a.picks||{};let body='';
 if(step.source&&!state.visited.includes(step.source+':'+state.step))return `<div class="pl-pause"><b>Check before deciding</b><p>Open ${step.source} and read the facts. Then return here.</p><button data-open="${step.source}" class="primary">Open ${step.source} →</button></div>`;
 if(step.kind==='choice'||step.kind==='reflect')body=`<div class="pl-choices">${step.options.map((o,i)=>`<button data-answer="${i}" aria-pressed="${a.choice===i}">${E(o)}</button>`).join('')}</div>`;
 if(step.kind==='compose'){const active=a.edit??step.groups.findIndex((_,i)=>chosen[i]===undefined);body=`<div class="pl-compose"><small>Build your message · drag or tap a tile</small>${step.groups.map((g,i)=>`<div class="pl-slot" data-drop="${i}"><div class="pl-slothead"><b>${g.label}</b>${chosen[i]!==undefined?`<button data-edit="${i}" aria-label="Edit ${g.label}">Edit</button>`:''}</div><p>${chosen[i]===undefined?'Place a tile here ↓':E(g.options[chosen[i]])}</p></div>`).join('')}${active>=0?`<b>Choose: ${step.groups[active].label}</b><div class="pl-choices">${step.groups[active].options.map((o,k)=>`<button draggable="true" data-prompt="${active}:${k}" aria-pressed="${chosen[active]===k}">${E(o)}</button>`).join('')}</div>`:''}<button id="pl-send" class="primary" ${step.groups.some((_,i)=>chosen[i]===undefined)?'disabled':''}>Send this prompt ↑</button></div>`}
 if(step.kind==='privacy')body=`<div class="pl-attachment"><small>Tap to attach · private details stay out</small>${step.fields.map(([f],i)=>`<button data-file="${i}" aria-pressed="${(a.files||[]).includes(i)}">${(a.files||[]).includes(i)?'☑':'□'} ${E(f)}</button>`).join('')}<button id="pl-attach" class="primary">Review attachments →</button></div>`;
 if(step.kind==='evidence')body=`<div class="pl-pause"><b>Tap each claim that needs correcting</b><div class="pl-choices">${step.claim.map((c,i)=>`<button data-claim="${i}" aria-pressed="${(a.claims||[]).includes(i)}">${E(c)}${(a.claims||[]).includes(i)?`<span class="pl-correction">Source: ${E(step.facts[i])}</span>`:''}</button>`).join('')}</div><button data-open="${step.source}">Read the source again</button><button id="pl-correct" class="primary">Ask AI to correct these →</button></div>`;
 return body;
 }
 function complete(a,receipt,feedback){a.done=true;a.feedback=feedback;state.receipts[state.step]=receipt;persistRender()}
 function render(){const opening=resetScroll;const scroll=resetScroll?0:($('#android-screen')?.scrollTop||0);resetScroll=false;stopAnimation();if(!journey)return home();PhoneLab.active=true;const step=current();const aiApp=step.app||journey.app;const inTask=view===aiApp&&!state.complete;const body=view===journey.app&&aiApp==='Notes'?'<div class="pl-card"><b>Chat closed for this step</b><p>Try the new problem yourself in Notes. You can return to AI support after your independent attempt.</p><button data-open="Notes" class="primary">Open Notes →</button></div>':view==='Welcome'?welcome():view==='Home'?launcher():view==='Messages'?messages():state.complete&&view==='Notes'?final():inTask?task():view==='Gallery'?gallery():source(view);
 $('#app').innerHTML=`<div class="pl-shell"><aside class="pl-outside"><button id="pl-home">← All workflows</button><small>${journey.person}’s workflow</small><h1>${journey.title}</h1><p>${journey.task}</p><div class="pl-four">${['Delegation','Description','Discernment','Diligence'].map(d=>`<span class="${state.receipts.some((r,i)=>r&&journey.steps[i].d===d)?'checked':''}">${d}</span>`).join('')}</div><p>Use the phone to complete the task. If you need the facts, press <b>● Home</b> and open Browser or Notes.</p><p class="muted">${state.step%2?'B operates · A checks':'A operates · B checks'} · swap after the next decision</p><button id="pl-reset">Restart this workflow</button>${state.resetPending?'<div class="pl-reset-confirm" role="alert"><p>Clear this workflow’s saved decisions?</p><button id="pl-confirm-reset">Clear and restart</button><button id="pl-cancel-reset">Keep my work</button></div>':''}</aside><div class="android" data-app="${view}" data-kind="${inTask?step.kind:''}"><div class="android-status"><span>09:41</span><button id="pl-shade" aria-label="Open notifications">▮▮▮ &nbsp; ▰</button></div><div class="android-appbar"><b>${view==='Welcome'?journey.person+'’s phone':icons[view]+' '+view}</b><small>${state.complete?'Result saved':view==='Home'?'Android-style practice':'Practice · no live connection'}</small></div>${drawer?`<div class="pl-shade"><b>Notifications</b><button id="pl-notification">${journey.notification}</button><button id="pl-close-shade">Close notifications</button></div>`:`<div class="android-screen ${opening?'pl-app-enter':''}" id="android-screen">${body}</div>`}<nav class="android-nav" aria-label="Android navigation"><button id="pl-back" aria-label="Back">◀</button><button id="pl-launcher" aria-label="Home">●</button><button id="pl-recents" aria-label="Recent apps">▣</button></nav></div></div>`;
 on('pl-home',()=>location.hash='');on('pl-all',()=>location.hash='');on('pl-unlock',()=>{state.started=true;save();open('Home')});on('pl-notification',()=>open('Messages'));on('pl-brief',()=>{state.visited.push('Browser:'+state.step);open('Browser')});on('pl-return',()=>open(aiApp));on('pl-resume',()=>open(state.complete?'Notes':aiApp));on('pl-launcher',()=>open('Home'));on('pl-back',()=>open(view==='Home'?'Messages':state.previous&&state.previous!==view?state.previous:'Home'));on('pl-shade',()=>{drawer=!drawer;render()});on('pl-close-shade',()=>{drawer=false;render()});on('pl-recents',()=>{stopAnimation();drawer=false;$('#android-screen').innerHTML=`<div class="pl-recents"><h2>Recent apps</h2>${['Messages','Browser',journey.app,'Notes',...(journey.id==='poster'?['Gallery']:[])].map(app=>`<button data-open="${app}">${icons[app]} ${app}</button>`).join('')}</div>`;bindApps()});
 on('pl-reset',()=>{state.resetPending=true;render()});on('pl-cancel-reset',()=>{state.resetPending=false;render()});on('pl-confirm-reset',()=>{delete store[journey.id];save();route(journey.id)});
 on('pl-download',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([journey.artifact+'\n\n'+state.receipts.join('\n\n')+'\n\nPractice record, not a certificate of mastery.'],{type:'text/plain'}));a.download=journey.id+'-learning-record.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});
 if($('#android-screen'))$('#android-screen').scrollTop=scroll;bindApps();if(inTask){bindTask();if(!state.played[state.step]){const stepIndex=state.step;animation=setTimeout(()=>{if(journey&&state.step===stepIndex&&view===aiApp){state.played[stepIndex]=true;persistRender()}},matchMedia('(prefers-reduced-motion: reduce)').matches?0:1000)}}
 $('#teacher').innerHTML=`<h3>${journey.title}</h3><p>3-minute setup + 42 minutes of decisions and discussion. Current decision: ${step.title} (${step.minutes} minutes).</p><p>Have students predict before choosing. Ask them to point to the source and explain their reason. The final transfer decision is individual before pair discussion. A green check records a supported practice choice, not independent mastery.</p><p>Result: ${journey.artifact}. All events and AI messages are fictional. App switching changes the simulation view; it does not use real Android or live AI.</p>`;
 }
 function bindApps(){document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>{state.visited.push(b.dataset.open+':'+state.step);save();open(b.dataset.open)})}
 function bindTask(){const step=current(),a=state.answers[state.step]||(state.answers[state.step]={});
 on('pl-skip',()=>{state.played[state.step]=true;persistRender()});
 document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const n=+b.dataset.answer;if(a.first===undefined)a.first=n;a.choice=n;if(step.kind==='reflect'||n===step.answer)complete(a,step.receipt+(step.kind==='reflect'?' '+step.options[n]:''),step.kind==='reflect'?step.reply:step.why[n]);else{a.done=false;state.receipts[state.step]=null;a.feedback=step.why[n];persistRender()}});
 const place=(value,target)=>{const [i,k]=value.split(':').map(Number);if(target!==undefined&&target!==i)return;a.picks={...a.picks,[i]:k};delete a.edit;a.done=false;state.receipts[state.step]=null;a.feedback='';persistRender()};
 document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{a.edit=+b.dataset.edit;render()});
 document.querySelectorAll('[data-prompt]').forEach(b=>{let origin,moved=false;b.onclick=()=>{if(!moved)place(b.dataset.prompt);moved=false};b.ondragstart=e=>e.preventDefault();b.onpointerdown=e=>{origin=[e.clientX,e.clientY];moved=false;b.setPointerCapture(e.pointerId)};b.onpointermove=e=>{if(origin&&Math.hypot(e.clientX-origin[0],e.clientY-origin[1])>8){moved=true;b.classList.add('dragging')}};b.onpointerup=e=>{if(moved){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-drop]');if(target)place(b.dataset.prompt,+target.dataset.drop)}origin=null;b.classList.remove('dragging')};b.onpointercancel=()=>{origin=null;moved=false;b.classList.remove('dragging')}});
 on('pl-send',()=>{if(step.groups.every((g,i)=>a.picks?.[i]===g.answer))complete(a,'Prompt: '+step.groups.map((g,i)=>g.options[a.picks[i]]).join(' '),step.reply);else{a.feedback='This request changes the goal or gives away work you need to keep. Check the selected tiles.';a.done=false;state.receipts[state.step]=null;persistRender()}});
 document.querySelectorAll('[data-file]').forEach(b=>b.onclick=()=>{const i=+b.dataset.file;a.files=(a.files||[]).includes(i)?a.files.filter(x=>x!==i):[...(a.files||[]),i];a.done=false;state.receipts[state.step]=null;a.feedback='';persistRender()});
 on('pl-attach',()=>{if(step.fields.every((f,i)=>f[1]===(a.files||[]).includes(i)))complete(a,step.reply,step.reply);else{a.feedback='The AI needs the task material, not other people’s private details. Review what you attached.';a.done=false;state.receipts[state.step]=null;persistRender()}});
 document.querySelectorAll('[data-claim]').forEach(b=>b.onclick=()=>{const i=+b.dataset.claim;a.claims=(a.claims||[]).includes(i)?a.claims.filter(x=>x!==i):[...(a.claims||[]),i];a.done=false;state.receipts[state.step]=null;a.feedback='';persistRender()});
 on('pl-correct',()=>{if((a.claims||[]).length===step.claim.length)complete(a,step.reply,step.reply);else{a.feedback='Check both claims against the source before accepting the draft.';persistRender()}});
 on('pl-next',()=>{if(!a.done)return;if(state.step===7){state.complete=true;save();open('Notes')}else{state.step++;resetScroll=true;state.previous=view;view=current().app||journey.app;save();render()}});
 }
 const PhoneLab=window.PhoneLab={active:false,home,route,setBangla(value){bn=value;if(journey)render()},stop:stopAnimation};
})();
