(() => {
'use strict';
const D=window.FLUENCY,W=window.WORKFLOWS,C=window.FluencyCore,esc=C.escapeHTML,$=id=>document.getElementById(id);
const titles=['Meet your task partner','Who should do what?','Give AI a useful brief','A confident answer. Good work?','Make the next message count','Would you put your name on it?','A new situation. Your decisions.','Show your judgement'];
const shorts=['Meet the task','Divide the work','Build the brief','Inspect the draft','Repair & refine','Own the result','Transfer the skills','Exit ticket'];
const state={workflow:'cv',mode:'pair',bangla:false,provider:'ChatGPT',lessons:{}};
const blank=()=>({stage:0,answers:{},checked:{},reveals:{},text:{},checks:{},visited:{0:true},seen:{},calc:{room:'600',materials:'400',people:'5'},calcResult:null});
try{const s=JSON.parse(sessionStorage.getItem('dialogue-fluency-v1'));if(s&&W.some(w=>w.id===s.workflow)){state.workflow=s.workflow;state.mode=s.mode==='class'?'class':'pair';state.bangla=!!s.bangla;state.provider=['ChatGPT','Claude','Gemini'].includes(s.provider)?s.provider:'ChatGPT';for(const w of W){const l=s.lessons?.[w.id];if(l&&Number.isInteger(l.stage)&&l.stage>=0&&l.stage<8)state.lessons[w.id]={...blank(),...l};}}}catch{}
const lesson=()=>state.lessons[state.workflow]||(state.lessons[state.workflow]=blank()),work=()=>W.find(w=>w.id===state.workflow);
const save=()=>{try{sessionStorage.setItem('dialogue-fluency-v1',JSON.stringify(state));}catch{}};
const say=t=>{$('announcement').textContent=t;};
let remaining=240,ticking=false,timerId=null,deadline=0;
const bn=t=>`<div class="bn" lang="bn">${esc(t)}</div>`,prose=t=>`<div class="prelines">${esc(t)}</div>`;
function pair(a,b){return `<div class="pair-bar"><strong>${state.mode==='class'?'Think → discuss → explain':lesson().stage%2?'B drives · A checks':'A drives · B checks'}</strong><span>${a}${bn(b||'আগে আলোচনা করো, তারপর উত্তর দেখো। তোমার সিদ্ধান্তের কারণ বলো।')}</span></div>`;}
function dsCards(){return `<div class="fourds">${D.ds.map(d=>`<div class="d-card"><strong>${d[0]}</strong><p>${d[1]}</p>${bn(d[2])}</div>`).join('')}</div>`;}
function field(id,label,placeholder='Write together. Your partner will review this.'){return `<label class="answer-label" for="${id}">${label}</label><textarea class="answer" id="${id}" data-text="${id}" rows="3" placeholder="${esc(placeholder)}">${esc(lesson().text[id]||'')}</textarea>`;}
function reveal(id,label,html){const open=!!lesson().reveals[id];return `<div class="reveal"><button data-reveal="${id}" aria-expanded="${open}" aria-controls="reveal-${id}">${open?'Hide':label}</button><div class="reveal-content" id="reveal-${id}" ${open?'':'hidden'}>${html}</div></div>`;}
function facts(){return `<details><summary>Open the case evidence · use it to check claims</summary><div><ul class="fact-list">${work().facts.map(f=>`<li>${esc(f)}</li>`).join('')}</ul><p class="small">All people, notices, opportunities, and events in these cases are fictional.</p></div></details>`;}
function words(){return `<details><summary>Language help · words & speaking frames</summary><div><div class="vocab">${work().words.map(v=>`<div><strong>${esc(v[0])}</strong> — ${esc(v[1])}<br><em>${esc(v[2])}</em>${bn(v[3])}</div>`).join('')}</div><div class="frame">${work().frames.map(f=>`<p>${esc(f)}</p>`).join('')}</div><p class="small">Clarify an idea briefly in Bangla if useful, then explain the decision in English. Adapt these frames.</p></div></details>`;}
function note(html){return `<details class="teacher-note"><summary>Teacher cue</summary><div>${html}</div></details>`;}
function quiz(group,questions){const l=lesson(),checked=!!l.checked[group];return `<div class="quiz">${questions.map((q,i)=>{const id=`${group}-${i}`,chosen=l.answers[id],right=chosen===q[2];return `<div class="question"><fieldset><legend>${i+1}. ${esc(q[0])}</legend><div class="options">${q[1].map((o,j)=>`<label class="option"><input type="radio" name="${id}" data-answer="${id}" data-group="${group}" value="${j}" ${chosen===j?'checked':''}><span>${esc(o)}</span></label>`).join('')}</div></fieldset>${checked?`<div class="feedback ${right?'':'bad'}"><strong>${right?'Supported decision.':'Reconsider this decision.'}</strong> ${esc(q[3])}${right?'':`<p><strong>Worked answer:</strong> ${esc(q[1][q[2]])}</p>`}</div>`:''}</div>`;}).join('')}<div class="check-row"><button class="primary" data-check="${group}">Check decisions</button><span class="small">${checked?`${questions.filter((q,i)=>l.answers[`${group}-${i}`]===q[2]).length} / ${questions.length} supported decisions`:'Choose every answer first.'}</span></div><div id="quiz-status-${group}" class="small" role="status"></div></div>`;}
function phone(user,ai,composerId){const p=state.provider,l=lesson();l.seen[p]=true;return `<div class="provider-tabs" role="group" aria-label="Practice interface style">${['ChatGPT','Claude','Gemini'].map(x=>`<button data-provider="${x}" aria-pressed="${p===x}">${x}</button>`).join('')}</div><p class="small">Interface practice · ${Object.keys(l.seen).length}/3 explored. The <strong>same authored example</strong> appears in each style; this is not a model comparison.</p><div class="phone ${p.toLowerCase()}"><div class="phone-head"><button class="phone-menu" data-tour="history" aria-label="Learn about chat history">☰</button><span class="phone-title">${p}</span><span class="sim-label">Teaching simulation</span></div><div class="phone-body"><div class="chat-user">${esc(user)}</div>${ai?`<div class="chat-ai"><div class="speaker">${p} · scripted example</div>${ai}</div>`:''}</div>${composerId?`<div class="composer"><label class="sr-only" for="${composerId}">Your practice message</label><textarea id="${composerId}" data-text="${composerId}" placeholder="Type your practice message. Nothing is sent to an AI.">${esc(l.text[composerId]||'')}</textarea><div class="composer-bottom"><button data-tour="attach" aria-label="Practice attaching the fictional fact sheet">＋</button><button data-tour="voice">Dictation tip</button><button class="primary" data-send="${composerId}">Save draft ↑</button></div><div class="small" id="compose-status-${composerId}">${l.checks[`saved-${composerId}`]?'Draft saved in this tab. Compare below.':'Practice only · no live AI connection'}</div></div>`:''}<div class="phone-foot">Simplified interface. Real controls vary by version, device, and account.</div></div>`;}
function poster(flawed=false){return `<figure class="poster ${flawed?'flawed':''}"><div class="poster-copy"><span class="kicker">${flawed?'Official university recruitment event':'Free peer-led workshop'}</span><h3>Career Steps</h3><p>${flawed?'Guaranteed overseas jobs & visas!':'Compare local and overseas opportunities'}</p></div><img src="assets/workshop-illustration.png" alt="AI-generated illustration of four fictional adult South Asian students discussing around a table with notebooks and one phone." width="1254" height="1254" loading="lazy"><figcaption><strong>18 November · 3:00–4:30 pm</strong><br>Room 105${flawed?'':'<br><span class="small">AI-generated illustration; fictional people.<br>Classroom sample — fictional event.</span>'}</figcaption></figure>`;}
function calculator(fixed){const c=lesson().calc;return `<div class="card calculator"><div class="eyebrow">${fixed?'REPAIRED LOCAL DEMO':'INTENTIONALLY FLAWED DEMO'}</div><h3>Workshop contribution</h3><p class="small">Compare actual and expected results. This demo does not collect money or send data.</p><div class="calc-fields">${[['room','Room cost (BDT)'],['materials','Material cost (BDT)'],['people','Attendees']].map(([id,label])=>`<label for="calc-${id}">${label}<input id="calc-${id}" data-calc="${id}" inputmode="${id==='people'?'numeric':'decimal'}" type="number" step="any" value="${esc(c[id])}"></label>`).join('')}</div><button data-calculate="${fixed?'fixed':'flawed'}" class="primary">Calculate</button><output id="calc-result" class="feedback" aria-live="polite">${esc(lesson().calcResult||'Try 600, 400, and 5.')}</output>${fixed?'<p class="small">Rounding up may create a small surplus. Agree how to use it.</p>':''}</div>`;}
function artifact(){const w=work();return w.id==='image'?poster():w.id==='code'?calculator(true):`<article class="cv"><div class="eyebrow">${w.id==='document'?'CORRECTED DRAFT · DETAILS STILL TO CONFIRM':'WORKED OUTPUT · FICTIONAL CASE'}</div>${prose(w.improved)}</article>`;}
function intro(){const w=work();return `<p class="stage-intro">${esc(w.intro)}</p><div class="lesson-purpose"><span>${esc(w.category)}</span><span>English: ${esc(w.focus)}</span><span>Workshop ${W.indexOf(w)+1} of 6 · 45 minutes</span></div>${pair('Read your own role first. A asks; B supplies the missing information. Agree what a good result must do.','প্রথমে নিজের ভূমিকা পড়ো। A প্রশ্ন করবে, B প্রয়োজনীয় তথ্য দেবে। ভালো ফল কেমন হবে তা ঠিক করো।')}<div class="grid"><div class="card"><div class="eyebrow">INFORMATION GAP · TAKE TURNS WITH THE PHONE</div><h3>${esc(w.student)}</h3><p>A reads A, then passes the phone to B to read B. Close your card before passing. Explain your information to your partner.</p>${reveal('roleA','Read Partner A’s card',`<p>${esc(w.roleA)}</p>`)}${reveal('roleB','Read Partner B’s card',`<p>${esc(w.roleB)}</p>`)}${field('success','Together: what must a good result do?','Our result needs to ___ because ___.')}${reveal('success-model','Compare with one possible goal',`<div class="feedback">${esc(w.goal)}</div>`)}</div><div><div class="card tint"><div class="eyebrow">FOUR HABITS · RETURN TO THEM THROUGHOUT</div>${dsCards()}</div>${words()}</div></div><p class="small">One workflow per 45-minute lesson. Choose another from the menu when ready; these six workshops form a short course.</p>${note('<p>Give partners about 30 seconds each to read privately. Listen for questions retrieving missing details. Accept equivalent wording; meaningful questions matter more than reciting a frame.</p>')}`;}
function divide(){return `<p class="stage-intro">Decide the goal before opening an AI. Divide the work according to the evidence, the tool, and the responsibility.</p>${pair('Choose together. The checker asks “Why should that person or tool do this part?”')}<div class="grid"><div class="card">${quiz('delegate',work().delegation)}</div><div><div class="card tint"><h3>Choose how to work</h3><p><strong>Automation:</strong> AI performs a bounded task you set, such as rewording a sentence.</p><p><strong>Augmentation:</strong> you and AI develop the work through questions, checking, and revision. This is our main pattern.</p><p><strong>Agency:</strong> you configure AI to carry out future tasks independently. This needs clear limits and checks; it is not needed here.</p><p class="frame">“I would delegate ___, but keep responsibility for ___ because ___.”</p>${bn('AI-এর সাহায্য নিলেও কোন সিদ্ধান্তের দায়িত্ব তোমার থাকবে তা বলো।')}</div>${facts()}${words()}</div></div>${note('<p>These choices fit the stated case. Accept a different division if learners justify capability, a suitable check, and who retains responsibility. Avoid universal rules about which tool or person is always best.</p>')}`;}
function brief(){const w=work();return `<p class="stage-intro">Describe the <strong>product</strong>, the <strong>process</strong>, and the AI’s <strong>performance</strong> as a collaborator.</p>${pair('A suggests a brief aloud. B asks for a missing detail. Type 3–5 sentences. Explore all three interface styles.')}<div class="grid"><div><div class="card"><div class="eyebrow">PLAN YOUR MESSAGE</div>${Object.entries(w.brief).map(([k,v])=>`<h3>${k[0].toUpperCase()+k.slice(1)}</h3><p>${esc(v)}</p>`).join('')}<p class="frame">“Create ___ for ___. First ___. Use only ___. Act as ___ and tell me if ___.”</p>${bn('ফল, কাজের ধাপ, এবং AI-এর ভূমিকা—এই তিনটি বিষয়ে নির্দেশ দাও।')}</div>${facts()}</div><div>${phone('I need help with this task. Where should I start?','<p>Tell me the goal, the evidence I should use, and how you want us to work together.</p>','prompt')}${reveal('model-prompt','Compare with the worked message',`<div class="feedback">${prose(w.prompt)}</div><p class="small">Find one instruction about the result, one about the process, and one about behaviour. Different wording can work.</p>`)}${reveal('clarification','Continue the worked conversation',`<div class="conversation"><p><strong>AI asks:</strong> ${esc(w.clarification)}</p><p><strong>The student answers:</strong> ${esc(w.humanReply)}</p></div><p class="checkpoint">This clarification becomes evidence at the next station.</p>`)}</div></div>${note('<p>Saved writing does not generate a response; these are authored examples. Switching interface styles retains our simulation. In a real new chat or product, re-establish the relevant context. Ask learners to identify all three Ps without copying the model prompt.</p>')}`;}
function inspect(){const w=work();return `<p class="stage-intro">The assistant received the brief and clarification. Keep useful parts, find problems, and check whether it followed the agreed process.</p>${pair('The driver reads the output. The checker names supporting evidence or a missing check. Use “The evidence says…”')}<div class="grid"><div>${phone(w.humanReply,prose(w.draft))}${w.id==='image'?poster(true):w.id==='code'?calculator(false):''}${facts()}</div><div class="card">${quiz('audit',w.audits)}${field('evidence','Write one claim beside supporting or contradicting evidence.','The draft says ___. The source says ___. Therefore ___.')}</div></div>${words()}${note('<p>Distinguish product (content), process (whether constraints affected the work), and performance (the assistant’s behaviour as a collaborator). Also recognise useful work. A model explanation is not independent verification.</p>')}`;}
function repair(){const w=work();return `<p class="stage-intro">Name what to keep, what to change, and how the next result should be checked.</p>${pair('B explains a problem precisely. A turns it into a follow-up. Then A reads the revised English and B checks the meaning.')}<div class="grid"><div>${phone('I have reviewed your draft. Here is what needs to change…','', 'repair')}${reveal('repair-model','Compare with the worked follow-up',`<div class="feedback">${prose(w.repair)}</div>`)}${facts()}</div><div class="card"><div class="eyebrow">NOTICE THE ENGLISH</div><h3>${esc(w.focus)}</h3><div class="language-before"><span>Before</span><p>${esc(w.language.before)}</p></div><div class="language-after"><span>After</span><p>${esc(w.language.after)}</p></div><p>${esc(w.language.notice)}</p>${bn(w.language.bn)}${field('language',esc(w.language.task))}${reveal('language-model','See one natural version',`<div class="feedback">${esc(w.language.model)}</div><p class="small">Alternatives work if they are accurate, natural, and fit the purpose.</p>`)}</div></div>${reveal('improved','Reveal the revised worked output',`<div class="grid"><div>${artifact()}</div><div class="card tint"><h3>What changed, and why?</h3><p>${esc(w.evidence)}</p><p class="frame">“The revised version ___, which is better because ___.”</p><p>Check the original goal again. A revision can introduce another error.</p></div></div>`)}${note('<p>After meaning is clear, recast one unnatural phrase and have the learner re-use it. The goal is a better message. The code demo is authored local code; it never executes learner input as code.</p>')}`;}
function own(){const w=work(),l=lesson(),ready=w.release.every((_,i)=>l.checks[`release-${i}`]);return `<p class="stage-intro">AI contributes to a result. A person remains responsible for how it is used.</p>${pair('For each check, explain how you would carry it out. Tick it after your partner can describe the check.')}<div class="grid"><div>${artifact()}</div><div><div class="card"><div class="eyebrow">DILIGENCE · FROM CREATION TO USE</div><h3>Your review plan</h3><div class="checklist">${w.release.map((t,i)=>`<label><input type="checkbox" data-tick="release-${i}" ${l.checks[`release-${i}`]?'checked':''}><span>${esc(t)}</span></label>`).join('')}</div><p class="small">Ticks record discussion, not proof of real-world checks.</p><button class="primary" data-release ${ready?'':'disabled'}>Explain our readiness decision</button>${l.reveals.readiness?`<div class="feedback"><strong>Human decision:</strong> ${w.id==='document'?'Not ready to circulate: contact and emergency procedure still need confirmation.':'Ready for further human review. Real use still needs the checks you described.'}</div>`:''}</div><div class="card tint"><h3>Describe AI’s contribution honestly</h3><p>${esc(w.disclosure)}</p><p class="small">A sample process note, not a universal requirement to put this wording on every CV or email. Follow the actual recipient’s instructions and never misrepresent authorship.</p></div><button data-download="artifact">Download worked output</button></div></div>${note('<p>Creation diligence: tools and information. Transparency: a truthful account of assistance suited to the context. Deployment: checks and responsibility for use. These also apply earlier. The document case correctly remains “not ready.”</p>')}`;}
function transfer(){const w=work();return `<p class="stage-intro">Apply all four Ds to a changed situation. Your decisions must fit the new brief.</p>${pair('2 minutes: plan. 4 minutes: create. 2 minutes: challenge. 2 minutes: revise and report in English.','২ মিনিট পরিকল্পনা, ৪ মিনিট উত্তর তৈরি, ২ মিনিট যাচাই, ২ মিনিট সংশোধন ও ইংরেজিতে উপস্থাপন।')}<div class="card transfer-brief"><div class="eyebrow">NEW BRIEF · LESS SUPPORT</div><h3>${esc(w.transfer)}</h3></div><div class="grid"><div class="card">${field('transfer-delegate','1 · Delegation: who does which part, and why?','We will ___. AI can ___ because ___.')}${field('transfer-description','2 · Description: write the actual new message or mini-output.','Create ___ for ___. Use ___. First ___.')}${field('transfer-discernment','3 · Discernment: name two evidence checks or test cases.','Compare ___ with ___. If ___, it should ___.')}${field('transfer-diligence','4 · Diligence: what must happen before use?','Before sharing or using it, we will ___.')}</div><div><div class="card tint"><h3>The partner’s challenge</h3><ul class="fact-list"><li>What do you know? What are you assuming?</li><li>Where could AI change the meaning?</li><li>How would you know the output works?</li><li>Can you explain that in simpler English?</li></ul>${field('transfer-revision','Improve one sentence after the challenge.','Before: ___\nAfter: ___\nI changed it because ___.')}</div>${words()}${reveal('transfer-model','Compare after your own attempt',`<div class="feedback"><h3>One defensible approach</h3><p>${esc(w.transferModel)}</p></div><p class="small">Judge your response against the brief, not its similarity to this example.</p>`)}</div></div>${note('<p>Listen for negotiation: a question, a reason, a revision. Require an actual message or mini-output. B1 pairs can plan briefly in Bangla before reporting in English; B2 pairs can hide frames and defend an alternative.</p>')}`;}
function exit(){const w=work(),l=lesson();let score=0,total=0;for(const [g,qs] of [['delegate',w.delegation],['audit',w.audits],['exit',[w.exit]]])for(let i=0;i<qs.length;i++){total++;if(l.checked[g]&&l.answers[`${g}-${i}`]===qs[i][2])score++;}return `<p class="stage-intro">Make a useful decision and explain it clearly. AI judgement and English both count.</p>${pair('A gives a 45-second decision pitch. B gives one strength and one specific improvement. Swap and repeat.')}<div class="grid"><div class="card">${quiz('exit',[w.exit])}<div class="end-score">${score} / ${total}</div><p class="small">Current checked decisions. This is practice feedback, not a score for your writing or a proficiency certificate.</p></div><div class="card tint"><h3>Your decision pitch</h3><p class="frame">“Our goal was ___. We gave AI ___ and kept ___. We noticed ___ because ___. We changed ___. Before use, we would ___.”</p>${field('pitch','Make speaking notes, then look away and explain.','Use your own words. Aim for 45 seconds.')}${field('feedback','Partner feedback: one strength + one next step.','You were clear when ___. Next time, ___.')}</div></div><div class="card"><h3>Peer check · give an example for each tick</h3><div class="fourds">${[['I justified a division of work.','I checked an AI result with evidence or a test.'],['I gave specific instructions and improved them.','I named a responsibility before use.'],['I used accurate task vocabulary.','I connected reasons with because, so that, or if.'],['I asked and answered a useful question.','I revised a sentence without changing facts.']].map((row,i)=>`<div class="d-card"><strong>${i<2?'AI judgement':'English communication'}</strong>${row.map((t,j)=>`<label class="peer-item"><input type="checkbox" data-tick="peer-${i}-${j}" ${l.checks[`peer-${i}-${j}`]?'checked':''}>${t}</label>`).join('')}</div>`).join('')}</div><div class="download-row"><button class="primary" data-download="record">Download our learning record</button><button data-print>Print this station</button><button data-reset>Restart this workflow</button></div><p class="small">Notes stay in this browser tab. Download before closing. Nothing is sent to an AI or teacher.</p></div>${note('<p>Assess spoken explanations and revisions, not only selected answers. Use the two separate rubrics in the teacher guide. A learner can demonstrate strong AI judgement while still needing language support.</p>')}`;}
const bodies=[intro,divide,brief,inspect,repair,own,transfer,exit];
function render(){const l=lesson(),w=work();document.body.classList.toggle('bangla',state.bangla);document.body.classList.toggle('classroom',state.mode==='class');$('mode').value=state.mode;$('bangla').setAttribute('aria-pressed',String(state.bangla));$('workflow').innerHTML=W.map((x,i)=>`<option value="${x.id}" ${x.id===w.id?'selected':''}>${i+1}. ${esc(x.title)}</option>`).join('');$('stations').innerHTML=shorts.map((s,i)=>`<button data-go="${i}" ${l.stage===i?'aria-current="step"':''}><span class="num">0${i+1}</span>${s}${l.visited[i]&&i!==l.stage?'<span class="done" aria-label="Visited">·</span>':''}</button>`).join('');const s=D.stages[l.stage];$('position').textContent=`STATION ${l.stage+1} / 8 · ${s.mins} MIN`;$('stage').innerHTML=`<div class="tags"><span class="tag workflow-tag">${esc(w.title)}</span>${s.ds.map(d=>`<span class="tag">${d}</span>`).join('')}</div><h2 class="stage-title" tabindex="-1">${titles[l.stage]}</h2>${bodies[l.stage]()}`;$('prev').disabled=l.stage===0;$('next').disabled=l.stage===7;$('progress-label').textContent=`${l.stage+1} of 8 · ${w.category}`;document.title=`${w.title} · AI Fluency Lab · Dialogue`;save();}
function focusStage(){document.querySelector('.stage-title').focus({preventScroll:true});$('lesson').scrollIntoView({block:'start'});}
function go(i){const l=lesson();l.stage=Math.max(0,Math.min(7,i));l.visited[l.stage]=true;l.calcResult=null;resetTimer();render();focusStage();updateHash();}
function switchWork(id){if(!W.some(w=>w.id===id))return;state.workflow=id;resetTimer();render();focusStage();updateHash();}
function updateHash(){history.replaceState(null,'',`#${state.workflow}/${lesson().stage+1}`);}
function fromHash(){const [id,n]=location.hash.slice(1).split('/');if(W.some(w=>w.id===id)){state.workflow=id;if(/^[1-8]$/.test(n||'')){lesson().stage=Number(n)-1;lesson().visited[lesson().stage]=true;}}}
function clockText(){$('time').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;}
function stopTimer(){clearInterval(timerId);ticking=false;$('timer-toggle').textContent='Start timer';}
function resetTimer(){stopTimer();remaining=D.stages[lesson().stage].mins*60;clockText();}
function dialog(title,html){$('info-title').textContent=title;$('info-body').innerHTML=html;$('info').showModal();}
function tour(kind){if(kind==='attach')dialog('Attach only what the task needs',`<p>In a real AI app, an attachment supplies context. Here is our fictional case sheet.</p><div class="attachment">Case facts · sample attachment</div><ul>${work().facts.map(f=>`<li>${esc(f)}</li>`).join('')}</ul><p>Paste relevant extracts or attach a permitted file. Check that AI read it correctly. Leave out unnecessary identity documents and other people’s private information.</p><p class="small">This button does not access your files.</p>`);else if(kind==='voice')dialog('Speak → check → send','<p>Keyboard dictation can help you draft on a phone. Check the transcript before sending, especially names, numbers, “not,” and Bangla–English switches.</p><p><strong>Try aloud:</strong> “Use only my facts. Do not invent experience. Ask if anything is missing.”</p><p>This lesson does not activate a microphone. Use your keyboard’s dictation if you choose. Controls vary across apps and accounts.</p>');else dialog('Keep the right context','<p>Use chat history to return to earlier work. In a follow-up, check what context is still available.</p><p>Moving to a different product does not automatically move your chat. Supply the goal, selected evidence, decisions made, and what you need next. Check privacy before copying.</p><p>Our style selector keeps the same teaching example. It does not connect to an account.</p>');}
function checkGroup(g){const qs=g==='delegate'?work().delegation:g==='audit'?work().audits:[work().exit];if(qs.some((q,i)=>lesson().answers[`${g}-${i}`]===undefined)){$(`quiz-status-${g}`).textContent='Choose an answer for every question first.';say('Choose an answer for every question first.');return;}lesson().checked[g]=true;render();document.querySelector(`[data-check="${g}"]`)?.focus({preventScroll:true});say('Read the feedback after each question with your partner.');}
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);say('Download prepared.');}
function record(){const w=work(),l=lesson();return `AI FLUENCY LAB — ${w.title}\nFictional classroom case · ${w.student}\nEnglish goal: ${w.focus}\n\nYOUR WRITING\n${Object.entries(l.text).map(([k,v])=>`${k.toUpperCase()}\n${v}`).join('\n\n')}\n\nDECISIONS\n${[['delegate',w.delegation],['audit',w.audits],['exit',[w.exit]]].flatMap(([g,qs])=>qs.map((q,i)=>`${q[0]}\nSelected: ${q[1][l.answers[`${g}-${i}`]]||'Not answered'}\n${l.checked[g]?`Worked answer: ${q[1][q[2]]}\n${q[3]}`:'Not checked'}`)).join('\n\n')}\n\nREVIEW PLAN\n${w.release.map((t,i)=>`${l.checks[`release-${i}`]?'[discussed]':'[not discussed]'} ${t}`).join('\n')}\n\nPractice notes, not a proficiency certificate.\nFramework: Rick Dakan, Joseph Feller, and Anthropic.\n`;}
function sources(){return `<p>Framework terminology and teaching approach: <strong>Rick Dakan, Joseph Feller, and Anthropic</strong>. An independent teaching exercise, not endorsed by Anthropic, OpenAI, Google, or either university.</p>${D.sourceLinks}<h3>Supplied materials consulted</h3><ul><li>AI Fluency for Students: framework and career transcripts.</li><li>Teaching AI Fluency: Description–Discernment loop; Description and Diligence assessment matrices.</li><li>The practical framework overview was consulted, not reproduced. Its file name and printed version differ.</li></ul><p>New fictional cases, Bangla glosses, ESL tasks and scripted replies form this educational adaptation. © 2026 Dialogue lesson adaptation. Course-based lesson text is shared under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">CC BY-NC-SA 4.0</a>. Source course materials © 2025 Rick Dakan, Joseph Feller, and Anthropic, CC BY-NC-SA 4.0. Third-party trademarks remain their owners’.</p><p>The illustration is AI-generated and depicts fictional people. Event copy is added separately. Product help pages consulted 7 September 2026; controls may change.</p><p>No live AI replies, uploads, accounts, external fonts, or tracking scripts. Written practice uses only this tab’s session storage where available.</p>`;}
function guide(){return `<p><strong>Six 45-minute workshops, one per lesson.</strong> Each includes a complete workflow and a specific English outcome.</p><div class="teacher-actions"><button data-fullscreen>Toggle fullscreen</button><a href="teacher-guide.txt" download>Download full teacher guide & keys</a></div><table><thead><tr><th>Workflow</th><th>English outcome</th></tr></thead><tbody>${W.map(w=>`<tr><td>${esc(w.title)}</td><td>${esc(w.focus)}</td></tr>`).join('')}</tbody></table><h3>45-minute sequence</h3><table><tbody>${shorts.map((s,i)=>`<tr><td>${i+1}. ${s}</td><td>${D.stages[i].mins} min</td></tr>`).join('')}</tbody></table><h3>Classroom and pairs</h3><p>Classroom mode enlarges text and adds teacher cues. Project one station at a time; invite predictions before revealing. In pairs, share one phone and swap driver/checker each station. There is no live room or synchronised control. Use station links to direct the class.</p><h3>Task-based English</h3><p>Pre-task: information gap and questions. Task: negotiate and create a message. Planning: use evidence and language support. Report: justify a decision. Language focus: notice, practise, and apply the form in a new situation.</p><p>B1: allow brief Bangla clarification and rehearsal with frames. B2: hide frames, require a counterargument, and defend an alternative. Give language feedback after the meaning is understood.</p><h3>Two separate rubrics</h3><p>Score each criterion 0 = not yet demonstrated, 1 = with support, 2 = independently with concrete evidence.</p><ul><li><strong>AI / 8:</strong> justified delegation; a specific brief; evidence-based evaluation and revision; responsibility before use.</li><li><strong>English / 8:</strong> task vocabulary; connected reasons; useful questions and responses; meaningful language revision.</li></ul><p>Assess the spoken explanation and created messages. Multiple-choice scores are practice only. Accept defensible alternatives; do not reward copying.</p><h3>Three products, one teaching conversation</h3><p>Explore each interface at station 3. Replies are scripted and deliberately identical across styles. Saved messages do not generate AI replies. For a later real-tool lesson, use fictional data, re-establish context in each product, and compare actual outputs using the same evidence.</p><h3>The two loops</h3><p>Delegation and Diligence frame purpose, tools, information, and responsibility. Description and Discernment repeat through brief → response → evidence → revision. All four habits recur throughout each workflow.</p><h3>Paper and connectivity</h3><p>The full guide includes role cards, facts, tasks and keys for all cases. Print this station prints the current view. Loaded core activities do not need a live service; a fresh visit still requires the site files.</p>`;}
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.text){lesson().text[t.dataset.text]=t.value;lesson().checks[`saved-${t.dataset.text}`]=false;save();}if(t.dataset.calc){lesson().calc[t.dataset.calc]=t.value;save();}});
document.addEventListener('change',e=>{const t=e.target;if(t.dataset.answer){lesson().answers[t.dataset.answer]=Number(t.value);const was=lesson().checked[t.dataset.group];lesson().checked[t.dataset.group]=false;save();if(was){render();document.querySelector(`input[data-answer="${t.dataset.answer}"][value="${t.value}"]`)?.focus({preventScroll:true});}}if(t.dataset.tick){lesson().checks[t.dataset.tick]=t.checked;save();if(t.dataset.tick.startsWith('release-')){const ready=work().release.every((_,i)=>lesson().checks[`release-${i}`]);document.querySelector('[data-release]').disabled=!ready;if(!ready){lesson().reveals.readiness=false;render();document.querySelector(`[data-tick="${t.dataset.tick}"]`)?.focus({preventScroll:true});}}}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.go!==undefined)go(Number(b.dataset.go));
 if(b.dataset.provider){state.provider=b.dataset.provider;lesson().seen[state.provider]=true;render();document.querySelector(`[data-provider="${state.provider}"]`)?.focus({preventScroll:true});}
 if(b.dataset.reveal){const id=b.dataset.reveal;lesson().reveals[id]=!lesson().reveals[id];if(id==='roleA'&&lesson().reveals[id])lesson().reveals.roleB=false;if(id==='roleB'&&lesson().reveals[id])lesson().reveals.roleA=false;render();document.querySelector(`[data-reveal="${id}"]`)?.focus({preventScroll:true});}
 if(b.dataset.check)checkGroup(b.dataset.check);if(b.dataset.tour)tour(b.dataset.tour);
 if(b.dataset.send){const id=b.dataset.send;if(!lesson().text[id]?.trim()){$(`compose-status-${id}`).textContent='Write a practice message first.';$(id).focus();return;}lesson().checks[`saved-${id}`]=true;save();$(`compose-status-${id}`).textContent='Saved in this tab. Compare with the worked example; no AI reply is generated.';say('Practice draft saved in this tab.');}
 if(b.dataset.release!==undefined){lesson().reveals.readiness=true;render();say('Readiness decision shown.');}
 if(b.dataset.calculate){const c=lesson().calc;if(b.dataset.calculate==='flawed')lesson().calcResult=`BDT ${Number(c.room)+Number(c.materials)/Number(c.people)} per attendee · intentionally flawed result`;else{const r=C.calculate(c.room,c.materials,c.people);lesson().calcResult=r.error||`BDT ${r.each} per attendee · total cost BDT ${r.total} · rounding surplus BDT ${r.surplus}`;}$('calc-result').textContent=lesson().calcResult;save();}
 if(b.dataset.download){if(b.dataset.download==='record')download(record(),`${state.workflow}-learning-record.txt`);else download(`${work().improved}\n\nPROCESS NOTE\n${work().disclosure}\n\nFICTIONAL CLASSROOM CASE\n`,work().output);}
 if(b.dataset.print!==undefined)window.print();
 if(b.dataset.reset!==undefined)dialog('Restart this workflow?',`<p>This clears writing, choices and checks for <strong>${esc(work().title)}</strong> in this tab. Other workflows are kept. Download a record first if needed.</p><button class="primary" data-confirm-reset>Restart this workflow</button>`);
 if(b.dataset.confirmReset!==undefined){state.lessons[state.workflow]=blank();$('info').close();go(0);}
 if(b.dataset.fullscreen!==undefined){if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>say('Fullscreen unavailable; Classroom mode still enlarges the lesson.'));}
});
$('prev').onclick=()=>go(lesson().stage-1);$('next').onclick=()=>go(lesson().stage+1);$('workflow').onchange=e=>switchWork(e.target.value);
$('bangla').onclick=()=>{state.bangla=!state.bangla;render();};$('mode').onchange=e=>{state.mode=e.target.value;render();};
$('timer-toggle').onclick=()=>{if(ticking){remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));stopTimer();clockText();return;}if(!remaining)remaining=D.stages[lesson().stage].mins*60;ticking=true;deadline=Date.now()+remaining*1000;$('timer-toggle').textContent='Pause';timerId=setInterval(()=>{remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));clockText();if(!remaining){stopTimer();say('Discussion time is up. Finish your thought and compare your answers.');}},250);};
$('timer-reset').onclick=resetTimer;$('close-info').onclick=()=>$('info').close();$('sources').onclick=()=>dialog('Sources & credits',sources());$('guide').onclick=()=>dialog('Teach AI fluency through English',guide());
window.addEventListener('hashchange',()=>{fromHash();resetTimer();render();focusStage();});
document.addEventListener('keydown',e=>{if(e.defaultPrevented||state.mode!=='class'||$('info').open||e.altKey||e.ctrlKey||e.metaKey||/INPUT|TEXTAREA|SELECT|BUTTON|SUMMARY/.test(e.target.tagName))return;if(e.key==='ArrowRight'&&lesson().stage<7){e.preventDefault();go(lesson().stage+1);}if(e.key==='ArrowLeft'&&lesson().stage>0){e.preventDefault();go(lesson().stage-1);}});
fromHash();resetTimer();render();
})();
