(() => {
'use strict';
const D=window.FLUENCY,W=window.WORKFLOWS,C=window.FluencyCore,esc=C.escapeHTML,$=id=>document.getElementById(id);
const titles=['See what good looks like','Who does which job?','Build a clear AI message','Skim, scan, compare','Repair the message','Check before use','Try a new situation','Show what you made'];
const shorts=['See the goal','Place the jobs','Build the brief','Compare evidence','Repair & say it','Check before use','New situation','Your results'];
const state={workflow:'cv',mode:'pair',bangla:false,provider:'ChatGPT',onboarding:!location.hash,lessons:{}};
const blank=()=>({stage:0,answers:{},checked:{},reveals:{},text:{},checks:{},visited:{0:true},seen:{},calc:{room:'600',materials:'400',people:'5'},calcResult:null});
try{const s=JSON.parse(sessionStorage.getItem('dialogue-fluency-v1'));if(s&&W.some(w=>w.id===s.workflow)){state.workflow=s.workflow;state.mode=s.mode==='class'?'class':'pair';state.bangla=!!s.bangla;state.provider=['ChatGPT','Claude','Gemini'].includes(s.provider)?s.provider:'ChatGPT';for(const w of W){const l=s.lessons?.[w.id];if(l&&Number.isInteger(l.stage)&&l.stage>=0&&l.stage<8)state.lessons[w.id]={...blank(),...l};}}}catch{}
const lesson=()=>state.lessons[state.workflow]||(state.lessons[state.workflow]=blank()),work=()=>W.find(w=>w.id===state.workflow);
const save=()=>{try{sessionStorage.setItem('dialogue-fluency-v1',JSON.stringify(state));}catch{}};
const say=t=>{$('announcement').textContent=t;};
let remaining=240,ticking=false,timerId=null,deadline=0;
const bn=t=>`<div class="bn" lang="bn">${esc(t)}</div>`,prose=t=>`<div class="prelines">${esc(t)}</div>`;
function phone(user,ai,composerId){const p=state.provider,l=lesson();l.seen[p]=true;return `<div class="provider-tabs" role="group" aria-label="Practice interface style">${['ChatGPT','Claude','Gemini'].map(x=>`<button data-provider="${x}" aria-pressed="${p===x}">${x}</button>`).join('')}</div><p class="small">Teaching simulation · same example in all three interfaces</p><div class="phone ${p.toLowerCase()}"><div class="phone-head"><button class="phone-menu" data-tour="history" aria-label="Learn about chat history">☰</button><span class="phone-title">${p}</span><span class="sim-label">Teaching simulation</span></div><div class="phone-body"><div class="chat-user">${esc(user)}</div>${ai?`<div class="chat-ai"><div class="speaker">${p} · scripted example</div>${ai}</div>`:''}</div>${composerId?`<div class="composer"><label class="sr-only" for="${composerId}">Your practice message</label><textarea id="${composerId}" data-text="${composerId}" placeholder="Type your practice message. Nothing is sent to an AI.">${esc(l.text[composerId]||'')}</textarea><div class="composer-bottom"><button data-tour="attach" aria-label="Practice attaching the fictional fact sheet">＋</button><button data-tour="voice">Dictation tip</button><button class="primary" data-send="${composerId}">Save draft ↑</button></div><div class="small" id="compose-status-${composerId}">${l.checks[`saved-${composerId}`]?'Draft saved in this tab. Compare below.':'Practice only · no live AI connection'}</div></div>`:''}<div class="phone-foot">Simplified interface. Real controls vary by version, device, and account.</div></div>`;}
function poster(flawed=false){return `<figure class="poster ${flawed?'flawed':''}"><div class="poster-copy"><span class="kicker">${flawed?'Official university recruitment event':'Free peer-led workshop'}</span><h3>Career Steps</h3><p>${flawed?'Guaranteed overseas jobs & visas!':'Compare local and overseas opportunities'}</p></div><img src="assets/workshop-illustration.png" alt="AI-generated illustration of four fictional adult South Asian students discussing around a table with notebooks and one phone." width="1254" height="1254" loading="lazy"><figcaption><strong>18 November · 3:00–4:30 pm</strong><br>Room 105${flawed?'':'<br><span class="small">AI-generated illustration; fictional people.<br>Classroom sample — fictional event.</span>'}</figcaption></figure>`;}
function calculator(fixed){const c=lesson().calc;return `<div class="card calculator"><div class="eyebrow">${fixed?'REPAIRED LOCAL DEMO':'INTENTIONALLY FLAWED DEMO'}</div><h3>Workshop contribution</h3><p class="small">Compare actual and expected results. This demo does not collect money or send data.</p><div class="calc-fields">${[['room','Room cost (BDT)'],['materials','Material cost (BDT)'],['people','Attendees']].map(([id,label])=>`<label for="calc-${id}">${label}<input id="calc-${id}" data-calc="${id}" inputmode="${id==='people'?'numeric':'decimal'}" type="number" step="any" value="${esc(c[id])}"></label>`).join('')}</div><button data-calculate="${fixed?'fixed':'flawed'}" class="primary">Calculate</button><output id="calc-result" class="feedback" aria-live="polite">${esc(lesson().calcResult||'Try 600, 400, and 5.')}</output>${fixed?'<p class="small">Rounding up may create a small surplus. Agree how to use it.</p>':''}</div>`;}
function artifact(){const w=work();return w.id==='image'?poster():w.id==='code'?calculator(true):`<article class="cv"><div class="eyebrow">${w.id==='document'?'CORRECTED DRAFT · DETAILS STILL TO CONFIRM':'WORKED OUTPUT · FICTIONAL CASE'}</div>${prose(w.improved)}</article>`;}
const V=window.makeVisualLessons({state,lesson,work,esc,bn,phone,artifact,calculator,poster,dialog,save,say,render,go,resetTimer});
function render(){
 const l=lesson(),w=work();document.body.classList.toggle('bangla',state.bangla);document.body.classList.toggle('classroom',state.mode==='class');document.body.classList.add('visual-first');
 $('mode').value=state.mode;$('bangla').setAttribute('aria-pressed',String(state.bangla));
 $('workflow').innerHTML=W.map((x,i)=>`<option value="${x.id}" ${x.id===w.id?'selected':''}>${i+1}. ${esc(x.title)}</option>`).join('');
 $('stations').innerHTML=`<button data-v="intro" ${state.onboarding?'aria-current="step"':''}><span class="num">▶</span>Start here · watch</button>`+shorts.map((s,i)=>`<button data-go="${i}" ${!state.onboarding&&l.stage===i?'aria-current="step"':''}><span class="num">0${i+1}</span>${s}</button>`).join('');
 const s=D.stages[l.stage];$('position').textContent=state.onboarding?'START HERE · 5 MIN':`STATION ${l.stage+1} / 8 · ${s.mins} MIN`;
 $('stage').innerHTML=state.onboarding?V.deck():`<div class="tags"><span class="tag workflow-tag">${esc(w.title)}</span></div><h2 class="stage-title" tabindex="-1">${titles[l.stage]}</h2>${V.render(l.stage)}`;
 document.querySelector('.lesson-nav').hidden=state.onboarding;
 $('prev').disabled=l.stage===0;$('next').disabled=l.stage===7;$('progress-label').textContent=`${l.stage+1} of 8`;
 document.title=`${w.title} · AI Fluency Lab · Dialogue`;save();
}
function focusStage(){document.querySelector('.stage-title')?.focus({preventScroll:true});$('lesson').scrollIntoView({block:'start'});}
function go(i){V.stop();state.onboarding=false;const l=lesson();l.stage=Math.max(0,Math.min(7,i));l.visited[l.stage]=true;l.calcResult=null;resetTimer();render();focusStage();updateHash();}
function switchWork(id){if(!W.some(w=>w.id===id))return;V.stop();state.workflow=id;state.onboarding=true;resetTimer();render();focusStage();updateHash();}
function updateHash(){history.replaceState(null,'',`#${state.workflow}/${state.onboarding?'start':lesson().stage+1}`);}
function fromHash(){const [id,n]=location.hash.slice(1).split('/');if(W.some(w=>w.id===id)){state.workflow=id;state.onboarding=n==='start';if(/^[1-8]$/.test(n||'')){lesson().stage=Number(n)-1;lesson().visited[lesson().stage]=true;}}}
function clockText(){$('time').textContent=`${String(Math.floor(remaining/60)).padStart(2,'0')}:${String(remaining%60).padStart(2,'0')}`;}
function stopTimer(){clearInterval(timerId);ticking=false;$('timer-toggle').textContent='Start timer';}
function resetTimer(){stopTimer();remaining=state.onboarding?300:D.stages[lesson().stage].mins*60;clockText();}
function dialog(title,html){$('info-title').textContent=title;$('info-body').innerHTML=html;$('info').showModal();}
function tour(kind){if(kind==='attach')dialog('Attach only what the task needs',`<p>In a real AI app, an attachment supplies context. Here is our fictional case sheet.</p><div class="attachment">Case facts · sample attachment</div><ul>${work().facts.map(f=>`<li>${esc(f)}</li>`).join('')}</ul><p>Paste relevant extracts or attach a permitted file. Check that AI read it correctly. Leave out unnecessary identity documents and other people’s private information.</p><p class="small">This button does not access your files.</p>`);else if(kind==='voice')dialog('Speak → check → send','<p>Keyboard dictation can help you draft on a phone. Check the transcript before sending, especially names, numbers, “not,” and Bangla–English switches.</p><p><strong>Try aloud:</strong> “Use only my facts. Do not invent experience. Ask if anything is missing.”</p><p>This lesson does not activate a microphone. Use your keyboard’s dictation if you choose. Controls vary across apps and accounts.</p>');else dialog('Keep the right context','<p>Use chat history to return to earlier work. In a follow-up, check what context is still available.</p><p>Moving to a different product does not automatically move your chat. Supply the goal, selected evidence, decisions made, and what you need next. Check privacy before copying.</p><p>Our style selector keeps the same teaching example. It does not connect to an account.</p>');}
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);say('Download prepared.');}
function record(){return `AI FLUENCY LAB — ${work().title}\nFictional classroom case\n${V.record()}\nOptional writing: ${lesson().text.extension||'Not attempted'}\n\nFramework: Rick Dakan, Joseph Feller, and Anthropic.\n`;}

function sources(){return `<p>Framework terminology and teaching approach: <strong>Rick Dakan, Joseph Feller, and Anthropic</strong>. An independent teaching exercise, not endorsed by Anthropic, OpenAI, Google, or either university.</p>${D.sourceLinks}<h3>Supplied materials consulted</h3><ul><li>AI Fluency for Students: framework and career transcripts.</li><li>Teaching AI Fluency: Description–Discernment loop; Description and Diligence assessment matrices.</li><li>The practical framework overview was consulted, not reproduced. Its file name and printed version differ.</li></ul><p>New fictional cases, Bangla glosses, ESL tasks and scripted replies form this educational adaptation. © 2026 Dialogue lesson adaptation. Course-based lesson text is shared under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="noopener">CC BY-NC-SA 4.0</a>. Source course materials © 2025 Rick Dakan, Joseph Feller, and Anthropic, CC BY-NC-SA 4.0. Third-party trademarks remain their owners’.</p><p>The illustration is AI-generated and depicts fictional people. Event copy is added separately. Product help pages consulted 7 September 2026; controls may change.</p><p>No live AI replies, uploads, accounts, external fonts, or tracking scripts. Written practice uses only this tab’s session storage where available.</p>`;}
function guide(){return `<p><strong>Watch → choose → build → say.</strong> The introduction takes 5 minutes; the eight activities take 40 minutes.</p><div class="teacher-actions"><button data-v="intro">Open the teaching slides</button><button data-fullscreen>Toggle fullscreen</button><a href="teacher-guide.txt" download>Download guide & keys</a></div><h3>Model the action before asking for words</h3><p>Use Start here. Show a poor and a better deliverable. Demonstrate the reading lenses: skim headings, scan for a detail, then compare the whole claim. Pause and ask students to point before asking them to speak.</p><h3>What the three Ps mean</h3><div class="v-ps"><div class="p-0"><h3>Product</h3><p>What to make</p><blockquote>“Draft a one-page CV.”</blockquote></div><div class="p-1"><h3>Process</h3><p>How to work</p><blockquote>“Ask about missing facts first.”</blockquote></div><div class="p-2"><h3>Performance</h3><p>How to behave as a collaborator</p><blockquote>“Be an honest editor.”</blockquote></div></div><h3>Pair routine</h3><p>A points and chooses. B checks the evidence and says why. Use the built sentence as support; swap roles at the next station. Listen plays device speech when available. “We practised aloud” is self-report, never a speaking score.</p><h3>Support fades gradually</h3><p>First compare examples and tap short choices. Next build the brief and repair message. Then assemble a sentence. The new-situation task offers a guided route and an optional editable sentence after success. Do not begin with blank-page writing.</p><h3>Feedback and rewards</h3><p>Correct choices add a visible component to the target, work plan, prompt, or evidence record. A retry gives a short cue. Supported claims, changed meaning, and claims with no evidence are distinct. Identical claims can be checked using any matching phrase. Alternative error locations are accepted when both reveal a real mismatch.</p><h3>Timing</h3><p>Teaching slides 5m; target 3m; delegation 4m; brief 5m; evidence 7m; repair 5m; diligence 3m; transfer 8m; report 5m.</p><h3>Assessment</h3><p>Separate AI judgement from English. For each use 0 = not demonstrated, 1 = with support, 2 = independent with evidence. AI /8: delegation, description, discernment, diligence. English /8: accurate task vocabulary, connected reasons, useful questions, meaningful revision. Activity stamps are completion feedback, not proficiency grades.</p><h3>Important distinctions</h3><p>Skimming and scanning locate evidence; they do not verify meaning by themselves. Compare the sentence, relationship, condition, and source. The three interfaces use the same scripted example. A new real chat needs relevant context again. There is no live AI, microphone recording, or teacher dashboard.</p>`;}

document.addEventListener('input',e=>{const t=e.target;if(t.dataset.text){lesson().text[t.dataset.text]=t.value;lesson().checks[`saved-${t.dataset.text}`]=false;save();}if(t.dataset.calc){lesson().calc[t.dataset.calc]=t.value;save();}});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;
 if(b.dataset.v){if(b.dataset.v==='intro'&&$('info').open)$('info').close();V.handle(b);updateHash();return;}
 if(b.dataset.go!==undefined)go(Number(b.dataset.go));
 if(b.dataset.provider){state.provider=b.dataset.provider;lesson().seen[state.provider]=true;render();document.querySelector(`[data-provider="${state.provider}"]`)?.focus({preventScroll:true});}
 if(b.dataset.tour)tour(b.dataset.tour);
 if(b.dataset.send){const id=b.dataset.send;if(!lesson().text[id]?.trim()){$(`compose-status-${id}`).textContent='Write a practice message first.';$(id).focus();return;}lesson().checks[`saved-${id}`]=true;save();$(`compose-status-${id}`).textContent='Saved in this tab. Compare with the worked example; no AI reply is generated.';say('Practice draft saved in this tab.');}
 if(b.dataset.calculate){const c=lesson().calc;if(b.dataset.calculate==='flawed')lesson().calcResult=`BDT ${Number(c.room)+Number(c.materials)/Number(c.people)} per attendee · intentionally flawed result`;else{const r=C.calculate(c.room,c.materials,c.people);lesson().calcResult=r.error||`BDT ${r.each} per attendee · total cost BDT ${r.total} · rounding surplus BDT ${r.surplus}`;}$('calc-result').textContent=lesson().calcResult;save();}
 if(b.dataset.download){if(b.dataset.download==='record')download(record(),`${state.workflow}-learning-record.txt`);else download(`${work().improved}\n\nPROCESS NOTE\n${work().disclosure}\n\nFICTIONAL CLASSROOM CASE\n`,work().output);}
 if(b.dataset.print!==undefined)window.print();
 if(b.dataset.reset!==undefined)dialog('Restart this workflow?',`<p>This clears writing, choices and checks for <strong>${esc(work().title)}</strong> in this tab. Other workflows are kept. Download a record first if needed.</p><button class="primary" data-confirm-reset>Restart this workflow</button>`);
 if(b.dataset.confirmReset!==undefined){state.lessons[state.workflow]=blank();$('info').close();go(0);}
 if(b.dataset.fullscreen!==undefined){if(document.fullscreenElement)document.exitFullscreen?.();else document.documentElement.requestFullscreen?.().catch(()=>say('Fullscreen unavailable; Classroom mode still enlarges the lesson.'));}
});
$('prev').onclick=()=>go(lesson().stage-1);$('next').onclick=()=>go(lesson().stage+1);$('workflow').onchange=e=>switchWork(e.target.value);
$('bangla').onclick=()=>{state.bangla=!state.bangla;render();};$('mode').onchange=e=>{state.mode=e.target.value;render();};
$('timer-toggle').onclick=()=>{if(ticking){remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));stopTimer();clockText();return;}if(!remaining)remaining=state.onboarding?300:D.stages[lesson().stage].mins*60;ticking=true;deadline=Date.now()+remaining*1000;$('timer-toggle').textContent='Pause';timerId=setInterval(()=>{remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000));clockText();if(!remaining){stopTimer();say('Discussion time is up. Finish your thought and compare your answers.');}},250);};
$('timer-reset').onclick=resetTimer;$('close-info').onclick=()=>$('info').close();$('sources').onclick=()=>dialog('Sources & credits',sources());$('guide').onclick=()=>dialog('Teach AI fluency through English',guide());
window.addEventListener('hashchange',()=>{V.stop();fromHash();resetTimer();render();focusStage();});
document.addEventListener('keydown',e=>{if(e.defaultPrevented||state.onboarding||state.mode!=='class'||$('info').open||e.altKey||e.ctrlKey||e.metaKey||/INPUT|TEXTAREA|SELECT|BUTTON|SUMMARY/.test(e.target.tagName))return;if(e.key==='ArrowRight'&&lesson().stage<7){e.preventDefault();go(lesson().stage+1);}if(e.key==='ArrowLeft'&&lesson().stage>0){e.preventDefault();go(lesson().stage-1);}});
fromHash();resetTimer();render();
})();
