/* One concrete, authored teaching demonstration. No real bookings or AI calls. */
window.renderBookingStory = ({state,persist,render,bangla}) => {
  if(!state.bookingStory){state.bookingStory={page:0,booked:[]};state.done=false}
  const s=state.bookingStory, page=s.page;
  const titles=['One appointment. Two customers.','Try the broken app.','Watch the AI’s fix.','Test the fix yourself.','Show the AI what is still wrong.','Try the changed app.','What made this fix better?'];
  const instructions=['Nadia can teach ONE student at 4 pm.','Tap Book on both phones.','The AI changes the button. Will that solve the problem?','Again: tap Book on both phones.','Choose the problem you just saw.','Tap Book on both phones again.','Compare what the customers received.'];
  const bookings=s.booked||[], repaired=page>=5;
  const phone=(name,i)=>{const clicked=bookings.includes(i),first=bookings[0]===i;return `<article class="bs-phone"><div class="bs-phonebar">${name}’s phone</div><small>TutorTime</small><div class="bs-avatar">N</div><b>Nadia · English tutor</b><div class="bs-time">4:00 pm</div>${clicked?`<div class="bs-result ${repaired&&!first?'unavailable':''}">${repaired&&!first?'Choose another time':'✓ Booking confirmed'}</div>`:`<button data-book="${i}" class="primary" ${![1,3,5].includes(page)?'disabled':''}>Book 4 pm</button>`}${clicked&&page===3?'<small>Button disabled ✓</small>':''}</article>`};
  document.querySelector('#app').innerHTML=`<div class="toolbar"><button id="bs-home">← All lessons</button><span class="muted">A short worked example · ${page+1} / 7</span><button id="bs-replay">↺ Start again</button></div><section class="bs-story"><small>Watch → try → notice → steer → check</small><h1>${titles[page]}</h1><p class="bs-instruction">${instructions[page]}</p>${bangla?'<p class="bn" lang="bn">একটি সময়ে একজনই পড়তে পারবে। দুটি ফোনে বুক করে দেখুন।</p>':''}<div class="bs-goal"><span>👩‍🏫</span><div><b>Nadia has one place.</b><br>4 pm → <strong>1 student</strong></div></div><div id="screen">
  ${page===0?'<div class="bs-rule"><span>✓ One confirmation</span><span>✕ Two confirmations</span></div><p class="bs-caption">Your job: make sure the app keeps that promise.</p>':''}
  ${[1,3,5].includes(page)?`<div class="bs-phones">${phone('Rafi',0)}${phone('Mitu',1)}</div>${bookings.length===2?`<div class="bs-outcome ${repaired?'good':'bad'}" role="status"><b>${repaired?'1 place → 1 confirmation ✓':'1 place → 2 confirmations ✕'}</b><p>${repaired?'One student books. The other chooses another time.':'Both students expect the same lesson. Nadia cannot teach both.'}</p></div>`:''}`:''}
  ${page===2?'<div class="bs-chat"><small>Codex · simulated work update</small><p>“I’ll stop people clicking twice. After one click, I’ll switch off the Book button.”</p><div class="bs-button-demo"><span>Book 4 pm</span><b>→</b><span class="disabled">Book 4 pm</span></div></div><p class="bs-caption">But Rafi and Mitu each have their own phone.</p>':''}
  ${page===4?`<div class="bs-chat"><small>Codex</small><p>“The button switches off. Fixed!”</p></div><div class="bs-options"><button data-problem="0">Both phones still say “Booking confirmed”.</button><button data-problem="1">The button needs a different colour.</button></div>${s.wrong?'<p class="bs-outcome bad" role="status">A colour change would leave two students expecting one lesson. Look at the confirmations.</p>':''}${s.evidence?'<div class="bs-evidence">📌 Evidence attached: Rafi ✓ + Mitu ✓ → only 1 place</div><div class="bs-message"><small>Your direction to Codex</small><p>“Only one student can have this time. If it is taken, ask the other student to choose another time.”</p><button id="bs-steer" class="primary">Send this direction ↑</button></div>':''}`:''}
  ${page===5?'<div class="bs-chat"><small>Codex · new action</small><p>“I’ve changed how the app reserves the time. Now check it using both phones.”</p></div>':''}
  ${page===6?`<div class="bs-comparison"><div><small>Button change</small><b>Rafi ✓ &nbsp; Mitu ✓</b><span>2 promises · 1 place ✕</span></div><div><small>Booking change</small><b>One ✓ &nbsp; Other: choose again</b><span>1 promise · 1 place ✓</span></div></div><div class="bs-options"><button id="bs-understand">It changed what happens to the customers.</button><button id="bs-looks">It made the button look better.</button></div>${s.finalWrong?'<p class="bs-outcome bad" role="status">Look at the number of confirmations before and after.</p>':''}${state.done?'<div class="complete" role="status"><b>Check the result against the goal.</b><p>“Fixed” is a claim. Trying both phones gave you evidence.</p></div><div class="speech">Tell your partner: “The goal was ___. The first fix still ___. We checked by ___.”</div><details class="history"><summary>Optional: what changed in the code?</summary><p>The first patch controlled one button. The repair controls the shared appointment: checking and reserving it happen together, so two customers cannot take the same place. This example demonstrates that behavior; it does not test a real service.</p></details>':''}`:''}
  </div><div class="bs-nav">${page===6&&state.done?'<button id="bs-lesson">Continue the lesson →</button>':''}${page>0?'<button id="bs-back">← Back</button>':''}${[0,1,2,3,5].includes(page)?`<button id="bs-next" class="primary" ${[1,3,5].includes(page)&&bookings.length<2?'disabled':''}>${['Try the app →','Ask AI to fix it →','Test that idea →','Stop & steer the AI →','','Compare the results →'][page]}</button>`:''}</div><p class="muted">Fictional app and AI work updates. Nothing is booked or sent. No coding knowledge needed.</p></section>`;
  const save=()=>{persist();render()},advance=()=>{save();window.scrollTo({top:0,behavior:'auto'})},on=(id,fn)=>{const e=document.getElementById(id);if(e)e.onclick=fn};
  on('bs-home',()=>location.hash='');on('bs-lesson',()=>location.hash='build/4');
  on('bs-replay',()=>{state.bookingStory={page:0,booked:[]};state.done=false;save()});
  on('bs-next',()=>{s.page++;s.booked=[];advance()});
  on('bs-back',()=>{s.page--;s.booked=[];advance()});
  document.querySelectorAll('[data-book]').forEach(b=>b.onclick=()=>{const i=+b.dataset.book;if(!s.booked.includes(i))s.booked.push(i);save()});
  document.querySelectorAll('[data-problem]').forEach(b=>b.onclick=()=>{s.evidence=b.dataset.problem==='0';s.wrong=!s.evidence;save()});
  on('bs-steer',()=>{s.page=5;s.booked=[];advance()});
  on('bs-understand',()=>{state.done=true;s.finalWrong=false;save()});
  on('bs-looks',()=>{s.finalWrong=true;state.done=false;save()});
  document.querySelector('#teacher').innerHTML='<h3>One appointment, two customers</h3><p>7 minutes: show the one-place goal (1 min); pairs test the original app (1 min); predict and test the button fix (2 min); point to the two confirmations and steer (1 min); retest and explain (2 min).</p><p>Ask “How many places?” and “How many confirmations?” before naming discernment. Both partners should operate one customer phone. Repeat the final test in the opposite order: whichever student books first should get the place. Do not describe a server or an atomic operation until students understand the customer outcome.</p>';
};
