/* Original fictional cases. All outputs are authored teaching simulations. */
window.LAB_SESSIONS = [
 {id:'voice',icon:'✉',title:'Your name. Your responsibility.',tag:'Authorship · privacy · publication',person:'Rafi · final-year student, University of Rajshahi',goal:'Make claims you can explain. Protect people before you publish.',deliverable:'An evidence-backed contact plan and a responsible publication decision.',steps:[
  {title:'A beautiful email. A difficult call.',minutes:4,d:'Delegation',kind:'reveal',instruction:'Watch the email become a conversation.',bn:'ইমেইলের কথাগুলো কি নিজে ব্যাখ্যা করতে পারবেন?',frame:'The email promises ___. Rafi can explain ___.',cards:[['Rafi’s notes','Read the abstract only. Interested in student commuting. Has not used regression.'],['AI-written email','“Your regression method shaped my research. I would extend your model in Rajshahi.”'],['Professor’s reply','“Which assumption would you change? Explain your proposed method.”']],question:'What should Rafi do before sending?',options:['Learn enough to explain his interest and write his own message.','Ask AI to make the email sound less formal.','Send now; prepare if the professor replies.'],answer:0,feedback:['His first task is understanding. The correspondence should represent that understanding.','A different tone does not supply the missing understanding.','The unsupported claim has already been sent. Preparation belongs before the promise.'],teacher:'4 min: reveal one card at a time. Ask pairs to point to the exact promise. Treat the professor example as a fictional case, not evidence that style proves AI use.'},
  {title:'Match the promise to the evidence',minutes:6,d:'Discernment',kind:'inspect',instruction:'Tap a claim. Find what Rafi can actually support.',bn:'দাবির সঙ্গে প্রমাণ মিলান।',frame:'The message says ___. His notes only show ___.',rounds:[
   {source:'Read: abstract and conclusion. Could explain the research question.',claim:'“I have studied your complete paper in depth.”',options:['Supported','Too strong','Need a new font'],answer:1,repair:'“Your study of commuting interested me. I am reading the full paper.”'},
   {source:'Collected travel-time notes from 12 classmates. No statistical analysis yet.',claim:'“I developed a validated model of transport inequality.”',options:['Supported','Too strong','Need a new font'],answer:1,repair:'“I collected initial travel-time notes from 12 classmates.”'},
   {source:'Question in Rafi’s own notebook: Do longer commutes reduce club participation?',claim:'“I am curious whether commuting affects participation.”',options:['Supported','Too strong','Need a new font'],answer:0,repair:'Keep it. A modest, specific question can be entirely his own.'}],teacher:'6 min: Partner A reads the claim, B points to the source. Swap each round. Emphasise precision, not impressive vocabulary.'},
  {title:'Who should do this part?',minutes:5,d:'Delegation',kind:'sort',instruction:'Assign each job. Keep the professional judgment.',bn:'কোন কাজটি নিজের করা দরকার?',frame:'I keep ___ because the reader is judging my ___.',items:[
   {text:'Choose why this professor’s work matters to me',answer:'Me',why:'Your research interest must be yours to explain.'},
   {text:'Generate practice questions about a paragraph I have read',answer:'AI assists',why:'Questions can expose gaps without writing your correspondence.'},
   {text:'Invent a personal connection to make my email persuasive',answer:'Do not do',why:'Neither a human nor an AI should invent your experience.'},
   {text:'Write and approve my final inquiry in my own words',answer:'Me',why:'In this exercise the inquiry demonstrates your own professional communication.'}],teacher:'5 min: distinguish this context from an absolute ban on language tools. Disability accommodations and institutional rules may change permitted support; authorship and accurate claims still matter.'},
  {title:'Before the upload',minutes:6,d:'Diligence',kind:'privacy',instruction:'Remove what the AI does not need.',bn:'অপ্রয়োজনীয় ব্যক্তিগত তথ্য সরান।',frame:'The task needs ___. It does not need ___.',task:'Ask for feedback on the structure of a commuting survey. Classmates agreed to classroom discussion only.',fields:[{text:'Names and phone numbers',remove:true},{text:'Student ID numbers',remove:true},{text:'Exact home addresses',remove:true},{text:'Anonymous survey questions',remove:false},{text:'A classmate’s health explanation',remove:true}],consequence:'Removing names alone is not enough: an exact address or a rare health detail can identify someone. Use the blank questions, not the classmates’ responses.',teacher:'6 min: request only structural feedback on blank questions. Do not suggest anonymisation automatically supplies consent. No files are uploaded here.'},
  {title:'A coach, not a ghostwriter',minutes:6,d:'Description',kind:'build',instruction:'Build a request that protects Rafi’s thinking.',bn:'উত্তর নয়, সহায়তা চাইুন।',frame:'Ask me ___; do not ___; wait until ___.',groups:[
   {label:'Help',options:['Ask me one question about my research interest.','Write a convincing personal research interest.'],answer:0},
   {label:'Boundary',options:['Do not draft the email or invent experience.','Add methods that sound advanced.'],answer:0},
   {label:'Process',options:['Wait for my answer, then point out one unclear idea.','Give me a polished final message immediately.'],answer:0}],result:'Coach: “What question arose when you read the study?” → Rafi answers from his notebook → Coach points to one unclear term → Rafi revises his own explanation.',teacher:'6 min: pairs say the request aloud. Then one plays coach and asks the other a question. The deliverable is a contact plan, not a generated advisor email.'},
  {title:'The picture travels without you',minutes:6,d:'Diligence',kind:'reveal',instruction:'Follow a poster after someone shares it.',bn:'শেয়ার হওয়ার পরে ছবিটির অর্থ কী হয়?',frame:'A viewer may believe ___. We must show ___.',cards:[['Student club poster','A photorealistic AI image shows smiling “scholarship winners” outside a university.'],['Original caption','“Illustration of possible futures.”'],['A repost crops the caption','“These students won places through our paid service.”']],question:'Which redesign reduces the misleading claim?',options:['Use a clearly illustrated scene and put “illustration, not actual recipients” inside the artwork.','Keep the photo and add a tiny caption below the post.','Make the faces more realistic.'],answer:0,feedback:['The image and its embedded label travel together. Still check each distribution context and avoid unsupported outcome claims.','The demonstration already showed what happens when that caption disappears.','Realism strengthens the false impression of documented success.'],teacher:'6 min: draw or point to the crop boundary. Discuss truthful promotion and people represented in images; avoid implying a label cures every misleading claim.'},
  {title:'Tell the truth about the process',minutes:7,d:'Diligence',kind:'inspect',instruction:'Choose a statement that matches what happened.',bn:'কাজের প্রক্রিয়া সম্পর্কে সঠিক কথা বলুন।',frame:'AI helped with ___. I decided and checked ___.',rounds:[
   {source:'Rafi wrote his inquiry. AI asked practice questions. No AI wording was copied. A form asks how AI was used.',claim:'Which disclosure fits?',options:['“No AI was involved.”','“I wrote the inquiry; AI supplied practice questions.”','“AI wrote everything.”'],answer:1,repair:'Disclose the actual contribution when asked. Neither conceal it nor exaggerate it.'},
   {source:'A scholarship requires an independently written essay. AI drafted two paragraphs that the student lightly edited.',claim:'What now?',options:['Submit: editing makes every idea mine.','Use an AI detector to decide.','Rework independently under the rules; seek clarification if needed.'],answer:2,repair:'A detector score cannot establish compliance. The actual process and the stated rules matter.'}],teacher:'7 min: discuss downstream trust, interview follow-up and policy. Do not teach “avoid detection” or claim future detectors will prove authorship.'},
  {title:'Your name is on it',minutes:5,d:'Transfer',kind:'exit',instruction:'AI closed. Make your own decision, then compare reasons.',bn:'AI বন্ধ রেখে নিজের সিদ্ধান্ত ব্যাখ্যা করুন।',frame:'I can stand behind ___ because ___.',source:'A local NGO invites a 100-word statement of your interest. It permits feedback tools but says the ideas and final writing must be yours. You have genuine volunteering notes.',question:'Which workflow meets that brief?',options:['Write from notes → ask for unclear points → revise yourself → verify each claim.','Generate a statement → change the names → submit.','Copy an example → run a detector → submit if it passes.'],answer:0,feedback:['Now explain one claim you could support with an example from your own experience.','The final writing and ideas were delegated despite the stated requirement.','Detection is not evidence of authorship or truth.'],teacher:'5 min: independent 30-second explanation per student. Assess an owned claim, a justified boundary and a truthful process statement. Grammar accuracy is secondary to clear meaning.'}
 ]},
 {id:'learn',icon:'◉',title:'Leave with a stronger mind.',tag:'Metacognition · evidence · independent transfer',person:'Mitu · final-year student, Varendra University',goal:'Use AI to diagnose a gap. Prove you can apply the idea without it.',deliverable:'A learning cycle: attempt, diagnosis, bounded help, independent transfer.',steps:[
  {title:'Try before you ask',minutes:5,d:'Delegation',kind:'choice',instruction:'AI is closed. Look at the two groups.',bn:'আগে নিজে চেষ্টা করুন।',frame:'The result shows ___. It does not yet prove ___.',source:'Study club: 20 students chose an AI study app. Their average score rose 10 points. Another 20 students did not use it; their score rose 3 points. Students chose their own group.',question:'Does this prove the app caused the bigger gain?',options:['Yes: 10 is bigger than 3.','No: the groups may differ in motivation or study time.','No evidence can ever help.'],answer:1,feedback:['The difference is real in this example. Its cause is not established by these groups.','Keep that distinction: an observed difference is not automatically a causal effect.','Better comparisons can strengthen evidence; uncertainty does not make investigation pointless.'],teacher:'5 min: students commit before revealing feedback. Record confidence with fingers 1–3. Revisit confidence after the transfer task.'},
  {title:'Two kinds of help',minutes:4,d:'Discernment',kind:'reveal',instruction:'Watch what each learner does next.',bn:'সহায়তার পরে শিক্ষার্থী নিজে কী করতে পারে?',frame:'This helped finish ___. It did not show ___.',cards:[['Learner A','AI gives a perfect explanation. A copies it and recognises every sentence.'],['Learner B','AI asks: “Who chose the groups?” B draws two groups and identifies a difference.'],['A new example, AI closed','Both must decide whether a training programme caused higher pay.']],question:'What would show learning?',options:['A can repeat the original sentence.','B can explain the new example with evidence.','Both have long chat histories.'],answer:1,feedback:['Recall of wording alone does not show transfer.','A new independent application gives stronger evidence than a polished saved answer.','Chat length is not a measure of understanding.'],teacher:'4 min: do not claim a specific learning gain from the fictional comparison. The next independent task is the evidence.'},
  {title:'Name the gap',minutes:5,d:'Discernment',kind:'sort',instruction:'Choose what kind of help Mitu needs.',bn:'কোথায় আটকে গেছেন তা চিহ্নিত করুন।',frame:'I can ___. I still cannot ___.',labels:['Vocabulary help','Reasoning help','Independent check'],items:[
   {text:'“I do not understand the word ‘assigned’.”',answer:'Vocabulary help',why:'A short definition and example may be enough.'},
   {text:'“I know all the words, but why does choosing a group matter?”',answer:'Reasoning help',why:'Ask a question or draw a comparison; a translation alone will not resolve the idea.'},
   {text:'“The explanation seems clear. Can I apply it to a different case?”',answer:'Independent check',why:'Close the explanation and attempt a new problem before requesting feedback.'}],teacher:'5 min: avoid treating every difficulty as an English problem. Students distinguish word knowledge, conceptual reasoning and evidence of mastery.'},
  {title:'Build a tutor that waits',minutes:6,d:'Description',kind:'build',instruction:'Keep the next thinking step for yourself.',bn:'চিন্তার পরের ধাপটি নিজের জন্য রাখুন।',frame:'Give me one ___, then wait for my ___.',groups:[
   {label:'Goal',options:['Help me distinguish a difference from a cause.','Finish my assignment as quickly as possible.'],answer:0},
   {label:'Help size',options:['Give the whole solution first.','Ask one guiding question without revealing the answer.'],answer:1},
   {label:'Check',options:['After my attempt, give a new example for me to solve alone.','Tell me I understand if I say yes.'],answer:0}],result:'Tutor: “Could the students who chose the app already study more?” → You propose another explanation → Tutor asks how to compare fairly → You attempt a new case.',teacher:'6 min: Partner B acts as tutor and must wait after one question. Swap. The waiting rule is observable, not merely a line in a prompt.'},
  {title:'Stop the helpful shortcut',minutes:7,d:'Discernment',kind:'chain',instruction:'Continue useful help. Stop when the tutor takes over.',bn:'AI চিন্তার কাজটি নিয়ে নিলে থামান।',frame:'You are doing ___ for me. Instead, ask me ___.',steps:[
   {text:'“Which students chose to use the app?”',stop:false,why:'A focused question directs attention without giving the conclusion.'},
   {text:'“Draw one possible difference between the two groups.”',stop:false,why:'You still generate the alternative explanation.'},
   {text:'“Here is a finished paragraph. Memorise it for your assessment.”',stop:true,why:'The stated goal was independent reasoning, not reproducing an answer.'}],recovery:{question:'How should the tutor recover?',options:['Ask me to test my explanation on a different example.','Rewrite the paragraph in simpler English.','Add more academic phrases.'],answer:0,result:'New case: an optional workshop attracts students already interested in research. You must identify the alternative explanation.'},teacher:'7 min: students must justify both Continue decisions as well as the Stop. These are authored visible work notes, not private chain of thought.'},
  {title:'Check the tutor against a source',minutes:6,d:'Discernment',kind:'inspect',instruction:'Scan for the words that change the claim.',bn:'দাবির অর্থ বদলে দেয় এমন শব্দ খুঁজুন।',frame:'The tutor says ___. The source says ___.',rounds:[
   {source:'Methods card: “Participants chose whether to attend. Scores were measured before and after.”',claim:'AI: “Participants were randomly assigned.”',options:['Matches the source','Contradicts the source','A harmless wording change'],answer:1,repair:'“Chose” and “randomly assigned” describe different designs.'},
   {source:'Results card: “The participants in this small study improved. More research is needed.”',claim:'AI: “This method works for every university student.”',options:['Matches the source','Goes beyond the source','Only a grammar issue'],answer:1,repair:'“This small study” does not support “every university student”.'}],teacher:'6 min: fictional source excerpts are sufficient for the exercise, not external research evidence. Require students to point to the changed words.'},
  {title:'New case. No tutor.',minutes:7,d:'Transfer',kind:'choice',instruction:'Apply the idea with the AI closed.',bn:'নতুন উদাহরণে নিজে প্রয়োগ করুন।',frame:'Another explanation is ___. I would check ___.',source:'Graduates who joined an optional interview workshop earn more after six months. They also had more prior work experience. An advert says: “Our workshop caused the salary increase.”',question:'What is the strongest response?',options:['Higher pay proves the advert.','Prior experience could explain the difference; investigate before making a causal claim.','The workshop definitely had no effect.'],answer:1,feedback:['The groups differ in a second important way.','You transferred the distinction. Uncertain cause does not mean no possible benefit.','The available evidence does not justify that conclusion either.'],teacher:'7 min: each student first chooses silently and explains independently, then compare. Count independent justification, not agreement after feedback.'},
  {title:'Did you learn—or just agree?',minutes:5,d:'Diligence',kind:'exit',instruction:'Choose evidence of learning, then make your next plan.',bn:'শেখার প্রমাণ কী?',frame:'At first I ___. Now I can ___. Next I will ___.',source:'Mitu understood an explanation while reading it, but could not explain the new case without looking. Her chat has 40 messages.',question:'What should she do next?',options:['Mark the topic mastered.','Request a longer explanation and copy it.','Identify the missing step, practise with a small hint, then retry independently.'],answer:2,feedback:['Feeling familiar and demonstrating a skill are different signals.','More text may hide the same gap.','Use the result to adjust the learning plan. A gap is useful evidence, not a failure of identity.'],teacher:'5 min: compare the initial confidence with independent transfer. Learners name a specific gap and one next action. Do not use confidence alone as proof of competence.'}
 ]},
 {id:'build',icon:'⌘',title:'A demo is a promise.',tag:'Vibe coding · testing · responsible launch',person:'Nila and Sami · student founders, Rajshahi',goal:'Stop a weak fix. Test the cause. Earn the right to release.',deliverable:'A tested repair plan and an honest pilot decision.',steps:[
  {title:'Meet TutorTime',minutes:4,d:'Diligence',kind:'reveal',instruction:'Watch the launch claim meet real customers.',bn:'ডেমোর পরে বাস্তব গ্রাহকের কী হয়?',frame:'The demo shows ___. It does not test ___.',cards:[['The demo','Beautiful profiles. One tutor. One booking. A green confirmation.'],['The launch post','“We built a secure platform. Book and pay today!”'],['First customers','Two people book 4 p.m. One pays but sees no booking. Another can open someone else’s details.']],question:'What did the demo establish?',options:['One demonstrated path worked.','The whole service is secure and reliable.','The founders should never use AI.'],answer:0,feedback:['A working path is useful evidence with a narrow scope.','Security and reliability require more than a successful screen recording.','The issue is the evidence for release, not the mere use of AI.'],teacher:'4 min: reveal incidents only after students predict what the demo proves. Cases and outputs are fictional.'},
  {title:'Two phones. One slot.',minutes:6,d:'Discernment',kind:'booking',instruction:'Run both customers through the same slot.',bn:'দুটি ফোনে একই সময় বুক করুন।',frame:'One phone ___, but two phones ___.',teacher:'6 min: run the single-click patch first, then the server reservation. Explain atomic as “check and reserve as one operation”; no coding prerequisite.'},
  {title:'Stop the build',minutes:7,d:'Discernment',kind:'chain',instruction:'Stop when the proposed fix misses the cause.',bn:'কারণটি ঠিক না করলে AI-কে থামান।',frame:'This fixes ___, but the problem is ___.',steps:[
   {text:'“Reproduce the bug using two customer accounts at once.”',stop:false,why:'This tests the reported concurrency problem.'},
   {text:'“Both requests read ‘available’ before either saves.”',stop:false,why:'The work note identifies the shared-state race.'},
   {text:'“Disable the button after one click. Ready to launch.”',stop:true,why:'Each phone has its own button. The shared server state remains unprotected.'}],recovery:{question:'What must the repair do?',options:['Reserve the slot atomically on the server, then test simultaneous requests.','Hide the second confirmation message.','Add a longer loading animation.'],answer:0,result:'Expected test: exactly one booking succeeds; the other receives “slot no longer available”. No duplicate reservation is stored.'},teacher:'7 min: require evidence: two different accounts, shared slot. A disabled button is useful UI feedback but insufficient protection.'},
  {title:'Hidden is not protected',minutes:6,d:'Diligence',kind:'inspect',instruction:'Compare the screen rule with the server rule.',bn:'বাটন লুকানো আর অনুমতি যাচাই এক নয়।',frame:'The screen hides ___. The server must check ___.',rounds:[
   {source:'Customer A requests /booking/42, which belongs to Customer B. The admin button is hidden.',claim:'AI: “Ordinary users cannot see the button, so bookings are private.”',options:['Ready','Test permissions on the server','Only change the colour'],answer:1,repair:'The server must verify who owns booking 42 before returning its data. Test using a second account.'},
   {source:'The server checks the signed-in account and denies access to bookings it does not own.',claim:'AI: “Now test both denied access and the owner’s legitimate access.”',options:['Continue: test both paths','Stop: all fail-safes are bad','Skip: code looks clear'],answer:0,repair:'This is appropriate defensive work: protect data while preserving valid use.'}],teacher:'6 min: use fictional IDs only. The exercise is conceptual; it provides no real target or access credentials.'},
  {title:'A green screen can lie',minutes:6,d:'Description',kind:'chain',instruction:'Follow a failed request to its customer message.',bn:'সবুজ বার্তা কি সত্যি সাফল্য দেখায়?',frame:'If ___ fails, show ___ and keep ___.',steps:[
   {text:'“The booking database is offline. Show a clear temporary error and log a non-sensitive diagnostic.”',stop:false,why:'This reports the failure without exposing customer details.'},
   {text:'“To keep the screen clean, catch every error and return an empty booking list.”',stop:true,why:'Customers cannot distinguish no bookings from a failed load. The failure has been hidden.'}],recovery:{question:'Choose the better requirement.',options:['Always display a green tick.','Show unavailable separately from empty; preserve records and test recovery.','Delete the failing test.'],answer:1,result:'Database unavailable → “We cannot load bookings yet.” Database restored → original bookings return. Empty account → “No bookings yet.”'},teacher:'6 min: make learners distinguish valid error handling from concealment. A catch block itself is not the problem.'},
  {title:'Patch or durable design?',minutes:6,d:'Delegation',kind:'sort',instruction:'Choose what each proposal needs.',bn:'কোন সমাধানটি টেকসই?',frame:'This value belongs in ___ because ___.',labels:['Useful design','Weak shortcut','Needs evidence'],items:[
   {text:'Central price rules used by checkout and receipts, with tests for discounts',answer:'Useful design',why:'One authoritative rule reduces inconsistent totals; tests still matter.'},
   {text:'Hard-code ৳500 into the payment screen because today’s tutor costs ৳500',answer:'Weak shortcut',why:'Other tutors and discounts invalidate the special case.'},
   {text:'Use the fixed number 60 to convert minutes to seconds',answer:'Useful design',why:'A stable unit conversion is a legitimate constant. Fixed values are not automatically bad.'},
   {text:'AI says “the new architecture is scalable” without a load test or workload assumptions',answer:'Needs evidence',why:'Ask for expected usage, limits and a test. A label is not evidence.'}],teacher:'6 min: physically trace price → booking → receipt with fingers. Good architecture separates responsibilities, but adds no guarantee by itself.'},
  {title:'Can we afford to keep the promise?',minutes:5,d:'Diligence',kind:'choice',instruction:'Look beyond the launch screen.',bn:'লঞ্চের পরে দায়িত্ব কে নেবে?',frame:'Before taking money, we need ___.',source:'Each booking brings ৳30 in fees. Payment and hosting cost ৳12. Average support/refund handling costs ৳25 per booking. Payment retries have not been tested for duplicate charges.',question:'What is the responsible next step?',options:['Launch widely: the UI is finished.','Run a limited no-payment pilot; test payment integrity and revisit costs before charging.','Hide support costs from the plan.'],answer:1,feedback:['৳30 − ৳12 − ৳25 = −৳7 per booking before other costs. More bookings do not solve that by themselves.','A pilot limits exposure while gathering evidence. Set an owner, stop conditions and support plan.','Unrecorded costs still affect the business and customers.'],teacher:'5 min: distinguish app creation from a sustainable service. Discuss refund ownership, monitoring, restoration and truthful launch claims.'},
  {title:'Release review: you sign',minutes:5,d:'Transfer',kind:'exit',instruction:'AI closed. Decide on a new failure.',bn:'নিজে পরীক্ষা বেছে নিন।',frame:'We will release only when the test shows ___.',source:'A payment provider times out after charging a customer. AI proposes retrying the charge automatically. No duplicate-payment protection has been demonstrated.',question:'Which test must come before charging real customers?',options:['Check that the retry animation is smooth.','Repeat the same payment request after a timeout; verify one charge and a reconciled booking.','Ask a second AI whether the code looks good.'],answer:1,feedback:['Appearance does not test financial integrity.','Require evidence that retries cannot create duplicate charges and that payment and booking records reconcile.','A second opinion can help review but cannot replace the operational test.'],teacher:'5 min: each partner explains the expected result before comparing. Final statement must specify the test, expected evidence, remaining risk and release owner.'}
 ]}
];
