/* Fictional consequences, not predictions about hiring, learning gains or engagement. */
(() => {
 const branch=(d,title,text,options,outcomes,extra={})=>({d,title,text,options,outcomes,kind:'branch',...extra});
 const trial=(title,text,options,outcomes,answer,extra={})=>branch('Discernment',title,text,options,outcomes,{kind:'trial',answer,...extra});
 const compare=(title,text,previews,options,outcomes)=>branch('Diligence',title,text,options,outcomes,{kind:'compare',previews});
 const times=[4,5,7,6,5,6,5,4];
 const get=id=>PHONE_JOURNEYS.find(j=>j.id===id);
 const opportunity=get('opportunity');
 opportunity.title='An application is the start—not the finish';
 opportunity.task='Rafi wants a field-assistant internship. Use AI to help him apply, then see whether he can handle the practical follow-up.';
 opportunity.artifact='An application route and readiness record';
 opportunity.sources.Browser='FICTIONAL INTERNSHIP · Student field assistant\nFinal-year students. Deadline: 18 October, 5 pm. Travel allowance only. Work includes checking interview sign-in records. AI assistance is allowed. Applicants must explain their experience and do a short records task themselves.';
 opportunity.sources.Notes='RAFI’S EXPERIENCE\nRegistered 45 visitors at a reading event. Used the organiser’s checklist. Has not designed a checking system. Wants to learn to check records accurately.';
 opportunity.steps=[
 branch('Delegation','What should AI do first?','Rafi wants to apply today. A polished draft is quick; finding skill gaps takes more effort. Choose a starting point.',['Make an impressive draft now.','Find my gaps and plan preparation.'],['Gemini produces a confident application immediately. Next, inspect the promise it makes.','Gemini identifies records-checking as a skill to practise. Rafi still needs to write the application.']),
 branch('Description','Choose the promise','Rafi registered 45 visitors using someone else’s checklist. Which version will he take into the application?',['“I designed a reliable records-checking system.”','“I registered 45 visitors using the organiser’s checklist.”'],['The application makes a strong claim. The follow-up will ask how the system works.','The application makes a narrower claim. The follow-up will ask what Rafi can do next.'],{variant:{step:0,texts:['Gemini’s fast draft says: “I designed a reliable records-checking system.” It sounds stronger than Rafi’s notes. Which version will he use?','Gemini’s preparation plan says: “Describe your registration work and practise checking records.” Which claim will Rafi use?']}}),
 compare('Does more data improve the advice?','Preview two possible inputs before sharing. Compare the useful advice, not just the amount of information.',[['Full class notes','Advice: compare IDs, flag conflicts, verify before editing. Extra exposure: classmates’ contacts and family notes.'],['Relevant brief','Advice: compare IDs, flag conflicts, verify before editing. Includes only the role, experience, skill gap and deadline.']],['Send the relevant brief.','Send all the notes.'],['In this case, the useful advice is the same. Rafi can obtain it without sharing the extra personal details.','In this case, the extra details do not improve the advice. The personal exposure increases without a task benefit.']),
 branch('Discernment','The coordinator replies','SIMULATED REPLY: “Before we decide, explain how you would handle conflicting sign-in records.” What will Rafi do?',['Ask Gemini for a professional-sounding explanation.','Identify what I can do and practise the missing step.'],['Gemini suggests “reconcile identifiers and validate anomalies”. The coordinator asks: “Show me on this sheet.” Better wording has not done the checking task.','Rafi identifies a specific gap: deciding which records need verification. He can now request targeted practice.'],{variant:{step:1,texts:['SIMULATED REPLY: “You said you designed a checking system. What did it check? Show us with an example.”','SIMULATED REPLY: “You used a checklist. What would you check yourself if two records disagreed?”']}}),
 branch('Description','Choose the help before the test','The task is to find suspicious records without deleting valid ones. What help do you want?',['Give me a method to read.','Give me a small problem and wait for my attempt.'],['Method: compare identifiers, flag repeated or conflicting records, then verify against the source. Reading it is preparation; the new problem will test application.','Practice next: use both the name and ID. Point to the repeated record before checking the explanation.']),
 trial('Try a small case','Which record may be repeated? Compare the name AND ID.',['Asha / 14 appears twice.','Asha and Karim have different names.'],['Same name and ID appear twice. Flag the possible duplicate; verify before deleting.','Different names alone do not identify a duplicate. Look for the repeated Asha / 14 entry.'],0,{table:[['Asha','14'],['Karim','15'],['Asha','14']]}),
 trial('New sheet. Chat closed.','Two people may share a name. What should Rafi do with this different sheet?',['Delete one Rina because the name repeats.','Flag ID 17: two names use it. Verify before editing.','Keep every row because the names differ.'],['That may delete a valid person. Rina can name two people; ID 17 attached to Rina and Salim is the conflict.','You found the conflict and chose verification rather than guessing which row to delete.','Names alone miss the conflicting ID. Check ID 17 before accepting both records.'],1,{app:'Notes',table:[['Rina','17'],['Rina','31'],['Salim','17']]}),
 branch('Diligence','What can you promise now?','Look back at your first independent decision. What is the next useful action?',['Claim expert-level records management.','Describe my experience and practise a further case before claiming independent skill.'],['One small exercise is weak evidence of expertise. A bigger promise creates a bigger gap to explain when the real work starts.','Your claim stays within the evidence. Another independent case can show whether the skill transfers. This story does not predict selection.'],{app:'Notes',summary:true})
 ];
 const learning=get('learning');learning.title='Does the help survive a closed chat?';learning.task='Mitu needs to explain a research claim tomorrow. Try an AI-help strategy, then discover what she can do when the example changes.';
 learning.steps=[
 branch('Delegation','Choose a tempting starting point','Mitu has limited time. Both forms of help can be useful. Which will she try first?',['Read a clear model explanation.','Attempt the problem, then ask for feedback.'],['A model can show what a good explanation sounds like. It does not yet show what Mitu can produce herself.','An attempt may feel slower and less fluent. It gives the tutor information about the particular gap.']),
 branch('Description','Set the tutor’s next move','The study compares students who chose an app with students who did not. What should ChatGPT do?',['Give the conclusion and explain it.','Ask one question, wait, then respond to my reasoning.'],['Model answer: the groups may differ in motivation or study time. A larger score gain does not by itself establish the cause.','Tutor question: could students who chose the app already have different study habits? Say one possible difference to your partner before continuing.']),
 compare('How much should the tutor see?','Preview the feedback from two possible inputs.',[['Named grade records','Feedback: compare how the groups were formed. The tutor also receives named classmates’ grades.'],['Fictional study card','Feedback: compare how the groups were formed. No classmates’ records are shared.']],['Use the fictional study card.','Upload named grades too.'],['The fictional card supports the same reasoning task without exposing classmates’ records.','Extra personal data has not changed this explanation. It adds exposure without answering the learning question.']),
 trial('Check an explanation that sounds convincing','ChatGPT says: “Students were randomly assigned, so the app caused the improvement.” The source says they chose their own groups.',['Accept it: it sounds like research language.','Challenge “randomly assigned” using the source.'],['The explanation relies on a study design that did not happen. Fluency hides a changed fact.','The changed assignment method matters to the reasoning, not just the wording.'],1,{source:'Browser'}),
 branch('Description','Prepare for the chat to close','A different case is coming. Choose how to prepare.',['Read the model explanation once more.','Explain the idea to my partner without looking, then ask for one hint if stuck.'],['Rereading may clarify the wording. The next independent attempt will show whether that understanding transfers.','An explanation attempt exposes a gap before the next task. Your partner should ask “why?”, not supply the answer.']),
 trial('Changed example. No tutor.','Students who chose an interview workshop later earn more. They also had more previous work experience. Does this prove the workshop caused the higher pay?',['Yes: their higher pay is the proof.','Not yet: prior experience could explain the difference.','No: the workshop definitely had no effect.'],['The groups already differ in experience. Higher pay alone cannot isolate the workshop’s effect.','You found an alternative explanation. This leaves the workshop’s effect uncertain, not disproved.','The evidence does not establish zero effect either. Uncertainty is not proof that nothing helped.'],1,{app:'Notes'}),
 trial('A second transfer test','People who chose a fitness app walk more. They also walked more BEFORE installing it. Which comparison would help next?',['Compare changes from each group’s starting level and consider other differences.','Compare only the final step counts.'],['Starting levels matter. A better comparison reduces one source of confusion, though it does not automatically prove cause.','The final difference could have existed before the app. You still need to account for the starting point.'],0,{app:'Notes'}),
 branch('Diligence','Adjust the learning plan','Use your first attempts below. Which next step fits your evidence?',['I can explain both: test a harder case later.','I missed a step: ask for one targeted hint, then retry a new case.'],['Treat this as evidence about these tasks, not proof of mastery everywhere. Say the explanation without reading it.','The mistake gives a useful target. Ask about that gap, rather than requesting a longer answer to copy.'],{app:'Notes',summary:true})
 ];
 const poster=get('poster');poster.artifact='A poster draft and audience test';poster.title='Will the poster work after it is shared?';poster.task='Nusrat needs students to find a speaking event. Choose a design, see it cropped and reposted, then test whether it still gets people to the right place.';
 poster.steps=[
 branch('Delegation','What should Claude prioritise?','You need attention AND usable event information. Choose a first draft to test.',['A dramatic headline; put details in the caption.','A clear event card with key facts inside the image.'],['The image is striking, but it depends on a caption travelling with it. Test that assumption before publication.','The card carries the facts with it. It still needs a readability and accuracy check.']),
 branch('Description','Give the designer a real audience','Who needs to use this poster?',['Current club members who know the venue.','New students seeing a repost on a small phone.'],['A familiar audience can fill some gaps. But a public repost may reach people without that background.','The brief now requires readable facts and enough context for someone new to the club.']),
 compare('Compare visual inputs','Which input improves the task without creating unnecessary exposure?', [['Class-group photo','Gives a recognisable group portrait. Shows classmates whose permission for promotion has not been obtained. Event facts still need checking.'],['Original club illustration','Shows a conversation scene without identifying classmates. Event facts still need checking.']],['Use the original illustration.','Use the class photo now.'],['The illustration supports the event message without creating an unapproved public association for classmates.','The photo may attract recognition, but people are now represented publicly without approval. It still does not solve the information problem.']),
 branch('Discernment','Test a captionless repost','A viewer shares only the image. Look at what remains. What can a new student do with it?',['Assume they can find the event.','Check whether time and room are visible.'],['The next decision needs evidence from the image, not from what the organiser remembers.','Point to the time and room in the image. If either is absent, the viewer has to ask or guess.'],{app:'Gallery',visual:'crop',variant:{step:0,texts:['The repost contains only “SPEAKING CIRCLE”. A new student messages: “When? Which room?” The caption did not travel.','The repost still shows 4 pm and Room 204. A new student can find the details—but are they current?']}}),
 branch('Description','Revise what will actually travel','How will you respond to the repost test?',['Add the missing details to the caption only.','Put the time and room inside the image, in readable text.'],['A caption-only repair leaves the shared image unchanged. A second captionless repost loses the repair too.','The repair changes the object being shared. The details now survive the same crop test.'],{app:'Gallery',visual:'repair'}),
 branch('Discernment','A late room change','The organiser confirms Room 205, not 204. Choose what to update.',['Update the announcement, leaving the image unchanged.','Update both the image and the announcement.'],['The two versions now disagree. Someone following the image still goes to Room 204.','Both visible versions now direct students to Room 205. Verify scheduled copies too.'],{app:'Gallery',visual:'room'}),
 branch('Diligence','Follow the audience','One student sees the image; another reads only the announcement. Test the two routes before sharing.',['Release the current versions.','Hold the release and compare both versions.'],['The preview shows where each version sends a reader. A finished design can still cause a wrong-room trip.','A short release check can prevent a wrong-room trip. If the versions disagree, repair the image before releasing.'],{app:'Gallery',visual:'routes'}),
 branch('Diligence','Choose the release evidence','Which evidence matters most for this task?',['The organiser likes the design.','A new reader can find the confirmed time and room in every shared version.'],['Approval of appearance is useful, but it does not test whether a new student can act on the poster.','Test the communication against its purpose: can someone get to the event correctly?'],{app:'Notes',summary:true})
 ];
 for(const j of PHONE_JOURNEYS){j.version=2;j.steps.forEach((s,i)=>s.minutes=times[i]);}
 window.resolveConsequenceStep=(j,state)=>{
 const base=j.steps[state.step],s={...base};if(s.variant)s.text=s.variant.texts[state.answers[s.variant.step]?.choice??0];
 if(j.id==='poster'){
 const details=state.answers[0]?.choice===1||state.answers[4]?.choice===1,updated=state.answers[5]?.choice===1;
 if(state.step===4&&details)s.outcomes=['The image already carries the details. A caption adds context, but check the image itself when facts change.',s.outcomes[1]];
 if(state.step===5&&!details)s.outcomes=['The announcement says Room 205, but the image still gives no time or room. An image-only reader must ask for help.','The room is updated, but the headline-only image still needs event details. Return to image repairs.'];
 if(state.step===6)s.outcomes=details&&updated?['Both previews show the confirmed room. Before release, check any scheduled copies and small-screen readability.','The comparison agrees: Room 205 on both routes. Check the scheduled versions too.']:['The current image cannot reliably get a new student to Room 205. Releasing it leaves that problem with the reader.','You caught a communication failure before release. Return to image repairs and make both routes usable.'];
 }return s;
 };
})();
