(() => {
'use strict';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let saved;try{saved=JSON.parse(localStorage.getItem('dialogue-fluency-v3'))||{}}catch{saved={}}
let brand=saved.brand||'ChatGPT', bangla=false, session, step, index, state;
const persist=()=>{try{localStorage.setItem('dialogue-fluency-v3',JSON.stringify(saved))}catch{}};
const bind=(id,fn)=>{const el=document.getElementById(id);if(el)el.onclick=fn};
const box=(label,text,cls='evidence')=>`<div class="${cls}"><small>${esc(label)}</small><p>${esc(text)}</p></div>`;
const feedback=(ok,text)=>`<div class="feedback ${ok?'':'bad'}" role="status"><strong>${ok?'✓ Evidence secured':'↻ Look again'}</strong>${esc(text)}</div>`;
function mark(){state.done=true;persist()}
function choice(data,key='answer',after){const picked=state[key];return `<div class="options">${data.options.map((o,i)=>`<button data-choice="${key}:${i}" aria-pressed="${picked===i}">${esc(o)}</button>`).join('')}</div>${picked===undefined?'':feedback(picked===data.answer,Array.isArray(data.feedback)?data.feedback[picked]:data.why||data.repair||'Use the evidence above to reconsider.')}`}
function wireChoice(data,key='answer',after){document.querySelectorAll(`[data-choice^="${key}:"]`).forEach(b=>b.onclick=()=>{const n=Number(b.dataset.choice.split(':')[1]);if(state[key]===undefined)state[key+'First']=n;state[key]=n;if(n!==data.answer)state.done=false;if(n===data.answer){if(after)after();else mark()}persist();render()})}
function home(){session=null;if(window.PhoneLab){window.PhoneLab.home();return}$('#teacher').innerHTML='';$('#app').innerHTML=`<div class="hero"><small>One phone · two thinkers · three lessons</small><h1>Use AI.<br>Keep your judgment.</h1><p>Three guided lessons about using AI responsibly at university and beyond. You will help fictional students handle an email, a learning problem, and an app launch.</p><p>Each lesson starts with the story and your assignment. Then you try prepared examples, discuss decisions, and check what happens. No AI account or coding experience is needed.</p></div><div class="habits">${[['↔','Delegation','Choose what stays yours.'],['▤','Description','Give help a clear boundary.'],['⌕','Discernment','Find evidence. Test the claim.'],['✓','Diligence','Own what happens next.']].map(x=>`<div class="habit"><b>${x[0]} ${x[1]}</b><span>${x[2]}</span></div>`).join('')}</div><div class="sessions">${LAB_SESSIONS.map((s,i)=>`<article class="session"><div class="icon">${s.icon}</div><small>Session ${i+1} · 45 minutes</small><h2>${window.LAB_BRIEFS[s.id].name}</h2><p>${window.LAB_BRIEFS[s.id].job}</p><p class="muted">You leave with: ${s.deliverable}</p><button class="primary" data-session="${s.id}">Meet the situation →</button></article>`).join('')}</div><p class="muted">Practice with familiar mobile interfaces. No account, upload or live AI required. Your decisions stay in this browser.</p>`;document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>location.hash=b.dataset.session+'/intro')}
function route(){const [id,n]=location.hash.slice(1).split('/');if(window.PhoneLab){window.PhoneLab.stop();window.PhoneLab.active=false;if(id==='phone'){session=null;window.PhoneLab.route(n);return}}session=LAB_SESSIONS.find(s=>s.id===id);if(!session)return home();index=Math.max(0,Math.min(7,(parseInt(n)||1)-1));step=session.steps[index];const key=session.id+'/'+index;state=saved[key]||(saved[key]={});render()}
function render(){if(location.hash.endsWith('/intro')||(index===0&&!saved['intro:'+session.id])){window.renderLabIntro({session,bangla,start:()=>{saved['intro:'+session.id]=true;persist();location.hash=session.id+'/1';render();window.scrollTo({top:0,behavior:'auto'})}});return}if(session.id==='build'&&index===2){window.renderBookingStory({state,persist,render,bangla});return}if(session.id==='build'&&[2,4].includes(index)){window.renderCodexWorkflow({index,state,persist,render,session,bangla});return}const complete=session.steps.filter((_,i)=>saved[session.id+'/'+i]?.done).length;
$('#app').innerHTML=`<div class="toolbar"><button id="home">← All lessons</button><div class="dots" aria-label="Lesson stages">${session.steps.map((s,i)=>`<button data-stage="${i}" aria-label="Stage ${i+1}: ${esc(s.title)}" aria-pressed="${i===index}">${saved[session.id+'/'+i]?.done?'✓':i+1}</button>`).join('')}</div><span class="muted">${complete}/8 explored · ${step.minutes} min</span></div><div class="layout"><section class="brief"><small>${esc(step.d)} · ${index+1} / 8</small><h1>${esc(step.title)}</h1><p class="instruction">${esc(step.instruction)}</p>${bangla?`<p class="bn" lang="bn">${esc(step.bn)}</p>`:''}<p class="muted">${esc(session.person)}</p>${index===0?'<button id="intro">▶ How this lesson works</button>':''}<div class="role"><b>${step.kind==='exit'?'First: work alone':index%2?'B operates · A checks':'A operates · B checks'}</b><br>${step.kind==='exit'?'Make your own decision. Then compare reasons.':'Point to evidence before you check. Swap next stage.'}</div><div class="speech"><small>Say it to your partner</small><p>${esc(step.frame)}</p></div>${state.done?'<div class="receipt">✓ Decision checked. Now explain the evidence without reading the feedback.</div>':''}</section><section><div class="brandbar" aria-label="Practice interface">${['ChatGPT','Claude','Gemini'].map(b=>`<button data-brand="${b}" aria-pressed="${brand===b}">${b}</button>`).join('')}</div><div class="phone" data-brand="${brand}"><div class="status"><span>9:41</span><span>▮▮▮ ▰</span></div><div class="phonehead"><span aria-hidden="true">☰</span><span>${brand==='Claude'?'✳ ':brand==='Gemini'?'✦ ':'◎ '}${brand}</span><span aria-hidden="true">✎</span></div><div class="simulation">Authored practice · no live AI · simulated work steps</div><div class="progress"><span style="width:${(index+1)/8*100}%"></span></div><div class="screen" id="screen"></div><div class="composerhint"><span>${brand==='Claude'?'Reply to Claude…':brand==='Gemini'?'Ask Gemini…':'Message ChatGPT…'}</span><span aria-hidden="true">＋ &nbsp; ↑</span></div><div class="phonefoot"></div></div></section></div><div class="nav"><button id="prev">← Back</button><span class="muted">${esc(session.tag)}</span><button class="primary" id="next">${index===7?'Learning record →':'Next →'}</button></div>`;
bind('intro',()=>location.hash=session.id+'/intro');bind('home',()=>location.hash='');bind('prev',()=>location.hash=index?session.id+'/'+index:'');bind('next',()=>index===7?record():location.hash=session.id+'/'+(index+2));document.querySelectorAll('[data-stage]').forEach(b=>b.onclick=()=>location.hash=session.id+'/'+(+b.dataset.stage+1));document.querySelectorAll('[data-brand]').forEach(b=>b.onclick=()=>{brand=b.dataset.brand;saved.brand=brand;persist();render()});activities[step.kind]();document.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>{b.classList.toggle('lit');b.setAttribute('aria-pressed',b.classList.contains('lit'))});$('#teacher').innerHTML=`<h3>${esc(step.title)}</h3><p>${esc(step.teacher)}</p><p>Session outcome: ${esc(session.deliverable)}</p>`;
}
const focusWords={
'voice/1':[['abstract and conclusion','complete paper in depth'],['No statistical analysis yet','validated model'],['Do longer commutes reduce club participation?','curious whether commuting affects participation']],
'voice/6':[['AI asked practice questions','disclosure'],['independently written','What now?']],
'learn/5':[['chose whether to attend','randomly assigned'],['this small study','every university student']],
'build/3':[['belongs to Customer B','cannot see the button'],['denies access','both denied access']]};
function scene(count){
if(session.id==='voice'&&index===5)return `<div class="poster"><div class="posterart"><small>Scholarship futures</small><svg viewBox="0 0 320 120" role="img" aria-label="Schematic of three students outside a university"><path d="M40 105V45l120-35 120 35v60" fill="#d7ddc7"/><path d="M55 48h210M80 48v57m40-57v57m80-57v57m40-57v57" stroke="#8eaa91" stroke-width="8"/>${[105,160,215].map((x,i)=>`<circle cx="${x}" cy="61" r="13" fill="#bc916b"/><path d="M${x-21} 118v-28q21-22 42 0v28" fill="${i===1?'#173f35':'#627f60'}"/>`).join('')}</svg>${state.answer===0?'<b class="embedded">Illustration · not actual recipients</b>':''}</div>${count<3?'<div class="posterlabel">Illustration of possible futures</div>':'<div class="cropped">✂ Caption cropped away</div><b class="repost">“Our paid service got them places!”</b>'}</div>`;
if(session.id==='build'&&index===0)return `<div class="demo"><small>TutorTime · ${count<3?'demo account':'live customers'}</small><div class="avatar">N</div><h3>Nadia · English tutor</h3><div class="appointment">16:00 · ${count<3?'✓ Booking confirmed':'A booked ↔ B booked'}</div><p class="muted">${count<3?'One tutor. One customer. One successful path.':'One slot. Two customers. Conflicting promises.'}</p></div>`;
if(session.id==='voice'&&index===0)return `<div class="promise"><span>▤<br><small>Abstract</small></span><span class="arrow">→</span><span>✉<br><small>“Your method”</small></span><span class="arrow">→</span><span>☎<br><small>${count<3?'Next?':'Explain it'}</small></span></div>`;
return '';
}
function evidencePair(d,r){const words=focusWords[session.id+'/'+index]?.[r]||[];const highlight=(text,word)=>{const safe=esc(text);return word&&text.includes(word)?safe.replace(esc(word),'<button class="evidenceword" data-evidence aria-pressed="false">'+esc(word)+'</button>'):safe};return `<div class="evidence"><small>Source · what we know</small><p>${highlight(d.source,words[0])}</p></div><div class="bubble"><small>AI output · check this</small><p>${highlight(d.claim,words[1])}</p></div><p class="muted">Tap the underlined words. Say what changed.</p>`}
const activities={
reveal(){const count=state.reveal||1;$('#screen').innerHTML=scene(count)+box(step.cards[Math.min(count,step.cards.length)-1][0],step.cards[Math.min(count,step.cards.length)-1][1],count%2?'evidence':'bubble')+(count>1?'<details class="history"><summary>Earlier in the story</summary>'+step.cards.slice(0,count-1).map(c=>box(c[0],c[1])).join('')+'</details>':'')+(count<step.cards.length?'<button id="reveal" class="primary">See what happens →</button>':`<b>${esc(step.question)}</b>${choice(step)}`);bind('reveal',()=>{state.reveal=count+1;persist();render()});wireChoice(step)},
choice(){ $('#screen').innerHTML=(session.id==='learn'&&index===0?'<div class="comparison"><div><small>Chose the app · 20 students</small><div class="bar" style="width:100%">+10 points</div></div><div><small>No app · 20 students</small><div class="bar" style="width:42%">+3</div></div><strong>Who chose each group?</strong></div>':'')+box('Case evidence',step.source)+`<b>${esc(step.question)}</b>`+choice(step);wireChoice(step)},
exit(){activities.choice()},
inspect(){const r=state.round||0,d=step.rounds[r];$('#screen').innerHTML=`<small>Evidence check ${r+1} / ${step.rounds.length}</small>${evidencePair(d,r)}${choice(d,'round'+r)}${state['round'+r]===d.answer?box('Supported action / repair',d.repair)+'<button id="roundnext" class="primary">'+(r<step.rounds.length-1?'Next evidence pair →':'Evidence checked ✓')+'</button>':''}`;wireChoice(d,'round'+r,()=>{if(step.rounds.every((x,i)=>state['round'+i]===x.answer))mark()});bind('roundnext',()=>{if(r<step.rounds.length-1){state.round=r+1;persist();render()}})},
sort(){const labels=step.labels||['Me','AI assists','Do not do'];$('#screen').innerHTML=step.items.map((d,i)=>`<div class="evidence"><p>${esc(d.text)}</p><div class="chips">${labels.map(x=>`<button data-sort="${i}" data-value="${esc(x)}" aria-pressed="${state['sort'+i]===x}">${esc(x)}</button>`).join('')}</div>${state['sort'+i]===undefined?'':feedback(state['sort'+i]===d.answer,d.why)}</div>`).join('');document.querySelectorAll('[data-sort]').forEach(b=>b.onclick=()=>{state['sort'+b.dataset.sort]=b.dataset.value;state.done=false;if(step.items.every((x,i)=>state['sort'+i]===x.answer))mark();persist();render()})},
privacy(){const selected=state.removed||[];$('#screen').innerHTML=box('Your task',step.task)+`<small>Tap to remove · tap again to restore</small><div class="options">${step.fields.map((f,i)=>`<button data-field="${i}" aria-pressed="${selected.includes(i)}"><span class="${selected.includes(i)?'removed':''}">${esc(f.text)}</span> ${selected.includes(i)?'— removed':'— included'}</button>`).join('')}</div><button class="primary" id="privacycheck">Preview safe attachment →</button>${state.checked?feedback(state.done,state.done?'Only the blank survey questions remain. No responses or identifying details are sent.':step.consequence):''}${state.done?box('Attachment preview','Blank survey questions · ready for structural feedback'):''}`;document.querySelectorAll('[data-field]').forEach(b=>b.onclick=()=>{const i=+b.dataset.field;state.removed=selected.includes(i)?selected.filter(x=>x!==i):[...selected,i];state.checked=false;state.done=false;persist();render()});bind('privacycheck',()=>{state.checked=true;if(step.fields.every((f,i)=>f.remove===selected.includes(i)))mark();persist();render()})},
build(){const picks=state.picks||{};const missing=step.groups.findIndex((_,i)=>picks[i]===undefined);const active=state.edit??missing;$('#screen').innerHTML=`<small>Prompt composer · drag a tile or tap it</small>${step.groups.map((g,i)=>`<div class="slot ${picks[i]!==undefined?'filled':''}" data-slot="${i}"><div class="slothead"><small>${esc(g.label)}</small>${picks[i]!==undefined?`<button class="edit" data-edit="${i}" aria-label="Edit ${esc(g.label)}">Edit</button>`:''}</div><div>${picks[i]===undefined?'Drop a matching tile here ↓':esc(g.options[picks[i]])}</div></div>`).join('')}${active>=0?`<small>Choose: ${esc(step.groups[active].label)}</small><div class="chips">${step.groups[active].options.map((o,j)=>`<button draggable="true" data-tile="${active}:${j}" aria-pressed="${picks[active]===j}">${esc(o)}</button>`).join('')}</div>`:''}<p class="muted">${missing<0?'Read your assembled request. Ready to send?':'Tap a tile to place it. You can edit every choice.'}</p><button class="primary" id="send" ${missing>=0?'disabled':''}>Send practice prompt ↑</button>${state.sent?feedback(state.done,state.done?'The request leaves the thinking with you.':'This request gives away part of the thinking. Check each selected tile.')+(state.done?box('Simulated response',step.result,'bubble'):''):''}`;
const put=(value,target)=>{const [i,j]=value.split(':').map(Number);if(target!==undefined&&i!==target)return;state.picks={...picks,[i]:j};delete state.edit;state.sent=false;state.done=false;persist();render()};document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>{state.edit=+b.dataset.edit;render()});document.querySelectorAll('[data-tile]').forEach(b=>{let origin, moved=false;b.onclick=()=>{if(!moved)put(b.dataset.tile);moved=false};b.ondragstart=e=>e.preventDefault();b.onpointerdown=e=>{origin=[e.clientX,e.clientY];moved=false;b.setPointerCapture(e.pointerId)};b.onpointermove=e=>{if(origin&&Math.hypot(e.clientX-origin[0],e.clientY-origin[1])>8){moved=true;b.classList.add('dragging')}};b.onpointerup=e=>{if(moved){const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-slot]');if(target)put(b.dataset.tile,+target.dataset.slot)}origin=null;b.classList.remove('dragging')};b.onpointercancel=()=>{origin=null;moved=false;b.classList.remove('dragging')}});document.querySelectorAll('[data-slot]').forEach(el=>{el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();const v=e.dataTransfer.getData('text/plain');if(/^\d+:\d+$/.test(v))put(v,+el.dataset.slot)}});bind('send',()=>{state.sent=true;if(step.groups.every((g,i)=>picks[i]===g.answer))mark();persist();render()})},
chain(){const n=state.chain||0,items=step.steps||step.chain, d=items[n];$('#screen').innerHTML=`<small>Visible work log · step ${n+1}</small><div class="steps">${items.slice(0,n+1).map((x,i)=>`<div class="workstep"><small>${i===n?'Review this step':'Checked ✓'}</small><div>${esc(x.text)}</div></div>`).join('')}</div><div class="split" style="margin-top:16px"><button id="continue">Continue →</button><button id="stop" class="stop">■ Stop AI</button></div>${state.chainFeedback?feedback(state.stopped, state.chainFeedback):''}${state.stopped?`<h3>Choose the repair</h3>${choice({options:step.recovery.options,answer:step.recovery.answer,feedback:step.recovery.options.map((_,i)=>i===step.recovery.answer?step.recovery.result:'Does this repair the cause? Check the stopped step.')},'repair')}`:''}`;bind('continue',()=>{if(d.stop){state.chainFeedback=d.why;state.stopped=false;state.done=false}else{state.chainFeedback='';state.chain=Math.min(n+1,items.length-1)}persist();render()});bind('stop',()=>{state.stopped=d.stop;state.chainFeedback=d.why;persist();render()});if(state.stopped)wireChoice(step.recovery,'repair')},
booking(){const tested=state.test;$('#screen').innerHTML=box('TutorTime · one place left','Both students see 16:00 available. Predict: can both reserve it?')+`<div class="split"><div class="testphone"><small>Phone A</small><b>16:00</b><span>${tested==='atomic'?'✓ Reserved':tested==='ui'?'✓ Reserved':'Available'}</span></div><div class="testphone"><small>Phone B</small><b>16:00</b><span>${tested==='atomic'?'Unavailable':tested==='ui'?'✓ Reserved':'Available'}</span></div></div><div class="options"><button id="ui">Test: disable each phone’s button</button><button id="atomic">Test: server checks + reserves together</button></div>${tested?feedback(tested==='atomic',tested==='atomic'?'One booking record. One success. The other request is refused.':'Two confirmations for one slot. Each phone blocked its own second click, but not the other phone.')+box('Shared booking records',tested==='atomic'?'16:00 → Student A · 1 record':'16:00 → Student A AND Student B · conflict'):''}`;bind('ui',()=>{state.test='ui';persist();render()});bind('atomic',()=>{state.test='atomic';mark();render()})}
};
function record(){const rows=session.steps.map((s,i)=>({title:s.title,done:!!saved[session.id+'/'+i]?.done,first:saved[session.id+'/'+i]?.answerFirst,answer:s.answer}));$('#app').innerHTML=`<h1>Your learning record</h1><p>${esc(session.deliverable)}</p>${rows.map(r=>box(r.done?'✓ Checked':'○ Revisit',r.title+(r.first!==undefined?(r.first===r.answer?' · first decision supported':' · revised after feedback'):''))).join('')}<div class="speech"><b>Explain independently</b><p>${esc(step.frame)}</p><p>Your partner checks: specific evidence · a reason · a next action.</p></div><div class="nav"><button id="return">Return to lesson</button><button id="download">Save record</button><button id="reset">Reset this lesson</button><button id="all">All lessons</button></div>`;bind('return',render);bind('all',()=>location.hash='');bind('download',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([session.title+'\n'+rows.map(r=>(r.done?'Checked: ':'Revisit: ')+r.title).join('\n')+'\n\nChecked activities are practice completion, not proof of independent mastery.'],{type:'text/plain'}));a.download='ai-fluency-record.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)});bind('reset',()=>{if(confirm('Reset your saved decisions for this lesson?')){session.steps.forEach((_,i)=>delete saved[session.id+'/'+i]);persist();route()}})}
bind('classroom',()=>{document.body.classList.toggle('classroom');$('#classroom').textContent=document.body.classList.contains('classroom')?'Pair view':'Classroom view'});bind('bangla',()=>{bangla=!bangla;$('#bangla').setAttribute('aria-pressed',bangla);if(window.PhoneLab?.active)window.PhoneLab.setBangla(bangla);else if(session)render()});bind('guide',()=>$('#help').showModal());bind('close',()=>$('#help').close());window.addEventListener('hashchange',route);route();
})();
