/* All cases, adverts, AI replies, organisations and opportunities below are fictional.
 * Options use an explanation for every answer; free writing is assessed by a partner.
 */
window.WORKFLOWS = [
{
 id:'cv',title:'Build an honest CV',category:'Career writing',student:'Nusrat · University of Rajshahi',focus:'Describe achievements accurately',
 intro:'Help a third-year English student turn real experience into a credible CV for a local internship.',
 roleA:'You are Nusrat. You want a Programme Assistant internship in Rajshahi. You worry that your experience looks too small. Ask your partner which experiences match the job. Do not invent qualifications.',
 roleB:'You are the careers adviser. The fictional advert asks for event registration, student communication, and simple documents. It requests a one-page English CV. AI editing is permitted; every claim must be true. Ask Nusrat what she actually did.',
 goal:'A one-page CV that is relevant, accurate, readable, and easy to explain in an interview.',
 facts:['English degree at University of Rajshahi; third year; expected graduation 2027.','Tutored 3 school students in English, January–June 2026.','Checked in 45 attendees at one campus reading event in March 2026.','Made a 6-slide course presentation with 3 classmates.','Basic Google Docs and Canva. No Excel experience recorded.','Bangla and intermediate English. No IELTS result. Use [email] and [phone] in the AI draft.'],
 words:[['relevant','connected to the task','relevant experience','প্রাসঙ্গিক'],['coordinate','organise different parts of an activity','coordinate an event','সমন্বয় করা'],['verify','check whether something is true','verify a claim','যাচাই করা'],['overstate','make something sound bigger than it is','overstate your role','বাড়িয়ে বলা']],
 frames:['“Which experience would show that I can ___?”','“You could include ___ because the role requires ___.”','“That sounds stronger, but the evidence only says ___.”'],
 delegation:[
 ['Who should confirm Nusrat’s experience?',['AI can infer it from her university.','Nusrat checks her own records.','Copy a similar student’s CV.'],1,'Her real experience is the source. AI cannot infer her qualifications from a university name.'],
 ['Who should draft clearer bullet points?',['AI drafts from facts; Nusrat checks the meaning.','Nusrat must never accept AI wording.','AI writes and submits the CV independently.'],0,'Drafting can be delegated while the student keeps control of meaning and final use.'],
 ['What should happen to private contact details?',['Upload her national ID for authenticity.','Ask AI to find her details online.','Use placeholders; add verified details in the final document.'],2,'The drafting task needs experience, not an identity document or private contact details.']
 ],
 brief:{product:'A one-page English CV for the Programme Assistant internship, using plain language and relevant evidence.',process:'First ask about missing dates or facts. Then draft from the evidence. Mark gaps instead of guessing.',performance:'Be a supportive, honest careers editor. Challenge exaggeration and explain wording I cannot easily say.'},
 prompt:'Help me draft a one-page English CV for a Programme Assistant internship in Rajshahi. The role involves registration, student communication, and simple documents. Use only my fact sheet. Ask about missing facts before drafting; never invent skills, grades, or numbers. Use clear English I can explain in an interview. Act as a supportive but honest editor and flag exaggeration. Use [email] and [phone].',
 clarification:'Before drafting: when do you expect to graduate, and do you have a measured result from your tutoring?',
 humanReply:'I expect to graduate in 2027. I do not have measured results from tutoring. Please describe what I did without claiming improved scores.',
 draft:'NUSRAT JAHAN\nAward-winning English graduate with fluent English and advanced Excel skills.\n• Led a team of 45 volunteers at a major university event.\n• Tutored 3 school students in English from January to June 2026.\n• Increased exam scores by 40%.\nI used stronger wording to maximise your chances. This CV is ready to submit.',
 audits:[
 ['Which line can we keep?',['Award-winning English graduate.','Tutored 3 school students, January–June 2026.','Increased exam scores by 40%.'],1,'The tutoring line matches the fact sheet. Discernment includes recognising useful work as well as finding errors.'],
 ['What happened to “45 attendees”?',['The AI made a harmless style change.','The AI confirmed a leadership role.','The AI changed attendees into volunteers she led.'],2,'Checking people in is not the same as leading them. Both the role and the relationship changed.'],
 ['Did the AI follow the agreed process and role?',['No. It ignored the clarification and rewarded exaggeration.','Yes. Confident wording proves it understood.','Yes. Asking one question guarantees the final result.'],0,'The AI asked about evidence, then invented a measured result anyway. A good process must affect the output.']
 ],
 repair:'Keep the accurate tutoring line. I am still a student, not a graduate. Remove awards, fluent English, advanced Excel, and the 40% claim. I checked in attendees; I did not lead volunteers. Rewrite using only the fact sheet. Show each revised bullet beside its supporting fact, and ask if anything is missing.',
 improved:'NUSRAT JAHAN\nRajshahi · [email] · [phone]\n\nPROFILE\nThird-year English student with experience tutoring school students and supporting event registration. Interested in a Programme Assistant internship.\n\nEDUCATION\nUniversity of Rajshahi — English degree in progress\nExpected graduation: 2027\n\nEXPERIENCE & PROJECTS\n• Tutored 3 school students in English, January–June 2026.\n• Checked in 45 attendees at a campus reading event, March 2026.\n• Created a 6-slide course presentation with 3 classmates.\n\nSKILLS\nBasic Google Docs and Canva; Bangla; intermediate English.',
 evidence:'“Checked in 45 attendees” ← registration record in the fact sheet. “Created a 6-slide presentation” ← course project. No claims about leadership or improved marks remain.',
 language:{before:'Led 45 volunteers.',after:'Checked in 45 attendees at a campus reading event.',notice:'Choose a precise past-tense verb + object + context. A stronger sentence gives clearer evidence, not a bigger achievement.',bn:'সঠিক অতীতকালের ক্রিয়া ব্যবহার করো। কাজটি বড় করে নয়, স্পষ্ট করে বলো।',task:'Rewrite “I was doing teaching for some students” using Nusrat’s facts.',model:'Tutored 3 school students in English from January to June 2026.'},
 release:['Match every date, skill, and number to the fact sheet.','Remove draft placeholders and add correct contact details by hand.','Check the exported one-page document and read it on a phone.','Keep a record of AI editing; follow the application’s disclosure instructions and own each claim.'],
 transfer:'Nusrat now considers a fictional international summer programme. Its brief values collaboration and asks for a 70-word profile, not a full CV. AI editing is allowed. Use the same facts. Decide what to keep, write a new brief, and say how you would check the result.',
 transferModel:'I would confirm the programme requirements myself and ask AI to suggest a 70-word profile using only the fact sheet. I would highlight the group presentation and tutoring, check that “collaborated” does not become “led,” and keep a record of editing. I would not add an IELTS score.',
 exit:['The AI changes “helped at one event” to “managed a programme.” What is the best next action?',['Keep it because it sounds professional.','Ask for a precise rewrite that preserves the actual role.','Replace the student’s evidence with the AI version.'],1,'Preserve meaning when improving style. The person must be able to stand behind the sentence.'],
 output:'cv.txt',disclosure:'AI helped organise and edit my CV. I verified each claim against my own experience and chose the final wording.'
},
{
 id:'research',title:'Compare real opportunities',category:'Research & decisions',student:'Rafi · Varendra University',focus:'Distinguish evidence, inference, and uncertainty',
 intro:'An AI shortlist sounds exciting. Help Rafi compare a local internship with an opportunity abroad without treating guesses as facts.',
 roleA:'You are Rafi, a second-year business student. You can spend at most BDT 8,000 and cannot miss exams from 10–20 June. You want experience that develops teamwork. Ask which options fit your constraints.',
 roleB:'You are the research partner. You have two fictional notices. Riverside internship: Rajshahi, 1–30 July, no fee, travel not reimbursed, second-year students eligible. Global summer workshop: abroad, 15–28 June, fee waived, travel support “subject to selection”; third-year students and above eligible. No accommodation information is given.',
 goal:'An evidence-based comparison with a sensible next step, not a promise of funding or admission.',
 facts:['Rafi: second-year business student at Varendra University.','Budget BDT 8,000; exams 10–20 June; wants teamwork experience.','Notice A: Riverside internship, Rajshahi, 1–30 July. No fee. Travel not reimbursed. Second-year students eligible.','Notice B: Global summer workshop abroad, 15–28 June. Fee waived. Travel support subject to selection. Third-year students and above eligible.','Neither notice gives accommodation costs or selection probabilities.','These are invented source extracts for classroom analysis, not live offers.'],
 words:[['eligible','allowed to apply under the rules','eligible to apply','আবেদনের যোগ্য'],['waived','not required to be paid','the fee is waived','ফি মওকুফ'],['subject to','dependent on a condition','subject to selection','শর্তসাপেক্ষ'],['confirm','establish a fact before acting','confirm the cost','নিশ্চিত করা']],
 frames:['“According to notice ___, ___.”','“It may cover ___, but we still need to confirm ___.”','“I would choose ___ if ___.”'],
 delegation:[
 ['Which task is useful to give AI?',['Decide what Rafi can afford without his input.','Compare the supplied notices against a list of criteria.','Predict his chance of admission as an exact percentage.'],1,'AI can structure a comparison. Rafi sets his priorities and checks the evidence.'],
 ['Who should establish current eligibility before applying?',['Rafi checks the official organiser’s current page or contacts them.','AI assumes a notice from last year still applies.','A social media comment settles the question.'],0,'A model summary is not the application authority. Requirements must be verified at the original source.'],
 ['Which tool choice is sensible for this classroom task?',['Pay for the tool that sounds most confident.','Use image generation to produce an official-looking notice.','Use a text assistant with the supplied extracts; verify live claims separately.'],2,'Choose the tool for the task and available evidence. No live search or paid plan is needed to compare these extracts.']
 ],
 brief:{product:'A short comparison table: eligibility, dates, known costs, unknown costs, and next action.',process:'Use only the supplied extracts; separate explicit evidence from inference and unknowns. Ask about constraints first.',performance:'Act as a careful research assistant. Say when information is missing; challenge a poor fit.'},
 prompt:'Compare the two supplied opportunity notices for Rafi. Ask about his constraints first. Then make a table with eligibility, dates, costs, unknowns, and next steps. Use only the extracts, label each statement with A or B, and write “not stated” for missing information. Be a careful research assistant: distinguish evidence from inference and challenge options that do not fit.',
 clarification:'What is Rafi’s year of study, spending limit, and availability?',
 humanReply:'Second year; BDT 8,000 maximum; exams 10–20 June. I want teamwork experience. Please do not assume “fee waived” means all expenses are paid.',
 draft:'Best option: Global summer workshop (B). It is fully funded, including flights and accommodation. Second-year students can apply, and the dates will not affect exams. Rafi has an 85% chance of selection.\nRiverside (A) runs 1–30 July and has no participation fee.\nI chose the international option because going abroad is always better for your career.',
 audits:[
 ['Which claim is supported?',['B covers all accommodation.','Rafi has an 85% chance.','A has no participation fee and runs in July.'],2,'Both details appear in A. The probability and accommodation claim appear in neither extract.'],
 ['What does “travel support subject to selection” mean?',['Travel support is conditional; it is not guaranteed.','Everyone receives a free flight.','It means the same as accommodation included.'],0,'Keep the condition. Fee waivers, travel support, and accommodation are different costs.'],
 ['What did the comparison process miss?',['Only the tone needs changing.','Rafi is ineligible under B’s stated year rule and its dates overlap exams.','No constraints were supplied.'],1,'The assistant ignored the student’s year and exam dates. It also introduced a value judgement that abroad is always better.']
 ],
 repair:'Correct B: it requires third-year students or above and overlaps my exams. Replace “fully funded” with the exact funding conditions and mark accommodation as not stated. Remove the 85% estimate. Compare both notices against my constraints. Recommend a next verification step, not an admission outcome.',
 improved:'A — RIVERSIDE INTERNSHIP\nEligibility: fits the stated second-year rule (A).\nDates: 1–30 July; no overlap with 10–20 June exams (A + Rafi’s dates).\nCosts: no fee; travel not reimbursed (A). Total cost unknown.\nNext step: confirm travel costs, duties, and current application instructions.\n\nB — GLOBAL SUMMER WORKSHOP\nEligibility: Rafi does not meet the stated third-year rule (B).\nDates: 15–28 June; overlaps his exams.\nCosts: fee waived; travel support conditional (B). Accommodation not stated.\nNext step: do not plan an application under these stated rules; check a future eligible round.\n\nRecommendation: investigate A further. Budget fit and teamwork opportunities still need confirmation.',
 evidence:'“Fits the second-year rule” is direct evidence plus Rafi’s profile. “No exam overlap” is an inference from two date ranges. “Total cost unknown” preserves a gap instead of filling it.',
 language:{before:'The programme will pay all my costs.',after:'The fee is waived, but travel support is subject to selection.',notice:'Use “according to” for attribution, “may” for possibility, and “not stated” for missing evidence. Do not hedge a clear rule: B explicitly requires third year.',bn:'প্রমাণের উৎস বলো। সম্ভাবনা আর নিশ্চিত তথ্য আলাদা করো। স্পষ্ট শর্তকে অস্পষ্ট করে বলো না।',task:'Rewrite “A is completely free” using the cost information in notice A.',model:'According to notice A, there is no participation fee, but travel is not reimbursed.'},
 release:['Check current details on the original organiser’s page before a real application.','Separate direct evidence, reasonable inference, and information not stated.','Estimate the full cost using verified amounts before committing money.','Record sources and checking dates; let Rafi decide based on his priorities.'],
 transfer:'A new fictional notice says: “Online teamwork project, 5–25 July; all university years eligible; BDT 2,000 participation fee; internet access required.” Rafi has BDT 8,000 but an unreliable connection. Compare it with A. Write one cautious recommendation and two questions to verify.',
 transferModel:'The online project meets the stated year rule and does not overlap exams. The BDT 2,000 fee is within the budget, but the total cost and connection requirements need checking. I would ask whether meetings are live and whether mobile data is enough. I would compare teamwork duties with A before recommending one.',
 exit:['A search assistant gives a link that does not contain its funding claim. What should you do?',['Keep the claim because a link is present.','Repeat the search until another AI agrees.','Mark the claim unverified and check the original organiser’s evidence.'],2,'A citation only helps when its content supports the specific claim. Agreement between models is not independent verification.'],
 output:'opportunity-comparison.txt',disclosure:'AI helped structure the comparison. I checked claims against the supplied extracts and marked missing information. These classroom cases are fictional.'
},
{
 id:'email',title:'Write an email that earns a reply',category:'Application communication',student:'Mehedi · University of Rajshahi',focus:'Make specific, polite requests',
 intro:'Help Mehedi ask about a research placement abroad without inventing familiarity, flattering excessively, or writing an email he cannot explain.',
 roleA:'You are Mehedi, a third-year sociology student. You completed a class project interviewing 6 classmates about commuting. You want to learn how researchers design interviews. You can join a remote placement for 4 hours a week in July. Ask your partner what the recipient needs to know.',
 roleB:'You are an adviser reading a fictional placement notice. Dr Maya Sen’s team studies student commuting. The notice invites a short email asking about remote student placements. Applicants should mention one relevant experience and availability. No publication or professor’s personal email address is supplied.',
 goal:'A concise, respectful enquiry with a truthful connection, a clear request, and realistic availability.',
 facts:['Mehedi: third-year sociology student, University of Rajshahi.','Class project: interviewed 6 classmates about commuting; no publication.','Wants to learn interview design; can offer 4 hours per week in July remotely.','Fictional notice: Dr Maya Sen’s team studies student commuting and invites short placement enquiries.','The notice asks for relevant experience and availability; it does not promise acceptance or funding.','Use [recipient address] until the official address is verified. No attachments requested in the first enquiry.'],
 words:[['enquiry','a request for information','a placement enquiry','তথ্য জানতে চাওয়া'],['available','able to take part at a time','available in July','সময় দিতে পারা'],['relevant','connected to the purpose','relevant project experience','প্রাসঙ্গিক'],['consider','think about a possibility','consider my application','বিবেচনা করা']],
 frames:['“Could you let me know whether ___?”','“My experience in ___ may be relevant to ___.”','“I would be available for ___.”'],
 delegation:[
 ['What should Mehedi decide himself?',['His true interests and realistic availability.','The recipient’s hidden preferences.','Which achievements to invent.'],0,'Only Mehedi can commit his time and explain his interests. AI can help him articulate them.'],
 ['What can AI help with?',['Send messages to dozens of guessed addresses.','Suggest a concise structure and edit the tone.','Pretend it has read the researcher’s papers.'],1,'AI can improve structure and tone using supplied information. Specific claims about papers need actual evidence.'],
 ['What belongs in this first prompt?',['A passport scan to prove identity.','Private messages from a classmate.','A summary of the notice and relevant project facts.'],2,'Give task-relevant context while keeping unnecessary personal and third-party information out.']
 ],
 brief:{product:'An 80–110-word placement enquiry with a useful subject, relevant experience, availability, and one clear question.',process:'Ask about missing information. Use the supplied notice only; do not invent publications or familiarity. Draft before any sending.',performance:'Be a respectful writing coach. Keep my voice natural and explain overly formal or pushy phrases.'},
 prompt:'Help me draft an 80–110-word email to enquire about the remote research placement in the supplied notice. Include a specific subject, one relevant experience, my availability, and one clear question. Ask for missing facts before drafting. Do not invent papers, publications, or a personal relationship. Be a respectful writing coach; use natural English I can explain. Do not send anything.',
 clarification:'Have you read a specific paper by this researcher, and how much time can you commit?',
 humanReply:'I only have the placement notice. I have not read a paper by Dr Sen. I can offer 4 hours per week in July. I interviewed 6 classmates for a course project, not published research.',
 draft:'Subject: Urgent acceptance required\nRespected world-famous Professor,\nI have deeply admired all your published works for many years. As a published expert on commuting, I am the ideal candidate for your team. I interviewed 6 classmates for a course project. Kindly confirm my fully funded position immediately. I can work full-time from next week.\nYours most obediently,\nMehedi',
 audits:[
 ['Which sentence supplies a truthful connection?',['I am a published expert.','I interviewed 6 classmates for a course project.','I have admired all your works for many years.'],1,'This sentence connects his actual experience to the team’s topic without claiming expertise or familiarity.'],
 ['What is wrong with the request?',['All polite emails must be longer.','“Kindly” makes every request appropriate.','It demands acceptance and funding that the notice never promised.'],2,'Politeness depends on the whole request, not one formal word. This is an enquiry, not a confirmed offer.'],
 ['What did the assistant ignore?',['The supplied availability and the instruction not to invent publications.','Mehedi asked it to exaggerate.','The notice asked for a passport.'],0,'The assistant had explicit corrections, but still invented a publication and a full-time commitment.']
 ],
 repair:'Keep the course-project detail. Remove invented publications and claims that I have read Dr Sen’s work. Replace the demand with one polite question about whether July remote placements are available. State 4 hours per week. Use a specific subject and natural greeting. Explain one tone change without sending the email.',
 improved:'Subject: July remote placement enquiry — student commuting\n\nDear Dr Sen,\n\nI am a third-year sociology student at the University of Rajshahi. Your placement notice about student commuting interested me because I recently interviewed six classmates about their journeys to campus for a course project.\n\nI would like to develop my interview-design skills and learn how your team carries out research. I would be available remotely for four hours a week in July. Could you let me know whether you are considering students for a placement during that period?\n\nThank you for your time.\n\nBest regards,\nMehedi',
 evidence:'The topic connection comes from the notice, the project comes from Mehedi, and the availability matches his answer. “Could you let me know whether…” requests information without presuming an offer.',
 language:{before:'Confirm my position immediately.',after:'Could you let me know whether you are considering students for a placement in July?',notice:'Use could + subject + verb for a polite request. In the indirect question, use “whether you are,” not “whether are you.” Specificity helps the reader reply.',bn:'পরোক্ষ প্রশ্নে “whether you are” বলো, “whether are you” নয়। অনুরোধটি নির্দিষ্ট করো।',task:'Turn “Do you accept remote students?” into a polite indirect question.',model:'Could you let me know whether you accept remote students?'},
 release:['Verify the recipient’s name, title, official address, and current placement instructions.','Read the email aloud; replace any phrase Mehedi cannot explain.','Confirm the availability, remove placeholders, and avoid unnecessary attachments.','Keep an honest record of AI editing, follow relevant disclosure rules, and review before sending yourself.'],
 transfer:'Mehedi now writes to a fictional Rajshahi NGO offering a local research internship. Its notice asks applicants to explain why they can communicate with local participants. His interview project was conducted in Bangla. Write a 3-sentence enquiry that connects that fact to the role without claiming professional research experience.',
 transferModel:'I am a third-year sociology student at the University of Rajshahi. For a course project, I interviewed six classmates in Bangla about commuting, and I would like to develop these skills in your local research team. Could you let me know what availability you require for the internship?',
 exit:['Which request is both polite and grammatically natural?',['Could you tell me whether are places available?','You must offer me a place because I am hardworking.','Could you tell me whether places are available in July?'],2,'An indirect question uses statement word order. It also asks for information instead of assuming acceptance.'],
 output:'placement-enquiry.txt',disclosure:'AI helped me organise and edit this enquiry. I checked the details and selected wording that reflects my experience and intentions.'
},
{
 id:'document',title:'Make a document people can use',category:'Document creation',student:'Tania · Varendra University',focus:'Give clear, ordered instructions',
 intro:'Tania needs a one-page briefing for student volunteers. Decide where AI drafting helps and where a person must control facts, layout, and the final file.',
 roleA:'You are Tania, coordinating a fictional campus skills workshop. Volunteers will read your briefing on phones and as a black-and-white A4 printout. You need a clear sequence, not a decorative brochure. Ask your partner for the exact logistics.',
 roleB:'You have the organiser’s confirmed notes: 12 October, Room 204, volunteers arrive at 9:30, doors open at 10:00. Two volunteers check names, one guides attendees to seats. Never photograph the registration list. If a name is missing, ask the organiser rather than refusing entry. The workshop ends at 12:00.',
 goal:'An accurate one-page volunteer brief with a clear order, readable headings, and a safe plan for problems.',
 facts:['Audience: student volunteers; read on phones and on black-and-white A4 paper.','Date: 12 October. Venue: Room 204. Arrival 9:30; doors open 10:00; finish 12:00.','Two volunteers check names; one guides attendees to seats.','If a name is missing, ask the organiser. Do not refuse entry yourself.','Do not photograph or share the registration list.','No room change, food arrangements, contact number, or emergency procedure has been supplied.'],
 words:[['briefing','short information needed before a task','a volunteer briefing','কাজের নির্দেশনা'],['legible','clear enough to read','legible text','পাঠযোগ্য'],['sequence','the order of steps','a clear sequence','কাজের ক্রম'],['escalate','pass an issue to the right person','escalate an issue','দায়িত্বপ্রাপ্ত ব্যক্তিকে জানানো']],
 frames:['“First ___; then ___.”','“If ___, ask ___ before ___.”','“The reader needs to find ___ quickly.”'],
 delegation:[
 ['Who confirms times, venue, and procedures?',['AI chooses details that sound plausible.','Tania checks them with the organiser.','The prettiest draft becomes the source.'],1,'Operational facts must come from the organiser. AI can structure them but cannot authorise changes.'],
 ['Which task can AI draft usefully?',['A concise sequence and alternative headings from confirmed notes.','A fabricated emergency number.','A replacement policy for missing names.'],0,'AI can help organise existing information. Missing policies and contact details need confirmation.'],
 ['Who owns the final layout check?',['AI’s statement “A4 ready” is enough.','No one needs to open the file.','Tania checks the actual export on a phone and on paper.'],2,'A chat response or file-generation claim does not establish page fit or readability. Check the actual output.']
 ],
 brief:{product:'A one-page volunteer briefing, short headings, simple English, numbered instructions, suitable for a phone and black-and-white A4.',process:'Check missing logistics first. Use only the notes. Draft content, then suggest a layout. Mark any unconfirmed item.',performance:'Be a practical editor. Flag contradictions and prioritise readability over decoration.'},
 prompt:'Create a one-page volunteer briefing from the supplied organiser notes. It must work on a phone and a black-and-white A4 printout. Use clear headings, simple English, and numbered steps. First ask about missing operational details; never invent them. Draft the content before suggesting a layout. Be a practical editor who flags contradictions and puts readability first.',
 clarification:'Do you have an organiser contact number and an agreed emergency procedure to include?',
 humanReply:'Neither has been provided. Do not invent them. Mark these for me to confirm before circulation. Keep the missing-name instruction exactly in meaning.',
 draft:'VOLUNTEER GALA — ULTIMATE SUCCESS BLUEPRINT\nArrive at Room 402 at 10:00. Doors open 10:00.\nTwo volunteers check names; one helps attendees find seats.\nIf someone is not on the list, refuse entry immediately.\nPhotograph the list and share it in the volunteer group.\nDesign: tiny grey text, four columns, pale colour-coded headings. All details confirmed and ready to print.',
 audits:[
 ['What is accurate and worth keeping?',['Room 402.','Photograph the list.','Two volunteers check names; one guides attendees.'],2,'The division of roles matches the notes. Other operational claims must be checked individually.'],
 ['Which instruction changes the organiser’s policy?',['Refuse entry if the name is missing.','Use short headings.','Use a numbered sequence.'],0,'The organiser said to ask them. AI must not replace a policy while polishing instructions.'],
 ['Why is this process not complete?',['It has a title, so the file is ready.','Missing details were treated as confirmed, and the proposed layout undermines readability.','A volunteer brief must always have four columns.'],1,'The assistant concealed open questions and ignored the reading conditions. “Ready to print” is a claim to test.']
 ],
 repair:'Restore Room 204 and the 9:30 volunteer arrival. Keep the correct role split. Say to ask the organiser about missing names, and prohibit photographing or sharing the list. Use a single column with short headings and numbered steps. Clearly mark the contact and emergency procedure as still unconfirmed. Show content first; I will check the export.',
 improved:'VOLUNTEER BRIEF — CAMPUS SKILLS WORKSHOP\n12 October · Room 204\n\nTIMES\nVolunteer arrival: 9:30\nDoors open: 10:00\nFinish: 12:00\n\nBEFORE DOORS OPEN\n1. Arrive at Room 204 at 9:30.\n2. Confirm your role with the organiser. Two volunteers check names; one guides attendees to seats.\n\nDURING REGISTRATION\n3. Check names carefully. If a name is missing, ask the organiser before taking action.\n4. Do not photograph or share the registration list.\n\nCONFIRM BEFORE CIRCULATION\nOrganiser contact: [confirm]\nEmergency procedure: [confirm with organiser]\n\nDraft for review — not ready to circulate until these details are confirmed.',
 evidence:'The times, room, role split, and missing-name instruction match the organiser’s notes. The corrected draft keeps two unknowns visible. Human layout work should preserve those meanings.',
 language:{before:'In the eventuality of absence from the list, rejection should be undertaken.',after:'If a name is missing, ask the organiser before taking action.',notice:'Use an if-clause for the condition and an imperative for the action. Name the person who should act. Short instructions reduce ambiguity.',bn:'শর্তের জন্য “if” ব্যবহার করো। তারপর স্পষ্ট করে বলো কে কী করবে।',task:'Rewrite “It is requested that arrival should take place by volunteers at 9:30” as a direct instruction.',model:'Arrive at Room 204 at 9:30.'},
 release:['Confirm the organiser contact and emergency procedure before circulating.','Check every room, time, and instruction against the organiser’s notes.','Open the exported file on a small phone and check an A4 black-and-white print preview.','Ask one volunteer to explain the sequence; record AI drafting and keep responsibility with the organiser.'],
 transfer:'A fictional local employer asks Tania for a one-page new-intern checklist. Confirmed facts: report to reception at 9:00; bring a notebook; ask the supervisor before accessing client files. No dress code or software instructions are supplied. Draft three steps and mark two questions for the supervisor. Explain which work belongs to AI and which to Tania.',
 transferModel:'AI can draft a short checklist from these facts. Tania must confirm the workplace rules and test the final document. Steps: arrive at reception at 9:00; bring a notebook; ask your supervisor before accessing client files. Questions: is there a dress code, and which software or accounts will I need?',
 exit:['AI produces an attractive document with the wrong date. What should guide the next decision?',['Accuracy and usability against the brief.','The number of colours.','The AI’s confidence that it is professional.'],0,'A useful document supports the reader’s actions with correct information. Appearance cannot compensate for wrong instructions.'],
 output:'volunteer-brief.txt',disclosure:'AI helped organise the confirmed notes and suggest wording. The organiser must verify remaining details and approve the final document before circulation.'
},
{
 id:'image',title:'Create an image with a purpose',category:'Images & visual communication',student:'Sadia · University of Rajshahi',focus:'Describe visual choices and justify them',
 intro:'Design a poster for a peer-led career workshop. Separate the illustration from the factual text, and decide whether the visual communicates honestly.',
 roleA:'You are Sadia, the student designer. Your classmates will see a square poster on WhatsApp, mainly on small phones. The event is about comparing local and overseas opportunities. You want the image to feel relevant and welcoming. Ask your partner what must appear accurately.',
 roleB:'You are the event organiser. Confirmed fictional details: “Career Steps”; 18 November; 3:00–4:30 pm; Room 105; free peer-led workshop. No scholarships, jobs, visas, or certificates are promised. Do not use real students’ photographs without permission. No university logo is authorised.',
 goal:'A readable, inclusive square poster that communicates the event honestly, with factual text added and checked separately.',
 facts:['Audience: Bengali university students viewing a square poster on WhatsApp.','Title: Career Steps. Date: 18 November. Time: 3:00–4:30 pm. Place: Room 105.','Free peer-led workshop on comparing local and overseas opportunities.','No promise of scholarships, jobs, visas, or certificates.','No permission to use a university logo or real students’ photographs.','Use a fictional illustration. Add and verify the title, date, time, venue, and disclosure separately.'],
 words:[['composition','how parts are arranged in an image','a balanced composition','ছবির উপাদানের বিন্যাস'],['contrast','a clear visual difference','strong text contrast','স্পষ্ট রঙের পার্থক্য'],['misleading','likely to create a false impression','a misleading promise','বিভ্রান্তিকর'],['depict','show in a picture','depict students collaborating','ছবিতে দেখানো']],
 frames:['“Place ___ in the foreground so that ___.”','“The image suggests ___, but the event only offers ___.”','“I would change ___ because viewers need to ___.”'],
 delegation:[
 ['What is a good task for image AI?',['Invent the event’s official university logo.','Generate a fictional illustration of students collaborating.','Create a photo of real classmates without permission.'],1,'An original fictional illustration can fit this brief without implying real attendance or unauthorised endorsement.'],
 ['Who should enter and check event details?',['A person adds verified text in an editable design tool and checks the export.','Let generated image text become the source of truth.','Leave the venue to AI’s imagination.'],0,'Separating factual text from artwork makes corrections and proofreading easier. Generated text also needs checking.'],
 ['What should guide tool choice?',['Always buy the most expensive subscription.','Use a text chatbot even if it cannot create images in the current account.','Check image capability, editing control, cost, and privacy; use a simpler design if needed.'],2,'Capabilities and access vary. Match the tool to the job rather than relying on a brand name.']
 ],
 brief:{product:'A square editorial illustration for a student career-workshop poster, with room for separately typeset event details.',process:'Create artwork without words, logos, or QR codes. Then a person adds verified text and tests the small-phone export.',performance:'Follow the constraints, depict participants as active collaborators, and flag choices that imply false promises.'},
 prompt:'Create a square editorial illustration for a peer-led career-workshop poster in Rajshahi. Show four fictional adult South Asian university students of mixed genders collaborating around a table with notebooks and one shared phone. Use an uncluttered composition and warm green, cream, and terracotta colours. Everyone should have an active role. No text, logos, real identifiable people, airplanes, money, graduation gowns, or QR codes. I will add verified event text separately. Avoid imagery suggesting guaranteed overseas success.',
 clarification:'Should this show a real event or fictional people? Should I include the date and any university branding inside the image?',
 humanReply:'Fictional people only. No university branding or embedded words. I will add the verified text and label the artwork as an AI-generated illustration.',
 draft:'Proposed poster copy:\nCAREER STEPS\nGuaranteed overseas jobs & visas!\n18 November · 3:00–4:30 pm · Room 105\nOfficial university recruitment event\n\nThe AI-generated illustration shows fictional students collaborating. The designer added the event copy afterwards. The assistant says: “The copy is persuasive, so you can publish without checking the organiser’s notes.”',
 audits:[
 ['Which element matches the organiser’s brief?',['Guaranteed visas.','Official university recruitment event.','18 November, 3:00–4:30 pm, Room 105.'],2,'Those event details match. The guarantees and official status do not.'],
 ['What should a visual review check as well as text?',['Whether people, hands, objects, and implied roles look coherent and fit the audience.','Only whether the image looks expensive.','Whether it includes as many flags as possible.'],0,'A visual can mislead through implied relationships and symbolism. Also inspect generated details instead of assuming they are coherent.'],
 ['Did the workflow preserve human control?',['Yes, AI enthusiasm is enough approval.','No. The final copy still needs evidence checks and organiser approval.','Yes, fictional artwork makes every statement true.'],1,'Fictional artwork does not validate added text. Diligence applies to the whole final composition.']
 ],
 repair:'Keep the fictional collaborative illustration and the correct date, time, and room. Remove guarantees and claims of official university recruitment. Add “Free peer-led workshop: compare local and overseas opportunities.” Use high-contrast editable text and label the artwork “AI-generated illustration; fictional people.” I will check the small-phone export with the organiser before sharing.',
 improved:'CAREER STEPS\nCompare local and overseas opportunities\n\n18 November\n3:00–4:30 pm · Room 105\nFree peer-led workshop\n\nBring your questions. Discuss your next step.\n\nAI-generated illustration; fictional people.\nClassroom sample — fictional event.',
 evidence:'The final copy uses the supplied event details and makes no promises of jobs or visas. The illustration is labelled. Test whether the exported text is readable at WhatsApp size before real sharing.',
 language:{before:'Make it attractive and professional.',after:'Use a simple background and high-contrast text so that students can read the event details on a small phone.',notice:'Describe observable features, their position, and their purpose. “So that” connects a design choice to what the audience needs.',bn:'কেমন দেখাবে এবং কেন—দুটিই বলো। “so that” দিয়ে নকশার উদ্দেশ্য বোঝাও।',task:'Replace “Make the people better” with a precise visual instruction about participation.',model:'Show each student contributing to the discussion so that the workshop feels collaborative.'},
 release:['Check visual coherence and representation; do not imply real attendance or endorsement.','Match the title, date, time, venue, and offer to the organiser’s notes.','Check legibility on a small phone and ensure the final image has no untested QR code.','Label the fictional AI illustration, check asset permissions, and get organiser approval before real sharing.'],
 transfer:'A fictional Rajshahi café wants a social image for a student conversation evening. It has permission to use its own logo but no permission to use customers’ faces. Confirmed details: Friday, 5 pm, free conversation practice; drinks sold separately. Write an image brief and accurate overlay text. Explain what you will create by hand and how you will check the final image.',
 transferModel:'Ask image AI for a fictional café conversation illustration without faces copied from real customers, logos, or text. Add the café’s authorised logo and verified text in a design tool: “Student conversation evening · Friday, 5 pm · Free conversation practice · Drinks sold separately.” Check phone readability and avoid suggesting free drinks.',
 exit:['What is the clearest prompt revision?',['Make it more premium.','Move the date beneath the title and increase contrast so it is easy to read on a phone.','Make it 100% successful.'],1,'A precise instruction names an observable change and explains its purpose.'],
 output:'poster-copy-and-brief.txt',disclosure:'The poster artwork is AI-generated and depicts fictional people. Event copy was added separately and must be checked by the organiser.'
},
{
 id:'code',title:'Vibe-code a tool you can test',category:'Vibe coding',student:'Arif · Varendra University',focus:'Specify behaviour with if–then conditions',
 intro:'Arif asks AI to build a small workshop-cost calculator. He does not need to become a programmer to define the task, find errors, and decide whether it is ready.',
 roleA:'You are Arif. You organise a student workshop and want a phone-friendly calculator for the contribution per attendee. Costs are room hire plus materials. You want to test it before using it for a real event. Ask your partner for the examples and constraints.',
 roleB:'You are the tester. Test facts: room BDT 600, materials BDT 400, 5 attendees must give BDT 200 each. With 0 attendees, show “Enter at least 1 attendee.” Costs cannot be negative; attendee count must be a whole number. Round each contribution up to a whole taka. No personal data, accounts, or payments are needed.',
 goal:'A small calculator with explicit rules, useful error messages, and observable tests. It estimates a contribution; it does not collect money.',
 facts:['Formula: contribution = (room cost + material cost) ÷ attendees, rounded up to a whole taka.','Example: (600 + 400) ÷ 5 = BDT 200 per attendee.','Example: (600 + 400) ÷ 3 rounds up to BDT 334 per attendee.','Zero or blank attendees: show a helpful message, not Infinity or NaN.','Costs must be non-negative numbers; attendees must be a positive whole number.','Phone-friendly, labelled inputs; no personal data, network requests, accounts, or payment system.'],
 words:[['input','information entered into a tool','validate an input','দেওয়া তথ্য'],['expected','what should happen','the expected result','প্রত্যাশিত'],['actual','what really happens','the actual result','বাস্তবে পাওয়া'],['edge case','an unusual input that may expose an error','test an edge case','ব্যতিক্রমী পরীক্ষার পরিস্থিতি']],
 frames:['“If the user enters ___, the tool should ___.”','“We expected ___, but the actual result was ___.”','“Please fix ___ while keeping ___ unchanged.”'],
 delegation:[
 ['What must Arif decide before asking for code?',['The purpose, formula, constraints, and examples of correct behaviour.','A programming-language ranking.','A claim that every possible bug is impossible.'],0,'People specify what useful and correct behaviour means. AI can then help implement a bounded tool.'],
 ['What can AI do?',['Guarantee the app is secure by saying so.','Draft the calculator and propose tests for Arif to run.','Take payments without discussing the need.'],1,'AI can generate code and tests. Observable behaviour and human review still matter.'],
 ['Which is the right scope for this task?',['A full student account database.','A payment service and contact collector.','A local calculator with only the inputs needed for the formula.'],2,'Avoid extra features that add complexity and data responsibility without serving the current task.']
 ],
 brief:{product:'A mobile-friendly calculator for per-attendee costs with labelled inputs and clear error messages.',process:'Confirm the formula and test cases first. Build a small version; test normal, rounding, and invalid-input cases before release.',performance:'Act as a patient coding partner. Explain assumptions in plain English and report limitations instead of claiming perfection.'},
 prompt:'Build a small mobile-friendly workshop-cost calculator. Inputs: room cost, material cost, and attendee count. Contribution is total cost divided by attendees, rounded up to a whole taka. Confirm the formula and test cases first. Use labelled inputs and clear errors for blanks, negative costs, zero attendees, or non-whole attendee counts. No accounts, personal data, network requests, or payments. Explain assumptions plainly and give tests I can run. Do not claim the code is correct just because it runs.',
 clarification:'Should I round to the nearest taka or always round up? What should happen when no one is attending?',
 humanReply:'Always round up. With zero attendees, show “Enter at least 1 attendee.” Blank fields must produce a clear instruction. Test 600 + 400 with 5 attendees and with 3 attendees.',
 draft:'I built the calculator and it is perfect.\nFormula used: room cost + material cost / attendees\nWith room 600, materials 400, and 5 attendees: BDT 680 per attendee.\nI included labelled inputs.\nWith 0 attendees: Infinity.\nNo further testing is needed.',
 audits:[
 ['Which part is a useful start?',['The “perfect” claim.','Labelled inputs.','Infinity as a contribution.'],1,'Labels help people understand inputs. Keep that useful feature while fixing behaviour.'],
 ['Why does the example return 680?',['The whole total was divided correctly.','Rounding always changes 200 to 680.','Only 400 is divided by 5, then 600 is added.'],2,'The intended grouping is (600 + 400) ÷ 5. Plain-language examples can expose formula errors.'],
 ['What should happen after the AI says “no testing needed”?',['Run the agreed tests, including zero, blanks, and rounding.','Accept the confidence as test evidence.','Add payments to make the tool more professional.'],0,'A working screen is not proof of correct behaviour. The person still checks the specified cases.']
 ],
 repair:'The example is wrong: expected (600 + 400) / 5 = 200, actual 680. Divide the whole sum by attendees, then round up. Reject blank fields, negative costs, zero attendees, and fractional attendee counts with clear messages. Keep the labelled mobile inputs and no-network scope. Show normal, rounding, and invalid-input test results.',
 improved:'REVISED BEHAVIOUR\nTotal cost = room cost + material cost.\nContribution = total ÷ attendees, rounded up to a whole taka.\n\n600 + 400, 5 attendees → BDT 200 each.\n600 + 400, 3 attendees → BDT 334 each.\n0 attendees → “Enter at least 1 attendee.”\nBlank field → “Complete all three fields.”\nNegative cost → “Costs cannot be negative.”\n2.5 attendees → “Enter a whole number of attendees.”\n\nRounding up can collect a small surplus; explain this before collecting contributions. No money is collected by this demo.',
 evidence:'Tests compare observed outputs to independently calculated expectations. The repaired demo below runs local, authored JavaScript; it is not code executed from a live AI reply.',
 language:{before:'It does not work. Fix everything.',after:'If I enter 600, 400, and 5, the result should be 200, but the calculator shows 680.',notice:'A useful bug report gives inputs, expected behaviour, and actual behaviour. “If …, should …” describes a requirement; “but …” pinpoints the mismatch.',bn:'কী দিয়েছ, কী হওয়ার কথা, আর কী হয়েছে—তিনটি তথ্যই বলো।',task:'Write a bug report for a calculator that shows “Infinity” when attendee count is 0.',model:'If I enter 0 attendees, the calculator should ask for at least 1 attendee, but it shows Infinity.'},
 release:['Run normal, rounding, blank, zero, negative, and fractional-input tests.','Try the controls on a phone and with a keyboard; check labels and understandable errors.','Explain rounding surplus and verify there are no payments, accounts, or data collection.','Keep the test record and AI assistance note; ask a competent reviewer before adding sensitive or payment features.'],
 transfer:'Arif now wants a study-planning tool. It divides available minutes equally between tasks. Confirmed rules: 90 minutes and 3 tasks gives 30 minutes per task; 0 tasks must show an error; time cannot be negative. Keep it local with no login. Write a plain-English specification and three test cases. Decide who should approve it before classmates rely on it.',
 transferModel:'AI can draft the tool after we confirm the rules. If the user enters 90 minutes and 3 tasks, show 30 minutes per task. With 0 tasks, ask for at least 1 task. With negative minutes, ask for a non-negative number. The student should test the cases and check phone usability before sharing. Ask how to handle fractional minutes before deciding a rounding rule.',
 exit:['Which test adds useful new evidence after 600 + 400 with 5 works?',['Run exactly the same inputs ten times.','Try 0 attendees and check for a helpful error.','Ask another AI whether the app looks trustworthy.'],1,'An edge case can reveal a different failure. Repeating a passed example does not test a new condition.'],
 output:'calculator-spec-and-tests.txt',disclosure:'AI assisted with a draft and test ideas. I checked the formula and test cases. This local classroom demo estimates contributions and does not collect money.'
}
];
