// Page, exact phrase, category, short explanation, Bangla meaning.
const ECCLESIASTES_GLOSSARY = [
  [1,"fully awake","Word","Completely awake and active. Here the city is only beginning its day.","পুরোপুরি জেগে ওঠা; এখানে শহরের দিনের কাজ সবে শুরু হচ্ছে।"],
  [1,"minarets","Word","The tall towers beside a mosque.","মসজিদের মিনার।"],
  [1,"His room is small; his dreams are not","Grammar","The second clause leaves out 'small': his dreams are not small. This omission creates a contrast.","দ্বিতীয় অংশে ‘small’ কথাটি আর বলা হয়নি: তার স্বপ্ন ছোট নয়।"],
  [1,"tea stall","Phrase","A small shop or roadside place where people drink tea and talk.","চায়ের দোকান; যেখানে মানুষ চা খায় ও আড্ডা দেয়।"],
  [1,"begins to burn","Metaphor","His desire becomes intense. There is no actual fire inside him.","তীব্র আকাঙ্ক্ষা জেগে ওঠে; সত্যিকারের আগুন নয়।"],
  [1,"a small bridge","Metaphor","His study connects his present life with the future he imagines.","পড়াশোনা তার বর্তমান জীবন ও কল্পিত ভবিষ্যতের মধ্যে যোগসূত্র তৈরি করে।"],
  [1,"far away","Phrase","Distant. A dream can also feel far away when it seems hard to achieve.","অনেক দূরে; স্বপ্ন পূরণ করা কঠিন মনে হলেও এই কথাটি বলা হয়।"],
  [1,"thin mist","Image","A light cloud of tiny water drops. In the story it suggests that the dream cannot last.","হালকা কুয়াশা; গল্পে স্বপ্নের অস্থায়িত্বের ইঙ্গিত।"],
  [2,"Before dawn","Time phrase","Before the first light of morning.","ভোরের আলো ফোটার আগে।"],
  [2,"His eyes are heavy","Phrase","He is sleepy and finds it hard to keep his eyes open.","ঘুমে তার চোখ জড়িয়ে আসছে।"],
  [2,"one page at a time","Pattern","He makes progress in small steps: one page, then another.","একবারে একটি পৃষ্ঠা করে; ধীরে ধীরে এগিয়ে যাওয়া।"],
  [2,"trying to be brave","Phrase","Trying to face a difficult moment without showing fear or sadness.","কষ্টের মুহূর্তেও সাহস ধরে রাখার চেষ্টা করা।"],
  [2,"one last moment","Phrase","A final short time together before they separate.","বিদায়ের আগে একসঙ্গে কাটানো শেষ একটু সময়।"],
  [2,"far from home","Phrase","A long way from his family and familiar surroundings.","বাড়ি, পরিবার ও পরিচিত পরিবেশ থেকে অনেক দূরে।"],
  [2,"curls around","Verb phrase","Moves around something in curved shapes, as mist or smoke can do.","কোনো কিছুর চারপাশে পাক খেয়ে ওঠে।"],
  [3,"hurries across","Verb phrase","Moves quickly from one side of a place to the other.","তাড়াতাড়ি এক পাশ থেকে অন্য পাশে যায়।"],
  [3,"cap and gown","Phrase","The special hat and long robe worn at graduation.","স্নাতক সমাপনী অনুষ্ঠানে পরা টুপি ও লম্বা পোশাক।"],
  [3,"held like a trophy","Comparison","He holds the diploma as if it were a prize for winning.","জয়ের পুরস্কারের মতো করে সনদটি ধরে আছে।"],
  [3,"feels worth it","Phrase","Seems valuable enough to justify the effort or difficulty.","কষ্ট ও পরিশ্রম সার্থক হয়েছে বলে মনে হয়।"],
  [3,"admired from far away","Phrase","Respected or wanted something before he could take part in it.","যে জীবনকে আগে দূর থেকে মুগ্ধ হয়ে দেখত।"],
  [3,"the ladder does not end","Metaphor","Each achievement leads to wanting another. This is a ladder of ambition.","একটি সাফল্যের পর আরেকটি চাওয়া; উচ্চাকাঙ্ক্ষার সিঁড়ি যেন শেষ হয় না।"],
  [3,"moving upward","Metaphor","Advancing in wealth or status, as well as literally riding upward.","আক্ষরিক অর্থে ওপরে ওঠা, আর রূপক অর্থে ধন বা মর্যাদায় এগিয়ে যাওয়া।"],
  [4,"is placed","Grammar","Passive voice: the focus is on the key being given, rather than the person giving it.","কর্মবাচ্য: কে চাবিটি দিল তার চেয়ে চাবি দেওয়ার ঘটনাটিই এখানে মুখ্য।"],
  [4,"a promise fulfilled","Phrase","Something hoped for that has now happened.","প্রত্যাশা বা প্রতিশ্রুতি পূরণ হওয়া।"],
  [4,"in rose and gold","Description","Wearing rose-colored and gold-colored clothing or decorations.","গোলাপি ও সোনালি রঙের পোশাক বা সাজে।"],
  [4,"he made it","Idiom","He achieved the success he wanted.","সে সফল হয়েছে; কাঙ্ক্ষিত অবস্থানে পৌঁছেছে।"],
  [4,"his younger self","Phrase","The person he was earlier in life.","কম বয়সে সে যেমন ছিল; তার তরুণ বয়সের সত্তা।"],
  [4,"and still","Discourse","Adds something that remains true despite everything just listed.","এত কিছুর পরেও যে অবস্থা রয়ে গেছে, তা বোঝায়।"],
  [5,"becomes a chain","Metaphor","His routine begins to feel like something that traps him.","দৈনন্দিন রুটিন তাকে বেঁধে রাখা শিকলের মতো হয়ে ওঠে।"],
  [5,"like a guest in his own life","Metaphor","He feels detached from a life that should belong to him.","নিজের জীবনেও যেন বাইরের অতিথি; আপনত্ব অনুভব করে না।"],
  [5,"Their bodies are close","Contrast","They sit near each other, but the following clause shows emotional distance.","কাছে বসে থাকলেও পরের অংশে তাদের মনের দূরত্ব বোঝানো হয়েছে।"],
  [5,"disappears into","Metaphor","Becomes so absorbed in something that contact with others fades.","কোনো কিছুতে এত ডুবে যায় যে অন্যদের সঙ্গে যোগাযোগ কমে যায়।"],
  [5,"except him","Grammar","Everyone else is included; he is left out.","সে ছাড়া অন্য সবাই; তাকে বাদ দিয়ে।"],
  [5,"begin to fade","Verb phrase","Start to become less clear or less powerful.","ধীরে ধীরে ফিকে বা দুর্বল হয়ে যেতে শুরু করে।"],
  [5,"His heart is not","Grammar","The words 'full of light' are understood from the previous sentence. His inner life feels dark.","আগের বাক্যের ‘আলোয় ভরা’ কথাটি এখানে আর বলা হয়নি; তার মনের অবস্থা অন্ধকার।"],
  [6,"with his head in his hand","Description","A posture that can show tiredness, worry, or grief.","হাতে মাথা ঠেকিয়ে; ক্লান্তি, দুশ্চিন্তা বা শোকের ভঙ্গি।"],
  [6,"heavy with grief","Phrase","Deeply burdened by sorrow after loss.","শোকে ভারাক্রান্ত।"],
  [6,"cannot enter this room and fix it","Metaphor","Money or achievement cannot undo this illness and loss.","অর্থ বা সাফল্য এই অসুস্থতা ও ক্ষতিকে মুছে দিতে পারে না।"],
  [6,"bows his head","Verb phrase","Lowers his head, here in prayer and sorrow.","মাথা নিচু করে; এখানে প্রার্থনা ও শোকে।"],
  [6,"reflective","Word","Quietly thinking about something deeply.","চিন্তামগ্ন; গভীরভাবে ভাবছে।"],
  [6,"the ground receives them both","Image","Both people are buried, whatever their social position was.","সামাজিক অবস্থান যা-ই হোক, দুজনই মাটিতে সমাহিত হয়।"],
  [6,"known and unknown","Paired contrast","Famous people and people who are not widely recognized.","পরিচিত ও অপরিচিত; খ্যাতিমান ও অখ্যাত মানুষ।"],
  [7,"strain","Word","Work with great physical effort.","শরীরের সব শক্তি দিয়ে কষ্ট করে কাজ করা।"],
  [7,"while weakness sits ignored","Contrast","'While' compares two simultaneous but unequal situations.","‘While’ একই সময়ে ঘটতে থাকা দুটি অসম অবস্থার তুলনা করে।"],
  [7,"bent over","Phrase","Leaning forward over something. Here it also suggests pressure or burden.","সামনে ঝুঁকে থাকা; এখানে চাপ বা বোঝার ইঙ্গিতও আছে।"],
  [7,"exhaustion","Word","Extreme tiredness after effort or stress.","পরিশ্রম বা চাপের ফলে চরম ক্লান্তি।"],
  [7,"rises and sets","Verb pair","The sun appears in the morning and disappears in the evening.","সূর্য ওঠে ও অস্ত যায়।"],
  [7,"stands still","Phrase","Stops moving. Here he also stops joining the endless race.","স্থির দাঁড়িয়ে থাকে; এখানে অন্তহীন দৌড়ে অংশ নেওয়া থামায়।"],
  [7,"the treadmill","Metaphor","A machine for running without moving forward; an image of endless effort without arrival.","এক জায়গায় দাঁড়িয়ে দৌড়ানোর যন্ত্র; শেষহীন পরিশ্রমেও কোথাও না পৌঁছানোর রূপক।"],
  [8,"gather around","Verb phrase","Come together around someone or something.","কারও বা কিছুর চারপাশে একত্র হওয়া।"],
  [8,"grief sits beside a bed","Personification","Grief is described as if it were a person sitting in the room.","শোককে ঘরে বসে থাকা মানুষের মতো করে বর্ণনা করা হয়েছে।"],
  [8,"comforts","Word","Helps someone feel less sad or distressed.","সান্ত্বনা দেয়; দুঃখ বা কষ্ট কিছুটা কমাতে সাহায্য করে।"],
  [8,"mourning","Word","Grieving because someone has died or something important has been lost.","মৃত্যু বা বড় ক্ষতির জন্য শোক করা।"],
  [8,"Life is not one season","Metaphor","Life includes different kinds of time: joy, sorrow, work, and rest.","জীবনে আনন্দ, দুঃখ, কাজ ও বিশ্রামের ভিন্ন ভিন্ন সময় আছে।"],
  [8,"can be controlled","Grammar","'Can be' plus a past participle describes what it is possible to control.","‘Can be’ ও ক্রিয়ার past participle দিয়ে নিয়ন্ত্রণ করা সম্ভব কি না বোঝানো হয়।"],
  [8,"every moment can be received","Image","Each moment can be accepted, even when it cannot be chosen.","সব মুহূর্ত বেছে নেওয়া যায় না, কিন্তু প্রতিটি মুহূর্ত গ্রহণ করা যায়।"],
  [9,"modest","Word","Simple and not expensive or grand.","সাধারণ, অনাড়ম্বর; দামি বা জাঁকজমকপূর্ণ নয়।"],
  [9,"that is enough","Phrase","Nothing more is needed to make this moment valuable.","এই মুহূর্তকে মূল্যবান করতে আর কিছু দরকার নেই।"],
  [9,"a promotion","Word","Moving to a higher position at work.","কাজে উচ্চতর পদে উন্নীত হওয়া; পদোন্নতি।"],
  [9,"No one is performing","Metaphor","Nobody is trying to impress an audience or put on a perfect appearance.","কেউ অন্যকে মুগ্ধ করার জন্য অভিনয় বা নিখুঁত সাজ দেখাচ্ছে না।"],
  [9,"Everyone belongs","Phrase","Everyone feels accepted as part of the group.","সবাই আপনজন হিসেবে গ্রহণযোগ্য; সবারই এখানে জায়গা আছে।"],
  [9,"offers thanks","Verb phrase","Expresses gratitude.","কৃতজ্ঞতা জানায়।"],
  [9,"fragile beauty","Phrase","Beauty that is delicate and will not last forever.","কোমল ও ক্ষণস্থায়ী সৌন্দর্য।"],
  [9,"with open hands","Image","Receiving life with gratitude and willingness, rather than trying to possess everything.","কৃতজ্ঞ ও গ্রহণে প্রস্তুত মন নিয়ে; সবকিছু আঁকড়ে ধরে রাখার চেষ্টা ছাড়া।"],
  [10,"under the sun","Phrase","Life in this world, viewed within its ordinary limits.","এই পৃথিবীর জীবন, তার স্বাভাবিক সীমাবদ্ধতার মধ্যে।"],
  [10,"chasing after the wind","Metaphor","Trying to possess something that cannot be caught or held.","যা ধরা বা ধরে রাখা যায় না, তার পেছনে ছোটা।"],
  [10,"all at once","Phrase","Completely and immediately, in a single moment.","একসঙ্গে, এক মুহূর্তে সম্পূর্ণভাবে।"],
  [10,"loosen its grip","Metaphor","Begin to have less control over someone.","কারও ওপর প্রভাব বা নিয়ন্ত্রণ ধীরে ধীরে কমানো।"],
  [10,"a humbler wisdom","Phrase","An understanding of life that is less proud and more aware of its limits.","অহংকার কমিয়ে জীবনের সীমাবদ্ধতা বোঝার প্রজ্ঞা।"],
  [10,"reaching for applause","Metaphor","Seeking other people's praise and approval.","অন্যের প্রশংসা ও স্বীকৃতি পেতে চেষ্টা করা।"],
  [10,"reverence","Word","Deep respect, especially toward God.","গভীর শ্রদ্ধা; বিশেষ করে ঈশ্বরের প্রতি।"],
  [10,"walk humbly","Metaphor","Live with humility rather than pride.","অহংকার ছাড়া বিনয়ের সঙ্গে জীবনযাপন করা।"],
  [10,"fear God","Phrase","Here, live with reverence and responsibility before God.","এখানে ঈশ্বরের প্রতি শ্রদ্ধা ও দায়বদ্ধতা নিয়ে জীবনযাপন করা।"],
  [10,"as an offering","Comparison","Like a gift freely given in devotion or gratitude.","ভক্তি বা কৃতজ্ঞতার সঙ্গে নিবেদিত উপহারের মতো।"],
  [10,"granted it","Verb phrase","Gave it or made it possible.","তা দান করেছেন বা সম্ভব করেছেন।"]
];
if (typeof module !== "undefined") module.exports = { ECCLESIASTES_GLOSSARY };
