// Six item labels in visual order: top-left, top-right, middle-left,
// middle-right, bottom-left, bottom-right. This keeps Guess the Items
// reveals aligned with the original card artwork.
window.PICTURE_THIS_GAME_DATA = {
  "weather": ["Stormy", "Sunny", "Snowy", "Windy", "Rainy", "Cloudy"],
  "vegetables": ["Broccoli", "Carrot", "Tomato", "Pepper", "Onion", "Peas"],
  "zoo": ["Giraffe", "Elephant", "Monkey", "Lion", "Bear", "Kangaroo"],
  "feelings": ["Happy", "Surprised", "Sad", "Confused", "Angry", "Tired"],
  "beverages": ["Coffee", "Water", "Tea", "Milk", "Soda", "Juice"],
  "play": ["Basketball", "Soccer Ball", "Volleyball", "Tennis Ball", "Baseball", "Football"],
  "school": ["Blackboard", "Pencil", "Notebook", "Backpack", "Book", "Desk"],
  "personal-items": ["Watch", "Mobile Phone", "Wallet", "Glasses", "Comb", "Purse"],
  "snack-time": ["Chocolate", "Grapes", "Apple", "Banana", "Donuts", "Crackers"],
  "hobbies": ["Reading Books", "Listening to Music", "Playing Sports", "Riding a Bike", "Surfing the Internet", "Watching Movies"],
  "shapes": ["Square", "Triangle", "Circle", "Star", "Diamond", "Octagon"],
  "bugs": ["Ant", "Spider", "Cockroach", "Grasshopper", "Worm", "Mosquito"],
  "tools": ["Pliers", "Hammer", "Saw", "Tape Measure", "Screwdriver", "Wrench"],
  "outdoor-places": ["Mountain", "Volcano", "Island", "Waterfall", "Forest", "Lake"],
  "furniture": ["Chair", "Bookshelf", "Bed", "Table", "Sofa", "Lamp"],
  "communication-tools": ["Mail", "Telephone", "Radio", "Email", "Television", "Newspaper"],
  "transportation": ["Bicycle", "Train", "Car", "Airplane", "Bus", "Motorcycle"],
  "great-outdoors": ["Horseback Riding", "Skateboarding", "Hiking", "Surfing", "Fishing", "Rock Climbing"],
  "jobs": ["Teacher", "Chef", "Doctor", "Business Person", "Police Officer", "Construction Worker"],
  "everyday-foods": ["Beans", "Corn", "Wheat", "Peanuts", "Potatoes", "Rice"],
  "musical-instruments": ["Guitar", "Drum", "Trumpet", "Violin", "Piano", "Saxophone"],
  "market": ["Fruit", "Eggs", "Chicken", "Vegetables", "Fish", "Bread"],
  "outdoor-gear": ["Scarf", "Hat", "Gloves", "Rain Boots", "Umbrella", "Sunglasses"],
  "pets": ["Cat", "Fish", "Dog", "Parrot", "Turtle", "Rabbit"],
  "at-the-beach": ["Beach Ball", "Sun Hat", "Beach Towel", "Sunscreen", "Sandcastle", "Flip-Flops"],
  "in-the-kitchen": ["Frying Pan", "Wooden Spoon", "Mixing Bowl", "Kettle", "Cutting Board", "Oven Mitt"],
  "getting-dressed": ["T-Shirt", "Jeans", "Sneakers", "Jacket", "Scarf", "Backpack"],
  "at-the-doctor": ["Stethoscope", "Thermometer", "Bandage", "Face Mask", "Crutch", "First-Aid Kit"],
  "cleaning-day": ["Broom", "Mop", "Bucket", "Sponge", "Spray Bottle", "Vacuum"],
  "in-the-garden": ["Watering Can", "Hand Trowel", "Garden Gloves", "Flowerpot", "Pruning Shears", "Garden Hose"],
  "at-the-playground": ["Slide", "Swing", "Seesaw", "Jump Rope", "Soccer Ball", "Frisbee"],
  "on-the-farm": ["Tractor", "Barn", "Hay Bale", "Pitchfork", "Wheelbarrow", "Milk Can"],
  "baby-things": ["Stroller", "Baby Bottle", "Pacifier", "Diaper", "Rattle", "High Chair"],
  "party-time": ["Balloons", "Birthday Cake", "Party Hat", "Gift Box", "Candle", "Party Horn"],
  "science-lab": ["Microscope", "Test Tube Rack", "Beaker", "Horseshoe Magnet", "Safety Goggles", "Lab Coat"],
  "sewing-kit": ["Sewing Machine", "Thread Spool", "Thimble", "Pin Cushion", "Zipper", "Button"],
  "winter-fun": ["Sled", "Ice Skates", "Snowboard", "Snow Shovel", "Ear Muffs", "Snow Tube"],
  "laundry-day": ["Washing Machine", "Laundry Basket", "Clothes Hanger", "Clothes Iron", "Clothespin", "Detergent Bottle"],
  "movie-night": ["Popcorn Tub", "Movie Ticket", "Projector", "Remote Control", "Cinema Seat", "Film Reel"],
  "space-travel": ["Rocket", "Astronaut Helmet", "Telescope", "Satellite", "Moon Rover", "Planet Earth"],
  "hair-salon": ["Hair Dryer", "Shampoo Bottle", "Salon Chair", "Hair Clippers", "Hair Rollers", "Curling Iron"],
  "at-the-airport": ["Suitcase", "Passport", "Boarding Pass", "Luggage Cart", "Control Tower", "Metal Detector"],
  "at-the-office": ["Stapler", "Calculator", "File Folder", "Hole Punch", "Binder Clip", "Tape Dispenser"],
  "under-the-sea": ["Dolphin", "Shark", "Octopus", "Seahorse", "Jellyfish", "Starfish"],
  "at-the-library": ["Library Card", "Book Cart", "Bookmark", "Card Catalog", "Magazine Rack", "Book Return Bin"],
  "at-the-harbor": ["Lighthouse", "Anchor", "Life Buoy", "Sailboat", "Fishing Net", "Dock Bollard"],
  "photography": ["DSLR Camera", "Tripod", "Camera Lens", "Flash Unit", "Memory Card", "Photo Album"],
  "fitness-equipment": ["Dumbbell", "Kettlebell", "Treadmill", "Yoga Mat", "Exercise Bike", "Resistance Band"],
  "at-the-museum": ["Dinosaur Fossil", "Ancient Vase", "Marble Statue", "Display Case", "Audio Guide", "Egyptian Mask"],
  "city-street": ["Traffic Light", "Fire Hydrant", "Parking Meter", "Streetlamp", "Crosswalk Sign", "Manhole Cover"],
  "at-a-wedding": ["Wedding Rings", "Bridal Bouquet", "Bridal Veil", "Tuxedo", "Ring Pillow", "Flower Arch"],
  "bathroom-fixtures": ["Bathtub", "Washbasin", "Toilet", "Showerhead", "Faucet", "Bathroom Mirror"],
  "money-and-banking": ["Banknote", "Coin Stack", "Credit Card", "Piggy Bank", "Safe", "ATM"],
  "houseplants": ["Cactus", "Orchid", "Bonsai Tree", "Fern", "Snake Plant", "Aloe Vera"],
  "at-the-dentist": ["Dental Chair", "Toothbrush", "Toothpaste Tube", "Floss Container", "Mouth Mirror", "Tooth Model"],
  "fire-station": ["Fire Engine", "Fire Helmet", "Coiled Fire Hose", "Fire Extinguisher", "Fire Axe", "Alarm Bell"],
  "at-the-hotel": ["Key Card", "Hotel Bell", "Bathrobe", "Slippers", "Luggage Rack", "Door Hanger"],
  "at-the-post-office": ["Mailbox", "Envelope", "Postage Stamp", "Parcel", "Mailbag", "Postal Scale"],
  "construction-site": ["Excavator", "Cement Mixer", "Construction Helmet", "Traffic Cone", "Brick Stack", "Safety Vest"],
  "at-the-theater": ["Stage Curtain", "Spotlight", "Theater Masks", "Prop Crown", "Megaphone", "Stage Microphone"],
  "at-the-restaurant": ["Menu Folder", "Serving Tray", "Napkin Ring", "Pepper Grinder", "Sauce Boat", "Soup Tureen"],
  "at-the-train-station": ["Train Ticket", "Platform Clock", "Ticket Machine", "Track Switch Lever", "Station Bench", "Conductor Whistle"],
  "at-the-bakery": ["Baguette", "Rolling Pin", "Baking Tray", "Flour Sack", "Bread Basket", "Oven Peel"],
  "at-the-police-station": ["Police Badge", "Handcuffs", "Police Radio", "Police Cap", "Traffic Baton", "Police Car"],
  "at-the-campsite": ["Dome Tent", "Sleeping Bag", "Camping Lantern", "Compass", "Camp Stove", "Canteen"],
  "board-games": ["Chess Knight", "Game Die", "Domino Tile", "Jigsaw Piece", "Playing Cards", "Sand Timer"],
  "jewelry": ["Pearl Necklace", "Charm Bracelet", "Hoop Earrings", "Brooch", "Cufflinks", "Hairpin"],
  "computer-equipment": ["Laptop", "Computer Mouse", "Keyboard", "USB Drive", "Wi-Fi Router", "Webcam"],
  "emergency-room": ["Ambulance", "Wheelchair", "IV Stand", "Blood Pressure Cuff", "Neck Brace", "Hospital Bed"],
  "car-parts": ["Steering Wheel", "Car Tire", "Spark Plug", "Gearshift", "Car Battery", "Side Mirror"],
  "ancient-egypt": ["Pyramid", "Sphinx Statue", "Papyrus Scroll", "Canopic Jar", "Scarab Amulet", "Ankh"],
  "flowers": ["Rose", "Sunflower", "Tulip", "Lotus Flower", "Daisy", "Lily"],
  "birds": ["Eagle", "Owl", "Penguin", "Flamingo", "Toucan", "Peacock"],
  "kitchen-appliances": ["Blender", "Toaster", "Microwave Oven", "Rice Cooker", "Refrigerator", "Dishwasher"],
  "art-supplies": ["Paint Palette", "Paintbrush", "Easel", "Oil Pastels", "Modeling Clay", "Ink Bottle"],
  "sports-equipment": ["Tennis Racket", "Cricket Bat", "Baseball Glove", "Hockey Stick", "Shuttlecock", "Table Tennis Paddle"],
  "at-the-pharmacy": ["Pill Bottle", "Medicine Box", "Eye Drops", "Nasal Spray", "Measuring Spoon", "Hot-Water Bottle"],
  "picnic-time": ["Picnic Basket", "Checkered Blanket", "Thermos Flask", "Sandwich", "Cooler Box", "Paper Cup"],
  "spices": ["Cinnamon Sticks", "Turmeric Root", "Cloves", "Cardamom Pods", "Peppercorns", "Bay Leaves"],
  "travel-accessories": ["Neck Pillow", "Luggage Tag", "Eye Mask", "Travel Adapter", "Toiletry Bag", "Luggage Scale"],
  "weather-instruments": ["Weather Vane", "Anemometer", "Barometer", "Weather Balloon", "Wind Sock", "Stevenson Screen"],
  "ways-to-travel": ["Tram", "Ferry", "Rickshaw", "Scooter", "Cable Car", "Pickup Truck"],
  "at-the-aquarium": ["Angelfish", "Hermit Crab", "Sea Anemone", "Clam Shell", "Coral Branch", "Aquarium Castle"],
  "at-the-coffee-shop": ["Espresso Machine", "Coffee Grinder", "Milk Frother", "Coffee Filter", "Sugar Bowl", "Takeaway Cup"],
  "at-the-supermarket": ["Shopping Cart", "Hand Basket", "Checkout Counter", "Barcode Scanner", "Receipt", "Reusable Bag"],
  "tableware": ["Dinner Plate", "Soup Bowl", "Fork", "Table Knife", "Teaspoon", "Chopsticks"],
  "cooking-utensils": ["Spatula", "Ladle", "Whisk", "Kitchen Tongs", "Colander", "Vegetable Peeler"],
  "fresh-fruit": ["Orange", "Mango", "Strawberry", "Watermelon", "Pineapple", "Lemon"],
  "fresh-vegetables": ["Cucumber", "Cabbage", "Eggplant", "Cauliflower", "Spinach", "Pumpkin"],
  "pantry-basics": ["Pasta", "Lentils", "Cooking Oil", "Salt Shaker", "Sugar Bag", "Oat Flakes"],
  "breakfast-foods": ["Toast", "Pancakes", "Cereal Box", "Yogurt Cup", "Jam Jar", "Granola Bar"],
  "home-entryway": ["Door Key", "Deadbolt", "Doorbell", "Doormat", "Coat Hook", "Shoe Rack"],
  "electrical-essentials": ["Light Switch", "Wall Outlet", "Power Plug", "Power Strip", "Light Bulb", "Extension Cord"],
  "personal-care": ["Bar Soap", "Deodorant", "Tissue Box", "Nail Clippers", "Hairbrush", "Razor"],
  "dishwashing": ["Dish Soap", "Dish Rack", "Scrub Brush", "Rubber Gloves", "Dish Towel", "Sink Strainer"],
  "food-storage": ["Food Container", "Bread Box", "Ice Tray", "Lunch Box", "Wax Paper Roll", "Aluminum Foil"],
  "writing-supplies": ["Ballpoint Pen", "Eraser", "Ruler", "Scissors", "Glue Stick", "Paper Clip"],
  "bathroom-essentials": ["Toilet Paper", "Hand Towel", "Soap Dish", "Bath Mat", "Plunger", "Toilet Brush"],
  "cleaning-extras": ["Dustpan", "Trash Can", "Garbage Bag", "Recycling Bin", "Squeegee", "Cleaning Cloth"],
  "parts-of-a-home": ["Front Door", "Window", "Staircase", "Ceiling Fan", "Curtain", "Door Handle"],
  "coffee-shop-drinks": ["Macchiato", "Americano", "Latte", "Cappuccino", "Mocha", "Espresso"]
};
