// Curated two-item links. Item indexes follow visual order:
// top-left, top-right, middle-left, middle-right, bottom-left, bottom-right.
// `word` is the displayed model; `answers` contains acceptable one-word variants.
window.PICTURE_THIS_LINK_DATA = {
  "shapes": [{"word":"four-sided","answers":["four-sided","quadrilateral"],"items":[0,4],"explanation":"A square and a diamond both have four sides."}],
  "furniture": [{"word":"seating","answers":["seating","sitting"],"items":[0,4],"explanation":"A chair and a sofa are both used for sitting."}],
  "communication-tools": [{"word":"broadcast","answers":["broadcast","broadcasting"],"items":[2,4],"explanation":"Radio and television both broadcast information and entertainment."}],
  "transportation": [{"word":"handlebars","answers":["handlebars"],"items":[0,5],"explanation":"A bicycle and a motorcycle are both steered with handlebars."}],
  "great-outdoors": [{"word":"boards","answers":["boards","board"],"items":[1,3],"explanation":"Skateboarding and surfing both use a board."}],
  "everyday-foods": [{"word":"legumes","answers":["legumes","legume"],"items":[0,3],"explanation":"Beans and peanuts are both legumes."}],
  "musical-instruments": [{"word":"strings","answers":["strings","stringed"],"items":[0,3],"explanation":"A guitar and a violin both make music with strings."}],
  "outdoor-gear": [{"word":"rain","answers":["rain","rainy"],"items":[3,4],"explanation":"Rain boots and an umbrella both help in rainy weather."}],
  "at-the-beach": [{"word":"sun","answers":["sun","sunny"],"items":[1,3],"explanation":"A sun hat and sunscreen both protect you from the sun."}],
  "getting-dressed": [{"word":"warmth","answers":["warmth","warm"],"items":[3,4],"explanation":"A jacket and a scarf both help keep you warm."}],
  "at-the-doctor": [{"word":"support","answers":["support","supportive"],"items":[2,4],"explanation":"A bandage and a crutch can both support an injury."}],
  "cleaning-day": [{"word":"floors","answers":["floors","floor"],"items":[1,5],"explanation":"A mop and a vacuum are both used to clean floors."}],
  "in-the-garden": [{"word":"watering","answers":["watering","water"],"items":[0,5],"explanation":"A watering can and a garden hose both water plants."}],
  "baby-things": [{"word":"feeding","answers":["feeding","feed"],"items":[1,5],"explanation":"A baby bottle and a high chair are both used at feeding time."}],
  "party-time": [{"word":"birthday","answers":["birthday"],"items":[1,4],"explanation":"A birthday cake and a candle are both part of a birthday celebration."}],
  "science-lab": [{"word":"protective","answers":["protective","protection","safety"],"items":[4,5],"explanation":"Safety goggles and a lab coat are protective lab clothing."}],
  "sewing-kit": [{"word":"fastening","answers":["fastening","fasteners","fastener"],"items":[4,5],"explanation":"A zipper and a button are both fasteners."}],
  "laundry-day": [{"word":"hanging","answers":["hanging","hang"],"items":[2,4],"explanation":"A clothes hanger and a clothespin both help hang clothes."}],
  "movie-night": [{"word":"projection","answers":["projection","projecting","project"],"items":[2,5],"explanation":"A projector and a film reel work together to project a movie."}],
  "space-travel": [{"word":"orbit","answers":["orbit","orbiting"],"items":[3,5],"explanation":"A satellite can orbit planet Earth."}],
  "hair-salon": [{"word":"heat","answers":["heat","heating","hot"],"items":[0,5],"explanation":"A hair dryer and a curling iron both use heat."}],
  "at-the-office": [{"word":"piercing","answers":["piercing","pierce","puncturing"],"items":[0,3],"explanation":"A stapler and a hole punch both pierce paper."}],
  "under-the-sea": [{"word":"tentacles","answers":["tentacles","tentacle"],"items":[2,4],"explanation":"An octopus and a jellyfish both have tentacles."}],
  "at-the-harbor": [{"word":"floating","answers":["floating","float"],"items":[2,3],"explanation":"A life buoy and a sailboat both float on water."}],
  "photography": [{"word":"storage","answers":["storage","storing","store"],"items":[4,5],"explanation":"A memory card and a photo album both store photographs."}],
  "fitness-equipment": [{"word":"cardio","answers":["cardio","aerobic"],"items":[2,4],"explanation":"A treadmill and an exercise bike are both used for cardio exercise."}],
  "city-street": [{"word":"crossing","answers":["crossing","cross"],"items":[0,4],"explanation":"A traffic light and a crosswalk sign both help people cross a street."}],
  "at-a-wedding": [{"word":"bride","answers":["bride","bridal"],"items":[1,2],"explanation":"A bridal bouquet and a bridal veil are both worn or carried by a bride."}],
  "money-and-banking": [{"word":"saving","answers":["saving","savings","save"],"items":[3,4],"explanation":"A piggy bank and a safe can both hold savings."}],
  "houseplants": [{"word":"succulents","answers":["succulents","succulent"],"items":[0,5],"explanation":"A cactus and aloe vera are both succulent plants."}],
  "at-the-hotel": [{"word":"wearing","answers":["wearing","wear","clothing"],"items":[2,3],"explanation":"A bathrobe and slippers are both things a hotel guest can wear."}],
  "at-the-post-office": [{"word":"weighing","answers":["weighing","weigh","weight"],"items":[3,5],"explanation":"A parcel can be weighed on a postal scale."}],
  "at-the-theater": [{"word":"amplification","answers":["amplification","amplify","loud"],"items":[4,5],"explanation":"A megaphone and a microphone both make a voice easier to hear."}],
  "at-the-train-station": [{"word":"tickets","answers":["tickets","ticket"],"items":[0,2],"explanation":"A train ticket can be bought from a ticket machine."}],
  "computer-equipment": [{"word":"input","answers":["input","controls","control"],"items":[1,2],"explanation":"A computer mouse and a keyboard are both input devices."}],
  "emergency-room": [{"word":"mobility","answers":["mobility","transport","moving"],"items":[0,1],"explanation":"An ambulance and a wheelchair both help move patients."}],
  "car-parts": [{"word":"control","answers":["control","controlling"],"items":[0,3],"explanation":"A steering wheel and a gearshift both help control a car."}],
  "kitchen-appliances": [{"word":"heating","answers":["heating","heat","hot"],"items":[1,2],"explanation":"A toaster and a microwave oven both heat food."}],
  "art-supplies": [{"word":"painting","answers":["painting","paint"],"items":[0,1],"explanation":"A paint palette and a paintbrush are both used for painting."}],
  "picnic-time": [{"word":"insulated","answers":["insulated","insulation","temperature"],"items":[2,4],"explanation":"A thermos flask and a cooler box both use insulation to control temperature."}],
  "travel-accessories": [{"word":"sleep","answers":["sleep","sleeping","rest"],"items":[0,2],"explanation":"A neck pillow and an eye mask can both help a traveler sleep."}],
  "at-the-aquarium": [{"word":"shells","answers":["shells","shell"],"items":[1,3],"explanation":"A hermit crab and a clam both have shells."}],
  "fresh-fruit": [{"word":"citrus","answers":["citrus"],"items":[0,5],"explanation":"An orange and a lemon are both citrus fruits."}],
  "fresh-vegetables": [{"word":"leafy","answers":["leafy","leaves"],"items":[1,4],"explanation":"Cabbage and spinach are both leafy vegetables."}],
  "breakfast-foods": [{"word":"spreading","answers":["spreading","spread"],"items":[0,4],"explanation":"Jam can be spread on toast."}],
  "home-entryway": [{"word":"security","answers":["security","locking","lock"],"items":[0,1],"explanation":"A door key and a deadbolt both secure an entrance."}],
  "dishwashing": [{"word":"scrubbing","answers":["scrubbing","scrub","cleaning"],"items":[0,2],"explanation":"Dish soap and a scrub brush are both used while scrubbing dishes."}],
  "food-storage": [{"word":"wrapping","answers":["wrapping","wrap","covering"],"items":[4,5],"explanation":"Wax paper and aluminum foil can both wrap food."}],
  "writing-supplies": [{"word":"fastening","answers":["fastening","fasten","attaching"],"items":[4,5],"explanation":"A glue stick and a paper clip can both fasten pieces of paper."}],
  "parts-of-a-home": [{"word":"openings","answers":["openings","opening","open"],"items":[0,1],"explanation":"A front door and a window are both openings in a home."}]
};
