// Discussion-question text and number positions for card-back TTS controls.
// Generated by scripts/build-question-data.py; do not hand-edit.
window.PICTURE_THIS_QUESTION_DATA = {
  "weather": {
    "questions": [
      "What is your favorite type of weather? Why?",
      "How do you get ready for school on a rainy day?",
      "What can you do outside on a snowy day?",
      "Choose one type of weather. What are three fun things to do on that kind of day?",
      "Choose another type of weather. What clothes do you wear outside in that weather?",
      "What climate would you like to live in? Why?"
    ],
    "positions": [
      13.14,
      23.18,
      33.29,
      43.41,
      57.84,
      72.2
    ]
  },
  "vegetables": {
    "questions": [
      "What are three vegetables on the card?",
      "What are two more vegetables not on the card? What do they look like?",
      "Which vegetables are common in this area? Which vegetables are uncommon in this area? Why?",
      "Which vegetables do you like? What other foods do you eat with these vegetables?",
      "What vegetables do you eat at breakfast? At lunch? At dinner?",
      "What vegetables would you grow in your own garden? Why?"
    ],
    "positions": [
      13.14,
      23.18,
      33.29,
      47.73,
      62.16,
      72.2
    ]
  },
  "zoo": {
    "questions": [
      "Which animal on the card is your favorite? Why?",
      "Tell me more about one animal. Where does it live? What does it eat?",
      "Which animals have you seen in real life? When and where did you see them?",
      "What are three other animals you might see in the zoo? What do they look like?",
      "Which animal would you like to speak to? What would you say to the animal?",
      "Imagine you are one of these animals. Which animal would you be? Why?"
    ],
    "positions": [
      13.14,
      23.18,
      33.29,
      47.73,
      62.16,
      76.51
    ]
  },
  "feelings": {
    "questions": [
      "What are three feelings on this card?",
      "When do you feel happy? Why?",
      "When have you felt surprised? What happened? What did you do?",
      "When do you feel tired? Why?",
      "What are three feelings not on this card? When do you have these feelings?",
      "What do you do when you feel confused?"
    ],
    "positions": [
      13.14,
      23.18,
      28.98,
      39.1,
      44.9,
      59.25
    ]
  },
  "beverages": {
    "questions": [
      "Which drink on the card is the healthiest? Why?",
      "Where do the drinks on the card come from? Where do you get these drinks?",
      "What do you drink at breakfast? What do you drink at lunch? Why?",
      "What is your favorite drink? What is your second favorite?",
      "Why do you drink hot drinks out of a mug? Why do you drink cold drinks out of a glass?",
      "Imagine you are in a hot desert. Which drink would you want to have? Why?"
    ],
    "positions": [
      13.14,
      23.18,
      37.61,
      47.73,
      57.84,
      72.2
    ]
  },
  "play": {
    "questions": [
      "Which games on the card do you play as a team? Which do you play as an individual?",
      "Which game is the easiest to play? Which one is the most difficult to play? Why?",
      "Choose one game. What do you need to play it? Why do you need it?",
      "Which games do you like to watch? Why?",
      "Which games do you like to play? Why?",
      "Which games have you never played before? Which games would you like to play? Why?"
    ],
    "positions": [
      13.14,
      27.49,
      41.92,
      52.04,
      62.16,
      72.2
    ]
  },
  "school": {
    "questions": [
      "Which items on the card do you put in a backpack?",
      "Which items do you need to do your homework? What else do you need to do your homework?",
      "Which items on the card are the most expensive? The least expensive? Why?",
      "What do students usually do at a desk? Who else uses a desk?",
      "What does the teacher use in the classroom? What do the students use in the classroom?",
      "What new item would you like in your classroom? Why?"
    ],
    "positions": [
      13.14,
      23.18,
      37.61,
      52.04,
      62.16,
      76.51
    ]
  },
  "personal-items": {
    "questions": [
      "Which item on the card is the most useful? Why?",
      "Which items on the card do you wear? Which ones do you carry? Where do you carry them?",
      "What are some other personal items that you carry and wear?",
      "Which item do you use the most? Why?",
      "What do people put in a purse? Why?",
      "What personal item would you like to buy? Why?"
    ],
    "positions": [
      13.14,
      23.18,
      37.61,
      47.73,
      57.84,
      67.88
    ]
  },
  "snack-time": {
    "questions": [
      "Which of the snacks on the card is the healthiest? Which is the least healthy?",
      "Which snacks are salty? Which are sweet? Which are crunchy? Which are soft?",
      "Which of the snacks do you like to eat? Why?",
      "What other snacks do you like to eat? What do they look like?",
      "Which snacks are easy to carry with you? Why?",
      "Imagine you are having a party. What snacks would you serve?"
    ],
    "positions": [
      13.14,
      27.49,
      41.92,
      52.04,
      62.16,
      72.2
    ]
  },
  "hobbies": {
    "questions": [
      "Which hobbies on the card are good for a rainy day? Which are good for a sunny day?",
      "Which two hobbies are the most similar? Why?",
      "What is your favorite hobby? Why?",
      "What do you usually read? Tell me about it.",
      "What sports do you play? What sports do you watch? Why?",
      "Imagine you have a day off from school. What activities would you do for fun? Why do you enjoy them?"
    ],
    "positions": [
      13.14,
      27.49,
      37.61,
      43.41,
      53.53,
      63.57
    ]
  },
  "shapes": {
    "questions": [
      "Which shapes on the card have sides? How many sides does each one have?",
      "What things in this room look like the shapes on the card?",
      "What three things outside of the classroom have these shapes?",
      "What shapes are used for traffic signs? What do the signs mean?",
      "What is the same about an octagon and an octopus?",
      "In which school subjects do you study shapes? Do you like to study shapes?"
    ],
    "positions": [
      13.14,
      27.49,
      37.61,
      47.73,
      57.84,
      67.88
    ]
  },
  "bugs": {
    "questions": [
      "Which bugs on the card are familiar to you?",
      "Where do people usually find bugs?",
      "Have you ever seen one of the bugs on the card? What happened?",
      "How do people protect themselves from bugs?",
      "Which of the bugs are you most afraid of? Why?",
      "If you saw a bug in your food, what would you do?"
    ],
    "positions": [
      13.14,
      23.18,
      28.98,
      39.1,
      49.22,
      59.25
    ]
  },
  "tools": {
    "questions": [
      "Which of the tools on the card is the most useful? Why?",
      "Choose two of the tools. What do you do with them?",
      "Which tool is the most dangerous to use? Why?",
      "Which tool is the easiest to use? The hardest? Why?",
      "What other tools are useful around a house?",
      "Imagine you could buy one of these tools. Which tool would you buy? Why?"
    ],
    "positions": [
      13.14,
      23.18,
      33.29,
      43.41,
      53.53,
      63.57
    ]
  },
  "outdoor-places": {
    "questions": [
      "Which of the places on the card is the most familiar to you? Which is the least familiar?",
      "Which places are good for a vacation? Why?",
      "Which place would you like to visit? Why?",
      "Which of the places are safe to live near? Why? Which are dangerous to live near? Why?",
      "Choose one of the places. What kinds of activities can you do there?",
      "Choose one of the places. What might it be like to live near this place?"
    ],
    "positions": [
      13.14,
      27.49,
      37.61,
      47.73,
      62.16,
      72.2
    ]
  },
  "furniture": {
    "questions": [
      "Which piece of furniture on the card do you use the most? Why?",
      "Which piece of furniture is the heaviest? How do people move it?",
      "Which piece of furniture have you slept on? Was it comfortable?",
      "What pieces of furniture do you have in the room where you sleep?",
      "What other pieces of furniture can be in a house?",
      "Where would you put each piece of furniture in a house?"
    ],
    "positions": [
      13.14,
      23.18,
      33.29,
      43.41,
      53.53,
      63.57
    ]
  },
  "communication-tools": {
    "questions": [
      "Which of the communication tools on the card do you use most often? Why?",
      "Which communication tools are good for communicating with many people at once?",
      "Which communication tools are the oldest? The newest?",
      "Which communication tool is the most expensive? Why?",
      "What communication tools do people have problems with? What kinds of problems do they have?",
      "If you could use only one way to communicate with others, which tool would you use? Why?"
    ],
    "positions": [
      13.14,
      27.49,
      41.92,
      52.04,
      62.16,
      76.51
    ]
  },
  "transportation": {
    "questions": [
      "What type of transportation on the card do you use most often? Where do you go?",
      "Which two types of transportation on the card are the slowest?",
      "Which types of transportation on the card are the most modern?",
      "Which types of transportation are the most fun? Why?",
      "What types of transportation do you take on a long trip? Ona short trip? Why?",
      "Imagine you are going on vacation. Where would you go? How would you get there?"
    ],
    "positions": [
      13.14,
      27.49,
      37.61,
      47.73,
      57.84,
      72.2
    ]
  },
  "great-outdoors": {
    "questions": [
      "Which of the outdoor activities on the card is the most fun? Why?",
      "Why do people do the activities on the card?",
      "Where can people do the activities on the card?",
      "Which of the activities is the most popular? Why?",
      "Why do you think these activities are popular?",
      "What equipment would you need to do the activities on the card?"
    ],
    "positions": [
      13.14,
      23.18,
      33.29,
      43.41,
      53.53,
      63.57
    ]
  },
  "jobs": {
    "questions": [
      "Which jobs on the card are interesting to you? Why?",
      "Where does each person on the card work?",
      "Which job requires the most education? Why?",
      "Which of the jobs on the card makes the most money? Why?",
      "Choose two of the jobs on the card. What do these people wear to work?",
      "What other jobs do you know? What job would you like to have in the future?"
    ],
    "positions": [
      13.14,
      23.18,
      33.29,
      43.41,
      53.53,
      63.57
    ]
  },
  "everyday-foods": {
    "questions": [
      "Which of the foods on the card do you eat often? Do you buy it every day?",
      "Which ones do you like to eat? Why?",
      "How are the foods on the card grown? How are they used?",
      "How do the foods on the card get from the farm to the market?",
      "In which parts of the world are the foods on the card common?",
      "Imagine you could only eat one of these foods. Which food would you choose? Why?"
    ],
    "positions": [
      13.14,
      27.49,
      33.29,
      43.41,
      53.53,
      63.57
    ]
  },
  "musical-instruments": {
    "questions": [
      "What musical instruments are the most popular? Why?",
      "Do you play any musical instruments? Why or why not?",
      "Which instrument on the card can play the loudest? Why?",
      "What instruments are used in your favorite type of music?",
      "Is it easy or hard to learn to play an instrument? Why?",
      "Imagine you are in a band. Which instrument would you play? Why?"
    ],
    "positions": [
      13.14,
      23.18,
      33.29,
      43.41,
      53.53,
      63.57
    ]
  },
  "market": {
    "questions": [
      "Which foods on the card are the most expensive? The least expensive? Why?",
      "What other foods do you buy at the market?",
      "Which foods do you eat most often?",
      "When is the best time of the year to get fruit? Vegetables? Why?",
      "How do you bring food home from the market?",
      "Imagine you own a store. What foods would you sell in the store? Why?"
    ],
    "positions": [
      13.14,
      27.49,
      37.61,
      43.41,
      53.53,
      63.57
    ]
  },
  "outdoor-gear": {
    "questions": [
      "Which items on the card do you wear when it is sunny? Why?",
      "Which items on the card do you wear when it is cold? Why?",
      "Which items on the card do you use when it is rainy? Why?",
      "What other things do you wear outside? Why?",
      "During what parts of the year do you need special items to wear outside? Why?",
      "Imagine you are going on vacation to the beach. What items would you take? Why?"
    ],
    "positions": [
      13.14,
      23.18,
      33.29,
      43.41,
      53.53,
      67.88
    ]
  },
  "pets": {
    "questions": [
      "How big are the pets on the card? Which pet is the biggest? Which is the smallest?",
      "Choose two of the pets. What do these pets eat?",
      "Which pets on the card are fun to play with? Why?",
      "Choose one of the pets. How do you take care of it?",
      "Choose two of the pets. What do they feel like when you touch them?",
      "What pet would you like to have? Why?"
    ],
    "positions": [
      13.14,
      27.49,
      37.61,
      47.73,
      57.84,
      67.88
    ]
  },
  "at-the-beach": {
    "questions": [
      "Which items on the card would you take to the beach? Why?",
      "Which item is the most useful on a hot day? Why?",
      "Which of these items have you used before? Where did you use them?",
      "How do people use each item at the beach?",
      "What are three more things people might bring to the beach?",
      "Imagine you are planning a beach day. Which three items would you pack first? Why?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      47.76,
      58.16,
      68.47
    ]
  },
  "in-the-kitchen": {
    "questions": [
      "Which items are used for cooking, and which are used for preparing food?",
      "Which item could become the hottest? Why?",
      "Which of these kitchen items have you used before?",
      "How do you use a cutting board safely?",
      "What other useful things might you find in a kitchen?",
      "Imagine you are making a simple meal. Which three items would you use, and why?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "getting-dressed": {
    "questions": [
      "Which items are clothing, and which item is used to carry things?",
      "Which item would keep you warmest? Why?",
      "Which of these items do you wear or use most often?",
      "When would you choose to wear a jacket or scarf?",
      "What other clothes do people often wear in hot weather?",
      "Imagine you can pack only three items for a trip. Which would you choose, and why?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "at-the-doctor": {
    "questions": [
      "Which items might a doctor use to check a patient?",
      "Which item is the longest, and which is the smallest?",
      "Which of these items have you seen or used before?",
      "How can a bandage or crutch help someone?",
      "What other people or things might you see at a clinic?",
      "Imagine a friend feels unwell. What would you say or do to help?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "cleaning-day": {
    "questions": [
      "Which items use water, and which items do not?",
      "Which item would be best for cleaning a carpet? Why?",
      "Which of these cleaning tools have you used before?",
      "How do people use a bucket and mop together?",
      "What other things can help keep a room clean?",
      "Imagine you have ten minutes to clean a room. What would you do first?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "in-the-garden": {
    "questions": [
      "Which items can hold or carry water?",
      "Which tool would be easiest to carry? Why?",
      "Which of these garden items have you used or seen before?",
      "How do people use a trowel and a flowerpot together?",
      "What other things might you find in a garden?",
      "Imagine you are planting a small garden. What would you do first?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "at-the-playground": {
    "questions": [
      "Which items can one person use alone?",
      "Which activity looks the most active? Why?",
      "What did you enjoy doing at playgrounds when you were younger?",
      "How can two people use a seesaw safely?",
      "What other games can people play at a playground?",
      "Imagine you are designing a playground. What would you add?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      47.76,
      58.16,
      68.47
    ]
  },
  "on-the-farm": {
    "questions": [
      "Which items are tools, and which items are places or containers?",
      "Which item is the largest in real life?",
      "Have you ever visited a farm? What did you see there?",
      "How can a wheelbarrow help with farm work?",
      "What crops or animals are common on farms near you?",
      "Imagine you work on a farm for one day. Which job would you choose?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "baby-things": {
    "questions": [
      "Which items are used for feeding a baby?",
      "Which item would be the most difficult to carry? Why?",
      "Which of these baby things have you used or seen?",
      "How does a stroller help an adult and a baby?",
      "What other items can make caring for a baby easier?",
      "Imagine you are buying a gift for a new baby. What would you choose?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "party-time": {
    "questions": [
      "Which items are decorations, and which items are gifts or food?",
      "Which item would be easiest to make at home? Why?",
      "What kind of party do you enjoy?",
      "How do people use balloons and a cake at a celebration?",
      "What other things can make a party enjoyable?",
      "Imagine you are planning a small party. What would you prepare first?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "science-lab": {
    "questions": [
      "Which items protect a person in a science lab?",
      "Which item helps you see very small things?",
      "Have you used any of these items? What did you do?",
      "How could you use the magnet and the test tube rack in experiments?",
      "What other things might you find in a science lab?",
      "Imagine you are doing a simple experiment. What would you investigate?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      58.16,
      68.47
    ]
  },
  "sewing-kit": {
    "questions": [
      "Which items can you find on a piece of clothing?",
      "Which item is the smallest? What is it used for?",
      "Have you ever sewn or repaired clothing? What happened?",
      "How do thread and a sewing machine work together?",
      "What clothes are easy to repair, and which are difficult?",
      "Imagine a button falls off your shirt. How would you fix it?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "winter-fun": {
    "questions": [
      "Which items can help you move across snow or ice?",
      "Which item keeps you warm, and which item helps with work?",
      "What winter activities have you tried or watched?",
      "How are a sled and a snow tube similar and different?",
      "What should people do to stay safe in winter weather?",
      "Imagine you have a free snowy day. How would you spend it?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "laundry-day": {
    "questions": [
      "Which items help wash clothes, and which help dry them?",
      "Which item uses electricity? What does it do?",
      "How often do you wash your clothes, and where?",
      "What steps do you follow from dirty clothes to clean clothes?",
      "Why do some clothes need special care?",
      "Imagine the washing machine stops working. How could you finish the laundry?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "movie-night": {
    "questions": [
      "Which items might you use before a movie begins?",
      "Which item controls the picture, and which controls it from a distance?",
      "Where do you usually watch movies? Who watches with you?",
      "How is watching a movie at home different from watching at a cinema?",
      "What makes a movie interesting or memorable?",
      "Imagine you are planning a movie night. What would you prepare and why?"
    ],
    "positions": [
      12.43,
      22.75,
      37.41,
      47.76,
      62.47,
      72.78
    ]
  },
  "space-travel": {
    "questions": [
      "Which items can travel through space?",
      "Which item helps people look at distant objects?",
      "What have you learned about space or the Moon?",
      "How would a rocket and a moon rover be used on the same mission?",
      "What might be difficult about living in space?",
      "Imagine you could visit another world. Where would you go and what would you explore?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      58.16,
      68.47
    ]
  },
  "hair-salon": {
    "questions": [
      "Which items use electricity?",
      "Which item holds a person, and which items change their hair?",
      "When did you last visit a hair salon or barber?",
      "How might a hair dryer and hair rollers be used together?",
      "What makes a visit to a salon comfortable?",
      "Imagine you work in a busy salon. How would you help your next customer?"
    ],
    "positions": [
      12.43,
      18.43,
      28.78,
      39.14,
      49.53,
      59.84
    ]
  },
  "at-the-airport": {
    "questions": [
      "Which items does a traveler carry?",
      "Which items help airport workers keep people safe?",
      "What do you usually do before a flight?",
      "How do a boarding pass and a passport help a traveler?",
      "What can make an airport journey easy or stressful?",
      "Imagine your flight is delayed for five hours. What would you do?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "at-the-office": {
    "questions": [
      "Which items help organize papers?",
      "Which item can help with numbers? What can it calculate?",
      "Which of these items have you used at school or work?",
      "How could you use a stapler and a file folder together?",
      "What other objects are useful in an office?",
      "Imagine you are setting up a new office. Which supplies would you buy first?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "under-the-sea": {
    "questions": [
      "Which animals have fins, and which have arms or tentacles?",
      "Which animal looks the fastest? Why?",
      "Have you seen any of these animals in real life or in a film?",
      "How are a dolphin and a shark similar and different?",
      "What dangers do sea animals face from people?",
      "Imagine you could explore the ocean safely. What would you hope to discover?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "at-the-library": {
    "questions": [
      "Which items help people carry, find, or return reading materials?",
      "Which item is the largest? Which is the smallest?",
      "When did you last visit a library, and what did you do there?",
      "How do people use a library card and a book return bin?",
      "What other things can people find or use in a library?",
      "If you organized a small library, which item would you need first? Why?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "at-the-harbor": {
    "questions": [
      "Which items help boats travel, stop, or stay safe?",
      "How are an anchor and a dock bollard similar and different?",
      "Have you ever visited a harbor? What did you see there?",
      "How do sailors use a lighthouse, a life buoy, and a fishing net?",
      "What other people, animals, or objects might you see at a harbor?",
      "Imagine you could take the sailboat anywhere. Where would you go? Why?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      68.47
    ]
  },
  "photography": {
    "questions": [
      "Which items take, store, or display photographs?",
      "Which equipment is easiest to carry? Which is hardest?",
      "What kinds of photographs do you enjoy taking or looking at?",
      "When would a photographer use a tripod or a flash unit?",
      "What other equipment can people use to take better photographs?",
      "If you could photograph one special event or place, what would you choose? Why?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      68.47
    ]
  },
  "fitness-equipment": {
    "questions": [
      "Which items can help with strength, balance, or heart exercise?",
      "Which equipment needs the most space? Which needs the least?",
      "Which kinds of exercise have you tried or would you like to try?",
      "How can people use exercise equipment safely?",
      "What other activities can help people stay active without equipment?",
      "If you could choose two items for a home gym, which would you choose? Why?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      72.78
    ]
  },
  "at-the-museum": {
    "questions": [
      "Which objects are exhibits, and which objects help visitors?",
      "Which exhibit looks oldest? Which might be the most fragile?",
      "What museums have you visited, and what did you enjoy there?",
      "Why do museums use display cases and audio guides?",
      "What other things could people see in a history or science museum?",
      "If you created a museum exhibit, what would you display? Why?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      68.47
    ]
  },
  "city-street": {
    "questions": [
      "Which items help people travel safely along a city street?",
      "Which item is tallest? Which items are close to the ground?",
      "Which of these items do you often see where you live?",
      "How are a parking meter and a fire hydrant used?",
      "What other signs, services, or objects are common on city streets?",
      "If you could improve one city street, what would you add or change? Why?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      68.47
    ]
  },
  "at-a-wedding": {
    "questions": [
      "Which items are worn, carried, or used as decorations?",
      "Which items look soft? Which look hard or heavy?",
      "Have you attended a wedding or another important celebration? What happened?",
      "How might people use the rings, bouquet, veil, and flower arch?",
      "What other food, clothing, music, or decorations can celebrations include?",
      "If you planned a celebration, which colors and decorations would you choose? Why?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      47.76,
      58.16,
      72.78
    ]
  },
  "bathroom-fixtures": {
    "questions": [
      "Which fixtures use water, and which do not?",
      "Which fixture is largest? Which could fit in your hand?",
      "Which bathroom fixtures do you use during your daily routine?",
      "How do a faucet, washbasin, and showerhead work together with water?",
      "What other useful things do people often keep in a bathroom?",
      "If you designed a new bathroom, which fixture would be most important? Why?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      58.16,
      72.78
    ]
  },
  "money-and-banking": {
    "questions": [
      "Which items represent, store, or give access to money?",
      "Which items are easiest to carry? Which is most secure?",
      "Which ways of paying or saving money have you used?",
      "How do people use a credit card, an ATM, and a safe?",
      "What other ways can people pay for something or keep money safe?",
      "If you were saving for something important, what would it be? Why?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      68.47
    ]
  },
  "houseplants": {
    "questions": [
      "Which plants have flowers, spines, or long leaves?",
      "Which plant looks tallest? Which looks most compact?",
      "What plants do you grow at home, school, or work?",
      "What do houseplants need in order to stay healthy?",
      "What other plants can people grow indoors?",
      "If you could choose one houseplant for your room, which would you choose? Why?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "at-the-dentist": {
    "questions": [
      "Which items help clean teeth, and which help a dentist examine them?",
      "Which item is smallest? Which would take up the most space?",
      "What do you do to keep your teeth clean?",
      "How might a dentist use the dental chair and mouth mirror?",
      "What other things might you find in a dentist's office?",
      "If you designed a toothbrush, what color or shape would you choose? Why?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "fire-station": {
    "questions": [
      "Which items help firefighters travel, stay safe, or put out a fire?",
      "Which item looks heaviest? Which could one person carry easily?",
      "Have you ever visited a fire station or seen a fire engine nearby?",
      "How do firefighters use a hose, helmet, and fire extinguisher?",
      "What other equipment or vehicles might a fire station have?",
      "If you could ask a firefighter one question, what would you ask?"
    ],
    "positions": [
      12.43,
      27.06,
      41.73,
      56.39,
      66.78,
      81.41
    ]
  },
  "at-the-hotel": {
    "questions": [
      "Which items are used at reception, and which are used inside a hotel room?",
      "Which item looks softest? Which looks strongest?",
      "Have you ever stayed in a hotel or guesthouse? What was it like?",
      "How might a guest use a key card, luggage rack, and door hanger?",
      "What other services or objects can a hotel provide?",
      "If you managed a small hotel, what would you do to welcome guests?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      62.47,
      72.78
    ]
  },
  "at-the-post-office": {
    "questions": [
      "Which items hold mail, and which help prepare or send it?",
      "Which item could hold the largest package? Which is the smallest?",
      "When did you last send or receive a letter or parcel?",
      "How do people use a postage stamp and postal scale?",
      "What other jobs or services are connected with delivering mail?",
      "If you mailed a surprise to a friend, what would you send? Why?"
    ],
    "positions": [
      12.43,
      22.75,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "construction-site": {
    "questions": [
      "Which items are machines, safety equipment, or building materials?",
      "Which item is largest? Which items could a worker wear or carry?",
      "Have you seen a construction site recently? What was being built?",
      "Why do workers use traffic cones, helmets, and safety vests?",
      "What other machines or materials might be found at a construction site?",
      "If you could design a new building, what would it be? Why?"
    ],
    "positions": [
      12.47,
      22.63,
      37.06,
      47.25,
      57.49,
      71.88
    ]
  },
  "at-the-theater": {
    "questions": [
      "Which items help performers be seen, heard, or dressed for a play?",
      "Which item looks brightest? Which might make the loudest sound?",
      "Have you ever watched or performed in a play? What do you remember?",
      "How are a spotlight, curtain, and microphone used during a performance?",
      "What other people, costumes, or objects are needed in a theater?",
      "If you could perform on stage, what role would you choose? Why?"
    ],
    "positions": [
      12.47,
      22.63,
      37.06,
      51.49,
      65.96,
      76.12
    ]
  },
  "at-the-restaurant": {
    "questions": [
      "Which items help serve food, and which are placed on a dining table?",
      "Which item could hold the most? Which looks easiest to carry?",
      "What kind of restaurant do you enjoy visiting?",
      "How might restaurant staff use a menu folder and serving tray?",
      "What other objects or jobs can you find in a restaurant?",
      "If you opened a restaurant, what food would you serve? Why?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "at-the-train-station": {
    "questions": [
      "Which items help passengers, and which help control train movement?",
      "Which item is tallest? Which could fit easily in a pocket?",
      "When did you last travel by train, or when would you like to?",
      "How do passengers use a ticket machine, clock, and station bench?",
      "What other people, signs, or objects might you see at a train station?",
      "If you could take a train trip anywhere, where would you go? Why?"
    ],
    "positions": [
      12.47,
      26.86,
      37.06,
      47.25,
      61.73,
      76.12
    ]
  },
  "at-the-bakery": {
    "questions": [
      "Which items are foods, and which are tools used by a baker?",
      "Which item is longest? Which could hold several pieces of bread?",
      "What bakery foods do you enjoy eating or making?",
      "How might a baker use a rolling pin, baking tray, and oven peel?",
      "What other foods, smells, or tools might you find in a bakery?",
      "If you created a new kind of bread, what would it be like?"
    ],
    "positions": [
      12.43,
      22.75,
      37.41,
      47.76,
      58.16,
      72.78
    ]
  },
  "at-the-police-station": {
    "questions": [
      "Which items help police communicate, travel, or direct traffic?",
      "Which item is largest? Which items could be worn or carried?",
      "When have you seen police helping people in your community?",
      "How might officers use a radio, traffic baton, and police car?",
      "What other jobs or services help keep a community safe?",
      "If you could improve safety in one public place, what would you change?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      52.08,
      62.47,
      72.78
    ]
  },
  "at-the-campsite": {
    "questions": [
      "Which items give shelter, light, direction, or a way to cook?",
      "Which item would take up the most room? Which would fit in a pocket?",
      "Have you ever slept in a tent or spent time at a campsite?",
      "How might campers use the compass, lantern, and camp stove?",
      "What other things would help make camping safe and comfortable?",
      "If you planned a one-night camping trip, where would you go and what would you pack?"
    ],
    "positions": [
      12.43,
      22.75,
      37.41,
      47.76,
      62.47,
      77.1
    ]
  },
  "board-games": {
    "questions": [
      "Which items are pieces, and which help players measure chance or time?",
      "Which item has the most curved edges? Which has the most corners?",
      "What board or card games do you enjoy playing?",
      "How are the die, playing cards, and sand timer used in games?",
      "What other game pieces or rules can you name?",
      "If you invented a board game, what would players need to do to win?"
    ],
    "positions": [
      12.43,
      27.06,
      41.73,
      52.08,
      62.47,
      72.78
    ]
  },
  "jewelry": {
    "questions": [
      "Which items are worn on the ears, neck, wrist, hair, or clothing?",
      "Which item looks heaviest? Which looks most delicate?",
      "Do you ever wear jewelry or give it as a gift?",
      "How are cufflinks, a brooch, and a hairpin fastened?",
      "What other materials, colors, or kinds of jewelry can you name?",
      "If you designed one piece of jewelry, what would it look like?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "computer-equipment": {
    "questions": [
      "Which items help with typing, pointing, storing, connecting, or video?",
      "Which item is smallest? Which would need the most desk space?",
      "Which computer equipment do you use most often?",
      "How might someone use the router, webcam, and USB drive?",
      "What other computer parts or accessories can you name?",
      "If you could improve one piece of computer equipment, what would you change?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "emergency-room": {
    "questions": [
      "Which items help transport, support, monitor, or treat a patient?",
      "Which item is largest? Which could one person carry easily?",
      "Have you ever seen an ambulance or visited an emergency room?",
      "How might staff use the wheelchair, IV stand, and blood pressure cuff?",
      "What other people or equipment might be found in an emergency room?",
      "If you worked on an emergency team, which role would interest you?"
    ],
    "positions": [
      12.47,
      26.86,
      37.06,
      47.25,
      61.73,
      76.12
    ]
  },
  "car-parts": {
    "questions": [
      "Which parts help a car move, turn, start, or show what is behind it?",
      "Which item is heaviest? Which is smallest?",
      "Which car parts have you seen repaired or replaced?",
      "How do drivers use the steering wheel, gearshift, and side mirror?",
      "What other parts can you find inside or outside a car?",
      "If you designed a car, which feature would you improve first?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      62.47,
      72.78
    ]
  },
  "ancient-egypt": {
    "questions": [
      "Which items look like a building, a statue, a container, or a symbol?",
      "Which item looks largest in real life? Which could be worn or carried?",
      "Have you seen Egyptian objects in a book, film, or museum?",
      "How might people have used the papyrus scroll, canopic jar, or amulet?",
      "What other places or objects do you connect with ancient Egypt?",
      "If you could explore one ancient Egyptian site, what would you hope to see?"
    ],
    "positions": [
      12.43,
      27.06,
      41.73,
      52.08,
      66.78,
      77.1
    ]
  },
  "flowers": {
    "questions": [
      "Which flowers have warm colors, and which have light or cool colors?",
      "Which flower has the widest petals? Which has the longest stem?",
      "Which flowers do you see where you live?",
      "When do people give, grow, or display flowers?",
      "What other flowers, colors, or scents can you name?",
      "If you created a bouquet from three pictured flowers, which would you choose and why?"
    ],
    "positions": [
      12.43,
      27.06,
      41.73,
      52.08,
      62.47,
      72.78
    ]
  },
  "birds": {
    "questions": [
      "Which birds have long legs, large beaks, or colorful feathers?",
      "Which bird is tallest? Which looks best suited to swimming?",
      "Which of these birds have you seen in real life, pictures, or films?",
      "Where might each bird live, feed, or rest?",
      "What other birds can you name, and what makes them distinctive?",
      "If you could safely observe one of these birds closely, which would you choose?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      47.76,
      58.16,
      72.78
    ]
  },
  "kitchen-appliances": {
    "questions": [
      "Which appliances heat, cool, mix, toast, cook, or clean?",
      "Which appliance is largest? Which could be moved most easily?",
      "Which kitchen appliances do you use most often?",
      "How might someone use the blender, rice cooker, and dishwasher?",
      "What other appliances can make kitchen work easier?",
      "If you invented a new kitchen appliance, what task would it do?"
    ],
    "positions": [
      12.43,
      22.75,
      37.41,
      47.76,
      62.47,
      72.78
    ]
  },
  "art-supplies": {
    "questions": [
      "Which items are used for painting, drawing, shaping, or holding art materials?",
      "Which item looks easiest to carry? Which would need the most space?",
      "Which of these art supplies have you used before? What did you make?",
      "How might an artist use the palette, easel, and ink bottle?",
      "What other art materials or tools can you name?",
      "If you made a picture today, which three supplies would you choose? Why?"
    ],
    "positions": [
      12.43,
      27.06,
      41.73,
      56.39,
      66.78,
      77.1
    ]
  },
  "sports-equipment": {
    "questions": [
      "Which items are held in one hand, and which are usually held with two hands?",
      "Which item is longest? Which looks lightest?",
      "Which sports using this equipment have you played or watched?",
      "How is a shuttlecock used differently from a ball?",
      "What other sports equipment can you name?",
      "If you could learn one sport connected to this card, which would you choose?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      52.08,
      62.47,
      72.78
    ]
  },
  "at-the-pharmacy": {
    "questions": [
      "Which items hold medicine, and which help someone use it?",
      "Which item is largest? Which could fit easily in a pocket?",
      "Which of these items have you seen in a pharmacy or medicine cabinet?",
      "How might someone use the measuring spoon or hot-water bottle safely?",
      "What other things might a pharmacy sell?",
      "If you worked in a pharmacy, which item would be easiest to explain to a customer?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      47.76,
      62.47,
      72.78
    ]
  },
  "picnic-time": {
    "questions": [
      "Which items carry food, keep things cool, or make sitting outdoors comfortable?",
      "Which item looks heaviest when full? Which is easiest to recycle?",
      "Have you ever eaten outdoors with friends or classmates? What was it like?",
      "How would you pack the basket, flask, and cooler box for a picnic?",
      "What other foods or supplies could people bring to a picnic?",
      "Imagine a picnic in a nearby place. What would you bring and why?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      52.08,
      66.78,
      77.1
    ]
  },
  "spices": {
    "questions": [
      "Which spices are roots, leaves, pods, bark, or dried flower buds?",
      "Which spice has the strongest color? Which pieces are smallest?",
      "Which of these spices have you smelled, tasted, or cooked with?",
      "How do people add spices to food or drinks?",
      "What other spices or seasonings can you name?",
      "If you created a new spice mixture, which three pictured spices would you combine?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "travel-accessories": {
    "questions": [
      "Which items help with comfort, identification, packing, or checking luggage?",
      "Which item is smallest? Which might be most useful on a long trip?",
      "Which travel accessories have you used or seen before?",
      "How are the luggage tag, adapter, and luggage scale used?",
      "What other useful travel accessories can you name?",
      "If you could pack only three items from this card, which would you choose?"
    ],
    "positions": [
      12.43,
      27.06,
      41.73,
      52.08,
      62.47,
      72.78
    ]
  },
  "ways-to-travel": {
    "questions": [
      "Which vehicles travel on roads, rails, water, or cables?",
      "Which vehicle could carry the most people? Which is smallest?",
      "Which of these ways to travel have you used or seen?",
      "Where might people use a ferry, tram, rickshaw, or cable car?",
      "What other types of transportation can you name?",
      "If you could take a short trip in one pictured vehicle, which would you choose?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "at-the-aquarium": {
    "questions": [
      "Which items are animals, shells, coral, or aquarium decorations?",
      "Which item has the most branches or tentacles? Which looks hardest?",
      "Which of these aquarium sights have you seen before?",
      "How might an angelfish or hermit crab move and find shelter?",
      "What other animals or objects might be found in an aquarium?",
      "If you designed an aquarium display, which three pictured items would you include?"
    ],
    "positions": [
      12.43,
      22.75,
      37.41,
      47.76,
      62.47,
      72.78
    ]
  },
  "at-the-coffee-shop": {
    "questions": [
      "Which items prepare a drink, hold ingredients, or help serve a customer?",
      "Which item is largest? Which could be used without electricity?",
      "Which coffee-shop equipment have you seen or used before?",
      "How might someone use the grinder, filter, and espresso machine in order?",
      "What other drinks, foods, or equipment might a coffee shop have?",
      "If you opened a small drink shop, which pictured items would you need first?"
    ],
    "positions": [
      12.47,
      26.86,
      37.06,
      47.25,
      61.73,
      76.12
    ]
  },
  "at-the-supermarket": {
    "questions": [
      "Which items help a shopper collect, pay for, or carry groceries?",
      "Which item is largest? Which could fit easily in one hand?",
      "Which of these supermarket items have you used or seen before?",
      "How does a shopper move from the cart to the checkout and then leave?",
      "What other things might you see in a supermarket?",
      "If you were buying food for one day, which pictured items would you use?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      52.08,
      66.78,
      77.1
    ]
  },
  "tableware": {
    "questions": [
      "Which items hold food, and which items help someone eat it?",
      "Which items are made of metal? Which look easiest to wash?",
      "Which kinds of tableware do you use most often?",
      "How would you arrange these items for a meal?",
      "What other things might people put on a dining table?",
      "If you could keep only four pictured items, which would you choose?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "cooking-utensils": {
    "questions": [
      "Which utensils are used for stirring, lifting, draining, or peeling food?",
      "Which item has holes? Which item looks sharpest?",
      "Which of these utensils have you used or watched someone use?",
      "How might a cook use several of these tools to prepare one meal?",
      "What other useful cooking utensils can you name?",
      "Which three pictured utensils would you choose for a small kitchen?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "fresh-fruit": {
    "questions": [
      "Which fruits have a peel, rind, leafy top, or crown?",
      "Which fruit is largest? Which has the strongest color?",
      "Which of these fruits have you eaten or seen for sale?",
      "How might people wash, cut, or serve these fruits?",
      "What other fresh fruits can you name?",
      "If you made a fruit plate, which three pictured fruits would you include?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "fresh-vegetables": {
    "questions": [
      "Which vegetables are leafy, round, long, or covered with florets?",
      "Which vegetable is darkest? Which looks heaviest?",
      "Which of these vegetables have you eaten or prepared before?",
      "How might people wash, cut, or cook these vegetables?",
      "What other fresh vegetables can you name?",
      "If you planned a vegetable dish, which three pictured items would you use?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "pantry-basics": {
    "questions": [
      "Which pantry items are grains, seasonings, legumes, or cooking ingredients?",
      "Which item is liquid? Which items are made of many small pieces?",
      "Which of these pantry basics do you recognize or use?",
      "How might someone store these foods and keep them fresh?",
      "What other basic foods might be kept in a pantry or cupboard?",
      "If you were stocking an empty pantry, which pictured items would you buy first?"
    ],
    "positions": [
      12.43,
      27.06,
      41.73,
      52.08,
      62.47,
      72.78
    ]
  },
  "breakfast-foods": {
    "questions": [
      "Which foods are baked, packaged, chilled, or ready to eat?",
      "Which item looks lightest? Which might take longest to prepare?",
      "Which of these breakfast foods have you tried or seen before?",
      "How might someone combine several pictured foods for breakfast?",
      "What other foods or drinks can be part of breakfast?",
      "If you needed a quick breakfast, which pictured items would you choose?"
    ],
    "positions": [
      12.43,
      27.06,
      41.73,
      52.08,
      66.78,
      77.1
    ]
  },
  "home-entryway": {
    "questions": [
      "Which items help someone enter, secure, or organize a home?",
      "Which items attach to a wall or door? Which rests on the floor?",
      "Which of these entryway items have you used or noticed before?",
      "What might someone do with these items when arriving home?",
      "What other useful things might be kept near an entrance?",
      "If you organized a small entryway, which pictured items would you include?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "electrical-essentials": {
    "questions": [
      "Which items connect to electricity, control it, or provide light?",
      "Which items have cords? Which items are usually fixed to a wall?",
      "Which of these electrical items have you used or seen?",
      "How can someone use plugs, outlets, and extension cords safely?",
      "What other common things in a home use electricity?",
      "If the power went out, which pictured items would stop being useful?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      62.47,
      72.78
    ]
  },
  "personal-care": {
    "questions": [
      "Which items are used for cleaning, grooming, or staying comfortable?",
      "Which items have a handle? Which item is made mostly of paper?",
      "Which of these personal-care items have you used or seen?",
      "How should someone store these items so they stay clean and safe?",
      "What other everyday personal-care items can you name?",
      "If you packed a small wash bag, which pictured items would you include?"
    ],
    "positions": [
      12.43,
      22.35,
      32.31,
      42.27,
      52.27,
      62.2
    ]
  },
  "dishwashing": {
    "questions": [
      "Which items help wash, protect, dry, or organize dishes?",
      "Which item has bristles? Which items are made mostly of metal?",
      "Which of these dishwashing items have you used or seen?",
      "What order might someone use these items when washing dishes by hand?",
      "What other things help keep a kitchen sink area clean?",
      "If you had only three pictured items, which would be most useful?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      58.16,
      68.47
    ]
  },
  "food-storage": {
    "questions": [
      "Which items wrap food, cover food, or hold food in a container?",
      "Which items are flexible? Which items keep their shape?",
      "Which of these food-storage items have you used or seen?",
      "How might someone choose the right item for leftovers or a packed meal?",
      "What other ways can food be stored safely?",
      "If you prepared lunch to take outside, which pictured items would you use?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      62.47,
      72.78
    ]
  },
  "writing-supplies": {
    "questions": [
      "Which supplies help write, measure, cut, attach, or correct something?",
      "Which items are made mostly of metal? Which is softest?",
      "Which of these writing supplies do you use most often?",
      "How might someone use several pictured items for one small project?",
      "What other supplies are useful for writing or paperwork?",
      "If you made a small pencil case, which pictured items would you pack?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      62.47,
      72.78
    ]
  },
  "bathroom-essentials": {
    "questions": [
      "Which items help with washing, drying, comfort, or cleaning?",
      "Which items are soft? Which items have a handle?",
      "Which of these bathroom items have you used or seen?",
      "Where would each pictured item normally be kept in a bathroom?",
      "What other ordinary bathroom items can you name?",
      "If you prepared a new bathroom, which pictured items would you get first?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "cleaning-extras": {
    "questions": [
      "Which items collect dirt, hold waste, wipe surfaces, or remove water?",
      "Which items are flexible? Which items can stand upright?",
      "Which of these cleaning items have you used or seen?",
      "How might someone sort ordinary trash from recyclable materials?",
      "What other things help keep a home or workplace clean?",
      "If you cleaned one room, which pictured items would be most useful?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      62.47,
      72.78
    ]
  },
  "parts-of-a-home": {
    "questions": [
      "Which parts help someone enter, see outside, move upstairs, or cool a room?",
      "Which parts usually move? Which parts are fixed in one place?",
      "Which of these home features are familiar to you?",
      "How might someone use each pictured part during an ordinary day?",
      "What other common parts of a home can you name?",
      "If you designed one room, which pictured parts would it need?"
    ],
    "positions": [
      12.43,
      27.06,
      41.73,
      52.08,
      66.78,
      77.1
    ]
  },
  "coffee-shop-drinks": {
    "questions": [
      "Which drinks contain mostly coffee, mostly milk, or a balance of both?",
      "How do the milk and foam layers differ among the six drinks?",
      "Which drink looks strongest? Which one looks creamiest?",
      "How are an espresso, an Americano, and a macchiato different?",
      "Which of these drinks have you ordered or tasted before?",
      "What would you ask the barista to change in your chosen drink?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      62.47,
      72.78
    ]
  },
  "at-the-hardware-store": {
    "questions": [
      "Which items on the card are used on surfaces?",
      "Which item looks strongest, and which looks easiest to carry?",
      "Which of these items have you seen someone use?",
      "How would you use the paint roller and paint tray together?",
      "What other useful things can people buy at a hardware store?",
      "If you could learn one home-repair skill, which item would you choose first?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "at-the-orchestra": {
    "questions": [
      "Which items are used for percussion, reading, or bowed strings?",
      "Which item is longest, and which item is smallest?",
      "Have you ever watched an orchestra in person or on a screen?",
      "Why do musicians place sheet music on a music stand?",
      "What other people or instruments might you see in an orchestra?",
      "If you joined an orchestra for one day, what role would you choose?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      52.08,
      62.47,
      77.1
    ]
  },
  "shoe-care": {
    "questions": [
      "Which items clean shoes, and which items help shoes keep their form?",
      "Which item would be easiest to lose? Why?",
      "How do you usually keep your shoes clean?",
      "What happens when a shoelace loses its aglet?",
      "What other things can help shoes last longer?",
      "If you designed a shoe-care kit, which three items would you include?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "camping-extras": {
    "questions": [
      "Which items help with a tent, a fire, or insects?",
      "Which item seems most important for a safe campsite?",
      "Have you ever used any extra camping equipment like these items?",
      "How do a tent peg and guyline work together?",
      "What other small items can make camping more comfortable?",
      "If you camped for one night, which two extras would you pack first?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      47.76,
      58.16,
      68.47
    ]
  },
  "bicycle-components": {
    "questions": [
      "Which components help with warning, tire pressure, or movement?",
      "Which component has the most small parts?",
      "Have you ever used a bicycle pump or bell?",
      "How do the chainring and bicycle chain move a bicycle?",
      "What other bicycle components can you name?",
      "If your bicycle needed one upgrade, which component would you choose?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "clothing-actions": {
    "questions": [
      "Which actions close clothing, and which open it?",
      "Which fastening is easiest to use? Why?",
      "Which of these clothing actions do you use most often?",
      "When might someone need help with buttons, zippers, or laces?",
      "What other verbs describe getting dressed?",
      "Imagine getting ready very quickly. Which fastening would you choose?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "communication-actions": {
    "questions": [
      "Which actions can happen during a classroom discussion?",
      "How are whispering and shouting different?",
      "When do you need to ask or answer a question?",
      "How can people disagree politely?",
      "What other ways can people communicate without words?",
      "Imagine a very noisy place. Which actions would help you communicate?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "device-actions": {
    "questions": [
      "Which actions use electricity, and which use an online account?",
      "How are turning off and unplugging different?",
      "Which device actions do you use every day?",
      "Why should you unplug some devices carefully?",
      "What other technology verbs do you know?",
      "Imagine helping someone use a new computer. Which instructions would you give first?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "eating-and-senses": {
    "questions": [
      "Which actions use the mouth, and which use the nose?",
      "How are biting and chewing different?",
      "What foods do you like to taste or smell?",
      "Why is it useful to smell food before eating it?",
      "What other sense verbs do you know?",
      "Imagine trying a new food. Which senses would you use first?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "everyday-problems": {
    "questions": [
      "Which actions are opposites or two sides of the same situation?",
      "Which problem is usually easiest to solve? Why?",
      "Have you ever lost something and found it later?",
      "What should you do before borrowing something?",
      "What other common problems can you describe in English?",
      "Imagine you break something that belongs to a friend. What would you say and do?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "family-members": {
    "questions": [
      "Which family words describe women, and which describe men?",
      "How are parents different from grandparents?",
      "Which of these family words do you use most often?",
      "When might you introduce a family member to someone?",
      "What other family words do you know in English?",
      "Imagine a family celebration. Which people might be there?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "kitchen-actions": {
    "questions": [
      "Which actions cook food, measure ingredients, or clean up afterward?",
      "How are boiling and frying different?",
      "Which kitchen actions do you do most often?",
      "Why is measuring useful when you follow a recipe?",
      "What other cooking verbs do you know?",
      "Imagine making a simple meal. In what order would you use these actions?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "moving-objects": {
    "questions": [
      "Which actions move something toward you, and which move it away?",
      "Which actions need the most strength? Why?",
      "When have you carried or dragged something heavy?",
      "How can you lift a box safely?",
      "What other movement verbs do you know?",
      "Imagine moving to a new home. Which actions would you use most?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      53.84,
      64.16
    ]
  },
  "parts-of-the-body": {
    "questions": [
      "Which body parts come in pairs, and which come in larger groups?",
      "How are fingers and toes similar?",
      "When do you need to name a body part in English?",
      "How do arms and legs help us in daily life?",
      "What other body parts can you name?",
      "Choose one body part and imagine one day without using it. What would be difficult?"
    ],
    "positions": [
      12.43,
      27.06,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "travel-actions": {
    "questions": [
      "Which actions happen before, during, and after a journey?",
      "Which travel action can take the most time? Why?",
      "What do you usually pack for a short trip?",
      "How should passengers get on and off a bus safely?",
      "What other travel verbs do you know?",
      "Imagine taking your first flight. Which actions would you notice?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "common-descriptions": {
    "questions": [
      "Which pictures compare price, age, and strength?",
      "Which descriptions are opposites?",
      "What is something new or old that you use often?",
      "How can you compare a cheap item with an expensive one?",
      "What other useful describing words do you know?",
      "Imagine choosing between a new cheap item and an old expensive item. What would you consider?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "digital-actions": {
    "questions": [
      "Which actions use a phone, a computer control, or paper?",
      "Which digital actions do you use most often?",
      "When did you last call or text someone?",
      "How do printing and scanning work in opposite directions?",
      "What other actions can you do with a phone or computer?",
      "Imagine you cannot use the internet for a day. Which action would you miss most?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "everyday-opposites": {
    "questions": [
      "Which actions form opposite pairs?",
      "Which pair changes a door, a lock, or a container?",
      "When do you lock or unlock something?",
      "What things can people fill and empty?",
      "What other opposite actions do you know?",
      "Imagine giving directions for leaving home. Which actions might you mention?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "hand-actions": {
    "questions": [
      "Which actions move an object from one place or person to another?",
      "How are giving and taking different?",
      "What games use throwing and catching?",
      "When might someone hide or reveal something?",
      "What other actions can people do with their hands?",
      "Which action would be easiest to demonstrate to the class? Why?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "health-symptoms": {
    "questions": [
      "Which symptoms affect breathing, temperature, and skin?",
      "Which symptoms might be easy or difficult for another person to notice?",
      "Which of these words have you heard before?",
      "How could you clearly describe one of these symptoms to an adult?",
      "What other common symptoms do you know?",
      "If a classmate felt unwell, what helpful action could you take?"
    ],
    "positions": [
      12.43,
      27.06,
      41.73,
      52.08,
      66.78,
      77.1
    ]
  },
  "how-people-behave": {
    "questions": [
      "Which behaviors on the card help other people?",
      "How are polite and rude behavior different?",
      "When have you seen someone act honestly?",
      "How can being careful prevent a problem?",
      "What other words describe the way people behave?",
      "Which behavior would you most want in a classmate or teammate? Why?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "location-words": {
    "questions": [
      "Where is the red object in each picture?",
      "Which location words are opposites?",
      "What is above or below you right now?",
      "How can you explain where a lost object is?",
      "What other location words do you know?",
      "Imagine hiding a key. Which location word could describe its position?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "more-jobs": {
    "questions": [
      "Which jobs work in healthcare, transport, and shops?",
      "Which job might require the most training? Why?",
      "Which of these workers have you spoken with before?",
      "What does each worker do during a normal day?",
      "What other common jobs can you name?",
      "Imagine trying one of these jobs for a day. Which would you choose?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "size-words": {
    "questions": [
      "Which pictures show differences in height, width, and overall size?",
      "Which size words are opposites? How do you know?",
      "What is something big or small that you use every day?",
      "When is a wide space more useful than a narrow one?",
      "What other size words do you know?",
      "Imagine choosing a bag for a trip. Which size would you choose, and why?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "social-actions": {
    "questions": [
      "Which actions can happen when people see each other?",
      "How are meeting and greeting different?",
      "When have you visited or invited someone?",
      "Why are apologizing and forgiving important?",
      "What other social actions help people get along?",
      "Imagine welcoming a new student. Which actions would you use first?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "clothing-care-actions": {
    "questions": [
      "Which actions store, smooth, or repair clothes?",
      "How are ironing and steaming similar or different?",
      "Which clothing-care actions have you seen or tried?",
      "Why do people fold or hang different kinds of clothes?",
      "What other words are useful when doing laundry?",
      "Imagine a shirt has a small hole. What would you do with it?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "common-food-groups": {
    "questions": [
      "Which foods are dairy, meat, or vegetables?",
      "How do the foods differ in color and texture?",
      "Which of these foods have you eaten?",
      "How might people use these foods in a meal?",
      "What other basic grocery foods can you name?",
      "Imagine making a shopping list. Which two foods would you add, and why?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "everyday-basics": {
    "questions": [
      "Which actions are connected with meals, chairs, and beds?",
      "How are sitting and standing different?",
      "When do you usually eat and drink during the day?",
      "What helps you wake up in the morning?",
      "What other basic daily actions do you know?",
      "Imagine explaining your morning routine. Which actions would you mention first?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "everyday-states": {
    "questions": [
      "Which states relate to appetite, health, and available time?",
      "How can you tell what each person is experiencing?",
      "When do you usually feel hungry or full?",
      "What habits can help a person stay healthy?",
      "What other everyday states can you describe?",
      "Imagine you suddenly have a free afternoon. What would you do?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "food-preparation-actions": {
    "questions": [
      "Which actions use a knife, hands, or an oven?",
      "How are slicing and dicing different?",
      "Which food-preparation actions have you seen at home?",
      "What foods can people bake or roast?",
      "What other cooking verbs do you know?",
      "Imagine preparing a simple meal. Which action would you do first?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "more-fresh-fruit": {
    "questions": [
      "Which fruits have stones, berries, or green flesh?",
      "How do these fruits differ in size and texture?",
      "Which of these fruits have you tasted?",
      "How can people eat or prepare each fruit?",
      "What other fresh fruits can you name?",
      "Imagine making a fruit snack. Which fruits would you combine?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "personal-qualities": {
    "questions": [
      "Which qualities are shown as opposite pairs?",
      "How can a person's actions show kindness or courage?",
      "When have you needed to be patient?",
      "Why might two people react differently to the same situation?",
      "What other words describe a person's character?",
      "Which quality would you most like to strengthen in yourself? Why?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      58.16,
      68.47
    ]
  },
  "places-in-town": {
    "questions": [
      "Which places are connected with health, books, and food?",
      "How are a library and a bookstore different?",
      "Which of these places have you visited?",
      "What might a person do at each place?",
      "What other places can people find in a town?",
      "Imagine giving a visitor directions. Which place would be easiest to explain?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "small-body-actions": {
    "questions": [
      "Which actions use the eyes, head, or hands?",
      "How are blinking and winking different?",
      "When do people nod or shake their heads?",
      "Why might someone clap or snap their fingers?",
      "What other small body movements can you name?",
      "Which action could you use in a silent classroom game?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "sound-actions": {
    "questions": [
      "Which actions make music, show emotion, or get attention at a door?",
      "How are humming and singing different?",
      "What kinds of things make you laugh?",
      "When might someone knock or ring before entering?",
      "What other sound actions can you name?",
      "Imagine telling a short story. Which sound action would make it more interesting?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "common-changes": {
    "questions": [
      "Which changes affect size, visibility, or quality?",
      "How are growing and improving different?",
      "What have you watched grow over time?",
      "What can make a situation improve or worsen?",
      "What other change verbs do you know?",
      "Imagine improving your classroom. What would you change first?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "common-contrasts": {
    "questions": [
      "Which words describe speed, sound, and depth?",
      "How are fast and slow movements different?",
      "When do you prefer a quiet place?",
      "Where might you hear a very loud sound?",
      "What other pairs of contrasting words do you know?",
      "Imagine planning a safe swimming area. Which descriptions would matter most?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "everyday-conditions": {
    "questions": [
      "Which words describe cleanliness, temperature, and weight?",
      "How can you tell whether something is hot or cold?",
      "What heavy or light things do you carry often?",
      "How do people keep shoes and clothes clean?",
      "What other condition words are useful in daily life?",
      "Imagine packing a bag for a trip. Which items would you keep light?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "people-at-home": {
    "questions": [
      "Which people are connected by family, marriage, or hospitality?",
      "How are the roles of a guest and a host different?",
      "Who do you often spend time with at home?",
      "What can a host do to welcome a guest?",
      "What other relationship words do you know?",
      "Imagine a guest is visiting your home. What would you plan together?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "people-we-meet": {
    "questions": [
      "Which people are connected by familiarity, shopping, or sports?",
      "How are the roles of a customer and a clerk different?",
      "Where have you met a helpful clerk or coach?",
      "How do people usually behave when meeting a stranger?",
      "What other social roles do you use in daily life?",
      "Imagine joining a new team. How could a coach and players welcome you?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "position-words": {
    "questions": [
      "Which words describe viewpoint, distance, and direction?",
      "How are near and far different?",
      "When do you need to know left from right?",
      "How can position words help when giving directions?",
      "What other position words can you name?",
      "Imagine guiding someone through a room. Which position words would you use?"
    ],
    "positions": [
      12.43,
      22.75,
      28.78,
      39.14,
      49.53,
      59.84
    ]
  },
  "quantity-words": {
    "questions": [
      "Which words compare amounts or show complete, partial, and empty quantities?",
      "How are more and double different?",
      "When might you need half of something?",
      "How can quantity words help when shopping or cooking?",
      "What other words can describe an amount?",
      "Imagine dividing a pizza for a class. How could you use half, double, all, or none?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "texture-words": {
    "questions": [
      "Which words describe surfaces, firmness, and cutting edges?",
      "How are smooth and rough objects different to touch?",
      "What soft or hard things do you use every day?",
      "Why is it important to know whether an edge is sharp or dull?",
      "What other texture words can you name?",
      "Imagine choosing a pillow and a work surface. Which qualities would you want?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "thinking-actions": {
    "questions": [
      "Which actions involve memory, certainty, or choices?",
      "How are knowing and guessing different?",
      "What helps you remember important things?",
      "When might someone change their mind?",
      "What other thinking verbs do you use often?",
      "Imagine making a difficult choice. What information would help you decide?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "ways-to-move": {
    "questions": [
      "Which movements use footsteps, water, or upward motion?",
      "How are running and walking different?",
      "Which of these movements have you practiced?",
      "Where can people safely swim or climb?",
      "What other movement verbs do you know?",
      "Imagine planning an active day. Which movements would you include?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "basic-colors": {
    "questions": [
      "Which colors are light, dark, warm, or cool?",
      "What happens when red is mixed with blue or yellow?",
      "Which colors do you notice most often around you?",
      "How can color help people organize or identify things?",
      "What other color words can you name?",
      "Choose two colors for a classroom poster. Why would they work together?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "basic-directions": {
    "questions": [
      "Which directions are used on a globe, and which describe vertical movement?",
      "How are north and up different?",
      "When have you used directions to find a place?",
      "How can a map or phone help someone travel east or west?",
      "What other direction words can you name?",
      "Imagine giving directions to a visitor. Which words would you need?"
    ],
    "positions": [
      12.43,
      27.06,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "basic-judgments": {
    "questions": [
      "Which words compare things, judge truth, or check accuracy?",
      "How are false and incorrect different?",
      "When do you need to decide whether two things are the same or different?",
      "How can someone check whether an answer is correct?",
      "What other evaluation words can you name?",
      "Imagine respectfully correcting a classmate. What could you say?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      47.76,
      58.16,
      68.47
    ]
  },
  "common-health-problems": {
    "questions": [
      "Which problems affect the teeth, stomach, throat, or nose?",
      "How are nausea and a stomachache different?",
      "Which of these health words have you heard before?",
      "What can someone say when asking a doctor or adult for help?",
      "What other common health problems can you name?",
      "Imagine helping a classmate who feels unwell. What could you do safely?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      58.16,
      68.47
    ]
  },
  "everyday-clothes": {
    "questions": [
      "Which clothes cover the upper body, lower body, or feet?",
      "How are a shirt and a sweater different?",
      "Which of these clothes do you wear often?",
      "When might someone choose sandals instead of socks and closed shoes?",
      "What other everyday clothes can you name?",
      "Choose three items for a short trip. Why would you pack them?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      58.16,
      68.47
    ]
  },
  "file-actions": {
    "questions": [
      "Which actions make, move, keep, or remove a digital file?",
      "How are upload and download different?",
      "Which file actions have you used on a phone or computer?",
      "Why is it useful to save a file before closing an app?",
      "What other computer actions can you name?",
      "Imagine organizing a class project online. Which file actions would you need?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "household-problems": {
    "questions": [
      "Which problems involve water, surface patches, or physical damage?",
      "How is a crack different from a dent?",
      "Which household problem words have you heard before?",
      "Who could safely help with a leak or clog?",
      "What other problems can happen in a home?",
      "Imagine noticing one of these problems early. What would you do next?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "more-body-parts": {
    "questions": [
      "Which body parts are joints, and which end in fingers or toes?",
      "How are an elbow and a knee similar?",
      "Which of these body-part words do you use most often?",
      "How do wrists and ankles help the body move?",
      "What other body parts can you name?",
      "Imagine explaining a minor injury. Which body words might you need?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  },
  "school-subjects": {
    "questions": [
      "Which subjects focus on numbers, people and places, or laboratory work?",
      "How are biology and chemistry different?",
      "Which school subject do you find most interesting? Why?",
      "How can statistics help people understand information?",
      "What other school subjects can you name?",
      "If you could design a class project, which two subjects would you combine?"
    ],
    "positions": [
      12.43,
      27.06,
      37.41,
      47.76,
      58.16,
      68.47
    ]
  },
  "useful-rooms": {
    "questions": [
      "Which rooms are mainly for rest, meals, or practical work?",
      "How is a bedroom different from a nursery?",
      "Which of these rooms have you visited or used?",
      "What activities usually happen in a kitchen or workshop?",
      "What other useful rooms can you name?",
      "If you could add one room to a community center, which would you choose?"
    ],
    "positions": [
      12.43,
      22.75,
      33.1,
      43.45,
      53.84,
      64.16
    ]
  }
};
