# Page 8 — cutaway apartment building with the street outside.
# Boxes read straight off the tiler grid labels, one block per tile.
P = [

# TILE r0c0
("Red hot air balloon", [1.2, 6.4, 5.2, 8.6], "The red hot air balloon", "float", "high above the green hills", False),
("Blue hot air balloon", [1.5, 11.6, 4.5, 13.1], "The blue hot air balloon", "drift", "across the morning sky", False),
("Flying stork", [1.3, 16.5, 4.0, 19.3], "The flying stork", "glide", "over the countryside", False),
("Yellow wheat field", [5.0, 13.2, 8.7, 24.0], "The yellow wheat field", "stretch", "along the hillside", False),
("Pink country house", [7.7, 10.2, 12.7, 15.1], "The pink country house", "stand", "among the trees", False),
("Yellow cottage on the hill", [9.4, 4.1, 12.7, 6.6], "The yellow cottage on the hill", "sit", "above the village", False),
("White cottage by the trees", [9.9, 6.6, 12.9, 10.2], "The white cottage by the trees", "look", "over the meadow", False),
("Little stream", [12.7, 7.8, 15.2, 13.9], "The little stream", "wind", "through the fields", False),
("Tall pine tree", [6.4, 11.4, 9.9, 12.6], "The tall pine tree", "grow", "on the green hill", False),
("Bare tree by the pink house", [9.9, 15.7, 13.3, 17.3], "The bare tree by the pink house", "lean", "towards the river", False),
("Green hillside trees", [5.9, 0.0, 12.0, 4.3], "The green hillside trees", "cover", "the far slope", True),
("White cat in the attic", [12.9, 21.6, 14.2, 23.3], "The white cat in the attic", "sleep", "beside the old boxes", False),
("Red tiled roof", [13.1, 0.9, 18.0, 7.1], "The red tiled roof", "shine", "in the afternoon sun", False),
("Brick chimney", [12.2, 0.0, 15.2, 1.2], "The brick chimney", "rise", "above the red roof", False),
("Black cat on the roof", [21.7, 2.7, 24.7, 4.6], "The black cat on the roof", "creep", "along the blue wall", False),
("Oval attic window", [19.9, 5.7, 23.6, 7.2], "The oval attic window", "face", "the quiet street", False),
("Small bird on the gutter", [23.3, 15.4, 24.5, 16.2], "The small bird on the gutter", "sing", "outside the balcony", False),
("Rain gutter", [15.2, 13.1, 17.1, 16.0], "The rain gutter", "run", "along the edge of the roof", False),
("Purple flowers in the balcony box", [25.2, 13.1, 28.2, 16.6], "The purple flowers in the balcony box", "bloom", "in the warm sunshine", True),
("White balcony railing", [27.3, 13.2, 31.5, 16.8], "The white balcony railing", "curve", "around the small balcony", False),
("Balcony glass door", [16.4, 17.4, 34.3, 22.8], "The balcony glass door", "open", "onto the balcony", False),

# TILE r0c1
("Attic window", [0.0, 29.6, 4.7, 32.8], "The attic window", "let", "light into the loft", False),
("Attic cupboard door", [6.4, 29.9, 12.0, 32.7], "The attic cupboard door", "hide", "the old winter clothes", False),
("Small cardboard box", [9.2, 26.2, 10.8, 28.2], "The small cardboard box", "sit", "on the bigger box", False),
("Big cardboard box", [10.6, 25.2, 13.3, 28.5], "The big cardboard box", "wait", "under the sloping roof", False),
("Jester puppet", [1.3, 41.0, 6.4, 42.2], "The jester puppet", "hang", "from its tangled strings", False),
("Green crocodile puppet", [4.3, 40.4, 8.0, 42.8], "The green crocodile puppet", "dangle", "above the desk", False),
("Sailor doll on the box", [6.8, 37.0, 10.8, 38.4], "The sailor doll on the box", "rest", "beside the red blanket", False),
("Woman at the attic desk", [2.9, 43.2, 13.3, 45.3], "The woman at the attic desk", "paint", "a wooden puppet", False),
("Red office chair", [5.9, 42.2, 13.8, 44.7], "The red office chair", "stand", "in front of the workbench", False),
("Little wooden doll", [4.3, 45.6, 8.7, 47.2], "The little wooden doll", "stand", "on the workbench", False),
("Chest of drawers in the attic", [7.5, 38.2, 12.7, 40.4], "The chest of drawers in the attic", "hold", "the puppet maker's tools", False),
("Paper roll", [3.1, 46.4, 4.5, 48.4], "The paper roll", "hang", "on the attic rail", False),
("Attic workbench", [8.7, 46.5, 13.3, 49.8], "The attic workbench", "carry", "brushes and paint pots", False),
("Red blanket in the attic", [9.9, 34.7, 12.2, 37.0], "The red blanket in the attic", "lie", "over the old bench", False),
("Blue cup on the desk", [4.7, 38.7, 6.8, 39.4], "The blue cup on the desk", "hold", "the paintbrushes", False),
("Framed family photo", [17.5, 25.3, 21.5, 27.6], "The framed family photo", "hang", "above the red sofa", False),
("Small gold picture", [19.4, 28.8, 22.2, 30.2], "The small gold picture", "decorate", "the living room wall", False),
("Red sofa", [23.8, 21.6, 30.6, 31.2], "The red sofa", "fill", "one side of the living room", False),
("Yellow cushion on the sofa", [26.4, 22.9, 28.7, 24.8], "The yellow cushion on the sofa", "sit", "in the corner of the seat", False),
("Second yellow cushion", [25.7, 28.7, 28.0, 30.2], "The second yellow cushion", "lean", "against the sofa arm", False),
("Dark wooden chest", [29.3, 20.8, 33.8, 27.8], "The dark wooden chest", "stand", "in front of the red sofa", False),
("Blue bowl on the chest", [29.6, 25.2, 30.6, 26.4], "The blue bowl on the chest", "hold", "the house keys", False),
("Green building blocks", [31.5, 27.9, 32.7, 29.0], "The green building blocks", "lie", "on the living room floor", True),
("White football", [31.3, 29.6, 32.9, 30.7], "The white football", "roll", "across the floor", False),
("Grey cat by the table", [29.6, 32.7, 32.9, 34.2], "The grey cat by the table", "wait", "for a piece of breakfast", False),
("Glass display cabinet", [17.3, 31.3, 31.9, 34.1], "The glass display cabinet", "show", "the family china", False),
("Spider plant on the cabinet", [15.7, 31.8, 18.2, 35.0], "The spider plant on the cabinet", "spill", "over the wooden top", False),
("Yellow hanging lamp", [15.4, 36.1, 21.3, 37.5], "The yellow hanging lamp", "hang", "above the dining table", False),
("Boy at the breakfast table", [24.0, 32.1, 30.6, 33.9], "The boy at the breakfast table", "reach", "for the bread", False),
("Dining table", [25.7, 34.1, 33.3, 39.6], "The dining table", "hold", "the family breakfast", False),
("Red dining chair", [26.4, 35.0, 33.3, 37.5], "The red dining chair", "stand", "beside the table", False),
("White plate", [24.0, 36.2, 25.9, 37.5], "The white plate", "wait", "on the tablecloth", False),
("Green teapot", [25.2, 34.4, 26.6, 35.5], "The green teapot", "steam", "on the breakfast table", False),
("Red mug", [25.2, 37.8, 26.6, 38.5], "The red mug", "stand", "next to the plate", False),
("Father in the striped shirt", [18.5, 40.1, 33.3, 43.5], "The father in the striped shirt", "carry", "a cup of coffee", False),
("Coffee machine", [21.7, 43.5, 26.8, 45.3], "The coffee machine", "brew", "the morning coffee", False),
("Kitchen counter", [26.4, 42.8, 33.3, 46.5], "The kitchen counter", "run", "along the kitchen wall", False),
("Kitchen wall cupboard", [17.1, 46.5, 23.1, 48.7], "The kitchen wall cupboard", "store", "the plates and glasses", False),
("White cooker", [26.4, 47.8, 32.4, 49.8], "The white cooker", "warm", "the kitchen", False),
("Kettle on the stove", [22.7, 48.2, 25.2, 49.2], "The kettle on the stove", "whistle", "on the hot ring", False),
("Blue dog bowl", [32.4, 47.8, 33.4, 48.8], "The blue dog bowl", "sit", "on the kitchen floor", False),
("Tall yellow kitchen cupboard", [16.8, 41.2, 26.4, 43.5], "The tall yellow kitchen cupboard", "stand", "beside the fridge", False),
]
