# Page 23 — second pass, filling in smaller objects missed on the first read.
# (name, [ymin, xmin, ymax, xmax], subject, bare-infinitive verb, rest, plural)

P = [
    ("Slippers by the sleeping mats", [16.9, 5.0, 19.6, 8.7],
     "The slippers", "wait", "beside the sleeping mat", True),
    ("Rug on the reading room floor", [15.5, 22.3, 22.1, 33.5],
     "The patterned rug", "lie", "in front of the sofa", False),
    ("Lamp beside the sofa", [1.6, 34.0, 5.5, 37.2],
     "The reading lamp", "stand", "beside the sofa", False),
    ("Fish tank chime near the bathroom", [4.6, 62.8, 8.0, 65.4],
     "The fish chime", "sway", "gently near the bathroom door", False),
    ("Soap dispenser by the sinks", [11.5, 68.9, 14.6, 71.5],
     "The soap dispenser", "sit", "beside the sink", False),
    ("Mirror above the sinks", [1.6, 71.6, 10.4, 91.0],
     "The bathroom mirror", "hang", "above the row of sinks", False),
    ("Window blinds in the bathroom", [0.0, 88.5, 8.5, 100.0],
     "The window blinds", "let", "light into the bathroom", False),
    ("Cloud shapes outside the window", [4.4, 92.4, 7.5, 97.5],
     "The clouds outside", "drift", "past the bathroom window", True),
    ("Coat pegs on the wall", [0.0, 63.9, 4.6, 67.0],
     "The coat pegs", "wait", "empty on the wall", True),
    ("Rubbish bin lid", [21.8, 79.6, 24.3, 83.5],
     "The bin lid", "sit", "half open on the bin", False),
    ("Playground swing seen through the window", [55.7, 20.7, 61.2, 25.0],
     "The distant swing", "hang", "still in the playground", False),
    ("Toy car outside on the road", [56.4, 68.9, 60.1, 74.4],
     "The little orange car", "drive", "past the nursery window", False),
    ("Sunflower window decorations", [42.5, 43.3, 47.5, 48.3],
     "The sunflower decorations", "brighten", "the cafeteria window", True),
    ("Second row of sunflower decorations", [42.7, 60.5, 47.5, 65.4],
     "The second sunflower decoration", "sit", "on the window ledge", False),
    ("Storage jars on the kitchen shelf", [35.8, 0.4, 42.7, 8.7],
     "The row of jars", "hold", "flour and sugar for baking", True),
    ("Cutlery on the dining table", [61.3, 25.7, 64.1, 28.3],
     "The cutlery on the table", "wait", "beside the plates", True),
    ("Water jug on the dining table", [58.9, 34.5, 62.0, 37.4],
     "The water jug", "stand", "in the middle of the table", False),
    ("Chair pushed under the table", [64.1, 40.4, 68.7, 44.5],
     "The empty chair", "sit", "pushed under the table", False),
    ("Storage boxes stacked under the stairs", [50.8, 61.6, 57.1, 68.1],
     "The stacked storage boxes", "sit", "in the space under the stairs", True),
    ("Lower storage boxes", [61.5, 61.3, 63.6, 68.9],
     "The lower storage box", "hold", "spare toys and games", False),
    ("Vending machine coin slot", [46.8, 51.8, 49.3, 53.9],
     "The coin slot", "wait", "for a coin", False),
    ("Snack packets in the vending machine", [45.4, 52.5, 51.9, 57.5],
     "The snack packets", "line", "the shelves of the machine", True),
    ("Bottled drinks in a crate", [88.7, 84.7, 96.1, 91.9],
     "The bottled drinks", "stand", "in a plastic crate", True),
    ("Juice cartons stacked in a crate", [88.9, 74.7, 96.3, 82.4],
     "The juice cartons", "stack", "neatly in their crate", True),
    ("Tins stacked on the low table", [86.6, 61.3, 92.6, 68.9],
     "The stacked tins", "sit", "on the low table", True),
    ("Wall banner reading Happy Birthday", [40.7, 84.2, 45.6, 92.4],
     "The birthday banner", "hang", "on the party wall", False),
    ("Balloon decorations near the party table", [37.4, 78.9, 41.4, 82.4],
     "The blue balloon", "bob", "above the party table", False),
    ("Second balloon near the party table", [37.9, 89.3, 42.1, 92.6],
     "The second balloon", "float", "above the birthday table", False),
    ("Paper crown on the birthday child", [36.4, 92.4, 39.6, 96.1],
     "The paper crown", "sit", "on the birthday child's head", False),
    ("Plates of party food", [39.3, 88.4, 43.1, 94.5],
     "The plates of party food", "cover", "the birthday table", True),
    ("Boy's red backpack on the wheelchair", [40.9, 87.9, 46.6, 92.6],
     "The red backpack", "hang", "from the back of the wheelchair", False),
    ("Wooden blocks scattered on the floor", [88.4, 92.1, 95.4, 98.7],
     "The scattered wooden blocks", "lie", "across the playroom floor", True),
    ("Rug in the playroom", [78.5, 66.6, 100.0, 85.9],
     "The playroom rug", "cover", "the wooden floor", False),
    ("Window view of the garden tree", [40.9, 71.4, 47.5, 78.7],
     "The garden tree", "stand", "outside the cafeteria window", False),
    ("Bird on the garden fence", [42.4, 76.7, 44.5, 79.1],
     "The garden bird", "perch", "on the distant fence", False),
]
