# Page 6 - "Wildlife and the Animal House": woodland and a stream across the top
# left, a fenced animal park and duck pond through the middle, and a cutaway
# family house full of pets on the right, with a camper van being washed in the
# garage at the bottom right.
# Boxes read off the 12 tile grids produced by tiler.py (page percentages).
# (name, [ymin, xmin, ymax, xmax], subject, bare-infinitive verb, rest, plural)

P = [
    # --- top left: sky, eagles, wind turbines, the owl tree ---
    ("White cloud over the forest", [0.5, 0.0, 3.0, 4.0], "The white cloud", "drift", "above the green forest", False),
    ("Golden eagle", [4.2, 4.2, 13.6, 15.5], "The golden eagle", "glide", "over the treetops", False),
    ("Brown hawk", [3.0, 10.0, 7.4, 14.8], "The brown hawk", "hunt", "high above the valley", False),
    ("Tall wind turbine", [2.8, 15.3, 13.5, 20.4], "The tall wind turbine", "turn", "slowly in the breeze", False),
    ("Second wind turbine", [4.9, 20.2, 11.6, 24.1], "The second wind turbine", "stand", "on the distant ridge", False),
    ("Snowy mountain range", [7.0, 11.5, 13.2, 26.0], "The snowy mountain range", "stretch", "along the horizon", False),
    ("Barn owl on the branch", [21.6, 4.0, 27.0, 6.6], "The barn owl", "doze", "on the thick branch", False),
    ("Tawny owl", [20.0, 9.4, 26.5, 12.1], "The tawny owl", "watch", "the forest floor below", False),
    ("Red squirrel on the branch", [30.5, 10.5, 34.0, 13.1], "The red squirrel", "sit", "on the oak branch", False),
    ("Fallen log by the stream", [20.0, 18.2, 22.8, 21.6], "The fallen log", "lie", "beside the little stream", False),
    ("Pine marten on the log", [23.0, 18.8, 25.2, 20.2], "The pine marten", "creep", "along the mossy log", False),
    ("Badger on the tree trunk", [25.3, 15.8, 28.4, 19.2], "The badger", "climb", "over the fallen trunk", False),
    ("Grey heron by the rocks", [29.5, 21.0, 34.5, 23.8], "The grey heron", "wade", "between the pale rocks", False),
    ("White rocks in the stream", [29.8, 18.2, 32.1, 20.2], "The white rocks", "sit", "in the shallow stream", True),
    ("Thick oak branch", [24.5, 1.5, 28.2, 13.5], "The thick oak branch", "reach", "across the woodland", False),
    ("Dark spruce in the wood", [16.7, 16.4, 21.9, 19.2], "The dark spruce", "grow", "beside the stream", False),
    ("Yellow meadow", [13.5, 12.0, 15.5, 17.5], "The yellow meadow", "shine", "in the morning sun", False),

    # --- top middle left: the lookout tower, the dirt bike, the fox ---
    ("Third wind turbine", [5.3, 24.6, 12.1, 28.2], "The third wind turbine", "spin", "above the pine wood", False),
    ("Wooden lookout tower", [5.1, 29.1, 15.3, 35.4], "The wooden lookout tower", "rise", "above the treetops", False),
    ("Gliding hawk", [5.1, 39.6, 7.7, 43.8], "The gliding hawk", "circle", "over the forest", False),
    ("Flock of small birds", [3.5, 29.0, 5.2, 35.2], "The small birds", "fly", "across the blue sky", True),
    ("Dirt bike rider", [16.3, 28.0, 20.7, 31.6], "The dirt bike rider", "ride", "along the forest track", False),
    ("Red fox at the water", [22.1, 25.7, 25.3, 28.6], "The red fox", "drink", "from the cold stream", False),
    ("Flying barn owl", [20.5, 37.7, 26.0, 42.7], "The flying barn owl", "swoop", "between the tall spruces", False),
    ("Tall spruce in the clearing", [6.7, 33.4, 33.0, 39.3], "The tall spruce", "tower", "over the clearing", False),
    ("Small spruce sapling", [12.8, 40.5, 18.6, 43.0], "The small spruce sapling", "grow", "in the open grass", False),
    ("Bush beside the track", [22.6, 31.0, 24.4, 32.8], "The bush", "grow", "beside the forest track", False),
    ("Grey rocks in the stream", [25.6, 26.0, 28.8, 30.6], "The grey rocks", "block", "the running water", True),
    ("Little waterfall", [18.0, 25.2, 19.9, 26.4], "The little waterfall", "tumble", "over the rocks", False),
    ("Distant mountain ridge", [7.4, 28.5, 10.7, 43.6], "The distant mountain ridge", "fade", "into the morning haze", False),
    ("Tall spruce by the tower", [0.5, 45.0, 32.6, 51.0], "The tall spruce by the tower", "sway", "in the light wind", False),

    # --- top middle right: the geese, the lake, the city and the stork nest ---
    ("Leading Canada goose", [6.3, 56.4, 7.9, 59.2], "The leading Canada goose", "lead", "the flock south", False),
    ("Goose above the flock", [4.2, 60.0, 5.7, 62.6], "The goose above the flock", "beat", "its wings steadily", False),
    ("Goose in the middle", [6.7, 60.6, 8.9, 63.5], "The goose in the middle", "follow", "the others closely", False),
    ("Goose on the right", [5.6, 63.8, 7.3, 66.6], "The goose on the right", "honk", "over the lake", False),
    ("Snowy mountain peak", [6.5, 51.3, 10.1, 56.9], "The snowy mountain peak", "shine", "above the forest", False),
    ("Second mountain", [7.7, 57.2, 10.1, 61.2], "The second mountain", "stand", "behind the trees", False),
    ("Speckled osprey", [10.7, 55.3, 18.1, 59.7], "The speckled osprey", "soar", "above the woodland", False),
    ("White sailboat", [9.5, 65.2, 14.1, 67.2], "The white sailboat", "sail", "across the wide lake", False),
    ("Blue lake", [12.3, 61.8, 14.9, 74.8], "The blue lake", "glitter", "in front of the city", False),
    ("Observation tower", [4.4, 68.3, 10.0, 69.6], "The observation tower", "rise", "above the city", False),
    ("Flying stork", [11.6, 70.3, 14.9, 73.4], "The flying stork", "return", "to its nest", False),
    ("Big stork nest", [14.9, 72.3, 19.5, 76.3], "The big stork nest", "sit", "on the wooden platform", False),
    ("Colourful kite", [25.3, 50.4, 30.7, 55.3], "The colourful kite", "hang", "in the branches of the spruce", False),
    ("Red gabled roof", [18.6, 59.0, 31.0, 72.6], "The red gabled roof", "cover", "the family house", False),
    ("Attic window", [27.7, 63.4, 33.5, 65.0], "The attic window", "look", "out over the garden", False),
    ("Small spruce on the hill", [15.8, 66.8, 18.6, 68.6], "The small spruce on the hill", "grow", "near the lake shore", False),
    ("White exhibition hall", [9.3, 69.8, 10.9, 74.2], "The white exhibition hall", "stand", "beside the water", False),
    ("Cloud above the city", [1.4, 65.5, 4.2, 71.7], "The cloud above the city", "float", "over the tall towers", False),

    # --- top right: the skyline, the building site, the roof animals ---
    ("White office tower", [4.7, 74.9, 10.0, 76.9], "The white office tower", "rise", "above the city", False),
    ("Wide office block", [4.2, 78.3, 10.0, 81.9], "The wide office block", "stand", "in the city centre", False),
    ("Narrow office tower", [5.1, 84.5, 10.0, 85.9], "The narrow office tower", "stand", "among the other buildings", False),
    ("Pair of tall towers", [4.0, 87.1, 10.0, 89.9], "The pair of tall towers", "overlook", "the river", True),
    ("Dark grey buildings", [6.0, 90.2, 10.0, 93.0], "The dark grey buildings", "line", "the far bank", True),
    ("White stork by the pond", [11.6, 75.7, 15.0, 76.9], "The white stork", "stand", "at the edge of the pond", False),
    ("Village pond", [12.8, 72.9, 15.0, 82.2], "The village pond", "lie", "between the green fields", False),
    ("Wooden roof trusses", [10.9, 84.3, 16.7, 92.7], "The wooden roof trusses", "wait", "on the building site", True),
    ("House with a new red roof", [7.7, 87.7, 15.0, 94.8], "The house with a new red roof", "stand", "on the hill", False),
    ("Smoking chimney", [2.6, 97.0, 14.9, 98.4], "The smoking chimney", "send", "grey smoke into the sky", False),
    ("Red roof of the neighbours", [8.4, 94.8, 15.3, 100.0], "The red roof of the neighbours", "shine", "in the sunlight", False),
    ("Pigeon on the roof ridge", [18.6, 87.7, 21.6, 89.3], "The pigeon", "rest", "on the roof ridge", False),
    ("Pine marten on the roof", [18.1, 89.7, 21.2, 94.2], "The pine marten on the roof", "run", "along the grey tiles", False),
    ("Pigeon flying to the roof", [20.5, 79.7, 24.2, 82.2], "The flying pigeon", "land", "on the steep roof", False),
    ("Swallow above the roof", [22.3, 82.8, 27.0, 85.9], "The swallow", "dive", "past the roof tiles", False),
    ("White dormer", [20.5, 84.2, 35.0, 96.7], "The white dormer", "stick", "out of the grey roof", False),
    ("Dormer window with a cat", [27.4, 91.8, 34.2, 95.2], "The dormer window", "let", "the sunlight into the attic", False),
    ("Ginger cat in the window", [31.2, 93.2, 34.4, 94.9], "The ginger cat", "sleep", "in the sunny window", False),
    ("Dolphin poster", [27.4, 74.6, 31.6, 77.9], "The dolphin poster", "hang", "on the bedroom wall", False),

    # --- middle left: the old beech, the watchers, the boars and the deer ---
    ("Grey squirrel on the trunk", [34.7, 5.1, 37.0, 6.6], "The grey squirrel", "cling", "to the smooth trunk", False),
    ("Little marten on the bark", [32.6, 6.8, 34.4, 7.8], "The little marten", "peep", "around the tree trunk", False),
    ("Birdwatcher in green", [37.3, 7.9, 45.6, 11.7], "The birdwatcher in green", "hide", "behind the leafy branches", False),
    ("Boy with a camera", [42.2, 12.7, 45.6, 14.6], "The boy with a camera", "photograph", "the wild animals", False),
    ("Red squirrel on the low branch", [42.4, 2.6, 46.3, 4.7], "The red squirrel on the low branch", "nibble", "a hazelnut", False),
    ("Snowy owl", [45.6, 7.1, 53.6, 10.7], "The snowy owl", "perch", "on the broken branch", False),
    ("Old beech trunk", [30.3, 4.4, 79.0, 9.1], "The old beech trunk", "rise", "out of the meadow", False),
    ("Raccoon in the grass", [42.6, 15.1, 45.6, 16.9], "The raccoon", "search", "for food in the grass", False),
    ("Two raccoons together", [40.3, 15.7, 42.4, 18.2], "The two raccoons", "play", "near the stream", True),
    ("Badger by the water", [36.8, 21.5, 40.3, 24.7], "The badger by the water", "sniff", "along the river bank", False),
    ("Hedgehog in the meadow", [43.1, 19.1, 44.9, 21.7], "The hedgehog", "shuffle", "through the long grass", False),
    ("Wild boar", [45.2, 18.5, 49.8, 22.2], "The wild boar", "root", "in the soft earth", False),
    ("Striped boar piglets", [49.4, 13.9, 51.3, 16.7], "The striped boar piglets", "trot", "behind their mother", True),
    ("Piglets near the trees", [50.1, 20.4, 52.0, 24.1], "The piglets near the trees", "hunt", "for acorns", True),
    ("Hedgehog on the path", [53.8, 13.3, 55.4, 14.9], "The hedgehog on the path", "curl", "up in the sunshine", False),
    ("Red deer stag", [54.0, 18.5, 63.8, 21.6], "The red deer stag", "raise", "his great antlers", False),
    ("Deer doe", [57.7, 13.1, 64.9, 17.3], "The deer doe", "graze", "in the green meadow", False),
    ("Spotted fawn", [61.9, 16.2, 64.7, 18.3], "The spotted fawn", "stay", "close to its mother", False),
    ("Rabbit in the grass", [58.2, 9.9, 61.9, 11.4], "The rabbit in the grass", "nibble", "the fresh grass", False),
    ("Molehill in the meadow", [55.0, 23.5, 56.9, 25.1], "The molehill", "rise", "above the flat grass", False),
    ("Blue tit on the tree", [61.9, 3.7, 63.9, 4.8], "The blue tit", "hop", "along the low branch", False),
    ("Crow on the fence", [64.3, 22.5, 67.1, 23.9], "The crow", "sit", "on the wooden fence", False),
    ("Two butterflies", [38.9, 13.3, 40.4, 14.6], "The two butterflies", "flutter", "over the wild flowers", True),
    ("Bush by the old tree", [58.2, 0.9, 62.9, 3.5], "The bush by the old tree", "hide", "a rabbit burrow", False),

    # --- middle: the wrecked cars, the photographer, the fox and the anthill ---
    ("Heron in the shallow water", [30.8, 25.2, 34.9, 27.9], "The heron in the shallow water", "hunt", "for small fish", False),
    ("Grey badger by the stream", [38.6, 25.3, 42.0, 31.9], "The grey badger by the stream", "rest", "on the warm bank", False),
    ("Wild boar near the bank", [44.7, 23.9, 49.4, 27.9], "The wild boar near the bank", "dig", "in the soft mud", False),
    ("Piglets by the water", [49.8, 22.9, 52.0, 26.9], "The piglets by the water", "follow", "the old boar", True),
    ("Rusty old car body", [40.3, 31.6, 46.6, 35.3], "The rusty old car body", "rot", "in the long grass", False),
    ("Abandoned car chassis", [33.3, 40.5, 44.3, 45.0], "The abandoned car chassis", "lean", "against the spruce trees", False),
    ("Old car wheel", [40.8, 42.5, 44.3, 44.9], "The old car wheel", "hang", "from the broken axle", False),
    ("Worn car tyre", [45.6, 34.3, 47.4, 36.5], "The worn car tyre", "lie", "in the deep grass", False),
    ("Molehill near the wreck", [47.0, 29.7, 48.8, 31.6], "The molehill near the wreck", "mark", "a mole's tunnel", False),
    ("Photographer in a hat", [48.7, 32.9, 53.6, 35.9], "The photographer in a hat", "point", "his camera at the deer", False),
    ("Black bird flying low", [51.2, 28.6, 55.2, 30.3], "The black bird", "swoop", "over the meadow", False),
    ("Running red fox", [56.1, 31.1, 59.8, 36.7], "The running red fox", "cross", "the open field", False),
    ("Hopping hare", [58.0, 25.7, 61.0, 27.9], "The hopping hare", "bound", "through the grass", False),
    ("Boy on the tree stump", [49.6, 40.8, 56.3, 43.6], "The boy on the tree stump", "wave", "at the squirrel", False),
    ("Squirrel on the spruce", [45.6, 37.6, 48.5, 38.9], "The squirrel on the spruce", "scramble", "up the rough bark", False),
    ("Woodpecker on the trunk", [40.3, 46.7, 42.5, 47.7], "The woodpecker", "tap", "on the tree trunk", False),
    ("Big anthill", [46.8, 45.8, 51.5, 51.0], "The big anthill", "stand", "beside the fence", False),
    ("Long wooden fence", [56.3, 27.9, 67.5, 53.0], "The long wooden fence", "run", "around the animal park", False),
    ("Green bush in the field", [51.7, 32.0, 54.5, 34.6], "The green bush in the field", "shelter", "the little hare", False),
    ("Thick tree trunk by the fence", [30.3, 47.3, 51.2, 49.8], "The thick tree trunk", "stand", "beside the wooden fence", False),
    ("Tree stump", [54.5, 41.8, 56.7, 43.7], "The tree stump", "make", "a good seat", False),
    ("Cat by the fence", [62.9, 46.2, 67.0, 48.4], "The cat by the fence", "stretch", "in the warm sun", False),

    # --- middle right: the balcony, the porch roof and the pets indoors ---
    ("Man on the balcony", [38.4, 62.1, 47.5, 64.8], "The man on the balcony", "call", "to the children", False),
    ("Boy walking by the fence", [42.2, 57.5, 48.4, 59.6], "The boy walking by the fence", "fold", "his arms", False),
    ("Football on the grass", [48.0, 53.3, 49.9, 54.8], "The football", "lie", "on the green grass", False),
    ("Wooden fence by the house", [40.3, 48.5, 48.7, 62.4], "The wooden fence by the house", "separate", "the garden from the wood", False),
    ("Ginger cat on the roof", [55.0, 58.3, 58.2, 61.7], "The ginger cat on the roof", "walk", "along the metal ridge", False),
    ("Tabby cat on the roof edge", [50.8, 63.5, 53.2, 65.6], "The tabby cat", "creep", "over the roof edge", False),
    ("Two swallows", [56.1, 70.5, 58.7, 74.5], "The two swallows", "dart", "past the house", True),
    ("Pigeons on the roof edge", [60.1, 64.4, 62.5, 68.6], "The pigeons", "line", "up on the roof edge", True),
    ("Big aquarium", [40.5, 71.0, 47.5, 77.2], "The big aquarium", "fill", "the whole wall", False),
    ("Potted palm", [44.5, 68.4, 50.1, 71.2], "The potted palm", "stand", "beside the window", False),
    ("Two cats on the shelf", [49.6, 69.8, 51.3, 72.3], "The two cats on the shelf", "watch", "the fish", True),
    ("Beach ball in the attic", [35.2, 73.1, 37.4, 74.7], "The beach ball", "sit", "on the attic floor", False),
    ("Grey metal porch roof", [50.8, 51.0, 60.1, 70.1], "The grey metal porch roof", "shelter", "the front door", False),
    ("Cat in the porch doorway", [62.4, 55.5, 65.7, 57.3], "The cat in the doorway", "wait", "for its dinner", False),
    ("Wooden porch", [60.1, 53.6, 68.0, 60.3], "The wooden porch", "run", "along the front of the house", False),
    ("Grey rabbit by the fence", [61.2, 50.2, 63.0, 51.7], "The grey rabbit", "sit", "under the fence", False),

    # --- right: the attic playroom, the living room and the loft ---
    ("Guinea pig cage", [33.0, 75.4, 37.0, 80.3], "The guinea pig cage", "stand", "on the attic floor", False),
    ("White toy dog", [36.3, 77.7, 38.5, 80.5], "The white toy dog", "lie", "beside the cage", False),
    ("Green toy dinosaur", [34.5, 80.8, 38.0, 83.6], "The green toy dinosaur", "guard", "the play corner", False),
    ("Blue floor cushions", [31.0, 81.3, 39.1, 85.1], "The blue floor cushions", "cover", "the attic floor", True),
    ("Pine marten on the tiles", [31.5, 85.6, 37.5, 88.4], "The pine marten on the tiles", "scramble", "up the steep roof", False),
    ("Swallow near the window", [39.1, 93.3, 40.9, 95.2], "The swallow near the window", "flit", "past the glass", False),
    ("Boy in a blue shirt", [41.0, 74.6, 51.2, 76.7], "The boy in a blue shirt", "watch", "the fish tank", False),
    ("Potted palm tree", [39.6, 77.6, 48.0, 79.8], "The potted palm tree", "grow", "in the living room", False),
    ("Girl in pink pyjamas", [41.0, 80.2, 50.8, 82.7], "The girl in pink pyjamas", "reach", "for the plant", False),
    ("Blue armchair", [43.6, 82.2, 49.8, 86.7], "The blue armchair", "face", "the window", False),
    ("Blue sofa", [48.9, 79.9, 54.5, 84.0], "The blue sofa", "stand", "in the middle of the room", False),
    ("Wooden coffee table", [49.4, 77.1, 52.2, 80.1], "The wooden coffee table", "sit", "on the yellow rug", False),
    ("Yellow rug", [48.0, 74.0, 53.1, 79.7], "The yellow rug", "cover", "the living room floor", False),
    ("Green plant behind the sofa", [43.6, 86.7, 47.5, 88.8], "The green plant behind the sofa", "lean", "towards the light", False),
    ("Plant on the cabinet", [55.4, 81.9, 58.2, 83.2], "The plant on the cabinet", "sit", "above the drawers", False),
    ("Wooden cabinet", [56.8, 80.6, 62.9, 82.3], "The wooden cabinet", "hold", "the pet food", False),
    ("Girl kneeling by the tank", [61.2, 81.4, 67.0, 84.0], "The girl kneeling by the tank", "feed", "her pet lizard", False),
    ("Glass terrarium", [61.9, 77.7, 66.6, 81.6], "The glass terrarium", "stand", "on the low table", False),
    ("Fish tank on the shelf", [58.2, 85.6, 62.4, 88.0], "The fish tank on the shelf", "glow", "in the dark room", False),
    ("Green lizard", [60.1, 82.9, 61.9, 85.1], "The green lizard", "bask", "under the warm lamp", False),
    ("Boy at the roof window", [56.8, 91.3, 61.0, 93.6], "The boy at the roof window", "look", "down at the garden", False),
    ("Large skylight", [48.0, 88.2, 66.6, 97.9], "The large skylight", "let", "sunshine into the loft", False),
    ("Grey cat on the skylight", [52.6, 93.6, 55.5, 95.6], "The grey cat", "climb", "across the skylight", False),

    # --- bottom left: the beekeeper, the hutch and the open manhole ---
    ("Beekeeper in a white suit", [75.6, 6.2, 87.0, 9.4], "The beekeeper in a white suit", "lift", "a frame from the hive", False),
    ("Beehive by the tree", [81.1, 2.2, 88.6, 6.3], "The beehive by the tree", "hum", "with busy bees", False),
    ("Second beehive", [80.7, 10.0, 88.1, 14.0], "The second beehive", "stand", "in the sunny corner", False),
    ("Honeycomb frame", [80.4, 7.9, 82.2, 10.3], "The honeycomb frame", "drip", "with fresh honey", False),
    ("Red rabbit hutch", [66.3, 19.5, 73.7, 28.0], "The red rabbit hutch", "stand", "at the top of the field", False),
    ("Bird above the fence", [67.9, 15.6, 70.1, 17.1], "The bird above the fence", "flit", "over the meadow", False),
    ("Bird on the fence rail", [71.4, 16.1, 73.7, 17.7], "The bird on the fence rail", "sing", "in the sunshine", False),
    ("Rabbit under the hutch", [77.9, 19.8, 81.8, 21.1], "The rabbit under the hutch", "nibble", "a dandelion leaf", False),
    ("Rabbit by the fence post", [73.7, 22.8, 77.2, 24.5], "The rabbit by the fence post", "wash", "its long ears", False),
    ("Man in a blue hat", [81.1, 16.5, 90.4, 19.7], "The man in a blue hat", "hold", "his dog's lead", False),
    ("Spotted Great Dane", [84.6, 20.2, 91.1, 25.5], "The spotted Great Dane", "sniff", "at the fence", False),
    ("Orange traffic cone", [93.0, 5.4, 95.9, 6.7], "The orange traffic cone", "stand", "on the grey drive", False),
    ("Second traffic cone", [91.1, 11.0, 94.2, 12.3], "The second traffic cone", "warn", "the drivers", False),
    ("Open manhole", [93.0, 7.1, 96.2, 14.4], "The open manhole", "lead", "down into the drains", False),
    ("Worker in a yellow helmet", [93.5, 11.0, 95.4, 12.5], "The worker in a yellow helmet", "climb", "out of the manhole", False),
    ("Rat by the drain", [92.3, 17.5, 94.1, 19.2], "The rat by the drain", "scurry", "across the concrete", False),
    ("Rat near the manhole", [93.8, 15.3, 95.4, 16.9], "The rat near the manhole", "sniff", "the cold air", False),
    ("Fern by the tree", [66.3, 0.9, 73.7, 3.5], "The fern by the tree", "grow", "in the deep shade", False),
    ("Bush behind the hives", [81.4, 0.0, 87.0, 2.9], "The bush behind the hives", "shelter", "the beehives", False),

    # --- bottom middle left: the rabbit run and the duck pond ---
    ("Rabbit near the hutch", [73.2, 25.4, 75.9, 26.9], "The rabbit near the hutch", "stand", "on its back legs", False),
    ("Brown rabbit in the grass", [75.6, 24.6, 78.1, 26.3], "The brown rabbit", "chew", "a blade of grass", False),
    ("Rabbit by the wire fence", [73.0, 28.2, 75.9, 29.7], "The rabbit by the wire fence", "hop", "towards the pond", False),
    ("Grey and white rabbit", [75.6, 26.6, 77.9, 28.4], "The grey and white rabbit", "sit", "quietly in the sun", False),
    ("Rabbit near the path", [75.1, 29.1, 77.9, 30.7], "The rabbit near the path", "sleep", "on the warm ground", False),
    ("Running guinea pig", [70.2, 34.7, 72.5, 36.9], "The running guinea pig", "hurry", "across the lawn", False),
    ("White goose on the bank", [63.5, 36.3, 68.7, 38.9], "The white goose on the bank", "waddle", "towards the pond", False),
    ("Duck on the rock", [70.0, 40.2, 73.0, 43.1], "The duck on the rock", "preen", "its feathers", False),
    ("Duck at the water's edge", [77.0, 35.1, 78.5, 37.7], "The duck at the water's edge", "paddle", "into the pond", False),
    ("Ducks on the pond", [79.5, 30.9, 82.5, 35.6], "The ducks on the pond", "swim", "in a little line", True),
    ("Kingfisher on the post", [80.2, 28.6, 81.9, 30.0], "The kingfisher on the post", "watch", "the water for fish", False),
    ("Swan spreading its wings", [77.0, 37.7, 84.6, 44.2], "The swan", "spread", "its great white wings", False),
    ("Goose on the water", [82.3, 43.6, 85.8, 46.8], "The goose on the water", "float", "beside the reeds", False),
    ("Turtle on the stone", [77.2, 46.7, 79.1, 49.2], "The turtle on the stone", "sunbathe", "beside the pond", False),
    ("Tall bulrushes", [65.5, 41.8, 77.2, 46.1], "The tall bulrushes", "grow", "at the edge of the pond", True),
    ("Reeds in the water", [76.3, 39.7, 81.8, 42.5], "The reeds in the water", "sway", "in the breeze", True),
    ("White stones round the pond", [66.3, 37.7, 71.1, 41.2], "The white stones", "edge", "the garden pond", True),
    ("Frog in the pond", [88.4, 47.0, 90.0, 48.5], "The frog", "sit", "on a lily pad", False),
    ("Dragonfly over the water", [88.6, 43.6, 89.8, 45.2], "The dragonfly", "hover", "above the still water", False),
    ("Water lily flower", [84.9, 49.3, 86.3, 50.7], "The water lily flower", "open", "on the pond", False),
    ("Brown puppy", [89.0, 24.9, 92.1, 26.4], "The brown puppy", "roll", "in the grass", False),
    ("Duck on the grass", [91.4, 30.8, 94.9, 32.9], "The duck on the grass", "lead", "her ducklings home", False),
    ("Little ducklings", [93.9, 32.6, 95.4, 34.4], "The little ducklings", "waddle", "after their mother", True),
    ("Grey rock by the fence", [85.6, 27.6, 89.9, 32.2], "The grey rock", "lie", "beside the wooden fence", False),
    ("Bush by the fence post", [82.3, 27.4, 85.1, 29.8], "The bush by the fence post", "grow", "next to the path", False),
    ("Garden pond", [70.0, 36.5, 94.0, 52.0], "The garden pond", "sparkle", "in the sunshine", False),

    # --- bottom middle right: the dogs, the kennel and the front door ---
    ("Woman kneeling on the lawn", [70.7, 51.2, 76.7, 53.7], "The woman kneeling on the lawn", "brush", "the big dog", False),
    ("Brown and white dog", [71.6, 53.2, 75.4, 55.9], "The brown and white dog", "enjoy", "the brushing", False),
    ("Red dog kennel", [70.2, 56.3, 74.9, 59.3], "The red dog kennel", "stand", "on the green lawn", False),
    ("Red toolbox", [76.0, 53.0, 78.6, 54.8], "The red toolbox", "sit", "on the grass", False),
    ("Grey dog bowl", [75.7, 56.2, 77.3, 57.7], "The grey dog bowl", "wait", "by the kennel", False),
    ("Yellow Labrador", [78.1, 57.5, 83.5, 62.4], "The yellow Labrador", "pull", "hard on the lead", False),
    ("Man in a blue shirt", [77.2, 65.2, 85.8, 67.6], "The man in a blue shirt", "hold", "several dog leads", False),
    ("Brown dog on the lawn", [77.2, 70.6, 80.1, 73.4], "The brown dog on the lawn", "run", "towards the house", False),
    ("Big red retriever", [86.3, 58.7, 91.1, 65.2], "The big red retriever", "bark", "at the other dogs", False),
    ("Large yellow dog", [86.0, 68.6, 91.1, 72.0], "The large yellow dog", "stand", "in the middle of the path", False),
    ("Small dog on a lead", [88.1, 67.5, 91.1, 68.8], "The small dog on a lead", "yap", "at the big dogs", False),
    ("Fluffy white dog", [89.5, 72.2, 92.1, 73.9], "The fluffy white dog", "trot", "beside the camper", False),
    ("Pack of little dogs", [91.8, 65.4, 95.3, 69.2], "The little dogs", "tangle", "their leads together", True),
    ("Two dogs sniffing", [91.8, 57.6, 95.3, 61.4], "The two dogs", "sniff", "at the grass", True),
    ("Lily pads on the pond", [85.6, 49.0, 88.0, 53.6], "The lily pads", "float", "on the still water", True),
    ("Frog on the lily pad", [86.0, 47.9, 87.5, 49.3], "The frog on the lily pad", "wait", "for a fly", False),
    ("Yellow ducklings", [86.5, 55.8, 88.1, 57.1], "The yellow ducklings", "paddle", "near the bank", True),
    ("Butterfly over the pond", [86.0, 54.3, 87.7, 55.5], "The butterfly", "flutter", "above the water", False),
    ("Green reeds by the water", [79.0, 51.8, 84.2, 56.9], "The green reeds by the water", "hide", "the ducklings", True),
    ("White front door", [64.0, 62.3, 73.7, 65.3], "The white front door", "open", "onto the garden", False),
    ("Concrete steps", [73.7, 60.3, 77.2, 65.2], "The concrete steps", "lead", "up to the front door", True),
    ("Flower box with pink flowers", [67.7, 66.4, 71.1, 72.6], "The flower box", "hang", "under the window", False),
    ("Kitchen window", [64.5, 68.6, 68.9, 71.7], "The kitchen window", "look", "out over the drive", False),

    # --- bottom right: the garage, the camper van and the dog walker ---
    ("Green plant in the loft", [65.3, 88.7, 70.9, 91.9], "The green plant in the loft", "grow", "beside the armchair", False),
    ("Blue armchair in the loft", [66.0, 86.8, 70.9, 93.0], "The blue armchair in the loft", "stand", "under the sloping roof", False),
    ("Yellow delivery van", [75.3, 74.8, 89.7, 82.8], "The yellow delivery van", "park", "inside the open garage", False),
    ("White camper van", [77.0, 79.7, 100.0, 96.1], "The white camper van", "wait", "in front of the garage", False),
    ("Woman washing the camper", [81.4, 82.8, 91.1, 85.7], "The woman washing the camper", "clean", "the windscreen", False),
    ("Man in an orange cap", [84.9, 90.5, 94.4, 93.1], "The man in an orange cap", "polish", "the side of the camper", False),
    ("Metal bucket", [93.9, 91.0, 96.3, 92.8], "The metal bucket", "stand", "on the concrete", False),
    ("Blue toolbox", [94.2, 93.1, 96.1, 95.1], "The blue toolbox", "sit", "beside the bucket", False),
    ("Dog on the camper roof", [77.0, 87.7, 79.3, 90.8], "The dog on the camper roof", "sleep", "in the warm sun", False),
    ("Cat by the toolbox", [92.8, 93.6, 94.9, 94.7], "The cat by the toolbox", "watch", "the busy dogs", False),
    ("Dog walker in an orange vest", [86.3, 74.9, 94.4, 76.9], "The dog walker in an orange vest", "gather", "the leads in her hand", False),
    ("White poodle", [87.0, 76.8, 91.1, 78.7], "The white poodle", "wait", "beside the drive", False),
    ("Two small white dogs", [88.4, 78.0, 91.6, 80.1], "The two small white dogs", "pull", "in different directions", True),
    ("Beagle on the drive", [92.8, 76.6, 95.8, 79.2], "The beagle on the drive", "follow", "a scent", False),
    ("Red watering can", [88.4, 82.4, 90.9, 83.4], "The red watering can", "stand", "by the camper door", False),
    ("Camper windscreen", [84.9, 85.6, 91.1, 89.3], "The camper windscreen", "shine", "after the wash", False),
    ("Camper wheel", [96.0, 86.2, 100.0, 89.4], "The camper wheel", "rest", "on the concrete drive", False),
    ("Van radiator grille", [81.8, 75.4, 86.0, 80.1], "The van radiator grille", "gleam", "in the shade", False),
]
