# Page 8 — cutaway apartment building with the street outside.
# Boxes read straight off the tiler grid labels, one block per tile.
P = [

# TILE r0c0
("Red hot air balloon", [1.2, 6.4, 5.2, 8.6], "The red hot air balloon", "float", "high above the green hills", False),
("Blue hot air balloon", [1.5, 11.6, 4.5, 13.1], "The blue hot air balloon", "drift", "across the morning sky", False),
("Flying stork", [1.3, 16.5, 4.0, 19.3], "The flying stork", "glide", "over the countryside", False),
("Pink country house", [7.7, 10.2, 12.7, 15.1], "The pink country house", "stand", "among the trees", False),
("Yellow cottage on the hill", [9.4, 4.1, 12.7, 6.6], "The yellow cottage on the hill", "sit", "above the village", False),
("White cottage by the trees", [9.9, 6.6, 12.9, 10.2], "The white cottage by the trees", "look", "over the meadow", False),
("Little stream", [12.7, 7.8, 15.2, 13.9], "The little stream", "wind", "through the fields", False),
("Tall pine tree", [6.4, 11.4, 9.9, 12.6], "The tall pine tree", "grow", "on the green hill", False),
("Bare tree by the pink house", [9.9, 15.7, 13.3, 17.3], "The bare tree by the pink house", "lean", "towards the river", False),
("White cat in the attic", [12.9, 21.6, 14.2, 23.3], "The white cat in the attic", "sleep", "beside the old boxes", False),
("Black cat on the roof", [21.7, 2.7, 24.7, 4.6], "The black cat on the roof", "creep", "along the blue wall", False),
("Oval attic window", [19.9, 5.7, 23.6, 7.2], "The oval attic window", "face", "the quiet street", False),
("Small bird on the gutter", [23.3, 15.4, 24.5, 16.2], "The small bird on the gutter", "sing", "outside the balcony", False),
("Purple flowers in the balcony box", [25.2, 13.1, 28.2, 16.6], "The purple flowers in the balcony box", "bloom", "in the warm sunshine", True),
("White balcony railing", [27.3, 13.2, 31.5, 16.8], "The white balcony railing", "curve", "around the small balcony", False),
("Balcony glass door", [16.4, 17.4, 34.3, 22.8], "The balcony glass door", "open", "onto the balcony", False),

# TILE r0c1
("Attic window", [0.0, 29.6, 4.7, 32.8], "The attic window", "let", "light into the loft", False),
("Small cardboard box", [9.2, 26.2, 10.8, 28.2], "The small cardboard box", "sit", "on the bigger box", False),
("Big cardboard box", [10.6, 25.2, 13.3, 28.5], "The big cardboard box", "wait", "under the sloping roof", False),
("Jester puppet", [1.3, 41.0, 6.4, 42.2], "The jester puppet", "hang", "from its tangled strings", False),
("Green crocodile puppet", [4.3, 40.4, 8.0, 42.8], "The green crocodile puppet", "dangle", "above the desk", False),
("Sailor doll on the box", [6.8, 37.0, 10.8, 38.4], "The sailor doll on the box", "rest", "beside the red blanket", False),
("Woman at the attic desk", [2.9, 43.2, 13.3, 45.3], "The woman at the attic desk", "paint", "a wooden puppet", False),
("Red office chair", [5.9, 42.2, 13.8, 44.7], "The red office chair", "stand", "in front of the workbench", False),
("Little wooden doll", [4.3, 45.6, 8.7, 47.2], "The little wooden doll", "stand", "on the workbench", False),
("Chest of drawers in the attic", [7.5, 38.2, 12.7, 40.4], "The chest of drawers in the attic", "hold", "the puppet maker's tools", False),
("Attic workbench", [8.7, 46.5, 13.3, 49.8], "The attic workbench", "carry", "brushes and paint pots", False),
("Red blanket in the attic", [9.9, 34.7, 12.2, 37.0], "The red blanket in the attic", "lie", "over the old bench", False),
("Blue cup on the desk", [4.7, 38.7, 6.8, 39.4], "The blue cup on the desk", "hold", "the paintbrushes", False),
("Framed family photo", [17.5, 25.3, 21.5, 27.6], "The framed family photo", "hang", "above the red sofa", False),
("Red sofa", [23.8, 21.6, 30.6, 31.2], "The red sofa", "fill", "one side of the living room", False),
("Yellow cushion on the sofa", [26.4, 22.9, 28.7, 24.8], "The yellow cushion on the sofa", "sit", "in the corner of the seat", False),
("Dark wooden chest", [29.3, 20.8, 33.8, 27.8], "The dark wooden chest", "stand", "in front of the red sofa", False),
("Blue bowl on the chest", [29.6, 25.2, 30.6, 26.4], "The blue bowl on the chest", "hold", "the house keys", False),
("Green building blocks", [31.5, 27.9, 32.7, 29.0], "The green building blocks", "lie", "on the living room floor", True),
("White football", [31.3, 29.6, 32.9, 30.7], "The white football", "roll", "across the floor", False),
("Grey cat by the table", [29.6, 32.7, 32.9, 34.2], "The grey cat by the table", "wait", "for a piece of breakfast", False),
("Glass display cabinet", [17.3, 31.3, 31.9, 34.1], "The glass display cabinet", "show", "the family china", False),
("Spider plant on the cabinet", [15.7, 31.8, 18.2, 35.0], "The spider plant on the cabinet", "spill", "over the wooden top", False),
("Yellow hanging lamp", [15.4, 36.1, 21.3, 37.5], "The yellow hanging lamp", "hang", "above the dining table", False),
("Boy at the breakfast table", [24.0, 32.1, 30.6, 33.9], "The boy at the breakfast table", "reach", "for the bread", False),
("Dining table", [25.7, 34.1, 33.3, 39.6], "The dining table", "hold", "the family breakfast", False),
("Red dining chair", [26.4, 35.0, 33.3, 37.5], "The red dining chair", "stand", "beside the table", False),
("White plate", [24.0, 36.2, 25.9, 37.5], "The white plate", "wait", "on the tablecloth", False),
("Green teapot", [25.2, 34.4, 26.6, 35.5], "The green teapot", "steam", "on the breakfast table", False),
("Red mug", [25.2, 37.8, 26.6, 38.5], "The red mug", "stand", "next to the plate", False),
("Father in the striped shirt", [18.5, 40.1, 33.3, 43.5], "The father in the striped shirt", "carry", "a cup of coffee", False),
("Coffee machine", [21.7, 43.5, 26.8, 45.3], "The coffee machine", "brew", "the morning coffee", False),
("Kitchen wall cupboard", [17.1, 46.5, 23.1, 48.7], "The kitchen wall cupboard", "store", "the plates and glasses", False),
("White cooker", [26.4, 47.8, 32.4, 49.8], "The white cooker", "warm", "the kitchen", False),
("Kettle on the stove", [22.7, 48.2, 25.2, 49.2], "The kettle on the stove", "whistle", "on the hot ring", False),
("Blue dog bowl", [32.4, 47.8, 33.4, 48.8], "The blue dog bowl", "sit", "on the kitchen floor", False),
("Tall yellow kitchen cupboard", [16.8, 41.2, 26.4, 43.5], "The tall yellow kitchen cupboard", "stand", "beside the fridge", False),

# TILE r0c2
("Wooden crate with a red cloth", [10.3, 50.2, 12.4, 52.8], "The wooden crate with a red cloth", "hold", "the summer things", False),
("Orange surfboard", [4.7, 54.6, 13.8, 55.8], "The orange surfboard", "lean", "against the attic wall", False),
("Picture of a green frog", [0.6, 58.2, 4.0, 60.3], "The picture of a green frog", "hang", "above the yellow armchair", False),
("Yellow armchair", [6.6, 56.8, 13.8, 62.9], "The yellow armchair", "wait", "in the corner of the room", False),
("Rag doll on the armchair", [8.0, 57.8, 12.0, 60.8], "The rag doll on the armchair", "lie", "across the soft cushion", False),
("Big potted tree", [0.6, 61.7, 12.0, 66.0], "The big potted tree", "reach", "up to the ceiling", False),
("Round side table", [11.5, 64.0, 13.8, 66.9], "The round side table", "stand", "next to the armchair", False),
("Little table lamp", [9.4, 65.2, 11.7, 66.0], "The little table lamp", "glow", "on the side table", False),
("Television set", [5.9, 66.8, 10.6, 70.3], "The television set", "show", "the morning news", False),
("Oval bathroom mirror", [16.1, 51.4, 18.2, 52.6], "The oval bathroom mirror", "hang", "above the washbasin", False),
("White towels on the shelf", [17.3, 50.6, 20.8, 52.9], "The white towels on the shelf", "wait", "beside the mirror", True),
("Toothbrushes in the glass", [21.7, 50.9, 24.0, 53.5], "The toothbrushes in the glass", "stand", "on the bathroom shelf", True),
("White washbasin", [25.2, 50.6, 28.0, 53.8], "The white washbasin", "fill", "with warm water", False),
("Shower head", [18.0, 55.7, 19.4, 56.8], "The shower head", "drip", "over the bathtub", False),
("Yellow shower curtain", [16.6, 57.8, 28.7, 58.9], "The yellow shower curtain", "hang", "beside the bath", False),
("Blue bathtub", [26.4, 55.1, 29.1, 58.0], "The blue bathtub", "wait", "for the evening bath", False),
("Yellow bath towel", [25.2, 54.8, 29.6, 55.8], "The yellow bath towel", "hang", "on the towel rail", False),
("Yellow rubber duck", [27.1, 56.8, 28.2, 57.7], "The yellow rubber duck", "float", "in the bathtub", False),
("White toilet", [28.7, 57.8, 32.4, 59.2], "The white toilet", "stand", "in the corner of the bathroom", False),
("Yellow star on the nursery wall", [20.3, 62.3, 22.2, 63.4], "The yellow star on the nursery wall", "shine", "above the cot", False),
("Yellow moon on the nursery wall", [23.3, 60.6, 25.2, 61.7], "The yellow moon on the nursery wall", "watch", "over the sleeping baby", False),
("Children's wardrobe", [17.1, 63.8, 25.0, 68.2], "The children's wardrobe", "hold", "the little clothes", False),
("Big panda teddy", [21.3, 68.6, 25.0, 70.8], "The big panda teddy", "sit", "on top of the shelf", False),
("Wooden cot", [26.4, 60.2, 33.3, 66.0], "The wooden cot", "stand", "under the painted stars", False),
("Baby in the cot", [27.3, 62.5, 29.6, 64.2], "The baby in the cot", "wake", "up from a long nap", False),
("Toddler in the red dungarees", [25.2, 65.5, 33.3, 66.9], "The toddler in the red dungarees", "peep", "into the cot", False),
("Parent leaning over the cot", [23.3, 66.9, 33.3, 69.7], "The parent leaning over the cot", "lift", "the baby out", False),
("Small nursery picture", [17.3, 69.4, 19.9, 70.6], "The small nursery picture", "brighten", "the nursery wall", False),
("Bed with the striped quilt", [26.4, 70.3, 30.6, 72.5], "The bed with the striped quilt", "wait", "in the next room", False),
("Red slipper", [32.4, 65.1, 33.4, 66.0], "The red slipper", "lie", "on the nursery floor", False),

# TILE r0c3
("Man carrying a box", [0.6, 77.2, 13.3, 79.6], "The man carrying a box", "climb", "the stairs to his flat", False),
("Cardboard box on the landing", [10.3, 75.2, 13.8, 77.3], "The cardboard box on the landing", "wait", "by the open door", False),
("Black stair railing", [7.1, 79.2, 13.3, 80.2], "The black stair railing", "guard", "the top of the stairs", False),
("White chimney", [0.6, 91.4, 4.5, 92.6], "The white chimney", "stand", "on the grey roof", False),
("Half-moon attic window", [3.8, 96.3, 5.7, 98.5], "The half-moon attic window", "look", "out over the town", False),
("Man on the balcony", [9.6, 92.4, 17.5, 94.9], "The man on the balcony", "drink", "his morning coffee", False),
("Blue mug", [14.7, 91.1, 16.1, 92.0], "The blue mug", "steam", "in the cool air", False),
("Ginger cat in his arms", [13.8, 93.5, 16.6, 94.9], "The ginger cat in his arms", "purr", "against his jumper", False),
("Big balcony window", [9.4, 91.7, 16.4, 99.4], "The big balcony window", "open", "onto the balcony", False),
("Window with pink curtains", [23.3, 90.6, 30.6, 94.9], "The window with pink curtains", "face", "the busy street", False),
("Cat asleep on the windowsill", [28.0, 91.7, 29.6, 93.8], "The cat asleep on the windowsill", "doze", "in the sunshine", False),
("Ticket machine on the post", [26.1, 89.5, 32.4, 90.7], "The ticket machine on the post", "wait", "for the next driver", False),
("Palm plant in the pot", [22.2, 73.1, 32.9, 75.8], "The palm plant in the pot", "stand", "by the flat door", False),
("Grey staircase", [23.1, 78.5, 33.3, 82.1], "The grey staircase", "lead", "up to the next floor", False),
("Open flat door", [15.2, 75.0, 32.4, 76.9], "The open flat door", "let", "the neighbours in", False),
("Brown bird on the wall", [26.4, 84.3, 28.9, 86.4], "The brown bird on the wall", "flutter", "beside the ivy", False),
("Climbing ivy", [26.8, 86.1, 33.4, 88.6], "The climbing ivy", "climb", "up the yellow wall", False),

# TILE r1c0
("Red parrot at the window", [33.8, 0.7, 38.0, 2.7], "The red parrot at the window", "watch", "the street below", False),
("Old man at the window", [30.7, 7.8, 36.2, 9.5], "The old man at the window", "lean", "out for some fresh air", False),
("House number sign", [42.9, 5.5, 43.9, 6.3], "The house number sign", "show", "the number of the house", False),
("White letterbox", [48.7, 5.4, 50.8, 6.6], "The white letterbox", "hang", "beside the front door", False),
("Grey front door", [44.5, 1.8, 58.7, 4.8], "The grey front door", "open", "onto the pavement", False),
("Grandmother in the pink jumper", [47.6, 1.4, 58.7, 4.3], "The grandmother in the pink jumper", "say", "goodbye at the door", False),
("Little girl in the red dress", [52.2, 4.0, 58.7, 6.1], "The little girl in the red dress", "skip", "along the pavement", False),
("Yellow pull-along duck", [54.5, 6.1, 56.4, 7.2], "The yellow pull-along duck", "follow", "the little girl", False),
("Boy in the striped jumper", [49.4, 7.8, 56.4, 10.2], "The boy in the striped jumper", "wave", "at his grandmother", False),
("Woman beside the red car", [43.4, 11.4, 50.8, 13.9], "The woman beside the red car", "load", "her shopping into the boot", False),
("Bunch of pink flowers", [47.3, 7.7, 49.9, 9.8], "The bunch of pink flowers", "brighten", "the front garden", False),
("Red car", [46.2, 9.2, 60.6, 15.1], "The red car", "wait", "at the kerb", False),
("Open car door", [48.3, 10.8, 55.9, 13.9], "The open car door", "swing", "out over the road", False),
("Boy on the bicycle", [60.7, 8.1, 69.0, 11.4], "The boy on the bicycle", "ride", "down the busy road", False),
("Standard lamp", [39.7, 18.0, 48.8, 19.3], "The standard lamp", "stand", "behind the sofa", False),
("Potted plant on the wall shelf", [40.1, 19.4, 42.7, 21.0], "The potted plant on the wall shelf", "trail", "down the wall", False),
("Picture of the desert", [36.6, 23.6, 41.0, 29.5], "The picture of the desert", "hang", "above the green sofa", False),
("Television in the living room", [43.8, 15.6, 48.9, 18.2], "The television in the living room", "stand", "on its wooden cabinet", False),
("Wooden TV cabinet", [48.7, 15.4, 53.1, 18.2], "The wooden TV cabinet", "hold", "the newspapers", False),
("Blue sofa with the green blanket", [43.1, 18.8, 52.6, 29.0], "The blue sofa with the green blanket", "face", "the television", False),
("Round coffee table", [49.4, 22.2, 52.9, 26.8], "The round coffee table", "stand", "on the green carpet", False),
("Vase of red flowers", [47.1, 23.6, 49.9, 25.0], "The vase of red flowers", "sit", "on the coffee table", False),
("Picture of the lighthouse", [58.7, 16.0, 64.5, 20.2], "The picture of the lighthouse", "hang", "over the blue sofa", False),
("Wooden display cabinet", [57.1, 20.8, 68.0, 25.3], "The wooden display cabinet", "keep", "the best glasses safe", False),
("Boy in the yellow T-shirt", [63.4, 24.8, 69.5, 26.8], "The boy in the yellow T-shirt", "turn", "the television on", False),

# TILE r1c1
("Trailing plant on the picture frame", [37.1, 27.9, 39.9, 29.0], "The trailing plant on the picture frame", "hang", "over the desert picture", False),
("Old woman in the wheelchair", [42.0, 27.0, 51.9, 30.1], "The old woman in the wheelchair", "point", "at the television", False),
("Wheelchair", [47.3, 29.3, 52.9, 31.8], "The wheelchair", "stand", "beside the sofa", False),
("Nurse in the white uniform", [38.5, 30.8, 51.9, 32.8], "The nurse in the white uniform", "look", "after the old woman", False),
("Pink slippers", [50.8, 27.3, 51.9, 29.2], "The pink slippers", "rest", "on the footplate", True),
("Shelf with the storage jars", [36.6, 34.7, 39.2, 38.2], "The shelf with the storage jars", "hang", "on the kitchen wall", False),
("Long trailing plant", [36.4, 37.0, 42.0, 39.0], "The long trailing plant", "hang", "down from the shelf", False),
("Open kitchen door", [36.1, 39.5, 53.1, 42.8], "The open kitchen door", "stand", "wide open", False),
("Woman pouring the tea", [38.0, 41.9, 51.2, 44.7], "The woman pouring the tea", "pour", "the tea into a cup", False),
("Pink teapot", [44.8, 41.3, 46.7, 42.8], "The pink teapot", "steam", "over the table", False),
("Green jug", [45.7, 40.5, 47.1, 41.6], "The green jug", "stand", "in the middle of the table", False),
("Wooden kitchen table", [46.4, 37.0, 54.1, 44.7], "The wooden kitchen table", "fill", "the middle of the room", False),
("Blue padded chair", [44.8, 34.8, 54.1, 37.3], "The blue padded chair", "wait", "at the end of the table", False),
("Wooden kitchen chair", [46.4, 42.7, 54.1, 45.9], "The wooden kitchen chair", "stand", "beside the table", False),
("Blue bowl on the table", [47.3, 40.4, 48.5, 41.7], "The blue bowl on the table", "hold", "the breakfast fruit", False),
("Tall glass", [47.6, 39.6, 48.7, 40.4], "The tall glass", "catch", "the light on the table", False),
("White fridge", [38.0, 46.4, 53.1, 49.3], "The white fridge", "hum", "in the corner of the kitchen", False),
("Red heart magnet", [44.5, 45.9, 45.5, 46.5], "The red heart magnet", "stick", "to the fridge door", False),
("Smiley face magnet", [45.7, 47.5, 46.9, 48.2], "The smiley face magnet", "hold", "a shopping list", False),
("Jars on top of the fridge", [36.4, 46.8, 38.7, 49.6], "The jars on top of the fridge", "wait", "out of reach", True),
("Hanging ivy in the living room", [55.7, 25.2, 61.5, 27.8], "The hanging ivy in the living room", "trail", "beside the cabinet", False),
("Television on the stand", [62.7, 27.5, 67.6, 30.5], "The television on the stand", "flicker", "in the dark room", False),
("Bookshelf with the jam jars", [56.4, 34.4, 62.4, 37.9], "The bookshelf with the jam jars", "hang", "above the plant", False),
("Green spider plant", [55.7, 34.1, 59.4, 35.8], "The green spider plant", "sit", "on the top shelf", False),
("Tall palm in the corner", [59.4, 33.8, 69.0, 35.6], "The tall palm in the corner", "grow", "beside the shelves", False),
("Doorway to the hall", [56.4, 41.0, 67.1, 43.8], "The doorway to the hall", "lead", "into the kitchen", False),
("Small picture by the door", [57.1, 45.2, 59.7, 46.2], "The small picture by the door", "hang", "next to the doorway", False),

# TILE r1c2
("Tall bathroom mirror", [39.4, 51.1, 45.2, 53.1], "The tall bathroom mirror", "reflect", "the tiled wall", False),
("Green shower curtain", [35.9, 53.2, 48.9, 55.8], "The green shower curtain", "hang", "around the shower", False),
("Girl at the washbasin", [44.8, 53.7, 52.7, 55.1], "The girl at the washbasin", "brush", "her teeth", False),
("Red step stool", [51.0, 53.2, 53.1, 55.1], "The red step stool", "help", "the girl reach the basin", False),
("Washbasin with the running tap", [46.4, 50.8, 48.9, 53.5], "The washbasin with the running tap", "fill", "with warm water", False),
("Toilet by the window", [48.5, 57.7, 53.6, 59.4], "The toilet by the window", "stand", "in the corner", False),
("Poster of a princess", [35.9, 61.1, 43.8, 62.2], "The poster of a princess", "hang", "on the pink wall", False),
("Top bunk bed", [37.1, 63.7, 41.5, 71.8], "The top bunk bed", "sit", "high above the floor", False),
("Unicorn picture", [35.0, 66.0, 37.6, 68.8], "The unicorn picture", "decorate", "the bedroom wall", False),
("Green toy snake", [38.3, 66.0, 43.8, 68.2], "The green toy snake", "dangle", "over the side of the bunk", False),
("White chest of drawers", [43.8, 61.1, 54.1, 63.5], "The white chest of drawers", "hold", "the girl's clothes", False),
("Doll on the chest of drawers", [43.1, 60.3, 46.4, 61.8], "The doll on the chest of drawers", "watch", "the bedroom door", False),
("Bed with the yellow quilt", [44.8, 64.9, 50.8, 69.8], "The bed with the yellow quilt", "stand", "under the bunk", False),
("Blue swivel chair", [47.3, 68.2, 53.6, 70.0], "The blue swivel chair", "spin", "beside the desk", False),
("Red shoes on the bedroom floor", [50.8, 61.4, 52.9, 63.2], "The red shoes on the bedroom floor", "wait", "beside the drawers", True),
("Bathroom mirror cabinet", [59.7, 50.9, 63.7, 53.1], "The bathroom mirror cabinet", "hang", "above the pink basin", False),
("Little cactus", [57.8, 51.7, 59.4, 52.8], "The little cactus", "sit", "on top of the cabinet", False),
("Blue shower curtain", [56.0, 57.7, 69.0, 59.1], "The blue shower curtain", "hang", "beside the shower", False),
("White bookcase", [59.7, 60.2, 69.0, 62.9], "The white bookcase", "hold", "the bedtime stories", False),
("Bunk bed with the blue quilt", [57.3, 63.7, 61.5, 71.8], "The bunk bed with the blue quilt", "wait", "to be made", False),
("Girl in the bottom bunk", [64.3, 65.4, 68.0, 67.2], "The girl in the bottom bunk", "hug", "her teddy bear", False),
("Brown teddy bear", [63.9, 67.4, 66.7, 68.8], "The brown teddy bear", "lie", "on the pink pillow", False),

# TILE r1c3
("Mother in the purple top", [36.4, 76.2, 49.7, 78.5], "The mother in the purple top", "hug", "her daughter goodbye", False),
("Girl in the red skirt", [39.2, 78.0, 49.7, 80.0], "The girl in the red skirt", "leave", "for school", False),
("Red shoes by the door", [50.1, 74.5, 52.0, 76.2], "The red shoes by the door", "sit", "on the doormat", True),
("Yellow banister on the middle floor", [40.1, 78.9, 53.1, 81.8], "The yellow banister on the middle floor", "run", "beside the steps", False),
("Tall ivy-covered tree", [30.3, 83.6, 68.3, 89.8], "The tall ivy-covered tree", "grow", "beside the yellow house", False),
("Bird's nest in the tree", [37.1, 87.0, 38.9, 89.5], "The bird's nest in the tree", "hide", "among the leaves", False),
("Red squirrel on the trunk", [47.8, 86.1, 50.3, 88.0], "The red squirrel on the trunk", "climb", "up the old tree", False),
("Girl carrying a bag", [35.5, 91.0, 42.0, 92.9], "The girl carrying a bag", "walk", "to the bus stop", False),
("Woman in the pink skirt", [30.3, 93.7, 41.5, 96.0], "The woman in the pink skirt", "wait", "for the bus", False),
("Blue bus at the stop", [30.3, 97.2, 45.5, 100.0], "The blue bus at the stop", "stop", "at the kerb", False),
("Driver in the bus", [34.8, 98.3, 39.9, 99.7], "The driver in the bus", "open", "the bus doors", False),
("Wooden garden fence", [49.2, 90.1, 53.4, 96.6], "The wooden garden fence", "surround", "the small garden", False),
("Purple hydrangea", [48.5, 97.5, 53.1, 100.0], "The purple hydrangea", "flower", "beside the fence", False),
("Brown rabbit on the grass", [56.4, 92.0, 58.7, 93.5], "The brown rabbit on the grass", "nibble", "the fresh grass", False),
("Man in the blue shirt on the stairs", [60.1, 77.8, 69.5, 80.2], "The man in the blue shirt on the stairs", "carry", "the rubbish downstairs", False),
("Door on the lower landing", [55.5, 75.0, 69.5, 77.3], "The door on the lower landing", "stand", "half open", False),
("Grey wheelie bin", [60.6, 98.5, 67.1, 100.0], "The grey wheelie bin", "wait", "on the pavement", False),

# TILE r2c0
("Green bicycle", [63.7, 6.5, 72.2, 13.5], "The green bicycle", "roll", "along the yellow lines", False),
("Policeman on the crossing", [71.0, 3.2, 85.2, 6.6], "The policeman on the crossing", "help", "the children cross", False),
("Boy on the red ride-on car", [76.6, 6.9, 84.5, 9.4], "The boy on the red ride-on car", "push", "himself along the pavement", False),
("Zebra crossing", [81.0, 0.0, 92.2, 4.3], "The zebra crossing", "cross", "the wide road", False),
("Black street lamp", [70.1, 11.7, 86.6, 13.9], "The black street lamp", "stand", "at the corner of the pavement", False),
("Blue sofa in the ground floor flat", [65.0, 15.2, 74.3, 23.4], "The blue sofa in the ground floor flat", "face", "the television", False),
("White cat on the sofa", [69.9, 16.0, 71.7, 18.8], "The white cat on the sofa", "stretch", "along the cushions", False),
("Green hedge in front of the flats", [75.4, 10.3, 85.6, 22.2], "The green hedge in front of the flats", "hide", "the ground floor windows", False),
("Pink flowering bush", [76.6, 19.1, 80.1, 21.6], "The pink flowering bush", "flower", "beside the path", False),
("Woman in the yellow top", [76.6, 22.0, 89.4, 24.4], "The woman in the yellow top", "walk", "along the pavement", False),
("Brown handbag", [82.2, 22.0, 84.8, 23.1], "The brown handbag", "swing", "from her shoulder", False),
("Blue family car", [86.1, 5.4, 99.2, 22.5], "The blue family car", "drive", "past the block of flats", False),
("Child in the back seat", [90.2, 8.5, 93.9, 10.6], "The child in the back seat", "look", "out of the window", False),
("Driver of the blue car", [89.5, 11.9, 93.9, 13.9], "The driver of the blue car", "steer", "down the road", False),
("Passenger in the front seat", [88.4, 15.1, 91.4, 16.8], "The passenger in the front seat", "sit", "beside the driver", False),

# TILE r2c1
("Blue armchair", [67.8, 27.3, 74.3, 32.5], "The blue armchair", "stand", "in front of the window", False),
("Green rucksack on the floor", [68.0, 23.9, 72.2, 25.9], "The green rucksack on the floor", "lie", "beside the table", False),
("Father walking with his family", [75.2, 24.7, 89.7, 27.8], "The father walking with his family", "stroll", "along the pavement", False),
("Red tulips in the garden", [76.9, 28.5, 81.5, 31.5], "The red tulips in the garden", "stand", "tall in the flower bed", True),
("Girl in the pink skirt", [81.5, 28.5, 89.7, 30.8], "The girl in the pink skirt", "push", "the wheelchair", False),
("Boy in the wheelchair", [81.7, 31.2, 89.7, 34.6], "The boy in the wheelchair", "laugh", "with his sister", False),
("Red flowers in the border", [77.8, 37.9, 79.9, 41.9], "The red flowers in the border", "grow", "behind the hedge", True),
("Cat lying on the hedge", [78.0, 43.0, 79.4, 44.7], "The cat lying on the hedge", "sunbathe", "on top of the hedge", False),
("Woman on the pink scooter", [85.7, 40.1, 96.9, 43.5], "The woman on the pink scooter", "ride", "down the middle of the road", False),
("Pink motor scooter", [89.9, 37.9, 98.7, 47.7], "The pink motor scooter", "buzz", "along the street", False),
("Pink crash helmet", [85.7, 41.0, 87.6, 42.5], "The pink crash helmet", "protect", "the rider's head", False),
("Flowers on the scooter", [88.0, 38.2, 90.8, 39.9], "The flowers on the scooter", "ride", "in the luggage rack", True),
("Baby in the high chair", [64.4, 36.2, 71.5, 38.2], "The baby in the high chair", "bang", "his spoon on the tray", False),
("Mother feeding the baby", [63.7, 39.8, 72.2, 42.6], "The mother feeding the baby", "hold", "out a spoonful of porridge", False),
("Table with the white cloth", [66.2, 38.7, 73.4, 44.7], "The table with the white cloth", "carry", "the family lunch", False),

# TILE r2c2
("Pink washbasin", [65.9, 49.7, 71.7, 52.3], "The pink washbasin", "stand", "under the mirror", False),
("Pink bathtub", [65.9, 54.3, 69.7, 57.7], "The pink bathtub", "wait", "behind the shower curtain", False),
("Blue bucket", [73.1, 52.3, 75.5, 54.6], "The blue bucket", "sit", "on the bathroom floor", False),
("Desk lamp on the homework desk", [65.9, 60.2, 69.7, 61.8], "The desk lamp on the homework desk", "light", "the open book", False),
("Open book on the desk", [67.8, 61.2, 69.2, 63.1], "The open book on the desk", "wait", "for the morning homework", False),
("Clown doll", [64.8, 63.7, 68.7, 64.8], "The clown doll", "sit", "on the edge of the bed", False),
("Lower bunk with the pink quilt", [65.9, 65.1, 69.7, 71.8], "The lower bunk with the pink quilt", "hold", "a sleepy girl", False),
("Purple hydrangeas in the hedge", [77.3, 48.8, 81.5, 53.5], "The purple hydrangeas in the hedge", "flower", "beside the pavement", True),
("Green dustcart", [72.4, 55.4, 95.5, 77.8], "The green dustcart", "stop", "outside the flats", False),
("Driver of the dustcart", [80.1, 59.4, 84.3, 61.2], "The driver of the dustcart", "wait", "in the cab", False),
("Orange warning light", [75.0, 59.1, 76.9, 60.0], "The orange warning light", "flash", "on the roof of the cab", False),
("Front wheel of the dustcart", [90.6, 58.8, 95.0, 61.7], "The front wheel of the dustcart", "rest", "against the kerb", False),

# TILE r2c3
("Golden dog running", [69.0, 83.9, 73.4, 88.7], "The golden dog running", "chase", "the little white terrier", False),
("Little white terrier", [70.6, 89.4, 73.8, 92.9], "The little white terrier", "bark", "at the big dogs", False),
("Spotted dog", [72.7, 93.5, 77.8, 95.4], "The spotted dog", "pull", "on its lead", False),
("Black poodle", [69.0, 97.8, 75.0, 99.7], "The black poodle", "trot", "along the pavement", False),
("Shaggy grey dog", [72.4, 95.2, 77.3, 97.2], "The shaggy grey dog", "sniff", "the ground", False),
("Dog walker in the striped tights", [63.7, 93.5, 73.4, 96.3], "The dog walker in the striped tights", "hold", "four leads at once", False),
("Binman in the blue cap", [80.6, 83.5, 95.5, 86.3], "The binman in the blue cap", "tip", "the bin into the lorry", False),
("Blue wheelie bin being emptied", [82.0, 85.8, 92.2, 89.5], "The blue wheelie bin being emptied", "lean", "against the lorry", False),
("Man in the yellow safety vest", [75.7, 88.7, 90.4, 91.7], "The man in the yellow safety vest", "wheel", "the next bin over", False),
("Second blue wheelie bin", [79.7, 92.0, 89.4, 94.9], "The second blue wheelie bin", "roll", "across the pavement", False),
("White rubbish bag", [81.3, 95.2, 84.3, 97.4], "The white rubbish bag", "swing", "from her hand", False),
("Old woman in the pink blouse", [77.1, 97.5, 89.4, 99.9], "The old woman in the pink blouse", "bring", "out her rubbish", False),
("Back wheels of the dustcart", [90.4, 73.1, 95.5, 79.9], "The back wheels of the dustcart", "stand", "on the wide road", True),
]
