# Page 16 — farm harvest scene. Boxes read off tiler grid labels, per tile.
# (name, [ymin, xmin, ymax, xmax], subject, bare-infinitive verb, rest, plural)

P = [
    # ---------- r0c0  x0-28 y0-36.3 ----------
    ("Small aeroplane in the sky", [2.8, 5.0, 4.7, 9.0],
     "The small aeroplane", "fly", "high above the farm", False),
    ("Blue house with a red roof on the hill", [5.0, 25.0, 8.5, 27.8],
     "The blue house", "stand", "on top of the green hill", False),
    ("Woman jogging along the hilltop", [10.0, 0.9, 14.5, 4.4],
     "The jogger", "run", "along the path on the hillside", False),
    ("First greenhouse tunnel", [9.5, 7.0, 26.0, 16.0],
     "The first greenhouse tunnel", "shelter", "rows of young plants", False),
    ("Second greenhouse tunnel", [9.5, 15.0, 26.0, 22.0],
     "The second greenhouse tunnel", "protect", "the seedlings from the wind", False),
    ("Third greenhouse tunnel", [9.5, 21.0, 26.0, 28.5],
     "The third greenhouse tunnel", "shine", "in the morning sunlight", False),
    ("Man napping on the straw pile", [16.5, 0.5, 21.0, 6.7],
     "The sleepy farmhand", "rest", "on the warm pile of straw", False),
    ("Straw hat of the sleeping man", [17.0, 0.9, 18.5, 2.4],
     "The straw hat", "cover", "the sleeping man's face", False),
    ("Sheep grazing on the grass", [16.4, 4.3, 18.8, 7.2],
     "The sheep", "graze", "quietly beside the straw pile", False),
    ("Large pile of loose straw", [15.8, 0.0, 28.5, 6.8],
     "The pile of straw", "sit", "at the edge of the field", False),
    ("Blue tractor with a front loader", [20.5, 7.0, 43.0, 22.0],
     "The blue tractor", "lift", "a heavy bale with its loader", False),
    ("Driver in the blue tractor cab", [23.0, 8.6, 27.2, 11.2],
     "The tractor driver", "steer", "the blue tractor carefully", False),
    ("Round hay bale in the loader grab", [16.5, 17.6, 23.3, 23.0],
     "The round hay bale", "hang", "in the jaws of the loader", False),
    ("Front loader arm and grab", [18.6, 15.0, 26.0, 23.5],
     "The loader arm", "reach", "up towards the trailer", False),

    # ---------- r0c1  x22-53 y0-36.3 ----------
    ("Small tree on the hilltop", [2.6, 34.0, 5.8, 35.7],
     "The little tree", "grow", "alone on the hilltop", False),
    ("Hiker walking along the ridge", [2.8, 37.5, 4.8, 38.6],
     "The hiker", "walk", "along the top of the ridge", False),
    ("Tall cypress tree on the ridge", [1.4, 41.3, 7.5, 42.8],
     "The tall cypress tree", "point", "straight up into the sky", False),
    ("Second cypress tree", [2.5, 46.6, 8.2, 47.8],
     "The second cypress tree", "stand", "beside the hilltop path", False),
    ("Third cypress tree", [4.2, 51.4, 8.9, 53.0],
     "The third cypress tree", "sway", "gently in the breeze", False),
    ("Glass greenhouse with an open door", [9.3, 22.0, 26.0, 39.4],
     "The glass greenhouse", "hold", "rows of green plants inside", False),
    ("Open glass door of the greenhouse", [12.3, 33.4, 25.1, 39.4],
     "The greenhouse door", "stand", "wide open in the sunshine", False),
    ("White utility cart with a canopy", [10.7, 41.1, 23.7, 49.8],
     "The white utility cart", "wait", "on the farm track", False),
    ("Paw print painted on the cart", [19.0, 42.0, 21.0, 43.7],
     "The paw print", "mark", "the side of the white cart", False),
    ("Vet in a white coat beside the cart", [11.8, 46.8, 21.0, 48.6],
     "The vet", "stand", "beside the white cart", False),
    ("Farmer in blue overalls and a green cap", [10.6, 49.8, 21.2, 52.5],
     "The farmer in blue overalls", "talk", "with the vet on the track", False),
    ("Child standing beside the white cart", [18.5, 48.0, 23.5, 49.5],
     "The child", "wait", "next to the white cart", False),
    ("Girl in a pink shirt near the greenhouse", [20.4, 37.5, 27.0, 39.4],
     "The girl in the pink shirt", "watch", "the animals by the greenhouse", False),
    ("Boy in an orange shirt bending down", [19.0, 34.0, 24.2, 36.0],
     "The boy in the orange shirt", "bend", "down towards the ground", False),
    ("Wheelbarrow beside the greenhouse", [22.0, 35.0, 24.5, 37.2],
     "The wheelbarrow", "sit", "on the path by the greenhouse", False),

    # ---------- r0c2  x47-78 y0-36.3 ----------
    ("Kite flying high in the sky", [3.0, 64.1, 5.2, 65.3],
     "The kite", "fly", "high above the fields", False),
    ("Child flying a kite on the hill", [5.3, 55.1, 6.8, 56.4],
     "The kite flyer", "hold", "the string of the kite", False),
    ("Farmhouse with a red roof", [6.6, 59.5, 8.9, 63.1],
     "The farmhouse", "sit", "beside the country road", False),
    ("White cottage with a red roof", [6.4, 71.4, 8.7, 74.2],
     "The white cottage", "stand", "at the edge of the field", False),
    ("Green tractor pulling a hay wagon", [5.5, 66.0, 8.9, 70.1],
     "The distant green tractor", "pull", "a wagon along the road", False),
    ("Hay wagon on the country road", [5.5, 67.9, 8.5, 70.1],
     "The hay wagon", "carry", "a load of hay to the barn", False),
    ("Man on a red mobility scooter", [9.3, 53.9, 20.0, 58.2],
     "The man on the mobility scooter", "ride", "along the farm track", False),
    ("Straw hat raised in greeting", [9.2, 57.2, 10.6, 58.4],
     "The raised straw hat", "wave", "hello to the other farmers", False),
    ("Man in dungarees holding a pitchfork", [10.4, 60.8, 19.8, 64.1],
     "The man with the pitchfork", "stand", "in the middle of the field", False),
    ("Pitchfork held upright", [10.5, 62.8, 14.0, 64.1],
     "The pitchfork", "point", "straight up at the sky", False),
    ("Green round baler machine", [14.8, 61.7, 30.5, 75.0],
     "The green baler", "roll", "the straw into round bales", False),
    ("Large black wheel of the baler", [25.8, 66.2, 30.5, 69.3],
     "The baler's big wheel", "turn", "slowly across the stubble", False),
    ("Small wheel of the baler", [28.5, 71.4, 31.0, 73.2],
     "The baler's small wheel", "roll", "over the dusty ground", False),
    ("Round hay bale on the stubble", [22.8, 47.4, 31.6, 53.7],
     "The round hay bale", "lie", "on the harvested field", False),
    ("Second round hay bale", [21.8, 55.2, 30.7, 61.4],
     "The second hay bale", "wait", "to be collected from the field", False),
    ("Fresh bale coming out of the baler", [21.1, 62.6, 28.0, 66.2],
     "The fresh bale", "come", "out of the back of the baler", False),
    ("Brown bird flying over the field", [31.3, 62.0, 33.1, 63.9],
     "The brown bird", "swoop", "low over the stubble field", False),
    ("Straw hat blowing through the air", [30.9, 74.7, 32.7, 76.4],
     "The flying straw hat", "tumble", "through the air in the wind", False),

    # ---------- r0c3  x72-100 y0-36.3 ----------
    ("Big barn with a silo", [5.5, 78.0, 8.9, 86.3],
     "The big barn", "store", "the grain from the harvest", False),
    ("Tall grain silo beside the barn", [5.3, 84.2, 8.2, 86.3],
     "The grain silo", "rise", "above the roof of the barn", False),
    ("Two walkers on the far ridge", [4.2, 96.2, 8.9, 99.2],
     "The two walkers", "cross", "the top of the far hill", True),
    ("Walker in an orange jacket", [4.4, 96.3, 8.8, 97.9],
     "The walker in the orange jacket", "point", "at something in the valley", False),
    ("Walker in a blue-green jacket", [4.2, 98.0, 8.6, 99.1],
     "The walker in the green jacket", "follow", "the path over the hill", False),
    ("Fox running across the stubble", [10.9, 83.5, 13.1, 88.1],
     "The red fox", "dash", "across the harvested field", False),
    ("Two rabbits sitting in the field", [16.2, 96.1, 19.4, 99.2],
     "The two rabbits", "sit", "very still in the field", True),
    ("Rabbit on the left", [16.5, 96.2, 19.3, 97.4],
     "The first rabbit", "listen", "for danger in the field", False),
    ("Rabbit on the right", [16.3, 98.3, 19.1, 99.1],
     "The second rabbit", "nibble", "at the stubble on the ground", False),
    ("Large silver tractor in the field", [13.7, 77.3, 32.1, 94.3],
     "The silver tractor", "drive", "across the harvested field", False),
    ("Cab of the silver tractor", [13.7, 79.1, 21.9, 86.6],
     "The tractor cab", "shelter", "the driver from the sun", False),
    ("Driver of the silver tractor", [17.1, 82.8, 22.0, 85.2],
     "The driver of the silver tractor", "look", "out across the field", False),
    ("Big rear wheel of the silver tractor", [21.6, 77.3, 32.1, 83.5],
     "The tractor's big rear wheel", "grip", "the dry soil of the field", False),
    ("Front wheel of the silver tractor", [22.8, 87.0, 31.7, 91.2],
     "The tractor's front wheel", "roll", "over the stubble", False),
    ("Orange tank trailer", [32.8, 79.4, 46.8, 98.9],
     "The orange tank trailer", "carry", "water out to the fields", False),
    ("Filler cap on top of the tank", [31.8, 90.8, 35.3, 93.7],
     "The filler cap", "sit", "on top of the orange tank", False),

    # ---------- r1c0  x0-28 y30.3-69.7 ----------
    ("Fruit tree beside the track", [26.5, 0.0, 45.7, 8.4],
     "The fruit tree", "grow", "beside the farm track", False),
    ("Trunk of the fruit tree", [35.4, 5.0, 49.0, 6.7],
     "The tree trunk", "hold", "up the heavy branches", False),
    ("Man picking fruit from the tree", [35.4, 5.6, 51.4, 8.4],
     "The fruit picker", "reach", "up into the branches", False),
    ("Small child pulling a wagon", [47.0, 1.9, 51.4, 3.7],
     "The small child", "pull", "a little wagon along the grass", False),
    ("Yellow wagon full of fruit", [49.6, 0.5, 54.0, 5.2],
     "The yellow wagon", "hold", "a load of picked fruit", False),
    ("Red tractor on the farm track", [27.4, 8.3, 50.5, 25.7],
     "The red tractor", "wait", "on the gravel track", False),
    ("Rear wheel of the red tractor", [37.2, 12.1, 49.9, 18.0],
     "The red tractor's rear wheel", "stand", "taller than the children", False),
    ("Front wheel of the red tractor", [35.3, 20.3, 45.8, 25.1],
     "The red tractor's front wheel", "rest", "on the edge of the track", False),
    ("Woman driving the red tractor", [30.0, 18.5, 37.0, 21.7],
     "The woman in the red tractor", "wave", "from the driver's seat", False),
    ("Teenager in a white vest", [34.2, 25.6, 47.6, 28.0],
     "The teenager in the white vest", "carry", "a can across the yard", False),
    ("Dog leaping along the track", [48.7, 18.4, 54.7, 25.4],
     "The leaping dog", "chase", "the cat along the track", False),
    ("Orange pumpkin on the grass", [50.5, 8.7, 51.9, 9.7],
     "The orange pumpkin", "lie", "in the long green grass", False),
    ("Second pumpkin on the grass", [53.6, 7.6, 55.2, 8.6],
     "The second pumpkin", "roll", "towards the edge of the path", False),
    ("Hedgehog in the grass", [55.2, 9.5, 56.3, 10.3],
     "The hedgehog", "hide", "in the grass beside the path", False),
    ("Yellow flowering bush", [43.8, 1.6, 47.2, 4.3],
     "The yellow bush", "flower", "at the edge of the orchard", False),
    ("Green grain trailer", [56.8, 10.4, 69.8, 28.0],
     "The green grain trailer", "fill", "up with golden grain", False),
    ("Black crow on the ploughed field", [63.1, 5.0, 66.8, 7.7],
     "The black crow", "hop", "across the ploughed soil", False),

    # ---------- r1c1  x22-53 y30.3-69.7 ----------
    ("Green jerry can", [41.6, 25.9, 44.9, 28.1],
     "The green can", "swing", "from the teenager's hand", False),
    ("Green hay trailer", [23.5, 25.1, 39.3, 35.4],
     "The green hay trailer", "hold", "a load of loose hay", False),
    ("Wheel of the green hay trailer", [35.3, 28.5, 40.5, 31.4],
     "The hay trailer's wheel", "sink", "into the soft ground", False),
    ("Man in a purple shirt hurrying", [32.8, 32.4, 43.7, 37.5],
     "The man in the purple shirt", "hurry", "across the farmyard", False),
    ("Metal bucket carried by the man", [37.4, 32.8, 40.5, 34.6],
     "The metal bucket", "swing", "in the farmer's hand", False),
    ("Khaki pickup truck", [29.3, 35.9, 43.9, 50.8],
     "The khaki pickup truck", "park", "beside the farm track", False),
    ("Front wheel of the pickup truck", [32.1, 37.0, 39.3, 40.0],
     "The pickup's front wheel", "rest", "on the gravel", False),
    ("Green crate on the pickup", [31.6, 42.1, 34.4, 44.3],
     "The green crate", "sit", "in the back of the truck", False),
    ("Milk churns in the truck bed", [34.2, 46.0, 37.9, 49.9],
     "The milk churns", "stand", "in the back of the pickup", True),
    ("Woman pushing a loaded hand truck", [34.6, 41.2, 45.8, 45.1],
     "The woman with the hand truck", "push", "the crates towards the pickup", False),
    ("Stack of crates on the hand truck", [35.3, 42.3, 40.5, 44.3],
     "The stack of crates", "wobble", "on the little hand truck", False),
    ("Loading ramp at the back of the truck", [40.3, 47.8, 44.4, 51.7],
     "The loading ramp", "lean", "against the back of the truck", False),
    ("Ginger cat running along the track", [48.7, 29.6, 51.0, 33.2],
     "The ginger cat", "race", "away down the track", False),
    ("Man in a white coat and cap sitting", [47.5, 36.2, 56.8, 40.3],
     "The man in the white coat", "sit", "on the wooden bench", False),
    ("White cap of the seated man", [47.5, 38.1, 49.3, 40.0],
     "The white cap", "shade", "the seated man's eyes", False),
    ("Person resting on the bench", [51.2, 40.4, 56.6, 43.7],
     "The resting person", "lean", "back against the bench", False),
    ("Wooden bench beside the track", [50.8, 35.9, 57.0, 44.3],
     "The wooden bench", "stand", "at the side of the track", False),
    ("Wooden barrel on the ground", [52.9, 32.7, 56.6, 34.4],
     "The wooden barrel", "stand", "on the grass by the bench", False),
    ("Unloading auger of the harvester", [57.8, 23.1, 66.4, 32.0],
     "The unloading auger", "pour", "grain into the trailer", False),
    ("Boy on the trailer ladder", [54.0, 45.7, 66.8, 48.2],
     "The boy on the ladder", "climb", "up the side of the trailer", False),
    ("Green shrub beside the track", [53.1, 48.1, 59.4, 50.5],
     "The green shrub", "grow", "beside the farm track", False),

    # ---------- r1c2  x47-78 y30.3-69.7 ----------
    ("Man in a red cap and dungarees", [32.8, 54.3, 43.9, 57.3],
     "The man in the red cap", "stand", "with his hands on his hips", False),
    ("Red cap worn by the farmer", [32.8, 54.8, 34.4, 56.5],
     "The red cap", "keep", "the sun off the farmer's head", False),
    ("Hedge behind the green tractor", [31.6, 57.4, 42.1, 62.5],
     "The green hedge", "grow", "along the edge of the track", False),
    ("Large green tractor", [34.4, 57.7, 52.3, 78.0],
     "The large green tractor", "rumble", "along the farm track", False),
    ("Exhaust stack of the green tractor", [33.2, 65.3, 37.6, 66.1],
     "The exhaust stack", "puff", "smoke into the air", False),
    ("Old man driving the green tractor", [31.6, 69.3, 40.5, 72.1],
     "The old man on the green tractor", "drive", "slowly down the track", False),
    ("Rear wheel of the green tractor", [38.8, 71.0, 49.6, 78.0],
     "The green tractor's rear wheel", "crush", "the stones on the track", False),
    ("Front wheel of the green tractor", [43.1, 59.2, 53.3, 66.2],
     "The green tractor's front wheel", "turn", "towards the farmyard", False),
    ("Red fuel can on the tractor", [42.4, 67.0, 46.8, 68.4],
     "The red fuel can", "hang", "on the side of the tractor", False),
    ("Ginger cat sitting on the grass", [40.9, 58.3, 44.4, 60.2],
     "The sitting cat", "watch", "the tractor go past", False),
    ("Two children playing on the verge", [50.3, 52.0, 57.0, 57.3],
     "The two children", "play", "together on the grassy verge", True),
    ("Girl in a purple top", [50.4, 52.1, 56.9, 54.2],
     "The girl in the purple top", "laugh", "at her friend", False),
    ("Boy in a green top", [50.6, 54.4, 56.9, 57.2],
     "The boy in the green top", "reach", "out towards the girl", False),
    ("Blue pickup with a white camper top", [48.4, 63.3, 63.6, 78.0],
     "The blue pickup", "serve", "as a shop on the farm track", False),
    ("Open display hatch on the camper", [52.6, 63.4, 57.1, 68.1],
     "The open hatch", "show", "the goods inside the van", False),
    ("Second display window with tools", [52.2, 70.3, 58.0, 73.9],
     "The tool display", "hang", "inside the open window", False),
    ("Front wheel of the blue pickup", [58.9, 67.4, 63.6, 70.5],
     "The blue pickup's front wheel", "sit", "on the edge of the track", False),
    ("Small green shrub by the trailer", [53.8, 48.1, 58.4, 51.1],
     "The little shrub", "grow", "at the foot of the trailer", False),

    # ---------- r1c3  x72-100 y30.3-69.7 ----------
    ("Wheel of the orange tanker", [45.6, 90.7, 51.0, 94.3],
     "The tanker's wheel", "roll", "along the edge of the field", False),
    ("Bushes behind the tanker", [35.3, 76.7, 45.4, 79.8],
     "The bushes", "grow", "thickly behind the tanker", True),
    ("Open door of the blue pickup", [55.0, 73.9, 64.0, 79.3],
     "The open door", "swing", "out from the blue pickup", False),
    ("Wheel of the blue pickup", [59.6, 82.1, 64.0, 84.7],
     "The blue pickup's wheel", "stand", "in the dust of the track", False),
    ("Boy in yellow dungarees with a toolbox", [56.4, 79.4, 69.7, 84.1],
     "The boy in the yellow dungarees", "carry", "a toolbox across the field", False),
    ("Green toolbox", [62.4, 78.5, 65.0, 81.8],
     "The green toolbox", "hang", "heavily from the boy's hand", False),
    ("Old man with a walking stick", [55.0, 87.0, 68.3, 93.3],
     "The old man", "walk", "slowly along the field edge", False),
    ("White sun hat of the old man", [55.0, 88.2, 57.3, 90.6],
     "The white sun hat", "shade", "the old man's face", False),
    ("Walking stick", [60.1, 86.9, 67.8, 87.8],
     "The walking stick", "steady", "the old man on the path", False),
    ("Spotted pig running across the track", [51.2, 93.9, 55.4, 99.2],
     "The spotted pig", "trot", "across the farm track", False),

    # ---------- r2c0  x0-28 y63.7-100 ----------
    ("Crow standing on the ploughed field", [69.4, 1.8, 72.9, 4.7],
     "The crow on the ground", "peck", "at the ploughed soil", False),
    ("Red combine harvester", [65.5, 3.3, 94.4, 28.0],
     "The red combine harvester", "cut", "its way through the wheat", False),
    ("Cab window of the combine", [70.6, 16.3, 74.7, 24.5],
     "The combine's cab window", "look", "out over the golden field", False),
    ("Engine on top of the combine", [65.5, 17.1, 70.3, 21.7],
     "The combine's engine", "roar", "at the top of the machine", False),
    ("Big front wheel of the combine", [84.5, 9.2, 94.4, 15.6],
     "The combine's front wheel", "press", "flat the stubble below", False),
    ("Second wheel of the combine", [84.0, 23.1, 94.2, 27.9],
     "The combine's second wheel", "carry", "the huge machine forward", False),
    ("Butterfly over the stubble", [92.6, 2.8, 95.8, 4.9],
     "The butterfly", "flutter", "low over the cut field", False),

    # ---------- r2c1  x22-53 y63.7-100 ----------
    ("Man standing on the combine steps", [68.7, 28.5, 81.9, 32.3],
     "The man on the combine steps", "climb", "up towards the cab", False),
    ("Blue cap of the man on the steps", [68.7, 29.9, 70.3, 32.0],
     "The blue cap", "sit", "on the climbing man's head", False),
    ("Driver inside the combine cab", [70.3, 31.5, 75.9, 33.5],
     "The combine driver", "steer", "the harvester through the wheat", False),
    ("Glass cab of the combine", [66.2, 30.1, 81.4, 36.4],
     "The combine's glass cab", "shine", "in the afternoon sun", False),
    ("Ladder up the side of the combine", [81.9, 26.5, 92.6, 29.8],
     "The combine's ladder", "lead", "up to the driver's door", False),
    ("Rear wheel of the combine", [82.6, 22.8, 94.4, 30.1],
     "The combine's rear wheel", "turn", "slowly through the stubble", False),
    ("Cutting header of the combine", [75.2, 30.8, 98.2, 50.8],
     "The cutting header", "sweep", "through the standing wheat", False),
    ("Conveyor grid on the header", [75.4, 36.1, 95.4, 50.8],
     "The conveyor", "carry", "the cut wheat up into the machine", False),
    ("Green tipping trailer", [56.8, 35.2, 79.1, 48.9],
     "The green tipping trailer", "collect", "the grain from the harvester", False),
    ("Wheel of the green tipping trailer", [75.9, 37.0, 80.0, 40.0],
     "The tipping trailer's wheel", "roll", "beside the combine", False),
    ("Second wheel of the tipping trailer", [75.9, 40.9, 79.8, 43.7],
     "The trailer's second wheel", "bump", "over the rough ground", False),

    # ---------- r2c2  x47-78 y63.7-100 ----------
    ("Yellow and red tractor", [60.2, 50.9, 78.6, 70.9],
     "The yellow tractor", "drive", "along the edge of the wheat", False),
    ("Canopy roof of the yellow tractor", [61.0, 54.8, 63.1, 61.3],
     "The tractor's canopy", "shade", "the driver from the sun", False),
    ("Driver of the yellow tractor", [62.7, 57.1, 67.8, 59.7],
     "The yellow tractor's driver", "hold", "the steering wheel firmly", False),
    ("Passenger behind the yellow tractor", [60.3, 53.2, 67.3, 55.3],
     "The passenger", "stand", "behind the tractor seat", False),
    ("Rear wheel of the yellow tractor", [69.9, 51.5, 78.2, 57.7],
     "The yellow tractor's rear wheel", "dig", "into the soft earth", False),
    ("Front wheel of the yellow tractor", [72.2, 62.3, 78.6, 68.7],
     "The yellow tractor's front wheel", "steer", "along the field edge", False),
    ("Woman pushing a stroller", [72.2, 74.1, 84.0, 76.7],
     "The woman with the stroller", "push", "the buggy up the path", False),
    ("Child sitting in the stroller", [79.4, 71.9, 83.8, 74.3],
     "The child in the stroller", "point", "at the big machines", False),
    ("Stroller on the field path", [77.5, 70.3, 86.5, 74.7],
     "The stroller", "bump", "along the narrow path", False),
    ("Man in a green t-shirt walking", [81.7, 61.1, 96.7, 64.8],
     "The man in the green t-shirt", "stroll", "along the edge of the field", False),
    ("Woman in yellow shorts walking", [81.0, 65.1, 94.7, 68.1],
     "The woman in the yellow shorts", "walk", "beside the wheat field", False),
    ("Purple headband", [81.0, 65.6, 82.4, 67.3],
     "The purple headband", "keep", "the woman's hair out of her eyes", False),
    ("Stones on the field path", [97.5, 56.8, 99.1, 59.7],
     "The stones", "lie", "scattered along the path", True),
    ("Bush at the edge of the path", [96.1, 71.6, 100.0, 75.0],
     "The bush", "grow", "at the edge of the path", False),

    # ---------- r2c3  x72-100 y63.7-100 ----------
    ("Old red vintage tractor", [59.3, 82.7, 83.8, 98.9],
     "The old red tractor", "stand", "in the corner of the meadow", False),
    ("Exposed engine of the old tractor", [66.2, 93.2, 70.3, 96.7],
     "The old tractor's engine", "sit", "open at the front", False),
    ("Steering wheel of the old tractor", [68.2, 89.5, 70.3, 91.2],
     "The steering wheel", "wait", "for someone to take hold of it", False),
    ("Metal seat of the old tractor", [69.6, 85.9, 73.8, 88.6],
     "The metal seat", "shine", "in the afternoon light", False),
    ("Big rear wheel of the old tractor", [75.2, 90.1, 83.8, 94.6],
     "The old tractor's rear wheel", "tower", "over the grass", False),
    ("Small front wheel of the old tractor", [72.0, 96.2, 75.2, 98.6],
     "The old tractor's front wheel", "rest", "in the long grass", False),
    ("Beekeeper in a white suit", [80.8, 93.2, 93.5, 97.7],
     "The beekeeper", "walk", "towards the wooden hives", False),
    ("Wide brimmed hat of the beekeeper", [80.8, 93.9, 82.6, 96.4],
     "The beekeeper's hat", "protect", "his face from the bees", False),
    ("Metal bucket held by the beekeeper", [85.2, 95.2, 88.6, 96.7],
     "The beekeeper's bucket", "hang", "from his gloved hand", False),
    ("Boy running away from the bees", [86.1, 77.4, 96.3, 84.7],
     "The running boy", "flee", "from the swarm of bees", False),
    ("Two wooden beehives", [93.3, 86.1, 99.1, 93.7],
     "The wooden beehives", "sit", "side by side in the meadow", True),
    ("Beehive on the left", [93.6, 86.2, 98.5, 90.2],
     "The left beehive", "hum", "with busy bees", False),
    ("Beehive on the right", [93.9, 90.5, 98.8, 93.6],
     "The right beehive", "stand", "on a wooden pallet", False),
    ("Swarm of bees in the air", [85.4, 83.9, 94.4, 87.5],
     "The swarm of bees", "chase", "the boy across the meadow", False),
    ("Small animal in the grass", [85.4, 97.8, 87.2, 99.2],
     "The little animal", "peep", "out of the long grass", False),
    ("Bushes at the edge of the meadow", [77.0, 98.0, 85.0, 100.0],
     "The bushes", "line", "the edge of the meadow", True),
    ("Bushes beside the wheat field", [95.7, 72.9, 100.0, 77.9],
     "The green bushes", "mark", "the corner of the field", True),
]
