# Page 15 - the modern farm: solar panels going up on the cowshed roof, the
# milking scene by the red barn, the vet in the pasture, the windmill, the
# loggers at the forest edge, the sheep field, the hay wagon, the stubborn
# donkey and the pig pen.
# Boxes read straight off the tiler grid labels, one block per tile.
P = [

# TILE r0c0 - the cowshed roof and the hay barn below
("Fir trees by the barn", [0.0, 0.0, 11.0, 8.5], "The fir trees", "stand", "beside the red barn", True),
("Solar panels on the roof", [6.0, 1.0, 22.0, 20.3], "The solar panels", "shine", "in the morning sun", True),
("Roofer in yellow overalls", [11.4, 11.4, 23.0, 16.5], "The roofer in yellow overalls", "install", "solar panels on the roof", False),
("Solar panel on the stand", [13.2, 14.7, 16.2, 19.9], "The solar panel on the stand", "wait", "to be fitted", False),
("Spare solar panel", [18.4, 15.6, 26.0, 20.1], "The spare solar panel", "lie", "flat on the wooden roof", False),
("Long wooden roof", [2.5, 0.0, 31.0, 42.0], "The long wooden roof", "slope", "down over the cowshed", False),
("Red wall above the panels", [0.0, 8.0, 9.0, 28.0], "The red wall above the panels", "rise", "behind the new roof", False),
("Post holding up the roof", [20.0, 5.8, 29.9, 8.1], "The white post", "hold", "up the heavy roof", False),
("Cow walking in the hay barn", [23.3, 0.5, 30.0, 9.7], "The cow in the hay barn", "walk", "through the yellow hay", False),
("Cow standing in the hay", [24.7, 9.5, 33.3, 14.0], "The cow in the middle of the barn", "stand", "in the deep hay", False),
("Calf walking out of the barn", [29.8, 6.0, 36.4, 13.9], "The young calf", "walk", "down to the pasture", False),
("Brown calf eating hay", [29.0, 14.8, 36.8, 21.5], "The brown calf", "eat", "hay in the barn", False),
("Yellow hay in the cowshed", [22.5, 0.0, 36.5, 22.0], "The yellow hay", "cover", "the floor of the cowshed", False),

# TILE r0c1 - the roof cats, the red barn gable and the milking corner
("Cat lying on the roof", [10.6, 24.3, 13.0, 28.0], "The grey cat", "doze", "on the warm roof", False),
("Kitten on the roof ridge", [6.2, 27.5, 7.9, 29.8], "The little kitten", "walk", "along the roof ridge", False),
("Open hatch in the roof", [19.5, 27.1, 25.2, 31.8], "The open hatch", "let", "light into the hayloft", False),
("Red barn", [3.0, 24.0, 40.0, 61.0], "The big red barn", "stand", "in the middle of the farm", False),
("Hayloft door with the cross", [12.5, 42.2, 22.0, 47.2], "The hayloft door", "face", "the farmyard below", False),
("Window in the barn wall", [30.4, 31.6, 36.0, 35.5], "The barn window", "reflect", "the blue sky", False),
("Cow being milked", [26.0, 38.5, 34.5, 51.0], "The cow by the barn", "stand", "still for the milking", False),
("Farmer milking the cow", [28.5, 47.5, 34.6, 50.8], "The farmer on the stool", "milk", "the spotted cow", False),
("Milk can by the stool", [31.0, 46.3, 34.7, 47.7], "The shiny milk can", "wait", "for the fresh milk", False),
("Farmer pushing the wheelbarrow", [29.5, 39.0, 42.0, 44.0], "The farmer in the green cap", "push", "the wheelbarrow of straw", False),
("Red wheelbarrow", [36.2, 40.4, 42.0, 44.3], "The red wheelbarrow", "carry", "a load of dirty straw", False),
("Squirrel on the tree trunk", [3.8, 50.2, 8.3, 52.1], "The red squirrel", "climb", "up the tree trunk", False),

# TILE r0c2 - the forest edge, the stream, the windmill and the loggers
("Stream in the forest", [10.3, 54.8, 15.1, 59.7], "The little stream", "flow", "out of the forest", False),
("Tall tree by the stream", [0.0, 59.0, 12.5, 65.5], "The tall tree", "grow", "beside the stream", False),
("Lumberjack with the chainsaw", [5.4, 65.0, 12.1, 69.0], "The lumberjack", "cut", "the fallen tree into logs", False),
("Felled log", [10.5, 64.5, 12.3, 70.7], "The felled log", "lie", "on the forest floor", False),
("Tree stump by the log", [14.2, 66.3, 16.0, 69.3], "The tree stump", "stick", "out of the bare earth", False),
("Tree stump by the fence", [18.4, 66.8, 20.2, 69.2], "The stump by the fence", "sit", "near the new fence posts", False),
("Yellow post drill", [6.0, 70.0, 20.2, 75.8], "The yellow post drill", "drill", "holes for the fence posts", False),
("Windmill above the farmyard", [12.3, 58.4, 45.3, 67.1], "The tall windmill", "turn", "in the light breeze", False),
("Man climbing the windmill ladder", [25.8, 62.4, 36.4, 65.6], "The man on the ladder", "climb", "up the windmill tower", False),
("Birds on the wire", [20.8, 65.8, 22.3, 68.7], "The little birds", "sit", "on the fence wire", True),
("Fence of the sheep field", [20.5, 66.0, 40.0, 86.0], "The wooden fence", "run", "around the sheep field", False),
("Sheep by the fence", [25.8, 73.0, 29.4, 75.9], "The sheep by the fence", "graze", "by the new posts", False),
("Sheep at the field corner", [28.7, 71.5, 31.7, 73.8], "The sheep at the corner", "nibble", "the short grass", False),
("Sheep at the bottom of the field", [31.6, 69.9, 35.5, 72.7], "The sheep on the slope", "wander", "down the hillside", False),

# TILE r0c3 - the log loader and the sheep flock
("Orange forestry tractor", [5.5, 75.3, 21.5, 89.3], "The orange forestry tractor", "carry", "logs out of the forest", False),
("Trailer loaded with logs", [4.4, 88.0, 15.7, 97.0], "The log trailer", "hold", "a pile of heavy logs", False),
("Crane lifting a log", [1.4, 90.5, 11.7, 96.1], "The blue crane", "lift", "a log onto the trailer", False),
("Logger in the yellow helmet", [6.2, 94.5, 14.6, 96.6], "The logger in the yellow helmet", "watch", "the swinging log", False),
("Dog with the red collar", [25.8, 82.8, 30.0, 85.3], "The dog with the red collar", "sit", "among the sheep", False),
("Little lamb", [25.6, 76.5, 27.7, 78.4], "The little lamb", "stay", "close to its mother", False),
("Sheep near the dog", [27.5, 76.0, 30.5, 79.2], "The sheep near the dog", "eat", "the fresh grass", False),
("Sheep in the middle of the flock", [25.4, 79.1, 28.8, 82.3], "The sheep in the middle of the flock", "chew", "a mouthful of grass", False),
("Sheep grazing by the bushes", [30.0, 84.1, 32.3, 87.5], "The sheep by the bushes", "graze", "on the green hillside", False),
("Black sheepdog", [31.7, 75.1, 34.9, 79.3], "The black sheepdog", "run", "around the flock", False),
("Wooden sheep shelter", [20.0, 85.2, 30.0, 97.7], "The wooden shelter", "give", "shade to the sheep", False),
("Feeding trough of the sheep", [26.3, 85.0, 29.8, 88.3], "The feeding trough", "hold", "hay for the sheep", False),

# TILE r1c0 - the vet visit in the pasture
("Farmer in the straw hat", [39.3, 1.8, 49.5, 6.3], "The farmer in the straw hat", "stroke", "the young cow's nose", False),
("Vet in the white coat", [39.3, 11.1, 49.7, 14.6], "The vet in the white coat", "listen", "to the cow's heart", False),
("Spotted cow with the vet", [39.5, 5.0, 48.1, 14.0], "The spotted cow", "stand", "between the farmer and the vet", False),
("Woman holding the cow", [37.0, 16.3, 47.8, 19.5], "The woman with black hair", "hold", "the cow by the halter", False),
("Cow with the halter", [37.5, 17.8, 47.7, 25.8], "The cow with the halter", "wait", "for its turn with the vet", False),
("Cow lying on the grass", [46.2, 3.0, 53.7, 13.1], "The cow on the grass", "rest", "in the morning sun", False),
("Cow with the swishing tail", [49.7, 13.5, 60.6, 25.7], "The big cow", "swish", "its long tail", False),
("Calf beside its mother", [54.4, 14.4, 60.9, 20.2], "The calf beside its mother", "sniff", "at the fresh grass", False),
("Boy feeding the calf", [55.3, 13.0, 62.0, 14.9], "The boy in the green shirt", "feed", "grass to the calf", False),
("Leafy tree in the pasture", [53.0, 2.0, 74.5, 10.3], "The leafy tree", "give", "shade to the pasture", False),
("Wire fence of the pasture", [48.5, 13.0, 68.0, 37.5], "The wire fence", "separate", "the pasture from the yard", False),

# TILE r1c1 - the farmyard path and the big red tractor
("Bush by the barn door", [36.2, 26.3, 47.6, 36.0], "The green bush", "grow", "against the barn wall", False),
("Yellow bird on the bush", [39.5, 32.1, 41.1, 33.2], "The yellow bird", "sing", "on the green bush", False),
("Dog jumping at the bush", [44.2, 33.0, 47.6, 36.1], "The excited dog", "jump", "up at the little bird", False),
("Cow walking to the fence", [46.7, 26.0, 54.6, 36.0], "The cow by the bush", "wander", "across the green pasture", False),
("Calf by the wire fence", [56.7, 22.5, 63.0, 29.5], "The calf by the fence", "look", "through the wire", False),
("Boy watching the tractor", [56.7, 30.8, 63.4, 32.7], "The boy in the pasture", "scratch", "his head in wonder", False),
("Man in the green T-shirt", [44.2, 36.7, 52.3, 39.2], "The man in the green T-shirt", "watch", "the busy farmyard", False),
("Woman in the purple top", [46.0, 38.6, 52.7, 40.8], "The woman in the purple top", "chat", "with the man beside her", False),
("Woman leading the goat", [42.0, 41.0, 50.0, 43.4], "The woman in the green vest", "lead", "the little goat along the path", False),
("Brown goat on the path", [45.0, 42.1, 49.5, 44.9], "The brown goat on the path", "trot", "beside the woman", False),
("Farmer carrying the milk churn", [40.2, 45.7, 49.2, 50.1], "The farmer with the milk churn", "wave", "with his free hand", False),
("Boy in the red jacket", [50.2, 47.8, 59.2, 50.8], "The boy in the red jacket", "play", "with the calf on the rope", False),
("Calf on the rope", [55.5, 43.5, 59.9, 48.0], "The calf on the rope", "pull", "against its lead", False),
("Big red tractor", [56.3, 27.8, 79.0, 47.7], "The big red tractor", "drive", "up the farm road", False),
("Driver of the red tractor", [57.4, 36.1, 60.9, 38.6], "The driver of the red tractor", "steer", "with both hands", False),
("Dog riding in the cab", [62.5, 36.7, 66.4, 39.9], "The dog in the cab", "ride", "along with the driver", False),

# TILE r1c2 - the barn door, the green pickup and the road
("Sliding barn door", [30.0, 51.4, 37.5, 59.2], "The sliding barn door", "stand", "wide open", False),
("Dog lying by the barn door", [37.4, 52.9, 39.5, 56.1], "The dog by the barn door", "doze", "beside his food bowl", False),
("Green pickup truck", [41.8, 51.4, 56.5, 67.2], "The green pickup truck", "stand", "loaded in the farmyard", False),
("Open door of the pickup", [43.5, 51.5, 52.5, 56.7], "The pickup door", "hang", "open on its hinges", False),
("Milk cans in the pickup bed", [47.8, 58.3, 50.4, 60.7], "The milk cans", "rattle", "in the pickup bed", True),
("Boxes in the pickup bed", [48.8, 60.3, 51.9, 63.6], "The white boxes", "sit", "behind the milk cans", True),
("Dog sniffing by the pickup", [49.7, 51.0, 54.0, 55.4], "The dog by the pickup", "sniff", "at the truck's tyres", False),
("Blue tractor", [40.0, 68.5, 54.6, 80.4], "The blue tractor", "pull", "the wagon of hay", False),
("Man in the orange waistcoat", [36.2, 71.6, 44.8, 74.9], "The man in the orange waistcoat", "fix", "the wire to the posts", False),
("Girl in the orange dress", [41.8, 68.5, 45.7, 69.9], "The girl in the orange dress", "help", "with the new fence", False),
("Boy on the bicycle", [52.0, 61.0, 64.0, 68.1], "The boy on the bicycle", "pedal", "along the smooth road", False),
("Bicycle trailer with the dog", [54.4, 67.9, 60.8, 71.5], "The orange bicycle trailer", "roll", "behind the bicycle", False),

# TILE r1c3 - the hay wagon, the sty and the arched shed
("Wagon loaded with hay", [38.1, 79.6, 51.3, 91.2], "The wooden wagon", "carry", "a mountain of hay", False),
("Woman riding in the hay", [34.6, 84.8, 38.5, 88.1], "The woman in the hay", "throw", "her arms in the air", False),
("Boy hiding in the hay", [38.3, 82.8, 40.4, 84.4], "The boy in the hay", "hide", "in the soft load", False),
("Man in the green jacket", [44.2, 79.7, 54.6, 82.7], "The man in the green jacket", "watch", "the hay wagon leave", False),
("Rooster on the gutter", [48.6, 87.3, 51.1, 88.9], "The rooster", "crow", "from the gutter", False),
("Yellow pig sty", [50.6, 88.5, 76.6, 100.0], "The yellow sty", "house", "the pigs at night", False),
("Arched metal shed", [32.5, 90.0, 55.2, 100.0], "The arched metal shed", "curve", "high behind the sty", False),
("Bush by the pig sty", [50.6, 84.2, 63.0, 88.4], "The bush by the sty", "grow", "beside the fence", False),
("Farmer leaning on the pig fence", [60.7, 75.3, 69.2, 79.8], "The farmer at the fence", "lean", "on the fence post", False),

# TILE r2c0 - the bench, the path and the road
("Grandmother knitting on the bench", [71.3, 5.0, 79.8, 11.8], "The grandmother on the bench", "knit", "in the shade of the tree", False),
("Red bench under the tree", [75.2, 6.0, 79.8, 10.3], "The red bench", "stand", "under the leafy tree", False),
("Red bicycle against the tree", [72.7, 1.6, 79.4, 5.8], "The red bicycle", "lean", "against the tree trunk", False),
("Grey stone by the bench", [79.0, 11.9, 80.4, 13.3], "The grey stone", "lie", "at the edge of the grass", False),
("Girl on the skateboard", [66.2, 14.3, 73.8, 17.7], "The girl on the skateboard", "balance", "with her arms out", False),
("Child kneeling on the path", [66.2, 19.3, 71.2, 22.3], "The child on the path", "play", "with the toy truck", False),
("Girl in the striped skirt", [64.9, 22.1, 71.6, 25.2], "The girl in the striped skirt", "sit", "on the sunny path", False),
("Toy truck on the path", [71.5, 18.9, 73.6, 21.7], "The red toy truck", "wait", "for its young owner", False),
("Man riding the horse", [82.2, 4.7, 92.6, 8.1], "The rider in the cowboy hat", "ride", "along the country road", False),
("Brown horse on the road", [85.0, 2.2, 100.0, 11.2], "The brown horse", "trot", "down the road", False),
("Trailer with the pig", [80.6, 14.4, 94.5, 23.2], "The green trailer", "carry", "a fat pink pig", False),
("Pink pig in the trailer", [85.2, 15.3, 89.8, 21.4], "The pig in the trailer", "sniff", "the country air", False),
("Country road", [56.0, 0.0, 100.0, 82.0], "The white country road", "wind", "past the farm", False),

# TILE r2c1 - the old tractor and the stubborn donkey
("Old red tractor", [76.0, 22.0, 93.1, 36.9], "The old red tractor", "chug", "along the dusty road", False),
("Old farmer driving the tractor", [74.3, 25.0, 83.3, 31.1], "The old farmer", "drive", "his little tractor", False),
("Puddle on the road", [82.1, 40.2, 83.7, 44.2], "The puddle", "shine", "on the warm road", False),
("Boy pulling the donkey", [85.5, 39.0, 96.4, 44.9], "The boy in the red cap", "pull", "on the donkey's lead", False),
("Stubborn donkey", [83.2, 44.7, 95.9, 51.5], "The stubborn donkey", "refuse", "to take another step", False),
("Boy pushing the donkey", [81.5, 52.0, 93.6, 57.3], "The boy in the blue shirt", "push", "the donkey from behind", False),
("Wild flowers on the verge", [92.1, 26.6, 98.1, 38.0], "The wild flowers", "bloom", "beside the road", True),

# TILE r2c2 - the paddock, the wagon and the pig pen fence
("Jogger in the yellow vest", [64.2, 54.0, 74.5, 57.3], "The jogger in the yellow vest", "jog", "along the white road", False),
("Father pulling the little wagon", [70.1, 49.6, 83.3, 54.2], "The father in the striped shirt", "pull", "the wagon behind him", False),
("Yellow wagon with the toddler", [73.6, 56.0, 79.4, 60.2], "The little yellow wagon", "carry", "the happy toddler", False),
("Donkey eating from the trough", [80.1, 57.4, 88.9, 68.0], "The grey donkey", "eat", "oats from the trough", False),
("Wooden feed trough", [87.8, 63.7, 93.1, 69.9], "The wooden feed trough", "hold", "golden oats", False),
("Fence of the pig pen", [66.5, 60.0, 81.0, 78.0], "The wire mesh fence", "keep", "the piglets inside", False),
("Water trough in the pig pen", [75.5, 66.6, 79.2, 73.9], "The long water trough", "hold", "water for the piglets", False),
("Piglet by the water trough", [77.6, 70.7, 80.5, 73.6], "The piglet by the trough", "drink", "from the long trough", False),
("Piglet in the muddy pen", [76.9, 73.9, 79.8, 77.9], "The piglet in the mud", "trot", "through the muddy pen", False),
("Piglet running out of the pen", [92.4, 72.5, 95.9, 76.7], "The runaway piglet", "escape", "through the open gate", False),
("Woman in the blue dress", [62.0, 68.5, 73.6, 70.9], "The woman in the blue dress", "watch", "the pigs with her daughter", False),
("Girl waving at the pigs", [62.3, 70.4, 68.9, 72.7], "The girl at the fence", "wave", "at the muddy pigs", False),

# TILE r2c3 - inside the pig pen
("Yellow barrel in the pig pen", [69.0, 85.7, 75.0, 88.7], "The yellow barrel", "stand", "in the muddy pen", False),
("Sow lying in the sty", [70.3, 92.1, 76.6, 98.0], "The mother sow", "nurse", "her hungry piglets", False),
("Piglets suckling the sow", [72.3, 92.3, 75.3, 94.8], "The newborn piglets", "drink", "milk from their mother", True),
("Mud puddle in the pen", [76.6, 79.6, 85.2, 94.6], "The mud puddle", "cover", "the middle of the pen", False),
("Pig splashing in the mud", [74.8, 85.0, 79.1, 89.6], "The lively pig", "splash", "into the mud puddle", False),
("Hen standing on the pig", [77.8, 83.9, 81.9, 85.9], "The little hen", "balance", "on the pig's back", False),
("Pig lying in the mud puddle", [80.3, 83.3, 83.8, 87.5], "The pig in the puddle", "wallow", "in the cool mud", False),
("Pig sitting by the puddle", [79.4, 77.1, 85.2, 82.3], "The pig by the puddle", "sit", "at the edge of the mud", False),
("Piglet by the gate post", [72.8, 77.1, 75.9, 79.9], "The piglet by the gate post", "sniff", "at the wire fence", False),
("Piglet trotting to the barrel", [72.2, 80.2, 76.6, 83.2], "The piglet by the barrel", "run", "toward the yellow barrel", False),
("Pig peeking over the gate", [84.8, 82.1, 89.8, 86.3], "The curious pig", "look", "over the metal gate", False),
("Boy in the pig pen", [85.9, 85.1, 96.4, 88.9], "The boy in the green cap", "call", "the pigs to dinner", False),
("Metal gate of the pig pen", [85.0, 76.5, 97.3, 88.7], "The metal gate", "close", "off the muddy pen", False),
("Piglet crossing the pen", [84.8, 90.1, 89.8, 93.6], "The piglet in a hurry", "hurry", "across the pen", False),
("Piglet in the corner of the pen", [90.3, 91.6, 97.3, 96.7], "The piglet in the corner", "wag", "its curly tail", False),
("Chainsaw in his hands", [7.5, 65.1, 9.1, 68.4], "The chainsaw", "roar", "through the tree trunk", False),
("Food bowl by the barn door", [38.1, 52.0, 39.2, 53.1], "The food bowl", "sit", "by the barn door", False),
("Milk churn in the farmer's hand", [44.2, 45.3, 48.5, 46.8], "The milk churn", "swing", "in the farmer's hand", False),
("Concrete base of the windmill", [41.2, 58.4, 45.2, 67.0], "The concrete base", "anchor", "the windmill tower", False),
("Saddle on the horse", [89.4, 4.0, 92.6, 7.2], "The leather saddle", "sit", "on the horse's back", False),
]
