# Page 23 — nursery cross-section: dorm/bathroom upstairs, cafeteria and
# playroom downstairs. Boxes read off tiler grid labels, per tile.
# (name, [ymin, xmin, ymax, xmax], subject, bare-infinitive verb, rest, plural)

P = [
    ('Dark blue starry curtains', [0.0, 0.0, 22.3, 12.7], 'The starry curtains', 'hang', 'across the tall window', False),
    ('Boy opening the curtains', [4.4, 3.1, 17.9, 10.6], 'The boy at the window', 'pull', 'the curtains open', False),
    ('Tall blue bookcase', [1.6, 12.6, 22.5, 24.5], 'The tall bookcase', 'hold', 'rows of picture books', False),
    ('Row of books on the top shelf', [4.4, 14.1, 8.7, 22.7], 'The row of books', 'line', 'the top shelf', True),
    ('Picture book with a red cover', [10.0, 18.6, 13.6, 22.5], 'The picture book', 'lean', 'against the other books', False),
    ('Books poster on the wall', [1.3, 24.4, 15.3, 33.5], 'The books poster', 'hang', 'above the sofa', False),
    ('Woman reading on the sofa', [4.7, 27.6, 16.5, 36.4], 'The woman on the sofa', 'read', 'a story out loud', False),
    ('Girl listening on the sofa', [7.5, 33.0, 15.5, 36.4], 'The girl on the sofa', 'listen', 'to the story', False),
    ('Dark blue sofa', [4.7, 25.7, 17.8, 36.4], 'The dark blue sofa', 'hold', 'the woman and the girl', False),
    ('Child asleep under a purple blanket', [21.5, 0.0, 30.9, 10.8], 'The sleeping child', 'sleep', 'under a purple blanket', False),
    ('Purple spotted blanket', [23.4, 3.3, 30.4, 10.7], 'The purple blanket', 'cover', 'the sleeping child', False),
    ('Child sleeping with brown hair', [23.6, 8.9, 34.8, 20.5], 'The child with brown hair', 'sleep', 'soundly on the mat', False),
    ('Green striped blanket', [24.6, 8.9, 32.7, 15.8], 'The green striped blanket', 'cover', 'the sleeping child', False),
    ('Blond child sleeping', [26.4, 0.4, 35.5, 8.7], 'The blond child', 'sleep', 'on the sleeping mat', False),
    ('Green polka dot cushion', [27.4, 4.7, 30.9, 7.8], 'The green spotted cushion', 'cushion', "the sleeping child's head", False),
    ('Girl hugging a soft toy', [25.4, 15.6, 34.8, 22.5], 'The girl with the soft toy', 'hug', 'her toy tight', False),
    ('Shoes beside the sleeping mats', [30.7, 6.7, 34.1, 10.6], 'The pair of shoes', 'wait', 'beside the sleeping mat', True),
    ('Child sleeping under an egg print blanket', [22.0, 21.7, 32.7, 33.5], 'The child under the egg blanket', 'sleep', 'peacefully on the mat', False),
    ('Yellow egg print blanket', [22.5, 26.4, 30.7, 33.5], 'The egg print blanket', 'cover', 'the sleeping child', False),
    ('Small shoes by the mats', [30.6, 21.3, 33.4, 24.5], 'The small shoes', 'sit', 'beside the mat', True),
    ('Green sleeping mat', [21.5, 33.5, 25.9, 36.4], 'The green sleeping mat', 'lie', 'empty on the floor', False),
    ('Dreamcatcher on the wall', [1.6, 28.5, 11.5, 36.9], 'The dreamcatcher', 'hang', 'above the bookcase', False),
    ('Feathers on the dreamcatcher', [7.5, 30.4, 11.5, 35.0], 'The dreamcatcher feathers', 'dangle', 'beneath the hoop', True),
    ('Round wall clock', [0.0, 39.4, 8.5, 47.0], 'The round clock', 'show', 'the time on the wall', False),
    ('Owl picture in a frame', [3.5, 51.5, 16.3, 61.6], 'The owl picture', 'hang', 'on the wall', False),
    ('Boy reading in an armchair', [23.6, 30.7, 36.4, 44.9], 'The boy in the armchair', 'read', 'a picture book', False),
    ('Green spotted armchair', [22.5, 40.4, 36.4, 49.8], 'The green armchair', 'hold', 'the reading boy', False),
    ('Books stacked on the floor', [30.6, 44.3, 34.3, 49.3], 'The stack of books', 'sit', 'beside the armchair', False),
    ('Plate of biscuits', [21.5, 45.1, 23.6, 49.3], 'The plate of biscuits', 'sit', 'on the floor', False),
    ('Wall lamp above the armchair', [17.6, 44.9, 21.1, 51.8], 'The wall lamp', 'light', 'the reading corner', False),
    ('Woman in a pink cardigan in the doorway', [8.0, 34.0, 26.0, 45.4], 'The woman in the doorway', 'walk', 'in through the door', False),
    ('Open wooden door', [3.0, 34.0, 26.9, 45.6], 'The wooden door', 'stand', 'wide open', False),
    ('Girl in a pink dress walking upstairs', [25.9, 55.7, 39.3, 66.2], 'The girl in the pink dress', 'climb', 'the stairs', False),
    ('Stuffed toy carried up the stairs', [27.1, 56.8, 30.9, 61.6], 'The stuffed elephant', 'dangle', "from the girl's hand", False),
    ('First aid cabinet on the wall', [1.3, 51.2, 12.7, 60.9], 'The first aid cabinet', 'hang', 'on the corridor wall', False),
    ('Red cross symbol on the cabinet', [3.9, 53.5, 6.6, 57.1], 'The red cross symbol', 'mark', 'the first aid cabinet', False),
    ('White wash basin in the corridor', [10.4, 52.6, 18.5, 60.7], 'The white wash basin', 'stand', 'beside the first aid cabinet', False),
    ('Wooden coat hooks', [0.0, 63.4, 5.8, 67.2], 'The wooden coat hooks', 'line', 'the top of the wall', True),
    ('Mobile of hanging fish', [4.6, 63.2, 24.6, 72.5], 'The fish mobile', 'hang', 'from the ceiling', False),
    ('Purple octopus on the mobile', [8.9, 65.4, 12.7, 69.2], 'The purple octopus', 'dangle', 'at the top of the mobile', False),
    ('Blue fish on the mobile', [12.0, 66.6, 15.6, 69.8], 'The blue fish', 'hang', 'below the octopus', False),
    ('Girl washing her hands', [12.9, 71.0, 23.6, 79.6], 'The girl at the sink', 'wash', 'her hands under the tap', False),
    ('White sink with a running tap', [14.6, 71.8, 22.7, 80.1], 'The white sink', 'run', 'with warm water', False),
    ('Boy drying his hands', [11.6, 82.7, 22.3, 92.4], 'The boy at the second sink', 'dry', 'his hands with a towel', False),
    ('Second white sink', [14.8, 83.8, 22.5, 92.1], 'The second sink', 'stand', 'beside the first one', False),
    ('Cupboards above the sinks', [0.0, 61.3, 8.4, 100.0], 'The bathroom cupboards', 'hold', 'spare towels and soap', False),
    ('Folded towels in the cupboard', [0.4, 82.8, 4.4, 92.3], 'The folded towels', 'stack', 'neatly in the cupboard', True),
    ('Hanging plant above the cupboards', [0.7, 87.0, 8.9, 96.4], 'The hanging plant', 'trail', 'down from the shelf', False),
    ('Small potted plant', [0.4, 71.3, 4.1, 76.7], 'The small potted plant', 'sit', 'on the cupboard shelf', False),
    ('Boy running along the corridor', [22.0, 90.1, 32.9, 100.0], 'The running boy', 'dash', 'along the corridor', False),
    ('Boy brushing his teeth', [13.6, 74.5, 24.4, 82.7], 'The boy brushing his teeth', 'brush', 'his teeth at the sink', False),
    ("Toothbrush in the boy's hand", [15.5, 75.3, 17.3, 77.6], 'The toothbrush', 'scrub', "against the boy's teeth", False),
    ('Girl waiting for the sink', [21.1, 70.5, 26.0, 76.5], 'The waiting girl', 'wait', 'her turn at the sink', False),
    ('Bin beside the sinks', [21.5, 78.7, 25.9, 84.7], 'The rubbish bin', 'stand', 'beside the sinks', False),
    ('Box of tissues on the counter', [27.4, 87.9, 32.4, 92.4], 'The box of tissues', 'sit', 'on the bathroom counter', False),
    ('Grey changing table', [26.7, 79.6, 39.3, 100.0], 'The changing table', 'stand', 'at the end of the bathroom', False),
    ('Baby lying on the changing table', [27.7, 89.1, 33.1, 100.0], 'The baby on the changing table', 'lie', 'still on the mat', False),
    ('Woman changing the baby', [22.5, 96.9, 33.6, 100.0], 'The woman at the changing table', 'change', "the baby's nappy", False),
    ('Globe on the shelf', [17.6, 92.6, 23.4, 100.0], 'The globe', 'sit', 'on the bathroom shelf', False),
    ('Toilet cubicles', [17.6, 89.1, 39.3, 100.0], 'The toilet cubicles', 'stand', 'in a row', True),
    ('Girl leaving a toilet cubicle', [27.1, 89.5, 36.4, 94.0], 'The girl leaving the cubicle', 'step', 'out of the toilet cubicle', False),
    ('Girl with a bow entering a cubicle', [26.7, 92.4, 36.6, 97.2], 'The girl with the bow', 'enter', 'the toilet cubicle', False),
    ('Toilet roll holder', [30.7, 96.9, 34.1, 100.0], 'The toilet roll holder', 'hold', 'a fresh roll of paper', False),
    ('Second child sleeping under a green blanket', [30.9, 0.0, 36.4, 6.7], 'The second sleeping child', 'sleep', 'under a striped blanket', False),
    ('Plate of biscuits on the floor', [33.8, 8.4, 37.2, 14.9], 'The second plate of biscuits', 'sit', 'on the wooden floor', False),
    ('Round wall clock above the door', [40.7, 12.6, 47.4, 20.5], 'The kitchen clock', 'show', 'the time above the door', False),
    ('Doorway to the outside', [43.5, 12.9, 66.9, 25.9], 'The open doorway', 'lead', 'out to the playground', False),
    ('Chef carrying a tray', [55.4, 13.5, 69.6, 24.5], 'The chef with the tray', 'carry', 'a tray of food inside', False),
    ('Tray carried by the chef', [59.4, 16.0, 63.6, 22.7], "The chef's tray", 'balance', 'on his hands', False),
    ('Kitchen shelf with jars', [33.6, 0.0, 44.4, 10.6], 'The kitchen shelf', 'hold', 'rows of storage jars', False),
    ('Row of storage jars', [35.5, 0.4, 42.1, 8.7], 'The storage jars', 'stand', 'in a neat row', True),
    ('Stack of plates on the shelf', [45.4, 0.0, 55.4, 5.9], 'The stack of plates', 'wait', 'to be used at lunch', False),
    ('Stack of bowls below the plates', [48.4, 0.0, 56.6, 6.4], 'The stack of bowls', 'sit', 'beneath the plates', False),
    ('Woman in a yellow apron serving food', [55.7, 0.0, 69.6, 8.8], 'The dinner lady', 'serve', 'food from the counter', False),
    ('Serving counter with hot food', [55.9, 1.6, 68.9, 18.9], 'The serving counter', 'hold', "the day's hot lunch", False),
    ('Girl reaching up for food', [56.4, 8.9, 68.7, 15.7], 'The girl reaching up', 'reach', 'up for her plate', False),
    ('Tray of green vegetables', [58.9, 11.5, 62.7, 15.7], 'The tray of vegetables', 'steam', 'on the serving counter', False),
    ('Girl in a green top at the table', [55.5, 32.9, 66.6, 40.9], 'The girl in the green top', 'eat', 'her lunch at the table', False),
    ('Boy with dark hair eating', [55.7, 26.9, 68.9, 33.4], 'The boy with dark hair', 'eat', 'his lunch happily', False),
    ('Girl bending down to pick something up', [56.4, 40.7, 69.4, 47.7], 'The bending girl', 'bend', 'down to pick something up', False),
    ('Wooden dining table with food', [58.4, 22.7, 69.4, 44.5], 'The wooden dining table', 'hold', 'plates of food', False),
    ('Blue backpack on the floor', [59.6, 44.2, 65.7, 49.6], 'The blue backpack', 'lean', 'against a table leg', False),
    ('Boy walking with a lunch box', [59.6, 47.3, 69.4, 57.3], 'The boy with the lunch box', 'carry', 'his lunch box across the room', False),
    ('Red lunch box', [61.5, 48.5, 65.7, 53.7], 'The red lunch box', 'swing', "in the boy's hand", False),
    ('Girl and boy sitting together on a stool', [58.2, 63.4, 69.4, 71.3], 'The two friends on the stool', 'sit', 'together on the stool', True),
    ('Boy talking on the stairs', [59.4, 66.4, 69.8, 74.7], 'The boy on the stairs', 'talk', 'to his friend on the stairs', False),
    ('Girl listening on the stairs', [60.4, 73.4, 69.8, 79.6], 'The girl on the stairs', 'listen', 'to her friend', False),
    ('Wooden staircase', [30.3, 40.6, 69.7, 60.9], 'The wooden staircase', 'lead', 'up to the bedroom', False),
    ('Handrail of the staircase', [30.3, 40.6, 62.5, 53.5], 'The staircase handrail', 'run', 'up alongside the stairs', False),
    ('Girl carrying a soft toy up the stairs', [33.8, 61.6, 44.9, 68.9], 'The girl with the soft toy', 'carry', 'her toy up the stairs', False),
    ('Blue soft toy elephant', [35.5, 62.5, 38.4, 65.9], 'The soft toy elephant', 'dangle', "from the girl's arm", False),
    ('Wooden storage boxes under the stairs', [50.8, 61.3, 63.6, 74.2], 'The wooden storage boxes', 'sit', 'under the staircase', True),
    ('Girl bending down at the low table', [65.5, 46.6, 74.5, 55.4], 'The girl at the low table', 'bend', 'down over the table', False),
    ('Boy at the wooden table', [58.9, 51.7, 67.6, 55.6], 'The boy at the table', 'sit', 'at the low wooden table', False),
    ('Rows of drink cartons on the shelf', [65.7, 39.4, 74.2, 52.5], 'The rows of drink cartons', 'stack', 'up on the shelf', True),
    ('Green potted plant by the shelf', [65.7, 55.4, 78.0, 63.9], 'The green potted plant', 'grow', 'beside the drinks shelf', False),
    ('Boy playing on the floor', [79.4, 45.4, 92.4, 55.6], 'The boy on the floor', 'play', 'with his toy car', False),
    ('Toy car on the floor', [86.1, 51.5, 89.4, 55.2], 'The toy car', 'roll', 'across the wooden floor', False),
    ('Girl playing with a toy dog', [80.6, 56.1, 92.4, 65.4], 'The girl with the toy dog', 'play', 'with her soft toy dog', False),
    ('White toy dog', [82.7, 61.5, 90.1, 68.7], 'The white toy dog', 'sit', 'in front of the toy house', False),
    ('Toy dolls house', [78.0, 63.4, 88.7, 71.6], 'The toy dolls house', 'stand', 'on the floor', False),
    ('Boy playing beside the dolls house', [82.0, 71.6, 94.0, 79.6], 'The boy beside the dolls house', 'kneel', 'on the floor to play', False),
    ('Bin liner tied at the top', [42.4, 71.6, 51.9, 82.7], 'The tied bin liner', 'wait', 'to be taken outside', False),
    ('Small drinks shelf unit', [65.5, 72.9, 75.6, 84.4], 'The small drinks shelf', 'hold', 'rows of juice cartons', False),
    ('Cans of drink on the shelf', [65.7, 79.4, 76.1, 87.9], 'The cans of drink', 'stack', 'up in neat rows', True),
    ('Boy in a wheelchair at the party table', [40.4, 85.9, 55.9, 96.3], 'The boy in the wheelchair', 'sit', 'at the birthday table', False),
    ('Wheelchair wheel at the party', [46.6, 87.7, 57.1, 92.3], "The wheelchair's big wheel", 'rest', 'beside the table', False),
    ('Man in glasses at the party table', [37.7, 96.1, 51.5, 100.0], 'The man at the party table', 'clap', 'for the birthday child', False),
    ('Girl in a party hat', [21.5, 89.5, 29.7, 94.9], 'The girl in the party hat', 'wear', 'a bright party hat', False),
    ('Party hat with a pompom', [22.0, 90.1, 24.4, 92.6], 'The pointed party hat', 'sit', "on the girl's head", False),
    ('Woman serving lunch from the counter', [67.6, 0.0, 82.6, 8.4], 'The dinner lady behind the counter', 'serve', 'food to the children', False),
    ('Plate of food on the counter', [73.9, 4.6, 79.6, 10.9], 'The plate of food', 'wait', 'on the serving counter', False),
    ('Girl waiting with her plate', [70.6, 10.9, 84.5, 20.5], 'The girl with her plate', 'wait', 'in the lunch queue', False),
    ('Boy in green eating at the table', [70.1, 19.5, 84.7, 27.3], 'The boy in green at the table', 'eat', 'his lunch at the table', False),
    ('Girl running with a napkin', [73.6, 33.1, 88.7, 40.4], 'The running girl', 'wave', 'a napkin as she runs', False),
    ('White napkin in her hand', [73.4, 33.6, 78.0, 38.4], 'The white napkin', 'flutter', "in the girl's hand", False),
    ('Blue backpack under the table', [80.6, 27.3, 91.2, 34.5], 'The backpack under the table', 'lean', 'against a chair leg', False),
    ('Girl crawling on the floor', [85.9, 5.2, 97.2, 20.9], 'The crawling girl', 'crawl', 'across the cafeteria floor', False),
    ('Dropped plate on the floor', [86.6, 21.7, 91.0, 26.7], 'The dropped plate', 'lie', 'on the cafeteria floor', False),
    ('Spilled food on the floor', [88.4, 26.0, 91.7, 30.7], 'The spilled food', 'scatter', 'across the tiles', False),
    ('Drink cartons on the table', [92.4, 82.4, 100.0, 92.1], 'The drink cartons on the table', 'stand', 'in a row', True),
    ('Boy reaching for coins', [30.9, 42.9, 43.5, 51.9], 'The boy reaching for the coins', 'reach', 'down for the dropped coins', False),
    ('Coins scattered on the floor', [39.3, 44.5, 42.5, 51.8], 'The scattered coins', 'roll', 'across the floor', True),
    ('Girl bending over to help', [31.6, 47.5, 45.4, 58.5], 'The girl bending over', 'bend', 'down to help pick up the coins', False),
    ('Vending machine with snacks', [44.5, 51.5, 52.6, 58.9], 'The vending machine', 'hold', 'rows of coloured snacks', False),
    ('Girl in a yellow headscarf', [46.6, 47.5, 57.6, 55.2], 'The girl in the headscarf', 'choose', 'a snack from the shelf', False),
    ('Girl in a striped top choosing a snack', [46.4, 55.4, 58.0, 63.6], 'The girl choosing a snack', 'pick', 'a snack from the shelf', False),
    ('Boy walking away with a napkin', [59.6, 24.1, 71.6, 34.1], 'The boy with the napkin', 'carry', 'a napkin across the room', False),
    ('Girl bending down near the stairs', [59.9, 33.6, 73.6, 42.5], 'The girl bending near the stairs', 'bend', 'down near the staircase', False),
    ('Boy and girl sitting on the stairs', [66.4, 61.5, 76.5, 70.5], 'The two children on the stairs', 'sit', 'together on the bottom step', True),
    ('Snack crates below the stairs', [65.2, 47.5, 74.2, 60.1], 'The crates of snacks', 'stack', 'up under the stairs', True),
    ('Small potted tree', [64.5, 51.5, 100.0, 68.9], 'The small potted tree', 'stand', 'beside the snack shelf', False),
    ('Boy playing with a toy car on the floor', [79.4, 68.7, 93.5, 78.0], 'The boy with the toy car', 'push', 'his toy car along the floor', False),
    ('Toy car on the wooden floor', [86.6, 68.5, 90.7, 72.7], 'The little toy car', 'zoom', 'across the wooden floor', False),
    ('Girl kneeling with a toy dog', [80.6, 79.6, 93.7, 88.9], 'The girl with the toy dog', 'kneel', 'beside the toy dolls house', False),
    ('Boy kneeling by the dolls house', [83.3, 89.6, 97.4, 100.0], 'The boy by the dolls house', 'kneel', 'on the floor to play', False),
    ('Girl covering her mouth in surprise', [65.7, 74.4, 78.0, 82.1], 'The surprised girl', 'gasp', 'in surprise', False),
    ('Boy sitting on a low box', [70.8, 78.9, 82.4, 89.1], 'The boy on the low box', 'sit', 'quietly on the box', False),
    ('Man in glasses clapping', [69.2, 91.6, 84.5, 100.0], 'The clapping man', 'clap', 'along with the party song', False),
    ('Stacked wooden building blocks', [83.3, 90.1, 100.0, 100.0], 'The stacked wooden blocks', 'tower', 'up on the playroom floor', True),
    ('Boy in a striped top playing with blocks', [82.0, 79.4, 97.7, 90.6], 'The boy playing with blocks', 'stack', 'the wooden blocks', False),
    ('Girl reaching for a block', [82.4, 71.9, 96.1, 82.4], 'The girl reaching for a block', 'reach', 'for a wooden block', False),
    ('Slippers by the sleeping mats', [16.9, 5.0, 19.6, 8.7], 'The slippers', 'wait', 'beside the sleeping mat', True),
    ('Rug on the reading room floor', [15.5, 22.3, 22.1, 33.5], 'The patterned rug', 'lie', 'in front of the sofa', False),
    ('Lamp beside the sofa', [1.6, 34.0, 5.5, 37.2], 'The reading lamp', 'stand', 'beside the sofa', False),
    ('Fish tank chime near the bathroom', [4.6, 62.8, 8.0, 65.4], 'The fish chime', 'sway', 'gently near the bathroom door', False),
    ('Soap dispenser by the sinks', [11.5, 68.9, 14.6, 71.5], 'The soap dispenser', 'sit', 'beside the sink', False),
    ('Mirror above the sinks', [1.6, 71.6, 10.4, 91.0], 'The bathroom mirror', 'hang', 'above the row of sinks', False),
    ('Window blinds in the bathroom', [0.0, 88.5, 8.5, 100.0], 'The window blinds', 'let', 'light into the bathroom', False),
    ('Cloud shapes outside the window', [4.4, 92.4, 7.5, 97.5], 'The clouds outside', 'drift', 'past the bathroom window', True),
    ('Coat pegs on the wall', [0.0, 63.9, 4.6, 67.0], 'The coat pegs', 'wait', 'empty on the wall', True),
    ('Rubbish bin lid', [21.8, 79.6, 24.3, 83.5], 'The bin lid', 'sit', 'half open on the bin', False),
    ('Playground swing seen through the window', [55.7, 20.7, 61.2, 25.0], 'The distant swing', 'hang', 'still in the playground', False),
    ('Toy car outside on the road', [56.4, 68.9, 60.1, 74.4], 'The little orange car', 'drive', 'past the nursery window', False),
    ('Sunflower window decorations', [42.5, 43.3, 47.5, 48.3], 'The sunflower decorations', 'brighten', 'the cafeteria window', True),
    ('Second row of sunflower decorations', [42.7, 60.5, 47.5, 65.4], 'The second sunflower decoration', 'sit', 'on the window ledge', False),
    ('Storage jars on the kitchen shelf', [35.8, 0.4, 42.7, 8.7], 'The row of jars', 'hold', 'flour and sugar for baking', True),
    ('Cutlery on the dining table', [61.3, 25.7, 64.1, 28.3], 'The cutlery on the table', 'wait', 'beside the plates', True),
    ('Water jug on the dining table', [58.9, 34.5, 62.0, 37.4], 'The water jug', 'stand', 'in the middle of the table', False),
    ('Chair pushed under the table', [64.1, 40.4, 68.7, 44.5], 'The empty chair', 'sit', 'pushed under the table', False),
    ('Storage boxes stacked under the stairs', [50.8, 61.6, 57.1, 68.1], 'The stacked storage boxes', 'sit', 'in the space under the stairs', True),
    ('Lower storage boxes', [61.5, 61.3, 63.6, 68.9], 'The lower storage box', 'hold', 'spare toys and games', False),
    ('Vending machine coin slot', [46.8, 51.8, 49.3, 53.9], 'The coin slot', 'wait', 'for a coin', False),
    ('Snack packets in the vending machine', [45.4, 52.5, 51.9, 57.5], 'The snack packets', 'line', 'the shelves of the machine', True),
    ('Bottled drinks in a crate', [88.7, 84.7, 96.1, 91.9], 'The bottled drinks', 'stand', 'in a plastic crate', True),
    ('Juice cartons stacked in a crate', [88.9, 74.7, 96.3, 82.4], 'The juice cartons', 'stack', 'neatly in their crate', True),
    ('Tins stacked on the low table', [86.6, 61.3, 92.6, 68.9], 'The stacked tins', 'sit', 'on the low table', True),
    ('Wall banner reading Happy Birthday', [40.7, 84.2, 45.6, 92.4], 'The birthday banner', 'hang', 'on the party wall', False),
    ('Balloon decorations near the party table', [37.4, 78.9, 41.4, 82.4], 'The blue balloon', 'bob', 'above the party table', False),
    ('Second balloon near the party table', [37.9, 89.3, 42.1, 92.6], 'The second balloon', 'float', 'above the birthday table', False),
    ('Paper crown on the birthday child', [36.4, 92.4, 39.6, 96.1], 'The paper crown', 'sit', "on the birthday child's head", False),
    ('Plates of party food', [39.3, 88.4, 43.1, 94.5], 'The plates of party food', 'cover', 'the birthday table', True),
    ("Boy's red backpack on the wheelchair", [40.9, 87.9, 46.6, 92.6], 'The red backpack', 'hang', 'from the back of the wheelchair', False),
    ('Wooden blocks scattered on the floor', [88.4, 92.1, 95.4, 98.7], 'The scattered wooden blocks', 'lie', 'across the playroom floor', True),
    ('Rug in the playroom', [78.5, 66.6, 100.0, 85.9], 'The playroom rug', 'cover', 'the wooden floor', False),
    ('Window view of the garden tree', [40.9, 71.4, 47.5, 78.7], 'The garden tree', 'stand', 'outside the cafeteria window', False),
    ('Bird on the garden fence', [42.4, 76.7, 44.5, 79.1], 'The garden bird', 'perch', 'on the distant fence', False),
]
