# Page 10 - the city park: the cafe terrace, the fountain, the kite meadow,
# the puppet theatre, the ice cream kiosk, the sandpit and the playground.
# Boxes read straight off the tiler grid labels, one block per tile.
P = [

# TILE r0c0
("Red brick cafe building", [0.0, 0.0, 15.3, 24.4], "The red brick cafe building", "stand", "at the edge of the park", False),
("Arched cafe window", [0.2, 0.8, 6.5, 5.4], "The arched cafe window", "look", "out over the terrace", False),
("Open cafe doorway", [0.5, 6.0, 13.5, 10.2], "The open cafe doorway", "lead", "into the cafe", False),
("Tall window with blue panes", [1.4, 10.5, 7.7, 14.0], "The tall window with blue panes", "catch", "the morning sun", False),
("Restroom sign", [2.1, 19.1, 4.7, 22.8], "The restroom sign", "point", "the way to the toilets", False),
("Woman in the red dress", [0.9, 24.1, 10.7, 26.5], "The woman in the red dress", "wait", "in the doorway", False),
("Grandmother in the pink cardigan", [5.1, 0.5, 10.0, 3.1], "The grandmother in the pink cardigan", "lean", "on the window ledge", False),
("Waiter in the white shirt", [3.5, 6.9, 16.5, 10.3], "The waiter in the white shirt", "carry", "the drinks to the table", False),
("Two glasses of juice", [7.7, 6.5, 9.5, 8.2], "The two glasses of juice", "wobble", "on the waiter's tray", True),
("Blue striped parasol", [6.5, 8.3, 12.3, 22.1], "The blue striped parasol", "shade", "the cafe tables", False),
("Empty yellow chair", [12.3, 1.2, 23.3, 4.5], "The empty yellow chair", "wait", "for another guest", False),
("Round cafe table by the wall", [18.4, 4.5, 24.4, 10.3], "The round cafe table by the wall", "hold", "the cups and the cakes", False),
("Man in the green jacket", [13.3, 2.9, 23.3, 6.6], "The man in the green jacket", "drink", "his coffee", False),
("Plate of cake", [18.6, 8.3, 19.8, 9.9], "The plate of cake", "sit", "in the middle of the table", False),
("Girl in the red top", [14.2, 9.7, 24.4, 12.7], "The girl in the red top", "sit", "with her back to the park", False),
("Round cafe table by the parasol", [19.5, 17.1, 24.4, 23.6], "The round cafe table by the parasol", "stand", "under the striped parasol", False),
("Woman in the blue top", [13.3, 18.4, 22.1, 21.4], "The woman in the blue top", "wave", "to a friend", False),
("Grandfather in the wheelchair", [14.2, 22.8, 24.7, 26.7], "The grandfather in the wheelchair", "enjoy", "his afternoon tea", False),
("Pink flowering hedge", [24.2, 0.0, 30.9, 20.4], "The pink flowering hedge", "border", "the cafe terrace", False),
("Yellow flowering plant", [27.2, 10.8, 31.6, 14.2], "The yellow flowering plant", "grow", "among the pink flowers", False),
("Duck near the hedge", [31.4, 22.4, 34.0, 24.4], "The duck near the hedge", "waddle", "across the grass", False),

# TILE r0c1
("Man in the blue T-shirt", [0.9, 27.4, 13.0, 30.2], "The man in the blue T-shirt", "hold", "the little boy's hand", False),
("Toddler in the yellow shirt", [6.2, 26.9, 13.4, 28.6], "The toddler in the yellow shirt", "walk", "beside his father", False),
("Girl in the green T-shirt", [15.3, 29.1, 25.8, 33.4], "The girl in the green T-shirt", "skip", "along the path", False),
("Sandy path through the park", [10.4, 22.0, 36.0, 36.5], "The sandy path through the park", "wind", "between the lawns", False),
("Round bush by the path", [0.7, 31.3, 8.6, 34.3], "The round bush by the path", "grow", "beside the cafe terrace", False),
("Hedge behind the path", [0.4, 35.0, 5.3, 38.0], "The hedge behind the path", "hide", "the far side of the park", False),
("Weeping willow tree", [0.0, 39.0, 15.1, 51.6], "The weeping willow tree", "hang", "over the meadow", False),
("Birch tree trunk", [7.4, 43.8, 16.5, 46.4], "The birch tree trunk", "rise", "behind the guitar player", False),
("Man in the yellow T-shirt", [13.0, 41.8, 21.6, 45.8], "The man in the yellow T-shirt", "play", "the guitar under the tree", False),
("Brown guitar", [17.4, 41.9, 20.2, 45.0], "The brown guitar", "ring", "out across the meadow", False),
("Music notes above the guitar", [15.1, 40.4, 17.2, 41.3], "The music notes above the guitar", "float", "into the air", True),
("Yellow dog by the path", [16.2, 37.1, 23.0, 40.1], "The yellow dog by the path", "listen", "to the music", False),
("Girl in the pink top", [22.0, 46.2, 28.6, 49.8], "The girl in the pink top", "run", "with her kite string", False),
("Wooden park bench", [28.1, 36.0, 35.5, 43.0], "The wooden park bench", "face", "the fountain", False),
("Bushes beside the path", [13.7, 33.7, 28.6, 39.3], "The bushes beside the path", "line", "the edge of the meadow", True),

# TILE r0c2
("Tall tree with a thick trunk", [0.0, 52.9, 10.7, 59.0], "The tall tree with a thick trunk", "shade", "the top of the meadow", False),
("Pink kite", [1.6, 58.9, 6.9, 62.1], "The pink kite", "smile", "down at the park", False),
("Long kite string", [2.5, 51.0, 20.2, 60.0], "The long kite string", "stretch", "up into the sky", False),
("Large bat kite", [0.7, 67.7, 7.2, 73.4], "The large bat kite", "swoop", "over the treetops", False),
("Small bat kite", [6.5, 65.2, 10.7, 68.9], "The small bat kite", "follow", "the bigger bat", False),
("Man in the black T-shirt", [13.7, 54.6, 26.7, 57.6], "The man in the black T-shirt", "fly", "the two bat kites", False),
("Black and white dog", [15.3, 60.6, 21.1, 66.8], "The black and white dog", "leap", "across the grass", False),
("Wooden stick", [16.2, 65.2, 18.1, 67.1], "The wooden stick", "stick", "out of the dog's mouth", False),
("Puppet theatre booth", [17.4, 68.3, 36.0, 74.8], "The puppet theatre booth", "stand", "on the edge of the meadow", False),
("Puppet theatre sign", [18.1, 68.8, 21.1, 72.0], "The puppet theatre sign", "announce", "the next show", False),
("Green frog puppet", [25.1, 68.8, 27.2, 70.0], "The green frog puppet", "pop", "up on the little stage", False),
("White puppet", [25.1, 70.3, 27.6, 71.4], "The white puppet", "bow", "to the children", False),
("Woman beside the puppet theatre", [18.3, 72.3, 28.6, 74.8], "The woman beside the puppet theatre", "watch", "the show begin", False),
("Boy in the red T-shirt", [23.4, 63.0, 30.4, 65.2], "The boy in the red T-shirt", "hurry", "towards the puppet show", False),
("Woman in the black hat", [26.2, 59.5, 36.0, 61.8], "The woman in the black hat", "sit", "on the grass with the children", False),
("Blue pushchair", [28.6, 55.2, 36.0, 58.4], "The blue pushchair", "park", "behind the little audience", False),
("White clouds", [0.0, 56.3, 4.4, 78.0], "The white clouds", "drift", "across the blue sky", True),

# TILE r0c3
("Woman with the shoulder bag", [8.8, 76.5, 20.4, 81.3], "The woman with the shoulder bag", "carry", "a basket across the grass", False),
("Wicker basket", [13.7, 79.3, 16.0, 81.4], "The wicker basket", "swing", "in the woman's hands", False),
("Boy in the orange T-shirt", [4.4, 83.6, 12.5, 86.0], "The boy in the orange T-shirt", "chase", "the football", False),
("Black dog on the hill", [6.9, 86.8, 14.6, 91.1], "The black dog on the hill", "jump", "for the ball", False),
("Black and white football", [4.1, 91.1, 6.5, 93.0], "The black and white football", "sail", "through the air", False),
("Girl in the yellow top", [9.5, 95.6, 17.9, 98.9], "The girl in the yellow top", "kick", "the ball back", False),
("White terrier", [16.9, 81.3, 20.2, 84.0], "The white terrier", "trot", "across the lawn", False),
("Tree on the hill", [0.7, 83.7, 4.8, 89.3], "The tree on the hill", "stand", "at the top of the slope", False),
("Ice cream kiosk", [13.7, 82.5, 36.0, 98.9], "The ice cream kiosk", "sell", "ice cream in the park", False),
("Seagull on the kiosk roof", [19.7, 93.8, 21.6, 95.3], "The seagull on the kiosk roof", "perch", "above the customers", False),
("Ice cream poster", [24.4, 81.1, 28.8, 83.1], "The ice cream poster", "show", "a big vanilla cone", False),
("Customer in the orange top", [26.2, 90.2, 36.0, 92.7], "The customer in the orange top", "point", "at the flavours", False),
("Ice cream seller", [25.5, 92.2, 31.3, 94.5], "The ice cream seller", "scoop", "the ice cream", False),
("Man buying ice cream", [25.3, 96.1, 36.0, 98.5], "The man buying ice cream", "pay", "at the counter", False),
("Ice cream cone", [27.2, 96.2, 29.0, 97.2], "The ice cream cone", "melt", "in the sunshine", False),
("Yellow bottle on the counter", [28.3, 89.0, 30.7, 89.9], "The yellow bottle on the counter", "stand", "next to the freezer", False),
("Ice cream freezer", [28.6, 83.4, 33.2, 87.4], "The ice cream freezer", "keep", "the ice cream cold", False),
("Doll on the grass", [29.0, 74.8, 32.3, 76.0], "The doll on the grass", "lie", "beside the puppet theatre", False),

]
