# Page 10 - the city park: the cafe terrace, the fountain, the kite meadow,
# the puppet theatre, the ice cream kiosk, the sandpit and the playground.
# Boxes read straight off the tiler grid labels, one block per tile.
P = [

# TILE r0c0
("Red brick cafe building", [0.0, 0.0, 15.3, 24.4], "The red brick cafe building", "stand", "at the edge of the park", False),
("Arched cafe window", [0.2, 0.8, 6.5, 5.4], "The arched cafe window", "look", "out over the terrace", False),
("Open cafe doorway", [0.5, 6.0, 13.5, 10.2], "The open cafe doorway", "lead", "into the cafe", False),
("Tall window with blue panes", [1.4, 10.5, 7.7, 14.0], "The tall window with blue panes", "catch", "the morning sun", False),
("Restroom sign", [2.1, 19.1, 4.7, 22.8], "The restroom sign", "point", "the way to the toilets", False),
("Woman in the red dress", [0.9, 24.1, 10.7, 26.5], "The woman in the red dress", "wait", "in the doorway", False),
("Grandmother in the pink cardigan", [5.1, 0.5, 10.0, 3.1], "The grandmother in the pink cardigan", "lean", "on the window ledge", False),
("Waiter in the white shirt", [3.5, 6.9, 16.5, 10.3], "The waiter in the white shirt", "carry", "the drinks to the table", False),
("Two glasses of juice", [7.7, 6.5, 9.5, 8.2], "The two glasses of juice", "wobble", "on the waiter's tray", True),
("Blue striped parasol", [6.5, 8.3, 12.3, 22.1], "The blue striped parasol", "shade", "the cafe tables", False),
("Empty yellow chair", [12.3, 1.2, 23.3, 4.5], "The empty yellow chair", "wait", "for another guest", False),
("Round cafe table by the wall", [18.4, 4.5, 24.4, 10.3], "The round cafe table by the wall", "hold", "the cups and the cakes", False),
("Man in the green jacket", [13.3, 2.9, 23.3, 6.6], "The man in the green jacket", "drink", "his coffee", False),
("Plate of cake", [18.6, 8.3, 19.8, 9.9], "The plate of cake", "sit", "in the middle of the table", False),
("Girl in the red top", [14.2, 9.7, 24.4, 12.7], "The girl in the red top", "sit", "with her back to the park", False),
("Round cafe table by the parasol", [19.5, 17.1, 24.4, 23.6], "The round cafe table by the parasol", "stand", "under the striped parasol", False),
("Woman in the blue top", [13.3, 18.4, 22.1, 21.4], "The woman in the blue top", "wave", "to a friend", False),
("Grandfather in the wheelchair", [14.2, 22.8, 24.7, 26.7], "The grandfather in the wheelchair", "enjoy", "his afternoon tea", False),
("Pink flowering hedge", [24.2, 0.0, 30.9, 20.4], "The pink flowering hedge", "border", "the cafe terrace", False),
("Yellow flowering plant", [27.2, 10.8, 31.6, 14.2], "The yellow flowering plant", "grow", "among the pink flowers", False),
("Duck near the hedge", [31.4, 22.4, 34.0, 24.4], "The duck near the hedge", "waddle", "across the grass", False),

# TILE r0c1
("Man in the blue T-shirt", [0.9, 27.4, 13.0, 30.2], "The man in the blue T-shirt", "hold", "the little boy's hand", False),
("Toddler in the yellow shirt", [6.2, 26.9, 13.4, 28.6], "The toddler in the yellow shirt", "walk", "beside his father", False),
("Girl in the green T-shirt", [15.3, 29.1, 25.8, 33.4], "The girl in the green T-shirt", "skip", "along the path", False),
("Sandy path through the park", [10.4, 22.0, 36.0, 36.5], "The sandy path through the park", "wind", "between the lawns", False),
("Round bush by the path", [0.7, 31.3, 8.6, 34.3], "The round bush by the path", "grow", "beside the cafe terrace", False),
("Hedge behind the path", [0.4, 35.0, 5.3, 38.0], "The hedge behind the path", "hide", "the far side of the park", False),
("Weeping willow tree", [0.0, 39.0, 15.1, 51.6], "The weeping willow tree", "hang", "over the meadow", False),
("Birch tree trunk", [7.4, 43.8, 16.5, 46.4], "The birch tree trunk", "rise", "behind the guitar player", False),
("Man in the yellow T-shirt", [13.0, 41.8, 21.6, 45.8], "The man in the yellow T-shirt", "play", "the guitar under the tree", False),
("Brown guitar", [17.4, 41.9, 20.2, 45.0], "The brown guitar", "ring", "out across the meadow", False),
("Music notes above the guitar", [15.1, 40.4, 17.2, 41.3], "The music notes above the guitar", "float", "into the air", True),
("Yellow dog by the path", [16.2, 37.1, 23.0, 40.1], "The yellow dog by the path", "listen", "to the music", False),
("Girl in the pink top", [22.0, 46.2, 28.6, 49.8], "The girl in the pink top", "run", "with her kite string", False),
("Wooden park bench", [28.1, 36.0, 35.5, 43.0], "The wooden park bench", "face", "the fountain", False),
("Bushes beside the path", [13.7, 33.7, 28.6, 39.3], "The bushes beside the path", "line", "the edge of the meadow", True),

# TILE r0c2
("Tall tree with a thick trunk", [0.0, 52.9, 10.7, 59.0], "The tall tree with a thick trunk", "shade", "the top of the meadow", False),
("Pink kite", [1.6, 58.9, 6.9, 62.1], "The pink kite", "smile", "down at the park", False),
("Long kite string", [2.5, 51.0, 20.2, 60.0], "The long kite string", "stretch", "up into the sky", False),
("Large bat kite", [0.7, 67.7, 7.2, 73.4], "The large bat kite", "swoop", "over the treetops", False),
("Small bat kite", [6.5, 65.2, 10.7, 68.9], "The small bat kite", "follow", "the bigger bat", False),
("Man in the black T-shirt", [13.7, 54.6, 26.7, 57.6], "The man in the black T-shirt", "fly", "the two bat kites", False),
("Black and white dog", [15.3, 60.6, 21.1, 66.8], "The black and white dog", "leap", "across the grass", False),
("Wooden stick", [16.2, 65.2, 18.1, 67.1], "The wooden stick", "stick", "out of the dog's mouth", False),
("Puppet theatre booth", [17.4, 68.3, 36.0, 74.8], "The puppet theatre booth", "stand", "on the edge of the meadow", False),
("Puppet theatre sign", [18.1, 68.8, 21.1, 72.0], "The puppet theatre sign", "announce", "the next show", False),
("Green frog puppet", [25.1, 68.8, 27.2, 70.0], "The green frog puppet", "pop", "up on the little stage", False),
("White puppet", [25.1, 70.3, 27.6, 71.4], "The white puppet", "bow", "to the children", False),
("Woman beside the puppet theatre", [18.3, 72.3, 28.6, 74.8], "The woman beside the puppet theatre", "watch", "the show begin", False),
("Boy in the red T-shirt", [23.4, 63.0, 30.4, 65.2], "The boy in the red T-shirt", "hurry", "towards the puppet show", False),
("Woman in the black hat", [26.2, 59.5, 36.0, 61.8], "The woman in the black hat", "sit", "on the grass with the children", False),
("Blue pushchair", [28.6, 55.2, 36.0, 58.4], "The blue pushchair", "park", "behind the little audience", False),
("White clouds", [0.0, 56.3, 4.4, 78.0], "The white clouds", "drift", "across the blue sky", True),

# TILE r0c3
("Woman with the shoulder bag", [8.8, 76.5, 20.4, 81.3], "The woman with the shoulder bag", "carry", "a basket across the grass", False),
("Wicker basket", [13.7, 79.3, 16.0, 81.4], "The wicker basket", "swing", "in the woman's hands", False),
("Boy in the orange T-shirt", [4.4, 83.6, 12.5, 86.0], "The boy in the orange T-shirt", "chase", "the football", False),
("Black dog on the hill", [6.9, 86.8, 14.6, 91.1], "The black dog on the hill", "jump", "for the ball", False),
("Black and white football", [4.1, 91.1, 6.5, 93.0], "The black and white football", "sail", "through the air", False),
("Girl in the yellow top", [9.5, 95.6, 17.9, 98.9], "The girl in the yellow top", "kick", "the ball back", False),
("White terrier", [16.9, 81.3, 20.2, 84.0], "The white terrier", "trot", "across the lawn", False),
("Tree on the hill", [0.7, 83.7, 4.8, 89.3], "The tree on the hill", "stand", "at the top of the slope", False),
("Ice cream kiosk", [13.7, 82.5, 36.0, 98.9], "The ice cream kiosk", "sell", "ice cream in the park", False),
("Seagull on the kiosk roof", [19.7, 93.8, 21.6, 95.3], "The seagull on the kiosk roof", "perch", "above the customers", False),
("Ice cream poster", [24.4, 81.1, 28.8, 83.1], "The ice cream poster", "show", "a big vanilla cone", False),
("Customer in the orange top", [26.2, 90.2, 36.0, 92.7], "The customer in the orange top", "point", "at the flavours", False),
("Ice cream seller", [25.5, 92.2, 31.3, 94.5], "The ice cream seller", "scoop", "the ice cream", False),
("Man buying ice cream", [25.3, 96.1, 36.0, 98.5], "The man buying ice cream", "pay", "at the counter", False),
("Ice cream cone", [27.2, 96.2, 29.0, 97.2], "The ice cream cone", "melt", "in the sunshine", False),
("Yellow bottle on the counter", [28.3, 89.0, 30.7, 89.9], "The yellow bottle on the counter", "stand", "next to the freezer", False),
("Ice cream freezer", [28.6, 83.4, 33.2, 87.4], "The ice cream freezer", "keep", "the ice cream cold", False),
("Doll on the grass", [29.0, 74.8, 32.3, 76.0], "The doll on the grass", "lie", "beside the puppet theatre", False),


# TILE r1c0
("Old tree with the twisted trunk", [30.3, 0.0, 56.7, 10.2], "The old tree with the twisted trunk", "spread", "over the corner of the park", False),
("Cat stretching on the branch", [32.7, 4.5, 35.0, 8.0], "The cat stretching on the branch", "reach", "along the branch", False),
("Cat lying on the branch", [35.2, 2.6, 38.3, 6.2], "The cat lying on the branch", "doze", "in the shade", False),
("Wooden bench by the path", [33.1, 14.5, 40.1, 21.0], "The wooden bench by the path", "stand", "beside the sandy path", False),
("Red bag on the bench", [34.3, 17.6, 37.1, 19.8], "The red bag on the bench", "wait", "for its owner", False),
("Blue jacket on the bench", [37.8, 16.0, 39.5, 18.2], "The blue jacket on the bench", "lie", "across the seat", False),
("Green rubbish bin", [39.7, 13.3, 44.6, 15.7], "The green rubbish bin", "stand", "next to the bench", False),
("Jogger in the pink top", [38.3, 17.1, 49.7, 21.6], "The jogger in the pink top", "run", "along the path", False),
("Little girl in the red dress", [46.0, 20.2, 52.3, 22.5], "The little girl in the red dress", "look", "into the fountain", False),
("Man on the sun lounger", [47.6, 6.0, 55.5, 12.0], "The man on the sun lounger", "sunbathe", "under the old tree", False),
("Red deckchair", [49.7, 5.4, 56.2, 12.3], "The red deckchair", "lean", "back on the grass", False),
("Pond with the ducks", [56.7, 0.0, 69.7, 10.2], "The pond with the ducks", "glitter", "in the sunshine", False),
("Yellow ducklings", [61.6, 1.2, 63.7, 3.2], "The yellow ducklings", "paddle", "after their mother", True),
("Duck on the pond", [64.2, 3.1, 66.1, 4.9], "The duck on the pond", "swim", "between the reeds", False),
("Bulrushes at the water's edge", [57.6, 0.0, 66.6, 1.9], "The bulrushes at the water's edge", "sway", "in the breeze", True),
("Bench where the couple sit", [52.1, 15.1, 59.9, 20.4], "The bench where the couple sit", "face", "the sunny lawn", False),
("Man in the sunglasses", [50.5, 15.6, 57.2, 18.1], "The man in the sunglasses", "rest", "his arm on the bench", False),
("Woman with the red hair", [51.2, 17.4, 59.9, 20.1], "The woman with the red hair", "lean", "against her friend", False),
("Woman in the purple top", [60.1, 12.3, 69.7, 15.1], "The woman in the purple top", "look", "after the small children", False),
("Hedge along the path", [44.1, 12.3, 69.7, 19.1], "The hedge along the path", "run", "beside the walkway", False),

# TILE r1c1
("Round fountain pool", [39.7, 24.3, 56.9, 42.1], "The round fountain pool", "sparkle", "in the middle of the park", False),
("Fountain jet", [30.3, 28.5, 51.6, 34.0], "The fountain jet", "shoot", "high into the air", False),
("Boy in the green T-shirt", [45.7, 30.6, 53.0, 32.9], "The boy in the green T-shirt", "wade", "through the shallow water", False),
("Boy in the orange swimsuit", [43.4, 34.9, 51.1, 37.4], "The boy in the orange swimsuit", "splash", "his friend", False),
("Toy doll in the fountain", [47.4, 25.7, 49.2, 27.2], "The toy doll in the fountain", "float", "on the water", False),
("Pair of sandals", [54.8, 36.8, 56.0, 38.4], "The pair of sandals", "sit", "on the edge of the pool", True),
("Elderly man in the green waistcoat", [30.3, 41.9, 41.8, 45.0], "The elderly man in the green waistcoat", "stroll", "past the fountain", False),
("Boy on the red bicycle", [35.5, 38.8, 43.6, 41.8], "The boy on the red bicycle", "pedal", "towards the fountain", False),
("Red bicycle", [38.7, 38.0, 43.9, 42.1], "The red bicycle", "roll", "along the path", False),
("Duck by the fountain", [31.3, 24.3, 33.4, 26.3], "The duck by the fountain", "wander", "onto the path", False),
("Duckling near the fountain", [34.4, 22.9, 36.2, 24.5], "The duckling near the fountain", "hurry", "after the ducks", False),
("Boy on the scooter", [53.4, 26.5, 66.9, 29.7], "The boy on the scooter", "steer", "around the fountain", False),
("Silver scooter", [58.9, 26.0, 66.4, 30.2], "The silver scooter", "roll", "across the sand", False),
("Boy in the yellow T-shirt", [62.0, 22.6, 69.5, 25.2], "The boy in the yellow T-shirt", "push", "his scooter uphill", False),
("Girl in the purple top", [58.1, 35.6, 68.8, 39.3], "The girl in the purple top", "mend", "the bicycle chain", False),
("Green bicycle", [55.5, 34.0, 69.7, 43.0], "The green bicycle", "stand", "upside down on the path", False),
("Girl sitting on the bench", [62.7, 40.2, 69.7, 43.3], "The girl sitting on the bench", "watch", "the bicycle repair", False),
("Red park bench", [63.4, 43.3, 69.7, 47.6], "The red park bench", "stand", "beside the path", False),

# TILE r1c2
("Big oak tree", [31.0, 47.0, 66.9, 58.7], "The big oak tree", "tower", "over the middle of the park", False),
("Yellow bird", [35.2, 52.6, 37.3, 54.3], "The yellow bird", "fly", "out of the oak tree", False),
("Nesting box on the trunk", [38.3, 50.2, 40.2, 52.4], "The nesting box on the trunk", "hang", "high up in the tree", False),
("Jogger in the orange T-shirt", [34.3, 61.4, 47.4, 66.0], "The jogger in the orange T-shirt", "run", "across the meadow", False),
("Girl sitting on the grass", [30.3, 59.3, 33.6, 60.9], "The girl sitting on the grass", "wait", "for the puppet show", False),
("Man lying on the grass", [30.3, 62.4, 33.8, 64.7], "The man lying on the grass", "stretch", "out in the sunshine", False),
("Boy in the striped shirt", [30.3, 66.4, 35.5, 68.6], "The boy in the striped shirt", "sit", "cross-legged on the lawn", False),
("Red swing frame", [47.4, 60.7, 61.8, 73.5], "The red swing frame", "stand", "on the playground grass", False),
("Boy on the swing", [53.4, 62.9, 57.6, 64.9], "The boy on the swing", "swing", "higher and higher", False),
("Swing with the chains", [48.8, 61.8, 57.4, 64.9], "The swing with the chains", "hang", "from the red frame", False),
("Man in the striped shirt", [50.4, 57.5, 62.7, 61.3], "The man in the striped shirt", "push", "the swing", False),
("Woman in the white top", [51.3, 68.6, 62.3, 71.4], "The woman in the white top", "hold", "the baby swing steady", False),
("Toddler in the red top", [55.5, 67.7, 61.8, 69.7], "The toddler in the red top", "sit", "in the baby swing", False),
("Folded buggy", [62.7, 60.4, 69.7, 63.6], "The folded buggy", "wait", "near the sandpit", False),
("Woman by the sandpit", [64.2, 54.9, 69.7, 58.1], "The woman by the sandpit", "call", "to the children", False),
("Tree behind the swings", [36.2, 70.5, 51.1, 77.0], "The tree behind the swings", "shade", "the playground", False),

# TILE r1c3
("Red rubbish bin", [34.1, 84.5, 39.4, 86.8], "The red rubbish bin", "stand", "beside the ice cream kiosk", False),
("Piece of litter", [38.5, 83.6, 39.4, 84.3], "The piece of litter", "blow", "across the sand", False),
("Woman in the pink top", [39.7, 87.3, 51.1, 90.5], "The woman in the pink top", "walk", "towards the playground", False),
("Skateboarder in the red cap", [39.7, 91.9, 49.7, 97.6], "The skateboarder in the red cap", "ride", "down the slope", False),
("Skateboard", [48.1, 92.1, 49.7, 96.4], "The skateboard", "rattle", "over the path", False),
("Leafy tree by the playground", [34.5, 73.5, 48.3, 84.0], "The leafy tree by the playground", "grow", "behind the climbing tower", False),
("Playground tower", [45.7, 74.8, 69.7, 86.5], "The playground tower", "rise", "above the playground", False),
("Red roof of the tower", [45.7, 76.0, 55.3, 86.4], "The red roof of the tower", "keep", "the rain off the platform", False),
("Boy at the top of the slide", [57.6, 76.8, 63.7, 78.9], "The boy at the top of the slide", "hold", "on to the handrail", False),
("Grey slide", [60.0, 72.0, 69.7, 78.6], "The grey slide", "curve", "down to the ground", False),
("Boy in the tower window", [58.3, 82.2, 62.3, 84.2], "The boy in the tower window", "peep", "out of the tower", False),
("Girl on the rope bridge", [55.5, 90.2, 66.0, 93.0], "The girl on the rope bridge", "cross", "the swinging bridge", False),
("Wooden rope bridge", [60.7, 84.9, 66.9, 96.1], "The wooden rope bridge", "sway", "between the two towers", False),
("Red climbing house", [51.3, 93.3, 62.7, 100.0], "The red climbing house", "stand", "at the end of the bridge", False),
("Man in the sun hat", [50.8, 96.1, 55.0, 98.9], "The man in the sun hat", "lie", "on the wooden platform", False),
("Child at the little window", [55.9, 97.9, 58.7, 99.5], "The child at the little window", "wave", "from the climbing house", False),

]
