# Page 9 — Wimmeltown high street: shops, the school, the daycare and the traffic.
# Boxes read straight off the tiler grid labels, one block per tile.
P = [

# TILE r0c0
("Yellow tower crane", [0.6, 2.0, 12.0, 16.6], "The yellow tower crane", "swing", "over the building site", False),
("Builder in the orange vest", [6.4, 4.9, 11.3, 6.1], "The builder in the orange vest", "measure", "the new wall", False),
("Builder in the red helmet", [6.4, 6.3, 11.3, 7.7], "The builder in the red helmet", "work", "on the building site", False),
("White farmhouse", [4.7, 11.4, 7.5, 16.5], "The white farmhouse", "stand", "in the green fields", False),
("Yellow house behind the market", [4.3, 17.3, 10.6, 21.6], "The yellow house behind the market", "look", "down on the high street", False),
("Big green tree", [4.7, 6.0, 10.8, 10.2], "The big green tree", "grow", "beside the building site", False),
("Yellow digger", [11.0, 8.5, 19.9, 17.4], "The yellow digger", "dig", "a hole in the ground", False),
("Driver in the digger", [14.7, 15.2, 18.5, 16.8], "The driver in the digger", "pull", "the levers", False),
("Pile of sand", [16.4, 10.5, 19.4, 14.3], "The pile of sand", "wait", "beside the digger", False),
("Half-built brick wall", [12.7, 4.8, 18.5, 9.2], "The half-built brick wall", "rise", "behind the fence", False),
("Building site fence", [13.1, 0.0, 18.9, 4.8], "The building site fence", "keep", "the children out", False),
("Chimney above the shop", [2.9, 12.8, 5.2, 13.7], "The chimney above the shop", "poke", "through the roof", False),
("Pink house", [8.7, 18.2, 28.7, 27.9], "The pink house", "stand", "next to the supermarket", False),
("Oval window", [10.6, 21.6, 12.9, 23.1], "The oval window", "shine", "in the morning light", False),
("Tall arched window", [16.4, 19.1, 21.0, 21.0], "The tall arched window", "face", "the high street", False),
("Second arched window", [16.4, 23.0, 21.3, 24.8], "The second arched window", "let", "the sunshine in", False),
("Wimmelmarket sign", [22.2, 0.9, 25.9, 14.3], "The Wimmelmarket sign", "hang", "above the shop windows", False),
("Woman at the checkout", [28.7, 9.2, 36.0, 11.5], "The woman at the checkout", "pay", "for her shopping", False),
("Shop assistant in the red shirt", [28.5, 11.9, 36.0, 13.9], "The shop assistant in the red shirt", "pack", "the bags", False),
("Kids yoga sign", [28.0, 22.0, 31.0, 25.0], "The kids yoga sign", "advertise", "the class upstairs", False),
("Bush beside the shop", [30.6, 19.1, 33.3, 21.6], "The bush beside the shop", "grow", "against the wall", False),

# TILE r0c1
("Round window in the gable", [12.2, 32.4, 13.8, 34.1], "The round window in the gable", "look", "out over the street", False),
("Big arched studio window", [17.1, 30.1, 25.0, 35.5], "The big arched studio window", "show", "the yoga class inside", False),
("Children doing yoga", [17.8, 30.7, 24.7, 35.0], "The children doing yoga", "stretch", "on their mats", True),
("Tall brick chimney", [3.1, 36.7, 7.1, 37.9], "The tall brick chimney", "stand", "above the tiled roof", False),
("Solar panels", [6.4, 39.0, 9.9, 48.2], "The solar panels", "catch", "the morning sun", True),
("Trees behind the houses", [1.0, 30.1, 5.4, 35.8], "The trees behind the houses", "wave", "in the wind", True),
("Waiter on the balcony", [13.1, 44.2, 19.6, 46.8], "The waiter on the balcony", "carry", "a tray to the table", False),
("Tray of drinks", [17.5, 44.5, 18.9, 45.8], "The tray of drinks", "wobble", "in the waiter's hands", False),
("Red flowers on the balcony", [18.7, 41.6, 20.8, 44.1], "The red flowers on the balcony", "spill", "over the flower box", True),
("Balcony railing", [20.6, 39.0, 23.3, 49.8], "The balcony railing", "run", "along the front of the cafe", False),
("Yellow curtains", [25.7, 38.7, 30.6, 41.6], "The yellow curtains", "hang", "in the cafe window", True),
("Bucket of red flowers", [18.0, 48.4, 20.3, 50.9], "The bucket of red flowers", "stand", "outside the flower shop", False),
("Pot of purple flowers", [27.1, 48.8, 30.6, 51.0], "The pot of purple flowers", "brighten", "the pavement", False),
("Man pushing a wheelchair", [26.4, 47.2, 33.3, 49.0], "The man pushing a wheelchair", "help", "his friend along the path", False),
("Nurse in the white uniform", [27.3, 43.8, 33.3, 45.6], "The nurse in the white uniform", "walk", "beside the wheelchair", False),
("Girl in the purple top", [29.9, 41.3, 36.0, 43.2], "The girl in the purple top", "wait", "outside the cafe", False),
("Ladder on the fire engine", [29.6, 22.0, 36.0, 39.2], "The ladder on the fire engine", "stretch", "along the roof of the truck", False),

# TILE r0c2
("Flower shop sign", [15.2, 50.6, 17.8, 56.8], "The flower shop sign", "hang", "above the shop door", False),
("Woman carrying a plant", [18.7, 50.9, 25.9, 52.8], "The woman carrying a plant", "buy", "a pot of flowers", False),
("Florist in the red apron", [18.2, 53.4, 26.8, 55.1], "The florist in the red apron", "serve", "her customers", False),
("Window boxes of pink flowers", [13.1, 49.2, 15.2, 57.8], "The window boxes of pink flowers", "hang", "under the windows", True),
("Potted palm outside the shop", [21.3, 56.8, 27.8, 58.5], "The potted palm outside the shop", "stand", "on the pavement", False),
("Row of plant pots", [25.4, 54.8, 28.2, 58.3], "The row of plant pots", "line", "the shop front", True),
("Girl on crutches", [20.1, 60.0, 29.6, 62.0], "The girl on crutches", "walk", "to the doctor's door", False),
("Doctor's nameplate", [21.5, 61.7, 24.5, 63.4], "The doctor's nameplate", "hang", "beside the surgery door", False),
("Smiling kite in the window", [21.5, 64.5, 25.2, 66.6], "The smiling kite in the window", "hang", "in the toy shop window", False),
("Red tricycle", [25.2, 64.0, 29.2, 66.9], "The red tricycle", "wait", "for a new owner", False),
("Yellow toy aeroplane", [22.2, 70.6, 24.0, 72.8], "The yellow toy aeroplane", "hang", "above the toys", False),
("Big pink panda", [23.6, 71.5, 28.7, 74.6], "The big pink panda", "sit", "in the shop window", False),
("Blue toy car", [27.1, 70.9, 29.4, 73.2], "The blue toy car", "shine", "under the window light", False),
("Toystore sign", [17.3, 68.5, 19.4, 77.8], "The toystore sign", "spell", "the name in big letters", False),
("Children at the upstairs window", [12.2, 62.2, 16.4, 66.2], "The children at the upstairs window", "watch", "the street below", True),
("Dog at the window", [14.3, 63.2, 16.1, 64.8], "The dog at the window", "bark", "at the passers-by", False),
("Dormer window", [6.6, 66.0, 8.9, 68.5], "The dormer window", "sit", "in the tiled roof", False),
("Chimney pot", [2.7, 66.3, 5.2, 67.5], "The chimney pot", "stand", "on the ridge of the roof", False),
("Green hill in the distance", [2.7, 58.6, 4.7, 62.9], "The green hill in the distance", "rise", "behind the town", False),
("Man in the wheelchair", [28.2, 54.0, 34.7, 56.8], "The man in the wheelchair", "roll", "along the pavement", False),
("Skylight in the red roof", [6.6, 52.3, 8.5, 53.5], "The skylight in the red roof", "let", "light into the attic", False),
("Window with the blue curtains", [5.9, 74.6, 9.9, 76.5], "The window with the blue curtains", "stand", "open at the top", False),

# TILE r0c3
("Kim's Bakery sign", [16.4, 82.7, 18.7, 90.9], "The Kim's Bakery sign", "invite", "the shoppers inside", False),
("Baker behind the counter", [19.6, 82.9, 25.0, 85.0], "The baker behind the counter", "sell", "the fresh bread", False),
("Old man buying bread", [20.1, 86.4, 28.7, 88.0], "The old man buying bread", "point", "at the loaves", False),
("Woman in the green top", [20.1, 88.0, 28.7, 89.4], "The woman in the green top", "queue", "behind the old man", False),
("Boy in the striped jumper", [22.2, 85.2, 30.6, 86.6], "The boy in the striped jumper", "choose", "a cake", False),
("Basket of bread rolls", [25.9, 82.4, 27.8, 85.2], "The basket of bread rolls", "sit", "on the counter", False),
("Striped market awning", [22.2, 89.2, 27.8, 97.5], "The striped market awning", "shade", "the market stall", False),
("Bunch of balloons", [14.5, 80.4, 17.1, 82.1], "The bunch of balloons", "bob", "outside the toy shop", False),
("Red balloon floating away", [1.3, 96.1, 3.3, 97.2], "The red balloon floating away", "escape", "into the blue sky", False),
("Man leaving the toy shop", [20.1, 77.3, 30.6, 79.6], "The man leaving the toy shop", "step", "out onto the pavement", False),
("Chimney with the metal cap", [2.0, 79.8, 4.7, 81.2], "The chimney with the metal cap", "stand", "above the bakery", False),
("Girl at the attic window", [5.9, 94.5, 8.5, 96.3], "The girl at the attic window", "wave", "from the top floor", False),
("Window box of red flowers", [13.8, 88.3, 15.7, 90.4], "The window box of red flowers", "hang", "above the bakery", False),
("Girl in the flat window", [12.0, 83.5, 15.9, 85.5], "The girl in the flat window", "lean", "on the windowsill", False),
("Round bakery sign", [15.9, 91.8, 18.9, 94.1], "The round bakery sign", "swing", "beside the door", False),
("Yellow curtains upstairs", [5.9, 74.7, 8.7, 76.1], "The yellow curtains upstairs", "hang", "in the attic window", True),
("Children at the flat window", [12.2, 76.7, 15.2, 78.6], "The children at the flat window", "look", "down at the shoppers", True),
("Trees behind the bakery", [1.0, 88.3, 4.7, 96.0], "The trees behind the bakery", "grow", "behind the rooftops", True),
("Woman in the pink top", [28.0, 85.3, 36.0, 87.3], "The woman in the pink top", "browse", "at the market stall", False),
("Girl in the rainbow jumper", [31.5, 79.8, 36.0, 81.8], "The girl in the rainbow jumper", "walk", "past the bakery", False),
("Market stall of toys", [28.7, 90.4, 36.0, 97.5], "The market stall of toys", "sell", "hats and dolls", False),

# TILE r1c0
("Girl pushing a trolley", [34.8, 2.0, 44.8, 4.1], "The girl pushing a trolley", "push", "the trolley to the car", False),
("Shopping trolley", [39.0, 0.6, 45.2, 3.1], "The shopping trolley", "rattle", "across the car park", False),
("Shopper in the pink top", [34.1, 4.3, 44.8, 6.6], "The shopper in the pink top", "leave", "the supermarket", False),
("Girl walking the dogs", [35.7, 8.9, 45.9, 12.0], "The girl walking the dogs", "hold", "four leads at once", False),
("Golden retriever", [40.6, 12.2, 46.6, 14.3], "The golden retriever", "sit", "on the pavement", False),
("Small white dog", [44.1, 7.7, 46.6, 9.8], "The small white dog", "trot", "beside the others", False),
("Black dog", [39.9, 14.5, 44.8, 17.1], "The black dog", "wait", "for a walk", False),
("White spotted dog", [38.7, 13.1, 41.3, 15.1], "The white spotted dog", "sniff", "the shopping bags", False),
("Customer at the till", [30.3, 12.3, 34.1, 14.6], "The customer at the till", "unload", "the shopping basket", False),
("Row of stacked trolleys", [34.6, 16.3, 39.9, 19.1], "The row of stacked trolleys", "stand", "outside the doors", True),
("Red fire engine", [31.2, 18.6, 48.9, 38.5], "The red fire engine", "drive", "along the high street", False),
("Firefighter in the cab", [35.5, 21.6, 39.9, 23.4], "The firefighter in the cab", "steer", "the fire engine", False),
("Second firefighter", [35.2, 25.1, 39.2, 26.5], "The second firefighter", "sit", "next to the driver", False),
("Ginger cat on the roof", [53.1, 5.1, 55.7, 8.0], "The ginger cat on the roof", "walk", "along the ridge", False),
("Green pick-up truck", [49.7, 12.0, 59.7, 27.9], "The green pick-up truck", "wait", "at the corner", False),
("Driver of the green truck", [50.6, 18.2, 56.2, 20.3], "The driver of the green truck", "look", "over his shoulder", False),
("Passenger in the truck", [52.7, 19.9, 56.4, 21.6], "The passenger in the truck", "point", "down the road", False),
("Red roof of the daycare", [55.2, 0.0, 69.5, 21.6], "The red roof of the daycare", "cover", "the whole building", False),
("Yellow chimney", [55.7, 0.4, 65.6, 3.1], "The yellow chimney", "stand", "at the end of the roof", False),
("Skylight window in the roof", [59.4, 5.7, 65.1, 11.1], "The skylight window in the roof", "open", "onto the playroom", False),
("Girl looking out of the skylight", [60.1, 7.5, 64.5, 9.8], "The girl looking out of the skylight", "watch", "the traffic go past", False),

# TILE r1c1
("Big wheel of the fire engine", [46.2, 26.1, 49.7, 29.2], "The big wheel of the fire engine", "turn", "on the wet road", False),
("Old people on the bench", [30.3, 41.0, 35.9, 44.1], "The old people on the bench", "rest", "in the sunshine", True),
("Man in the brown jacket", [30.3, 47.2, 36.4, 48.7], "The man in the brown jacket", "wait", "beside the bench", False),
("Hedge behind the school fence", [46.4, 37.8, 53.1, 52.8], "The hedge behind the school fence", "hide", "the playground", False),
("Boy by the school fence", [50.6, 47.9, 54.5, 49.6], "The boy by the school fence", "throw", "a ball over the wall", False),
("Blue and yellow bus", [51.5, 32.8, 69.5, 52.8], "The blue and yellow bus", "stop", "outside the school", False),
("Bus driver", [56.4, 35.5, 59.6, 37.0], "The bus driver", "open", "the doors", False),
("Passenger on the bus", [60.6, 40.4, 63.4, 41.9], "The passenger on the bus", "look", "out of the window", False),
("Children on the bus", [63.4, 45.3, 66.6, 46.5], "The children on the bus", "wave", "at their friends", True),
]
