# Page 9 — Wimmeltown high street: shops, the school, the daycare and the traffic.
# Boxes read straight off the tiler grid labels, one block per tile.
P = [

# TILE r0c0
("Yellow tower crane", [0.6, 2.0, 12.0, 16.6], "The yellow tower crane", "swing", "over the building site", False),
("Builder in the orange vest", [6.4, 4.9, 11.3, 6.1], "The builder in the orange vest", "measure", "the new wall", False),
("Builder in the red helmet", [6.4, 6.3, 11.3, 7.7], "The builder in the red helmet", "work", "on the building site", False),
("White farmhouse", [4.7, 11.4, 7.5, 16.5], "The white farmhouse", "stand", "in the green fields", False),
("Yellow house behind the market", [4.3, 17.3, 10.6, 21.6], "The yellow house behind the market", "look", "down on the high street", False),
("Big green tree", [4.7, 6.0, 10.8, 10.2], "The big green tree", "grow", "beside the building site", False),
("Yellow digger", [11.0, 8.5, 19.9, 17.4], "The yellow digger", "dig", "a hole in the ground", False),
("Driver in the digger", [14.7, 15.2, 18.5, 16.8], "The driver in the digger", "pull", "the levers", False),
("Pile of sand", [16.4, 10.5, 19.4, 14.3], "The pile of sand", "wait", "beside the digger", False),
("Half-built brick wall", [12.7, 4.8, 18.5, 9.2], "The half-built brick wall", "rise", "behind the fence", False),
("Building site fence", [13.1, 0.0, 18.9, 4.8], "The building site fence", "keep", "the children out", False),
("Chimney above the shop", [2.9, 12.8, 5.2, 13.7], "The chimney above the shop", "poke", "through the roof", False),
("Pink house", [8.7, 18.2, 28.7, 27.9], "The pink house", "stand", "next to the supermarket", False),
("Oval window", [10.6, 21.6, 12.9, 23.1], "The oval window", "shine", "in the morning light", False),
("Tall arched window", [16.4, 19.1, 21.0, 21.0], "The tall arched window", "face", "the high street", False),
("Second arched window", [16.4, 23.0, 21.3, 24.8], "The second arched window", "let", "the sunshine in", False),
("Wimmelmarket sign", [22.2, 0.9, 25.9, 14.3], "The Wimmelmarket sign", "hang", "above the shop windows", False),
("Woman at the checkout", [28.7, 9.2, 36.0, 11.5], "The woman at the checkout", "pay", "for her shopping", False),
("Shop assistant in the red shirt", [28.5, 11.9, 36.0, 13.9], "The shop assistant in the red shirt", "pack", "the bags", False),
("Kids yoga sign", [28.0, 22.0, 31.0, 25.0], "The kids yoga sign", "advertise", "the class upstairs", False),
("Bush beside the shop", [30.6, 19.1, 33.3, 21.6], "The bush beside the shop", "grow", "against the wall", False),

# TILE r0c1
("Round window in the gable", [12.2, 32.4, 13.8, 34.1], "The round window in the gable", "look", "out over the street", False),
("Big arched studio window", [17.1, 30.1, 25.0, 35.5], "The big arched studio window", "show", "the yoga class inside", False),
("Children doing yoga", [17.8, 30.7, 24.7, 35.0], "The children doing yoga", "stretch", "on their mats", True),
("Tall brick chimney", [3.1, 36.7, 7.1, 37.9], "The tall brick chimney", "stand", "above the tiled roof", False),
("Solar panels", [6.4, 39.0, 9.9, 48.2], "The solar panels", "catch", "the morning sun", True),
("Trees behind the houses", [1.0, 30.1, 5.4, 35.8], "The trees behind the houses", "wave", "in the wind", True),
("Waiter on the balcony", [13.1, 44.2, 19.6, 46.8], "The waiter on the balcony", "carry", "a tray to the table", False),
("Tray of drinks", [17.5, 44.5, 18.9, 45.8], "The tray of drinks", "wobble", "in the waiter's hands", False),
("Red flowers on the balcony", [18.7, 41.6, 20.8, 44.1], "The red flowers on the balcony", "spill", "over the flower box", True),
("Balcony railing", [20.6, 39.0, 23.3, 49.8], "The balcony railing", "run", "along the front of the cafe", False),
("Yellow curtains", [25.7, 38.7, 30.6, 41.6], "The yellow curtains", "hang", "in the cafe window", True),
("Bucket of red flowers", [18.0, 48.4, 20.3, 50.9], "The bucket of red flowers", "stand", "outside the flower shop", False),
("Pot of purple flowers", [27.1, 48.8, 30.6, 51.0], "The pot of purple flowers", "brighten", "the pavement", False),
("Man pushing a wheelchair", [26.4, 47.2, 33.3, 49.0], "The man pushing a wheelchair", "help", "his friend along the path", False),
("Nurse in the white uniform", [27.3, 43.8, 33.3, 45.6], "The nurse in the white uniform", "walk", "beside the wheelchair", False),
("Girl in the purple top", [29.9, 41.3, 36.0, 43.2], "The girl in the purple top", "wait", "outside the cafe", False),
("Ladder on the fire engine", [29.6, 22.0, 36.0, 39.2], "The ladder on the fire engine", "stretch", "along the roof of the truck", False),

# TILE r0c2
("Flower shop sign", [15.2, 50.6, 17.8, 56.8], "The flower shop sign", "hang", "above the shop door", False),
("Woman carrying a plant", [18.7, 50.9, 25.9, 52.8], "The woman carrying a plant", "buy", "a pot of flowers", False),
("Florist in the red apron", [18.2, 53.4, 26.8, 55.1], "The florist in the red apron", "serve", "her customers", False),
("Window boxes of pink flowers", [13.1, 49.2, 15.2, 57.8], "The window boxes of pink flowers", "hang", "under the windows", True),
("Potted palm outside the shop", [21.3, 56.8, 27.8, 58.5], "The potted palm outside the shop", "stand", "on the pavement", False),
("Row of plant pots", [25.4, 54.8, 28.2, 58.3], "The row of plant pots", "line", "the shop front", True),
("Girl on crutches", [20.1, 60.0, 29.6, 62.0], "The girl on crutches", "walk", "to the doctor's door", False),
("Doctor's nameplate", [21.5, 61.7, 24.5, 63.4], "The doctor's nameplate", "hang", "beside the surgery door", False),
("Smiling kite in the window", [21.5, 64.5, 25.2, 66.6], "The smiling kite in the window", "hang", "in the toy shop window", False),
("Red tricycle", [25.2, 64.0, 29.2, 66.9], "The red tricycle", "wait", "for a new owner", False),
("Yellow toy aeroplane", [22.2, 70.6, 24.0, 72.8], "The yellow toy aeroplane", "hang", "above the toys", False),
("Big pink panda", [23.6, 71.5, 28.7, 74.6], "The big pink panda", "sit", "in the shop window", False),
("Blue toy car", [27.1, 70.9, 29.4, 73.2], "The blue toy car", "shine", "under the window light", False),
("Toystore sign", [17.3, 68.5, 19.4, 77.8], "The toystore sign", "spell", "the name in big letters", False),
("Children at the upstairs window", [12.2, 62.2, 16.4, 66.2], "The children at the upstairs window", "watch", "the street below", True),
("Dog at the window", [14.3, 63.2, 16.1, 64.8], "The dog at the window", "bark", "at the passers-by", False),
("Dormer window", [6.6, 66.0, 8.9, 68.5], "The dormer window", "sit", "in the tiled roof", False),
("Chimney pot", [2.7, 66.3, 5.2, 67.5], "The chimney pot", "stand", "on the ridge of the roof", False),
("Green hill in the distance", [2.7, 58.6, 4.7, 62.9], "The green hill in the distance", "rise", "behind the town", False),
("Man in the wheelchair", [28.2, 54.0, 34.7, 56.8], "The man in the wheelchair", "roll", "along the pavement", False),
("Skylight in the red roof", [6.6, 52.3, 8.5, 53.5], "The skylight in the red roof", "let", "light into the attic", False),
("Window with the blue curtains", [5.9, 74.6, 9.9, 76.5], "The window with the blue curtains", "stand", "open at the top", False),

# TILE r0c3
("Kim's Bakery sign", [16.4, 82.7, 18.7, 90.9], "The Kim's Bakery sign", "invite", "the shoppers inside", False),
("Baker behind the counter", [19.6, 82.9, 25.0, 85.0], "The baker behind the counter", "sell", "the fresh bread", False),
("Old man buying bread", [20.1, 86.4, 28.7, 88.0], "The old man buying bread", "point", "at the loaves", False),
("Woman in the green top", [20.1, 88.0, 28.7, 89.4], "The woman in the green top", "queue", "behind the old man", False),
("Boy in the striped jumper", [22.2, 85.2, 30.6, 86.6], "The boy in the striped jumper", "choose", "a cake", False),
("Basket of bread rolls", [25.9, 82.4, 27.8, 85.2], "The basket of bread rolls", "sit", "on the counter", False),
("Striped market awning", [22.2, 89.2, 27.8, 97.5], "The striped market awning", "shade", "the market stall", False),
("Bunch of balloons", [14.5, 80.4, 17.1, 82.1], "The bunch of balloons", "bob", "outside the toy shop", False),
("Red balloon floating away", [1.3, 96.1, 3.3, 97.2], "The red balloon floating away", "escape", "into the blue sky", False),
("Man leaving the toy shop", [20.1, 77.3, 30.6, 79.6], "The man leaving the toy shop", "step", "out onto the pavement", False),
("Chimney with the metal cap", [2.0, 79.8, 4.7, 81.2], "The chimney with the metal cap", "stand", "above the bakery", False),
("Girl at the attic window", [5.9, 94.5, 8.5, 96.3], "The girl at the attic window", "wave", "from the top floor", False),
("Window box of red flowers", [13.8, 88.3, 15.7, 90.4], "The window box of red flowers", "hang", "above the bakery", False),
("Girl in the flat window", [12.0, 83.5, 15.9, 85.5], "The girl in the flat window", "lean", "on the windowsill", False),
("Round bakery sign", [15.9, 91.8, 18.9, 94.1], "The round bakery sign", "swing", "beside the door", False),
("Yellow curtains upstairs", [5.9, 74.7, 8.7, 76.1], "The yellow curtains upstairs", "hang", "in the attic window", True),
("Children at the flat window", [12.2, 76.7, 15.2, 78.6], "The children at the flat window", "look", "down at the shoppers", True),
("Trees behind the bakery", [1.0, 88.3, 4.7, 96.0], "The trees behind the bakery", "grow", "behind the rooftops", True),
("Woman in the pink top", [28.0, 85.3, 36.0, 87.3], "The woman in the pink top", "browse", "at the market stall", False),
("Girl in the rainbow jumper", [31.5, 79.8, 36.0, 81.8], "The girl in the rainbow jumper", "walk", "past the bakery", False),
("Market stall of toys", [28.7, 90.4, 36.0, 97.5], "The market stall of toys", "sell", "hats and dolls", False),

# TILE r1c0
("Girl pushing a trolley", [34.8, 2.0, 44.8, 4.1], "The girl pushing a trolley", "push", "the trolley to the car", False),
("Shopping trolley", [39.0, 0.6, 45.2, 3.1], "The shopping trolley", "rattle", "across the car park", False),
("Shopper in the pink top", [34.1, 4.3, 44.8, 6.6], "The shopper in the pink top", "leave", "the supermarket", False),
("Girl walking the dogs", [35.7, 8.9, 45.9, 12.0], "The girl walking the dogs", "hold", "four leads at once", False),
("Golden retriever", [40.6, 12.2, 46.6, 14.3], "The golden retriever", "sit", "on the pavement", False),
("Small white dog", [44.1, 7.7, 46.6, 9.8], "The small white dog", "trot", "beside the others", False),
("Black dog", [39.9, 14.5, 44.8, 17.1], "The black dog", "wait", "for a walk", False),
("White spotted dog", [38.7, 13.1, 41.3, 15.1], "The white spotted dog", "sniff", "the shopping bags", False),
("Customer at the till", [30.3, 12.3, 34.1, 14.6], "The customer at the till", "unload", "the shopping basket", False),
("Row of stacked trolleys", [34.6, 16.3, 39.9, 19.1], "The row of stacked trolleys", "stand", "outside the doors", True),
("Red fire engine", [31.2, 18.6, 48.9, 38.5], "The red fire engine", "drive", "along the high street", False),
("Firefighter in the cab", [35.5, 21.6, 39.9, 23.4], "The firefighter in the cab", "steer", "the fire engine", False),
("Second firefighter", [35.2, 25.1, 39.2, 26.5], "The second firefighter", "sit", "next to the driver", False),
("Ginger cat on the roof", [53.1, 5.1, 55.7, 8.0], "The ginger cat on the roof", "walk", "along the ridge", False),
("Green pick-up truck", [49.7, 12.0, 59.7, 27.9], "The green pick-up truck", "wait", "at the corner", False),
("Driver of the green truck", [50.6, 18.2, 56.2, 20.3], "The driver of the green truck", "look", "over his shoulder", False),
("Passenger in the truck", [52.7, 19.9, 56.4, 21.6], "The passenger in the truck", "point", "down the road", False),
("Red roof of the daycare", [55.2, 0.0, 69.5, 21.6], "The red roof of the daycare", "cover", "the whole building", False),
("Yellow chimney", [55.7, 0.4, 65.6, 3.1], "The yellow chimney", "stand", "at the end of the roof", False),
("Skylight window in the roof", [59.4, 5.7, 65.1, 11.1], "The skylight window in the roof", "open", "onto the playroom", False),
("Girl looking out of the skylight", [60.1, 7.5, 64.5, 9.8], "The girl looking out of the skylight", "watch", "the traffic go past", False),

# TILE r1c1
("Big wheel of the fire engine", [46.2, 26.1, 49.7, 29.2], "The big wheel of the fire engine", "turn", "on the wet road", False),
("Old people on the bench", [30.3, 41.0, 35.9, 44.1], "The old people on the bench", "rest", "in the sunshine", True),
("Man in the brown jacket", [30.3, 47.2, 36.4, 48.7], "The man in the brown jacket", "wait", "beside the bench", False),
("Hedge behind the school fence", [46.4, 37.8, 53.1, 52.8], "The hedge behind the school fence", "hide", "the playground", False),
("Boy by the school fence", [50.6, 47.9, 54.5, 49.6], "The boy by the school fence", "throw", "a ball over the wall", False),
("Blue and yellow bus", [51.5, 32.8, 69.5, 52.8], "The blue and yellow bus", "stop", "outside the school", False),
("Bus driver", [56.4, 35.5, 59.6, 37.0], "The bus driver", "open", "the doors", False),
("Passenger on the bus", [60.6, 40.4, 63.4, 41.9], "The passenger on the bus", "look", "out of the window", False),
("Children on the bus", [63.4, 45.3, 66.6, 46.5], "The children on the bus", "wave", "at their friends", True),

# TILE r1c2
("Red roof of the school", [31.2, 55.1, 46.2, 77.8], "The red roof of the school", "shine", "in the sunshine", False),
("School name sign", [52.7, 58.6, 59.2, 66.9], "The school name sign", "spell", "out the name of the school", False),
("Arched school doorway", [58.7, 60.0, 69.5, 64.8], "The arched school doorway", "welcome", "the children inside", False),
("Boy at the classroom window", [48.0, 63.2, 53.1, 64.9], "The boy at the classroom window", "look", "down at the bus", False),
("Teacher at the window", [50.1, 71.4, 55.2, 73.4], "The teacher at the window", "write", "on the whiteboard", False),
("Arched classroom window", [45.9, 60.8, 53.1, 63.5], "The arched classroom window", "face", "the playground", False),
("Big tree in the playground", [35.9, 48.8, 48.0, 55.1], "The big tree in the playground", "shade", "the school wall", False),
("Football on the wall", [48.5, 50.9, 50.3, 52.3], "The football on the wall", "balance", "on top of the wall", False),
("Child climbing the tree", [43.1, 52.0, 45.2, 53.5], "The child climbing the tree", "climb", "up to the branches", False),
("Boy in the red shirt", [49.2, 53.4, 54.5, 55.1], "The boy in the red shirt", "throw", "the ball back", False),
("White wall by the playground", [52.7, 50.0, 55.9, 55.1], "The white wall by the playground", "edge", "the school garden", False),
("School chimney", [30.3, 72.0, 32.9, 73.7], "The school chimney", "rise", "above the red tiles", False),
("Two pigeons on the roof", [39.2, 73.2, 40.4, 75.8], "The two pigeons on the roof", "rest", "on the warm tiles", True),
("Traffic light pole", [55.2, 54.3, 65.6, 55.1], "The traffic light pole", "stand", "at the crossing", False),
("Little white car", [60.6, 55.4, 63.2, 56.6], "The little white car", "park", "outside the school", False),
("Bush by the school steps", [64.5, 56.2, 67.5, 58.6], "The bush by the school steps", "grow", "next to the door", False),
("Downstairs classroom window", [61.7, 70.9, 69.5, 73.7], "The downstairs classroom window", "look", "out on the street", False),

# TILE r1c3
("Police station sign", [59.2, 95.1, 62.4, 99.9], "The police station sign", "stand", "above the front door", False),
("Policeman at his desk", [53.6, 96.0, 57.3, 97.8], "The policeman at his desk", "answer", "the telephone", False),
("Officer in the office window", [64.5, 92.3, 69.5, 94.8], "The officer in the office window", "read", "a report", False),
("Boy at the police station window", [63.9, 89.5, 67.5, 91.0], "The boy at the police station window", "wait", "inside the station", False),
("Skateboard on the ledge", [43.1, 93.5, 45.7, 96.0], "The skateboard on the ledge", "lie", "on the flat roof", False),
("Air vent on the wall", [41.5, 96.9, 45.2, 99.1], "The air vent on the wall", "hum", "beside the window", False),
("Man with the shopping basket", [30.3, 84.9, 38.2, 87.3], "The man with the shopping basket", "carry", "his shopping home", False),
("Little girl in the red dress", [34.8, 87.3, 39.2, 88.7], "The little girl in the red dress", "hold", "her father's hand", False),
("Stall with the pink cloth", [32.9, 89.5, 40.4, 94.8], "The stall with the pink cloth", "display", "the toys for sale", False),
("Doll on the market stall", [30.3, 88.1, 33.6, 89.5], "The doll on the market stall", "sit", "on the top shelf", False),
("Wooden crate at the stall", [34.8, 96.0, 38.2, 97.5], "The wooden crate at the stall", "hold", "the spare stock", False),
("Plant on the windowsill", [48.0, 82.9, 50.8, 84.3], "The plant on the windowsill", "grow", "in a red pot", False),
("Girl in the classroom window", [50.3, 77.3, 55.0, 80.0], "The girl in the classroom window", "sit", "at her desk", False),
("Man cleaning the window", [60.6, 82.9, 63.9, 84.3], "The man cleaning the window", "wipe", "the glass clean", False),
("Children in the downstairs classroom", [64.8, 77.3, 69.5, 80.1], "The children in the downstairs classroom", "work", "at their tables", True),
("Yellow window blind", [49.7, 88.3, 52.7, 92.0], "The yellow window blind", "shade", "the police office", False),
("Plant in the police window", [52.7, 88.7, 54.8, 89.8], "The plant in the police window", "sit", "behind the glass", False),

# TILE r2c0
("Dot's Daycare sign", [67.8, 23.6, 70.6, 27.6], "The Dot's Daycare sign", "hang", "above the glass door", False),
("Man in the yellow shirt", [73.4, 5.1, 82.9, 7.1], "The man in the yellow shirt", "fill", "a water bottle", False),
("Toddler in the red dress", [80.6, 6.3, 86.2, 8.0], "The toddler in the red dress", "hold", "on to the window ledge", False),
("Woman carrying a flower pot", [77.3, 10.5, 89.7, 14.3], "The woman carrying a flower pot", "carry", "the flowers to the door", False),
("Pot of pink flowers", [76.6, 13.1, 81.7, 16.5], "The pot of pink flowers", "spill", "over the sides of the pot", False),
("Hanging plant by the door", [71.5, 0.9, 77.3, 3.4], "The hanging plant by the door", "hang", "beside the window", False),
("Little girl in the pink top", [84.1, 10.0, 89.9, 12.0], "The little girl in the pink top", "hold", "a small doll", False),
("Yellow ball on the grass", [85.7, 5.4, 87.3, 6.6], "The yellow ball on the grass", "lie", "in the daycare garden", False),
("Woman in the purple coat", [82.7, 16.2, 95.0, 18.6], "The woman in the purple coat", "collect", "her daughter", False),
("Man in the striped shirt", [80.6, 19.1, 93.5, 21.9], "The man in the striped shirt", "carry", "his son on his shoulders", False),
("Baby on his shoulders", [80.8, 20.5, 83.1, 21.9], "The baby on his shoulders", "grab", "his father's hair", False),
("Woman with the long fair hair", [84.3, 23.0, 95.9, 25.3], "The woman with the long fair hair", "push", "the wheelchair up the path", False),
("Boy in the wheelchair", [89.2, 25.1, 96.9, 28.0], "The boy in the wheelchair", "smile", "at the other children", False),
("Girl with the ponytail", [85.7, 1.7, 96.9, 4.1], "The girl with the ponytail", "lean", "over the sandpit fence", False),
("Small boy at the fence", [90.8, 4.3, 96.9, 6.4], "The small boy at the fence", "climb", "over the low fence", False),
("Child in the sandpit", [93.1, 7.5, 98.7, 9.7], "The child in the sandpit", "dig", "in the soft sand", False),
("Red bucket in the sand", [95.9, 9.2, 98.0, 10.6], "The red bucket in the sand", "fill", "up with sand", False),
("Wooden fence round the sandpit", [92.2, 2.3, 99.6, 16.3], "The wooden fence round the sandpit", "keep", "the sand off the grass", False),
("Beach ball on the grass", [96.6, 19.3, 98.7, 21.3], "The beach ball on the grass", "roll", "towards the hedge", False),
("Children behind the window", [77.3, 20.5, 83.4, 22.3], "The children behind the window", "play", "inside the daycare", True),
("Tray of cakes in the window", [75.0, 16.3, 76.9, 19.1], "The tray of cakes in the window", "cool", "on the windowsill", False),

# TILE r2c1
("Girl in the daycare doorway", [71.5, 24.8, 78.7, 26.5], "The girl in the daycare doorway", "hold", "the door open", False),
("Toddler at the daycare door", [77.1, 25.3, 83.6, 26.5], "The toddler at the daycare door", "toddle", "out into the garden", False),
("Boy running to the swings", [81.0, 29.2, 87.8, 31.5], "The boy running to the swings", "run", "across the playground", False),
("Boy on the climbing frame", [76.2, 35.3, 82.4, 37.6], "The boy on the climbing frame", "hang", "from the metal bar", False),
("Boy in the red shorts", [76.9, 38.2, 83.4, 39.8], "The boy in the red shorts", "wait", "for his turn", False),
("Father in the blue striped shirt", [70.3, 37.9, 82.0, 40.4], "The father in the blue striped shirt", "watch", "the children play", False),
("Metal climbing frame", [75.7, 31.5, 83.4, 37.3], "The metal climbing frame", "stand", "in the middle of the grass", False),
("Wooden swing frame", [83.1, 30.4, 96.9, 41.0], "The wooden swing frame", "creak", "in the wind", False),
("Girl on the swing", [87.1, 36.1, 95.5, 38.4], "The girl on the swing", "swing", "higher and higher", False),
("Blue seesaw", [87.6, 40.1, 91.3, 48.2], "The blue seesaw", "tip", "up and down", False),
("Big green hedge in the playground", [70.1, 29.6, 96.9, 52.8], "The big green hedge in the playground", "surround", "the play area", False),
("Bus wheel", [64.3, 36.7, 68.5, 39.2], "The bus wheel", "roll", "along the road", False),
("Zebra crossing stripes", [74.5, 46.5, 88.0, 66.0], "The zebra crossing stripes", "cross", "the wide road", True),
("Flower sticker on the window", [71.5, 26.7, 74.3, 28.8], "The flower sticker on the window", "decorate", "the daycare glass", False),

# TILE r2c2
("Woman crossing the road", [71.5, 56.3, 82.9, 59.1], "The woman crossing the road", "hold", "her daughter's hand", False),
("Little girl on the crossing", [76.6, 53.7, 82.9, 56.2], "The little girl on the crossing", "step", "onto the white stripes", False),
("Boy with the school bag", [66.4, 58.8, 74.1, 60.8], "The boy with the school bag", "hurry", "into school", False),
("Girl in the tartan skirt", [65.9, 62.0, 73.4, 64.0], "The girl in the tartan skirt", "climb", "the school steps", False),
("Child in the pink jumper", [66.4, 64.0, 70.8, 65.1], "The child in the pink jumper", "follow", "her friends", False),
("Boy on the bicycle", [72.2, 65.4, 79.9, 69.8], "The boy on the bicycle", "cycle", "past the school gate", False),
("Bushes by the school wall", [71.0, 68.5, 78.0, 74.8], "The bushes by the school wall", "grow", "along the brick wall", True),
("Cyclist in the green helmet", [78.0, 74.4, 89.7, 77.8], "The cyclist in the green helmet", "wheel", "his bike to the kerb", False),
("Bicycle by the kerb", [82.7, 72.4, 89.4, 79.6], "The bicycle by the kerb", "lean", "against the pavement", False),
("Yellow car", [86.2, 59.2, 99.5, 74.8], "The yellow car", "wait", "with its door open", False),
("Man loading the car", [86.9, 59.2, 99.5, 62.5], "The man loading the car", "lift", "a bag into the car", False),
("Open car door", [89.9, 61.7, 98.7, 63.5], "The open car door", "stand", "wide open", False),
("Girl in the yellow dress", [89.2, 56.3, 96.9, 58.9], "The girl in the yellow dress", "wait", "beside the car", False),
("Hedge beside the road", [83.1, 47.0, 99.5, 55.8], "The hedge beside the road", "grow", "along the pavement", False),
("Children at the school window", [65.9, 71.5, 68.7, 73.2], "The children at the school window", "watch", "the street below", True),

# TILE r2c3
("White police car", [71.0, 75.9, 83.8, 87.3], "The white police car", "park", "outside the station", False),
("Blue light on the police car", [71.0, 78.7, 73.1, 83.0], "The blue light on the police car", "sit", "on the roof", False),
("Officer on the quad bike", [72.9, 87.0, 81.7, 89.5], "The officer on the quad bike", "check", "his radio", False),
("Police quad bike", [75.5, 83.5, 86.6, 92.0], "The police quad bike", "stand", "next to the car", False),
("Policeman on the pavement", [76.9, 94.1, 89.2, 96.6], "The policeman on the pavement", "talk", "to a young boy", False),
("Boy in the orange shirt", [82.7, 92.1, 89.4, 93.9], "The boy in the orange shirt", "ask", "the policeman a question", False),
("Steps up to the police station", [75.7, 93.2, 82.9, 99.9], "The steps up to the police station", "lead", "to the front door", True),
("Policewoman at the window", [64.3, 89.5, 69.9, 91.4], "The policewoman at the window", "look", "out at the street", False),
("Officer in the front office", [64.7, 92.4, 69.9, 94.5], "The officer in the front office", "sit", "at his computer", False),
("Man on the telephone", [65.9, 96.1, 73.4, 97.5], "The man on the telephone", "make", "an urgent call", False),
("Yellow bird flying over the road", [92.2, 80.9, 96.9, 83.9], "The yellow bird flying over the road", "swoop", "low over the tarmac", False),
("Pigeons on the pavement", [96.6, 91.4, 98.7, 94.5], "The pigeons on the pavement", "peck", "at the crumbs", True),
("Second police car", [89.2, 97.2, 96.9, 99.9], "The second police car", "wait", "at the side of the road", False),
("Boy at the brick school window", [64.7, 78.4, 67.6, 79.9], "The boy at the brick school window", "press", "his nose to the glass", False),
]
