# Page 18 — country fair with rodeo, marquee, stage and market. Boxes read off tiler grid labels.
# (name, [ymin, xmin, ymax, xmax], subject, bare-infinitive verb, rest, plural)

P = [
    # ---------- r0c0  x0-28 y0-36.3 ----------
    ("White house with a red roof", [6.4, 7.6, 18.6, 19.3],
     "The white house", "stand", "on the hill above the fair", False),
    ("Round window in the gable", [9.4, 14.1, 11.3, 15.6],
     "The round window", "look", "out from the gable end", False),
    ("Red tractor with a cab", [11.8, 5.0, 27.5, 18.0],
     "The red tractor", "pull", "a trailer down the lane", False),
    ("Driver of the red tractor", [15.0, 12.3, 18.7, 14.5],
     "The tractor driver", "steer", "carefully down the hill", False),
    ("Orange beacon on the cab roof", [12.0, 12.6, 13.4, 13.7],
     "The orange beacon", "flash", "on top of the cab", False),
    ("Big rear wheel of the red tractor", [19.7, 12.7, 26.2, 16.9],
     "The tractor's rear wheel", "roll", "along the country lane", False),
    ("Front wheel of the red tractor", [20.8, 5.9, 27.1, 9.4],
     "The tractor's front wheel", "turn", "towards the fairground", False),
    ("Green trailer full of passengers", [17.1, 18.4, 24.8, 27.0],
     "The green trailer", "carry", "visitors to the fair", False),
    ("Wheel of the green trailer", [22.0, 20.3, 24.8, 22.3],
     "The trailer wheel", "bump", "over the rough lane", False),
    ("Boy in a green top on the trailer", [15.3, 19.7, 18.5, 21.4],
     "The boy on the trailer", "wave", "at the people below", False),
    ("Woman in a blue top on the trailer", [15.0, 21.5, 18.5, 23.6],
     "The woman on the trailer", "hold", "on to the side rail", False),
    ("Person in a straw hat on the trailer", [15.3, 23.5, 18.5, 25.1],
     "The person in the straw hat", "sit", "at the back of the trailer", False),
    ("Horse in the hillside field", [14.1, 1.9, 18.5, 5.5],
     "The horse", "graze", "in the field above the fair", False),
    ("Wooden fence in the field", [16.2, 1.6, 19.0, 6.7],
     "The wooden fence", "run", "along the edge of the field", False),
    ("White picket fence by the house", [17.6, 17.5, 20.6, 19.9],
     "The picket fence", "surround", "the little garden", False),
    ("Trees behind the house", [5.0, 23.1, 15.5, 28.0],
     "The trees", "grow", "thickly behind the house", True),
    ("Yellow-green tree on the hill", [9.9, 3.3, 16.9, 8.3],
     "The leafy tree", "stand", "alone on the hillside", False),
    ("Man in a yellow shirt waving", [23.9, 2.2, 33.6, 5.0],
     "The man in the yellow shirt", "wave", "up at the tractor", False),
    ("Woman in a red top on the slope", [25.3, 19.4, 32.2, 21.7],
     "The woman in the red top", "climb", "up the grassy slope", False),
    ("Yellow striped stall awning", [29.7, 5.3, 32.7, 12.8],
     "The striped awning", "shade", "the stall below it", False),

    # ---------- r0c1  x22-53 y0-36.3 ----------
    ("Big marquee tent", [4.1, 25.3, 36.4, 53.0],
     "The big marquee", "stand", "in the middle of the fairground", False),
    ("Finial at the top of the tent", [3.9, 37.9, 5.5, 38.9],
     "The tent finial", "point", "up into the blue sky", False),
    ("Blue roof of the marquee", [5.0, 25.4, 25.2, 53.0],
     "The tent roof", "slope", "down over the fair", False),
    ("Red canvas wall of the tent", [20.4, 25.6, 36.4, 33.8],
     "The tent wall", "flap", "gently in the breeze", False),
    ("Window in the tent wall", [24.8, 26.8, 30.8, 32.6],
     "The tent window", "let", "light into the marquee", False),
    ("Balloon bird on the guy rope", [5.3, 42.0, 9.9, 46.2],
     "The balloon bird", "float", "above the tent", False),
    ("Rolled canvas along the tent", [21.8, 33.3, 25.2, 44.3],
     "The rolled canvas", "rest", "along the front of the tent", False),
    ("Second rolled canvas", [22.7, 42.9, 26.2, 49.3],
     "The second roll of canvas", "sit", "above the open side", False),
    ("Large tree behind the tent", [4.8, 22.8, 15.0, 28.7],
     "The large tree", "rise", "behind the marquee", False),
    ("Man in a green shirt at a table", [27.8, 35.5, 34.5, 39.4],
     "The man in the green shirt", "eat", "his lunch in the tent", False),
    ("Bottle on the table", [30.9, 39.6, 33.1, 40.5],
     "The bottle", "stand", "on the wooden table", False),
    ("Boy in a striped shirt in the tent", [27.1, 46.1, 33.6, 48.0],
     "The boy in the striped shirt", "reach", "across the table", False),
    ("Man in a red shirt raising his arm", [30.2, 46.3, 36.4, 49.3],
     "The man in the red shirt", "raise", "his arm to call a friend", False),
    ("Man in a white shirt and cap", [26.4, 49.7, 33.6, 52.2],
     "The man in the white shirt", "serve", "the people in the tent", False),

    # ---------- r0c2  x47-78 y0-36.3 ----------
    ("Green and white striped banner", [7.8, 55.7, 15.0, 62.5],
     "The green striped banner", "flutter", "above the fairground", False),
    ("Blue and white striped banner", [7.1, 64.2, 15.5, 70.2],
     "The blue striped banner", "wave", "in the summer wind", False),
    ("Yellow and white striped banner", [8.0, 73.0, 15.5, 76.3],
     "The yellow banner", "snap", "at the top of its pole", False),
    ("Flag pole by the grandstand", [9.0, 63.3, 21.4, 63.9],
     "The flag pole", "stand", "beside the grandstand", False),
    ("Grandstand full of spectators", [10.6, 63.6, 34.5, 78.0],
     "The grandstand", "fill", "up with cheering people", False),
    ("Man filming with a camera", [16.4, 65.0, 23.4, 67.3],
     "The man with the camera", "film", "the rodeo from the stand", False),
    ("Woman in a purple top standing up", [13.2, 70.3, 19.6, 72.4],
     "The woman in the purple top", "stand", "up to see better", False),
    ("Man in a white hat cheering", [12.7, 72.5, 17.3, 74.2],
     "The man in the white hat", "cheer", "for the rodeo rider", False),
    ("Elderly man at the cake table", [26.4, 55.4, 31.7, 57.9],
     "The elderly man", "wait", "for a slice of cake", False),
    ("Table covered with cakes", [29.7, 53.2, 36.4, 61.3],
     "The cake table", "hold", "a row of home made cakes", False),
    ("Cake on a stand", [30.2, 53.5, 32.7, 55.9],
     "The cake", "sit", "proudly on its stand", False),
    ("Second cake on the table", [30.4, 56.0, 32.7, 58.7],
     "The second cake", "wait", "to be cut into slices", False),
    ("Metal urn on the table", [27.4, 58.9, 31.3, 60.7],
     "The metal urn", "keep", "the coffee hot", False),
    ("Man in a white cap and apron", [26.0, 49.8, 33.6, 52.2],
     "The man in the apron", "serve", "cake to the visitors", False),

    # ---------- r0c3  x72-100 y0-36.3 ----------
    ("Man in a green striped shirt cheering", [10.6, 75.3, 20.0, 78.3],
     "The man in the striped shirt", "punch", "the air with excitement", False),
    ("Man in a yellow shirt shouting", [13.4, 77.3, 20.0, 79.3],
     "The man in the yellow shirt", "shout", "encouragement to the rider", False),
    ("Woman in a white hat in the stand", [12.2, 72.5, 16.9, 74.4],
     "The woman in the white hat", "watch", "the rodeo closely", False),
    ("Woman in a pink top in the stand", [20.4, 79.6, 28.3, 82.0],
     "The woman in the pink top", "lean", "forward in her seat", False),
    ("Small dog on the stand rail", [17.6, 82.8, 21.0, 84.4],
     "The little dog", "perch", "on the rail of the stand", False),
    ("Red barn on the hillside", [16.9, 88.1, 23.6, 95.0],
     "The red barn", "stand", "behind the rodeo ring", False),
    ("Big tree beside the barn", [1.3, 90.8, 23.4, 100.0],
     "The big tree", "shade", "the corner of the field", False),
    ("Trunk of the big tree", [15.3, 95.3, 23.4, 97.7],
     "The tree trunk", "rise", "beside the red barn", False),
    ("Boy leaning on the arena fence", [23.4, 91.9, 28.3, 94.6],
     "The boy at the fence", "lean", "over to watch the bull", False),
    ("Man in a white shirt at the fence", [23.6, 95.2, 28.5, 97.5],
     "The man at the fence", "watch", "the rodeo from the rail", False),
    ("Rodeo arena fence", [27.8, 72.0, 33.6, 100.0],
     "The arena fence", "curve", "around the rodeo ring", False),
    ("Bucking bull in the arena", [24.6, 79.0, 44.0, 96.1],
     "The bucking bull", "kick", "wildly in the sandy ring", False),
    ("Rodeo rider on the bull", [24.6, 87.5, 33.6, 93.0],
     "The rodeo rider", "hang", "on to the bucking bull", False),
    ("Black hat of the rodeo rider", [25.0, 88.5, 27.1, 90.3],
     "The rider's black hat", "fly", "off his head", False),

    # ---------- r1c0  x0-28 y30.3-69.7 ----------
    ("Green vintage tractor", [35.3, 0.0, 49.5, 9.1],
     "The green vintage tractor", "stand", "on display at the fair", False),
    ("Wheel of the green tractor", [43.5, 1.6, 49.6, 5.2],
     "The green tractor's wheel", "sit", "heavy on the sand", False),
    ("Blue vintage tractor", [32.8, 4.5, 44.4, 15.6],
     "The blue vintage tractor", "shine", "in the afternoon sun", False),
    ("Exhaust stack of the blue tractor", [32.8, 12.7, 37.9, 13.7],
     "The exhaust stack", "rise", "above the old engine", False),
    ("Front wheel of the blue tractor", [40.7, 7.0, 44.4, 9.1],
     "The blue tractor's front wheel", "rest", "on the fairground sand", False),
    ("Grey vintage tractor", [31.6, 14.0, 41.1, 19.3],
     "The grey tractor", "wait", "in the row of old machines", False),
    ("Dark red vintage tractor", [31.8, 18.4, 41.1, 27.3],
     "The dark red tractor", "attract", "a crowd of admirers", False),
    ("Exposed engine of the red tractor", [35.8, 20.0, 39.3, 23.6],
     "The old engine", "sit", "open for everyone to see", False),
    ("Rear wheel of the dark red tractor", [37.0, 24.6, 40.9, 27.3],
     "The red tractor's rear wheel", "tower", "over the visitors", False),
    ("Boy in a white top running", [45.6, 2.5, 54.2, 8.8],
     "The running boy", "race", "across the fairground", False),
    ("Man in a green top bending down", [42.6, 10.1, 50.3, 13.1],
     "The man in the green top", "bend", "down towards the dog", False),
    ("Child with a dog", [43.5, 11.6, 50.1, 14.0],
     "The child with the dog", "hold", "the puppy carefully", False),
    ("Dog being held up", [47.0, 12.1, 50.1, 14.9],
     "The little dog", "wriggle", "in the child's arms", False),
    ("Man in a blue jacket and white hat", [37.9, 16.3, 48.2, 19.3],
     "The man in the white hat", "admire", "the old tractors", False),
    ("Woman in a red coat with a camera", [40.9, 19.7, 53.8, 23.0],
     "The woman in the red coat", "photograph", "the vintage machines", False),
    ("Man kneeling with a camera", [46.1, 23.4, 53.8, 27.3],
     "The kneeling photographer", "crouch", "down for a better shot", False),
    ("Black and white cat", [43.5, 23.7, 45.1, 25.7],
     "The black and white cat", "slink", "between the tractors", False),
    ("Boy pulling a wooden cart", [50.3, 10.9, 57.5, 13.4],
     "The boy with the cart", "pull", "the little cart along", False),
    ("Wooden soapbox cart", [52.2, 12.1, 59.4, 17.7],
     "The wooden cart", "rattle", "over the sandy ground", False),
    ("Boy pushing the cart", [51.5, 13.2, 56.6, 15.6],
     "The pushing boy", "shove", "the cart from behind", False),
    ("Child riding in the cart", [52.0, 14.7, 55.6, 16.8],
     "The child in the cart", "hold", "on tightly to the sides", False),
    ("Man at the sound desk", [58.2, 2.5, 66.9, 6.0],
     "The sound engineer", "adjust", "the volume for the band", False),
    ("Sound mixing desk", [64.3, 0.0, 69.8, 8.4],
     "The mixing desk", "control", "the sound on the stage", False),
    ("Man with a guitar beside the stage", [59.4, 10.9, 68.7, 14.6],
     "The guitarist", "tune", "his guitar by the stage", False),
    ("Woman in a white sun hat waving", [56.1, 20.4, 68.7, 23.9],
     "The woman in the sun hat", "wave", "to someone in the crowd", False),
    ("White sun hat", [56.1, 20.9, 58.4, 23.6],
     "The white sun hat", "shade", "the woman's face", False),
    ("Man in a yellow jacket and red cap", [54.5, 25.2, 66.9, 28.0],
     "The man in the yellow jacket", "walk", "through the crowd", False),

    # ---------- r1c1  x22-53 y30.3-69.7 ----------
    ("Photographer kneeling by the tractors", [37.0, 27.3, 45.4, 30.6],
     "The photographer", "kneel", "to photograph the tractors", False),
    ("Big bunch of balloon animals", [34.4, 32.1, 50.1, 40.0],
     "The bunch of balloons", "bob", "above the crowd", False),
    ("Balloon flower", [41.6, 34.7, 45.4, 37.2],
     "The balloon flower", "stand", "out among the animals", False),
    ("Pink balloon poodle", [45.6, 32.8, 48.6, 34.7],
     "The balloon poodle", "dangle", "from the seller's hand", False),
    ("Red balloon ball", [35.8, 37.0, 38.6, 38.8],
     "The red balloon", "float", "at the top of the bunch", False),
    ("Balloon seller in a red hat", [53.1, 37.0, 62.2, 40.0],
     "The balloon seller", "hold", "a huge bunch of balloons", False),
    ("Red hat of the balloon seller", [53.1, 37.5, 54.7, 39.4],
     "The red hat", "sit", "on the seller's head", False),
    ("Woman in a white top with a child", [55.2, 32.8, 66.9, 36.0],
     "The woman in the white top", "point", "at the balloons", False),
    ("Small child reaching for a balloon", [60.1, 34.8, 66.9, 36.6],
     "The little child", "reach", "up for a balloon", False),
    ("Boy carrying a tray of food", [40.0, 40.4, 52.4, 42.8],
     "The boy with the tray", "carry", "food back to his family", False),
    ("Tray of food", [44.7, 40.6, 46.3, 43.1],
     "The tray of food", "balance", "in the boy's hands", False),
    ("Child in a green dress skipping", [45.4, 29.0, 51.9, 32.0],
     "The skipping child", "skip", "across the fairground", False),
    ("Red cap of the man in yellow", [53.8, 26.2, 55.6, 28.1],
     "The red cap", "sit", "back on the man's head", False),
    ("Cow in the show pen", [40.9, 44.9, 49.1, 53.0],
     "The show cow", "stand", "quietly in its pen", False),
    ("Blue curtain of the show pen", [41.6, 44.0, 52.8, 53.0],
     "The blue curtain", "hang", "around the show pen", False),
    ("Wooden crate of balloons", [52.6, 42.0, 58.0, 46.2],
     "The wooden crate", "hold", "the seller's spare balloons", False),
    ("Man in green dungarees", [52.6, 46.3, 64.0, 49.3],
     "The man in the dungarees", "lead", "the cattle to the ring", False),
    ("Girl in a red top with a child", [59.4, 42.9, 66.9, 45.6],
     "The girl in the red top", "hold", "a small child's hand", False),
    ("Blonde girl in a green top", [61.3, 37.0, 69.8, 39.4],
     "The girl in the green top", "look", "up at the balloons", False),

    # ---------- r1c2  x47-78 y30.3-69.7 ----------
    ("Cow being led to the ring", [39.8, 50.3, 48.6, 59.4],
     "The brown and white cow", "walk", "slowly towards the ring", False),
    ("Man leading the cow", [40.2, 57.4, 48.2, 59.7],
     "The man with the halter", "lead", "the cow to the contest", False),
    ("Second cow in the pen", [44.9, 47.0, 48.8, 53.7],
     "The second cow", "wait", "its turn in the pen", False),
    ("Beauty contest sign", [32.8, 60.2, 45.4, 69.3],
     "The contest sign", "hang", "over the show ring", False),
    ("Painted cow's head on the sign", [34.2, 63.3, 38.6, 67.2],
     "The painted cow", "smile", "down from the sign", False),
    ("Green winner's wreath", [43.5, 63.3, 49.1, 65.9],
     "The green wreath", "wait", "for the winning cow", False),
    ("Boy in dungarees and a green cap", [45.8, 52.9, 57.5, 55.3],
     "The boy in the green cap", "help", "with the show cattle", False),
    ("Green cap of the boy", [45.8, 53.5, 47.2, 55.0],
     "The green cap", "shade", "the boy's eyes", False),
    ("Yellow wellington boots", [55.2, 53.2, 57.5, 55.1],
     "The yellow boots", "keep", "the boy's feet clean", True),
    ("Girl in dungarees leading a cow", [46.1, 55.4, 58.0, 57.9],
     "The girl in the dungarees", "lead", "her cow into the ring", False),
    ("Green wellington boots", [55.4, 55.5, 58.0, 57.6],
     "The green boots", "sink", "into the soft sand", True),
    ("Prize cow at the contest", [48.6, 57.7, 58.0, 63.1],
     "The prize cow", "stand", "still for the judges", False),
    ("Woman holding up a wreath", [48.0, 62.9, 60.3, 65.6],
     "The woman with the wreath", "hold", "up the winner's garland", False),
    ("Man in a red waistcoat", [47.5, 66.2, 59.4, 68.7],
     "The man in the red waistcoat", "announce", "the winner of the contest", False),
    ("Clown in a yellow hat", [39.3, 72.8, 51.4, 77.0],
     "The clown", "dance", "along the arena rail", False),
    ("Clown's yellow hat", [39.3, 73.3, 41.4, 75.2],
     "The clown's hat", "wobble", "on top of his head", False),
    ("Clown's spotted red trousers", [44.7, 73.3, 49.6, 75.9],
     "The spotted trousers", "flap", "as the clown dances", False),
    ("Woman with an ice cream", [50.8, 73.0, 61.2, 75.9],
     "The woman with the ice cream", "enjoy", "a cone in the sunshine", False),
    ("Ice cream cone", [51.0, 75.1, 52.8, 76.4],
     "The ice cream", "melt", "slowly in the heat", False),
    ("Woman in a purple dress", [57.1, 51.1, 68.7, 54.3],
     "The woman in the purple dress", "watch", "the cattle judging", False),
    ("Blue and white parasol", [57.8, 67.9, 61.7, 72.1],
     "The parasol", "shade", "the stall beneath it", False),
    ("Man in a yellow jacket with a hat", [60.1, 71.0, 69.8, 73.5],
     "The man in the yellow jacket", "walk", "his dog through the fair", False),
    ("Poodle on a lead", [63.6, 73.7, 66.9, 75.2],
     "The poodle", "trot", "along on its lead", False),
    ("Child with arms in the air", [62.9, 55.8, 69.8, 58.0],
     "The excited child", "throw", "both arms into the air", False),

    # ---------- r1c3  x72-100 y30.3-69.7 ----------
    ("Second clown in green trousers", [42.1, 91.0, 53.8, 94.3],
     "The second clown", "run", "across the rodeo ring", False),
    ("Feathered hat of the second clown", [42.1, 91.9, 44.0, 93.7],
     "The feathered hat", "bounce", "as the clown runs", False),
    ("Clown's big red shoes", [49.6, 89.0, 53.5, 93.7],
     "The big red shoes", "flap", "across the sand", True),
    ("White goose in the arena", [43.1, 96.4, 48.2, 98.6],
     "The white goose", "waddle", "along the arena fence", False),
    ("Man in a white shirt at the rail", [48.4, 79.8, 60.3, 82.7],
     "The man at the rail", "point", "at the bucking bull", False),
    ("Man in a yellow shirt at the rail", [49.1, 84.2, 60.3, 87.2],
     "The man in the yellow shirt", "lean", "on the arena rail", False),
    ("Man in a cowboy hat by the bushes", [55.7, 95.5, 62.2, 98.7],
     "The man in the cowboy hat", "stand", "beside the green bushes", False),
    ("Straw cowboy hat", [55.7, 95.9, 57.5, 98.4],
     "The cowboy hat", "shade", "the man's face", False),
    ("Green bush by the arena", [54.7, 89.8, 61.7, 95.5],
     "The green bush", "grow", "beside the rodeo ring", False),
    ("Metal picnic bench", [47.5, 94.4, 53.8, 100.0],
     "The picnic bench", "wait", "empty at the field edge", False),
    ("Confetti falling in the arena", [37.1, 79.7, 42.0, 85.9],
     "The confetti", "flutter", "down onto the sand", True),

    # ---------- r2c0  x0-28 y63.7-100 ----------
    ("Wooden stage", [84.7, 0.0, 97.2, 25.7],
     "The wooden stage", "hold", "the whole country band", False),
    ("Red stage curtain", [65.2, 0.2, 85.2, 20.5],
     "The red curtain", "hang", "behind the band", False),
    ("Hoedown welcome sign", [70.8, 0.4, 84.7, 5.2],
     "The welcome sign", "greet", "everyone at the hoedown", False),
    ("Cartoon cow on the sign", [77.8, 1.4, 84.2, 4.4],
     "The painted cow", "play", "a guitar on the sign", False),
    ("Loudspeaker on the left", [70.1, 5.6, 78.7, 8.8],
     "The loudspeaker", "blast", "music across the fair", False),
    ("Loudspeaker on the right", [66.2, 16.9, 72.6, 19.3],
     "The second loudspeaker", "hang", "above the stage", False),
    ("Fiddler in a cowboy hat", [72.7, 9.8, 84.7, 12.8],
     "The fiddler", "play", "a fast country tune", False),
    ("Fiddler's straw cowboy hat", [72.7, 9.9, 74.3, 11.8],
     "The fiddler's hat", "tip", "back on his head", False),
    ("Banjo player in a red cap", [72.0, 12.9, 84.7, 15.9],
     "The banjo player", "pick", "at the strings", False),
    ("Red cap of the banjo player", [72.0, 13.7, 73.4, 15.2],
     "The red cap", "sit", "low over his eyes", False),
    ("Banjo", [76.9, 13.0, 80.0, 15.7],
     "The banjo", "ring", "out across the fairground", False),
    ("Double bass player", [75.2, 6.5, 89.8, 12.2],
     "The bass player", "lean", "into his double bass", False),
    ("Double bass", [72.2, 8.7, 84.7, 12.2],
     "The double bass", "thump", "out a steady rhythm", False),
    ("Woman playing a guitar", [75.4, 17.4, 84.7, 20.2],
     "The guitarist on the stage", "strum", "along with the band", False),
    ("Guitar on the stage", [77.8, 17.2, 82.1, 19.9],
     "The guitar", "rest", "on the player's knee", False),
    ("Girl playing a fiddle", [78.7, 15.2, 89.8, 18.3],
     "The young fiddler", "dance", "while she plays", False),
    ("Man dancing below the stage", [85.4, 1.6, 97.2, 4.4],
     "The dancing man", "clap", "along with the music", False),
    ("Boy in a red top with a drink", [90.3, 5.5, 100.0, 8.3],
     "The boy in the red top", "hold", "a cold drink", False),
    ("Boy with his arms raised", [86.8, 10.9, 100.0, 14.0],
     "The boy in the beige top", "cheer", "for the band", False),
    ("Man in a straw hat with a rucksack", [85.6, 20.3, 98.6, 23.9],
     "The man with the rucksack", "walk", "past the stage", False),
    ("Straw hat of the walking man", [85.6, 22.0, 87.5, 24.0],
     "The straw hat", "shade", "the walking man", False),
    ("Child in a striped top running", [91.5, 25.2, 99.0, 28.0],
     "The running child", "dash", "towards the music", False),
    ("Brown hen near the stage", [78.5, 24.3, 81.9, 27.0],
     "The brown hen", "peck", "at the sandy ground", False),
    ("Green bush behind the stage", [72.9, 20.0, 84.2, 23.6],
     "The green bush", "grow", "at the edge of the stage", False),

    # ---------- r2c1  x22-53 y63.7-100 ----------
    ("Woman in a red jacket walking", [65.0, 26.2, 77.3, 29.7],
     "The woman in the red jacket", "walk", "hand in hand with a friend", False),
    ("Woman in a white top in the crowd", [64.1, 22.2, 76.3, 25.5],
     "The woman in the white top", "stroll", "through the fairground", False),
    ("Woman pushing a pushchair", [69.2, 30.8, 82.4, 34.7],
     "The woman with the pushchair", "push", "her baby through the crowd", False),
    ("Pushchair in the crowd", [75.9, 31.9, 84.7, 35.1],
     "The pushchair", "roll", "slowly over the sand", False),
    ("Toddler in the pushchair", [76.1, 33.0, 81.9, 35.2],
     "The toddler", "watch", "the fair go by", False),
    ("Man in a green shirt walking", [72.0, 36.4, 86.5, 39.4],
     "The man in the green shirt", "walk", "towards the market stalls", False),
    ("Woman in a purple top and blue skirt", [72.7, 39.2, 86.5, 42.3],
     "The woman in the blue skirt", "carry", "a drink through the crowd", False),
    ("Woman with shopping bags", [67.5, 45.0, 80.5, 49.3],
     "The woman with the bags", "carry", "her shopping home", False),
    ("White shopping bag", [75.0, 45.0, 78.7, 46.8],
     "The white bag", "swing", "from the woman's hand", False),
    ("Yellow handbag", [75.2, 47.0, 78.7, 49.3],
     "The yellow handbag", "hang", "over the woman's arm", False),
    ("Hen pecking in the crowd", [78.0, 24.5, 81.9, 27.2],
     "The hen", "wander", "between people's feet", False),
    ("Small dog running loose", [80.3, 46.1, 83.5, 49.3],
     "The little dog", "run", "loose across the fairground", False),
    ("Girl in a pink top playing", [85.6, 27.6, 94.4, 31.4],
     "The girl in the pink top", "spin", "round with her friend", False),
    ("Girl in a purple top running", [88.2, 31.5, 94.9, 36.4],
     "The girl in the purple top", "chase", "her friend across the sand", False),
    ("Small boy in a striped top", [91.0, 25.3, 98.6, 28.7],
     "The small boy", "run", "after the older children", False),
    ("Boy playing at the limbo pole", [84.5, 38.9, 97.7, 44.3],
     "The boy at the pole", "bend", "backwards under the pole", False),
    ("Woman in green trousers dancing", [84.7, 44.1, 97.7, 48.5],
     "The dancing woman", "sway", "to the country music", False),
    ("Long wooden limbo pole", [83.6, 44.7, 99.1, 51.7],
     "The long pole", "stretch", "across the dancing game", False),

    # ---------- r2c2  x47-78 y63.7-100 ----------
    ("Man in a beige jumper walking", [68.0, 51.7, 81.9, 55.1],
     "The man in the beige jumper", "walk", "towards the market", False),
    ("Woman with her hands on her hips", [65.0, 59.9, 77.3, 62.5],
     "The woman in the purple top", "stand", "with her hands on her hips", False),
    ("Boy in a green shirt beside her", [70.1, 62.0, 77.3, 64.4],
     "The boy in the green shirt", "wait", "beside his mother", False),
    ("Man carrying a crate of vegetables", [75.4, 54.0, 87.0, 57.9],
     "The man with the crate", "carry", "vegetables to the stall", False),
    ("Red cap of the crate carrier", [75.4, 54.8, 77.0, 56.7],
     "The red cap", "keep", "the sun off his head", False),
    ("Crate of green vegetables", [80.1, 54.3, 82.8, 58.5],
     "The crate of vegetables", "weigh", "heavy in his arms", False),
    ("Boy in green dungarees", [73.6, 56.8, 80.5, 58.8],
     "The boy in the dungarees", "help", "at the vegetable stall", False),
    ("Woman in a red top at the stall", [75.4, 59.9, 83.8, 62.8],
     "The woman at the stall", "arrange", "the produce on the table", False),
    ("Crate of produce on the stall", [80.8, 61.6, 82.8, 63.9],
     "The crate of produce", "sit", "at the front of the stall", False),
    ("White market stall table", [77.8, 61.9, 87.0, 70.1],
     "The market stall", "display", "honey and fresh eggs", False),
    ("Jars of honey on the stall", [80.1, 65.4, 82.6, 68.7],
     "The jars of honey", "glow", "golden in the sunshine", True),
    ("Tray of eggs on the stall", [77.1, 67.3, 78.7, 70.5],
     "The tray of eggs", "sit", "at the back of the stall", False),
    ("Woman in a white coat serving", [76.4, 69.9, 89.1, 72.1],
     "The woman in the white coat", "serve", "a customer at the stall", False),
    ("Man in a brown jacket buying", [76.2, 71.6, 89.1, 74.2],
     "The man in the brown jacket", "choose", "a jar of honey", False),
    ("Flower stall with sunflowers", [81.9, 55.4, 95.4, 65.6],
     "The flower stall", "brighten", "the whole corner of the fair", False),
    ("Sunflowers in a pot", [81.9, 57.4, 86.5, 60.2],
     "The sunflowers", "lean", "towards the sun", True),
    ("Blue flower pot", [87.0, 58.0, 89.8, 60.2],
     "The blue pot", "hold", "a leafy green plant", False),
    ("Pink and red flowers", [84.0, 60.5, 89.8, 65.0],
     "The pink flowers", "spill", "over the edge of the stall", True),
    ("Yellow flower pot", [91.0, 60.0, 94.4, 62.5],
     "The yellow pot", "stand", "at the front of the display", False),
    ("Girl in a yellow top with a stick", [88.4, 51.1, 100.0, 54.3],
     "The girl in the yellow top", "hold", "one end of the pole", False),
    ("Antique cartwheel on display", [68.0, 68.2, 73.8, 71.2],
     "The old cartwheel", "lean", "against the display cart", False),

    # ---------- r2c3  x72-100 y63.7-100 ----------
    ("Red and white striped market awning", [63.7, 75.0, 72.6, 100.0],
     "The striped awning", "shade", "the market stalls below", False),
    ("Vegetable market stall", [72.2, 85.1, 78.6, 96.1],
     "The vegetable stall", "overflow", "with fresh produce", False),
    ("Tray of tomatoes", [72.9, 90.2, 75.9, 93.3],
     "The tray of tomatoes", "shine", "bright red on the stall", False),
    ("Tray of green vegetables", [72.6, 87.5, 75.6, 90.6],
     "The green vegetables", "sit", "neatly in their tray", True),
    ("Tray of cucumbers", [75.2, 90.8, 78.2, 94.3],
     "The cucumbers", "lie", "in a long green row", True),
    ("Bread rolls on the stall", [72.6, 85.1, 75.4, 88.1],
     "The bread rolls", "wait", "on the front of the stall", True),
    ("Cash register on the stall", [70.3, 81.9, 73.8, 85.0],
     "The cash register", "sit", "at the end of the counter", False),
    ("Stall holder in a yellow top", [69.9, 85.4, 75.9, 88.6],
     "The stall holder", "serve", "the queue of customers", False),
    ("Crate of potatoes", [80.1, 92.2, 86.5, 99.2],
     "The crate of potatoes", "stand", "beside the market stall", False),
    ("Price sign on the potato stall", [76.4, 96.7, 79.1, 99.2],
     "The price sign", "hang", "above the potatoes", False),
    ("Man in a blue apron at the potatoes", [85.0, 92.1, 92.6, 96.1],
     "The man in the blue apron", "pick", "out the best potatoes", False),
    ("Woman in a red coat shopping", [69.2, 79.6, 81.4, 82.7],
     "The woman in the red coat", "browse", "along the market stalls", False),
    ("Boy in a white top at the market", [74.3, 82.4, 83.3, 84.6],
     "The boy in the white top", "hold", "his grandmother's hand", False),
    ("Woman pushing a buggy at the market", [75.0, 84.4, 87.0, 87.5],
     "The woman with the buggy", "push", "her child past the stalls", False),
    ("Buggy at the market", [80.8, 86.2, 88.4, 91.2],
     "The buggy", "roll", "along beside the stalls", False),
    ("Child in the buggy pointing", [79.8, 88.7, 85.2, 90.9],
     "The child in the buggy", "point", "at the bright vegetables", False),
    ("Woman in a yellow top with a bag", [70.8, 75.9, 86.5, 78.7],
     "The woman in the yellow top", "carry", "her shopping bag", False),
    ("Man carrying a child on his shoulders", [68.0, 76.1, 75.4, 78.7],
     "The man with the child", "carry", "his son on his shoulders", False),
    ("Boy in a green top in the crowd", [80.1, 79.3, 87.9, 82.0],
     "The boy in the green top", "follow", "his family through the market", False),
    ("Woman in a green jacket with a handbag", [85.0, 80.4, 98.6, 83.5],
     "The woman in the green jacket", "chat", "with a friend", False),
    ("Brown handbag", [91.9, 80.4, 95.4, 82.3],
     "The brown handbag", "hang", "from the woman's shoulder", False),
    ("Man in a red top with a bucket", [85.0, 84.7, 98.6, 88.4],
     "The man with the bucket", "carry", "his shopping in a bucket", False),
    ("Blue bucket of shopping", [92.6, 87.1, 95.4, 88.7],
     "The blue bucket", "swing", "as the man walks", False),
    ("Woman in a yellow jacket", [88.4, 75.6, 100.0, 78.7],
     "The woman in the yellow jacket", "head", "home from the market", False),
    ("Green bushes at the fair's edge", [91.5, 86.1, 100.0, 100.0],
     "The green bushes", "edge", "the far side of the field", True),
]
