# Page 17 — riding stable / equestrian centre. Boxes read off tiler grid labels, per tile.
# (name, [ymin, xmin, ymax, xmax], subject, bare-infinitive verb, rest, plural)

P = [
    # ---------- r0c0  x0-28 y0-36.3 ----------
    ("Woman carrying buckets to the stables", [1.6, 9.3, 12.8, 13.1],
     "The woman with the buckets", "carry", "water down to the stables", False),
    ("Yellow sun hat", [1.5, 10.3, 2.9, 12.0],
     "The yellow sun hat", "shade", "the woman's face", False),
    ("Blue bucket of water", [6.6, 8.4, 8.9, 10.0],
     "The blue bucket", "swing", "from the woman's hand", False),
    ("Brown dog running down the lane", [9.9, 13.2, 13.1, 17.7],
     "The brown dog", "run", "down the sandy lane", False),
    ("Wooden paddock fence on the hill", [1.3, 13.2, 8.9, 24.2],
     "The wooden fence", "surround", "the green paddock", False),
    ("Big tree beside the paddock", [0.0, 22.8, 20.0, 27.3],
     "The big tree", "shade", "the corner of the paddock", False),
    ("Open wooden shelter", [9.0, 3.3, 18.9, 10.8],
     "The wooden shelter", "keep", "the hay out of the rain", False),
    ("Girl in a white top holding a pony", [12.9, 17.5, 20.0, 20.2],
     "The girl in the white top", "hold", "the pony by its halter", False),
    ("Light brown pony being led", [13.2, 12.7, 20.0, 19.3],
     "The light brown pony", "follow", "the girl across the yard", False),
    ("Big brown horse being groomed", [19.2, 4.7, 30.7, 19.3],
     "The big brown horse", "stand", "still while it is brushed", False),
    ("Girl in a purple top brushing the horse", [19.7, 12.7, 30.7, 16.2],
     "The girl in the purple top", "brush", "the horse's shiny coat", False),
    ("Grooming brush", [20.8, 12.3, 22.4, 13.7],
     "The grooming brush", "sweep", "along the horse's back", False),
    ("Feed bucket on the ground", [22.9, 5.6, 28.0, 7.8],
     "The feed bucket", "stand", "on the ground by the shelter", False),
    ("Yellow feed scoop", [22.9, 5.9, 25.2, 8.1],
     "The yellow scoop", "sit", "in the top of the bucket", False),
    ("Child with a wagon of apples", [18.8, 18.9, 23.4, 21.1],
     "The child with the wagon", "bring", "apples for the horses", False),
    ("Yellow wagon full of apples", [21.1, 18.6, 25.2, 22.0],
     "The yellow wagon", "carry", "a heap of red apples", False),
    ("Riding boots on the ground", [30.6, 12.1, 34.1, 14.9],
     "The riding boots", "lie", "forgotten on the sand", True),
    ("Grey rock beside the path", [19.0, 22.9, 20.8, 24.5],
     "The grey rock", "sit", "beside the sandy path", False),

    # ---------- r0c1  x22-53 y0-36.3 ----------
    ("Large tree with a spreading crown", [0.0, 22.0, 19.5, 34.0],
     "The spreading tree", "cast", "a wide shadow on the grass", False),
    ("Thick trunk of the large tree", [6.9, 25.3, 19.2, 28.7],
     "The thick trunk", "lean", "over the paddock fence", False),
    ("Pinto horse galloping in the field", [1.5, 39.6, 12.7, 48.9],
     "The pinto horse", "gallop", "across the green field", False),
    ("Chestnut horse rolling on its back", [6.0, 32.4, 16.9, 43.1],
     "The chestnut horse", "roll", "happily on the grass", False),
    ("Horse and rider jumping a fence", [6.4, 48.0, 21.4, 53.0],
     "The horse and rider", "jump", "over the wooden fence", False),
    ("Elderly man in a yellow shirt", [20.8, 33.9, 31.7, 36.9],
     "The elderly man", "lean", "on the paddock fence", False),
    ("Fence post in the paddock", [18.1, 30.7, 26.2, 31.8],
     "The fence post", "stand", "firmly in the ground", False),
    ("Rocks in the long grass", [17.6, 26.2, 19.9, 28.7],
     "The rocks", "lie", "half hidden in the grass", True),
    ("Stone at the edge of the arena", [32.2, 37.2, 34.3, 38.9],
     "The stone", "mark", "the edge of the arena", False),

    # ---------- r0c2  x47-78 y0-36.3 ----------
    ("Rider in a blue jacket", [5.7, 50.3, 15.5, 53.7],
     "The rider in the blue jacket", "lean", "forward over the jump", False),
    ("Black riding helmet", [5.7, 51.7, 7.3, 53.3],
     "The riding helmet", "protect", "the rider's head", False),
    ("Chestnut horse clearing a jump", [6.9, 47.0, 22.1, 57.0],
     "The chestnut jumper", "sail", "over the coloured poles", False),
    ("Red and white show jump", [15.3, 51.5, 20.1, 57.9],
     "The show jump", "stand", "in the middle of the field", False),
    ("Wooden jump wing", [17.1, 56.9, 25.2, 58.4],
     "The jump wing", "hold", "up the striped pole", False),
    ("Horse peeping out from behind a tree", [2.9, 58.3, 8.7, 61.8],
     "The curious horse", "peep", "out from behind the tree", False),
    ("Tall dark fir tree", [0.0, 58.0, 20.9, 64.4],
     "The tall fir tree", "tower", "over the stable yard", False),
    ("Large open barn", [1.5, 60.5, 36.4, 78.0],
     "The open barn", "shelter", "the horses in their stalls", False),
    ("Grey corrugated barn roof", [1.5, 60.6, 20.5, 78.0],
     "The barn roof", "slope", "steeply down to the beams", False),
    ("Dark brown horse in the barn doorway", [22.7, 60.5, 34.5, 67.5],
     "The dark brown horse", "look", "out of the barn doorway", False),
    ("Palomino horse in a stall", [24.6, 69.4, 30.8, 72.7],
     "The palomino horse", "wait", "quietly in its stall", False),
    ("Grey horse in the end stall", [25.7, 75.0, 30.6, 78.0],
     "The grey horse", "peer", "over the door of its stall", False),
    ("Boy reaching up to a pony", [27.4, 67.7, 36.4, 69.6],
     "The boy in the striped shirt", "stroke", "the pony's soft nose", False),
    ("Pony's head being petted", [27.4, 67.3, 29.9, 69.0],
     "The pony's head", "lean", "down towards the boy", False),
    ("Man in a white shirt leading a horse", [24.8, 56.3, 36.4, 59.4],
     "The man in the white shirt", "lead", "a horse across the yard", False),
    ("Woman with a pitchfork", [24.3, 51.2, 36.4, 54.3],
     "The woman with the pitchfork", "clean", "out the stable yard", False),
    ("Pitchfork leaning on a shoulder", [23.6, 50.3, 28.0, 51.6],
     "The pitchfork", "rest", "on the woman's shoulder", False),
    ("Barbecue grill on a stand", [30.6, 47.4, 34.8, 50.6],
     "The barbecue", "smoke", "gently by the fence", False),

    # ---------- r0c3  x72-100 y0-36.3 ----------
    ("Hayloft full of straw bales", [10.4, 78.1, 20.0, 85.0],
     "The hayloft", "hold", "the winter store of hay", False),
    ("Man working in the hayloft", [10.6, 80.4, 20.0, 84.7],
     "The man in the hayloft", "stack", "the bales under the roof", False),
    ("Hay winch machine", [10.8, 84.4, 19.8, 92.4],
     "The hay winch", "lift", "the bales up to the loft", False),
    ("Winch arm above the barn", [10.8, 85.9, 13.4, 92.4],
     "The winch arm", "swing", "out over the yard", False),
    ("Hay bale hanging from the winch", [18.5, 90.2, 23.8, 93.3],
     "The hanging bale", "dangle", "high above the ground", False),
    ("Grey and white horse in a stall", [25.5, 74.5, 30.4, 79.3],
     "The grey and white horse", "watch", "the busy yard below", False),
    ("Boy in a yellow riding helmet", [29.0, 82.7, 36.4, 85.2],
     "The boy in the yellow helmet", "get", "ready for his lesson", False),
    ("Metal downpipe on the barn", [24.6, 87.6, 32.7, 88.9],
     "The downpipe", "run", "down the side of the barn", False),
    ("Badger in the grass", [23.6, 96.1, 26.2, 98.7],
     "The badger", "snuffle", "along the edge of the wood", False),

    # ---------- r1c0  x0-28 y30.3-69.7 ----------
    ("Red tiled roof of the farmhouse", [22.8, 0.0, 39.2, 14.0],
     "The red tiled roof", "cover", "the old farmhouse", False),
    ("Yellow wooden farmhouse", [35.3, 0.0, 69.8, 18.3],
     "The yellow farmhouse", "stand", "at the edge of the yard", False),
    ("Dormer window in the roof", [38.6, 1.6, 47.2, 11.1],
     "The dormer window", "look", "out over the stable yard", False),
    ("Person asleep in bed", [41.0, 3.3, 45.8, 7.8],
     "The sleeping person", "doze", "under a warm pink quilt", False),
    ("Pink quilt on the bed", [43.1, 2.5, 46.5, 7.8],
     "The pink quilt", "cover", "the sleeping person", False),
    ("Woman in a yellow top carrying a tray", [51.5, 8.2, 59.4, 12.3],
     "The woman in the yellow top", "bring", "breakfast out to the balcony", False),
    ("Tray of food", [55.2, 9.9, 57.0, 12.2],
     "The tray of food", "wobble", "in the woman's hands", False),
    ("Elderly man at the balcony table", [55.0, 10.7, 64.0, 15.2],
     "The elderly man", "sit", "at the breakfast table", False),
    ("Woman in a purple dress serving", [51.2, 16.3, 61.2, 19.4],
     "The woman in the purple dress", "pour", "a drink for her guest", False),
    ("Table on the balcony", [57.8, 12.9, 62.2, 17.7],
     "The balcony table", "hold", "the breakfast things", False),
    ("Woman in a pink top on the balcony", [56.8, 4.4, 66.8, 7.8],
     "The woman in the pink top", "look", "down at the yard", False),
    ("Small child beside her", [59.4, 1.9, 65.9, 4.1],
     "The small child", "peep", "through the balcony railing", False),
    ("White balcony railing", [59.2, 0.0, 67.8, 24.8],
     "The white railing", "run", "along the front of the balcony", False),
    ("Flower box with red flowers", [62.9, 8.2, 69.1, 14.0],
     "The flower box", "spill", "red flowers over its edge", False),
    ("Flower box with blue flowers", [58.9, 18.1, 64.0, 24.5],
     "The second flower box", "brighten", "the front of the house", False),
    ("Green bush behind the house", [34.2, 13.8, 47.2, 21.4],
     "The green bush", "grow", "against the farmhouse wall", False),
    ("Man riding a bicycle", [29.0, 20.0, 42.5, 28.0],
     "The man on the bicycle", "ride", "across the sandy yard", False),
    ("Bicycle wheel", [36.3, 20.3, 42.6, 24.5],
     "The bicycle wheel", "spin", "over the loose sand", False),
    ("Basket on the bicycle", [34.9, 21.2, 39.3, 24.5],
     "The bicycle basket", "hold", "the shopping for the farm", False),
    ("Red tractor in the yard", [46.8, 18.4, 69.8, 28.0],
     "The red tractor", "park", "in the middle of the yard", False),
    ("Big wheel of the red tractor", [60.1, 21.2, 69.8, 27.3],
     "The red tractor's wheel", "sink", "into the soft sand", False),

    # ---------- r1c1  x22-53 y30.3-69.7 ----------
    ("Red horse-drawn carriage", [26.5, 22.0, 45.3, 33.2],
     "The red carriage", "wait", "for the driver to set off", False),
    ("Spoked wheel of the carriage", [41.0, 27.3, 45.4, 30.3],
     "The carriage wheel", "shine", "in the afternoon sun", False),
    ("Two carriage horses in harness", [34.8, 31.9, 48.6, 45.1],
     "The two carriage horses", "stand", "patiently in their harness", True),
    ("Front carriage horse", [34.8, 35.2, 47.0, 45.1],
     "The front carriage horse", "toss", "its head impatiently", False),
    ("Rear carriage horse", [37.2, 31.9, 48.6, 42.8],
     "The second carriage horse", "wait", "beside its partner", False),
    ("Boy in a red shirt with a carrot", [43.8, 42.7, 51.9, 45.1],
     "The boy in the red shirt", "offer", "a carrot to the horses", False),
    ("Red toolbox on the sand", [43.8, 45.4, 45.8, 48.0],
     "The red toolbox", "sit", "open on the sandy ground", False),
    ("Spotted appaloosa horse", [35.1, 45.7, 46.8, 53.0],
     "The spotted horse", "wait", "for the farrier to finish", False),
    ("Red tractor beside the house", [47.3, 22.0, 67.8, 32.9],
     "The parked tractor", "rest", "beside the farmhouse", False),
    ("Green seat of the tractor", [47.5, 29.9, 53.3, 32.7],
     "The tractor seat", "wait", "for the driver to climb up", False),
    ("Man in white shirt and dungarees", [48.4, 32.4, 62.2, 36.0],
     "The man in the dungarees", "chat", "beside the red tractor", False),
    ("Girl in a blue skirt hugging a friend", [49.6, 37.0, 61.9, 40.0],
     "The girl in the blue skirt", "hug", "her friend in the yard", False),
    ("Girl in a purple top being hugged", [49.4, 38.6, 59.4, 41.2],
     "The girl in the purple top", "smile", "at her friend", False),
    ("Saddled brown horse", [50.8, 44.9, 64.1, 53.0],
     "The saddled horse", "wait", "for its rider", False),
    ("Horse droppings on the sand", [62.9, 45.4, 64.3, 46.8],
     "The droppings", "lie", "on the sandy ground", True),

    # ---------- r1c2  x47-78 y30.3-69.7 ----------
    ("Farrier bending over a hoof", [37.2, 54.6, 46.8, 59.4],
     "The farrier", "check", "the horse's front hoof", False),
    ("Green cap of the farrier", [39.3, 57.8, 41.1, 59.4],
     "The green cap", "hide", "the farrier's face", False),
    ("Farrier's hammer", [37.2, 57.4, 39.0, 58.5],
     "The hammer", "hang", "ready in the farrier's hand", False),
    ("Man in a beige coat walking", [40.9, 59.2, 53.3, 63.5],
     "The man in the beige coat", "stroll", "across the stable yard", False),
    ("Blue flat cap", [40.9, 59.9, 42.6, 61.8],
     "The flat cap", "sit", "on the walking man's head", False),
    ("Silver horse trailer", [36.0, 62.3, 57.5, 78.0],
     "The silver horse trailer", "stand", "with its ramp down", False),
    ("Open door of the horse trailer", [36.0, 62.3, 47.7, 66.2],
     "The trailer door", "swing", "wide open", False),
    ("Loading ramp of the trailer", [50.3, 63.3, 58.0, 70.5],
     "The loading ramp", "reach", "down to the sandy ground", False),
    ("Palomino horse coming down the ramp", [41.6, 63.4, 51.4, 70.5],
     "The palomino horse", "step", "carefully down the ramp", False),
    ("Rider in a yellow top and red cap", [48.4, 51.7, 55.6, 58.2],
     "The rider in the yellow top", "sit", "up straight in the saddle", False),
    ("Red baseball cap", [48.4, 54.5, 50.0, 56.4],
     "The red cap", "keep", "the sun out of her eyes", False),
    ("Brown pony with its head down", [51.2, 47.0, 64.0, 58.2],
     "The brown pony", "drop", "its head towards the ground", False),
    ("Blue saddle blanket", [53.3, 50.0, 57.5, 53.7],
     "The blue saddle blanket", "sit", "under the little saddle", False),
    ("Toy horse on wheels", [57.1, 62.0, 60.1, 65.3],
     "The toy horse", "stand", "abandoned on the sand", False),
    ("Lunge line on the ground", [56.1, 58.6, 61.7, 62.5],
     "The lunge line", "curl", "loosely on the ground", False),
    ("Boy in a red vest", [50.8, 70.5, 62.6, 73.9],
     "The boy in the red vest", "watch", "the horse come off the trailer", False),
    ("Man with a camera", [49.4, 74.7, 62.2, 78.0],
     "The man with the camera", "take", "a photograph of the horses", False),
    ("White paddock fence", [62.0, 54.6, 69.8, 78.0],
     "The white fence", "curve", "around the training ring", False),
    ("Fence post by the ring", [63.6, 59.2, 67.8, 60.4],
     "The fence post", "hold", "the white rails in place", False),
    ("Hen scratching in the sand", [66.0, 65.4, 69.8, 68.1],
     "The hen", "scratch", "in the sandy ground", False),

    # ---------- r1c3  x72-100 y30.3-69.7 ----------
    ("Yellow pickup truck", [31.6, 80.7, 46.8, 98.4],
     "The yellow pickup truck", "park", "beside the open stable", False),
    ("Cab window of the yellow truck", [32.8, 87.1, 37.9, 93.0],
     "The truck's window", "reflect", "the bright afternoon sky", False),
    ("Wheel of the yellow truck", [38.8, 95.2, 42.8, 97.7],
     "The truck's wheel", "rest", "on the dusty ground", False),
    ("Bed of the yellow pickup", [37.4, 81.1, 44.0, 91.2],
     "The truck bed", "wait", "to be loaded with hay", False),
    ("Barred window of the horse trailer", [40.9, 72.2, 45.4, 75.3],
     "The trailer window", "let", "fresh air into the box", False),
    ("Wheel of the horse trailer", [49.6, 76.5, 52.8, 79.3],
     "The trailer wheel", "sit", "still on the sand", False),
    ("Open-sided stable", [41.9, 83.6, 62.2, 100.0],
     "The open stable", "shelter", "the mare and her foal", False),
    ("Corrugated stable roof", [42.1, 83.6, 51.4, 100.0],
     "The stable roof", "keep", "the rain off the animals", False),
    ("Wooden roof post", [48.9, 93.2, 62.2, 94.3],
     "The wooden post", "hold", "up the stable roof", False),
    ("Brown mare in the stable", [48.7, 86.1, 55.6, 95.2],
     "The brown mare", "watch", "over her young foal", False),
    ("Foal lying on the straw", [54.7, 85.9, 59.4, 89.7],
     "The little foal", "rest", "on the soft straw", False),
    ("Vet in a white coat kneeling", [52.4, 90.1, 61.0, 93.4],
     "The vet in the white coat", "kneel", "beside the newborn foal", False),
    ("Girl in a purple top watching", [50.8, 82.1, 59.4, 84.3],
     "The girl in the purple top", "watch", "the foal quietly", False),
    ("Girl in a pink top by the foal", [54.3, 84.5, 59.4, 86.9],
     "The girl in the pink top", "stroke", "the foal gently", False),
    ("Man carrying a wooden plank", [60.1, 92.8, 65.9, 99.2],
     "The man with the plank", "carry", "a board across his shoulder", False),
    ("Wooden plank", [60.1, 95.3, 62.6, 99.2],
     "The wooden plank", "balance", "on the man's shoulder", False),

    # ---------- r2c0  x0-28 y63.7-100 ----------
    ("Old man in a rocking chair", [68.7, 15.5, 78.7, 20.2],
     "The old man", "rock", "gently on the shady porch", False),
    ("White sun hat of the old man", [68.7, 16.1, 70.5, 18.3],
     "The white sun hat", "tip", "forward over his eyes", False),
    ("Wooden rocking chair", [70.6, 15.5, 78.7, 20.2],
     "The rocking chair", "creak", "on the wooden porch", False),
    ("Window with purple curtains", [72.4, 1.6, 79.1, 6.0],
     "The window", "look", "out onto the yard", False),
    ("Cactus on the windowsill", [73.6, 3.3, 76.1, 4.9],
     "The little cactus", "sit", "on the sunny windowsill", False),
    ("Dog lying on the porch", [83.3, 1.6, 87.0, 5.0],
     "The sleepy dog", "lie", "stretched out on the porch", False),
    ("Boy carrying a crate of vegetables", [86.8, 2.5, 100.0, 6.1],
     "The boy with the crate", "carry", "vegetables into the house", False),
    ("Red crate of vegetables", [92.6, 1.8, 96.3, 4.9],
     "The red crate", "hold", "fresh vegetables from the garden", False),
    ("Man in a black top hat", [79.8, 11.3, 92.6, 14.5],
     "The man in the top hat", "hold", "the pony's bridle", False),
    ("Black top hat", [79.8, 11.5, 81.9, 13.2],
     "The top hat", "sit", "proudly on the man's head", False),
    ("Boy in a green cap and dungarees", [82.2, 15.4, 95.8, 18.6],
     "The boy in the green cap", "stand", "beside the grey pony", False),
    ("Green cap", [82.2, 15.8, 84.0, 17.7],
     "The green cap", "shade", "the boy's eyes", False),
    ("Yellow wellington boots", [92.6, 15.5, 95.8, 18.2],
     "The yellow boots", "sink", "into the soft sand", True),
    ("Grey pony with a saddle blanket", [85.0, 7.8, 100.0, 17.4],
     "The grey pony", "wait", "to be led away", False),
    ("Yellow saddle pad on the grey pony", [88.9, 12.6, 94.9, 15.6],
     "The yellow saddle pad", "sit", "on the pony's back", False),
    ("Palomino horse in the yard", [81.9, 21.2, 94.4, 28.0],
     "The palomino horse", "trot", "across the sandy yard", False),
    ("Blue bridle on the palomino", [83.6, 21.8, 87.0, 24.5],
     "The blue bridle", "fit", "neatly over the horse's nose", False),

    # ---------- r2c1  x22-53 y63.7-100 ----------
    ("Woman riding a brown and white horse", [64.4, 32.1, 81.9, 46.5],
     "The woman on the spotted horse", "ride", "slowly across the yard", False),
    ("Rider in a purple top", [63.7, 36.6, 72.6, 39.7],
     "The rider in the purple top", "hold", "the reins in both hands", False),
    ("Long pale tail of the horse", [66.2, 41.3, 70.3, 46.5],
     "The horse's pale tail", "swish", "from side to side", False),
    ("Woman in a green top walking", [72.0, 41.0, 85.2, 45.2],
     "The woman in the green top", "walk", "across the sandy yard", False),
    ("Girl riding a palomino pony", [75.2, 22.0, 94.4, 35.0],
     "The girl on the palomino", "ride", "past the farmhouse", False),
    ("Rider in a white top", [75.2, 27.3, 88.4, 30.9],
     "The rider in the white top", "sit", "comfortably in the saddle", False),
    ("Blue bridle on the palomino pony", [83.6, 22.0, 87.0, 24.3],
     "The pony's blue bridle", "shine", "against its pale coat", False),
    ("Pony cart with two children", [81.7, 34.9, 94.4, 43.7],
     "The pony cart", "roll", "across the yard", False),
    ("Wheel of the pony cart", [90.1, 35.2, 94.2, 37.8],
     "The cart wheel", "turn", "slowly in the sand", False),
    ("Boy in a red jacket driving the cart", [81.9, 37.9, 92.6, 40.9],
     "The boy in the red jacket", "drive", "the little pony cart", False),
    ("Small girl in the cart", [84.7, 36.2, 90.3, 38.3],
     "The small girl", "sit", "beside her brother in the cart", False),
    ("Dark pony pulling the cart", [88.9, 40.1, 97.2, 50.0],
     "The dark pony", "pull", "the cart across the yard", False),
    ("Blonde mane of the cart pony", [89.4, 46.6, 92.6, 49.2],
     "The pony's blonde mane", "toss", "in the warm air", False),
    ("Green bush by the ring", [79.4, 48.7, 88.8, 53.0],
     "The green bush", "grow", "beside the training ring", False),
    ("Green bushes at the yard edge", [93.3, 27.5, 100.0, 40.0],
     "The bushes", "line", "the edge of the yard", True),

    # ---------- r2c2  x47-78 y63.7-100 ----------
    ("Round training ring", [63.7, 48.4, 97.2, 78.0],
     "The training ring", "curve", "around the sandy circle", False),
    ("Post of the training ring", [68.0, 54.3, 78.7, 55.3],
     "The ring post", "hold", "the white rails steady", False),
    ("Pig running across the ring", [69.2, 63.4, 72.6, 69.3],
     "The pig", "dash", "across the training ring", False),
    ("Chicken flapping over the ring", [66.2, 64.8, 69.6, 67.8],
     "The chicken", "flap", "away over the fence", False),
    ("Rider in a yellow top on a pony", [74.3, 60.8, 81.9, 64.1],
     "The rider in the yellow top", "hold", "on tightly to the reins", False),
    ("Black riding helmet in the ring", [74.3, 61.6, 75.9, 63.3],
     "The black helmet", "keep", "the young rider safe", False),
    ("Palomino pony rearing up", [75.2, 57.7, 88.9, 64.7],
     "The palomino pony", "rear", "up on its back legs", False),
    ("Trainer in a red top", [72.4, 68.5, 85.2, 71.8],
     "The trainer in the red top", "guide", "the pony around the ring", False),
    ("Green cap of the trainer", [72.4, 69.3, 74.0, 70.9],
     "The trainer's cap", "shade", "his eyes from the sun", False),
    ("Long lunge whip", [73.6, 66.0, 86.1, 72.4],
     "The lunge whip", "point", "towards the circling pony", False),
    ("Woman in an orange dress", [75.9, 51.5, 89.1, 55.3],
     "The woman in the orange dress", "watch", "the lesson from the fence", False),
    ("Man in a cowboy hat by the fence", [83.3, 62.6, 97.2, 66.8],
     "The man in the cowboy hat", "lean", "on the white fence", False),
    ("Straw cowboy hat", [83.3, 64.5, 85.4, 66.8],
     "The cowboy hat", "shade", "the man's face", False),
    ("Red neckerchief", [86.3, 64.3, 88.2, 65.8],
     "The red neckerchief", "hang", "around the man's neck", False),
    ("Blue bucket of feed by the ring", [78.2, 74.4, 81.4, 77.2],
     "The blue feed bucket", "stand", "just outside the ring", False),

    # ---------- r2c3  x72-100 y63.7-100 ----------
    ("Rider on a palomino by the fence", [63.7, 72.0, 76.7, 82.0],
     "The rider on the palomino", "trot", "along the white fence", False),
    ("Rider in a green top", [63.7, 75.3, 68.7, 78.0],
     "The rider in the green top", "look", "back over her shoulder", False),
    ("Woman in a white top at the fence", [64.1, 82.8, 77.7, 85.6],
     "The woman at the fence", "open", "the paddock gate", False),
    ("White fence beside the trees", [63.7, 72.0, 72.2, 89.3],
     "The white fence", "run", "along the edge of the wood", False),
    ("Person in yellow by the trees", [63.7, 95.0, 72.6, 97.7],
     "The person in yellow", "walk", "towards the shady trees", False),
    ("Woman in a red top by the trees", [63.7, 97.5, 73.1, 100.0],
     "The woman in the red top", "stand", "at the edge of the wood", False),
    ("Boy riding a spotted pony", [81.5, 72.0, 92.6, 80.1],
     "The boy on the spotted pony", "ride", "towards the training ring", False),
    ("Boy in a green top on the pony", [81.5, 75.6, 90.3, 78.1],
     "The boy in the green top", "grip", "the reins carefully", False),
    ("Spotted grey pony", [83.6, 72.0, 92.6, 81.3],
     "The spotted pony", "walk", "steadily across the sand", False),
    ("Yellow saddle pad on the spotted pony", [87.7, 75.3, 90.3, 77.5],
     "The saddle pad", "cushion", "the pony's back", False),
    ("Boy climbing the fence", [86.6, 80.7, 94.9, 83.2],
     "The climbing boy", "wave", "from the top of the fence", False),
    ("White fence at the wood's edge", [91.0, 74.7, 95.8, 84.4],
     "The low fence", "separate", "the yard from the trees", False),
    ("Big leafy tree by the ring", [69.6, 82.4, 97.2, 100.0],
     "The leafy tree", "shade", "the corner of the yard", False),
    ("Trunk of the leafy tree", [84.5, 91.0, 96.3, 95.5],
     "The tree trunk", "rise", "up out of the bushes", False),
    ("Woodpecker on the tree trunk", [93.8, 92.8, 96.3, 94.3],
     "The woodpecker", "cling", "to the side of the trunk", False),
    ("Red squirrel in the bushes", [95.6, 95.3, 99.1, 97.4],
     "The red squirrel", "peep", "out of the green bushes", False),
]
