# Page 11 - the sports fields and the shopping street: the football pitch, the
# baseball diamond, the basketball court, the row of shops and the busy road.
# Boxes read straight off the tiler grid labels, one block per tile.
P = [

# TILE r0c0
("Green football pitch", [2.8, 0.0, 18.6, 28.0], "The green football pitch", "stretch", "behind the wire fence", False),
("White goal net", [4.9, 0.0, 10.5, 3.2], "The white goal net", "wait", "for the next shot", False),
("Goalkeeper in the white kit", [5.3, 1.2, 10.0, 2.8], "The goalkeeper in the white kit", "guard", "the goal", False),
("Boy in the white shirt", [5.3, 8.0, 10.0, 9.3], "The boy in the white shirt", "run", "onto the pitch", False),
("Boy in the red cap", [6.7, 9.9, 12.1, 10.8], "The boy in the red cap", "dribble", "the ball forward", False),
("Boy in the blue cap", [7.2, 5.2, 12.1, 6.6], "The boy in the blue cap", "wait", "for a pass", False),
("Girl in the red shirt", [12.1, 3.2, 17.7, 5.1], "The girl in the red shirt", "jog", "along the touchline", False),
("Boy watching by the fence", [11.9, 0.8, 18.6, 2.3], "The boy watching by the fence", "watch", "the football match", False),
("Girl in the yellow shirt", [14.0, 12.7, 20.9, 14.7], "The girl in the yellow shirt", "chase", "after the ball", False),
("Boy in the blue shirt", [11.2, 17.1, 16.5, 18.5], "The boy in the blue shirt", "play", "in the middle of the pitch", False),
("Girl with the blonde ponytail", [13.3, 22.1, 19.5, 23.5], "The girl with the blonde ponytail", "stand", "at the edge of the game", False),
("White football", [8.4, 14.8, 9.8, 15.7], "The white football", "bounce", "across the grass", False),
("Floodlight pole", [0.0, 6.5, 6.0, 7.1], "The floodlight pole", "rise", "above the pitch", False),
("Chain link fence", [13.5, 0.0, 24.2, 28.0], "The chain link fence", "separate", "the pitch from the road", False),
("Yellow car", [19.3, 0.6, 28.8, 13.3], "The yellow car", "drive", "along the road", False),
("Driver in the yellow car", [21.9, 6.8, 24.2, 8.5], "The driver in the yellow car", "steer", "past the football pitch", False),
("Passenger waving from the car", [21.9, 3.9, 24.4, 5.4], "The passenger waving from the car", "wave", "out of the window", False),
("Grey road", [25.3, 0.0, 33.5, 28.0], "The grey road", "curve", "through the town", False),
("Sea Food banner", [30.0, 0.0, 36.2, 5.1], "The sea food banner", "hang", "outside the restaurant", False),
("Girl with the pink backpack", [29.8, 14.8, 36.2, 17.3], "The girl with the pink backpack", "walk", "along the pavement", False),
("Boy in the yellow vest", [29.3, 20.8, 36.2, 22.8], "The boy in the yellow vest", "follow", "his troop", False),
("Fire hydrant", [32.1, 10.6, 34.4, 11.6], "The fire hydrant", "stand", "beside the kerb", False),

# TILE r0c1
("White school building", [0.7, 29.3, 5.3, 34.7], "The white school building", "look", "down over the fields", False),
("House with the red roof", [2.6, 40.2, 5.3, 44.2], "The house with the red roof", "sit", "on the far hillside", False),
("Tall conifer trees", [1.2, 30.0, 5.8, 33.1], "The tall conifer trees", "grow", "behind the goal", True),
("Football goal", [7.2, 29.3, 16.3, 33.4], "The football goal", "stand", "at the end of the pitch", False),
("Football in the air", [8.1, 25.2, 10.0, 26.5], "The football in the air", "fly", "towards the goal", False),
("Girl kicking the ball", [8.1, 27.7, 13.5, 29.9], "The girl kicking the ball", "kick", "the ball at the goal", False),
("Baseball diamond", [9.3, 37.4, 15.3, 53.0], "The baseball diamond", "curve", "across the second field", False),
("Pitcher in the blue shirt", [8.1, 40.7, 13.5, 42.4], "The pitcher in the blue shirt", "throw", "the ball to the catcher", False),
("Fielder in the blue cap", [5.1, 43.4, 10.0, 44.8], "The fielder in the blue cap", "wait", "for the ball", False),
("Batter in the red cap", [7.4, 48.9, 12.8, 50.2], "The batter in the red cap", "swing", "at the pitch", False),
("Tall backstop fence", [4.9, 35.0, 21.4, 38.0], "The tall backstop fence", "catch", "the wild balls", False),
("Stadium floodlight", [0.9, 36.2, 5.1, 37.4], "The stadium floodlight", "tower", "over the baseball field", False),
("Man in the blue shirt", [14.4, 37.9, 24.9, 40.2], "The man in the blue shirt", "lean", "on the wire fence", False),
("Boy sitting on the grass", [16.0, 33.7, 21.9, 35.3], "The boy sitting on the grass", "rest", "beside the fence", False),
("Man in the dark suit", [16.3, 45.8, 24.9, 48.4], "The man in the dark suit", "watch", "the baseball game", False),
("Child crouching by the fence", [19.8, 48.9, 24.7, 51.3], "The child crouching by the fence", "peer", "through the wire", False),
("Scout in the red cap", [30.5, 24.3, 36.2, 26.0], "The scout in the red cap", "march", "along the pavement", False),
("Scout in the yellow cap", [29.1, 26.5, 36.2, 28.3], "The scout in the yellow cap", "carry", "his rucksack", False),
("Scout with the brown hair", [29.8, 30.6, 36.2, 32.6], "The scout with the brown hair", "chat", "with her friend", False),
("Scout leader with the map", [27.0, 33.7, 36.2, 39.0], "The scout leader with the map", "lead", "the troop into town", False),
("Folded map", [29.3, 36.8, 33.5, 39.0], "The folded map", "show", "the way to the park", False),
("Palm tree leaves", [28.8, 43.6, 36.2, 51.3], "The palm tree leaves", "spread", "over the pavement", True),

# TILE r0c2
("Yellow apartment block", [0.9, 72.3, 5.8, 87.4], "The yellow apartment block", "stand", "on the hill above the town", False),
("Yellow house with the red roof", [3.0, 61.5, 7.2, 65.2], "The yellow house with the red roof", "overlook", "the baseball field", False),
("Pitcher on the mound", [10.2, 53.2, 16.5, 55.6], "The pitcher on the mound", "wind", "up for the throw", False),
("Pitcher's mound", [15.3, 51.8, 17.2, 56.0], "The pitcher's mound", "sit", "in the middle of the diamond", False),
("Catcher behind the plate", [9.5, 64.4, 15.3, 66.8], "The catcher behind the plate", "crouch", "behind the batter", False),
("Fielder near first base", [7.2, 48.7, 12.8, 50.5], "The fielder near first base", "cover", "first base", False),
("Fielder in the middle of the field", [6.0, 57.5, 12.1, 59.2], "The fielder in the middle of the field", "stand", "out in the sunshine", False),
("Outfielder in the blue cap", [6.7, 68.3, 11.2, 69.5], "The outfielder in the blue cap", "wait", "far out in the field", False),
("Baseball helmet on the grass", [16.3, 52.1, 17.9, 53.9], "The baseball helmet on the grass", "lie", "beside the mound", False),
("Man in the yellow shirt", [10.9, 71.4, 17.2, 73.5], "The man in the yellow shirt", "coach", "the young players", False),
("Girl behind the wire fence", [14.0, 73.9, 18.1, 75.6], "The girl behind the wire fence", "hold", "on to the wire", False),
("Boy in the red shirt", [18.6, 66.0, 23.3, 67.5], "The boy in the red shirt", "queue", "at the gate", False),
("Boy in the yellow shirt", [19.5, 67.4, 23.7, 68.9], "The boy in the yellow shirt", "wait", "behind his friend", False),
("Woman in the pink top", [17.4, 70.0, 20.0, 71.4], "The woman in the pink top", "walk", "towards the field", False),
("Bicycle behind the fence", [19.8, 51.0, 24.2, 54.1], "The bicycle behind the fence", "lean", "against the wire", False),
("Father in the blue shirt", [20.9, 60.3, 31.2, 62.7], "The father in the blue shirt", "hold", "his little boy's hand", False),
("Little boy in the blue shirt", [25.8, 63.0, 30.7, 64.6], "The little boy in the blue shirt", "look", "up at his father", False),
("Gate in the fence", [18.8, 66.4, 29.8, 68.0], "The gate in the fence", "swing", "open to the field", False),
("Red pickup truck", [25.3, 67.7, 36.2, 78.0], "The red pickup truck", "park", "beside the court", False),
("Bushes by the fence", [30.7, 62.1, 36.2, 67.4], "The bushes by the fence", "grow", "along the pavement", True),

# TILE r0c3
("Big trees behind the court", [1.2, 88.0, 6.5, 93.6], "The big trees behind the court", "shade", "the far end of the court", True),
("Basketball hoop", [6.7, 78.6, 12.1, 81.9], "The basketball hoop", "hang", "above the court", False),
("Basketball in the air", [8.1, 82.9, 10.0, 84.2], "The basketball in the air", "sail", "towards the hoop", False),
("Basketball court", [14.9, 78.2, 21.4, 100.0], "The basketball court", "fill", "the corner of the park", False),
("Player in the black top", [12.8, 85.6, 19.5, 87.4], "The player in the black top", "jump", "for the ball", False),
("Player with his arms up", [14.0, 83.4, 19.8, 84.9], "The player with his arms up", "block", "the shot", False),
("Player in the striped top", [14.0, 87.3, 20.0, 88.8], "The player in the striped top", "guard", "his opponent", False),
("Boy in the green top", [14.7, 93.3, 21.4, 95.0], "The boy in the green top", "wait", "at the side of the court", False),
("Boy in the orange top", [12.1, 98.1, 17.2, 99.5], "The boy in the orange top", "stretch", "before the game", False),
("Boy leaning on the fence", [17.4, 96.4, 25.3, 98.4], "The boy leaning on the fence", "rest", "against the wire", False),
("Spectator in the yellow top", [14.9, 74.3, 19.5, 76.0], "The spectator in the yellow top", "cheer", "for the players", False),
("Boy crouching by the court", [18.1, 82.3, 22.8, 84.3], "The boy crouching by the court", "tie", "his shoelace", False),
("Red estate car", [22.3, 72.0, 34.6, 83.4], "The red estate car", "park", "beside the basketball court", False),
("Man with the shopping bag", [22.3, 84.5, 33.5, 87.1], "The man with the shopping bag", "walk", "back to his car", False),
("Green shopping bag", [27.2, 86.0, 29.1, 87.4], "The green shopping bag", "swing", "from the man's hand", False),
("White bag on the ground", [30.0, 82.3, 33.5, 83.7], "The white bag on the ground", "sit", "beside the car", False),
("Person in the wheelchair", [25.3, 87.3, 32.1, 90.5], "The person in the wheelchair", "wait", "near the barbecue", False),
("Golf bag on a trolley", [25.8, 90.2, 30.9, 92.1], "The golf bag on a trolley", "lean", "on its little wheels", False),
("Boy in the striped shirt", [29.3, 92.4, 36.2, 94.5], "The boy in the striped shirt", "hurry", "towards the barbecue", False),
("Pink flowers by the fence", [25.3, 95.5, 28.8, 97.9], "The pink flowers by the fence", "bloom", "along the wire", True),

]
