# Page 24 — farm visit: farmhouse, orchard, barn, animals, market stall,
# school bus, pig pen, sheep shearing, chicken coop, rabbit hutch.
# Boxes read off tiler grid labels, per tile.
# (name, [ymin, xmin, ymax, xmax], subject, bare-infinitive verb, rest, plural)

P = [
    # ---------- r0c0  x0-28 y0-36.3 ----------
    ("Boy playing a handheld game at the window", [1.6, 2.5, 8.0, 8.4],
     "The boy at the window", "play", "a game on his handheld console", False),
    ("Girl blowing bubbles from the window", [1.8, 10.6, 7.5, 15.7],
     "The girl at the window", "blow", "soap bubbles from the window", False),
    ("Two squirrels running along the roof", [10.4, 8.9, 15.0, 20.0],
     "The two squirrels", "scamper", "along the porch roof", True),
    ("Girl riding a white pony", [4.4, 20.6, 12.7, 26.5],
     "The girl on the white pony", "ride", "along the farm track", False),
    ("White pony with a rider", [6.9, 21.5, 13.4, 27.5],
     "The white pony", "trot", "along the sunny path", False),
    ("Person leading the pony on a rope", [7.5, 26.7, 13.9, 28.0],
     "The person leading the pony", "lead", "the pony by its rope", False),
    ("Man carrying a pie onto the porch", [20.3, 0.9, 30.9, 6.7],
     "The man with the pie", "carry", "a fresh pie onto the porch", False),
    ("Fresh pie on a tray", [21.5, 1.9, 25.5, 5.9],
     "The pie", "cool", "on its tray", False),
    ("Grandfather holding a baby", [20.9, 10.9, 30.9, 16.2],
     "The grandfather", "hold", "the baby gently", False),
    ("Baby in the grandfather's arms", [23.1, 12.6, 27.4, 15.9],
     "The baby", "snuggle", "into the grandfather's arms", False),
    ("Grandmother in a purple cardigan", [21.5, 14.5, 31.3, 20.5],
     "The grandmother", "sit", "beside the grandfather", False),
    ("Washing line with towels", [17.9, 20.5, 26.0, 27.6],
     "The washing line", "hold", "towels drying in the breeze", False),
    ("Pink towel on the line", [18.6, 21.3, 23.6, 24.5],
     "The pink towel", "flap", "on the washing line", False),
    ("White towel on the line", [18.6, 24.5, 24.6, 27.3],
     "The white towel", "dry", "in the warm air", False),
    ("Black dog sleeping on the porch", [17.6, 0.0, 27.6, 5.7],
     "The black dog", "sleep", "on the porch step", False),
    ("Red dog bone on the porch", [26.7, 0.9, 28.7, 3.1],
     "The red dog bone", "lie", "beside the sleeping dog", False),
    ("White sheep by the fence", [22.9, 26.5, 30.9, 28.0],
     "The white sheep", "graze", "beside the porch fence", False),
    ("Wooden porch railing", [26.7, 22.7, 34.8, 28.0],
     "The wooden porch railing", "run", "along the edge of the porch", False),

    # ---------- r0c1  x22-53 y0-36.3 ----------
    ("Cows grazing in the far field", [4.4, 24.3, 8.0, 30.4],
     "The distant cows", "graze", "in the far field", True),
    ("Woman feeding a goat treat", [4.4, 25.0, 12.5, 30.4],
     "The rider on the far pony", "lead", "the pony across the field", False),
    ("Girl offering a treat to a goat", [8.0, 27.8, 15.0, 32.6],
     "The girl with the treat", "offer", "a treat to the goat", False),
    ("First apple tree", [1.6, 33.6, 15.5, 42.5],
     "The first apple tree", "grow", "heavy with ripe apples", False),
    ("Second apple tree", [4.4, 41.4, 16.9, 47.9],
     "The second apple tree", "stand", "beside the first tree", False),
    ("Third apple tree", [1.8, 47.6, 17.3, 57.0],
     "The third apple tree", "shade", "the orchard path", False),
    ("Fourth apple tree", [3.5, 55.7, 15.9, 64.6],
     "The fourth apple tree", "hang", "heavy with fruit", False),
    ("Man picking apples on a ladder", [12.0, 35.5, 21.7, 41.4],
     "The man on the ladder", "pick", "apples from the tree", False),
    ("Wooden ladder against the tree", [15.6, 36.9, 26.4, 40.4],
     "The wooden ladder", "lean", "against the apple tree", False),
    ("Man holding a basket of apples", [15.5, 39.0, 26.2, 44.7],
     "The man with the basket", "hold", "a basket of apples", False),
    ("Basket full of apples", [17.6, 41.4, 22.5, 45.4],
     "The basket of apples", "fill", "up with red apples", False),
    ("Beekeeper checking a hive frame", [16.6, 42.4, 27.6, 47.9],
     "The beekeeper", "check", "a frame from the hive", False),
    ("Beekeeper's wide hat and veil", [16.6, 43.5, 20.3, 46.6],
     "The beekeeper's veil", "protect", "her face from the bees", False),
    ("Frame covered in bees", [16.6, 44.5, 20.9, 48.7],
     "The frame of bees", "hum", "with busy activity", False),
    ("Two yellow beehive boxes", [21.7, 46.4, 32.7, 60.1],
     "The two beehive boxes", "sit", "in the orchard grass", True),
    ("Boy reaching up into a tree", [17.3, 62.0, 27.4, 68.9],
     "The boy in the red cap", "reach", "up for an apple", False),
    ("Boy climbing a wooden ladder", [18.6, 65.4, 30.3, 69.9],
     "The climbing boy", "climb", "up the wooden ladder", False),
    ("Sunflowers by the washing line", [26.4, 21.5, 30.9, 25.7],
     "The sunflowers", "bloom", "beside the washing line", True),
    ("White sheep near the flowers", [24.6, 27.6, 30.6, 30.4],
     "The white sheep by the flowers", "chew", "on the grass", False),
    ("Two turkeys near the mailbox", [26.5, 33.4, 32.7, 42.1],
     "The two turkeys", "strut", "across the farmyard grass", True),
    ("Turkey with tail feathers spread", [26.7, 33.6, 32.9, 39.4],
     "The turkey with spread feathers", "puff", "up its tail feathers", False),
    ("Small dark birds in the grass", [28.9, 41.6, 32.2, 45.6],
     "The small dark birds", "peck", "at seeds in the grass", True),

    # ---------- r0c2  x47-78 y0-36.3 ----------
    ("Golden wheat field on the hill", [0.0, 60.6, 4.4, 78.0],
     "The golden wheat field", "wave", "gently in the wind", False),
    ("Green tractor pulling a baler", [4.9, 61.6, 11.7, 75.0],
     "The green tractor", "pull", "a hay baler across the field", False),
    ("Hay baler behind the tractor", [7.5, 68.9, 13.7, 76.0],
     "The hay baler", "roll", "the straw into round bales", False),
    ("Round hay bales in the field", [8.9, 56.6, 15.0, 65.9],
     "The round hay bales", "dot", "the harvested field", True),
    ("More hay bales further along", [8.9, 71.4, 14.6, 80.6],
     "The row of hay bales", "line", "the edge of the field", True),
    ("Wind turbines on the hill", [4.1, 82.3, 12.0, 90.2],
     "The wind turbines", "turn", "slowly on the distant hill", True),
    ("Man picking apples on a ladder", [16.9, 50.5, 26.0, 56.6],
     "The apple picker", "reach", "for the highest apples", False),
    ("Older man with a basket of apples", [21.5, 53.7, 28.3, 60.1],
     "The older man with the basket", "hold", "his basket steady", False),
    ("Boy carrying a green crate", [23.6, 58.5, 32.7, 65.1],
     "The boy with the crate", "carry", "a crate of apples", False),
    ("Green crate full of apples", [23.6, 58.9, 27.6, 63.6],
     "The green crate", "overflow", "with fresh apples", False),
    ("Blue pickup truck loaded with crates", [21.5, 65.4, 33.6, 79.6],
     "The blue pickup truck", "carry", "crates of apples to the barn", False),
    ("Crates of apples in the truck bed", [22.5, 66.4, 26.4, 74.7],
     "The crates of apples", "fill", "the back of the truck", True),
    ("Ramp down from the truck", [25.9, 74.4, 30.6, 79.6],
     "The truck's ramp", "lean", "down to the ground", False),
    ("Man in a green cap by a barrel", [26.4, 70.5, 34.6, 75.7],
     "The man by the barrel", "tip", "apples into a barrel", False),
    ("Wooden barrel of apples", [27.4, 73.9, 33.6, 79.4],
     "The wooden barrel", "fill", "up with apples", False),
    ("Solar panels on the barn roof", [30.6, 55.0, 36.4, 71.5],
     "The solar panels", "gather", "sunlight on the barn roof", True),
    ("Two pigeons on the barn roof", [26.4, 78.5, 30.4, 84.1],
     "The two pigeons", "perch", "on the barn roof", True),
    ("Man reaching towards a rubbish bin", [26.7, 68.5, 34.6, 76.4],
     "The man by the bin", "empty", "scraps into the bin", False),
    ("Metal rubbish bin by the barn", [28.6, 75.7, 33.4, 79.6],
     "The metal rubbish bin", "stand", "beside the barn wall", False),

    # ---------- r0c3  x72-100 y0-36.3 ----------
    ("Cows grazing in the distant field", [11.5, 79.3, 15.2, 87.9],
     "The distant cows", "graze", "in the far field", True),
    ("Round barn window", [12.2, 88.8, 20.9, 96.2],
     "The round barn window", "sit", "above the hayloft door", False),
    ("Dovecote on the barn roof", [3.9, 85.0, 15.5, 96.4],
     "The little dovecote", "perch", "on the ridge of the barn roof", False),
    ("Racoon peering out of the dovecote", [6.4, 87.5, 11.5, 92.4],
     "The racoon", "peer", "out of the dovecote", False),
    ("Second racoon in the dovecote", [6.7, 91.9, 12.0, 96.7],
     "The second racoon", "hide", "inside the little dovecote", False),
    ("Two dark birds on the barn roof", [23.6, 89.8, 29.0, 98.9],
     "The two dark birds", "strut", "along the barn ridge", True),
    ("Boy in the hayloft with hay", [24.6, 84.5, 34.8, 92.4],
     "The boy in the hayloft", "toss", "hay down from the loft", False),
    ("Pulley rope in the hayloft", [21.7, 84.1, 34.6, 87.0],
     "The hayloft pulley rope", "hang", "down from the beam", False),
    ("Orange cat curled in the hay", [28.9, 89.5, 33.4, 94.9],
     "The orange cat in the hay", "curl", "up in the soft hay", False),
    ("Round window above the barn door", [15.0, 46.1, 21.5, 51.9],
     "The round barn window", "sit", "above the big door", False),

    # ---------- r1c0  x0-28 y30.3-69.7 ----------
    ("Woman selling produce at her stall", [39.8, 0.4, 49.6, 8.7],
     "The woman at the market stall", "sell", "fresh produce to visitors", False),
    ("Striped awning over the stall", [34.4, 0.0, 41.2, 10.9],
     "The striped awning", "shade", "the market stall", False),
    ("Baskets of tomatoes on the stall", [43.5, 2.7, 48.4, 7.6],
     "The basket of tomatoes", "sit", "at the front of the stall", False),
    ("Jars of preserves on the stall", [46.4, 3.6, 50.5, 9.4],
     "The jars of preserves", "line", "the market stall", True),
    ("Crate of green vegetables", [50.3, 6.0, 54.7, 11.3],
     "The crate of vegetables", "sit", "beside the stall", False),
    ("Bunch of carrots on the stall", [48.4, 12.3, 54.7, 17.4],
     "The bunch of carrots", "stand", "upright on the stall", False),
    ("Milk churn beside the stall", [42.1, 15.7, 49.4, 20.5],
     "The milk churn", "stand", "beside the market stall", False),
    ("Sunflowers in a vase", [38.1, 0.4, 46.1, 4.7],
     "The sunflowers in the vase", "brighten", "the market stall", True),
    ("Pumpkins on the ground", [51.5, 0.0, 56.6, 6.4],
     "The pumpkins", "sit", "on the ground by the stall", True),
    ("Blue tractor parked nearby", [37.7, 20.0, 47.5, 30.8],
     "The little blue tractor", "wait", "beside the stall", False),
    ("Blue mailbox by the road", [39.8, 33.3, 47.0, 39.7],
     "The blue mailbox", "stand", "beside the farm track", False),
    ("Watering can on the grass", [22.5, 26.0, 26.7, 31.1],
     "The watering can", "sit", "on the grass verge", False),
    ("Milk churn by the flowerbed", [23.4, 32.4, 30.0, 39.8],
     "The second milk churn", "stand", "beside the flowerbed", False),
    ("Yellow school bus", [56.4, 0.0, 92.4, 27.8],
     "The yellow school bus", "wait", "in the farmyard", False),
    ("Boy jumping out of the bus", [69.6, 4.2, 84.0, 15.7],
     "The boy jumping off the bus", "leap", "down from the school bus", False),
    ("Sleeping boy on the bus seat", [69.9, 0.0, 78.0, 8.4],
     "The sleeping boy on the bus", "sleep", "through the whole journey", False),
    ("Boy leaning out of the bus window", [70.1, 21.7, 81.0, 27.5],
     "The boy at the bus window", "lean", "out of the window", False),
    ("Soft toy koala on the bus seat", [72.7, 15.5, 79.9, 20.1],
     "The soft toy koala", "sit", "on the bus seat", False),
    ("Front wheel of the school bus", [79.3, 12.0, 89.6, 19.1],
     "The bus's front wheel", "rest", "on the farmyard ground", False),
    ("Crow perched on the bus roof", [67.3, 1.6, 71.1, 6.2],
     "The crow", "perch", "on the roof of the bus", False),

    # ---------- r1c1  x22-53 y30.3-69.7 ----------
    ("Turkeys near the mailbox", [27.1, 33.6, 33.8, 42.5],
     "The pair of turkeys near the mailbox", "gobble", "as they wander past", True),
    ("Brown and white goat", [30.7, 36.9, 40.7, 46.2],
     "The brown and white goat", "nibble", "at the grass", False),
    ("Girl pushing a wheelbarrow", [33.6, 44.0, 46.4, 51.9],
     "The girl with the wheelbarrow", "push", "a load across the yard", False),
    ("Blue wheelbarrow of hay", [33.6, 43.5, 42.5, 51.5],
     "The blue wheelbarrow", "carry", "a load of straw", False),
    ("Girl running with arms out", [46.1, 32.8, 58.0, 42.5],
     "The running girl", "run", "with her arms spread wide", False),
    ("Girl in a green top walking", [46.4, 36.8, 60.1, 47.5],
     "The girl in the green top", "walk", "towards the pony", False),
    ("Two girls chatting together", [48.9, 44.9, 63.9, 55.4],
     "The two girls", "chat", "together in the farmyard", True),
    ("Girl with glasses talking", [49.6, 45.4, 63.4, 53.5],
     "The girl with glasses", "talk", "to her friend", False),
    ("Brown pony with a saddle", [49.4, 55.7, 63.4, 70.5],
     "The brown pony", "wait", "patiently in the farmyard", False),
    ("Black and white pony", [42.5, 63.4, 63.9, 74.4],
     "The black and white pony", "stand", "beside the brown pony", False),
    ("Woman with a rucksack holding a child's hand", [59.7, 32.4, 70.6, 43.3],
     "The woman with the rucksack", "hold", "the child's hand", False),
    ("Small boy walking with his mother", [59.9, 27.6, 68.9, 34.1],
     "The small boy", "walk", "beside his mother", False),
    ("Girl skipping across the farmyard", [59.9, 40.4, 69.9, 47.9],
     "The skipping girl", "skip", "across the farmyard", False),

    # ---------- r1c2  x47-78 y30.3-69.7 ----------
    ("Alpaca peering out of a barn window", [33.6, 55.7, 43.5, 66.8],
     "The alpaca", "peer", "out of the barn window", False),
    ("Cow standing in the barn doorway", [36.8, 61.8, 47.9, 73.9],
     "The cow in the doorway", "poke", "its head through the door", False),
    ("Cow wearing a straw hat", [36.8, 62.6, 47.9, 74.0],
     "The cow in the straw hat", "chew", "on a mouthful of hay", False),
    ("Woman with a rucksack waving", [37.4, 47.5, 47.9, 55.6],
     "The woman waving", "wave", "at the children arriving", False),
    ("Racoon watching from a barn window", [33.8, 74.7, 40.5, 82.3],
     "The racoon at the window", "watch", "the farmyard below", False),
    ("Small dog kennel by the barn", [43.5, 74.4, 51.7, 84.7],
     "The little dog kennel", "sit", "beside the barn wall", False),
    ("Sleeping dog in the kennel", [45.6, 76.5, 50.6, 82.7],
     "The sleeping dog", "curl", "up inside its kennel", False),
    ("Grey and white pony with a saddle", [39.8, 51.2, 56.4, 68.9],
     "The grey and white pony", "wait", "beside the barn", False),
    ("Puppies playing near the kennel", [58.0, 72.9, 64.1, 80.6],
     "The playful puppies", "tumble", "near the dog kennel", True),
    ("Dachshund dog sitting on the ground", [56.6, 79.6, 65.9, 90.1],
     "The dachshund", "sit", "on the sandy ground", False),
    ("Yellow tennis ball on the ground", [64.6, 81.5, 67.6, 84.5],
     "The tennis ball", "lie", "on the farmyard ground", False),
    ("Girl holding a backpack", [58.4, 43.1, 68.0, 50.5],
     "The girl with the backpack", "carry", "her backpack over one shoulder", False),

    # ---------- r1c3  x72-100 y30.3-69.7 ----------
    ("Man carrying milk churns", [58.4, 76.5, 71.6, 88.4],
     "The man with the milk churns", "carry", "two heavy milk churns", False),
    ("Two metal milk churns", [59.9, 77.6, 69.9, 86.6],
     "The metal milk churns", "clank", "as the man walks", True),
    ("Cows peering through the barn door", [43.5, 84.5, 55.4, 100.0],
     "The cows in the barn doorway", "peer", "out at the visitors", True),
    ("Rooster crowing by the barn", [55.7, 87.5, 65.9, 95.5],
     "The crowing rooster", "crow", "loudly by the barn", False),
    ("Turkey strutting near the barn", [56.6, 96.7, 65.4, 100.0],
     "The strutting turkey", "strut", "near the barn entrance", False),
    ("Wire fence beside the barn", [64.6, 88.4, 74.2, 100.0],
     "The wire fence", "run", "along the side of the barn", False),
    ("Garden fork stuck in the ground", [64.8, 96.4, 74.4, 100.0],
     "The garden fork", "stick", "up out of the ground", False),
    ("Bushes beside the barn wall", [61.5, 92.2, 66.9, 100.0],
     "The bushes", "grow", "against the barn wall", True),

    # ---------- r2c0  x0-28 y63.7-100 ----------
    ("Boy shouting near the bus door", [70.1, 3.9, 78.5, 8.6],
     "The boy near the bus door", "shout", "goodbye to his friends", False),
    ("Snails on the ground near the bus", [78.3, 15.5, 82.7, 21.9],
     "The snails on the ground", "inch", "slowly across the dirt", True),
    ("Boy talking on the phone", [78.9, 20.9, 89.5, 27.6],
     "The boy on the phone", "chat", "on his mobile phone", False),
    ("Girl feeding a pig with a bottle", [83.6, 22.7, 96.1, 31.0],
     "The girl with the bottle", "feed", "a piglet from a bottle", False),
    ("Small pink piglet drinking from a bottle", [85.0, 27.8, 94.0, 34.6],
     "The little piglet", "drink", "milk from the bottle", False),
    ("Metal trough for the pigs", [83.3, 19.6, 100.0, 30.0],
     "The metal feeding trough", "hold", "food for the pigs", False),
    ("Butterflies over the flowers", [79.6, 3.1, 84.7, 8.8],
     "The butterflies", "flutter", "over the flowerbed", True),
    ("Flowers by the bus", [84.7, 0.0, 100.0, 6.7],
     "The bright flowers", "bloom", "beside the school bus", True),
    ("Green bush by the pig pen", [86.6, 6.4, 100.0, 15.9],
     "The green bush", "grow", "beside the pig pen", False),

    # ---------- r2c1  x22-53 y63.7-100 ----------
    ("Children walking together in a line", [69.9, 25.2, 79.4, 40.0],
     "The children walking together", "walk", "in a line towards the farm", True),
    ("Boy holding hands with a girl", [70.6, 25.9, 79.4, 33.1],
     "The boy holding hands", "walk", "hand in hand with his friend", False),
    ("Girl with a purple backpack", [69.6, 33.4, 78.9, 39.8],
     "The girl with the purple backpack", "carry", "her backpack proudly", False),
    ("Man with arms outstretched welcoming visitors", [68.9, 42.5, 83.3, 51.9],
     "The man welcoming visitors", "welcome", "the children to the farm", False),
    ("Small pig sty sign", [79.4, 44.5, 84.5, 51.4],
     "The pig sty sign", "hang", "above the little pen", False),
    ("Muddy pig pen with several pigs", [83.1, 22.7, 100.0, 47.5],
     "The muddy pig pen", "hold", "a whole family of pigs", False),
    ("Mother pig lying in the mud", [83.3, 42.3, 95.6, 51.1],
     "The mother pig", "lie", "in the cool mud", False),
    ("Piglets playing in the mud", [83.6, 24.6, 92.6, 42.3],
     "The piglets", "roll", "playfully in the mud", True),
    ("Chickens on the pig sty roof", [67.5, 41.6, 74.4, 51.5],
     "The chickens on the roof", "peck", "at the barn roof", True),
    ("Sheep grazing near the pen", [92.4, 44.5, 100.0, 51.9],
     "The white sheep by the pen", "graze", "quietly near the pig pen", False),

    # ---------- r2c2  x47-78 y63.7-100 ----------
    ("Boy filling a bucket with soapy water", [63.6, 47.9, 76.5, 58.0],
     "The boy with the bucket", "fill", "a bucket with soapy water", False),
    ("Blue bucket full of suds", [63.4, 51.5, 75.2, 61.8],
     "The bucket of suds", "foam", "with soapy water", False),
    ("Woman shearing a sheep", [63.4, 55.4, 78.0, 71.4],
     "The woman shearing the sheep", "shear", "the wool from the sheep", False),
    ("Sheep being sheared on a mat", [65.9, 55.9, 75.4, 68.3],
     "The sheep on the mat", "lie", "still while it is sheared", False),
    ("Purple mat under the sheep", [69.4, 51.5, 80.6, 65.9],
     "The purple mat", "catch", "the falling wool", False),
    ("Two dogs watching the shearing", [64.6, 71.9, 76.5, 82.8],
     "The two dogs watching", "watch", "the shearing closely", True),
    ("Yellow chicks near the shearing mat", [72.4, 71.9, 76.3, 78.0],
     "The yellow chicks by the mat", "peep", "around the shearing mat", True),
    ("Chicken coop with a ladder", [72.4, 78.0, 90.1, 100.0],
     "The chicken coop", "stand", "on short wooden legs", False),
    ("Ladder up to the chicken coop", [79.6, 79.6, 91.7, 87.9],
     "The coop ladder", "lead", "up to the little door", False),
    ("Two hens looking out of the coop window", [79.4, 90.6, 87.7, 98.4],
     "The two hens", "peer", "out of the coop window", True),
    ("Girl collecting eggs from a nesting box", [83.3, 87.9, 100.0, 100.0],
     "The girl collecting eggs", "collect", "eggs from the nesting box", False),
    ("Nesting box full of eggs", [80.3, 88.9, 90.1, 98.4],
     "The nesting box", "hold", "several white eggs", False),
    ("Basket of eggs on the girl's arm", [90.1, 92.4, 100.0, 98.9],
     "The basket of eggs", "fill", "with fresh eggs", False),

    # ---------- r2c3  x72-100 y63.7-100 ----------
    ("Man walking with milk churns", [66.4, 76.0, 79.4, 90.6],
     "The man carrying churns", "walk", "across the yard with the churns", False),
    ("Cockerel drinking from a trough", [66.9, 84.7, 74.7, 92.4],
     "The cockerel at the trough", "drink", "water from the trough", False),
    ("Grey metal water trough", [69.4, 87.5, 76.5, 96.7],
     "The grey water trough", "hold", "fresh water for the birds", False),
    ("Garden fork leaning nearby", [69.9, 97.0, 77.8, 100.0],
     "The garden fork", "lean", "against the coop", False),
    ("White hen strutting past chicks", [70.1, 87.5, 79.6, 100.0],
     "The white hen", "watch", "over her chicks", False),
    ("Yellow chicks following the hen", [72.4, 90.1, 77.6, 96.4],
     "The chicks following the hen", "follow", "close behind their mother", True),
    ("Two birds on the coop roof", [70.6, 78.9, 76.3, 87.5],
     "The two birds on the roof", "perch", "on the coop's sloping roof", True),
    ("Boy holding a basket of eggs", [86.6, 66.9, 100.0, 74.7],
     "The boy with the basket", "hold", "a basket of fresh eggs", False),
    ("Rabbit hutch with a ramp", [80.6, 84.7, 100.0, 100.0],
     "The rabbit hutch", "stand", "at the edge of the farmyard", False),
    ("Grey rabbit on the ramp", [86.8, 84.4, 95.6, 92.6],
     "The grey rabbit", "hop", "up the wooden ramp", False),
    ("Spotted rabbit on the grass", [88.7, 76.4, 96.7, 86.5],
     "The spotted rabbit", "nibble", "at the grass", False),
    ("Girl holding a net near the rabbits", [82.1, 71.6, 92.4, 82.4],
     "The girl with the net", "hold", "a small net near the hutch", False),
    ("Snails near the rabbit hutch", [96.4, 94.5, 100.0, 100.0],
     "The snails near the hutch", "creep", "slowly across the grass", True),
]
