# Page 22 — nursery playground, craft rooms and vegetable garden.
# Boxes read off tiler grid labels, per tile.
# (name, [ymin, xmin, ymax, xmax], subject, bare-infinitive verb, rest, plural)

P = [
    # ---------- r0c0  x0-28 y0-36.3 ----------
    ("Nursery playhouse with a red roof", [0.4, 0.0, 33.6, 16.9],
     "The nursery playhouse", "stand", "at the edge of the playground", False),
    ("Red pitched roof of the playhouse", [0.4, 0.1, 8.9, 16.9],
     "The red roof", "slope", "down over the playhouse", False),
    ("Orange cat on the roof", [2.7, 7.5, 7.5, 10.3],
     "The orange cat", "creep", "along the top of the roof", False),
    ("Green bush on the roof edge", [6.4, 2.7, 8.2, 5.7],
     "The little bush", "grow", "beside the roof", False),
    ("Washing line of children's paintings", [9.9, 0.0, 15.5, 12.8],
     "The line of paintings", "hang", "across the playhouse window", False),
    ("Painting of a house", [11.5, 1.6, 15.5, 5.2],
     "The painting of a house", "dry", "on the washing line", False),
    ("Painting of a green field", [11.3, 6.5, 15.2, 10.0],
     "The painting of a field", "flutter", "on the line", False),
    ("Painting of a green dragon", [11.3, 10.1, 15.2, 12.8],
     "The dragon painting", "hang", "at the end of the line", False),
    ("Paper rocket decoration", [17.4, 2.8, 20.1, 5.2],
     "The paper rocket", "point", "up towards the ceiling", False),
    ("Red paper heart on the glass", [17.1, 2.8, 19.2, 4.4],
     "The paper heart", "stick", "to the playhouse window", False),
    ("Second red paper heart", [21.3, 3.3, 23.6, 5.0],
     "The second paper heart", "decorate", "the window", False),
    ("Boy in a white shirt at the window", [18.3, 7.0, 29.9, 10.9],
     "The boy at the window", "look", "out at the playground", False),
    ("Pot of paintbrushes", [24.3, 3.1, 28.0, 5.4],
     "The pot of paintbrushes", "sit", "on the craft table", False),
    ("White craft table", [27.4, 0.0, 32.7, 11.1],
     "The craft table", "hold", "the paper and paints", False),
    ("Purple stool by the table", [30.9, 4.2, 34.8, 6.7],
     "The purple stool", "wait", "under the craft table", False),
    ("Second purple stool", [30.9, 7.6, 34.8, 10.3],
     "The second stool", "stand", "beside the first one", False),
    ("Big nursery window", [0.4, 13.8, 33.6, 27.0],
     "The nursery window", "look", "out onto the path", False),
    ("Rainbow sticker on the window", [8.3, 15.0, 12.7, 19.3],
     "The paper rainbow", "arch", "across the glass", False),
    ("Cloud sticker beside the rainbow", [9.0, 19.2, 11.0, 21.7],
     "The paper cloud", "float", "next to the rainbow", False),
    ("Yellow sun sticker", [6.4, 22.3, 10.1, 24.8],
     "The paper sun", "shine", "in the corner of the window", False),
    ("Small sun sticker", [14.1, 16.4, 17.3, 18.6],
     "The little paper sun", "brighten", "the nursery window", False),
    ("Sun sticker on the left", [13.9, 14.3, 16.2, 15.9],
     "The third paper sun", "stick", "to the glass", False),
    ("Lower sun sticker", [25.7, 15.7, 29.0, 17.9],
     "The lowest paper sun", "sit", "near the windowsill", False),
    ("Woman tidying the craft room", [13.2, 20.5, 23.4, 24.2],
     "The nursery teacher", "tidy", "up the craft room", False),
    ("Blue bucket of scraps", [21.5, 21.5, 25.5, 24.2],
     "The blue bucket", "hold", "the paper scraps", False),
    ("Round table covered with paper", [18.8, 15.0, 23.4, 24.2],
     "The round table", "hold", "the children's paper", False),
    ("Roll of paper on the table", [18.5, 16.3, 20.6, 19.3],
     "The roll of paper", "wait", "to be cut up", False),
    ("Globe on a stand", [11.3, 23.2, 15.0, 25.4],
     "The globe", "stand", "in the corner of the room", False),
    ("Wooden chair by the globe", [14.8, 23.4, 18.5, 25.7],
     "The wooden chair", "sit", "beside the globe", False),
    ("Yellow toy crab on the floor", [25.3, 16.4, 29.9, 20.5],
     "The toy crab", "lie", "on the nursery floor", False),

    # ---------- r0c1  x22-53 y0-36.3 ----------
    ("Wooden stool by the globe", [15.3, 23.6, 18.7, 26.0],
     "The little stool", "wait", "for someone to sit down", False),
    ("Second nursery building", [3.9, 29.1, 21.0, 37.2],
     "The second nursery building", "stand", "beside the first one", False),
    ("Red roof of the second building", [3.9, 29.1, 10.1, 37.2],
     "The second red roof", "shelter", "the playroom below", False),
    ("Bunting inside the window", [9.2, 30.4, 10.8, 35.1],
     "The bunting", "stretch", "across the playroom", False),
    ("Wall lamp on the left", [2.5, 28.5, 4.5, 30.4],
     "The wall lamp", "hang", "above the window", False),
    ("Wall lamp on the right", [2.5, 34.4, 4.5, 36.3],
     "The second wall lamp", "light", "the doorway", False),
    ("Table and chairs through the glass", [13.6, 30.7, 19.0, 35.1],
     "The playroom table", "wait", "for the children to come in", False),
    ("Little wooden chair", [14.8, 30.7, 19.0, 32.3],
     "The little chair", "stand", "beside the table", False),
    ("Solar system mobile", [5.5, 37.3, 15.5, 42.5],
     "The solar system mobile", "hang", "in the playroom window", False),
    ("Yellow sun of the mobile", [5.5, 38.4, 8.9, 41.2],
     "The mobile's sun", "hang", "at the top of the mobile", False),
    ("Striped planet on the mobile", [8.3, 40.7, 10.1, 42.3],
     "The striped planet", "dangle", "from a thread", False),
    ("Blue planet on the mobile", [10.4, 39.8, 12.4, 41.4],
     "The blue planet", "turn", "slowly in the air", False),
    ("Ringed planet on the mobile", [12.2, 39.6, 14.1, 41.2],
     "The ringed planet", "hang", "below the others", False),
    ("Orange table in the playroom", [12.9, 37.3, 15.0, 42.5],
     "The orange table", "stand", "under the window", False),
    ("Orange stool", [15.3, 40.1, 17.8, 42.2],
     "The orange stool", "sit", "beside the orange table", False),
    ("Woman holding a big umbrella", [7.1, 42.3, 25.0, 47.7],
     "The woman with the umbrella", "open", "the big umbrella", False),
    ("Large orange and yellow umbrella", [1.3, 39.2, 7.3, 50.2],
     "The big umbrella", "shade", "the doorway", False),
    ("Pole of the umbrella", [6.9, 41.2, 25.0, 43.4],
     "The umbrella pole", "rise", "from its heavy base", False),
    ("Base of the umbrella stand", [23.6, 40.4, 25.5, 43.4],
     "The umbrella base", "hold", "the pole steady", False),
    ("Girl pulling a toy wagon", [20.4, 30.4, 29.9, 33.5],
     "The girl with the wagon", "pull", "her friend along the path", False),
    ("Blue toy wagon", [24.6, 31.8, 33.1, 42.5],
     "The blue wagon", "roll", "along the concrete path", False),
    ("Front wheel of the wagon", [29.7, 32.4, 32.7, 34.3],
     "The wagon's front wheel", "turn", "on the path", False),
    ("Rear wheel of the wagon", [30.6, 35.0, 33.6, 37.2],
     "The wagon's back wheel", "squeak", "as it goes", False),
    ("Child riding in the wagon", [22.2, 33.8, 27.6, 37.5],
     "The child in the wagon", "hold", "on to the sides", False),
    ("Boy in blue shorts walking", [25.7, 42.9, 36.4, 47.7],
     "The boy in the blue shorts", "walk", "across the playground", False),
    ("Girl crouching on the path", [29.5, 25.6, 36.4, 32.0],
     "The crouching girl", "reach", "down towards the ground", False),
    ("Small tree in a planter", [7.1, 48.3, 19.6, 50.6],
     "The little tree", "grow", "in a wooden planter", False),

    # ---------- r0c2  x47-78 y0-36.3 ----------
    ("Shop with a striped awning", [1.3, 49.8, 5.0, 59.1],
     "The little shop", "stand", "across the road", False),
    ("Man in uniform with a newspaper", [3.9, 53.5, 10.1, 58.5],
     "The man in uniform", "read", "his newspaper by the wall", False),
    ("Folded newspaper", [4.3, 57.1, 6.4, 58.8],
     "The newspaper", "flap", "in the man's hand", False),
    ("Man in green on the seesaw", [4.8, 61.7, 15.0, 66.2],
     "The man in the green top", "sit", "on the end of the seesaw", False),
    ("Round building with a red roof", [1.3, 67.4, 8.9, 71.2],
     "The round building", "stand", "at the end of the street", False),
    ("Wooden door of the round building", [4.8, 68.5, 8.9, 70.2],
     "The wooden door", "stay", "shut", False),
    ("Bald man in a suit", [5.5, 71.3, 10.1, 73.9],
     "The man in the suit", "chat", "beside the low wall", False),
    ("Woman with glasses", [5.7, 73.6, 11.7, 75.6],
     "The woman with glasses", "listen", "to her friend", False),
    ("Woman in a headscarf", [6.0, 75.3, 12.0, 77.6],
     "The woman in the headscarf", "stand", "beside the wall", False),
    ("Long wooden seesaw", [11.5, 62.0, 20.1, 78.0],
     "The long seesaw", "tip", "up and down", False),
    ("Pivot post of the seesaw", [16.2, 69.6, 20.1, 71.8],
     "The seesaw post", "hold", "the plank in the middle", False),
    ("Bushes behind the sandbox", [9.9, 55.5, 15.5, 61.6],
     "The bushes", "grow", "behind the sandpit", True),
    ("Large wooden sandbox", [19.9, 47.8, 29.0, 67.5],
     "The wooden sandpit", "fill", "the middle of the lawn", False),
    ("Boy in red playing in the sandpit", [18.3, 51.2, 26.2, 55.1],
     "The boy in the red top", "dig", "in the warm sand", False),
    ("Big sandcastle", [18.3, 55.7, 23.8, 59.1],
     "The sandcastle", "rise", "in the middle of the sandpit", False),
    ("Blue toy car in the sand", [19.9, 59.7, 23.4, 62.7],
     "The toy car", "sit", "in the soft sand", False),
    ("Blue bucket in the sandpit", [20.8, 65.4, 23.6, 67.3],
     "The blue bucket", "wait", "at the edge of the sandpit", False),
    ("Cup in the sand", [24.1, 56.2, 26.4, 57.6],
     "The plastic cup", "lie", "on its side in the sand", False),
    ("Woman in a red waistcoat kneeling", [22.7, 69.0, 33.6, 73.9],
     "The woman in the waistcoat", "kneel", "down beside the child", False),
    ("Small child being helped", [26.2, 63.3, 33.6, 68.1],
     "The small child", "hold", "on to the woman's hand", False),
    ("Red toy on the grass", [29.0, 49.8, 30.8, 52.0],
     "The red toy", "lie", "forgotten on the grass", False),
    ("Snail on the grass", [32.7, 50.3, 34.8, 52.0],
     "The snail", "crawl", "slowly across the lawn", False),

    # ---------- r0c3  x72-100 y0-36.3 ----------
    ("Shop with an orange awning", [1.3, 72.4, 8.9, 84.1],
     "The corner shop", "sit", "on the far side of the road", False),
    ("Big leafy tree", [0.4, 81.8, 29.0, 100.0],
     "The big tree", "shade", "the corner of the playground", False),
    ("Thick trunk of the tree", [15.3, 91.0, 29.0, 97.4],
     "The tree trunk", "rise", "up out of the grass", False),
    ("Hollow knot in the trunk", [20.6, 92.8, 22.9, 94.3],
     "The hollow knot", "hide", "a hole in the trunk", False),
    ("Bird's nest with eggs", [3.9, 86.7, 5.9, 89.5],
     "The bird's nest", "hold", "three small eggs", False),
    ("Grey bird flying to the nest", [2.5, 90.5, 5.2, 94.0],
     "The grey bird", "fly", "back towards its nest", False),
    ("Red squirrel on a branch", [9.9, 89.5, 14.1, 92.4],
     "The red squirrel", "scamper", "along the branch", False),
    ("Yellow kite stuck in the tree", [1.3, 96.2, 7.5, 99.2],
     "The yellow kite", "hang", "caught in the branches", False),
    ("Seesaw with two children", [17.1, 72.0, 22.9, 81.0],
     "The seesaw", "rock", "with two children on it", False),
    ("Boy in yellow on the seesaw", [12.2, 76.5, 21.0, 79.8],
     "The boy in the yellow top", "push", "off with his feet", False),
    ("Girl in purple on the seesaw", [14.1, 79.4, 21.5, 83.0],
     "The girl in the purple top", "ride", "the seesaw down", False),
    ("Boy kicking a football", [19.9, 82.1, 31.3, 88.9],
     "The boy with the ball", "kick", "the football across the grass", False),
    ("Green and white football", [28.8, 81.3, 31.3, 84.1],
     "The football", "roll", "over the lawn", False),
    ("Girl in a red dress by the tree", [24.3, 94.4, 36.4, 99.2],
     "The girl in the red dress", "run", "towards the big tree", False),

    # ---------- r1c0  x0-28 y30.3-69.7 ----------
    ("Toy car on the shelf", [35.3, 2.5, 37.9, 6.0],
     "The toy car", "sit", "on the nursery shelf", False),
    ("Green bush beside the building", [36.7, 0.0, 45.8, 4.3],
     "The green bush", "grow", "against the nursery wall", False),
    ("Man doing carpentry with tools", [36.3, 5.6, 50.0, 12.5],
     "The man with the tools", "mend", "a broken toy", False),
    ("Red screwdriver", [39.8, 10.9, 44.0, 12.5],
     "The screwdriver", "turn", "in the man's hand", False),
    ("Green tool on the ground", [44.5, 8.7, 46.7, 11.5],
     "The green tool", "rest", "on the man's knee", False),
    ("Wooden toolbox", [46.1, 12.3, 51.9, 18.0],
     "The wooden toolbox", "hold", "hammers and saws", False),
    ("Hammer in the toolbox", [46.1, 12.6, 48.2, 15.2],
     "The hammer", "stick", "out of the toolbox", False),
    ("Saw in the toolbox", [46.3, 16.3, 48.6, 18.0],
     "The saw", "lean", "against the side of the box", False),
    ("Boy kneeling with toys", [34.9, 15.7, 44.4, 21.1],
     "The kneeling boy", "sort", "the toys on the path", False),
    ("Pink watering can", [36.5, 21.1, 40.5, 23.6],
     "The pink watering can", "stand", "on the concrete path", False),
    ("Green toy flower", [40.3, 21.7, 42.8, 24.5],
     "The toy flower", "lie", "on the path", False),
    ("Yellow toy sun", [43.5, 21.7, 45.4, 23.3],
     "The toy sun", "sit", "beside the toy flower", False),
    ("Blue bucket with brushes", [38.4, 25.9, 42.1, 28.0],
     "The bucket of brushes", "wait", "at the edge of the path", False),
    ("Red tool on the path", [51.5, 10.4, 54.0, 12.8],
     "The bent red tool", "lie", "on the concrete", False),
    ("Spirit level on the path", [53.6, 10.9, 55.9, 15.2],
     "The spirit level", "rest", "flat on the path", False),
    ("Wooden plank with a wheel", [51.2, 17.4, 53.8, 22.3],
     "The wooden plank", "lie", "beside the toolbox", False),
    ("Girl driving a blue toy car", [52.2, 3.6, 61.2, 7.4],
     "The girl in the blue car", "steer", "along the path", False),
    ("Blue toy car on the path", [58.2, 1.0, 64.1, 10.9],
     "The blue toy car", "roll", "down the path", False),
    ("Front wheel of the blue car", [61.3, 1.6, 64.1, 3.8],
     "The blue car's front wheel", "spin", "on the concrete", False),
    ("Rear wheel of the blue car", [61.3, 7.0, 64.1, 9.2],
     "The blue car's back wheel", "turn", "slowly", False),
    ("Boy on a red ride-on car", [56.8, 15.0, 66.9, 19.3],
     "The boy on the red car", "push", "himself along with his feet", False),
    ("Red ride-on car", [62.4, 13.3, 69.2, 20.5],
     "The red ride-on car", "roll", "along the nursery path", False),
    ("Yellow wheel of the ride-on", [66.7, 16.0, 69.2, 18.0],
     "The yellow wheel", "turn", "under the little car", False),
    ("Bushes at the path edge", [64.8, 0.0, 69.8, 3.5],
     "The bushes", "line", "the edge of the path", True),

    # ---------- r1c1  x22-53 y30.3-69.7 ----------
    ("Glass jar on the path", [37.4, 28.5, 39.7, 30.1],
     "The glass jar", "stand", "on the concrete path", False),
    ("Rope climbing frame", [35.3, 26.5, 61.2, 40.0],
     "The rope climbing frame", "rise", "in the middle of the lawn", False),
    ("Metal cap on the climbing frame", [35.3, 32.4, 37.6, 34.3],
     "The metal cap", "sit", "on top of the frame", False),
    ("Base plate of the climbing frame", [59.4, 31.5, 61.5, 36.0],
     "The base plate", "hold", "the frame in the ground", False),
    ("Central pole of the climbing frame", [36.3, 32.8, 60.3, 34.3],
     "The central pole", "support", "the whole climbing net", False),
    ("Child climbing the rope net", [43.5, 29.0, 50.0, 36.3],
     "The climbing child", "pull", "herself up the ropes", False),
    ("Orange wagon full of balls", [36.7, 37.0, 43.5, 42.3],
     "The orange wagon", "hold", "a load of coloured balls", False),
    ("Coloured balls in the wagon", [36.7, 37.5, 39.5, 41.2],
     "The coloured balls", "fill", "the little wagon", True),
    ("Wheel of the orange wagon", [41.9, 38.7, 43.7, 40.6],
     "The wagon's wheel", "rest", "on the grass", False),
    ("Wooden play tower", [34.6, 45.4, 66.9, 53.0],
     "The wooden play tower", "stand", "in the middle of the playground", False),
    ("Red roof of the play tower", [34.6, 45.5, 40.5, 53.0],
     "The tower's red roof", "shelter", "the platform below", False),
    ("Boy in a purple cap in the tower", [41.6, 46.3, 47.7, 50.0],
     "The boy in the purple cap", "peer", "out of the tower", False),
    ("Pirate flag on the tower", [41.2, 41.6, 45.8, 44.9],
     "The pirate flag", "fly", "from the play tower", False),
    ("Boy on the tower ladder", [49.4, 42.4, 56.6, 45.6],
     "The boy on the ladder", "climb", "up towards the platform", False),
    ("Wooden ladder up the tower", [51.2, 41.6, 66.9, 45.9],
     "The wooden ladder", "lean", "against the play tower", False),
    ("Child in yellow on the ladder", [58.2, 43.5, 66.9, 49.3],
     "The child in the yellow top", "hang", "from the ladder rungs", False),
    ("Girl with a dandelion clock", [64.6, 35.2, 69.8, 40.0],
     "The girl with the dandelion", "blow", "the dandelion seeds away", False),
    ("Dandelion clock", [65.3, 35.2, 67.3, 36.6],
     "The dandelion clock", "scatter", "its seeds on the breeze", False),

    # ---------- r1c2  x47-78 y30.3-69.7 ----------
    ("Boy in a white top on the tower", [40.9, 52.5, 53.8, 57.3],
     "The boy on the platform", "reach", "for the hanging basket", False),
    ("Hanging basket on a pulley", [42.6, 57.5, 45.4, 60.5],
     "The hanging basket", "swing", "from the pulley rope", False),
    ("Pulley rope across the towers", [38.8, 56.2, 40.5, 75.8],
     "The pulley rope", "stretch", "between the two towers", False),
    ("Rope bridge between the towers", [45.6, 56.8, 51.7, 67.5],
     "The rope bridge", "sway", "between the two towers", False),
    ("Second play tower", [40.9, 66.0, 61.2, 78.0],
     "The second play tower", "stand", "at the end of the bridge", False),
    ("Arched windows on the tower", [45.6, 69.1, 48.2, 74.9],
     "The arched windows", "look", "out over the playground", True),
    ("Boy with a telescope", [36.3, 71.3, 42.6, 74.2],
     "The boy with the telescope", "search", "the horizon", False),
    ("Toy telescope", [38.6, 67.9, 40.5, 71.5],
     "The telescope", "point", "across the playground", False),
    ("Flag with a crown", [34.6, 75.4, 38.1, 78.0],
     "The white flag", "flutter", "above the play tower", False),
    ("Yellow slide", [53.1, 53.1, 69.8, 62.5],
     "The yellow slide", "curve", "down from the tower", False),
    ("Girl sliding down the slide", [55.4, 56.2, 66.9, 63.9],
     "The girl on the slide", "whizz", "down to the grass", False),
    ("Child under the play tower", [61.5, 52.8, 66.9, 55.1],
     "The child under the tower", "hide", "in the shady space", False),
    ("Second child under the tower", [65.7, 52.8, 69.8, 54.8],
     "The second child", "crouch", "beside the tower legs", False),
    ("Yellow gourd on the grass", [56.8, 63.4, 62.2, 67.3],
     "The yellow gourd", "sit", "on the grass", False),
    ("Wooden play shop", [48.9, 68.5, 61.2, 78.0],
     "The play shop", "stand", "beside the climbing tower", False),
    ("Red roof of the play shop", [48.9, 68.5, 51.4, 78.0],
     "The play shop's roof", "shade", "the little counter", False),
    ("Basket of goods on the counter", [56.8, 74.7, 58.9, 77.3],
     "The basket of goods", "sit", "on the shop counter", False),
    ("Toy cat on the shop shelf", [52.2, 70.5, 54.7, 71.8],
     "The toy cat", "perch", "on the shop shelf", False),
    ("Girl in dungarees pulling a rope", [62.0, 69.9, 69.8, 74.2],
     "The girl in the dungarees", "tug", "hard on the long rope", False),

    # ---------- r1c3  x72-100 y30.3-69.7 ----------
    ("Bird on the play shop roof", [46.8, 76.5, 49.1, 78.1],
     "The bird", "perch", "on the shop roof", False),
    ("Boy climbing the swing ladder", [36.3, 79.8, 47.0, 84.7],
     "The boy on the swing frame", "climb", "up the metal ladder", False),
    ("Blue swing frame", [32.8, 80.7, 54.9, 100.0],
     "The swing frame", "stand", "at the end of the lawn", False),
    ("Ladder on the swing frame", [38.6, 81.8, 54.7, 85.3],
     "The swing ladder", "lead", "up to the top bar", False),
    ("Girl on a swing", [41.4, 85.1, 54.0, 90.3],
     "The girl on the swing", "swing", "high above the grass", False),
    ("Ropes of the swing", [34.9, 85.9, 47.2, 90.0],
     "The swing ropes", "creak", "as the swing moves", True),
    ("Nest swing", [50.8, 90.7, 58.0, 98.4],
     "The nest swing", "hang", "from the metal frame", False),
    ("Child asleep in the nest swing", [51.9, 92.8, 55.6, 96.7],
     "The sleeping child", "doze", "in the round nest swing", False),
    ("Ropes of the nest swing", [39.3, 93.5, 51.4, 98.0],
     "The nest swing's ropes", "hold", "the seat off the ground", True),
    ("Woman pulling a skipping rope", [59.2, 79.4, 69.8, 85.0],
     "The woman with the rope", "turn", "the long skipping rope", False),
    ("Long skipping rope", [65.7, 72.0, 68.7, 81.3],
     "The skipping rope", "sweep", "across the grass", False),
    ("Tennis racket on the grass", [59.4, 85.6, 62.2, 88.9],
     "The tennis racket", "lie", "on the lawn", False),
    ("Hoops on the grass", [60.1, 84.4, 61.7, 86.0],
     "The hoops", "rest", "on the grass", True),
    ("Bean plant wigwam", [60.3, 91.9, 69.8, 95.5],
     "The bean wigwam", "stand", "in the vegetable garden", False),
    ("Rocks on the grass", [63.4, 96.2, 65.9, 99.2],
     "The rocks", "sit", "at the edge of the garden", True),

    # ---------- r2c0  x0-28 y63.7-100 ----------
    ("Wooden play shed", [69.6, 0.0, 97.2, 19.3],
     "The play shed", "stand", "at the bottom of the garden", False),
    ("Red roof of the play shed", [69.6, 0.0, 76.3, 19.3],
     "The shed roof", "keep", "the rain off the toys", False),
    ("Grey striped cat on the shed", [70.1, 1.6, 77.7, 7.4],
     "The striped cat", "stretch", "out on the shed roof", False),
    ("Man holding a blue toy horse", [77.1, 7.8, 95.4, 14.0],
     "The man in the striped top", "carry", "a big toy horse", False),
    ("Large blue toy horse", [81.9, 8.7, 91.2, 16.9],
     "The blue toy horse", "sit", "in the man's arms", False),
    ("Shed window with tools", [80.1, 0.0, 91.2, 6.0],
     "The shed window", "show", "the tools inside", False),
    ("Skipping ropes on the wall", [80.8, 1.9, 84.7, 5.0],
     "The skipping ropes", "hang", "on the shed wall", True),
    ("Toy rabbit on the shelf", [88.0, 3.3, 91.2, 5.5],
     "The toy rabbit", "sit", "on the shed shelf", False),
    ("Hanging basket of plants", [76.8, 16.6, 82.6, 20.3],
     "The hanging basket", "dangle", "beside the shed door", False),
    ("Purple spade by the shed", [86.3, 17.2, 93.5, 18.8],
     "The purple spade", "lean", "against the shed", False),
    ("Man pushing a wheelchair", [63.6, 22.0, 75.4, 27.3],
     "The man with the wheelchair", "push", "his friend along the path", False),
    ("Wheel of the wheelchair", [70.8, 26.3, 76.1, 28.0],
     "The wheelchair's wheel", "roll", "smoothly along the path", False),
    ("Boy in an orange striped top", [83.3, 20.5, 97.2, 24.8],
     "The boy in the orange top", "reach", "out towards the toy horse", False),
    ("Butterfly on the grass", [84.0, 25.4, 85.8, 27.3],
     "The butterfly", "flutter", "over the lawn", False),
    ("Toy cow on wheels", [92.2, 26.0, 97.2, 28.0],
     "The toy cow", "stand", "on the path", False),
    ("Bushes behind the shed", [70.8, 8.7, 76.1, 15.2],
     "The bushes", "grow", "behind the play shed", True),

    # ---------- r2c1  x22-53 y63.7-100 ----------
    ("Child in a wheelchair", [65.2, 27.8, 77.3, 34.1],
     "The child in the wheelchair", "ride", "along the nursery path", False),
    ("Big wheel of the wheelchair", [70.3, 27.0, 76.8, 30.1],
     "The big wheel", "turn", "along the path", False),
    ("Dandelion clocks in the grass", [70.6, 38.3, 73.1, 42.2],
     "The dandelion clocks", "stand", "tall in the grass", True),
    ("Boy pushing a wheelbarrow", [72.9, 45.4, 86.5, 49.3],
     "The boy with the wheelbarrow", "push", "the pumpkins along the path", False),
    ("Green wheelbarrow of pumpkins", [78.9, 37.9, 85.4, 44.9],
     "The green wheelbarrow", "carry", "a load of orange pumpkins", False),
    ("Pumpkins in the wheelbarrow", [78.0, 38.3, 81.4, 43.4],
     "The pumpkins", "fill", "the wheelbarrow", True),
    ("Wheel of the wheelbarrow", [83.6, 38.3, 85.4, 40.0],
     "The wheelbarrow's wheel", "squeak", "along the path", False),
    ("Girl pushing a toy cow", [85.0, 27.0, 97.2, 31.4],
     "The girl with the toy cow", "push", "her toy along the path", False),
    ("Butterfly over the lawn", [89.1, 47.0, 90.7, 48.5],
     "The second butterfly", "dance", "over the grass", False),
    ("Pink flowers in the grass", [91.5, 35.8, 93.5, 38.1],
     "The pink flowers", "bloom", "beside the path", True),
    ("Bush by the path", [91.0, 46.6, 97.2, 50.8],
     "The bush", "grow", "beside the winding path", False),

    # ---------- r2c2  x47-78 y63.7-100 ----------
    ("Garden hose on the grass", [72.7, 49.8, 76.0, 57.0],
     "The garden hose", "curl", "across the lawn", False),
    ("Boy working the water pump", [80.8, 52.0, 94.4, 57.0],
     "The boy at the pump", "work", "the handle up and down", False),
    ("Green water pump", [81.5, 56.5, 89.1, 60.1],
     "The water pump", "stand", "beside the wooden trough", False),
    ("Woman filling a watering can", [80.3, 60.9, 89.1, 66.1],
     "The woman at the trough", "fill", "the watering can", False),
    ("Red spotted watering can", [85.6, 59.5, 89.6, 62.5],
     "The spotted watering can", "sit", "under the pump", False),
    ("Wooden water trough on wheels", [86.6, 57.4, 94.0, 69.9],
     "The wooden trough", "hold", "the water from the pump", False),
    ("Wheel of the water trough", [91.9, 60.6, 94.2, 62.7],
     "The trough's wooden wheel", "rest", "on the path", False),
    ("Water in the trough", [88.0, 61.1, 89.8, 68.7],
     "The water", "shine", "in the wooden trough", False),
    ("Orange bucket on the path", [92.6, 65.4, 96.3, 68.4],
     "The orange bucket", "stand", "on the wet path", False),
    ("Puddle on the path", [95.8, 61.6, 97.7, 64.4],
     "The puddle", "spread", "across the concrete", False),
    ("Stream through the garden", [88.2, 71.3, 100.0, 78.0],
     "The little stream", "wind", "through the garden", False),
    ("Green frog by the stream", [94.5, 70.5, 96.8, 73.5],
     "The green frog", "sit", "beside the stream", False),
    ("Stepping stones in the stream", [88.9, 71.6, 91.6, 76.7],
     "The stepping stones", "cross", "the shallow stream", True),
    ("Bush beside the path", [91.0, 47.8, 95.4, 51.1],
     "The green bush", "grow", "beside the path", False),
    ("Rocks on the path", [94.9, 51.8, 97.2, 55.1],
     "The rocks", "edge", "the concrete path", True),

    # ---------- r2c3  x72-100 y63.7-100 ----------
    ("Girl carrying a watering can", [76.4, 74.7, 89.1, 80.1],
     "The girl with the watering can", "carry", "water to the vegetables", False),
    ("Boy pulling up a carrot", [73.1, 82.7, 86.5, 88.1],
     "The boy in the yellow top", "pull", "a carrot out of the soil", False),
    ("Orange carrot", [74.3, 86.7, 79.8, 88.7],
     "The carrot", "come", "up out of the earth", False),
    ("Raised vegetable bed", [80.1, 85.8, 87.5, 100.0],
     "The raised bed", "hold", "rows of vegetables", False),
    ("Cabbage in the vegetable bed", [80.8, 91.0, 82.8, 93.3],
     "The cabbage", "grow", "in the raised bed", False),
    ("Cucumbers in the bed", [81.7, 95.9, 83.8, 98.6],
     "The cucumbers", "lie", "along the soil", True),
    ("Strawberries in the bed", [83.1, 91.6, 84.5, 93.7],
     "The strawberries", "ripen", "in the sunshine", True),
    ("Tomato plant with red fruit", [72.2, 96.5, 81.9, 100.0],
     "The tomato plant", "hang", "heavy with red tomatoes", False),
    ("Yellow peppers on the vine", [77.5, 90.1, 79.8, 92.4],
     "The yellow peppers", "dangle", "from the climbing vine", True),
    ("Boy launching a paper boat", [90.1, 84.5, 98.1, 89.7],
     "The boy by the water", "launch", "a paper boat", False),
    ("Paper boat on the water", [94.5, 80.4, 97.2, 84.1],
     "The paper boat", "float", "down the little stream", False),
    ("Second paper boat with a mast", [91.5, 81.8, 94.9, 84.1],
     "The second paper boat", "sail", "along the water", False),
    ("Stepping stones across the stream", [92.2, 73.6, 95.8, 78.7],
     "The flat stones", "cross", "the running water", True),
    ("Stepping stones on the path", [87.5, 72.8, 89.8, 83.2],
     "The round stones", "lead", "towards the vegetable garden", True),
    ("Snail on the path", [88.2, 83.9, 89.8, 85.0],
     "The little snail", "inch", "across the stones", False),
    ("Potatoes on the soil", [91.5, 90.4, 94.0, 94.3],
     "The potatoes", "lie", "on the dark soil", True),
    ("Garden trowel", [91.0, 95.0, 95.4, 96.7],
     "The garden trowel", "stick", "into the earth", False),
    ("Leafy plants in the garden", [86.3, 92.2, 90.7, 96.1],
     "The leafy plants", "spread", "across the vegetable patch", True),
]
