# Page 19 - the night harvest party at Wimmelfarm: string lights between the
# red barn and the blue farmhouse, the long dinner table, the pond with the
# turkey and the fisherman, the ox-drawn hay wagon at the gate, the lantern
# walk on the lawn, the night garden with the flashlight and the fox, the
# chicken coop and the cow paddock.
# Boxes read straight off the tiler grid labels, one block per tile.
P = [

# TILE r0c0 - the night sky, the silos, the barn roof and the hayloft
("Starry night sky", [0.0, 28.0, 5.5, 62.0], "The starry night sky", "stretch", "over the whole farm", False),
("Green hill behind the barn", [1.0, 2.0, 9.0, 24.0], "The green hill", "rise", "behind the grain silos", False),
("Solar panels on the roof", [6.0, 0.5, 13.5, 10.9], "The solar panels", "rest", "on the blue barn roof", True),
("Blue barn roof", [2.0, 0.0, 31.5, 12.8], "The blue barn roof", "slope", "down toward the trees", False),
("Grain silo on the left", [2.5, 10.2, 13.6, 16.2], "The grain silo on the left", "shine", "in the moonlight", False),
("Grain silo on the right", [2.5, 19.8, 15.4, 25.9], "The grain silo on the right", "stand", "beside the red barn", False),
("Red barn", [10.5, 2.5, 49.5, 27.6], "The big red barn", "glow", "under the party lights", False),
("Hayloft windows", [21.5, 10.3, 25.8, 14.0], "The hayloft windows", "reflect", "the night sky", True),
("Pictures on the barn wall", [19.9, 13.6, 23.9, 19.5], "The pictures on the barn wall", "hang", "in a neat row", True),
("Open window shutter", [19.3, 19.1, 22.7, 22.1], "The open window shutter", "swing", "on its hinges", False),
("Bushes by the barn", [20.0, 0.0, 49.0, 2.8], "The leafy bushes", "grow", "along the barn wall", True),
("String of party lights", [25.5, 8.0, 33.0, 48.5], "The string of party lights", "twinkle", "between the barn and the house", False),
("Star lantern by the barn", [29.8, 16.3, 34.2, 18.9], "The star lantern by the barn", "glow", "above the doorway", False),
("Boy hanging the party lights", [26.3, 8.5, 38.3, 13.2], "The boy on the platform", "hang", "the party lights on the barn", False),

# TILE r0c1 - the blue farmhouse, the skylight, the windows and the porch roof
("Blue farmhouse", [3.0, 22.0, 38.0, 52.6], "The blue farmhouse", "stand", "in the middle of the farm", False),
("Red roof of the farmhouse", [2.8, 21.6, 17.8, 52.6], "The red roof", "cover", "the blue farmhouse", False),
("Skylight window", [2.8, 39.8, 10.0, 43.4], "The skylight window", "open", "onto the night sky", False),
("Father at the skylight", [3.2, 40.4, 7.1, 42.2], "The father at the skylight", "watch", "the stars with his child", False),
("Child at the skylight", [6.9, 41.3, 9.4, 42.8], "The child at the skylight", "point", "at the full moon", False),
("Owl on the chimney", [4.3, 47.2, 8.2, 49.3], "The brown owl", "perch", "on the chimney", False),
("White chimney", [5.5, 49.1, 10.1, 51.7], "The white chimney", "stick", "up from the red roof", False),
("Upstairs window on the left", [17.6, 27.8, 24.3, 33.2], "The upstairs window on the left", "let", "in the evening air", False),
("Man waving from the window", [18.0, 29.5, 23.4, 31.7], "The man in the red shirt", "wave", "from the upstairs window", False),
("Woman leaning out of the window", [19.2, 37.2, 25.0, 39.5], "The woman in the yellow shirt", "lean", "out of the middle window", False),
("Upstairs window with blue panes", [15.5, 42.4, 21.5, 44.9], "The window with blue panes", "sit", "under the red roof", False),
("Red curtain blowing in the wind", [15.7, 48.3, 21.5, 50.8], "The red curtain", "blow", "in the night breeze", False),
("Porch roof", [22.2, 42.3, 27.2, 50.9], "The little porch roof", "shelter", "the front steps", False),
("White porch columns", [30.3, 44.9, 38.3, 47.8], "The white porch columns", "hold", "up the porch roof", True),
("Fir tree by the house", [21.8, 25.9, 40.0, 29.2], "The dark fir tree", "grow", "beside the farmhouse", False),
("Star lantern by the fir tree", [27.0, 25.0, 31.0, 27.2], "The star lantern by the fir tree", "shine", "on the dark branches", False),
("Star lantern over the lawn", [26.5, 35.7, 30.7, 38.1], "The star lantern over the lawn", "hang", "from the long wire", False),
("Star lantern by the porch", [27.9, 43.2, 32.1, 45.6], "The star lantern by the porch", "light", "up the front steps", False),
("Man carrying a crate", [28.8, 47.4, 39.7, 50.6], "The man with the crate", "carry", "supplies to the party", False),

# TILE r0c2 - the pond, the fisherman, the turkey, the horse and the tractor
("Tall green tree by the house", [1.3, 52.1, 18.7, 60.7], "The tall green tree", "tower", "over the farmhouse", False),
("Front porch", [16.4, 50.5, 32.0, 60.3], "The front porch", "wrap", "around the corner of the house", False),
("Woman reading on the porch", [21.8, 53.1, 28.9, 55.5], "The woman on the porch", "read", "a story out loud", False),
("Child listening on the porch", [21.4, 55.3, 26.1, 57.3], "The child on the porch", "listen", "to the bedtime story", False),
("Glowing star lantern", [30.2, 58.0, 36.3, 61.0], "The big glowing star lantern", "sparkle", "over the garden path", False),
("Purple paper lantern", [29.8, 51.6, 34.0, 54.1], "The purple paper lantern", "dangle", "from the string of lights", False),
("Pink paper lantern", [30.2, 54.7, 34.4, 57.2], "The pink paper lantern", "sway", "on the light string", False),
("Full moon", [2.6, 65.5, 7.5, 69.6], "The full moon", "shine", "over the fields", False),
("Long white cloud", [0.7, 60.0, 4.3, 75.4], "The long white cloud", "drift", "across the night sky", False),
("Rolling hills in the distance", [4.0, 72.0, 11.5, 84.0], "The rolling hills", "roll", "away into the dark", True),
("Plowed field", [9.8, 61.5, 14.2, 71.3], "The plowed field", "wait", "for the spring seeds", False),
("Brown horse", [9.0, 65.8, 13.6, 69.6], "The brown horse", "stand", "at the edge of the field", False),
("Cowboy on the horse", [7.8, 66.5, 11.1, 68.2], "The cowboy", "ride", "across the dark field", False),
("Country road", [8.0, 62.0, 22.0, 100.0], "The country road", "wind", "past the farm gate", False),
("Red tractor", [12.2, 68.5, 23.4, 78.3], "The big red tractor", "roll", "down toward the pond", False),
("Farmer driving the tractor", [15.2, 71.6, 18.5, 73.9], "The farmer in the cab", "drive", "the big red tractor", False),
("Pond", [21.5, 63.5, 33.5, 78.5], "The quiet pond", "glitter", "in the moonlight", False),
("Yellow bench", [18.7, 59.9, 22.4, 64.4], "The yellow bench", "face", "the quiet pond", False),
("Fisherman on the bench", [19.9, 59.7, 25.2, 62.2], "The fisherman on the bench", "fish", "in the pond at night", False),
("Fish on the line", [22.7, 65.1, 26.1, 66.4], "The little fish", "dangle", "from the fishing line", False),
("Turkey fanning its tail", [22.3, 63.0, 29.4, 66.9], "The big turkey", "fan", "out its dark tail feathers", False),
("Girl feeding the turkey", [25.7, 61.7, 34.5, 64.4], "The girl in the blue dress", "feed", "the hungry turkey", False),
("Picnic basket", [25.9, 60.2, 28.0, 61.6], "The picnic basket", "sit", "on the grass by the bench", False),
("Boy in the green cap", [25.6, 65.1, 35.3, 67.8], "The boy in the green cap", "hold", "out food for the turkey", False),
("Kid in the yellow shorts", [26.4, 68.0, 35.0, 69.9], "The kid in the yellow shorts", "watch", "the turkey show off", False),
("Woman in the green top", [25.5, 69.9, 35.0, 71.8], "The woman in the green top", "laugh", "at the proud turkey", False),
("Man in the green shirt by the pond", [26.4, 72.5, 35.0, 74.9], "The man in the green shirt", "greet", "the family at the car", False),
("Diving board over the pond", [21.5, 73.0, 24.2, 78.6], "The wooden diving board", "stick", "out over the pond", False),
("Yellow duck at the pond", [21.5, 76.6, 24.3, 78.7], "The yellow duck", "waddle", "along the pond bank", False),

# TILE r0c3 - the road, the police car, the old tractor, the bus and the yellow car
("Little red barn on the hill", [3.0, 83.5, 9.9, 90.2], "The little red barn", "sit", "on the far hill", False),
("White cottage on the hill", [5.5, 90.5, 9.4, 94.8], "The white cottage", "nestle", "against the hillside", False),
("Yellow school bus", [2.5, 94.3, 12.2, 100.0], "The yellow bus", "arrive", "at the farm for the party", False),
("Man waving at the bus", [6.9, 92.3, 14.5, 94.5], "The man on the road", "wave", "both arms at the bus", False),
("Police car", [9.9, 76.7, 14.8, 84.7], "The police car", "flash", "its red light on the road", False),
("Old tractor on the road", [8.7, 85.1, 16.1, 92.7], "The old tractor", "chug", "down the country road", False),
("Old farmer on the tractor", [8.7, 86.6, 12.2, 88.7], "The old farmer", "steer", "his rusty tractor", False),
("Police officer with the flashlight", [14.6, 81.6, 21.5, 83.8], "The police officer", "direct", "the party traffic", False),
("Pile of grey rocks", [22.0, 79.0, 24.3, 84.1], "The pile of grey rocks", "lie", "beside the pond", False),
("Yellow car with the open trunk", [25.0, 74.5, 36.0, 86.3], "The yellow car", "park", "by the pond with its trunk open", False),
("Man unloading the car", [25.2, 72.0, 36.4, 75.2], "The man at the car", "unload", "bags from the trunk", False),
("Wooden pavilion", [18.5, 85.5, 38.0, 100.0], "The wooden pavilion", "shelter", "the corner of the yard", False),

# TILE r1c0 - the forklift, the campfire, the welcome sign and the gate
("Blue forklift", [32.5, 10.0, 49.6, 20.5], "The blue forklift", "lift", "the boy up to the lights", False),
("Woman driving the forklift", [35.8, 14.8, 44.4, 18.1], "The woman in the forklift", "hold", "the platform steady", False),
("Wooden pallet platform", [37.4, 7.3, 41.0, 14.4], "The wooden pallet", "balance", "on the forklift forks", False),
("Man in the white shirt", [41.4, 19.7, 52.4, 23.3], "The man in the white shirt", "chat", "with the woman in yellow", False),
("Woman in the yellow shirt", [41.0, 24.2, 51.9, 27.5], "The woman in the yellow shirt", "shake", "hands with her neighbour", False),
("Campfire", [53.0, 6.0, 59.5, 10.5], "The little campfire", "crackle", "inside its ring of stones", False),
("Girl with the ponytail by the fire", [46.6, 4.9, 52.4, 7.3], "The girl with the ponytail", "warm", "her hands at the fire", False),
("Boy roasting a marshmallow", [47.5, 7.5, 55.2, 10.2], "The boy on the stump", "roast", "a marshmallow over the fire", False),
("Girl carrying the basket", [50.1, 2.2, 57.0, 5.0], "The girl with the basket", "bring", "snacks to the campfire", False),
("Toddler in the red shorts", [49.8, 5.2, 54.7, 7.6], "The toddler in the red shorts", "toddle", "toward the campfire", False),
("Boy crouching by the campfire", [53.6, 4.9, 58.5, 8.3], "The boy by the fire", "poke", "at the glowing logs", False),
("Welcome sign", [51.4, 14.5, 61.8, 22.8], "The wooden welcome sign", "welcome", "everyone to Wimmelfarm", False),
("Steer horns on the sign", [50.5, 16.5, 53.5, 21.4], "The steer horns", "sit", "on top of the welcome sign", True),
("White fence by the gate", [55.0, 0.0, 69.9, 6.6], "The white fence", "run", "along the farm lane", False),
("Red wagon", [51.0, 22.8, 58.0, 27.7], "The little red wagon", "wait", "by the farm gate", False),
("Girl lying in the red wagon", [51.4, 23.4, 55.6, 27.1], "The girl in the wagon", "rest", "after the long day", False),

# TILE r1c1 - the swing set, the sandbox, the drinks table and the golf cart
("Swing set", [33.3, 25.5, 51.0, 38.5], "The blue swing set", "stand", "on the party lawn", False),
("Girl on the swing", [41.9, 30.4, 47.7, 33.5], "The girl on the swing", "swing", "high over the grass", False),
("Woman on the stepladder", [30.2, 35.1, 39.7, 38.9], "The woman on the stepladder", "fix", "the top of the swing set", False),
("Stepladder", [35.0, 34.2, 42.1, 38.8], "The wooden stepladder", "lean", "against the swing frame", False),
("Toddler climbing the ladder", [39.4, 33.9, 43.5, 36.3], "The toddler in purple", "climb", "the bottom rungs", False),
("Sandbox", [35.1, 39.2, 43.5, 46.2], "The wooden sandbox", "hold", "a mountain of sand", False),
("Sandcastle", [35.8, 40.0, 40.2, 42.5], "The sandcastle", "rise", "out of the sandbox", False),
("Toddler in the sandbox", [37.0, 42.1, 40.9, 44.0], "The toddler in the sandbox", "build", "a tall sandcastle", False),
("Radio on the table", [42.1, 44.0, 44.2, 46.5], "The silver radio", "play", "country music for the party", False),
("Cooler full of ice", [45.4, 39.5, 48.9, 42.3], "The blue cooler", "keep", "the drinks cold", False),
("Drinks table", [48.4, 40.9, 54.7, 46.2], "The drinks table", "stand", "between the sandbox and the grill", False),
("Woman serving drinks", [44.2, 41.7, 49.1, 44.2], "The woman behind the table", "serve", "cold drinks to the guests", False),
("Man in the blue jacket", [46.8, 43.5, 55.6, 45.9], "The man in the blue jacket", "reach", "for a cold drink", False),
("Green bottles", [45.1, 45.7, 48.6, 46.8], "The green bottles", "stand", "in a row on the table", True),
("Barbecue grill", [41.6, 48.0, 50.0, 52.3], "The barbecue grill", "sizzle", "with burgers and corn", False),
("Man grilling burgers", [38.6, 47.3, 45.9, 50.6], "The man in the white apron", "grill", "burgers for everyone", False),
("White golf cart", [49.8, 30.2, 66.5, 42.0], "The white golf cart", "carry", "guests around the farm", False),
("Red-haired woman in the golf cart", [51.9, 35.0, 63.1, 39.4], "The red-haired woman", "wave", "from the golf cart", False),
("Farmer in overalls waving", [55.0, 41.6, 67.0, 45.6], "The farmer in overalls", "welcome", "the guests to the party", False),
("Man in the cowboy hat", [48.9, 46.3, 62.2, 49.3], "The man in the cowboy hat", "carry", "a plate to the long table", False),
("Heart-shaped balloon", [64.2, 24.8, 68.7, 28.3], "The heart-shaped balloon", "float", "above the hay wagon", False),

# TILE r1c2 - the long dinner table, the doghouse and the stable roof
("Long dinner table", [42.5, 48.5, 58.5, 67.5], "The long dinner table", "stretch", "across the farmyard", False),
("Wooden bench at the table", [52.2, 53.0, 59.8, 64.1], "The wooden bench", "seat", "half the hungry guests", False),
("Candles on the table", [46.5, 58.3, 49.1, 59.5], "The candles", "flicker", "on the white tablecloth", True),
("Man in blue overalls at the table", [48.0, 56.5, 54.7, 59.4], "The man in blue overalls", "eat", "an ice cream cone", False),
("Man in the brown waistcoat", [44.2, 61.4, 51.4, 64.4], "The man in the brown waistcoat", "talk", "over his shoulder", False),
("Little boy by the table", [50.1, 53.4, 58.0, 55.6], "The little boy by the bench", "ask", "for another helping", False),
("Toddler at the table", [45.6, 53.1, 48.6, 55.1], "The toddler at the table", "bang", "a spoon on the plate", False),
("Man in the maroon shirt", [45.1, 50.4, 51.4, 53.3], "The man in the maroon shirt", "sit", "at the end of the bench", False),
("Grandfather carrying two mugs", [37.9, 52.8, 45.8, 55.3], "The grandfather", "carry", "two mugs of hot cider", False),
("Man in red overalls", [37.0, 55.4, 46.3, 57.7], "The man in red overalls", "stand", "behind the long table", False),
("Woman in the green cardigan", [40.0, 59.2, 44.0, 61.0], "The woman in the green cardigan", "chat", "with the grandmother", False),
("Grandmother with the white hair", [39.8, 60.8, 43.5, 62.8], "The grandmother with white hair", "smile", "at the dinner guests", False),
("Woman in the purple sweater", [36.3, 63.3, 42.5, 65.6], "The woman in the purple sweater", "tell", "a funny story", False),
("Man in the denim jacket", [36.0, 65.7, 42.5, 68.4], "The man in the denim jacket", "listen", "to the funny story", False),
("Black-haired man at the table end", [36.3, 69.7, 43.5, 72.1], "The black-haired man", "pour", "juice at the table end", False),
("Grandmother in the yellow blouse", [42.0, 68.2, 48.6, 71.2], "The grandmother in yellow", "raise", "her cup for a toast", False),
("Child at the end of the table", [42.3, 71.0, 47.0, 73.0], "The child at the table end", "wait", "for the food to come", False),
("Man passing a plate", [43.3, 66.0, 52.4, 68.7], "The balding man", "pass", "a plate down the table", False),
("Row of little fir trees", [44.2, 68.0, 56.6, 71.0], "The little fir trees", "line", "the path to the stable", True),
("Red-roofed doghouse", [53.3, 60.8, 63.1, 67.2], "The red-roofed doghouse", "stand", "empty on the grass", False),
("Children stargazing on the grass", [57.5, 57.0, 63.2, 62.5], "The two children", "gaze", "up at the stars", True),
("Grey rock by the doghouse", [56.8, 55.5, 60.8, 59.1], "The grey rock", "make", "a fine backrest", False),
("Red dog bowl", [62.9, 62.5, 64.5, 64.4], "The red dog bowl", "sit", "beside the doghouse", False),
("Dog bone", [64.1, 60.9, 65.8, 62.0], "The white dog bone", "lie", "forgotten on the grass", False),
("Shingled roof of the stable", [43.5, 68.5, 66.5, 96.0], "The shingled stable roof", "slope", "down toward the paddock", False),
("American flag on the roof", [55.2, 80.2, 63.6, 86.8], "The American flag", "fly", "from the stable roof", False),
("Kite stuck on the roof", [51.0, 74.5, 54.0, 77.5], "The blue kite", "sit", "stuck on the shingles", False),
("Grandmother in the rocking chair", [64.8, 66.9, 73.4, 71.5], "The grandmother in the rocking chair", "doze", "under a yellow blanket", False),

# TILE r1c3 - the lantern walk on the lawn, the canoe and the ladder
("Woman in the purple top", [31.7, 74.4, 44.0, 77.5], "The woman in the purple top", "bring", "a plate of food to the table", False),
("Man in the teal shirt", [32.1, 77.9, 42.1, 80.7], "The man in the teal shirt", "chat", "by the yellow car", False),
("Boy marching with a lantern", [38.2, 82.0, 43.5, 84.7], "The boy in the orange trousers", "march", "across the lawn with his lantern", False),
("Girl with the glowing lantern", [40.2, 86.6, 45.8, 88.8], "The girl in the red top", "lower", "her glowing lantern to the grass", False),
("Little boy dragging a lantern", [44.2, 90.1, 50.0, 92.0], "The little boy in stripes", "drag", "his lantern behind him", False),
("Big boy with the paper lanterns", [38.4, 92.1, 48.6, 96.1], "The big boy in overalls", "hand", "out paper lanterns", False),
("Red canoe", [37.0, 89.2, 45.3, 98.3], "The red canoe", "rest", "against the pavilion wall", False),
("Ladder against the wall", [35.1, 93.1, 42.5, 97.6], "The long ladder", "lean", "against the stable wall", False),
("Man in the blue vest", [29.2, 89.1, 39.3, 91.7], "The man in the blue vest", "stand", "talking under the pavilion", False),
("Man in the orange shirt", [28.8, 91.7, 38.3, 94.2], "The man in the orange shirt", "nod", "along to the conversation", False),

# TILE r2c0 - the ox wagon on the bridge and the creek below
("Brown ox", [70.6, 2.5, 79.0, 14.6], "The brown ox", "pull", "the hay wagon over the bridge", False),
("Tan ox", [75.2, 4.2, 85.0, 16.5], "The tan ox", "plod", "across the stone bridge", False),
("Old man driving the wagon", [63.0, 15.0, 73.2, 19.9], "The old driver", "guide", "the oxen with his stick", False),
("Hay wagon", [66.0, 17.2, 80.6, 28.0], "The wooden hay wagon", "creak", "over the old bridge", False),
("Girl in the hay wagon", [67.8, 18.7, 72.6, 21.4], "The blonde girl in the wagon", "enjoy", "the bumpy hay ride", False),
("Girl waving from the wagon", [66.4, 21.3, 70.3, 23.6], "The dark-haired girl", "hold", "the balloon string tight", False),
("Man in the blue cap", [64.4, 5.1, 74.5, 10.3], "The man in the blue cap", "cheer", "as the wagon rolls past", False),
("Man in the grey hoodie", [81.7, 2.7, 94.5, 6.0], "The man in the grey hoodie", "watch", "the oxen cross the bridge", False),
("Stone bridge", [78.0, 0.0, 100.0, 23.0], "The stone bridge", "arch", "over the little creek", False),
("Creek under the bridge", [92.3, 10.0, 100.0, 25.5], "The creek", "flow", "under the stone bridge", False),
("White dog by the creek", [90.9, 21.5, 95.4, 26.5], "The skinny white dog", "sniff", "along the creek bank", False),
("Bottle floating in the creek", [95.2, 17.6, 98.0, 19.2], "The glass bottle", "bob", "in the dark water", False),
("Old boot in the creek", [97.5, 15.3, 100.0, 17.7], "The old brown boot", "float", "down the creek", False),

# TILE r2c1 - the apple trees, the watering can and the vegetable garden
("Man with the watering can", [65.2, 27.3, 76.8, 31.1], "The man in the blue jacket", "water", "the young apple trees", False),
("Apple tree by the gate", [67.6, 31.2, 86.0, 36.6], "The apple tree by the gate", "carry", "bright red apples", False),
("Middle apple tree", [67.9, 36.6, 89.8, 41.2], "The middle apple tree", "drop", "an apple now and then", False),
("Apple tree by the garden", [74.3, 41.2, 85.7, 45.9], "The apple tree by the garden", "bend", "under its ripe fruit", False),
("Boy in yellow under the apple tree", [80.8, 34.7, 88.5, 37.2], "The boy in yellow", "whisper", "to his friend under the tree", False),
("Boy in red picking apples", [81.7, 36.7, 88.0, 38.9], "The boy in red", "pick", "an apple from the low branch", False),
("White rail fence", [78.5, 25.5, 100.0, 47.0], "The white rail fence", "follow", "the path down to the creek", False),
("Vegetable garden", [69.5, 43.5, 85.0, 52.0], "The vegetable garden", "grow", "in tidy moonlit rows", False),
("Watermelon in the patch", [76.2, 48.7, 78.2, 51.0], "The fat watermelon", "ripen", "in the garden patch", False),
("Row of cabbages", [80.0, 46.8, 83.5, 50.2], "The cabbages", "sit", "in a straight row", True),
("Carrot patch", [74.8, 45.0, 77.3, 49.9], "The carrot patch", "show", "only its feathery tops", False),
("Raised garden bed", [63.3, 47.0, 70.3, 54.2], "The raised garden bed", "overflow", "with herbs and flowers", False),

# TILE r2c2 - the night garden, the fox, the scarecrow and the chicken coop
("Fox sneaking by the garden", [69.3, 50.9, 72.9, 55.4], "The sly fox", "sneak", "toward the chicken coop", False),
("Red water pump", [66.6, 55.8, 72.4, 58.5], "The red water pump", "stand", "beside the trough", False),
("Water trough", [70.1, 53.4, 74.5, 59.1], "The stone water trough", "hold", "cool clear water", False),
("Woman with the flashlight", [74.3, 51.2, 85.6, 55.1], "The woman in the red hat", "shine", "her flashlight on the cabbages", False),
("Flashlight beam", [79.0, 44.5, 90.0, 51.5], "The flashlight beam", "light", "up the vegetable rows", False),
("Scarecrow in the garden", [76.6, 54.6, 88.9, 58.5], "The floppy scarecrow", "guard", "the seedling field", False),
("Boy beside the scarecrow", [82.9, 55.1, 89.8, 57.3], "The boy beside the scarecrow", "copy", "its floppy pose", False),
("Field of seedlings", [83.5, 48.0, 100.0, 68.5], "The field of seedlings", "sprout", "in long dark rows", False),
("Chicken coop", [83.0, 71.3, 100.0, 85.1], "The chicken coop", "sit", "under its corrugated roof", False),
("Ramp of the chicken coop", [94.4, 71.4, 100.0, 75.8], "The yellow ramp", "lead", "up into the coop", False),
("Rooster on the coop", [84.6, 71.3, 88.8, 73.9], "The colourful rooster", "crow", "from the coop fence", False),
("White hen by the coop", [86.0, 68.5, 92.5, 71.5], "The big white hen", "flap", "her wings at the piglets", False),
("Hen pecking the ground", [91.1, 70.0, 94.9, 72.7], "The hen by the ramp", "peck", "at the scattered corn", False),
("Little chick", [93.8, 68.5, 97.2, 70.2], "The little chick", "scurry", "after its mother", False),
("Pink piglets", [91.5, 64.0, 96.4, 68.7], "The pink piglets", "chase", "each other past the coop", True),
("Teenager cheering by the stable", [70.3, 68.3, 80.6, 72.2], "The teenager in the yellow shirt", "cheer", "from the stable walkway", False),
("Woman taking a photo", [73.7, 74.3, 84.7, 79.1], "The woman in the red skirt", "take", "a photo of the piglets", False),

# TILE r2c3 - the log cabin, the stone chimney and the cow paddock
("Log cabin", [69.5, 79.5, 85.3, 94.8], "The log cabin", "stand", "behind the chicken coop", False),
("Stone chimney", [52.7, 92.9, 84.0, 98.7], "The stone chimney", "climb", "up the cabin wall", False),
("Window with the pink curtain", [70.2, 84.2, 77.8, 88.1], "The window with the pink curtain", "glow", "warm and yellow", False),
("Window of the log cabin", [73.0, 89.1, 78.7, 92.0], "The cabin window by the chimney", "reflect", "the moonlight", False),
("Potted plant on the post", [71.8, 77.0, 77.3, 79.2], "The potted plant", "sit", "on the porch post", False),
("Spotted cow", [85.5, 85.1, 95.5, 97.6], "The spotted cow", "graze", "in the moonlit paddock", False),
("Cowbell", [89.6, 90.0, 92.4, 91.4], "The brass cowbell", "ring", "softly as the cow grazes", False),
("Wooden paddock fence", [84.5, 84.0, 100.0, 100.0], "The wooden paddock fence", "keep", "the cow in her field", False),
]
