# Page 20 - Wimmel School: cutaway school building with music room, office,
# playrooms, gym, classroom, kitchen, art room; street scene below.
# Boxes read off tile grids (tiler.py), page-percent [ymin, xmin, ymax, xmax].

P = [
    # --- r0c0: sky, roofs, office tower, music room ---
    ("Cloud above the roof", [1.0, 0.6, 3.2, 3.6],
     "The small white cloud", "float", "in the morning sky", False),
    ("Yellow helicopter", [1.4, 4.6, 8.0, 11.2],
     "The yellow helicopter", "fly", "over the school roof", False),
    ("Long red roof", [3.9, 0.0, 10.8, 100.0],
     "The long red roof", "stretch", "across the whole school", False),
    ("Roof of the tower", [8.4, 5.2, 15.6, 29.5],
     "The pointed tower roof", "rise", "above the school office", False),
    ("Row of star windows", [15.5, 7.5, 20.1, 28.0],
     "The row of star windows", "shine", "above the office", False),
    ("Poster on the office wall", [17.2, 2.0, 26.3, 5.0],
     "The colourful poster", "hang", "on the music room wall", False),
    ("Acoustic guitar", [27.5, 0.8, 33.8, 3.0],
     "The acoustic guitar", "hang", "on the music room wall", False),
    ("Drum with two sticks", [30.2, 2.5, 33.8, 5.0],
     "The drum with two sticks", "hang", "in the music room", False),
    ("Aquarium in the office", [28.3, 9.0, 33.5, 16.2],
     "The aquarium", "sit", "on the office shelf", False),
    ("Purple flowerpot", [24.9, 23.3, 27.2, 25.3],
     "The purple flowerpot", "stand", "on top of the toy cupboard", False),

    # --- r1c0: office, entrance, gym, hallway, cloakroom ---
    ("Boy with a camera", [31.4, 0.2, 39.7, 3.3],
     "The boy with the camera", "take", "a photo in the music room", False),
    ("School secretary", [29.4, 7.7, 41.2, 17.4],
     "The school secretary", "talk", "on the telephone", False),
    ("Computer screen with cars", [29.9, 14.8, 37.4, 18.6],
     "The computer screen", "show", "pictures of cars", False),
    ("Plant on the office windowsill", [37.0, 7.8, 42.3, 10.8],
     "The potted plant", "grow", "on the office windowsill", False),
    ("Plant by the toy cupboard", [37.7, 21.2, 41.8, 24.2],
     "The potted plant", "stand", "by the toy cupboard", False),
    ("Cupboard full of toys", [27.0, 20.5, 42.8, 27.8],
     "The cupboard full of toys", "stand", "by the upstairs window", False),
    ("Wimmel School sign", [45.8, 7.5, 49.3, 18.3],
     "The orange school sign", "hang", "above the entrance", False),
    ("Two black birds on the porch roof", [49.3, 6.7, 53.7, 14.0],
     "The two black birds", "peck", "at the porch roof", True),
    ("Green ball on the porch roof", [50.0, 13.8, 52.1, 15.4],
     "The green ball", "lie", "on the porch roof", False),
    ("Basketball", [50.0, 2.4, 53.5, 4.7],
     "The basketball", "fall", "towards the basket", False),
    ("Gymnastic rings", [49.8, 0.2, 54.6, 2.3],
     "The gymnastic rings", "hang", "from the gym ceiling", True),
    ("Basketball hoop", [53.5, 2.5, 56.5, 5.0],
     "The basketball hoop", "hang", "on the gym wall", False),
    ("Girl jumping for the ball", [56.5, 1.0, 67.7, 3.7],
     "The girl in the gym", "jump", "for the basketball", False),
    ("Boy in the gym", [62.4, 3.0, 68.4, 6.1],
     "The boy in the gym", "wait", "under the basket", False),
    ("Wall clock", [55.8, 12.4, 61.2, 15.6],
     "The wall clock", "show", "the time in the hallway", False),
    ("Calendar on the wall", [61.0, 12.4, 64.4, 14.6],
     "The calendar", "hang", "under the clock", False),
    ("Cactus on the shelf", [58.7, 9.9, 61.6, 11.2],
     "The little cactus", "sit", "on the hallway shelf", False),
    ("Picture of a whale", [54.4, 21.6, 57.9, 27.0],
     "The picture of a whale", "hang", "in the cloakroom", False),
    ("Hats on the shelf", [57.8, 21.0, 60.7, 27.0],
     "The hats", "wait", "on the cloakroom shelf", True),
    ("Coats on the hooks", [62.8, 22.5, 69.8, 27.0],
     "The coats", "hang", "on the cloakroom hooks", True),

    # --- r0c1: roof birds, balloon, upstairs playroom left ---
    ("Three pigeons on the roof", [3.2, 25.4, 11.8, 37.9],
     "The three pigeons", "peck", "at crumbs on the roof", True),
    ("Blue balloon", [1.8, 46.4, 6.4, 49.2],
     "The blue balloon", "float", "above the school", False),
    ("Letter tied to the balloon", [9.7, 40.6, 13.0, 43.4],
     "The little letter", "dangle", "from the balloon string", False),
    ("Beach ball on the roof", [10.0, 48.3, 12.2, 50.3],
     "The beach ball", "rest", "on the edge of the roof", False),
    ("Bunting in the upstairs doorway", [20.0, 33.0, 21.8, 36.5],
     "The bunting", "hang", "over the upstairs doorway", False),
    ("Boy running through the doorway", [22.8, 33.0, 32.8, 36.8],
     "The boy in the red shirt", "run", "through the doorway", False),
    ("Picture of a knight", [16.5, 38.0, 24.4, 44.2],
     "The picture of a knight", "hang", "on the playroom wall", False),
    ("Hanging plant", [16.7, 44.7, 24.9, 47.7],
     "The hanging plant", "trail", "from its purple pot", False),
    ("Box of picture books", [25.1, 39.9, 36.8, 44.8],
     "The box of picture books", "stand", "next to the sofa", False),

    # --- r0c2: roof, reading corner, play shop ---
    ("Red toy plane on the roof", [8.5, 56.2, 11.8, 62.2],
     "The red toy plane", "lie", "on the school roof", False),
    ("Two chimneys", [1.8, 70.2, 4.3, 76.0],
     "The two chimneys", "stand", "on top of the roof", True),
    ("Purple butterfly", [6.2, 72.8, 8.3, 75.2],
     "The purple butterfly", "flutter", "above the roof", False),
    ("Number frieze", [13.7, 30.4, 16.2, 74.0],
     "The row of numbers", "run", "above the upstairs windows", False),
    ("Shape frieze", [43.6, 30.4, 46.3, 73.6],
     "The row of shapes", "run", "above the downstairs windows", False),
    ("Hanging globe", [17.9, 49.2, 21.8, 51.4],
     "The little globe", "hang", "from the ceiling", False),
    ("Paper sun", [19.3, 53.1, 23.2, 55.6],
     "The paper sun", "dangle", "from the ceiling", False),
    ("Blue striped sofa", [22.3, 46.3, 33.6, 56.1],
     "The blue striped sofa", "stand", "in the reading corner", False),
    ("Boy reading a book", [22.1, 47.0, 30.5, 51.9],
     "The boy on the sofa", "read", "a picture book", False),
    ("Bookshelf in the reading corner", [16.5, 55.2, 27.7, 59.1],
     "The bookshelf", "hold", "rows of colourful books", False),
    ("Purple beanbag", [28.6, 54.6, 34.2, 59.1],
     "The purple beanbag", "wait", "in the reading corner", False),
    ("Toy ladybird", [29.8, 57.0, 31.4, 58.3],
     "The toy ladybird", "sit", "on the beanbag", False),
    ("Play shop", [17.2, 61.4, 30.5, 69.9],
     "The play shop", "stand", "in the corner of the playroom", False),
    ("Boy behind the fruit stall", [19.8, 63.7, 27.7, 67.5],
     "The boy in the blue cap", "sell", "fruit at the play shop", False),
    ("Girl with a shopping bag", [21.4, 69.4, 33.3, 72.7],
     "The girl with the shopping bag", "buy", "fruit at the play shop", False),
    ("Bunch of bananas", [21.6, 67.4, 23.9, 69.0],
     "The bunch of bananas", "dangle", "from the shopkeeper's hand", False),
    ("Jars on the shelf", [19.5, 60.9, 24.4, 63.9],
     "The jars", "stand", "on the shop shelf", True),
    ("Basket of fruit", [25.4, 62.2, 30.5, 68.7],
     "The basket of fruit", "sit", "on the shop counter", False),
    ("Toy pram", [28.9, 65.3, 34.2, 68.7],
     "The blue toy pram", "wait", "beside the play shop", False),

    # --- r0c3: attic window, hills, shed ---
    ("Yellow butterfly", [8.1, 75.9, 9.7, 77.5],
     "The yellow butterfly", "flutter", "by the chimney", False),
    ("Red butterfly", [12.3, 77.0, 13.9, 78.4],
     "The red butterfly", "fly", "past the drainpipe", False),
    ("Two hot air balloons", [3.6, 94.8, 9.2, 100.0],
     "The two hot air balloons", "drift", "over the green hills", True),
    ("Cloud over the hill", [1.5, 85.4, 2.9, 87.2],
     "The little cloud", "hang", "in the summer sky", False),
    ("Two birds in the sky", [1.7, 90.4, 2.8, 92.4],
     "The two birds", "fly", "high above the hills", True),
    ("Two pigeons on the window canopy", [10.9, 85.0, 15.1, 90.6],
     "The two pigeons", "cuddle", "on the window canopy", True),
    ("Paper garland in the window", [16.0, 79.5, 18.3, 86.7],
     "The paper garland", "hang", "across the attic window", False),
    ("Child in a ghost costume", [19.3, 79.6, 30.0, 86.7],
     "The child in the ghost costume", "wave", "at the attic window", False),
    ("Girl in a witch costume", [27.9, 79.1, 35.0, 85.9],
     "The girl in the witch costume", "point", "with her magic wand", False),
    ("Curtain with stars", [16.5, 86.7, 32.6, 93.0],
     "The blue curtain with stars", "hang", "in the attic corner", False),
    ("Girl under the curtain", [24.0, 87.6, 32.6, 90.6],
     "The girl in the yellow hat", "crawl", "out from under the curtain", False),
    ("Pond on the hill", [13.0, 96.9, 18.8, 100.0],
     "The little pond", "sparkle", "at the foot of the hills", False),
    ("Garden shed", [24.5, 93.5, 40.3, 100.0],
     "The garden shed", "stand", "behind the school", False),
    ("Bush by the shed", [40.3, 97.7, 45.3, 100.0],
     "The bush by the shed", "grow", "beside the shed door", False),

    # --- r1c1: toy doctor room, classroom with teacher ---
    ("Picture of a teddy bear", [32.6, 30.7, 40.2, 33.5],
     "The picture of a teddy bear", "lean", "against the wall", False),
    ("Green toy mouse", [36.3, 36.1, 39.5, 38.9],
     "The green toy mouse", "wait", "on the playroom floor", False),
    ("Toy owl with a bandage", [34.6, 39.0, 39.7, 42.3],
     "The toy owl", "wear", "a red bandage on its head", False),
    ("Toy donkey", [33.7, 44.1, 40.2, 48.9],
     "The grey toy donkey", "visit", "the toy doctor", False),
    ("Girl in a nurse cap", [30.9, 47.5, 39.3, 51.4],
     "The girl in the nurse cap", "look", "after the toy donkey", False),
    ("Boy with a bandage", [33.2, 50.6, 39.7, 55.1],
     "The boy in the green shirt", "unroll", "a white bandage", False),
    ("First aid kit", [36.3, 54.8, 39.7, 57.3],
     "The red first aid kit", "lie", "open on the floor", False),
    ("Bunting over the classroom door", [48.6, 32.6, 50.2, 36.1],
     "The bunting", "hang", "over the classroom door", False),
    ("Poster of a walking bear", [47.2, 39.5, 53.9, 45.1],
     "The poster of a bear", "hang", "on the classroom wall", False),
    ("Teacher in the green dress", [50.0, 37.5, 65.8, 42.5],
     "The teacher in the green dress", "hug", "the little children", False),
    ("Boy hugging the teacher", [54.9, 37.2, 64.9, 40.3],
     "The little boy", "hug", "the teacher", False),
    ("Girl in the pink dress", [55.8, 33.3, 65.8, 36.6],
     "The girl in the pink dress", "run", "to the teacher", False),
    ("Girl in the yellow jumper", [56.5, 42.3, 66.5, 45.4],
     "The girl in the yellow jumper", "smile", "at the teacher", False),
    ("Girl in the orange jumper", [51.6, 46.0, 60.7, 48.6],
     "The girl in the orange jumper", "stand", "by the climbing frame", False),
    ("Abacus", [66.9, 32.1, 69.1, 39.4],
     "The abacus", "stand", "by the classroom window", False),
    ("Marble run", [60.5, 44.9, 69.8, 48.2],
     "The marble run", "twist", "down to the floor", False),

    # --- r1c2: tea party, photo wall, snack kitchen ---
    ("Toy chick", [35.8, 49.8, 39.5, 52.0],
     "The yellow toy chick", "watch", "the toy doctor", False),
    ("Boy pouring tea", [30.8, 59.7, 39.5, 63.8],
     "The boy with the teapot", "pour", "tea for the toys", False),
    ("Tea party table", [35.6, 62.6, 40.2, 68.7],
     "The little blue table", "hold", "the toys' tea party", False),
    ("Plate of pancakes", [36.6, 64.7, 39.0, 67.1],
     "The plate of pancakes", "wait", "in the middle of the table", False),
    ("White puppy at the tea party", [33.7, 63.2, 37.4, 66.1],
     "The white puppy", "sniff", "at the pancakes", False),
    ("Plush pig", [34.6, 66.6, 39.0, 69.6],
     "The pink plush pig", "doze", "at the tea party", False),
    ("Red-haired girl at the tea party", [35.6, 69.0, 40.2, 71.5],
     "The red-haired girl", "hold", "a tiny teacup", False),
    ("Photo wall", [47.0, 49.1, 54.6, 57.9],
     "The wall of photos", "show", "all the children's faces", False),
    ("Girl pointing at the photos", [52.3, 49.5, 62.1, 52.0],
     "The girl in the yellow dress", "point", "at her photo on the wall", False),
    ("Kitchen sink", [47.2, 60.8, 53.7, 65.3],
     "The kitchen sink", "shine", "in the snack corner", False),
    ("Teacher with the juice jug", [48.1, 65.1, 60.7, 70.5],
     "The teacher with the glasses", "pour", "juice for the children", False),
    ("Jug of juice", [53.3, 64.3, 57.9, 66.7],
     "The jug of red juice", "fill", "the little cup", False),
    ("Girl in dungarees", [55.4, 60.5, 66.3, 64.7],
     "The girl in the dungarees", "hold", "out her cup for juice", False),
    ("Serving trolley", [56.1, 64.9, 64.9, 70.5],
     "The serving trolley", "carry", "a plate of rolls", False),
    ("Girl smelling the flowers", [54.4, 52.9, 64.9, 57.0],
     "The girl in purple", "reach", "for the vase of flowers", False),
    ("Vase of flowers", [54.9, 57.1, 60.0, 59.9],
     "The vase of red flowers", "stand", "on the round table", False),
    ("Round green table", [59.6, 55.8, 64.0, 61.8],
     "The round green table", "stand", "in the snack corner", False),
    ("Lamp post", [51.2, 73.6, 93.3, 76.4],
     "The tall lamp post", "stand", "on the pavement corner", False),
    ("Tower of building blocks", [56.5, 70.6, 71.7, 73.6],
     "The tower of blocks", "reach", "almost to the ceiling", False),

    # --- r1c3: roofer, squirrel, art room top, garden ---
    ("Man repairing the roof", [30.9, 89.3, 42.3, 95.5],
     "The man in the dungarees", "hammer", "a nail into the roof", False),
    ("Toolbox on the roof", [37.0, 79.4, 44.6, 85.3],
     "The wooden toolbox", "sit", "on the bay roof", False),
    ("Squirrel on the roof", [41.9, 86.2, 49.5, 89.8],
     "The squirrel", "scamper", "across the bay roof", False),
    ("Drawings on the washing line", [51.4, 79.0, 57.9, 96.7],
     "The children's drawings", "dry", "on the washing line", True),
    ("Drawing of a tractor", [52.3, 79.1, 57.4, 83.2],
     "The drawing of a tractor", "hang", "on the washing line", False),
    ("Drawing of a dinosaur", [52.6, 87.9, 57.4, 91.5],
     "The drawing of a dinosaur", "hang", "next to the house picture", False),
    ("Paper rocket", [60.7, 81.1, 63.0, 83.7],
     "The paper rocket", "hang", "from the art room ceiling", False),
    ("Table with flowerpots", [57.8, 97.5, 60.8, 100.0],
     "The table with flowerpots", "stand", "in the school garden", False),
    ("Green ball on the grass", [55.1, 98.7, 56.6, 99.8],
     "The green ball", "lie", "on the grass", False),

    # --- r2c0: entrance hall, car, street left ---
    ("Girl hugging the puppy", [62.4, 9.3, 72.2, 13.0],
     "The girl in the blue top", "hug", "the little puppy", False),
    ("Beige puppy", [65.2, 11.3, 69.8, 14.0],
     "The beige puppy", "lick", "the girl's cheek", False),
    ("Man helping with a shoe", [62.4, 13.6, 74.5, 17.7],
     "The man in the flat cap", "hold", "out a yellow shoe", False),
    ("Yellow shoe on the floor", [72.6, 13.0, 74.3, 14.5],
     "The yellow shoe", "wait", "by the doorstep", False),
    ("Girl at the cloakroom window", [73.1, 20.9, 75.9, 22.7],
     "The little girl", "peek", "out of the cloakroom window", False),
    ("Shoes in the cloakroom", [69.6, 21.2, 73.6, 27.0],
     "The shoes", "sit", "in rows in the cloakroom", True),
    ("Front steps", [75.2, 7.0, 83.3, 20.5],
     "The grey front steps", "lead", "up to the school door", True),
    ("Bush by the school wall", [72.7, 0.0, 77.3, 3.7],
     "The bush by the school wall", "grow", "next to the entrance", False),
    ("Bush by the steps", [78.0, 20.5, 81.5, 24.2],
     "The bush by the steps", "grow", "beside the pavement", False),
    ("Red family car", [76.6, 0.0, 97.3, 12.5],
     "The red family car", "park", "in front of the school", False),
    ("Man in the car", [80.1, 2.2, 85.2, 5.5],
     "The man in the car", "smile", "from the front seat", False),
    ("Toddler in the car seat", [85.0, 1.6, 91.2, 5.0],
     "The toddler", "sit", "in the child seat", False),
    ("Boy getting out of the car", [83.1, 5.3, 94.5, 10.3],
     "The boy in the yellow shirt", "climb", "out of the car", False),
    ("Mother with the blue bag", [78.9, 10.1, 95.0, 16.2],
     "The mother with the blue bag", "take", "the boy's hand", False),
    ("Blue shoulder bag", [87.1, 12.1, 91.2, 14.5],
     "The blue shoulder bag", "hang", "from the mother's shoulder", False),
    ("Girl on the purple bike", [80.3, 18.0, 92.2, 25.3],
     "The girl in the helmet", "ride", "her purple bike to school", False),

    # --- r2c1: lawn, hedge, scooter, cargo bike ---
    ("Two purple balloons", [75.2, 26.2, 81.9, 29.7],
     "The two purple balloons", "bob", "over the hedge", True),
    ("Orange butterfly on the wall", [71.3, 35.9, 72.9, 37.4],
     "The orange butterfly", "rest", "on the yellow wall", False),
    ("Butterfly by the flowers", [71.5, 47.3, 73.3, 48.8],
     "The red admiral butterfly", "hover", "by the little flowers", False),
    ("Mole on the molehill", [74.3, 36.2, 78.0, 41.7],
     "The little mole", "peek", "out of its molehill", False),
    ("Flowers in the grass", [73.1, 41.3, 75.9, 45.5],
     "The little flowers", "bloom", "in the grass", True),
    ("Long hedge", [80.0, 22.0, 87.9, 96.0],
     "The long green hedge", "run", "along the pavement", False),
    ("Man on the blue scooter", [77.3, 31.5, 94.3, 36.0],
     "The man in the dark jumper", "ride", "a blue kick scooter", False),
    ("Blue kick scooter", [85.9, 27.0, 96.8, 37.8],
     "The blue kick scooter", "roll", "along the pavement", False),
    ("Cargo bike with a canopy", [78.0, 39.0, 97.3, 56.4],
     "The cargo bike", "carry", "two children to school", False),
    ("Boy with a bottle in the cargo bike", [81.7, 40.4, 88.4, 44.3],
     "The boy in the green jacket", "drink", "from his bottle", False),
    ("Girl in the cargo bike", [83.4, 45.2, 89.1, 47.9],
     "The dark-haired girl", "chat", "in the cargo bike", False),
    ("Teddy bear in the cargo bike", [83.6, 39.3, 88.4, 41.2],
     "The teddy bear", "ride", "along in the cargo bike", False),

    # --- r2c2: playroom window, pavement middle ---
    ("Boy waving with the toy dog", [62.8, 49.2, 70.3, 55.1],
     "The boy at the window", "wave", "to his friends", False),
    ("Blue toy dog", [67.6, 49.2, 71.0, 52.2],
     "The blue toy dog", "sit", "in the boy's arm", False),
    ("Play mat with roads", [63.8, 55.1, 71.2, 72.9],
     "The play mat with roads", "cover", "the playroom floor", False),
    ("Orange toy car", [65.7, 57.4, 68.0, 60.1],
     "The orange toy car", "wait", "on the play mat", False),
    ("Toy house on the mat", [67.6, 55.4, 69.8, 57.3],
     "The little toy house", "stand", "at the edge of the mat", False),
    ("Toy tower block", [67.6, 61.1, 70.8, 63.0],
     "The toy tower block", "stand", "in the middle of the mat", False),
    ("Boy pushing the red car", [63.5, 64.6, 70.8, 69.9],
     "The blond boy", "push", "the red toy car", False),
    ("Red toy car", [69.6, 63.6, 71.5, 66.2],
     "The red toy car", "zoom", "across the play mat", False),
    ("Soap bubbles", [72.8, 55.4, 77.4, 66.7],
     "The soap bubbles", "float", "over the schoolyard", True),
    ("Round bush on the lawn", [72.9, 52.3, 77.3, 57.3],
     "The round bush", "grow", "on the front lawn", False),
    ("Daisies by the wall", [73.6, 67.9, 79.1, 72.4],
     "The white daisies", "bloom", "by the school wall", True),
    ("Mother kneeling on the pavement", [76.9, 59.2, 90.1, 65.0],
     "The kneeling mother", "point", "at the soap bubbles", False),
    ("Boy with the blue backpack", [79.4, 56.2, 90.3, 60.1],
     "The boy with the backpack", "look", "up at the bubbles", False),
    ("Blue backpack", [83.1, 56.2, 87.5, 58.2],
     "The blue backpack", "hang", "on the boy's shoulders", False),
    ("Woman riding the cargo bike", [80.8, 50.4, 95.4, 56.4],
     "The woman in the helmet", "pedal", "the heavy cargo bike", False),
    ("Little brown dog", [83.1, 66.0, 89.1, 69.2],
     "The little brown dog", "trot", "along the pavement", False),
    ("Grey cat", [91.0, 72.8, 96.8, 78.1],
     "The grey cat", "dash", "across the street", False),

    # --- r2c3: art room, teacher with clock, running children ---
    ("Child in the wheelchair", [61.9, 78.5, 74.7, 83.2],
     "The child in the wheelchair", "cut", "out a paper heart", False),
    ("Boy drawing at the table", [61.7, 84.8, 73.0, 89.4],
     "The boy with the pencil", "draw", "at the craft table", False),
    ("Boy with the pirate drawing", [60.0, 89.9, 68.9, 93.7],
     "The boy in the orange vest", "show", "his pirate drawing", False),
    ("Drawing of a pirate ship", [64.1, 89.6, 68.0, 93.4],
     "The drawing of a pirate ship", "flap", "in the boy's hands", False),
    ("Purple craft table", [68.5, 81.4, 74.7, 93.7],
     "The purple craft table", "hold", "pencils and paints", False),
    ("Trolley with paint pots", [70.6, 89.2, 75.2, 93.7],
     "The blue trolley", "carry", "pots of paint", False),
    ("Teacher with the alarm clock", [75.2, 83.9, 93.1, 92.7],
     "The teacher in the pink dress", "wave", "the children into school", False),
    ("Red alarm clock", [76.2, 83.3, 79.6, 85.8],
     "The red alarm clock", "ring", "in the teacher's hand", False),
    ("Boy pulling on his jacket", [80.1, 76.2, 92.4, 80.3],
     "The boy in the red jacket", "pull", "the jacket over his head", False),
    ("Boy in the white vest", [84.3, 81.4, 94.0, 86.0],
     "The boy in the white vest", "hurry", "to the school door", False),
    ("Boy eating his breakfast", [82.9, 89.3, 95.9, 94.3],
     "The boy with the blue bowl", "eat", "his breakfast on the way", False),
    ("Girl washing her face", [80.8, 94.7, 92.6, 99.2],
     "The girl in the star shirt", "wipe", "her face with a flannel", False),
    ("Puddle under the drainpipe", [77.9, 78.6, 80.6, 82.2],
     "The puddle", "spread", "under the drainpipe", False),
]
