# Page 11 - the sports fields and the shopping street: the football pitch, the
# baseball diamond, the basketball court, the row of shops and the busy road.
# Boxes read straight off the tiler grid labels, one block per tile.
P = [

# TILE r0c0
("Green football pitch", [2.8, 0.0, 18.6, 28.0], "The green football pitch", "stretch", "behind the wire fence", False),
("White goal net", [4.9, 0.0, 10.5, 3.2], "The white goal net", "wait", "for the next shot", False),
("Goalkeeper in the white kit", [5.3, 1.2, 10.0, 2.8], "The goalkeeper in the white kit", "guard", "the goal", False),
("Boy in the white shirt", [5.3, 8.0, 10.0, 9.3], "The boy in the white shirt", "run", "onto the pitch", False),
("Boy in the red cap", [6.7, 9.9, 12.1, 10.8], "The boy in the red cap", "dribble", "the ball forward", False),
("Boy in the blue cap", [7.2, 5.2, 12.1, 6.6], "The boy in the blue cap", "wait", "for a pass", False),
("Girl in the red shirt", [12.1, 3.2, 17.7, 5.1], "The girl in the red shirt", "jog", "along the touchline", False),
("Boy watching by the fence", [11.9, 0.8, 18.6, 2.3], "The boy watching by the fence", "watch", "the football match", False),
("Girl in the yellow shirt", [14.0, 12.7, 20.9, 14.7], "The girl in the yellow shirt", "chase", "after the ball", False),
("Boy in the blue shirt", [11.2, 17.1, 16.5, 18.5], "The boy in the blue shirt", "play", "in the middle of the pitch", False),
("Girl with the blonde ponytail", [13.3, 22.1, 19.5, 23.5], "The girl with the blonde ponytail", "stand", "at the edge of the game", False),
("White football", [8.4, 14.8, 9.8, 15.7], "The white football", "bounce", "across the grass", False),
("Floodlight pole", [0.0, 6.5, 6.0, 7.1], "The floodlight pole", "rise", "above the pitch", False),
("Chain link fence", [13.5, 0.0, 24.2, 28.0], "The chain link fence", "separate", "the pitch from the road", False),
("Yellow car", [19.3, 0.6, 28.8, 13.3], "The yellow car", "drive", "along the road", False),
("Driver in the yellow car", [21.9, 6.8, 24.2, 8.5], "The driver in the yellow car", "steer", "past the football pitch", False),
("Passenger waving from the car", [21.9, 3.9, 24.4, 5.4], "The passenger waving from the car", "wave", "out of the window", False),
("Grey road", [25.3, 0.0, 33.5, 28.0], "The grey road", "curve", "through the town", False),
("Sea Food banner", [30.0, 0.9, 45.0, 5.1], "The sea food banner", "hang", "outside the restaurant", False),
("Girl with the pink backpack", [29.8, 14.8, 36.2, 17.3], "The girl with the pink backpack", "walk", "along the pavement", False),
("Boy in the yellow vest", [29.3, 20.8, 36.2, 22.8], "The boy in the yellow vest", "follow", "his troop", False),
("Fire hydrant", [32.1, 10.6, 34.4, 11.6], "The fire hydrant", "stand", "beside the kerb", False),

# TILE r0c1
("White school building", [0.7, 29.3, 5.3, 34.7], "The white school building", "look", "down over the fields", False),
("House with the red roof", [2.6, 40.2, 5.3, 44.2], "The house with the red roof", "sit", "on the far hillside", False),
("Tall conifer trees", [1.2, 30.0, 5.8, 33.1], "The tall conifer trees", "grow", "behind the goal", True),
("Football goal", [7.2, 29.3, 16.3, 33.4], "The football goal", "stand", "at the end of the pitch", False),
("Football in the air", [8.1, 25.2, 10.0, 26.5], "The football in the air", "fly", "towards the goal", False),
("Girl kicking the ball", [8.1, 27.7, 13.5, 29.9], "The girl kicking the ball", "kick", "the ball at the goal", False),
("Baseball diamond", [9.3, 37.4, 15.3, 53.0], "The baseball diamond", "curve", "across the second field", False),
("Pitcher in the blue shirt", [8.1, 40.7, 13.5, 42.4], "The pitcher in the blue shirt", "throw", "the ball to the catcher", False),
("Fielder in the blue cap", [5.1, 43.4, 10.0, 44.8], "The fielder in the blue cap", "wait", "for the ball", False),
("Batter in the red cap", [7.4, 48.9, 12.8, 50.2], "The batter in the red cap", "swing", "at the pitch", False),
("Tall backstop fence", [4.9, 35.0, 21.4, 38.0], "The tall backstop fence", "catch", "the wild balls", False),
("Stadium floodlight", [0.9, 36.2, 5.1, 37.4], "The stadium floodlight", "tower", "over the baseball field", False),
("Man in the blue shirt", [14.4, 37.9, 24.9, 40.2], "The man in the blue shirt", "lean", "on the wire fence", False),
("Boy sitting on the grass", [16.0, 33.7, 21.9, 35.3], "The boy sitting on the grass", "rest", "beside the fence", False),
("Man in the dark suit", [16.3, 45.8, 24.9, 48.4], "The man in the dark suit", "watch", "the baseball game", False),
("Child crouching by the fence", [19.8, 48.9, 24.7, 51.3], "The child crouching by the fence", "peer", "through the wire", False),
("Scout in the red cap", [30.5, 24.3, 36.2, 26.0], "The scout in the red cap", "march", "along the pavement", False),
("Scout in the yellow cap", [29.1, 26.5, 36.2, 28.3], "The scout in the yellow cap", "carry", "his rucksack", False),
("Scout with the brown hair", [29.8, 30.6, 36.2, 32.6], "The scout with the brown hair", "chat", "with her friend", False),
("Scout leader with the map", [27.0, 33.7, 36.2, 39.0], "The scout leader with the map", "lead", "the troop into town", False),
("Folded map", [29.3, 36.8, 33.5, 39.0], "The folded map", "show", "the way to the park", False),
("Palm tree leaves", [28.8, 43.6, 36.2, 51.3], "The palm tree leaves", "spread", "over the pavement", True),

# TILE r0c2
("Yellow apartment block", [0.9, 72.3, 5.8, 87.4], "The yellow apartment block", "stand", "on the hill above the town", False),
("Yellow house with the red roof", [3.0, 61.5, 7.2, 65.2], "The yellow house with the red roof", "overlook", "the baseball field", False),
("Pitcher on the mound", [10.2, 53.2, 16.5, 55.6], "The pitcher on the mound", "wind", "up for the throw", False),
("Pitcher's mound", [15.3, 51.8, 17.2, 56.0], "The pitcher's mound", "sit", "in the middle of the diamond", False),
("Catcher behind the plate", [9.5, 64.4, 15.3, 66.8], "The catcher behind the plate", "crouch", "behind the batter", False),
("Fielder near first base", [7.2, 48.7, 12.8, 50.5], "The fielder near first base", "cover", "first base", False),
("Fielder in the middle of the field", [6.0, 57.5, 12.1, 59.2], "The fielder in the middle of the field", "stand", "out in the sunshine", False),
("Outfielder in the blue cap", [6.7, 68.3, 11.2, 69.5], "The outfielder in the blue cap", "wait", "far out in the field", False),
("Baseball helmet on the grass", [16.3, 52.1, 17.9, 53.9], "The baseball helmet on the grass", "lie", "beside the mound", False),
("Man in the yellow shirt", [10.9, 71.4, 17.2, 73.5], "The man in the yellow shirt", "coach", "the young players", False),
("Girl behind the wire fence", [14.0, 73.9, 18.1, 75.6], "The girl behind the wire fence", "hold", "on to the wire", False),
("Boy in the red shirt", [18.6, 66.0, 23.3, 67.5], "The boy in the red shirt", "queue", "at the gate", False),
("Boy in the yellow shirt", [19.5, 67.4, 23.7, 68.9], "The boy in the yellow shirt", "wait", "behind his friend", False),
("Woman in the pink top", [17.4, 70.0, 20.0, 71.4], "The woman in the pink top", "walk", "towards the field", False),
("Bicycle behind the fence", [19.8, 51.0, 24.2, 54.1], "The bicycle behind the fence", "lean", "against the wire", False),
("Father in the blue shirt", [20.9, 60.3, 31.2, 62.7], "The father in the blue shirt", "hold", "his little boy's hand", False),
("Little boy in the blue shirt", [25.8, 63.0, 30.7, 64.6], "The little boy in the blue shirt", "look", "up at his father", False),
("Gate in the fence", [18.8, 66.4, 29.8, 68.0], "The gate in the fence", "swing", "open to the field", False),
("Red pickup truck", [25.3, 67.7, 36.2, 78.0], "The red pickup truck", "park", "beside the court", False),
("Bushes by the fence", [30.7, 62.1, 36.2, 67.4], "The bushes by the fence", "grow", "along the pavement", True),

# TILE r0c3
("Big trees behind the court", [1.2, 88.0, 6.5, 93.6], "The big trees behind the court", "shade", "the far end of the court", True),
("Basketball hoop", [6.7, 78.6, 12.1, 81.9], "The basketball hoop", "hang", "above the court", False),
("Basketball in the air", [8.1, 82.9, 10.0, 84.2], "The basketball in the air", "sail", "towards the hoop", False),
("Basketball court", [14.9, 78.2, 21.4, 100.0], "The basketball court", "fill", "the corner of the park", False),
("Player in the black top", [12.8, 85.6, 19.5, 87.4], "The player in the black top", "jump", "for the ball", False),
("Player with his arms up", [14.0, 83.4, 19.8, 84.9], "The player with his arms up", "block", "the shot", False),
("Player in the striped top", [14.0, 87.3, 20.0, 88.8], "The player in the striped top", "guard", "his opponent", False),
("Boy in the green top", [14.7, 93.3, 21.4, 95.0], "The boy in the green top", "wait", "at the side of the court", False),
("Boy in the orange top", [12.1, 98.1, 17.2, 99.5], "The boy in the orange top", "stretch", "before the game", False),
("Boy leaning on the fence", [17.4, 96.4, 25.3, 98.4], "The boy leaning on the fence", "rest", "against the wire", False),
("Spectator in the yellow top", [14.9, 74.3, 19.5, 76.0], "The spectator in the yellow top", "cheer", "for the players", False),
("Boy crouching by the court", [18.1, 82.3, 22.8, 84.3], "The boy crouching by the court", "tie", "his shoelace", False),
("Red estate car", [22.3, 72.0, 34.6, 83.4], "The red estate car", "park", "beside the basketball court", False),
("Man with the shopping bag", [22.3, 84.5, 33.5, 87.1], "The man with the shopping bag", "walk", "back to his car", False),
("Green shopping bag", [27.2, 86.0, 29.1, 87.4], "The green shopping bag", "swing", "from the man's hand", False),
("White bag on the ground", [30.0, 82.3, 33.5, 83.7], "The white bag on the ground", "sit", "beside the car", False),
("Person in the wheelchair", [25.3, 87.3, 32.1, 90.5], "The person in the wheelchair", "wait", "near the barbecue", False),
("Golf bag on a trolley", [25.8, 90.2, 30.9, 92.1], "The golf bag on a trolley", "lean", "on its little wheels", False),
("Boy in the striped shirt", [29.3, 92.4, 39.8, 95.0], "The boy in the striped shirt", "cook", "at the barbecue", False),
("Pink flowers by the fence", [25.3, 95.5, 28.8, 97.9], "The pink flowers by the fence", "bloom", "along the wire", True),


# TILE r1c0
("Red tiled roof", [34.8, 0.0, 58.9, 47.0], "The red tiled roof", "cover", "the whole row of shops", False),
("Palm tree by the shop", [41.8, 8.2, 53.4, 20.4], "The palm tree by the shop", "grow", "right through the roof", False),
("Palm fronds over the awning", [45.5, 0.0, 59.0, 4.0], "The palm fronds over the awning", "droop", "over the awning", True),
("Green tree by the restaurant", [32.0, 1.7, 40.1, 5.4], "The green tree by the restaurant", "stand", "beside the sea food sign", False),
("Skateboard on the pavement", [32.7, 13.9, 34.5, 15.1], "The skateboard on the pavement", "lie", "where its rider left it", False),
("Dee Dee's Clothing sign", [53.4, 14.8, 57.6, 24.1], "The Dee Dee's Clothing sign", "spell", "out the name of the shop", False),
("Clothing shop window", [55.6, 20.4, 65.2, 24.7], "The clothing shop window", "show", "the new summer dresses", False),
("Striped shop awning", [60.0, 0.0, 67.0, 13.3], "The striped shop awning", "shade", "the tables outside", False),
("Rosie's Ices sign", [58.6, 11.6, 69.5, 12.7], "The Rosie's Ices sign", "hang", "down the side of the wall", False),
("Woman in the pink dress", [59.5, 15.1, 69.5, 17.3], "The woman in the pink dress", "come", "out of the clothes shop", False),
("Man in the sun hat", [57.6, 17.4, 69.5, 20.1], "The man in the sun hat", "carry", "the baby on his arm", False),
("Child in the green top", [62.7, 18.2, 69.5, 20.4], "The child in the green top", "hold", "on to her mother", False),
("Waiter in the white apron", [65.3, 4.8, 69.5, 8.0], "The waiter in the white apron", "serve", "the outside tables", False),

# TILE r1c1
("White dove", [45.0, 27.1, 49.2, 32.2], "The white dove", "land", "on the red roof", False),
("Blue car", [34.8, 38.4, 40.9, 43.6], "The blue car", "pull", "away from the kerb", False),
("Yellow car at the kerb", [37.8, 35.3, 40.9, 43.0], "The yellow car at the kerb", "wait", "in the traffic", False),
("Parking meter", [39.2, 45.5, 42.2, 46.4], "The parking meter", "stand", "on the pavement", False),
("Tall palm tree", [30.3, 43.0, 40.8, 51.6], "The tall palm tree", "sway", "above the street", False),
("Leafy street tree", [48.3, 31.9, 69.5, 43.6], "The leafy street tree", "shade", "the front of the shops", False),
("Tree by the shop corner", [43.6, 46.1, 62.7, 53.0], "The tree by the shop corner", "grow", "at the corner of the street", False),
("Cat on the shop roof", [56.7, 38.0, 59.0, 39.9], "The cat on the shop roof", "creep", "along the gutter", False),
("Shop window with the glass canopy", [51.9, 24.8, 67.4, 32.9], "The shop window with the glass canopy", "face", "the pavement", False),
("Spotted dress in the window", [57.9, 28.0, 63.4, 30.9], "The spotted dress in the window", "hang", "in the shop window", False),
("Yellow dress on the mannequin", [61.4, 26.8, 67.4, 28.6], "The yellow dress on the mannequin", "catch", "the shoppers' eyes", False),
("Woman looking in the window", [63.5, 26.8, 69.5, 29.3], "The woman looking in the window", "stare", "at the summer dresses", False),
("Man in the shop doorway", [56.7, 48.1, 66.4, 50.6], "The man in the shop doorway", "stand", "in the open door", False),

# TILE r1c2
("Maroon car", [39.7, 54.1, 42.5, 58.7], "The maroon car", "park", "under the trees", False),
("Tall tree by the pavement", [31.0, 57.8, 53.4, 68.6], "The tall tree by the pavement", "tower", "over the parked cars", False),
("Round tree over the car", [39.2, 47.6, 58.1, 57.2], "The round tree over the car", "hang", "over the blue car", False),
("Zebra crossing", [36.2, 68.6, 51.1, 78.0], "The zebra crossing", "stripe", "the wide road", False),
("Dog walker in the blue top", [37.6, 70.0, 49.2, 73.2], "The dog walker in the blue top", "cross", "the road with her dogs", False),
("Yellow dog on the lead", [44.8, 68.3, 48.3, 70.5], "The yellow dog on the lead", "pull", "on its lead", False),
("Black poodle", [47.8, 66.1, 53.4, 69.2], "The black poodle", "trot", "over the crossing", False),
("Black and white dog", [41.3, 74.8, 45.5, 78.0], "The black and white dog", "sniff", "at the road", False),
("Blue car with the boot open", [48.8, 53.8, 62.7, 60.0], "The blue car with the boot open", "wait", "for the shopping", False),
("Man loading the car", [48.5, 59.8, 61.8, 62.3], "The man loading the car", "lift", "the bags into the boot", False),
("White bag in the boot", [54.4, 57.3, 57.6, 59.3], "The white bag in the boot", "sit", "in the open boot", False),
("Police car", [56.2, 62.4, 69.5, 74.2], "The police car", "cruise", "slowly down the road", False),
("Blue light on the police car", [56.5, 65.8, 58.1, 70.1], "The blue light on the police car", "sit", "on the roof", False),
("Police officer at the wheel", [60.2, 68.6, 62.7, 70.5], "The police officer at the wheel", "drive", "past the shops", False),
("Children in the police car", [60.2, 66.1, 63.2, 68.6], "The children in the police car", "peer", "out of the window", True),
("Woman with the shopping bags", [60.7, 55.8, 69.5, 59.0], "The woman with the shopping bags", "carry", "her shopping home", False),
("Little girl in the yellow dress", [64.2, 53.2, 69.5, 55.0], "The little girl in the yellow dress", "skip", "beside her mother", False),

# TILE r1c3
("Barbecue grill", [31.0, 95.0, 39.0, 100.0], "The barbecue grill", "smoke", "at the edge of the field", False),
("Woman in the pink blouse", [36.2, 79.9, 47.4, 82.8], "The woman in the pink blouse", "throw", "the frisbee", False),
("White frisbee", [35.2, 77.4, 37.8, 78.9], "The white frisbee", "spin", "across the grass", False),
("Woman in the blue top", [33.1, 83.9, 39.8, 87.1], "The woman in the blue top", "hold", "her plate of food", False),
("Plate of food", [37.8, 85.1, 39.0, 87.4], "The plate of food", "balance", "on her knees", False),
("Girl in the pink top", [34.9, 88.8, 39.8, 90.5], "The girl in the pink top", "help", "at the picnic", False),
("Man relaxing in the folding chair", [40.6, 86.0, 45.5, 88.8], "The man relaxing in the folding chair", "stretch", "out in the sun", False),
("Folding picnic table", [39.8, 89.9, 45.5, 93.0], "The folding picnic table", "hold", "the drinks", False),
("Bottles and cups on the table", [39.8, 90.4, 42.6, 92.7], "The bottles and cups on the table", "wait", "for the thirsty players", True),
("Boy in the black T-shirt", [41.3, 95.0, 45.5, 97.0], "The boy in the black T-shirt", "reach", "for a drink", False),
("Girl in the red skirt", [43.4, 92.1, 48.3, 94.2], "The girl in the red skirt", "run", "back to the picnic", False),
("Small girl in the yellow top", [45.7, 87.9, 52.5, 89.7], "The small girl in the yellow top", "call", "her dog", False),
("Brown dog", [48.8, 83.1, 52.3, 86.8], "The brown dog", "run", "across the grass", False),
("White dog on the crossing", [41.3, 75.1, 45.5, 77.1], "The white dog on the crossing", "walk", "beside the black dog", False),
("Black dog on the lead", [41.5, 76.8, 45.5, 79.3], "The black dog on the lead", "tug", "towards the grass", False),
("Little white dog", [46.0, 76.8, 48.8, 79.3], "The little white dog", "scamper", "after the others", False),
("Tree by the music school", [49.4, 76.6, 69.5, 87.1], "The tree by the music school", "shade", "the roof of the house", False),
("Bushes behind the house", [48.8, 91.1, 62.7, 100.0], "The bushes behind the house", "screen", "the back of the house", True),
("Stone chimney", [55.9, 88.8, 64.1, 91.7], "The stone chimney", "rise", "through the tiled roof", False),
("Brown tiled roof", [59.9, 84.3, 69.5, 100.0], "The brown tiled roof", "slope", "down towards the street", False),

]
