# Page 21 — busy primary classroom. Boxes read off tiler grid labels, per tile.
# (name, [ymin, xmin, ymax, xmax], subject, bare-infinitive verb, rest, plural)

P = [
    # ---------- r0c0  x0-28 y0-36.3 ----------
    ("Alphabet train frieze on the wall", [1.3, 0.4, 15.5, 28.0],
     "The alphabet frieze", "run", "right along the classroom wall", False),
    ("Toy engine at the front of the frieze", [11.3, 0.4, 16.2, 4.3],
     "The little engine", "pull", "the alphabet carriages", False),
    ("Letter card A with an apple", [10.4, 4.2, 14.5, 6.4],
     "The letter A card", "show", "a shiny green apple", False),
    ("Letter card B with a boat", [9.2, 6.2, 14.1, 8.6],
     "The letter B card", "show", "a little sailing boat", False),
    ("Letter card C with a cat", [8.0, 8.4, 13.6, 10.6],
     "The letter C card", "show", "a white cat", False),
    ("Letter card D with a dog", [7.1, 10.4, 12.9, 12.5],
     "The letter D card", "show", "a brown dog", False),
    ("Letter card E with an elephant", [6.4, 12.3, 12.2, 14.5],
     "The letter E card", "show", "a grey elephant", False),
    ("Letter card F with a flower", [6.0, 14.3, 11.5, 16.5],
     "The letter F card", "show", "a purple flower", False),
    ("Letter card G with grapes", [4.8, 16.4, 10.8, 18.6],
     "The letter G card", "show", "a bunch of grapes", False),
    ("Letter card H with a heart", [4.3, 18.4, 10.1, 20.6],
     "The letter H card", "show", "a big red heart", False),
    ("Letter card I with an ice cream", [2.9, 20.4, 9.4, 22.3],
     "The letter I card", "show", "an ice cream cone", False),
    ("Letter card J with a jam jar", [2.5, 22.1, 8.9, 24.2],
     "The letter J card", "show", "a jar of jam", False),
    ("Letter card K with a kite", [1.8, 25.4, 7.8, 27.8],
     "The letter K card", "show", "a yellow kite", False),
    ("Cloud decorations on the wall", [1.3, 0.8, 11.0, 11.5],
     "The paper clouds", "float", "along the top of the wall", True),
    ("Smiling cloud on the wall", [4.1, 1.9, 6.6, 6.3],
     "The smiling cloud", "beam", "down at the class", False),
    ("Large green blackboard", [9.9, 3.0, 32.7, 23.9],
     "The green blackboard", "cover", "the front wall of the classroom", False),
    ("Sums written on the blackboard", [20.4, 4.2, 31.8, 8.1],
     "The sums", "wait", "to be worked out", True),
    ("Chalk question on the blackboard", [18.3, 8.9, 21.7, 16.2],
     "The chalk question", "ask", "everyone their name", False),
    ("Girl writing on the blackboard", [21.3, 12.6, 33.6, 16.2],
     "The girl at the blackboard", "write", "her name in chalk", False),
    ("Piece of chalk", [21.1, 15.5, 22.4, 16.3],
     "The piece of chalk", "squeak", "across the blackboard", False),
    ("Girl cleaning the blackboard", [17.1, 19.4, 31.8, 22.3],
     "The girl with the sponge", "wipe", "the blackboard clean", False),
    ("Yellow board sponge", [17.4, 17.4, 19.0, 18.9],
     "The yellow sponge", "rub", "the chalk marks away", False),
    ("Boy reaching up at the board", [17.4, 17.2, 30.8, 19.6],
     "The boy at the board", "stretch", "up to reach the top", False),
    ("Boy in a red top at a desk", [21.5, 24.3, 32.7, 27.3],
     "The boy at the desk", "work", "quietly on his own", False),
    ("Potted tree in the corner", [29.0, 0.4, 41.8, 3.8],
     "The potted tree", "stand", "in the corner of the room", False),

    # ---------- r0c1  x22-53 y0-36.3 ----------
    ("Letter card L with a frog", [2.5, 27.8, 8.2, 29.8],
     "The letter L card", "show", "a little green frog", False),
    ("Letter card M with a muffin", [2.7, 29.8, 8.2, 31.8],
     "The letter M card", "show", "a tasty muffin", False),
    ("Letter card N with a nail", [2.5, 31.8, 8.2, 33.8],
     "The letter N card", "show", "a shiny nail", False),
    ("Letter card O with an octopus", [2.2, 33.8, 8.2, 36.0],
     "The letter O card", "show", "a blue octopus", False),
    ("Letter card P with popcorn", [2.2, 35.8, 8.2, 38.0],
     "The letter P card", "show", "a box of popcorn", False),
    ("Letter card Q with a queen", [2.2, 37.8, 8.2, 40.0],
     "The letter Q card", "show", "a smiling queen", False),
    ("Letter card R with a robot", [1.8, 40.0, 8.2, 42.2],
     "The letter R card", "show", "a little robot", False),
    ("Letter card S with a sun", [2.0, 42.0, 8.2, 44.2],
     "The letter S card", "show", "a bright yellow sun", False),
    ("Letter card T with a tiger", [2.2, 44.0, 8.2, 46.2],
     "The letter T card", "show", "a striped tiger", False),
    ("Toy train at the end of the frieze", [5.0, 46.1, 8.5, 48.2],
     "The second toy train", "chug", "along the end of the frieze", False),
    ("Second alphabet row on the wall", [9.2, 28.5, 14.1, 45.1],
     "The second row of letters", "carry", "on from U to Z", False),
    ("Letter card U with an umbrella", [9.7, 31.5, 13.8, 33.5],
     "The letter U card", "show", "a blue umbrella", False),
    ("Letter card V with a volcano", [9.4, 33.5, 13.8, 35.7],
     "The letter V card", "show", "an erupting volcano", False),
    ("Letter card W with a whale", [9.9, 35.5, 13.8, 37.7],
     "The letter W card", "show", "a spouting whale", False),
    ("Letter card X with a xylophone", [10.1, 37.5, 13.8, 39.7],
     "The letter X card", "show", "a coloured xylophone", False),
    ("Letter card Y with yarn", [10.1, 39.6, 13.8, 41.8],
     "The letter Y card", "show", "a ball of yarn", False),
    ("Letter card Z with a zebra", [9.9, 41.8, 13.8, 44.0],
     "The letter Z card", "show", "a stripy zebra", False),
    ("Teacher in a purple cardigan", [15.5, 28.5, 31.8, 33.7],
     "The teacher", "lean", "over the children's work", False),
    ("Wooden group table", [24.6, 27.5, 32.7, 41.2],
     "The group table", "hold", "everybody's exercise books", False),
    ("Boy in a green top at the table", [19.0, 34.2, 26.2, 37.5],
     "The boy in the green top", "look", "up from his writing", False),
    ("Girl in a purple top at the table", [20.6, 39.5, 31.8, 43.1],
     "The girl in the purple top", "write", "carefully in her book", False),
    ("Boy in a red top at the table", [20.8, 24.5, 32.7, 28.0],
     "The boy in the red top", "read", "the page in front of him", False),
    ("Boy in blue dungarees at the table", [27.4, 31.5, 36.4, 35.4],
     "The boy in the dungarees", "colour", "in his picture", False),
    ("Exercise books on the table", [25.0, 27.6, 29.9, 39.7],
     "The exercise books", "lie", "open on the table", True),
    ("Pot of pencils on the table", [27.4, 30.1, 30.4, 31.7],
     "The pot of pencils", "stand", "in the middle of the table", False),
    ("Large globe on a stand", [19.7, 45.4, 32.7, 51.1],
     "The big globe", "spin", "slowly on its stand", False),
    ("Wooden globe table", [30.9, 45.4, 36.4, 50.8],
     "The globe table", "hold", "the heavy world globe", False),
    ("Girl beside the globe", [24.6, 51.1, 32.7, 53.0],
     "The girl at the globe", "search", "for her country", False),

    # ---------- r0c2  x47-78 y0-36.3 ----------
    ("Large classroom window", [0.4, 48.9, 20.5, 63.6],
     "The classroom window", "look", "out onto the playground", False),
    ("Solar system mobile", [2.5, 49.5, 18.2, 57.3],
     "The solar system mobile", "hang", "in front of the window", False),
    ("Yellow sun of the mobile", [2.9, 52.6, 7.8, 55.9],
     "The paper sun", "hang", "at the top of the mobile", False),
    ("Striped planet on the mobile", [6.9, 50.4, 9.6, 52.5],
     "The striped planet", "dangle", "from a piece of thread", False),
    ("Blue and green planet", [9.2, 52.0, 12.0, 54.0],
     "The blue planet", "turn", "gently in the draught", False),
    ("Red planet on the mobile", [9.0, 54.6, 11.7, 56.5],
     "The red planet", "swing", "beside the others", False),
    ("Ringed planet on the mobile", [12.2, 54.0, 15.0, 56.2],
     "The ringed planet", "hang", "below the red one", False),
    ("Dark blue planet", [15.3, 53.5, 17.8, 55.3],
     "The dark blue planet", "hang", "at the bottom of the mobile", False),
    ("Boy reading on the windowsill", [11.1, 55.8, 19.9, 62.5],
     "The boy on the windowsill", "read", "a book in the sunshine", False),
    ("Open book on the windowsill", [13.6, 57.7, 16.9, 60.2],
     "The open book", "rest", "on the boy's knees", False),
    ("Glass door to the playground", [1.1, 64.5, 25.2, 71.9],
     "The glass door", "lead", "out to the playground", False),
    ("Handle of the glass door", [14.1, 64.8, 15.5, 66.1],
     "The door handle", "wait", "for someone to turn it", False),
    ("Bird flying past the door", [7.1, 66.5, 10.1, 69.6],
     "The flying bird", "swoop", "past the glass door", False),
    ("Birds splashing in a puddle", [13.2, 65.9, 15.5, 71.5],
     "The birds", "splash", "in the shallow puddle", True),
    ("Puddle in the playground", [14.8, 65.9, 18.2, 70.1],
     "The puddle", "shine", "on the wet playground", False),
    ("Seesaw in the playground", [5.5, 57.8, 8.0, 62.5],
     "The seesaw", "sit", "empty in the playground", False),
    ("Girl spinning the globe", [23.6, 50.9, 34.8, 54.3],
     "The girl at the globe", "spin", "the world around", False),
    ("Toy pedal car", [22.0, 58.9, 32.7, 67.3],
     "The toy pedal car", "roll", "across the classroom floor", False),
    ("Steering wheel of the pedal car", [22.7, 62.6, 25.5, 64.5],
     "The steering wheel", "turn", "in the driver's hands", False),
    ("Front wheel of the pedal car", [26.7, 65.1, 29.4, 66.8],
     "The pedal car's wheel", "squeak", "as it turns", False),
    ("Girl driving the pedal car", [21.1, 59.5, 27.6, 63.1],
     "The girl in the pedal car", "steer", "around the classroom", False),
    ("Boy pushing the pedal car", [26.4, 55.1, 36.4, 61.3],
     "The pushing boy", "shove", "the car from behind", False),
    ("Big smiling robot model", [17.4, 73.6, 32.7, 78.0],
     "The big robot", "grin", "at the whole class", False),
    ("Robot's eye stalk", [17.4, 73.9, 19.9, 75.3],
     "The robot's eye", "wobble", "on its long stalk", False),
    ("Robot's grinning mouth", [22.7, 74.8, 24.5, 77.3],
     "The robot's mouth", "smile", "from ear to ear", False),
    ("Purple glove on a spring", [24.6, 70.7, 26.9, 72.4],
     "The springy glove", "bounce", "out from the robot", False),
    ("Boy making things at a table", [28.5, 65.9, 36.4, 70.1],
     "The boy in the striped top", "build", "something at the table", False),

    # ---------- r0c3  x72-100 y0-36.3 ----------
    ("Playground window", [0.4, 77.3, 29.0, 100.0],
     "The big window", "show", "the whole playground outside", False),
    ("Swing frame in the playground", [2.5, 78.4, 12.9, 88.1],
     "The swing frame", "stand", "in the middle of the playground", False),
    ("Red swing seat", [10.4, 80.7, 11.7, 82.3],
     "The red swing", "hang", "empty in the rain", False),
    ("Round nest swing", [9.4, 83.8, 12.0, 86.6],
     "The nest swing", "sway", "slowly in the wind", False),
    ("Climbing ladder on the swing frame", [8.3, 78.5, 12.7, 80.1],
     "The climbing ladder", "lead", "up the side of the frame", False),
    ("Sandpit in the playground", [14.1, 80.4, 20.3, 90.9],
     "The sandpit", "wait", "for the rain to stop", False),
    ("Sandcastle in the sandpit", [14.1, 84.2, 18.2, 86.4],
     "The sandcastle", "stand", "in the middle of the sandpit", False),
    ("Toy car in the playground", [14.1, 78.4, 16.4, 81.3],
     "The toy car", "sit", "on the wet grass", False),
    ("Rainbow stuck on the window", [9.4, 90.1, 14.1, 97.7],
     "The paper rainbow", "arch", "across the window", False),
    ("Sun sticker on the glass", [4.1, 92.7, 7.8, 95.2],
     "The paper sun", "shine", "on the window glass", False),
    ("Cloud sticker on the glass", [11.3, 88.8, 13.6, 92.3],
     "The paper cloud", "float", "under the rainbow", False),
    ("Second cloud sticker", [14.6, 94.1, 16.9, 98.7],
     "The second paper cloud", "sit", "at the end of the rainbow", False),
    ("Boy with a blue cap by the robot", [26.9, 80.1, 36.4, 84.7],
     "The boy in the blue cap", "watch", "the robot closely", False),
    ("Blue cap", [26.9, 82.4, 29.0, 84.4],
     "The blue cap", "sit", "backwards on the boy's head", False),
    ("Boy sticking suns on the window", [20.1, 86.1, 36.4, 92.1],
     "The boy at the window", "stick", "paper suns on the glass", False),
    ("Paper sun cut-out in his hand", [20.4, 91.6, 23.6, 94.0],
     "The paper sun cut-out", "wait", "to be stuck on the glass", False),
    ("Boy kneeling on the windowsill", [18.5, 94.5, 29.0, 98.0],
     "The kneeling boy", "reach", "up to the top of the window", False),
    ("Large sun cut-out on the wall", [9.4, 97.9, 13.6, 100.0],
     "The big paper sun", "brighten", "the rainy day", False),

    # ---------- r1c0  x0-28 y30.3-69.7 ----------
    ("Shelf of jars on the wall", [34.6, 4.4, 39.5, 8.3],
     "The shelf of jars", "hold", "the classroom paints", False),
    ("Girl typing on a typewriter", [42.1, 3.1, 54.7, 6.7],
     "The girl at the typewriter", "type", "a letter to her friend", False),
    ("Girl in a flowered top watching", [42.8, 6.5, 55.4, 10.3],
     "The girl in the flowered top", "watch", "her friend typing", False),
    ("Red typewriter", [46.8, 1.0, 50.5, 5.2],
     "The red typewriter", "clatter", "as the keys go down", False),
    ("Wooden desk with the typewriter", [49.6, 0.0, 54.7, 7.4],
     "The wooden desk", "stand", "against the classroom wall", False),
    ("Boy in an orange top painting", [35.3, 12.3, 47.2, 16.8],
     "The boy in the orange top", "paint", "a picture at the table", False),
    ("Boy in a white apron at the craft table", [34.6, 20.3, 44.4, 25.4],
     "The boy in the apron", "squeeze", "paint onto his paper", False),
    ("Round craft table", [39.3, 13.5, 51.0, 27.3],
     "The craft table", "hold", "all the paints and brushes", False),
    ("Tray of paints on the table", [39.8, 17.7, 43.3, 20.5],
     "The tray of paints", "sit", "in the middle of the table", False),
    ("Jar of water on the table", [43.1, 21.2, 45.4, 22.7],
     "The jar of water", "hold", "the dirty paintbrushes", False),
    ("Painted sheet of paper", [40.7, 15.0, 43.3, 18.0],
     "The painted paper", "dry", "on the table top", False),
    ("Foam letter Z on the floor", [47.5, 15.7, 49.6, 17.7],
     "The foam letter Z", "lie", "forgotten on the floor", False),
    ("Foam letter F on paper", [47.5, 20.9, 50.0, 23.0],
     "The foam letter F", "rest", "on a sheet of paper", False),
    ("Foam letter P on paper", [50.5, 21.2, 52.8, 23.1],
     "The foam letter P", "sit", "beside the other letters", False),
    ("Boy lying on a beanbag", [50.1, 10.4, 60.8, 22.3],
     "The boy on the beanbag", "flick", "through his picture cards", False),
    ("Yellow star beanbag", [55.0, 12.6, 60.8, 19.3],
     "The star beanbag", "squash", "under the boy's weight", False),
    ("Picture card in his hands", [52.2, 13.0, 54.7, 15.2],
     "The picture card", "show", "a bright cartoon picture", False),
    ("Spider plant in a purple pot", [56.9, 1.9, 65.2, 6.0],
     "The spider plant", "spill", "over the side of its pot", False),
    ("Low display shelf", [60.6, 0.0, 69.8, 28.0],
     "The display shelf", "run", "along the classroom wall", False),
    ("Blue marble on the floor", [54.7, 1.3, 56.1, 2.3],
     "The blue marble", "roll", "across the wooden floor", False),

    # ---------- r1c1  x22-53 y30.3-69.7 ----------
    ("Boy in a light blue top painting", [37.4, 26.7, 48.6, 30.7],
     "The boy in the blue top", "dip", "his brush into the paint", False),
    ("Boy with his arms out", [40.7, 30.7, 53.8, 38.6],
     "The boy in the green top", "stretch", "his arms out wide", False),
    ("Girl with her arms in the air", [41.4, 39.0, 53.8, 45.2],
     "The girl in the yellow top", "reach", "both arms into the air", False),
    ("Girl bending over on the floor", [44.5, 44.3, 54.0, 50.3],
     "The girl in the striped top", "bend", "right down to the floor", False),
    ("Boy on a chair at the table", [27.4, 31.3, 38.1, 36.4],
     "The boy on the chair", "kneel", "up to reach his work", False),
    ("Red wavy ribbon on the floor", [50.8, 24.5, 52.8, 27.8],
     "The wavy ribbon", "curl", "across the classroom floor", False),
    ("Toy car on the classroom floor", [39.8, 49.4, 42.1, 51.4],
     "The little toy car", "wait", "on the wooden floor", False),
    ("Shelf of puppets", [54.5, 30.4, 65.9, 41.2],
     "The shelf of puppets", "stand", "ready for the next show", False),
    ("Prince puppet in a crown", [58.9, 30.7, 65.5, 33.0],
     "The prince puppet", "wait", "at the end of the shelf", False),
    ("King puppet in a red robe", [55.7, 32.8, 65.0, 35.5],
     "The king puppet", "stand", "in his bright red robe", False),
    ("Wolf puppet", [54.7, 35.0, 63.1, 37.2],
     "The wolf puppet", "grin", "at the other puppets", False),
    ("Pink pig puppet", [58.2, 35.9, 64.5, 38.6],
     "The pig puppet", "sit", "beside the wolf", False),
    ("Girl puppet in a red hat", [55.2, 37.9, 64.0, 40.6],
     "The girl puppet", "wear", "a bright red hood", False),
    ("Wooden bookshelf", [63.8, 29.0, 69.8, 42.5],
     "The bookshelf", "hold", "rows of picture books", False),
    ("Row of books on the shelf", [66.4, 31.5, 69.8, 34.1],
     "The books", "stand", "neatly side by side", True),
    ("Open picture book on the shelf", [66.6, 34.1, 69.8, 38.8],
     "The open picture book", "show", "a big colourful drawing", False),
    ("Red puppet theatre", [58.2, 42.3, 69.8, 53.0],
     "The puppet theatre", "stand", "at the back of the room", False),

    # ---------- r1c2  x47-78 y30.3-69.7 ----------
    ("Girl looking through a microscope", [37.2, 59.2, 45.8, 63.5],
     "The girl at the microscope", "peer", "down at a tiny leaf", False),
    ("Microscope on the science bench", [40.9, 56.5, 45.4, 59.7],
     "The microscope", "stand", "on the science bench", False),
    ("Long science bench", [44.2, 50.6, 51.4, 65.8],
     "The science bench", "hold", "the class experiments", False),
    ("Petri dishes on the bench", [44.5, 52.3, 45.8, 55.1],
     "The petri dishes", "sit", "in a neat row", True),
    ("Jar on the bench shelf", [48.2, 62.3, 49.8, 63.8],
     "The glass jar", "stand", "under the science bench", False),
    ("Boy at the modelling table", [28.5, 65.1, 40.0, 70.1],
     "The boy at the modelling table", "shape", "a lump of clay", False),
    ("Tray of coloured beads", [31.4, 73.6, 34.6, 76.7],
     "The tray of beads", "sparkle", "on the craft table", False),
    ("Stack of paper on the table", [35.3, 71.3, 37.2, 74.2],
     "The stack of paper", "wait", "to be drawn on", False),
    ("Painted picture drying on the floor", [53.3, 52.1, 57.0, 57.9],
     "The painted picture", "dry", "on the classroom floor", False),
    ("Second painted picture on the floor", [51.5, 58.0, 54.9, 63.9],
     "The second painting", "lie", "flat on the floor", False),
    ("Boy in a blue hat on the floor", [56.4, 57.1, 65.9, 60.4],
     "The boy in the blue hat", "sit", "cross legged on the floor", False),
    ("Blue hat", [56.4, 57.4, 58.7, 59.7],
     "The blue hat", "flop", "over the boy's forehead", False),
    ("Boy running across the classroom", [53.3, 64.0, 66.8, 72.1],
     "The running boy", "dash", "towards the hopscotch mat", False),
    ("Number wall with counting shapes", [46.1, 72.0, 66.8, 100.0],
     "The number wall", "teach", "the numbers one to ten", False),
    ("Red cone on the number wall", [45.9, 71.4, 48.9, 73.5],
     "The red cone", "sit", "on top of the number wall", False),
    ("Red cube on the number wall", [47.0, 74.7, 49.6, 76.9],
     "The red cube", "stand", "beside the cone", False),
    ("Number one on the wall", [50.3, 71.6, 52.6, 72.7],
     "The number one", "start", "the counting row", False),
    ("Number two on the wall", [50.3, 73.7, 52.6, 74.9],
     "The number two", "come", "after the number one", False),
    ("Number three on the wall", [50.8, 75.7, 53.3, 76.9],
     "The number three", "sit", "next to the number two", False),
    ("Hopscotch mat on the floor", [64.3, 62.3, 73.8, 78.0],
     "The hopscotch mat", "stretch", "across the classroom floor", False),
    ("Next show sign on the theatre", [63.8, 49.2, 67.8, 52.5],
     "The next show sign", "announce", "the coming puppet play", False),
    ("Clock on the puppet theatre", [67.5, 49.4, 72.2, 52.5],
     "The clock", "show", "the time of the next show", False),

    # ---------- r1c3  x72-100 y30.3-69.7 ----------
    ("Basket of building blocks", [40.2, 76.5, 46.8, 82.7],
     "The basket of blocks", "wait", "beside the craft table", False),
    ("Round craft table with paper", [40.9, 84.5, 49.1, 99.2],
     "The round craft table", "hold", "a long roll of paper", False),
    ("Roll of paper on the table", [40.9, 87.0, 44.9, 93.0],
     "The roll of paper", "unroll", "across the table", False),
    ("Sheet of paper being cut", [41.2, 92.1, 44.0, 96.4],
     "The sheet of paper", "curl", "under the scissors", False),
    ("Glue pot on the craft table", [42.1, 86.1, 44.0, 87.5],
     "The glue pot", "stand", "open on the table", False),
    ("Scissors on the craft table", [40.0, 88.7, 42.6, 89.8],
     "The scissors", "lie", "ready on the table", True),
    ("Girl cutting out paper", [35.8, 95.3, 47.2, 99.2],
     "The girl with the scissors", "cut", "carefully along the line", False),
    ("Yellow sphere on the number wall", [48.2, 78.2, 51.0, 80.6],
     "The yellow sphere", "sit", "on the number wall", False),
    ("Green cylinder on the number wall", [47.5, 81.4, 52.4, 83.2],
     "The green cylinder", "stand", "upright on the wall", False),
    ("Blue pyramid on the number wall", [50.8, 83.9, 53.8, 86.7],
     "The blue pyramid", "point", "up towards the ceiling", False),
    ("Number four with counters", [52.4, 78.1, 61.7, 79.8],
     "The number four", "sit", "above four round counters", False),
    ("Number five with yellow bars", [53.1, 80.2, 62.2, 82.3],
     "The number five", "count", "five yellow bars", False),
    ("Number six with green shapes", [54.5, 82.8, 65.0, 85.3],
     "The number six", "count", "six green shapes", False),
    ("Number seven with green bars", [55.2, 85.8, 67.3, 88.1],
     "The number seven", "count", "seven green bars", False),
    ("Number eight with counters", [56.1, 88.7, 68.3, 90.6],
     "The number eight", "count", "eight round counters", False),
    ("Number nine with red squares", [57.3, 91.8, 66.8, 94.3],
     "The number nine", "count", "nine red squares", False),
    ("Number ten with counters", [58.9, 95.2, 66.4, 97.7],
     "The number ten", "finish", "the counting row", False),
    ("Purple toy snake", [52.6, 86.8, 58.4, 99.2],
     "The toy snake", "wind", "along the top of the wall", False),
    ("Orange toy car on the floor", [49.4, 91.6, 51.9, 94.3],
     "The orange toy car", "sit", "on the classroom floor", False),

    # ---------- r2c0  x0-28 y63.7-100 ----------
    ("Story picture of a girl in a meadow", [64.3, 0.5, 73.1, 6.0],
     "The first story picture", "show", "a girl walking in a meadow", False),
    ("Story picture with a fir tree", [64.1, 6.5, 72.8, 11.5],
     "The second story picture", "show", "a dark forest", False),
    ("Story picture with a wolf", [63.8, 11.8, 72.6, 16.9],
     "The third story picture", "show", "the wolf meeting the girl", False),
    ("Story picture with grandmother", [63.6, 17.4, 72.4, 22.5],
     "The fourth story picture", "show", "the wolf and the grandmother", False),
    ("Story picture of the wolf running", [63.6, 22.9, 72.2, 27.8],
     "The last story picture", "show", "the wolf running away", False),
    ("Model fir tree on the shelf", [72.2, 10.9, 74.3, 12.3],
     "The model fir tree", "stand", "on the display shelf", False),
    ("Model of Red Riding Hood", [71.5, 12.6, 74.0, 14.0],
     "The little model girl", "stand", "beside the model tree", False),
    ("Toy grandmother in bed", [72.0, 15.2, 73.8, 17.9],
     "The toy grandmother", "lie", "tucked up in bed", False),
    ("Toy wolf on the shelf", [70.8, 20.3, 72.8, 22.3],
     "The toy wolf", "crouch", "on the display shelf", False),
    ("Model gingerbread house", [70.1, 24.2, 72.6, 26.5],
     "The gingerbread house", "sit", "at the end of the shelf", False),
    ("Teacher telling a story", [73.6, 0.5, 88.4, 10.0],
     "The story teacher", "kneel", "down to tell the story", False),
    ("Big picture book on a stand", [77.8, 10.4, 87.5, 19.0],
     "The big picture book", "stand", "open on its easel", False),
    ("Girl in a spotted dress listening", [74.3, 19.1, 84.2, 24.2],
     "The girl in the spotted dress", "put", "her hand up to answer", False),
    ("Blue floor cushion", [79.8, 18.9, 84.0, 26.5],
     "The floor cushion", "keep", "the children comfortable", False),
    ("Girl lying with a toy dog", [90.1, 4.1, 96.3, 14.3],
     "The girl on the floor", "cuddle", "her soft toy dog", False),
    ("Toy dog", [92.6, 10.4, 96.0, 14.3],
     "The toy dog", "lie", "under the girl's arm", False),
    ("Boy in a striped top listening", [87.0, 17.2, 96.3, 21.4],
     "The boy in the striped top", "listen", "to the story", False),
    ("Girl in a yellow top listening", [86.1, 21.7, 96.3, 26.7],
     "The girl in the yellow top", "sit", "quietly on the floor", False),

    # ---------- r2c1  x22-53 y63.7-100 ----------
    ("Bookshelf behind the story corner", [66.2, 30.4, 72.6, 42.5],
     "The bookshelf", "stand", "behind the story corner", False),
    ("Row of green books", [66.9, 30.4, 71.4, 34.1],
     "The green books", "line", "up on the shelf", True),
    ("Puppet stage with a crocodile", [64.3, 42.9, 72.6, 48.5],
     "The puppet stage", "show", "a green crocodile puppet", False),
    ("Boy playing with a baby doll", [75.2, 27.8, 90.7, 34.7],
     "The boy with the doll", "rock", "the baby doll gently", False),
    ("Baby doll", [81.9, 27.6, 87.9, 32.3],
     "The baby doll", "lie", "in the boy's arms", False),
    ("Blue cushion on the floor", [88.0, 28.1, 92.3, 33.2],
     "The blue cushion", "sit", "under the boy", False),
    ("Girl in a purple top on the floor", [72.0, 35.9, 81.9, 40.0],
     "The girl in the purple top", "sit", "back on the floor", False),
    ("Boy in a yellow top pointing", [72.9, 39.8, 82.4, 45.6],
     "The boy in the yellow top", "point", "across the classroom", False),
    ("Boy with a paper crown", [82.8, 35.5, 96.3, 42.8],
     "The boy in the crown", "gallop", "on his hobby horse", False),
    ("Paper crown", [82.8, 37.0, 85.1, 39.7],
     "The paper crown", "sit", "crooked on his head", False),
    ("Hobby horse head", [86.8, 39.5, 91.2, 42.8],
     "The hobby horse", "bob", "along beside the boy", False),
    ("Girl in a red hat with a dragon", [84.3, 43.5, 96.3, 50.0],
     "The girl in the red hat", "play", "with a dragon puppet", False),
    ("Green dragon puppet", [86.6, 43.5, 92.6, 48.6],
     "The dragon puppet", "open", "its wide green mouth", False),
    ("Star wand on the floor", [96.3, 48.6, 98.4, 50.3],
     "The star wand", "lie", "dropped on the floor", False),

    # ---------- r2c2  x47-78 y63.7-100 ----------
    ("Girl behind the puppet theatre", [66.4, 52.6, 79.1, 57.0],
     "The girl behind the theatre", "peep", "round the puppet stage", False),
    ("Dressing up rail on wheels", [80.8, 51.5, 97.2, 65.0],
     "The dressing up rail", "hold", "all the costumes", False),
    ("Purple wizard hat", [75.9, 59.5, 79.8, 61.6],
     "The wizard hat", "curl", "over at the tip", False),
    ("Yellow crown on the rail", [78.0, 61.1, 81.0, 63.1],
     "The golden crown", "wait", "for a king or queen", False),
    ("Green top hat", [76.9, 57.8, 81.0, 59.7],
     "The green top hat", "stand", "on the top shelf", False),
    ("Brown cowboy hat", [78.7, 54.9, 81.4, 57.9],
     "The cowboy hat", "sit", "beside the other hats", False),
    ("Purple witch hat", [77.1, 52.6, 81.9, 55.0],
     "The witch hat", "lean", "against the rail", False),
    ("Pink dress on the rail", [84.7, 52.6, 92.6, 55.7],
     "The pink dress", "hang", "from the costume rail", False),
    ("Rainbow striped top", [85.6, 55.4, 89.8, 57.7],
     "The striped top", "hang", "next to the pink dress", False),
    ("Blue dungarees on the rail", [85.9, 57.4, 91.7, 59.4],
     "The blue dungarees", "dangle", "from a wooden hanger", True),
    ("Teddy bear costume", [83.6, 59.7, 92.1, 62.5],
     "The bear costume", "hang", "in the middle of the rail", False),
    ("Purple flower garland", [83.3, 62.3, 94.4, 64.7],
     "The flower garland", "trail", "down from the rail", False),
    ("Green shoes on the bottom shelf", [93.3, 53.1, 95.4, 55.1],
     "The green shoes", "sit", "on the bottom shelf", True),
    ("Brown boots on the shelf", [92.8, 55.4, 95.4, 57.6],
     "The brown boots", "stand", "side by side", True),
    ("Yellow shoes on the shelf", [93.5, 57.8, 95.4, 60.1],
     "The yellow shoes", "wait", "for someone to try them on", True),
    ("Green party hat on the floor", [92.4, 64.6, 95.8, 66.4],
     "The party hat", "lie", "on its side on the floor", False),
    ("Marbles scattered on the floor", [70.3, 58.8, 80.5, 73.9],
     "The marbles", "scatter", "across the classroom floor", True),
    ("Glass jar full of marbles", [81.0, 74.4, 87.0, 78.0],
     "The jar of marbles", "stand", "beside the fish tank", False),

    # ---------- r2c3  x72-100 y63.7-100 ----------
    ("Boy sorting coloured shapes", [70.1, 85.9, 79.1, 92.4],
     "The boy sorting shapes", "sort", "the shapes into groups", False),
    ("Girl playing with shapes", [67.8, 94.5, 79.1, 99.2],
     "The girl with the shapes", "hold", "up a yellow bar", False),
    ("Coloured plastic shapes on the floor", [76.4, 85.5, 82.8, 100.0],
     "The plastic shapes", "spread", "out across the floor", True),
    ("Red circle counter", [76.6, 92.1, 78.4, 93.4],
     "The red circle", "lie", "among the other shapes", False),
    ("Green rectangle counter", [80.3, 85.5, 81.9, 87.5],
     "The green rectangle", "sit", "beside the yellow bars", False),
    ("Yellow bar counter", [81.0, 90.8, 82.6, 94.3],
     "The yellow bar", "stretch", "across the floor", False),
    ("Aquarium in the classroom", [88.4, 72.0, 95.4, 87.2],
     "The fish tank", "bubble", "quietly in the corner", False),
    ("Toy diver in the fish tank", [89.8, 79.9, 91.6, 82.3],
     "The toy diver", "float", "inside the fish tank", False),
    ("Green turtle in the fish tank", [89.8, 77.0, 91.4, 79.0],
     "The little turtle", "swim", "along the bottom of the tank", False),
    ("Paper boat above the tank", [86.3, 83.3, 88.9, 86.7],
     "The paper boat", "hover", "above the water", False),
    ("Boy floating a paper boat", [85.4, 87.0, 100.0, 92.4],
     "The boy with the paper boat", "lower", "his boat onto the water", False),
    ("Boy carrying a wooden tray", [83.6, 92.2, 100.0, 99.2],
     "The boy with the tray", "carry", "a tray across the classroom", False),
    ("Wooden tray of things", [91.9, 92.4, 94.2, 95.4],
     "The wooden tray", "hold", "shells and pebbles", False),
    ("Cabinet under the fish tank", [93.3, 72.0, 100.0, 91.8],
     "The wooden cabinet", "support", "the heavy fish tank", False),
    ("Shells and stones on the cabinet", [91.0, 72.5, 94.9, 81.0],
     "The shells and stones", "lie", "in a row on the cabinet", True),
]
