# Page 5 - "Building the New House": a cutaway house under construction, with a
# playground on the left, a crane and conservatory on the right, and a closed
# street across the bottom.
# Boxes read off the 12 tile grids produced by tiler.py (page percentages).
# (name, [ymin, xmin, ymax, xmax], subject, bare-infinitive verb, rest, plural)

P = [
    # --- top left: sky, hills, the timber lorry, the playground fence ---
    ("White cloud", [1.7, 1.7, 4.6, 7.9], "The white cloud", "float", "above the green hills", False),
    ("Green hill", [7.5, 0.0, 15.5, 9.5], "The green hill", "rise", "behind the building site", False),
    ("Bundle of wooden beams", [8.0, 6.7, 16.1, 18.1], "The bundle of wooden beams", "lie", "on the old pickup truck", False),
    ("Blue pickup truck", [14.7, 7.0, 20.9, 17.8], "The blue pickup truck", "carry", "long wooden beams to the site", False),
    ("Front wheel of the truck", [18.0, 15.2, 21.0, 17.7], "The front wheel of the truck", "turn", "on the country road", False),
    ("Rear wheel of the truck", [18.0, 8.3, 21.1, 10.7], "The rear wheel of the truck", "roll", "along the country road", False),
    ("Small white house", [12.6, 17.4, 15.4, 20.2], "The small white house", "stand", "beside the country road", False),
    ("Timber house frame", [10.1, 19.6, 15.3, 26.2], "The timber house frame", "wait", "for its new roof", False),
    ("Country road", [20.4, 0.0, 22.3, 25.0], "The country road", "run", "past the building site", False),
    ("Green bush", [18.4, 3.2, 26.0, 6.8], "The green bush", "grow", "beside the road", False),
    ("Boy in a red cap", [25.2, 7.2, 33.3, 10.8], "The boy in the red cap", "climb", "on the wooden frame", False),
    ("Wooden swing frame", [28.7, 5.2, 35.1, 12.1], "The wooden swing frame", "stand", "on the playground grass", False),
    ("Man in a striped shirt", [22.6, 14.3, 31.5, 17.0], "The man in the striped shirt", "watch", "the children at play", False),
    ("Little child in blue", [26.1, 16.1, 31.6, 18.0], "The little child in blue", "hold", "on to the yellow barrier", False),
    ("Builder in a yellow helmet", [23.8, 19.5, 32.4, 22.4], "The builder in the yellow helmet", "stand", "beside the safety barrier", False),
    ("Striped safety barrier", [26.8, 13.9, 28.8, 19.9], "The striped safety barrier", "block", "the way to the site", False),
    ("Tall green bush", [22.0, 22.3, 32.0, 25.1], "The tall green bush", "hide", "the edge of the field", False),

    # --- top middle left: village, crane, the blue front of the house ---
    ("Tall yellow crane", [5.7, 22.2, 15.5, 30.2], "The tall yellow crane", "stand", "above the old rooftops", False),
    ("Church tower", [5.8, 32.3, 15.3, 35.3], "The church tower", "rise", "above the village", False),
    ("Big green hill", [8.4, 27.1, 15.9, 43.6], "The big green hill", "roll", "behind the village", False),
    ("Red village rooftops", [13.2, 27.0, 16.2, 41.1], "The red village rooftops", "shine", "in the morning sun", True),
    ("Round green tree", [9.8, 35.2, 13.4, 37.4], "The round green tree", "grow", "next to the church", False),
    ("Red tiled roof", [8.0, 43.4, 16.2, 52.9], "The red tiled roof", "cover", "the top of the new house", False),
    ("Blue wooden house", [16.5, 29.0, 35.5, 39.3], "The blue wooden house", "wait", "for its new owners", False),
    ("Wooden front door", [22.1, 31.7, 33.4, 36.2], "The wooden front door", "open", "on to the balcony", False),
    ("Round window", [20.8, 32.9, 22.2, 34.3], "The round window", "let", "light into the hallway", False),
    ("Man in white overalls", [20.0, 41.7, 29.6, 44.8], "The man in the white overalls", "blow", "insulation into the roof", False),
    ("Man in a green shirt", [23.0, 45.2, 32.4, 47.9], "The man in the green shirt", "hold", "a wooden board in place", False),
    ("Cloud of insulation", [19.6, 44.3, 24.1, 49.1], "The cloud of insulation", "puff", "out of the thick hose", False),
    ("Thick grey hose", [23.0, 39.8, 29.6, 43.0], "The thick grey hose", "snake", "across the wooden floor", False),
    ("Wooden roof rafters", [16.4, 35.1, 20.8, 43.6], "The wooden roof rafters", "hold", "up the heavy roof", True),
    ("Brick chimney wall", [22.1, 46.5, 33.4, 50.0], "The brick chimney wall", "run", "up through the house", False),
    ("Scaffold plank", [28.6, 40.3, 30.5, 46.7], "The scaffold plank", "carry", "the two workmen", False),
    ("Balcony railing", [29.1, 26.7, 33.4, 36.2], "The balcony railing", "protect", "the workers on the balcony", False),
    ("Green hedge", [18.4, 23.6, 30.5, 30.0], "The green hedge", "grow", "along the garden fence", False),

    # --- top middle right: the roof, the attic and the upstairs rooms ---
    ("Roofer in a yellow helmet", [4.2, 47.7, 12.2, 53.6], "The roofer in the yellow helmet", "fit", "solar panels on the roof", False),
    ("Solar panels", [7.5, 47.6, 14.8, 57.9], "The solar panels", "sit", "on the red roof", True),
    ("Red roof tiles", [6.3, 46.9, 15.9, 62.4], "The red roof tiles", "cover", "the front of the roof", True),
    ("Hot air balloon", [4.0, 68.4, 8.7, 70.1], "The hot air balloon", "drift", "across the blue sky", False),
    ("Man with insulation", [10.5, 60.4, 16.4, 64.3], "The man with the insulation", "push", "soft wool between the beams", False),
    ("Wooden roof frame", [6.8, 58.5, 16.6, 73.5], "The wooden roof frame", "hold", "the whole roof together", False),
    ("Little black spider", [18.3, 50.3, 19.4, 51.2], "The little black spider", "hang", "from the attic wall", False),
    ("Brick gable wall", [19.7, 52.3, 33.4, 57.8], "The brick gable wall", "divide", "the two upstairs rooms", False),
    ("Man in yellow trousers", [25.0, 52.8, 33.4, 55.2], "The man in the yellow trousers", "sort", "the tiles on the floor", False),
    ("Man in a white shirt", [22.5, 50.6, 32.4, 52.4], "The man in the white shirt", "stand", "in the narrow doorway", False),
    ("Stack of blue tiles", [29.9, 54.7, 33.4, 57.2], "The stack of blue tiles", "wait", "on the wooden floor", False),
    ("Grey bucket", [29.0, 55.3, 32.0, 57.2], "The grey bucket", "hold", "the workman's tools", False),
    ("Man with a radiator", [22.0, 62.4, 33.4, 65.5], "The man with the radiator", "carry", "a heavy radiator across the room", False),
    ("White radiator", [25.0, 62.4, 29.6, 67.7], "The white radiator", "wait", "for its place on the wall", False),
    ("Workman bending over", [23.2, 59.6, 32.4, 62.4], "The workman bending over", "lift", "the second radiator", False),
    ("Grey wooden door", [19.7, 62.4, 29.6, 66.1], "The grey wooden door", "lead", "into the next room", False),
    ("Red toolbox", [30.2, 65.9, 33.1, 68.6], "The red toolbox", "sit", "on the dusty floor", False),
    ("Man in blue overalls", [23.0, 69.8, 33.4, 73.4], "The man in the blue overalls", "carry", "a big plasterboard panel", False),
    ("Plasterboard panel", [19.9, 68.1, 30.5, 72.9], "The plasterboard panel", "lean", "against the workman's shoulder", False),

    # --- top right: the crane, the hills and the scaffold ---
    ("Yellow crane jib", [4.2, 72.4, 8.8, 97.1], "The yellow crane jib", "reach", "across the building site", False),
    ("Crane tower", [8.5, 90.9, 33.4, 94.2], "The crane tower", "stand", "beside the new house", False),
    ("Crane hook", [14.1, 82.3, 19.4, 84.0], "The crane hook", "hang", "over the garden", False),
    ("Crane cables", [8.5, 82.4, 14.8, 84.0], "The crane cables", "hold", "the heavy hook", True),
    ("Rolling green hills", [11.3, 72.0, 18.5, 100.0], "The rolling green hills", "stretch", "into the distance", True),
    ("House with a red roof", [14.6, 75.2, 19.0, 79.7], "The house with the red roof", "sit", "among the green fields", False),
    ("Farmhouse", [16.2, 88.0, 19.9, 91.1], "The farmhouse", "stand", "beside the quiet lane", False),
    ("Small red barn", [16.4, 93.1, 18.5, 94.8], "The small red barn", "stand", "at the edge of the field", False),
    ("Big dark tree", [13.6, 80.0, 22.2, 83.1], "The big dark tree", "grow", "in the middle of the meadow", False),
    ("Builder waving", [23.2, 80.3, 33.4, 82.9], "The builder waving", "signal", "to the crane driver", False),
    ("Scaffold platform", [27.6, 79.7, 29.6, 86.2], "The scaffold platform", "hold", "the builder above the ground", False),
    ("Scaffold poles", [28.5, 80.6, 34.5, 85.9], "The scaffold poles", "hold", "up the wooden platform", True),
    ("Blue electric drill", [30.6, 75.3, 32.4, 77.1], "The blue electric drill", "lie", "on the bare floor", False),
    ("Builder's bucket", [31.1, 84.6, 33.1, 85.9], "The builder's bucket", "stand", "on the scaffold", False),
    ("White country lane", [20.4, 79.5, 21.8, 100.0], "The white country lane", "wind", "past the little houses", False),
    ("Garden bushes", [22.0, 85.4, 34.3, 91.1], "The garden bushes", "grow", "beside the crane", True),
    ("Flowering shrub", [22.0, 95.2, 33.4, 100.0], "The flowering shrub", "bloom", "at the edge of the garden", False),
    # --- middle left: the playground, the tractor and the new slide ---
    ("Red tractor", [50.4, 2.7, 59.4, 13.9], "The red tractor", "lift", "the new slide into place", False),
    ("Farmer in a white hat", [45.3, 6.0, 52.0, 9.0], "The farmer in the white hat", "drive", "the old red tractor", False),
    ("Big blue slide", [44.0, 6.0, 57.6, 19.2], "The big blue slide", "hang", "from the tractor's arm", False),
    ("Red crane arm", [41.2, 8.8, 53.4, 16.7], "The red crane arm", "swing", "the slide over the grass", False),
    ("Tractor's rear wheel", [51.3, 2.7, 59.4, 6.6], "The tractor's rear wheel", "sink", "into the soft grass", False),
    ("Tractor's front wheel", [55.7, 11.2, 59.4, 13.9], "The tractor's front wheel", "rest", "on the playground path", False),
    ("Tyre swing", [36.8, 6.7, 40.2, 11.0], "The tyre swing", "hang", "from the wooden beam", False),
    ("Wooden seesaw", [33.5, 14.0, 38.2, 22.3], "The wooden seesaw", "wait", "for two more children", False),
    ("Wooden playhouse", [44.5, 18.0, 51.5, 25.7], "The wooden playhouse", "stand", "in the corner of the playground", False),
    ("Red playhouse roof", [36.8, 18.0, 44.9, 25.7], "The red playhouse roof", "keep", "the rain off the children", False),
    ("Arched playhouse door", [45.8, 21.1, 51.0, 24.4], "The arched playhouse door", "open", "into the little house", False),
    ("Boy in orange trousers", [51.3, 16.0, 61.7, 19.2], "The boy in the orange trousers", "reach", "up to the playhouse", False),
    ("Round green bush", [44.0, 0.7, 56.1, 5.1], "The round green bush", "grow", "at the edge of the playground", False),
    ("Small fir tree", [60.4, 5.8, 67.1, 9.0], "The small fir tree", "wait", "to be planted", False),
    ("Young tree", [62.0, 12.3, 68.7, 16.7], "The young tree", "lie", "beside the fresh hole", False),
    ("Man in a red cap", [59.9, 18.8, 69.4, 22.3], "The man in the red cap", "dig", "a hole for the new tree", False),
    ("Bush by the steps", [52.3, 22.4, 58.9, 25.7], "The bush by the steps", "grow", "against the wooden stairs", False),

    # --- middle left of the house: stairs, kitchen and the plasterers ---
    ("Worker with a backpack", [36.8, 26.1, 46.9, 29.2], "The worker with the backpack", "climb", "the outside stairs", False),
    ("Upper wooden staircase", [33.5, 25.0, 48.8, 34.9], "The upper wooden staircase", "lead", "to the first floor", False),
    ("Lower wooden staircase", [45.0, 24.8, 63.6, 34.9], "The lower wooden staircase", "lead", "up from the garden", False),
    ("Man with a red board", [39.3, 32.3, 49.2, 35.6], "The man with the red board", "carry", "a red panel through the door", False),
    ("Red panel", [40.7, 32.7, 45.0, 35.9], "The red panel", "shine", "in the workman's hands", False),
    ("Oval window", [51.6, 32.7, 53.7, 34.7], "The oval window", "look", "out over the garden", False),
    ("Tan wooden door", [56.2, 34.6, 63.6, 36.3], "The tan wooden door", "stand", "at the back of the house", False),
    ("Man on a stepladder", [35.6, 42.2, 45.0, 45.4], "The man on the stepladder", "fix", "the kitchen wall", False),
    ("Kitchen stepladder", [43.5, 41.5, 49.7, 44.2], "The kitchen stepladder", "stand", "in front of the cooker", False),
    ("Cooker hood", [36.8, 46.8, 40.2, 49.4], "The cooker hood", "hang", "above the new cooker", False),
    ("Kitchen counter", [43.2, 40.0, 49.7, 49.8], "The kitchen counter", "run", "along the kitchen wall", False),
    ("Green power tool", [40.9, 45.2, 43.7, 47.0], "The green power tool", "sit", "on the kitchen counter", False),
    ("Red wall cupboard", [35.4, 40.0, 38.3, 43.0], "The red wall cupboard", "hang", "above the worktop", False),
    ("New oven", [45.3, 44.9, 49.7, 47.0], "The new oven", "wait", "under the black hob", False),
    ("Plasterer in blue dungarees", [52.7, 40.6, 63.6, 43.9], "The plasterer in the blue dungarees", "smooth", "the ceiling above his head", False),
    ("Aluminium stepladder", [56.4, 40.9, 67.3, 44.2], "The aluminium stepladder", "wobble", "under the plasterer", False),
    ("Woman catching bricks", [55.7, 46.5, 65.9, 49.4], "The woman catching the bricks", "catch", "the falling pieces of brick", False),
    ("Falling rubble", [51.3, 43.4, 56.1, 46.7], "The falling rubble", "drop", "from the broken ceiling", False),
    ("Ceiling pipe", [51.1, 42.8, 53.4, 45.1], "The ceiling pipe", "stick", "out of the old ceiling", False),
    ("Wooden trestle", [62.0, 44.8, 67.3, 48.4], "The wooden trestle", "hold", "the long plank steady", False),
    ("Girl in a purple jacket", [63.4, 30.6, 69.4, 33.4], "The girl in the purple jacket", "help", "the workers outside", False),
    ("Boy in blue overalls", [64.3, 37.2, 69.4, 39.9], "The boy in the blue overalls", "carry", "a brick to the wall", False),

    # --- middle right of the house: bathrooms, the red room, the fitters ---
    ("Man in a yellow shirt", [39.1, 51.1, 49.5, 53.6], "The man in the yellow shirt", "check", "the new bathroom", False),
    ("Plumber in an orange vest", [43.2, 52.8, 49.5, 55.8], "The plumber in the orange vest", "fit", "a tap in the shower", False),
    ("Blue shower tiles", [40.5, 53.9, 48.8, 58.7], "The blue shower tiles", "cover", "the bathroom wall", True),
    ("Shower pipe", [43.9, 55.0, 46.4, 56.9], "The shower pipe", "come", "out of the tiled wall", False),
    ("Man with a caulking gun", [39.8, 61.0, 49.7, 64.3], "The man with the caulking gun", "seal", "the edge of the new door", False),
    ("Caulking gun", [41.6, 59.6, 43.4, 61.8], "The caulking gun", "squeeze", "white sealant on the frame", False),
    ("Blue door", [36.1, 61.9, 49.2, 66.1], "The blue door", "stand", "in its new frame", False),
    ("Man with a wooden block", [43.2, 67.3, 49.5, 70.7], "The man with the wooden block", "knock", "the floorboards together", False),
    ("Woman laying carpet", [43.2, 71.8, 49.5, 74.8], "The woman laying the carpet", "roll", "out the new carpet", False),
    ("Toolbox on the floor", [46.9, 59.6, 49.2, 61.7], "The toolbox on the floor", "hold", "screws and nails", False),
    ("Bathroom ceiling lamp", [50.9, 53.0, 52.9, 57.2], "The bathroom ceiling lamp", "hang", "from the white ceiling", False),
    ("Woman in orange dungarees", [56.4, 54.8, 66.4, 58.1], "The woman in the orange dungarees", "fix", "the new washbasin", False),
    ("White toilet", [62.4, 55.3, 66.4, 58.1], "The white toilet", "stand", "beside the basin", False),
    ("Plumber with a pipe", [60.4, 51.9, 66.7, 55.0], "The plumber with the pipe", "connect", "the waste pipe", False),
    ("Bathroom mirror", [55.7, 53.1, 59.6, 55.2], "The bathroom mirror", "hang", "above the washbasin", False),
    ("Washbasin", [59.7, 56.7, 61.7, 58.4], "The washbasin", "wait", "for its taps", False),
    ("Man fitting a lamp", [52.3, 61.6, 63.6, 64.9], "The man fitting the lamp", "hang", "a lamp from the ceiling", False),
    ("White ceiling lamp", [54.6, 60.4, 56.6, 63.0], "The white ceiling lamp", "swing", "from the man's hand", False),
    ("Tall stepladder", [59.2, 61.9, 66.7, 64.9], "The tall stepladder", "stand", "in the middle of the red room", False),
    ("Red wall", [50.4, 59.4, 66.4, 67.7], "The red wall", "brighten", "the new living room", False),
    ("Man in a blue cap", [55.0, 68.4, 61.7, 71.4], "The man in the blue cap", "drill", "a hole in the wall", False),
    ("Wooden work table", [58.7, 65.0, 63.6, 67.3], "The wooden work table", "hold", "the workman's tools", False),
    ("Little spider", [34.1, 54.2, 35.3, 55.2], "The little spider", "crawl", "along the ceiling", False),
    ("Tool bag", [65.2, 59.6, 66.7, 61.8], "The tool bag", "sit", "against the red wall", False),

    # --- middle right: the conservatory, the garage and the hedge ---
    ("Rolled carpet", [47.3, 74.7, 49.7, 77.7], "The rolled carpet", "wait", "at the edge of the room", False),
    ("Tall window", [36.3, 73.2, 48.3, 78.2], "The tall window", "look", "out over the garden", False),
    ("Glass conservatory", [34.7, 79.7, 49.7, 92.3], "The glass conservatory", "shine", "in the afternoon sun", False),
    ("Man cleaning the glass", [37.7, 80.1, 47.8, 82.6], "The man cleaning the glass", "wipe", "the big glass panes", False),
    ("Cleaning cloth", [36.8, 81.0, 39.5, 84.0], "The cleaning cloth", "squeak", "against the glass", False),
    ("Wooden bench", [47.2, 79.8, 49.2, 82.9], "The wooden bench", "hold", "the man up to the window", False),
    ("Boy in a yellow T-shirt", [43.5, 87.1, 49.2, 89.9], "The boy in the yellow T-shirt", "watch", "the man clean the windows", False),
    ("Glass roof panels", [35.1, 82.3, 40.9, 91.1], "The glass roof panels", "let", "the sunlight into the room", True),
    ("Wooden shutters", [48.1, 93.5, 53.9, 97.0], "The wooden shutters", "hang", "on the outside wall", True),
    ("Painter on a stepladder", [53.4, 82.0, 63.6, 84.2], "The painter on the stepladder", "paint", "the garage ceiling", False),
    ("Painter's stepladder", [57.4, 80.6, 66.7, 84.0], "The painter's stepladder", "stand", "beside the green car", False),
    ("Green car", [57.4, 81.0, 66.7, 88.6], "The green car", "park", "inside the new garage", False),
    ("Garage roof", [50.9, 80.0, 52.9, 92.3], "The garage roof", "cover", "the family car", False),
    ("Man with a raised arm", [57.4, 90.9, 67.3, 93.0], "The man with the raised arm", "point", "at the crane above", False),
    ("Yellow crate", [59.7, 92.8, 63.6, 94.5], "The yellow crate", "stand", "against the garden wall", False),
    ("Tall green hedge", [33.5, 93.4, 68.0, 100.0], "The tall green hedge", "hide", "the neighbour's garden", False),

    # --- bottom left: planting, the tipper truck and the street ---
    ("Girl planting a tree", [65.8, 3.2, 76.7, 6.6], "The girl planting the tree", "hold", "the young tree straight", False),
    ("Young sapling", [64.2, 5.5, 75.1, 9.0], "The young sapling", "stand", "in the fresh soil", False),
    ("Garden spade", [72.1, 2.6, 76.5, 4.3], "The garden spade", "lean", "against the girl's leg", False),
    ("Yellow tipper truck", [67.0, 10.8, 77.0, 30.6], "The yellow tipper truck", "wait", "for its load of soil", False),
    ("Truck's back wheel", [73.3, 12.2, 76.7, 14.5], "The truck's back wheel", "stand", "on the muddy ground", False),
    ("Truck's middle wheel", [73.3, 17.4, 76.7, 20.1], "The truck's middle wheel", "rest", "beside the fence", False),
    ("Woman in a purple dress", [74.2, 5.2, 85.1, 9.3], "The woman in the purple dress", "walk", "along the pavement", False),
    ("Boy in a green jacket", [77.7, 9.4, 84.9, 12.2], "The boy in the green jacket", "run", "after his mother", False),
    ("Man loading the truck", [64.4, 19.0, 70.9, 22.3], "The man loading the truck", "throw", "soil into the truck", False),
    ("Worker in a cap", [65.8, 21.1, 70.9, 23.5], "The worker in the cap", "stand", "on the back of the truck", False),
    ("Metal fence", [77.2, 0.0, 82.5, 25.0], "The metal fence", "run", "along the building site", False),
    ("Girl on a scooter", [83.0, 14.3, 92.3, 18.2], "The girl on the scooter", "ride", "down the street", False),
    ("Girl in a yellow dress", [83.0, 13.9, 92.3, 16.4], "The girl in the yellow dress", "sit", "behind her friend", False),
    ("Green scooter", [86.8, 12.9, 95.1, 20.9], "The green scooter", "buzz", "along the road", False),
    ("Scooter's front wheel", [90.7, 18.0, 94.8, 20.7], "The scooter's front wheel", "spin", "on the smooth road", False),
    ("Scooter's back wheel", [91.2, 13.1, 94.8, 15.8], "The scooter's back wheel", "turn", "under the seat", False),
    ("Woman in a red top", [83.0, 23.1, 95.6, 26.0], "The woman in the red top", "hold", "her child's hand", False),
    ("Bush by the pavement", [86.5, 0.0, 99.6, 9.6], "The bush by the pavement", "grow", "at the side of the street", False),
    ("Small stones", [91.6, 8.4, 93.7, 12.4], "The small stones", "lie", "on the grey road", True),

    # --- bottom middle: bricklaying, the dog and the barriers ---
    ("Truck's front wheel", [72.1, 26.9, 77.0, 29.7], "The truck's front wheel", "stand", "in the wet mud", False),
    ("Girl with a shovel", [64.5, 30.6, 73.5, 33.3], "The girl with the shovel", "shovel", "sand into a bucket", False),
    ("Stack of bricks", [67.9, 34.0, 73.7, 37.4], "The stack of bricks", "wait", "on a wooden pallet", False),
    ("Man carrying a brick", [65.1, 37.2, 75.1, 40.2], "The man carrying the brick", "carry", "a heavy brick to the wall", False),
    ("Pile of sand", [69.3, 39.4, 75.1, 47.6], "The pile of sand", "lie", "beside the new wall", False),
    ("Bricklayer in a red shirt", [65.8, 47.7, 74.6, 51.6], "The bricklayer in the red shirt", "lay", "bricks along the wall", False),
    ("Boy in a striped shirt", [75.9, 28.8, 85.1, 32.2], "The boy in the striped shirt", "run", "after the little dog", False),
    ("Yellow bollard", [75.6, 36.6, 79.8, 38.5], "The yellow bollard", "stand", "at the edge of the site", False),
    ("Brown dog", [80.9, 35.8, 85.6, 42.4], "The brown dog", "chase", "the boy down the street", False),
    ("Red and white barrier", [80.7, 41.2, 91.4, 46.3], "The red and white barrier", "warn", "the cars to slow down", False),
    ("Worker with a machine", [76.8, 47.4, 89.5, 50.4], "The worker with the machine", "press", "the new path flat", False),
    ("Boy holding hands", [84.2, 26.1, 96.5, 29.4], "The boy holding hands", "walk", "beside his mother", False),
    ("Yellow butterfly", [88.6, 33.7, 90.5, 34.9], "The yellow butterfly", "flutter", "over the pavement", False),
    ("Wooden hoarding", [73.5, 30.0, 77.4, 41.1], "The wooden hoarding", "fence", "off the building site", False),
    ("The street", [92.4, 25.0, 99.5, 50.0], "The street", "run", "past the new house", False),

    # --- bottom right: the digger, the road works and the red car ---
    ("Long concrete pipe", [71.4, 46.9, 76.4, 57.8], "The long concrete pipe", "lie", "on the bare ground", False),
    ("New brick wall", [66.8, 48.0, 73.5, 66.1], "The new brick wall", "grow", "higher every day", False),
    ("Yellow excavator", [60.4, 65.3, 77.1, 78.1], "The yellow excavator", "dig", "a trench for the pipe", False),
    ("Excavator's bucket", [69.8, 61.0, 73.5, 64.9], "The excavator's bucket", "scoop", "up the heavy soil", False),
    ("Excavator's arm", [63.6, 64.8, 70.9, 69.2], "The excavator's arm", "swing", "over the building site", False),
    ("Caterpillar tracks", [74.0, 70.2, 77.0, 76.6], "The caterpillar tracks", "grip", "the muddy ground", True),
    ("Excavator driver", [64.9, 71.5, 68.6, 74.2], "The excavator driver", "pull", "the levers in his cab", False),
    ("Pile of earth", [72.6, 54.5, 78.8, 70.1], "The pile of earth", "spill", "across the site", False),
    ("Green road roller", [85.1, 50.2, 90.5, 54.7], "The green road roller", "flatten", "the new pavement", False),
    ("Yellow post", [75.6, 50.8, 84.4, 52.8], "The yellow post", "hold", "the site fence up", False),
    ("Road closed sign", [81.9, 59.0, 85.6, 61.3], "The road closed sign", "tell", "the drivers to stop", False),
    ("Striped road barrier", [80.0, 57.3, 91.4, 62.4], "The striped road barrier", "close", "the road to traffic", False),
    ("Man in a yellow raincoat", [75.6, 65.0, 84.9, 67.3], "The man in the yellow raincoat", "carry", "a round road sign", False),
    ("Round red sign", [75.1, 65.8, 77.2, 67.5], "The round red sign", "warn", "the drivers of the work", False),
    ("Boy in a blue cap", [77.7, 63.1, 90.0, 66.1], "The boy in the blue cap", "watch", "the diggers at work", False),
    ("Car's front wheel", [86.5, 72.4, 90.9, 75.1], "The car's front wheel", "stop", "at the road works", False),
    ("Red family car", [78.1, 69.8, 91.0, 93.0], "The red family car", "wait", "at the closed road", False),
    ("Man driving the car", [80.0, 78.0, 84.4, 81.2], "The man driving the car", "look", "at the road works", False),
    ("Child in the back seat", [80.5, 84.9, 83.0, 87.1], "The child in the back seat", "peer", "out of the car window", False),
    ("Car's back wheel", [86.3, 86.9, 90.9, 89.9], "The car's back wheel", "stand", "on the grey road", False),
    ("Girl walking a dog", [81.6, 93.4, 95.1, 96.7], "The girl walking the dog", "hold", "the dog's lead tightly", False),
    ("Little dog", [92.6, 83.4, 95.6, 87.1], "The little dog", "sniff", "along the pavement", False),
    ("Surveyor with a level", [67.2, 84.9, 76.3, 87.4], "The surveyor with the level", "measure", "the height of the road", False),
    ("Surveying tripod", [67.7, 83.4, 76.3, 85.9], "The surveying tripod", "stand", "on three long legs", False),
    ("Man in an orange vest", [66.1, 88.1, 77.2, 91.1], "The man in the orange vest", "wait", "for the surveyor to finish", False),
    ("Yellow concrete block", [75.6, 79.5, 78.8, 82.8], "The yellow concrete block", "sit", "beside the digger", False),
    ("Second concrete block", [75.6, 96.2, 83.5, 99.5], "The second concrete block", "block", "the end of the path", False),
    ("Green hedge by the road", [64.9, 93.1, 74.1, 100.0], "The green hedge by the road", "grow", "along the pavement", False),
    ("Grey pavement", [74.0, 90.3, 78.8, 100.0], "The grey pavement", "lead", "towards the town", False),
]
