# Page 13 - night-time street with two cutaway houses at bedtime.
# Boxes read per-tile from the labelled grid (tiler.py), page-percent coords.
# Entry: (name, [ymin, xmin, ymax, xmax], subject, bare-infinitive verb, rest, plural)

P = [
    # --- Night sky and village backdrop (r0c0/r0c1) ---
    ("Crescent moon", [1.4, 6.0, 4.3, 8.3],
     "The crescent moon", "shine", "over the sleeping village", False),
    ("Stars in the sky", [0.0, 0.0, 6.5, 60.0],
     "The stars", "twinkle", "in the night sky", True),
    ("Owl", [1.5, 10.0, 8.5, 16.8],
     "The owl", "fly", "over the rooftops", False),
    ("Fir forest on the hill", [1.9, 19.0, 6.0, 28.6],
     "The fir forest", "stand", "on the dark hill", False),
    ("Wheat field", [5.5, 15.0, 10.8, 25.5],
     "The wheat field", "glow", "in the moonlight", False),
    ("Yellow house in the village", [8.5, 2.2, 13.1, 6.3],
     "The yellow house", "stand", "at the edge of the village", False),
    ("Cottage with the red roof", [9.2, 7.0, 12.4, 9.7],
     "The little cottage", "sleep", "under its red roof", False),
    ("Pink farmhouse", [8.5, 10.4, 12.7, 14.5],
     "The pink farmhouse", "stand", "among the trees", False),
    ("Stream", [12.7, 8.0, 15.8, 15.6],
     "The stream", "flow", "through the meadow", False),

    # --- Blue house exterior (r0c0/r1c0) ---
    ("Chimney of the blue house", [10.6, 0.0, 15.4, 1.3],
     "The brick chimney", "rise", "above the red roof", False),
    ("Round window", [19.7, 5.6, 22.4, 7.8],
     "The round window", "glow", "in the gable", False),
    ("Spider on the thread", [17.5, 9.7, 22.3, 10.5],
     "The spider", "hang", "from the roof on a thread", False),
    ("Balcony of the blue house", [24.6, 12.5, 33.6, 16.8],
     "The little balcony", "hold", "boxes of flowers", False),
    ("Flowers on the balcony", [24.7, 12.5, 27.5, 16.4],
     "The pink flowers", "bloom", "on the balcony railing", True),
    ("Upstairs window of the blue house", [28.4, 7.0, 35.8, 12.6],
     "The upstairs window", "shine", "into the night", False),
    ("Boy at the window", [29.5, 7.8, 35.6, 10.3],
     "The little boy", "look", "out of the window", False),
    ("Grandmother at the window", [28.7, 9.9, 35.5, 12.4],
     "The grandmother", "wave", "from the window", False),
    ("Red parrot", [32.8, 0.5, 39.3, 3.3],
     "The red parrot", "sit", "on its perch in the window", False),
    ("House number two", [42.8, 5.5, 44.4, 6.6],
     "The house number", "hang", "beside the front door", False),
    ("Window by the front door", [41.9, 7.8, 48.6, 10.7],
     "The lit window", "glow", "beside the front door", False),
    ("Plants on the windowsill", [46.1, 8.1, 48.6, 10.6],
     "The green plants", "sit", "in the window box", True),
    ("Front door of the blue house", [45.6, 0.4, 59.3, 5.0],
     "The front door", "stand", "open in the lamplight", False),
    ("Grandfather at the door", [46.8, 0.8, 56.5, 2.9],
     "The grandfather", "say", "goodnight at the door", False),
    ("Mother in the doorway", [46.8, 2.8, 58.4, 5.2],
     "The mother", "hug", "her daughter goodnight", False),
    ("Girl in the red skirt", [50.2, 1.6, 57.7, 3.3],
     "The little girl", "hug", "her mother at the door", False),
    ("Letterbox", [48.1, 5.0, 50.4, 6.6],
     "The letterbox", "hang", "on the wall by the door", False),
    ("Red car", [48.4, 9.5, 60.7, 14.3],
     "The red car", "park", "in front of the house", False),

    # --- First house: attic workshop (r0c1) ---
    ("Attic window", [0.0, 30.5, 3.4, 33.2],
     "The attic window", "show", "the starry sky", False),
    ("Attic door", [5.5, 29.8, 13.6, 32.0],
     "The attic door", "stay", "shut for the night", False),
    ("Cardboard box under the roof", [8.5, 24.5, 13.6, 28.4],
     "The cardboard box", "sit", "under the sloping roof", False),
    ("Chest of drawers in the attic", [8.3, 38.0, 13.6, 42.2],
     "The chest of drawers", "stand", "in the attic", False),
    ("Red jacket", [9.9, 34.9, 12.2, 36.6],
     "The red jacket", "lie", "over the open drawer", False),
    ("Puppet in the blue coat", [7.1, 36.4, 12.0, 38.1],
     "The puppet in blue", "sit", "on the chest of drawers", False),
    ("Dark vase in the attic", [5.0, 38.4, 8.5, 39.7],
     "The dark vase", "stand", "on the chest of drawers", False),
    ("Dragon puppet", [2.5, 40.0, 8.7, 42.5],
     "The dragon puppet", "hang", "from its strings", False),
    ("Red swivel chair", [6.2, 42.3, 14.1, 44.9],
     "The red swivel chair", "wait", "at the workbench", False),
    ("Puppet in the black hat", [3.6, 44.0, 7.8, 45.6],
     "The puppet in the black hat", "sit", "on the workbench", False),
    ("Desk lamp in the attic", [3.4, 45.8, 6.6, 47.7],
     "The desk lamp", "bend", "over the workbench", False),
    ("Workbench in the attic", [6.0, 45.4, 11.0, 50.5],
     "The workbench", "hold", "jars and bottles", False),
    ("Crate on the workbench", [2.5, 46.6, 8.9, 51.0],
     "The wooden crate", "sit", "at the end of the workbench", False),

    # --- First house: upstairs television room (r0c2) ---
    ("Tall chest of drawers", [0.0, 50.3, 13.5, 54.2],
     "The tall chest of drawers", "stand", "against the wall", False),
    ("Ironing board", [3.9, 54.3, 13.6, 56.1],
     "The ironing board", "lean", "against the wall", False),
    ("Picture above the armchair", [0.0, 58.3, 2.9, 60.4],
     "The picture", "hang", "above the armchair", False),
    ("Yellow armchair", [5.5, 56.6, 14.1, 61.6],
     "The yellow armchair", "hold", "the tired mother", False),
    ("Mother in the armchair", [4.3, 58.6, 13.6, 63.5],
     "The mother", "watch", "television in the armchair", False),
    ("Cuddly toy on the armchair", [7.9, 58.5, 10.2, 59.9],
     "The cuddly toy", "snuggle", "against the mother", False),
    ("Ficus tree", [0.8, 62.0, 12.2, 65.3],
     "The ficus tree", "grow", "in its pot by the television", False),
    ("Round side table", [11.3, 63.4, 13.8, 67.0],
     "The round side table", "stand", "beside the armchair", False),
    ("Blue candle", [9.0, 65.3, 11.7, 66.4],
     "The blue candle", "stand", "on the side table", False),
    ("Television", [5.7, 66.2, 10.1, 70.1],
     "The television", "flicker", "in the dark room", False),
    ("Television stand", [9.9, 65.9, 14.1, 70.7],
     "The television stand", "hold", "the video recorder", False),
    ("Video tapes on the shelf", [11.8, 66.5, 13.3, 70.2],
     "The video tapes", "sit", "under the television", True),
    ("Light switch", [5.5, 70.2, 6.6, 71.0],
     "The light switch", "wait", "beside the door", False),

    # --- First house: living and dining room (r0c1) ---
    ("Family photograph", [17.1, 24.8, 21.7, 27.3],
     "The family photograph", "hang", "on the wall", False),
    ("Red sofa", [23.4, 21.5, 31.7, 30.1],
     "The red sofa", "stand", "in the living room", False),
    ("Cat on the sofa", [26.6, 24.5, 28.9, 26.7],
     "The cat", "sleep", "on the arm of the sofa", False),
    ("Striped cushion", [26.0, 23.2, 28.7, 25.3],
     "The striped cushion", "lie", "under the sleeping cat", False),
    ("Yellow cushion", [24.8, 28.5, 27.1, 30.3],
     "The yellow cushion", "rest", "on the red sofa", False),
    ("Blue mug", [29.0, 22.6, 31.0, 23.7],
     "The blue mug", "stand", "on the low cabinet", False),
    ("Low cabinet by the sofa", [29.8, 21.1, 34.0, 25.2],
     "The low cabinet", "stand", "beside the sofa", False),
    ("Wooden chest", [28.5, 25.1, 32.2, 28.7],
     "The wooden chest", "serve", "as a coffee table", False),
    ("Display cabinet", [17.1, 31.0, 30.8, 34.1],
     "The display cabinet", "show", "the family china", False),
    ("Potted plant on the cabinet", [15.5, 32.1, 18.7, 35.4],
     "The potted plant", "trail", "over the display cabinet", False),
    ("Chair by the cabinet", [25.0, 32.1, 31.7, 34.3],
     "The wooden chair", "stand", "at the dining table", False),
    ("Dining table", [26.0, 33.9, 32.7, 38.8],
     "The dining table", "wait", "to be cleared", False),
    ("Red chair", [26.9, 35.0, 32.7, 37.5],
     "The red chair", "stand", "at the dining table", False),
    ("Ceiling lamp over the table", [15.3, 35.9, 21.5, 37.6],
     "The ceiling lamp", "light", "the dining table", False),
    ("Plates on the table", [23.7, 35.2, 26.3, 37.7],
     "The dinner plates", "wait", "on the table", True),
    ("Man at the dining table", [19.9, 37.5, 33.1, 41.1],
     "The father", "clear", "the table after dinner", False),
    ("Open book on the floor", [32.0, 28.5, 33.4, 30.1],
     "The open book", "lie", "on the living room floor", False),

    # --- First house: kitchen (r0c1) ---
    ("Kitchen wall cupboard", [15.6, 45.2, 21.4, 48.9],
     "The wall cupboard", "hang", "above the cooker", False),
    ("Coffee maker", [23.6, 43.5, 26.4, 45.1],
     "The coffee maker", "sit", "on the kitchen counter", False),
    ("Kitchen cupboard", [26.2, 42.9, 32.7, 45.6],
     "The kitchen cupboard", "stand", "under the counter", False),
    ("Cooker", [25.7, 47.2, 31.7, 50.0],
     "The cooker", "stand", "under the yellow tiles", False),
    ("Pet bowl", [32.5, 47.7, 33.6, 48.8],
     "The pet bowl", "wait", "on the kitchen floor", False),

    # --- First house: blue bathroom (r0c2) ---
    ("Bathroom window", [15.5, 50.9, 19.9, 53.1],
     "The bathroom window", "glow", "with warm light", False),
    ("Shelf with the toiletries", [22.2, 50.6, 23.8, 53.7],
     "The shelf", "hold", "the toiletries", False),
    ("Washbasin in the blue bathroom", [25.0, 50.4, 28.9, 54.2],
     "The washbasin", "stand", "under the shelf", False),
    ("Cupboard under the sink", [29.0, 52.0, 32.7, 54.4],
     "The cupboard", "hide", "under the washbasin", False),
    ("Yellow towel", [25.2, 53.1, 28.9, 54.8],
     "The yellow towel", "hang", "on the rail", False),
    ("Shower head in the blue bathroom", [16.5, 53.9, 18.7, 55.9],
     "The shower head", "spray", "warm water", False),
    ("Man bathing the baby", [19.1, 56.2, 32.6, 59.4],
     "The father", "bathe", "the baby in the tub", False),
    ("Baby in the bath", [25.0, 55.9, 27.5, 57.9],
     "The baby", "splash", "in the warm water", False),
    ("Baby bathtub", [25.7, 54.5, 29.2, 58.4],
     "The baby bathtub", "stand", "on its stand", False),
    ("Toilet in the blue bathroom", [28.5, 57.9, 32.7, 59.8],
     "The toilet", "stand", "in the corner", False),
    ("Blue bucket", [31.5, 57.1, 33.6, 58.5],
     "The blue bucket", "wait", "by the toilet", False),

    # --- First house: nursery (r0c2) ---
    ("Stars on the nursery wall", [18.0, 60.5, 26.5, 64.5],
     "The painted stars", "decorate", "the green wall", True),
    ("Moon night light", [21.8, 61.4, 25.2, 63.1],
     "The moon night light", "glow", "on the nursery wall", False),
    ("Nursery wardrobe", [16.9, 64.0, 28.0, 68.7],
     "The wardrobe", "stand", "in the nursery", False),
    ("Changing table", [23.4, 68.2, 32.7, 72.1],
     "The changing table", "stand", "beside the wardrobe", False),
    ("Panda bear", [21.5, 68.7, 25.4, 70.7],
     "The panda bear", "sit", "on the changing table", False),
    ("Cot", [26.6, 60.2, 33.6, 66.2],
     "The cot", "hold", "the sleeping child", False),
    ("Child in the cot", [27.3, 62.3, 30.3, 65.3],
     "The little child", "sleep", "under the patchwork blanket", False),
    ("Ball on the nursery floor", [29.9, 65.7, 32.0, 67.2],
     "The ball", "lie", "beside the cot", False),
    ("Green romper on the floor", [32.0, 66.2, 33.6, 68.7],
     "The green romper", "lie", "on the nursery floor", False),

    # --- Stairwell and hall (r0c3/r1c3/r2c3) ---
    ("Open door on the top landing", [2.5, 72.2, 14.5, 75.7],
     "The door", "stand", "open on the top landing", False),
    ("Banister on the top landing", [7.1, 79.0, 13.6, 81.7],
     "The banister", "guard", "the top of the stairs", False),
    ("White door on the middle landing", [15.7, 75.5, 30.3, 77.8],
     "The white door", "stand", "open on the landing", False),
    ("Palm tree on the landing", [21.8, 73.0, 33.0, 75.7],
     "The palm tree", "grow", "in a pot on the landing", False),
    ("Staircase to the top floor", [19.9, 77.6, 33.6, 82.3],
     "The staircase", "climb", "to the top floor", False),
    ("Slippers by the staircase", [29.0, 76.5, 30.3, 78.3],
     "The slippers", "wait", "at the top of the stairs", True),
    ("Teenager in the black T-shirt", [36.5, 75.9, 50.2, 78.7],
     "The teenager", "chat", "on the landing", False),
    ("Girl in the white T-shirt", [37.2, 78.8, 50.2, 81.4],
     "The girl in white", "listen", "to the teenager", False),
    ("Boots by the door", [49.8, 74.8, 52.1, 76.7],
     "The boots", "stand", "beside the door", True),
    ("Staircase to the middle floor", [44.2, 78.5, 55.1, 82.4],
     "The middle staircase", "lead", "down to the hall", False),
    ("Staircase in the hall", [56.8, 78.7, 68.9, 82.6],
     "The bottom staircase", "reach", "the downstairs hall", False),
    ("Kick scooter", [64.2, 77.2, 68.6, 80.1],
     "The kick scooter", "lean", "against the staircase", False),
    ("Sunflowers in the pot", [63.9, 72.4, 72.6, 76.3],
     "The sunflowers", "sleep", "in their pot in the hall", True),
    ("Ivy on the stairwell wall", [27.4, 83.0, 68.5, 89.8],
     "The ivy", "climb", "up the stairwell wall", False),
    ("Nest in the ivy", [36.7, 86.3, 39.3, 88.9],
     "The bird's nest", "hide", "in the ivy", False),
    ("Bat by the wall", [22.2, 83.6, 24.8, 86.3],
     "The bat", "flit", "past the stairwell wall", False),
    ("Bat under the roof", [3.4, 84.3, 5.4, 85.7],
     "The little bat", "fly", "under the eaves", False),
    ("Bat by the balcony", [10.4, 89.4, 12.0, 91.7],
     "The third bat", "swoop", "past the balcony", False),

    # --- Neighbour's house (r0c3) ---
    ("Roof of the neighbour's house", [0.0, 89.2, 8.0, 100.0],
     "The dark roof", "cover", "the neighbour's house", False),
    ("Chimney of the neighbour's house", [0.4, 91.1, 4.3, 93.4],
     "The chimney", "stand", "on the dark roof", False),
    ("Semicircular window", [3.4, 95.8, 5.7, 98.8],
     "The semicircular window", "peek", "out of the roof", False),
    ("Black cat on the roof", [2.2, 98.0, 4.3, 99.3],
     "The black cat", "prowl", "along the rooftop", False),
    ("Man on the balcony", [10.1, 92.5, 17.8, 95.1],
     "The neighbour", "stretch", "on the balcony before bed", False),
    ("Bedroom window of the neighbours", [9.9, 95.7, 16.8, 99.6],
     "The bedroom window", "glow", "with lamplight", False),
    ("Couple in the bed", [12.0, 96.0, 15.4, 99.3],
     "The couple", "read", "in bed", True),
    ("Wooden balcony", [17.1, 89.8, 22.0, 99.6],
     "The wooden balcony", "jut", "out over the garden", False),
    ("Window with the pink curtains", [23.6, 90.4, 31.7, 95.0],
     "The window", "hide", "behind pink curtains", False),
    ("Sign with the white car", [26.0, 89.5, 32.6, 91.0],
     "The car sign", "hang", "on the neighbour's wall", False),
    ("Man with the white cat", [25.3, 94.8, 34.4, 97.7],
     "The man", "carry", "the white cat indoors", False),
    ("White cat in his arms", [26.4, 94.9, 28.9, 96.4],
     "The white cat", "ride", "in the man's arms", False),
    ("Woman in the green shorts", [25.1, 97.2, 33.9, 99.6],
     "The woman", "stand", "at the neighbour's door", False),

    # --- Second house: living room (r1c0/r1c1) ---
    ("Floor lamp", [37.5, 17.5, 52.0, 19.9],
     "The floor lamp", "light", "the living room", False),
    ("Cactus by the lamp", [40.2, 19.8, 42.5, 21.1],
     "The little cactus", "sit", "on the windowsill", False),
    ("Mountain painting", [37.0, 23.5, 40.4, 27.8],
     "The mountain painting", "hang", "above the sofa", False),
    ("Black television", [44.7, 15.2, 48.8, 18.3],
     "The black television", "stand", "in the corner", False),
    ("Bookshelf under the television", [48.4, 14.9, 53.2, 18.6],
     "The bookshelf", "hold", "books under the television", False),
    ("Blue sofa", [41.0, 18.7, 53.3, 28.0],
     "The blue sofa", "stand", "under the mountain painting", False),
    ("Checked blanket on the sofa", [41.3, 19.0, 46.3, 26.9],
     "The checked blanket", "lie", "over the back of the sofa", False),
    ("Pink rabbit", [45.6, 25.1, 48.6, 26.5],
     "The pink rabbit", "wait", "for the little girl", False),
    ("Round coffee table", [49.6, 22.0, 53.7, 26.8],
     "The round coffee table", "stand", "on the green rug", False),
    ("Vase of red flowers", [46.6, 23.2, 50.4, 25.1],
     "The vase of red flowers", "decorate", "the coffee table", False),
    ("Mother in the living room", [39.5, 27.6, 53.2, 31.7],
     "The mother", "take", "her daughter to bed", False),
    ("Girl in the pink nightdress", [45.1, 31.0, 52.8, 32.9],
     "The little girl in pink", "hold", "her mother's hand", False),

    # --- Second house: kitchen (r1c1) ---
    ("Shelf with the jugs", [36.3, 34.4, 39.7, 39.4],
     "The kitchen shelf", "carry", "jugs and pots", False),
    ("Green toy snake on the shelf", [36.3, 36.7, 43.0, 39.2],
     "The green toy snake", "hang", "down over the kitchen shelf", False),
    ("Kitchen bench", [44.9, 34.1, 54.2, 38.1],
     "The kitchen bench", "stand", "at the table", False),
    ("Kitchen table", [47.0, 37.3, 54.2, 43.1],
     "The kitchen table", "hold", "a late supper", False),
    ("Bread on the table", [47.2, 40.1, 48.8, 42.5],
     "The loaf of bread", "wait", "on the breadboard", False),
    ("Glass of milk", [45.9, 39.0, 47.8, 39.9],
     "The glass of milk", "stand", "on the kitchen table", False),
    ("Girl at the kitchen table", [43.5, 38.7, 50.9, 41.2],
     "The girl", "eat", "a late supper", False),
    ("Grandmother at the table", [41.7, 41.8, 52.4, 45.0],
     "The grandmother", "eat", "supper with her granddaughter", False),
    ("Walking stick on the chair", [43.3, 43.5, 48.6, 45.2],
     "The walking stick", "lean", "against the chair", False),
    ("Cat under the table", [52.3, 38.3, 53.9, 40.3],
     "The black and white cat", "play", "under the kitchen table", False),
    ("Kitchen door", [35.8, 40.3, 47.2, 44.6],
     "The kitchen door", "stay", "closed for the evening", False),
    ("Refrigerator", [36.5, 45.5, 50.2, 50.0],
     "The refrigerator", "hum", "in the corner", False),
    ("Milk bottles on the fridge", [36.3, 46.3, 38.6, 49.9],
     "The milk bottles", "stand", "on top of the fridge", True),

    # --- Second house: yellow bathroom (r1c2) ---
    ("Oval mirror", [39.8, 50.9, 45.8, 53.7],
     "The oval mirror", "hang", "over the washbasin", False),
    ("Washbasin under the mirror", [46.8, 50.4, 50.4, 54.2],
     "The washbasin", "wait", "under the oval mirror", False),
    ("Bathroom cabinet", [50.2, 50.3, 54.2, 54.4],
     "The bathroom cabinet", "stand", "under the basin", False),
    ("Spotted shower curtain", [36.3, 54.0, 52.8, 56.4],
     "The spotted shower curtain", "hang", "from the rail", False),
    ("Bidet", [46.1, 55.9, 48.8, 58.1],
     "The bidet", "stand", "in the corner", False),
    ("Toilet in the yellow bathroom", [49.8, 57.9, 54.2, 59.8],
     "The toilet", "wait", "beside the shower", False),

    # --- Second house: pink bedroom (r1c2) ---
    ("Princess poster", [35.8, 60.6, 42.1, 62.4],
     "The princess poster", "hang", "on the pink wall", False),
    ("Loft bed in the pink bedroom", [35.3, 63.7, 54.2, 70.4],
     "The loft bed", "fill", "the pink bedroom", False),
    ("Toy unicorn", [34.9, 66.0, 37.2, 67.8],
     "The toy unicorn", "peep", "over the top bunk", False),
    ("Bookshelf above the bed", [35.1, 69.1, 37.6, 71.5],
     "The little bookshelf", "hang", "above the bed", False),
    ("Pink chest of drawers", [45.6, 60.8, 54.2, 63.1],
     "The pink chest of drawers", "stand", "by the bed", False),
    ("Toy monkey", [42.6, 60.0, 46.5, 61.5],
     "The toy monkey", "sit", "on the chest of drawers", False),
    ("Heart balloon", [42.1, 68.5, 44.9, 69.9],
     "The heart balloon", "float", "by the bedpost", False),
    ("Spotted desk chair", [47.2, 68.3, 53.9, 70.2],
     "The spotted desk chair", "roll", "on its little wheels", False),
    ("Clothes on the bedroom floor", [51.9, 66.8, 53.5, 68.4],
     "The clothes", "lie", "on the bedroom floor", True),

    # --- Second house: ground floor rooms (r1c0/r1c1/r2c0/r2c1) ---
    ("Lighthouse picture", [57.0, 15.8, 63.3, 20.3],
     "The lighthouse picture", "hang", "on the wall", False),
    ("Linen cupboard", [56.1, 20.9, 65.8, 25.7],
     "The linen cupboard", "keep", "the towels tidy", False),
    ("Chest of drawers by the television", [57.8, 25.5, 67.6, 28.1],
     "The chest of drawers", "stand", "beside the television", False),
    ("Grey television", [62.4, 26.7, 67.2, 30.7],
     "The grey television", "sit", "on its stand", False),
    ("Blue armchair", [64.2, 14.9, 75.2, 22.0],
     "The blue armchair", "hold", "the mother and her baby", False),
    ("Mother with the baby", [63.5, 16.3, 74.5, 20.5],
     "The mother", "rock", "her baby to sleep", False),
    ("Baby on her lap", [67.3, 18.4, 71.2, 20.5],
     "The baby", "fall", "asleep in her arms", False),
    ("White cat on the armchair", [67.1, 20.1, 69.4, 21.7],
     "The white cat", "curl", "up on the armchair", False),
    ("Low table by the armchair", [70.3, 22.1, 74.5, 26.0],
     "The low table", "stand", "by the armchair", False),
    ("Armchair by the television", [66.4, 27.0, 74.7, 32.3],
     "The second armchair", "face", "the grey television", False),
    ("Round dining table", [66.2, 38.6, 73.1, 45.2],
     "The round table", "wear", "a white tablecloth", False),
    ("White chair at the table", [65.0, 35.8, 74.3, 38.8],
     "The white chair", "stand", "at the round table", False),
    ("Blue chair at the table", [68.3, 41.7, 74.5, 45.6],
     "The blue chair", "wait", "at the round table", False),
    ("Houseplant in the dining room", [55.6, 33.8, 66.8, 35.7],
     "The tall houseplant", "grow", "in the dining room", False),
    ("Wall cabinet with the cups", [56.5, 34.6, 64.0, 37.5],
     "The wall cabinet", "display", "the china cups", False),
    ("Grey door", [56.3, 40.9, 67.2, 44.3],
     "The grey door", "stay", "closed", False),
    ("Calendar on the kitchen wall", [57.0, 45.8, 59.3, 47.6],
     "The calendar", "hang", "on the kitchen wall", False),

    # --- Second house: downstairs bathroom (r1c2/r2c1/r2c2) ---
    ("Pink washbasin", [65.5, 50.4, 72.2, 54.3],
     "The pink washbasin", "stand", "in the downstairs bathroom", False),
    ("Mirror in the downstairs bathroom", [60.0, 51.1, 64.0, 53.1],
     "The mirror", "hang", "above the pink basin", False),
    ("Cactus in the bathroom", [57.5, 51.5, 59.5, 52.7],
     "The cactus", "perch", "on top of the mirror", False),
    ("Shower in the downstairs bathroom", [57.7, 55.2, 60.2, 56.7],
     "The hand shower", "hang", "on the tiled wall", False),
    ("Blue shower curtain", [55.6, 56.6, 64.0, 58.4],
     "The blue shower curtain", "hang", "beside the bathtub", False),
    ("Pink bathtub", [63.0, 54.0, 72.6, 59.1],
     "The pink bathtub", "wait", "for bathtime", False),
    ("Blue potty", [72.7, 52.3, 75.0, 54.8],
     "The blue potty", "sit", "on the bathroom floor", False),

    # --- Second house: children's room (r1c2/r2c2) ---
    ("Shelf above the bunk bed", [55.6, 66.2, 57.2, 68.7],
     "The wall shelf", "hang", "above the bunk bed", False),
    ("Bunk bed in the children's room", [57.0, 64.6, 70.3, 71.2],
     "The bunk bed", "stand", "in the children's room", False),
    ("Man reading the story", [61.2, 67.1, 67.7, 70.6],
     "The father", "read", "a bedtime story", False),
    ("Girl listening to the story", [62.4, 66.0, 66.8, 68.1],
     "The girl", "listen", "to the bedtime story", False),
    ("Storybook", [64.9, 68.2, 67.2, 69.9],
     "The storybook", "lie", "open in the father's hands", False),
    ("Bookcase in the children's room", [60.0, 60.0, 65.4, 62.8],
     "The bookcase", "hold", "the children's books", False),
    ("Blue desk lamp", [66.2, 60.2, 70.1, 62.2],
     "The blue desk lamp", "bend", "over the desk", False),
    ("Desk in the children's room", [68.3, 60.9, 75.0, 63.5],
     "The desk", "stand", "under the lamp", False),
    ("Blue stool", [70.3, 62.6, 75.0, 64.5],
     "The blue stool", "spin", "on its single leg", False),
    ("Red toy on the floor", [64.2, 63.5, 68.8, 64.7],
     "The red toy", "lie", "beside the bunk bed", False),
    ("Green rucksack", [72.2, 69.4, 75.2, 71.5],
     "The green rucksack", "wait", "for the morning", False),

    # --- Street and gardens (r2 row) ---
    ("Pink moped", [66.4, 2.2, 77.3, 10.3],
     "The pink moped", "drive", "down the night street", False),
    ("Moped rider in the helmet", [63.5, 4.2, 74.2, 8.2],
     "The moped rider", "ride", "home through the night", False),
    ("Luggage on the moped", [67.1, 1.8, 71.2, 5.0],
     "The bags", "balance", "on the back of the moped", True),
    ("Street lamp", [69.4, 11.6, 78.2, 14.0],
     "The street lamp", "light", "the pavement", False),
    ("Zebra crossing", [75.2, 0.0, 84.7, 3.8],
     "The zebra crossing", "stripe", "the dark road", False),
    ("Street sweeper", [78.0, 0.0, 100.0, 28.5],
     "The street sweeper", "sweep", "the street at night", False),
    ("Driver of the sweeper", [82.9, 21.5, 86.6, 23.9],
     "The driver", "steer", "the street sweeper", False),
    ("Rotating brush", [95.7, 12.2, 100.0, 16.1],
     "The rotating brush", "scrub", "the road clean", False),
    ("Orange beacon on the cab", [79.2, 23.2, 81.2, 24.8],
     "The orange beacon", "flash", "on the cab roof", False),
    ("Hedge in front of the houses", [75.9, 14.0, 87.5, 76.0],
     "The long hedge", "line", "the front gardens", False),
    ("Red flowers in the hedge", [77.1, 36.7, 79.6, 41.9],
     "The red flowers", "bloom", "in the hedge", True),
    ("Blue hydrangeas in the hedge", [77.1, 49.7, 81.9, 54.2],
     "The blue hydrangeas", "flower", "by the police car", True),
    ("Red tulips in the hedge", [76.9, 60.2, 80.3, 62.5],
     "The red tulips", "grow", "in the front garden", True),
    ("Hedgehog by the red flowers", [78.0, 42.2, 79.8, 43.7],
     "The hedgehog", "snuffle", "through the hedge", False),
    ("Sleeping hedgehog", [76.9, 56.2, 79.2, 58.5],
     "The second hedgehog", "doze", "in the hedge", False),
    ("Woman with the pink hair", [77.1, 35.8, 90.3, 39.4],
     "The woman with pink hair", "carry", "a glowing lantern", False),
    ("Round paper lantern", [78.7, 40.0, 82.2, 42.8],
     "The round lantern", "glow", "on its stick", False),
    ("Girl with the lantern", [82.4, 39.2, 90.3, 41.9],
     "The little girl", "walk", "in the lantern parade", False),
    ("Fish lantern", [81.7, 42.9, 84.7, 45.6],
     "The fish lantern", "swim", "through the night air", False),
    ("Little dog on the pavement", [83.6, 29.8, 87.3, 31.7],
     "The little dog", "trot", "along the pavement", False),
    ("Police car", [83.6, 51.8, 95.0, 69.0],
     "The police car", "stop", "by the kerb", False),
    ("Flashing light on the police car", [81.3, 59.9, 84.3, 63.8],
     "The flashing light", "spin", "on the roof of the police car", False),
    ("Police officer", [81.7, 57.4, 96.4, 62.2],
     "The police officer", "step", "out of the patrol car", False),
    ("Boy in the orange shirt", [83.2, 69.9, 90.1, 71.8],
     "The boy in orange", "hold", "his mother's hand", False),
    ("Blonde woman on the pavement", [77.6, 71.6, 89.8, 73.9],
     "The blonde woman", "talk", "to the police officer", False),
    ("Woman with the shopping bag", [77.8, 75.1, 90.3, 79.2],
     "The woman with the shopping bag", "walk", "home in the lamplight", False),
    ("Lamp post by the path", [69.6, 81.9, 90.8, 84.2],
     "The lamp post", "shine", "over the courtyard", False),
    ("Boy in the yellow shirt", [67.6, 84.7, 76.6, 87.2],
     "The boy in yellow", "shake", "hands with the dog", False),
    ("Golden dog", [69.9, 87.5, 76.6, 91.3],
     "The golden dog", "give", "its paw to the boy", False),
    ("Dog owner with the lead", [62.8, 91.7, 76.6, 95.2],
     "The dog owner", "hold", "the long lead", False),
    ("Shaggy dog", [69.6, 96.2, 76.8, 99.0],
     "The shaggy dog", "sit", "patiently on the path", False),
    ("Blue wheelie bin", [60.0, 95.2, 68.0, 97.9],
     "The blue wheelie bin", "stand", "by the hedge", False),
    ("Brown wheelie bin", [60.5, 97.7, 67.5, 100.0],
     "The brown wheelie bin", "wait", "for collection day", False),
    ("Woman in the yellow blouse", [77.3, 90.3, 91.2, 93.1],
     "The woman in yellow", "stroll", "with her family", False),
    ("Girl with the torch", [83.4, 87.7, 91.2, 90.3],
     "The girl with the torch", "shine", "her light at the lamp post", False),
    ("Boy in the wheelchair", [81.9, 92.9, 90.9, 95.9],
     "The boy", "ride", "in his wheelchair", False),
    ("Man pushing the wheelchair", [76.6, 95.8, 91.2, 99.3],
     "The bearded man", "push", "the wheelchair", False),
    ("Ginger cat", [92.2, 79.0, 95.9, 83.2],
     "The ginger cat", "dash", "across the road", False),
    ("Grey cat on the lawn", [55.6, 89.7, 58.8, 92.8],
     "The grey cat", "creep", "across the lawn", False),
    ("Low brick wall", [50.0, 89.4, 55.1, 96.2],
     "The low brick wall", "border", "the front garden", False),
    ("Hydrangea bush", [48.4, 96.0, 55.1, 100.0],
     "The hydrangea bush", "bloom", "by the garden wall", False),
    ("Garden hedge", [52.6, 93.5, 64.0, 100.0],
     "The garden hedge", "grow", "behind the brick wall", False),
    ("Cyclist", [41.6, 90.0, 50.4, 100.0],
     "The cyclist", "ride", "past the house at night", False),
]
