# Page 12 - the river beach and the farm: swimmers and the police boat on the
# river, the beach picnics, the campsite, the zip line, the country road with
# the tractor, the flower garden, the red farmhouse, the pony paddock, the
# rabbit pen and the farmyard breakfast tables.
# Boxes read straight off the tiler grid labels, one block per tile.
P = [

# TILE r0c0 - the river, the big tree, the wading girls
("Tall leafy tree on the beach", [1.0, 0.0, 29.0, 9.8], "The tall leafy tree", "stand", "at the edge of the beach", False),
("Squirrel in the big tree", [4.5, 1.8, 8.0, 4.9], "The squirrel in the big tree", "sit", "on a leafy branch", False),
("Boy climbing the tree", [16.2, 2.5, 23.8, 5.2], "The boy in the blue shorts", "climb", "up the big tree", False),
("Boy in the tree hollow", [21.5, 5.2, 27.5, 8.1], "The boy in the red shorts", "hide", "inside the hollow tree", False),
("Swan near the police boat", [2.0, 12.3, 5.8, 17.3], "The swan near the police boat", "swim", "past the police boat", False),
("Swan in the middle of the river", [11.8, 16.0, 16.5, 21.0], "The swan in the middle of the river", "glide", "across the calm water", False),
("Seagulls on the water", [17.1, 23.3, 20.1, 26.9], "The seagulls on the water", "float", "on the little waves", True),
("Mother wading in the river", [17.5, 13.0, 26.8, 15.3], "The mother in the green swimsuit", "hold", "her daughter's hands in the water", False),
("Girl in the pink swimsuit", [19.8, 11.8, 26.8, 13.4], "The girl in the pink swimsuit", "splash", "in the shallow water", False),
("Weeping willow on the beach", [20.8, 14.8, 34.5, 23.5], "The weeping willow", "grow", "in the middle of the sandy beach", False),
("Blue river", [0.0, 0.0, 18.0, 62.0], "The blue river", "flow", "past the sandy beach", False),
("Sandy beach", [13.0, 30.0, 33.0, 70.0], "The sandy beach", "stretch", "along the river bank", False),

# TILE r0c1 - the police boat, the dinghy, the swimmers, the air mattresses
("Police boat", [1.5, 18.5, 13.5, 34.5], "The police boat", "patrol", "along the river", False),
("Policeman at the wheel", [2.3, 24.9, 7.8, 27.3], "The policeman at the wheel", "steer", "the police boat", False),
("Policeman beside the driver", [2.3, 27.3, 7.8, 29.4], "The policeman beside the driver", "watch", "over the swimmers", False),
("Boy on the police boat", [2.8, 22.1, 6.6, 24.1], "The boy on the police boat", "sit", "at the back of the boat", False),
("Seagull in the air", [1.1, 33.8, 5.0, 37.2], "The seagull in the air", "fly", "above the river", False),
("Red rubber dinghy", [2.5, 37.6, 9.8, 47.1], "The red rubber dinghy", "drift", "down the river", False),
("Boy with the yellow paddle", [1.3, 42.9, 7.6, 46.2], "The boy with the yellow paddle", "paddle", "the red dinghy", False),
("Girl lying in the dinghy", [3.4, 38.3, 7.8, 41.9], "The girl in the dinghy", "lie", "in the front of the boat", False),
("Dog swimming in the river", [15.8, 36.7, 18.8, 39.4], "The dog in the river", "swim", "after its owner", False),
("Woman swimming on her back", [15.6, 40.7, 22.5, 47.6], "The woman with the red ponytail", "swim", "on her back", False),
("Swimmer in the dark cap", [14.6, 45.5, 17.2, 49.8], "The swimmer in the dark cap", "race", "through the water", False),
("Girl on the red air mattress", [20.6, 26.4, 26.5, 31.1], "The girl on the red air mattress", "float", "down the lazy river", False),
("Man on the yellow air mattress", [19.7, 31.2, 26.4, 37.5], "The man on the yellow air mattress", "kick", "his feet in the water", False),
("Blue towel with the fish pattern", [28.2, 43.5, 31.5, 49.8], "The blue fish towel", "dry", "in the sunshine", False),
("Pink beach bag", [30.4, 45.2, 33.8, 47.8], "The pink beach bag", "sit", "on the blue towel", False),
("Striped beach mat", [31.0, 39.9, 35.0, 44.9], "The striped beach mat", "wait", "for the next sunbather", False),
("Black sandals on the sand", [25.4, 47.6, 27.8, 50.0], "The black sandals", "lie", "side by side on the sand", True),
("Lavender beach towel", [23.4, 47.2, 27.7, 53.0], "The lavender beach towel", "wait", "for a wet swimmer", False),
("Woman with the water bottle", [29.0, 32.3, 35.2, 36.9], "The woman with the water bottle", "pour", "a cold drink for the grandma", False),
("Grandma in the red wheelchair", [32.0, 35.2, 41.3, 39.8], "The grandma in the red wheelchair", "enjoy", "the picnic on the beach", False),

# TILE r0c2 - the swimmers by the shore, the umbrella, the beach picnic
("Father in the deep water", [1.2, 56.9, 5.6, 60.5], "The father in the deep water", "swim", "towards his little boy", False),
("Little boy splashing water", [3.5, 54.7, 6.9, 57.4], "The little boy in the water", "splash", "water at his father", False),
("Boy in the duck ring", [3.3, 60.2, 7.3, 64.4], "The boy in the duck ring", "float", "in the yellow duck ring", False),
("Grandma in the pink swimsuit", [7.5, 53.0, 15.2, 57.8], "The grandma in the pink swimsuit", "run", "away from the little crab", False),
("Little crab", [12.7, 52.2, 14.9, 53.8], "The little crab", "pinch", "the grandma's finger", False),
("Blue and white beach umbrella", [0.2, 70.0, 7.4, 76.3], "The blue and white beach umbrella", "shade", "the sleeping man", False),
("Man sunbathing on the blue towel", [7.5, 68.4, 13.3, 75.2], "The man on the blue towel", "sleep", "in the shade of the umbrella", False),
("Red bag by the umbrella", [6.4, 73.5, 8.2, 76.2], "The red bag by the umbrella", "sit", "next to the sleeping man", False),
("Brown dog on the sand", [8.7, 64.1, 15.2, 68.0], "The brown dog on the sand", "sniff", "the footprints in the sand", False),
("Footprints in the sand", [6.3, 60.3, 9.5, 64.3], "The footprints in the sand", "lead", "across the warm beach", True),
("Little white dog", [19.4, 53.1, 24.5, 56.0], "The little white dog", "run", "along the beach", False),
("Girl in the yellow swimsuit", [18.5, 57.5, 25.7, 59.7], "The girl in the yellow swimsuit", "talk", "to her mother on the blanket", False),
("Woman in the sun hat", [16.9, 60.2, 25.0, 63.9], "The woman in the sun hat", "show", "the teddy bear to her daughter", False),
("Teddy bear on the pink blanket", [19.6, 60.5, 22.7, 61.7], "The teddy bear on the pink blanket", "dance", "in the mother's hands", False),
("Blue picnic bag", [19.2, 62.9, 24.5, 64.9], "The blue picnic bag", "stand", "open on the blanket", False),
("Pink picnic blanket", [20.4, 57.0, 26.4, 65.9], "The pink picnic blanket", "cover", "the warm sand", False),
("Black rucksack on the sand", [22.7, 53.4, 25.7, 56.1], "The black rucksack", "sit", "next to the picnic things", False),
("Blue dragonfly on the bush", [31.8, 55.1, 33.9, 57.1], "The blue dragonfly", "rest", "on the green bush", False),
("Puppy in the bushes", [32.7, 61.9, 35.5, 64.0], "The puppy in the bushes", "hide", "between the big bushes", False),
("Big green bushes", [27.5, 46.0, 38.0, 66.0], "The big green bushes", "separate", "the beach from the road", True),

# TILE r0c2/r0c3 - the barbecue corner
("Man in the red vest", [14.8, 69.7, 22.2, 72.7], "The man in the red vest", "drink", "a bottle of lemonade", False),
("Man at the barbecue", [15.2, 72.9, 25.7, 76.6], "The man at the barbecue", "grill", "sausages for everyone", False),
("Barbecue grill", [22.2, 71.5, 26.8, 75.0], "The black barbecue", "stand", "full of sizzling sausages", False),
("Girl on the folding chair", [21.3, 68.2, 29.2, 71.4], "The girl on the folding chair", "wait", "for a grilled sausage", False),
("Blue cool box", [22.7, 66.6, 26.8, 68.8], "The blue cool box", "keep", "the drinks nice and cold", False),
("Folding chairs by the barbecue", [16.4, 75.9, 25.3, 79.9], "The folding chairs", "stand", "ready on the grass", True),
("Picnic basket on the chair", [22.8, 76.5, 25.1, 78.6], "The picnic basket", "hold", "the fresh bread rolls", False),

# TILE r0c3 - the campsite
("Pink changing hut", [0.0, 79.6, 9.4, 84.8], "The pink changing hut", "stand", "between the trees", False),
("Boy in the changing hut", [4.0, 80.8, 8.8, 83.0], "The boy in the changing hut", "change", "into his swimming trunks", False),
("Yellow tent", [2.4, 84.6, 13.5, 96.6], "The yellow tent", "stand", "on the green meadow", False),
("Man putting up the tent", [1.4, 96.4, 12.1, 99.4], "The man by the tent", "pull", "the tent rope tight", False),
("Grey dog in the tent", [10.8, 87.4, 13.8, 90.0], "The grey dog in the tent", "peek", "out of the yellow tent", False),
("Blue car with the open boot", [11.5, 89.6, 25.4, 100.0], "The blue car", "wait", "with its boot wide open", False),
("Red sleeping bag", [17.8, 90.1, 20.1, 91.9], "The red sleeping bag", "lie", "rolled up in the boot", False),
("Green sleeping bag", [19.4, 90.4, 21.7, 92.7], "The green sleeping bag", "lie", "next to the red one", False),
("Boy carrying the cool box", [13.6, 85.1, 26.1, 88.4], "The boy in the yellow shirt", "carry", "the heavy cool box", False),
("White cool box", [16.2, 86.9, 19.9, 89.8], "The white cool box", "belong", "to the camping family", False),
("Squirrel by the barn", [32.1, 98.2, 35.8, 100.0], "The squirrel by the barn", "climb", "down the tree", False),

# TILE r1c0 - the zip line, the road, the cyclist, the tractor
("Girl on the wooden ramp", [33.8, 2.8, 41.5, 5.1], "The girl on the wooden ramp", "wait", "for her turn on the zip line", False),
("Girl on the zip line", [36.4, 6.5, 42.9, 11.5], "The girl on the zip line", "swing", "through the air on the tyre", False),
("Red zip line post", [33.3, 14.7, 46.0, 18.9], "The red wooden post", "hold", "up the long zip line rope", False),
("Birch trees by the beach", [31.0, 17.5, 41.5, 22.1], "The birch trees", "grow", "next to the zip line", True),
("Country road", [38.0, 0.0, 66.0, 64.0], "The country road", "wind", "past the farm to the beach", False),
("Green hedge by the road", [38.5, 20.0, 46.5, 45.0], "The green hedge", "grow", "thick beside the road", False),
("Dragonfly by the road", [46.4, 11.9, 48.7, 13.7], "The dragonfly by the road", "hover", "over the green bushes", False),
("Girl on the yellow bicycle", [52.3, 4.5, 61.5, 8.7], "The girl in the green helmet", "pedal", "along the country road", False),
("Yellow bicycle", [56.3, 1.8, 65.1, 10.6], "The yellow bicycle", "roll", "down the smooth road", False),
("Blue tractor", [42.0, 15.9, 60.4, 29.3], "The blue tractor", "drive", "slowly along the road", False),
("Tractor driver in the plaid shirt", [44.6, 22.1, 50.5, 24.5], "The tractor driver in the plaid shirt", "look", "back at the cyclist", False),
("Red flowers by the road", [64.2, 1.0, 68.6, 3.9], "The red flowers by the road", "bloom", "at the edge of the field", True),
("Pink tulips by the fence", [60.2, 13.8, 65.1, 18.6], "The pink tulips", "grow", "in front of the wooden fence", True),
("Wooden fence by the road", [56.5, 12.3, 70.0, 40.0], "The wooden fence", "run", "along the sheep meadow", False),
("Lamb at the water trough", [64.3, 20.2, 69.6, 25.3], "The lamb at the water trough", "wait", "for a drink of water", False),
("Water trough", [65.7, 17.3, 71.3, 21.7], "The water trough", "stand", "full of cool water", False),

# TILE r1c1 - the beach picnic, the green car, the petting paddock
("Man lying on the orange mat", [35.3, 21.2, 40.2, 27.4], "The man on the orange mat", "sunbathe", "flat on his stomach in the sun", False),
("Blue checked picnic blanket", [35.6, 27.6, 40.4, 34.8], "The blue checked picnic blanket", "lie", "spread out on the sand", False),
("Teddy bear on the picnic blanket", [37.6, 30.8, 40.1, 32.4], "The teddy bear on the picnic blanket", "sit", "among the picnic plates", False),
("Cool box by the blanket", [37.7, 27.8, 41.1, 30.2], "The cool box by the blanket", "keep", "the picnic food fresh", False),
("Green car with the canoe", [48.3, 35.8, 58.1, 48.9], "The green car", "drive", "towards the campsite", False),
("Wooden canoe on the roof", [45.5, 37.5, 49.6, 45.6], "The wooden canoe", "ride", "on the roof of the car", False),
("Girl in the back seat", [50.4, 41.2, 54.3, 43.1], "The girl in the back seat", "look", "out of the car window", False),
("Woman driving the green car", [49.7, 43.5, 52.9, 45.2], "The woman at the wheel", "drive", "the family to the river", False),
("Boy petting the lamb", [58.9, 26.2, 67.9, 29.4], "The boy in the orange shirt", "stroke", "the little lamb's head", False),
("Little lamb by the fence", [62.6, 29.2, 67.3, 32.6], "The little lamb by the fence", "stand", "close to the friendly boy", False),
("Girl carrying the piglet", [60.2, 36.0, 73.2, 39.4], "The girl in the yellow hat", "carry", "the piglet in her arms", False),
("White piglet", [62.6, 35.9, 65.3, 38.9], "The white piglet", "wriggle", "in the girl's arms", False),
("Girl feeding the lamb", [64.9, 32.9, 73.3, 35.4], "The girl in the pink dress", "feed", "the hungry lamb from a bowl", False),
("Lamb eating from the bowl", [69.3, 27.6, 74.8, 33.3], "The lamb by the girl", "eat", "from the yellow bowl", False),
("Boy in the wheelchair", [66.1, 38.1, 74.8, 42.9], "The boy in the wheelchair", "hold", "a rabbit on his lap", False),
("Wooden gate of the paddock", [56.7, 39.6, 68.7, 46.2], "The wooden gate", "let", "visitors into the paddock", False),

# TILE r1c2 - the flower garden and the farmhouse
("Red farmhouse", [38.5, 64.5, 80.0, 100.0], "The red farmhouse", "stand", "behind the flower garden", False),
("Sunflowers in the garden", [45.5, 53.0, 55.0, 64.8], "The sunflowers in the garden", "turn", "their faces to the sun", True),
("Blue garden fence", [50.7, 51.5, 69.5, 65.0], "The blue garden fence", "protect", "the flower garden", False),
("Cat on the garden path", [55.8, 61.1, 57.8, 64.0], "The cat on the garden path", "creep", "along the garden path", False),
("White rabbit in the garden", [55.9, 55.0, 57.7, 56.9], "The white rabbit in the garden", "nibble", "the young green leaves", False),
("Purple hydrangeas in the garden", [57.7, 56.3, 61.2, 59.3], "The purple hydrangeas", "bloom", "beside the sunflowers", True),
("Red tulips in the garden", [62.1, 60.2, 65.2, 62.5], "The red tulips in the garden", "grow", "in a neat little row", True),
("Woman carrying sunflowers", [58.3, 52.6, 71.5, 56.6], "The woman in the straw hat", "carry", "a bunch of sunflowers", False),
("Bushes with yellow roses", [57.4, 63.8, 64.4, 70.7], "The bushes with yellow roses", "flower", "along the farmhouse wall", True),
("Attic window of the farmhouse", [42.0, 67.1, 45.9, 68.7], "The attic window", "sit", "high up under the roof", False),
("Window with the white curtains", [60.1, 72.9, 64.9, 75.7], "The window with the white curtains", "let", "light into the farmhouse", False),
("Yellow flowers in the window box", [64.9, 72.5, 68.9, 76.6], "The yellow flowers in the window box", "brighten", "the red farmhouse wall", True),

# TILE r1c3 - the farmhouse roof and the barn doorway
("Girl in the upstairs window", [45.7, 77.6, 56.7, 83.3], "The girl in the upstairs window", "shake", "a yellow towel out of the window", False),
("Pink flowers in the window box", [53.0, 78.5, 57.0, 83.1], "The pink flowers in the window box", "hang", "below the girl's window", True),
("Magpie on the roof", [36.6, 84.0, 41.4, 86.5], "The magpie on the roof", "hop", "across the grey roof", False),
("Flowers in the dormer window", [36.9, 89.8, 41.6, 91.9], "The flowers in the dormer window", "bloom", "high up on the roof", True),
("Solar panels on the roof", [45.5, 89.6, 59.5, 100.0], "The solar panels", "catch", "the bright sunlight", True),
("Striped door curtain", [59.7, 79.6, 68.8, 83.2], "The striped door curtain", "hang", "in the barn doorway", False),
("Golden puppy in the doorway", [65.6, 79.4, 70.9, 81.8], "The golden puppy", "wag", "its tail in the doorway", False),

# TILE r2c0 - the wheat field, the ponies
("Yellow wheat field", [66.5, 0.0, 100.0, 11.0], "The yellow wheat field", "ripen", "in the summer sun", False),
("Scarecrow in the wheat field", [79.9, 3.1, 95.5, 9.1], "The scarecrow", "scare", "the cheeky crows away", False),
("Black crow above the scarecrow", [77.7, 6.1, 82.0, 9.1], "The black crow", "dive", "at the scarecrow's hat", False),
("Orange butterfly", [79.3, 1.8, 81.6, 3.4], "The orange butterfly", "flutter", "over the wheat field", False),
("Little blue bird in the field", [92.0, 9.2, 94.0, 10.7], "The little blue bird", "peck", "at the fallen grain", False),
("Brown pony", [70.2, 10.6, 83.7, 19.9], "The brown pony", "trot", "along the grassy path", False),
("Boy riding the brown pony", [70.7, 14.6, 77.8, 17.2], "The boy in the riding helmet", "ride", "the trotting pony", False),
("Black horse", [80.4, 17.5, 96.1, 27.3], "The black horse", "walk", "calmly out of the paddock", False),
("Woman riding the black horse", [76.7, 21.2, 88.6, 24.8], "The woman in the blue polo shirt", "ride", "the big black horse", False),
("Sheep resting on the grass", [70.7, 22.4, 75.2, 26.9], "The sheep by the fence", "rest", "in the shade on the grass", True),
("Molehills on the grass", [35.5, 68.0, 37.8, 74.0], "The little molehills", "dot", "the grass in front of the farm", True),

# TILE r2c1 - the rabbit pen
("Grazing sheep in the paddock", [74.9, 35.5, 79.0, 40.4], "The grazing sheep", "graze", "on the fresh green grass", False),
("Rabbit hutch with the red roof", [76.5, 24.5, 90.0, 36.1], "The rabbit hutch with the red roof", "house", "the rabbits and guinea pigs", False),
("Guinea pigs in the hutch", [80.9, 29.5, 85.8, 32.7], "The guinea pigs in the hutch", "squeak", "inside the wooden hutch", True),
("Toddler at the rabbit hutch", [83.1, 33.2, 90.2, 35.9], "The toddler at the rabbit hutch", "peek", "into the rabbit hutch", False),
("Bucket of carrots", [85.4, 36.3, 89.0, 38.2], "The bucket of carrots", "stand", "full of fresh carrots", False),
("Mother kneeling on the grass", [80.0, 42.4, 89.9, 46.2], "The mother in the striped top", "kneel", "next to the little boy", False),
("Girl holding the white rabbit", [84.4, 39.6, 90.2, 42.5], "The girl in the yellow dress", "hold", "a soft white rabbit", False),
("Little boy in the blue t-shirt", [84.2, 41.8, 89.9, 44.2], "The little boy in the blue t-shirt", "point", "at the grey rabbit", False),
("Boy crawling with the carrot", [90.0, 34.4, 94.1, 38.8], "The boy with the carrot", "crawl", "after the little rabbit", False),
("Brown rabbit on the grass", [93.3, 30.9, 95.5, 33.4], "The brown rabbit", "hop", "away from the boy", False),
("Grey rabbit", [91.2, 40.6, 94.1, 43.7], "The grey rabbit", "sniff", "at the orange carrot", False),
("Black and white guinea pig", [92.8, 43.5, 95.5, 45.9], "The black and white guinea pig", "scurry", "towards the girl's hands", False),
("Blue play tunnel", [94.2, 37.9, 98.3, 42.6], "The blue play tunnel", "lie", "on the grass for the rabbits", False),
("Girl reaching for the guinea pig", [89.8, 45.4, 96.5, 48.7], "The girl in the white headband", "reach", "for the little guinea pig", False),
("Blue wire fence of the rabbit pen", [89.3, 21.8, 100.0, 30.4], "The blue wire fence", "keep", "the rabbits safely inside", False),
("Fence around the pony paddock", [69.3, 35.5, 100.0, 64.5], "The long brown fence", "surround", "the pony paddock", False),

# TILE r2c2 - the farmyard
("Woman in the blue sun hat", [74.7, 54.3, 84.4, 57.9], "The woman in the blue sun hat", "watch", "the horses over the fence", False),
("Pink scooter", [69.5, 60.0, 77.9, 68.8], "The pink scooter", "wait", "in the middle of the farmyard", False),
("Girl sitting on the scooter", [65.5, 64.5, 77.9, 67.8], "The girl on the scooter", "balance", "the flower basket on her lap", False),
("Hydrangea in the basket", [65.6, 66.8, 72.5, 69.9], "The hydrangea plant in the basket", "bloom", "pink and purple", False),
("Woman in the green apron", [65.0, 68.5, 76.2, 72.2], "The woman in the green apron", "sell", "flowers from the farm", False),
("Mother in the pink t-shirt", [85.2, 52.5, 96.3, 55.9], "The mother in the pink t-shirt", "show", "the little girl the baby goat", False),
("Little girl in the red dress", [89.5, 54.9, 97.0, 57.3], "The little girl in the red dress", "reach", "up to pet the baby goat", False),
("Little goat kid", [89.0, 53.8, 93.0, 56.0], "The little goat kid", "snuggle", "in the woman's arms", False),
("Girl pushing the wheelbarrow", [81.9, 65.2, 90.2, 69.3], "The girl in the striped shirt", "push", "her friend across the yard", False),
("Boy in the wheelbarrow", [85.6, 67.4, 92.7, 71.1], "The boy in the wheelbarrow", "laugh", "as the wheelbarrow bumps along", False),
("Green wheelbarrow", [86.8, 66.0, 96.0, 71.5], "The green wheelbarrow", "bump", "across the farmyard", False),
("White hen flapping its wings", [85.8, 73.2, 90.3, 75.8], "The white hen", "flap", "out of the wheelbarrow's way", False),
("Brown rooster in the yard", [94.4, 75.5, 98.2, 78.2], "The brown rooster", "peck", "at the dusty ground", False),
("Bush with yellow flowers", [95.1, 56.5, 100.0, 61.0], "The bush with yellow flowers", "bloom", "at the edge of the yard", False),

# TILE r2c3 - the breakfast tables by the barn
("Farmer carrying the cheese", [68.2, 89.7, 81.6, 93.4], "The farmer in the green apron", "carry", "a whole wheel of cheese", False),
("Round yellow cheese", [72.6, 90.3, 75.3, 93.5], "The round yellow cheese", "smell", "delicious and fresh", False),
("Cow looking out of the barn", [70.2, 92.1, 79.2, 95.7], "The cow in the barn", "look", "curiously out of the barn", False),
("Red barn door", [64.0, 94.8, 80.0, 100.0], "The red barn door", "stand", "wide open beside the cow", False),
("Man eating the corn cob", [69.5, 76.0, 79.2, 79.2], "The man in the blue t-shirt", "bite", "into the yellow corn cob", False),
("Woman in the yellow blouse", [70.2, 83.3, 74.8, 86.0], "The woman in the yellow blouse", "chat", "with the whole family", False),
("Man in the red striped shirt", [72.8, 84.3, 80.6, 87.9], "The man in the red striped shirt", "drink", "a hot cup of coffee", False),
("Wooden picnic table", [74.2, 75.4, 82.5, 88.2], "The wooden picnic table", "stand", "in front of the barn", False),
("Silver kettle on the table", [74.2, 80.8, 77.2, 82.4], "The silver kettle", "steam", "next to the bread", False),
("Boy with the mug", [77.9, 81.2, 83.0, 84.2], "The boy with the mug", "sip", "his warm milk", False),
("Grandpa in the green vest", [77.9, 86.6, 83.9, 89.7], "The grandpa in the green vest", "tell", "stories at the table", False),
("Girl with the pinwheel", [84.9, 80.6, 89.7, 84.8], "The girl with the pinwheel", "spin", "her pink pinwheel", False),
("Girl with the black bob", [82.6, 84.6, 89.9, 87.2], "The girl with the black bob", "listen", "to grandpa's stories", False),
("Grandma waving at the table", [82.8, 89.1, 89.9, 92.8], "The grandma at the table", "wave", "her arm as she talks", False),
("Picnic table in the yard", [83.3, 79.3, 91.8, 93.7], "The picnic table in the yard", "hold", "all the cups and plates", False),
("Grey cat at the milk cans", [88.8, 96.6, 94.6, 99.0], "The grey cat", "try", "to reach the fresh milk", False),
("Milk churns by the barn", [89.8, 94.9, 94.1, 97.1], "The milk churns", "stand", "full of fresh milk", True),
("Basket of yellow flowers", [81.2, 97.7, 86.7, 100.0], "The basket of yellow flowers", "sit", "beside the barn wall", False),
("Rucksack under the table", [80.0, 75.3, 83.0, 77.5], "The rucksack", "wait", "under the picnic table", False),
]
